### ISSUE TITLE
As a user i can understand how to use the historian

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#1001]

**Comment by caroline-church** [comment]
@EdProsser Can you give an estimate for this please?

**Comment by EdProsser** [comment]
We currently don't really expose much of this to the user IIRC. I'd say that a high estimate would be one working week to get the docs done and ready for human consumption.

**Comment by markcastle3** [comment]
@EdProsser is this near to be closed out ?

**Comment by markcastle3** [comment]
#1853

**Comment by mbwhite** [comment]
# Historian and the REST API

The Historian records are available via REST API calls. These are very similar to REST APIs for interacting with other assets as the Historian Records are assets in the Historian registry.

Each HistorianRecord (defined in the system model file), is available by issuing GET calls : `system/historian` for all records, and a `system/historian/{id}` for a record with the specific transaction id.

Be careful issuing the all records call as this is not limited.

A transaction can currently be executed by issuing a PUT request. 
A GET call can now be made on each transaction to get all transaction record. or a GET specifing an ID to get a specific transaction.

By using a combination of the historian records, and the transaction records a complete picture of what assets have been modified by what transactions and by whom can be created. 

# Historian and the Client API
A change has been made to the client API such that there is no long a DefaultTransaction registry. 

Each transaction type now has it's own registry.  Therefore the call 
BusinessNetworkConnection.getTransactionRegistry() must take as a parameter the name of the transaction type.

**Comment by mbwhite** [comment]
@EdProsser   fyi - some extra notes above
