### ISSUE TITLE
ACL engine should resolve relationships for use in conditions

### ISSUE THREAD

**Issue by vinitesh** [hyperledger/composer#1007]
In permissions.acl , conditions can be defined on multi tier relationship of a resource or paticipants.
Like it should be able to evaluate properties of a relationship object.

## Context

asset CC identified by id{

o String id
-->Package package

}

asset Package identified by id{

o String id
--> Individual individual

}

participant Individual identified by id{

o String id 
}

rule cc {
description: "Allow the Individual Update access to CC"
participant(p): "org.model.Individual"
operation: READ
resource(r): "org.model.CC"
condition: (p.getIdentifier() == r.package.individual.getIdentifier())
action: ALLOW

} 

In the above context , 'r.package.individual.getIdentifier()'  should be evaluated and individual should have the access to cc objects that belongs to a package associated with him.

Currently conditions can only evaluate single tier relationship like  'r.package.getIdentifier()'

**Comment by shachisharma** [comment]
I am looking into this problem

**Comment by vinitesh** [comment]
Is there any progress on this enhancement?

**Comment by sstone1** [comment]
This got added ages ago in:
Allow ACL rules to resolve and navigate relationships #1468
Woohoo!
