### ISSUE TITLE
Model Collector Requires Test Support

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1026]
modelcollector.js (composer-common/lib/tools) is currently untested

## Context
Regressions could creep into the code

## Expected Behavior
Should the expected behaviour of the code functions change, a test should fail.

## Actual Behavior
No tests fail

## Possible Fix
Add testing support

**Comment by sstone1** [comment]
@dselman is going to `rm -rf` this.

**Comment by nklincoln** [comment]
code deleted ... this is now irrelevant
