### ISSUE TITLE
Composer common requires test extensions

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1027]
Code coverage items has now been broken into explicit separate issues and referenced.

Pending work remains in that composer-common requires test extensions to improve testing quality:
- [x] aclfile, should check returned json structure and validate test should check the response
- [x] aclrule, should check json structure and test validate response
- [x] model bindings should check constructed json instead of asserting not null
- [x] predicate should check constructed json instead of asserting not null
- [x] introspect/stringvalidator should check validate result
- [x] introspect/types should check validate result
- [x] introspect/validator should check validate result
- [ ] models/model could be broken down into component tests

Having run tests locally, it is possible to inspect code coverage in the Istanbul Coverage output, located in /packages/composer-common/coverage/html/index.html

Using the above file, it is possible to see exactly where the code is not being tested, and it is here where we should be trying to steer the testing.

## Context
Regressions could creep in if untested

## Expected Behavior
Tests fail if code broken

## Actual Behavior
No tests to fail

## Possible Fix
Add tests

**Comment by sstone1** [comment]
@nklincoln can you split this into chunks so we can hand them out please?

**Comment by nklincoln** [comment]
now completely broken down into separate tasks .. so closing this one.
