### ISSUE TITLE
Quickstart docs have extraneous backticks and incorrect Hyperledger references

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#1030]
https://hyperledger.github.io/composer/installing/quickstart.html

There are lots of extraneous backticks on this page, and also several times we refer to `Hyperledger v1.0`. There is no such thing - all instances need to be changed to `Hyperledger Fabric v1.0`.

**Comment by EdProsser** [comment]
Weird markdown bug. Fixed it.

**Comment by EdProsser** [comment]
Apparently once you've indented a column enough under an ordered list item it presumes it's a codeblock without requiring the normal ``` syntax.
