### ISSUE TITLE
Documentation on connection profiles to add V1 profile description

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1032]
Looking at the reference doc page
https://hyperledger.github.io/composer/reference/connectionprofile.html
provides some information about connection profiles but could be improved
- The connection profile shown is only for hlf v0.6 this should be stated
- We should include an example of hlf v1 including useful descriptions of each property
- There are some mistakes about where connection profiles are stored. We should state they are stored in the users home directory in a directory called '.composer-connection-profiles' (the dot is missing in places on the currently documented page). We could also give examples for linux and mac users to show the difference in home directory naming (note even on linux the home directories are not necessarily in the /home directory)
- We should state here as well that at this time no example for windows is provided because windows is not yet supported.
- There is a mistake describing the keystore property in the current documentation. The example given above it isn't a real directory and the description says `/home//` which isn't meaningful. We should present an example of a linux home directory at least.

I will add a description about V1 alpha 1 profiles as a comment soon

**Comment by davidkel** [comment]
The details here apply to connection to hlf v1 alpha 1 only.
A complete example of a v1 profile is as follows
```
{
    "type": "hlfv1",
    "orderers": [
        {
            "url": "grpcs://",
            "cert": ""
        },
        {
            "url": "grpcs://",
            "cert": ""
        }
    ],
    "ca": {
            "url:" "https://",
            "trustedRoots": "",
            "verify": true
    },
    "peers": [
        {
            "requestURL": "grpcs://",
            "eventURL": "grpcs://",
            "cert": ""
        },
        {
            "requestURL": "grpcs://",
            "eventURL": "grpcs://",
            "cert": ""
        }
    ],
    "keyValStore": "YOUR_HOME_DIR/.hfc-key-store",
    "channel": "mychannel",
    "mspID": "Org1MSP",
    "deployWaitTime": "300",
    "invokeWaitTime": "100"
}
```
- `type` is the connection type it must be `hlfv1` for connecting to HLF V1 alpha
- `orderers` is an array of objects which describe each orderer to communicate with, of the form shown above where `url` is the url of that orderer and `cert` is the appropriate certificate to use if you are connecting over tls (defined by using the protocol `grpcs://` rather than `grpc://`)
- `peers` is an array of objects which describe each peer to communicate with. Each peer will have a `requestURL` and `eventURL` and if tls is used will also need the appropriate TLS certificate defined in `cert`
- the `cert` field should be populated with the certificate string in pem format. This string is of the form 
```
-----BEGIN CERTIFICATE----- ... -----END CERTIFICATE-----
```
note that this pattern could be repeated multiple times if more than one cert is required and all that information needs to be stored in the field
- keyValStore defines the location for storing ecerts and user information. For alpha 1 it must be the directory '.hfc-key-store' in your home directory.
- channel is the channel defined in your fabric where the business network is to be deploy or is already deployed to. The channel needs to already be defined in the fabric itself and is not something that composer sets up.
- mspid is the mspid of your organisation. It will be associated with the enrollment id that you will use to interact with the business network.
- deployWaitTime (Optional) is the time to wait for a response before timing out attempting to deploy a business network
- invokeWaitTime (Optional) is the time to wait for a response before timing out when invoking a transaction or making a query request.

There is also a simplified version of the above if you don't need to use TLS or if you don't need the trustedRoots and verify options of the ca definition
```
{
    "type": "hlfv1",
    "orderers": [
        "grpc://localhost:7050"
    ],
    "ca":"http://localhost:7054",
    "peers": [
        {
            "requestURL": "grpc://localhost:7051",
            "eventURL": "grpc://localhost:7053"
        }
    ],
    "keyValStore": "YOUR_HOME_DIR/.hfc-key-store",
    "channel": "mychannel",
    "mspID": "Org1MSP",
    "deployWaitTime": "300",
    "invokeWaitTime": "100"
}

```

**Comment by davidkel** [comment]
We should also note that this profile is currently subject to change while HLF V1 is still in alpha/beta

**Comment by bjdzliu** [comment]
Thank you for your description. I've just gotten some cert question:,
1 What is the format of multiple certs for peer or order?
2 ca-cert and server-cert need  to  be filled in conf ? 
For my example:
orderers is using these cert: ca0-cert.pem (root cert) and  cert0.pem(server cert)
peer1  is using these cert: ca-cert.pem (root cert) and  cert1.pem(server cert)
peer2  is using these cert: ca-cert.pem (root cert,same as peer1 ) and  cert1.pem(server cert)

My order has two certs,What is the Internal Field Separator between them?

I notice the issue https://github.com/hyperledger/composer/issues/893 , that tell me  i should delete the \r\n in my cert. Is't correct?
    "orderers": [
        {
            "url": "grpcs://orderer0-1494331223:7050",
"cert": "-----BEGIN CERTIFICATE-----MIIB7jCCAZSgAwIBA...-----END CERTIFICATE----------BEGIN CERTIFICATE----MJSU&WHSUSS-----END CERTIFICATE",

**Comment by davidkel** [comment]
@bjdzliu I believe there is an rfc that defines the order for certificates in pem format. As an example doing a google search provided the following
https://serverfault.com/questions/476576/how-to-combine-various-certificates-into-single-pem

**Comment by davidkel** [comment]
Looks like the V0.6 connection profile page has gone from the website now. We should re-instate it along with V1.
Depending on when we release the new version of the hlf v1 connector we will want to include them and I will document them here

**Comment by sstone1** [comment]
This looks like it has been done, please reopen if you disagree.
