### ISSUE TITLE
Cannot scroll to the bottom of data model if 100+ fields

### ISSUE THREAD

**Issue by harrika1982** [hyperledger/composer#1038]
## Context
When you have 115+ fields in the asset model you can't see them all in the test space on the playground. You have to hit edit to see the whole entry. A user should be able to scroll down to see all the fields to check to make sure the information is correct. 

## Expected Behavior
When you have an asset with a very large data model you should be able to scroll down to see all the fields but it seems to only be possible through the edit field. 

## Actual Behavior
See attached picture

<img width="741" alt="screen shot 2017-05-17 at 4 25 00 pm" src="https://cloud.githubusercontent.com/assets/15254733/26205170/f92a0f18-3bae-11e7-8481-f469b609959a.png">

**Comment by winslet** [comment]
@caroline-church looks like its a bug on the expand (can we set a larger max-height?) the collapse is working great 👍 ima tag you on behalf of Kathryn as you have the understanding here.

**Comment by winslet** [comment]
@markcastle3 could we make a call on whether we would like to push this into production before next week?

**Comment by markcastle3** [comment]
@winslet i believe the call is to wait for the next scheduled release which is the end of next week.

**Comment by winslet** [comment]
yeah chatted with @caroline-church yesterday and forgot to update this - it seems we will have to do a rethink of the expand module and remake it in JS not just CSS to get this to work at extreme scales.

**Comment by caroline-church** [comment]
done so closing
