### ISSUE TITLE
Top navigation updates

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#1041]
Show current connection profile and include a popover menu to switch or manage identities.

There is already an item in the playground component wishlist #649 for a suitable popover menu and an initial design...

![image](https://cloud.githubusercontent.com/assets/3535067/26057152/3429c2ca-3970-11e7-85ed-a387ba1dff03.png)

Tagged this with design since I think there are discussions around exactly how this should work, e.g. whether the connection profile should get a similar menu.

**Comment by Tobias-Hunter** [comment]
Closing: With the #902 work this will be implemented differently.
