### ISSUE TITLE
As a user, I can ensure the privacy and security of assets and transactions

### ISSUE THREAD

**Issue by rfu2k** [hyperledger/composer#1043]
Currently access control is available that enforces which users can create or manipulate data elements in the business network. As a user I want the additional ability to ensure that confidential transaction information at the data level is only available to participants who were part of that transaction. 

For example, in a business network with participants A, B, and C - a transaction between participants A and B with confidential data should be protected in such a way that C is not able to read and understand that confidential data if it is retrieved from underlying data level, e.g. shared ledger, world state.

**Comment by dklesev** [comment]
my notes on this are:

### Data Access Restriction by Encryption

**Description:**

> As a transaction participant, I need the guarantee that the data is encrypted and only transaction participants or trusted parties can decrypt it.

**Explanation:**

> Three parties exists: A, B, C
> Each party has its own peer instance so the whole ledger is consistent and updated on all peers.
> When party A transfers an asset to party B, only this two participants can read transaction data even the whole transaction is commited and synchronised among all peers.
> If party C tries to decrypt data, it can’t retrieve any meaningful information but garbage.

**Possible solution:**

> As per transaction, the publisher generates a unique symetric key which can be shared with other transaction participants or access granted parties.

**Problems:**

- Complex queries are maybe not possible
- Performance issues
- Scalability aspects


### Temporal Data Access

**Description:**

> As a data owner, I want to grant only temporary reading access to some of my (encrypted?) ledger information (assets).

**Explanation:**

> Three parties exists: DataOwner, Auditor and Supplier 
> DataOwner wants his information to be shared with other parties but some parts (assets) can only be accessed temporary and are encrypted by default and restricted only to the DataOwner.
> Common secret share is not an option.
> Restricting data access by ACL or asset access date limitation field is not an option.
> F.e. an Auditor requests the information which workers (name, id …) were involved in which manufacturing processes for a given asset or time period.

**Possible solution:**

> A read query by the requesting party peer can be approved by DataOwner peer. Then the peer decrypts the data (or some fields) and returns it to the requesting party peer.

**Problems:**

- Performance issues
- Scalability
