### ISSUE TITLE
Enable O-Auth doc is out of date with code

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1050]
It would appear that the page https://hyperledger.github.io/composer/managing/github-oauth.html has been victim to an un-tracked code shuffle behind the scenes. The result is unfortunately that the documentation to enable something, is not possible to action.

This files no longer live under composer-connector-server, but have been moved to composer-playground-api (same directory of config and same name file)

Only change required is that of the directory.

**Comment by EdProsser** [comment]
Done, will go into next PR.
