### ISSUE TITLE
Better 404 Error Page

### ISSUE THREAD

**Issue by Tobias-Hunter** [hyperledger/composer#1053]
Currently the 404 in the Playground is:
![image](https://cloud.githubusercontent.com/assets/25635381/26313458/e48375de-3f02-11e7-980b-46a92d2ce3a4.png)
& for the Docs:
![image](https://cloud.githubusercontent.com/assets/25635381/26313402/b09ad212-3f02-11e7-899c-f1e3785d06a7.png)
Suggested:
![image](https://cloud.githubusercontent.com/assets/25635381/26313430/c5feb236-3f02-11e7-91a2-e55ad3a78284.png)

Assigning @winslet for Hi-Fis 🚀

**Comment by winslet** [comment]
Initial pass: 

![image](https://cloud.githubusercontent.com/assets/13980028/26317446/6102c356-3f0f-11e7-8182-a378854ed1d5.png)

We probably need to have a conversation about the wording on this page...

**Comment by winslet** [comment]
done - released in 0.7.3
