### ISSUE TITLE
File '/home/composer/.composer-credentials' not found when starting composer-playground from macOS terminal

### ISSUE THREAD

**Issue by l2fprod** [hyperledger/composer#1056]
I've installed composer-playground with `npm install -g composer-playground`.

The install went fine, compiling all native code.

```
node -v
v6.9.1
```

```
macOS 10.12.4
```

When I start the composer-playground I get:

![image](https://cloud.githubusercontent.com/assets/12746550/26317082/9822447c-3f16-11e7-87ac-17b87fd63795.png)

**Comment by dselman** [comment]
Please follow the instruction here:
https://hyperledger.github.io/composer/tutorials/getting-started-playground.html

To install and run Playground locally.

**Comment by l2fprod** [comment]
@dselman of course I did follow this page and the docker instructions worked perfectly

But these instructions https://hyperledger.github.io/composer/tutorials/getting-started-playground.html#installnpm led to this error message.
