### ISSUE TITLE
When creating a new hlfv1 connection profile in composer-playground Pressing Enter cancels the process.

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1057]
I want to create a new HLF V1 connection profile so I bring up the form that allows me to enter the various details such as orderer/ca/peer etc. 
I enter the details (note that the save button is highlighted in blue) and press enter.
## Expected Behavior
It should save the profile

## Actual Behavior
It cancels the profile creation and returns to the previous screen.

**Comment by caroline-church** [comment]
done so closing
