### ISSUE TITLE
Getting Started for HLFV1 blocks user with unknown profile use

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1061]
If a user is following the getting started guide, and then moves onto the tutorials, there is an option to have checked out the hlfv1 versions of the samples.

At the point where a user has created a new BNA, and wishes to update/deploy the archive, the command will fail because behind the scenes the 0.6 profile is being used.

It is necessary for a user to change the profile being used in order for the hlfv1 item to work. This is done via:

`composer network update --archiveFile <blah>.bna -p hlfv1 -i admin -s adminpw`

This will swap the profile being used. If the profile is not swapped, the update/deploy will fail with unhelpful error messages - the new user needs to know to swap the profile.

## Context
Following the getting started path and tutorials for hlfv1 items reaches a failure point that is undocumented

## Expected Behavior
Should be able to follow tutorial with out being blocked

## Actual Behavior
Deploy fails with unhelpful error messages.

**Comment by sstone1** [comment]
@nklincoln is this still relevant with the new getting started guide? Can you retest please?

**Comment by sstone1** [comment]
Closing as no response 😉
