### ISSUE TITLE
Load times are super slow on Web Playground but with limited understanding to why

### ISSUE THREAD

**Issue by winslet** [hyperledger/composer#1063]
## Context

We have noticed now that the load times for the Web Playground (http://composer-playground.mybluemix.net) can sometimes reach 10+ seconds on a cold load. We should try and work out why this is such a large amount of time and see if we can optimise what we are loading in to reduce it. 

## Analysis

Some basic analysis from Chrome devtools:

<img width="1551" alt="image" src="https://cloud.githubusercontent.com/assets/13980028/26357994/fb965bee-3fc8-11e7-9976-4ad7767d5227.png">

We seem to be loading in 3 large .js files:

1. polyfills.1381732ff68fda37fdc5.bundle.js (could this be the icons @caroline-church? )
2. vendor.e4848d04a3b13649e6d2.bundle.js
3. main.217aa03d7dc94f5a7c56.bundle.js

<img width="298" alt="image" src="https://cloud.githubusercontent.com/assets/13980028/26358930/fc246206-3fcb-11e7-8da5-33a74a3e15b4.png">

<img width="295" alt="image" src="https://cloud.githubusercontent.com/assets/13980028/26358954/094ca4ac-3fcc-11e7-984c-08742a824aae.png">

<img width="297" alt="image" src="https://cloud.githubusercontent.com/assets/13980028/26358963/0b7f0c38-3fcc-11e7-9199-4a909c9f3729.png">

The other interesting graph is:

<img width="324" alt="image" src="https://cloud.githubusercontent.com/assets/13980028/26359126/8451cc0e-3fcc-11e7-9e2a-c6840f37b8a0.png">

This suggests we are waiting for 6 seconds doing nothing? (im not totally sure about this).

## Possible Fix

Chrome has some suggestions on how we could optimise the js:

<img width="784" alt="image" src="https://cloud.githubusercontent.com/assets/13980028/26359201/bc5b72b2-3fcc-11e7-8141-fa2db1a4e00a.png">

**Comment by winslet** [comment]
Further investigation:

It seems we are doing a `ng build -prod` build for the online playground which means they have already been reduced in size (this would have been an easy win). 

Having just built the playground locally I get this for the summary of load time (compare to the above):

![image](https://cloud.githubusercontent.com/assets/13980028/26361754/e04e5ee4-3fd3-11e7-8ae0-ba95c6a3b210.png)

What is noticeable is that the thing that has been removed is the "idle" time - im not sure of the implications of this yet, but it could suggest server side changes needed?

**Comment by jt-nti** [comment]
Something we could probably do to make it appear to be loading faster is to move the splash screen to the loading screen while the rest of the application loads. See also #1379
