### ISSUE TITLE
As a playground user i can connect to Fabric v1next (beta1)

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#1064]
To connect to fabric-alpha-2 the following fields need to be added/changed to the connection profile in the playground

- [ ] DeployWaitTime and InvokeWaitTime should just be one field called timeout

- [ ] Certificate Authority needs to have a url and name property

**Comment by davidkel** [comment]
Split this into 2 issues (see #1100) as this is the minimum we need to support alpha2.
