### ISSUE TITLE
sample applications for hlfv1 needs a travis build

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1068]
I'm unsure when we plan to cleanup our sample applications but until we do I think it would be a good idea to have a travis build of the sample applications for hlfv1 running to check pull requests as we don't have one at the moment.

**Comment by dselman** [comment]
@mbwhite will this be redundant when we move to a merged getting started?

**Comment by sstone1** [comment]
This will be redundant when the merged getting started work goes in, otherwise that has failed 😉
