### ISSUE TITLE
0.7.2: AssetRegistry.getAll() does not resolve to an array of resources as documented

### ISSUE THREAD

**Issue by sanjay-saxena** [hyperledger/composer#1069]
The API documentation of `AssetRegistry.getAll()` method say this about the return value:

```
Returns:

A promise that will be resolved with an array of {@link
Resource} objects when complete, or rejected with an error.
```

Also, [assetregistry.js](https://hyperledger.github.io/composer/jsdoc/composer-runtime_lib_api_assetregistry.js.html) shows the usage of the `getAll()` method as shown below:

```
        /**
         * Get a list of all of the existing assets in this asset registry.
         * @example
         * // Get the vehicle asset registry.
         * return getAssetRegistry('org.acme.Vehicle')
         *   .then(function (vehicleAssetRegistry) {
         *     // Get all of the vehicles in the vehicle asset registry.
         *     return assetRegistry.getAll();
         *   })
         *   .then(function (vehicles) {
         *     // Process the array of vehicle objects.
         *     vehicles.forEach(function (vehicle) {
         *       console.log(vehicle.vehicleId);
         *     });
         *   })
         *   .catch(function (error) {
         *     // Add optional error handling here.
         *   });
```
In my simple network definition, I don't use any ACLs. So, there is no issue of permissions involved. Since `Registry` does not expose a method to retrieve the current size, I am trying to use the following code, along the lines of the code snippet in assetregistry.js, to compute the size of the AssetRegistry:

```
/**
 * Creates a new task.
 * @param {org.example.collab.todolist.CreateTask} txn -- the CreateTask transaction
 * @transaction
 */
function onTaskCreation(txn) {
    var assetRegistry = null;

    return getAssetRegistry(TASK)
          .then(function(taskAssetRegistry) {
              assetRegistry = taskAssetRegistry;
              assetRegistry.getAll();
          })
          .then(function(tasks) {
              var len = 0;

              tasks.forEach(function(task) {
                  len++;
              });
              var taskId = 'Task-' + len++;
              ...
           });
```
When I try to submit `CreateTask` transaction in the `Composer Playground`, I see the following error:

```
TypeError: Cannot read property 'forEach' of undefined
```

## Context
See above.

## Expected Behavior
The promise returned by `getAll()` method should resolve to an array.

## Your Environment
* Version used: 0.72
* Environment name and version (e.g. Chrome 39, node.js 5.4): Composer Playground in Chrome
* Operating System and version (desktop or mobile): macOS 10.12.1
* Link to your project:

**Comment by dselman** [comment]
Array.forEach is not part of ES5 Javascript:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach?v=control
https://stackoverflow.com/questions/9329446/for-each-over-an-array-in-javascript

**Comment by sanjay-saxena** [comment]
I was following the pattern from the sample code snippet in [assetregistry.js](https://hyperledger.github.io/composer/jsdoc/composer-runtime_lib_api_assetregistry.js.html). Note that parameter `tasks` passed in the function is not getting resolved so I couldn't even print the output of `tasks.toJSON()` to the console.

**Comment by sstone1** [comment]
You are missing a return statement:

'assetRegistry.getAll();'

Should be:

'return assetRegistry.getAll();'

**Comment by sanjay-saxena** [comment]
Oops! Silly me :) Still trying to get used to JS and Promises.
