### ISSUE TITLE
composer-rest-server hangs against Bluemix Blockchain service (v0.6)

### ISSUE THREAD

**Issue by ibmamnt** [hyperledger/composer#1080]
composer-rest-server hands in the following condition.
   1.  Initiate rest api call operation after 5 minutes of idle times.
   2. Run Post operation twice within a second.

## Context
- Composer Client Version:
  composer-cli @0.7.2
  composer-rest-server @0.7.2
  Composer runs on Docker images (both local and Bluemix container service)

- Fabric:
   Bluemix Blockchain service.

## Expected Behavior
   No crash is expected.

## Actual Behavior
1.  composer-rest-server issue the following error and hangs
```events.js:160
throw er; // Unhandled 'error' event
^
Error: {"created":"@1495591568.993681036","description":"Secure read
failed","file":"../src/core/lib/security/transport/secure_endpoint.c","file_line":
157,"grpc_status":14,"referenced_errors":
[{"created":"@1495591568.993668691","description":"OS Error","errno":
104,"file":"../src/core/lib/iomgr/tcp_posix.c","file_line":
229,"os_error":"Connection reset by peer","syscall":"recvmsg"}]}
at ClientDuplexStream._emitStatusIfDone (/usr/local/lib/node_modules/
composer-rest-server/node_modules/grpc/src/node/src/client.js:189U19)
at ClientDuplexStream._receiveStatus (/usr/local/lib/node_modules/
composer-rest-server/node_modules/grpc/src/node/src/client.js:169U8)
at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/
src/node/src/client.js:634
```
 Note that this is known behaviour when hfc is used against Bluemix environment.

2.  composer-rest-server issue the following error and hangs.
```
events.js:160
throw er; // Unhandled 'error' event
^
Error
at ClientDuplexStream._emitStatusIfDone (/usr/local/lib/node_modules/
composer-rest-server/node_modules/grpc/src/node/src/client.js:189J19)
at ClientDuplexStream._receiveStatus (/usr/local/lib/node_modules/
composer-rest-server/node_modules/grpc/src/node/src/client.js:169J8)
at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/
src/node/src/client.js:634
```

## Possible Fix

1, composer-rest-server should "ping" to Hyperledger Fabric every 3 minutes. Note that gRPC has 5 minutes timeout by default. grpc_status = 14 means client needs to retry to connect to gRPC server. This is kind of keep alive operation (still happens in v1.0), and work around used in many projects.

2, This is not known problem. But composer-rest-server should not handle "post" when one is already in the queue. (Situation may change in v1.0, but Bluemix does not provide v1.0 "test" service yet.

## Steps to Reproduce
1.   Create Blockchain service on IBM Bluemix
2.   Deploy sample "CarAuction" business network to the environment created in step 1.
3.   Build composer-rest-server image with connection profile to connect to the Bluemix env.
4.   Run the Docker image locally.
5.   Open explorer  (e.g http://localhost:3000) for direct Swagger operations against Fabric.
 
For problem 1
6.  Run Post operation, and wait more than 5 minutes, and then run Post operation again.

For problem 2
7. Run Post operations within 1 seconds (i.e. twice)

## Existing issues
None found so far.

## Context
 The project cat not release the product within a given time frame (end in the end of June) because of this problem.

## Your Environment
 -  Docker latest on MacOS Sierra

**Comment by dselman** [comment]
These both look like a symptom of the event hub disconnect issue that the Hyperledger Fabric team are working on.

Related issues:
https://jira.hyperledger.org/browse/FAB-4002
https://jira.hyperledger.org/browse/FAB-3310
https://jira.hyperledger.org/browse/FAB-2436

I don't think there is anything we can do about this at the Composer level.

**Comment by ibmamnt** [comment]
I understood the issue. Normally, we work around the application level "ping" operation for keep alive for now (e.g. implement 3 minutes ping operation against Hyperledger fabric). Is it possible to implement this feature for immediate work around ?

**Comment by dselman** [comment]
Because this is related to the event hub, you would have to submit a transaction that emitted an event to keep the connection alive. We hope to deliver the ability to emit events from Composer today (in version 0.7.3).

**Comment by ibmamnt** [comment]
Oh, I see. I also hope to catch the error in the code such that this is known issue (it should be possible to parse grpc == 14), and continue to process in stead of hang (e.g. stop running).  I'll ask user to try 0.7.3 anyway to obtain new feedback.

**Comment by sstone1** [comment]
This is being tracked under the following Fabric issues:

https://jira.hyperledger.org/browse/FAB-4002
https://jira.hyperledger.org/browse/FAB-3310
https://jira.hyperledger.org/browse/FAB-2436

There is nothing that Composer can do about this, please direct all queries to the Fabric team.
