### ISSUE TITLE
Composer not generating enums in Swagger for model enums

### ISSUE THREAD

**Issue by gcharters** [hyperledger/composer#1083]
## Context
The Vehicle Lifecycle Network uses enums, for example, to describe the taxation class:

enum TaxClass {
  o PRIVATE_LIGHT_GOODS
  o PETROL_CAR
  o DIESEL_CAR
  o ALTERNATIVE_FUEL_CAR
  ...
}

These don't make it through to the Swagger as enums, they're typed as plain strings.  The swagger would be much more usable if these were enums.  For example:

            "taxationClass": {
              "type": "string",
              "enum": [
                "PRIVATE_LIGHT_GOODS",
                "PETROL_CAR",
                "DIESEL_CAR",
                "ALTERNATIVE_FUEL_CAR",
                ...
              ]
            }

## Expected Behavior
Enums in the Swagger

## Actual Behavior
Strings in the swagger

## Possible Fix
Generate enums in the Swagger :)

## Steps to Reproduce
1.  Deploy the Vehicle Lifecycle Network sample
2.  View the Swagger for taxationClass in VehicleDetails.

## Existing issues
- [ x] [GitHub Issues](https://github.com/hyperledger/composer/issues)
None found

## Context
My generate Java client is difficult to use as I need to view the model files to know the valid values.

## Your Environment

* Version used: hlfv1 + composer 0.7.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): node.js 6.9.5
* Operating System and version (desktop or mobile): Ubuntu 16.04 TLS
* Link to your project: N/A

**Comment by sstone1** [comment]
So the reason this doesn't work already is because the LoopBack model schema documentation does not refer to enumerations at all - try searching for `enum` on this page:
http://loopback.io/doc/en/lb3/Model-definition-JSON-file.html

However if we add an `enum` property then it appears in the Swagger 🤦‍♂️ 

Will get this delivered!

**Comment by sstone1** [comment]
Fixed in v0.7.4.
