### ISSUE TITLE
Filtering does not work with Loopback generated REST APIs

### ISSUE THREAD

**Issue by sanjay-saxena** [hyperledger/composer#1087]
Using 0.7.2, I was able to generate the Angular2 app and the REST APIs. Once I executed `npm start` from the newly generated `angular-app` folder, I was able to play with at the REST APIs by pointing the browser to the Loopback Explorer at `localhost:3000/explorer`. 

Since I had populated the world state using a bootstrap transaction,  I am able to  retrieve **ALL** the assets by exercising `GET /Task` API in the Loopback Explorer or by pointing the browser to `http://localhost:3000/api/Task`.

However, if I want to filter the assets/tasks using one of the model attributes say `{"taskId":"Task-1"}`, then the response still includes **ALL** the tasks instead of just `Task-1`. In this case, the encoded URL looks like this -- `http://localhost:3000/api/Task?filter=%7B%22taskId%22%3A%22Task-1%22%7D`.

## Expected Behavior
JSON response should only include the filtered asset that matches the criteria.

## Actual Behavior
JSON response includes all the assets. The filter is not being applied.

## Your Environment
* Version used: Composer 0.7.2; Fabric 1.0.0-alpha1
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome, Node v6.10
* Operating System and version (desktop or mobile): macOS 10.12.1
* Link to your project: https://github.com/sanjay-saxena/todolist-network

**Comment by dselman** [comment]
This feature is not yet supported (the world state is in a key-value store, so there is no way to efficiently implement this). We are working on support for complex queries under the Query Epic and #990 which will require a moving to storing world state in CouchDB.
