### ISSUE TITLE
AddFile Modal style needs fixing for correct rendering on firefox

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1089]
The AddFile modal is not rendering correctly on firefox and resulting in badly structured component.

## Context
The visual aspect could be improved for the browser

## Expected Behavior
It should look the same across all browsers

## Actual Behavior
On firefox, sections overlap

## Steps to Reproduce
Spin up composer
Navigate to url using firefox browser
Add file
Observe layout

**Comment by caroline-church** [comment]
done so closing
