### ISSUE TITLE
Empty business network does not include an acl file

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1090]
If a user selects to start from an empty business network definition, there is no ACL file provided to edit, and no way of using the playground to import one.

The current work around is to export what they have, input the acl file manually, and then import their BNA.

An empty ACL file should be provided within the empty business network definition and/or it should be possible to add an ACL file via the Playground

## Possible Fix
1) Add ACL file to empty business network
2) Enable the addition of an ACL file through the AddFile action

**Comment by EdMoffatt** [comment]
So, this one sort of slipped through the cracks :)  I'd suggest that ReadMe and ACL files should behave in a very similar way i.e.

- There should always be one.
- If we import a network that doesn't have one, we should create an "empty" one.
- The empty ones should have some more info in them!
   - Perhaps the empty ReadMe could include info on where to find our docs?
   - Perhaps the "empty" ACL could include something to help a user understand the syntax?  Maybe a comment block at the top, which could also reference where the docs on ACLs live?  That'd be super-ace ;)
- We shouldn't offer the ability to create an empty one from within the "Add File" dialog
- If the user drags one in to import it, we should handle that "gracefully"
   - In the case of a ReadMe, I think we should warn them "this will replace your current ReadMe"
   - For now, I think the behaviour should be the same for an ACL.  This could change later if we come up with a reason to have multiple ACL files, but for now lets not add the complication of multiple ACLs and therefore ordering of files being important ;)

**Comment by winslet** [comment]
Update following new functionality:

ACL files can now be added but there is still only a readme when the empty network is imported. I agree with the ideas that Ed has put above.

**Comment by jt-nti** [comment]
There is now an ACL in the empty business network as a result of #2313
