### ISSUE TITLE
Composer will delete any malformed function or resource upon switching from the 'Define' to 'Test' tab or swapping file

### ISSUE THREAD

**Issue by pastadin** [hyperledger/composer#1097]
Name is self explanatory.

To Recreate:

1. Open Playground
2. Add the following asset:
```
assetz Thing identified by x {
	o String x
}
```
3. Swap to another file or from Define to Test
 
Alternate:
2. Add the following function: 
```
fucntion foo(bar) {
  	return bar.doAThing();
}
```
3. Swap to another file or from Define to Test

4. The function/asset is now gone

**Comment by sstone1** [comment]
Duplicate of Playground should warn a user if they navigate from "Define" without deploying #922.
