### ISSUE TITLE
Plan a Playground Tour

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1099]
Linked to #912 

Eventual goal is to have a tour that can be launched in the web Playground, which takes a new user through the key features of Composer, using Playground as an exploration and learning tool.  @mahoney1 has proposed using Hopscotch for this: http://linkedin.github.io/hopscotch/
We're not planning to tackle that all in one go though.  Instead, here are some initial tasks:

- [x] List out the Hopscotch bubbles we would like to appear for this tour: this can be just bullet-points in Git wiki for now, and should tell us what we would show a new user when they first access Playground (if they're the sort of user who wants to take the tour of course :)  I'd like @Tobias-Hunter to take ownership of this and get a first proposal down, then share the link on this issue so that others can weigh in!
The tour should end with something like "Developers can learn how to get a local Composer setup by clicking on this here "Get Local Version" link".

- [ ] Screen-recording of going through the steps in that tour.  We'll put this up on YouTube.  Again, gonna dump this one on @Tobias-Hunter ;)

- [x] Low-fi mockup to show: if a user visits the web Playground...  Where would we present the offer to take a tour?  (Another one for @Tobias-Hunter )

- [ ] Prove that it's possible to get Hopscotch working in web Playground (not building the full walkthrough at this stage, just showing we can pop up some test bubbles!) - this one's for @mahoney1 to investigate!

**Comment by Tobias-Hunter** [comment]
Initial Low-Fi thoughts on the Playground Tour & how the user could initiate this tour, we should also provide a way for the user to initiate a tour even if they didn't want to first time around!

![image](https://cloud.githubusercontent.com/assets/25635381/26681291/8b58a1b2-46d4-11e7-9bbc-9e5a25458f6e.png)
![image](https://cloud.githubusercontent.com/assets/25635381/26681232/529f87f0-46d4-11e7-9df4-d85c1baf91cd.png)
![image](https://cloud.githubusercontent.com/assets/25635381/26681252/5df7808a-46d4-11e7-942a-7c7326f24dc7.png)

**Comment by Tobias-Hunter** [comment]
The order for points in the tour, note this is not the script for the video!

https://ibm.box.com/s/deg6uyn6hnc2cr3uayhed0ukrgczmmfj

**Comment by Tobias-Hunter** [comment]
Having recorded the audio, I would like to do another recording for this & then re-record the video! 🚀

**Comment by EdMoffatt** [comment]
Just had a thought that we could tie this in with #657 - so for example, when the Basic Sample Network is selected in the Import Catalogue:
![image](https://user-images.githubusercontent.com/7454304/26870251-51606318-4b67-11e7-8eaa-81a45ad56d3e.png)
We could offer "Deploy and start Tutorial" as the button and then a smaller link to "Just deploy: skip Tutorial".
What do you think, @Tobias-Hunter ?

**Comment by mahoney1** [comment]
@Tobias-Hunter @EdMoffatt So had a prelim discussion with @Jakeeyturner on this. It would seem (for the Playground tour) that it should ideally be an Angular 2 tour module (ie whatever tour choice is used eg "import TourNG2BootstrapModule"). Hopscotch tour is good for 'static' HTML content, but for the Playground app we might need an NG2 tour module and added to the [root?] app component or similar.

**Comment by Tobias-Hunter** [comment]
![image](https://user-images.githubusercontent.com/25635381/27025376-2e4b63d4-4f52-11e7-83a5-ac99fae4982b.png)
![image](https://user-images.githubusercontent.com/25635381/27025280-dd05e5f8-4f51-11e7-863d-dcfdf2465d60.png)
If the catalogue was introduced, this was how I had imagined the initiation of the tour. So the Welcome page would allow the user to take the tour or choose a sample, if the user chooses to take a tour then we would import the basic sample business network. A tour stop would be Import/Replace & this could be a good end point as well as saying "Get local version" here! @EdMoffatt @mahoney1

**Comment by Tobias-Hunter** [comment]
![playground tutorial](https://user-images.githubusercontent.com/25635381/27440193-e7378e42-5761-11e7-9308-0858d530691c.gif)

A really simple way we could use our tutorial at the moment could be this, in the Splash Screen modal provide a **Follow the tutorial** button, this would then open the playground & then in another tab open up the tutorial! 🎈

**Comment by EdMoffatt** [comment]
Just leaving a quick comment to reference #1379 

That one is going to do an initial introduction of the option to "Open Tutorial", which to start with will just open up the docs tutorial in a new tab.  That behaviour we can then hopefully replace with the tour once we have it!

**Comment by winslet** [comment]
@KaiUsher I know you were keen to have a look at doing something like this, could you put your thoughts in here?

**Comment by sstone1** [comment]
As far as I know, nobody is working on this at the moment or planning to work on it, so closing. 
If somebody wishes to work on this in the future, then please reopen this issue or open a new issue.
