### ISSUE TITLE
As a playground user I want to be able to configure new settings in HLF v1.0

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1100]
There are optional new fields to connect to fabric-alpha-2 the following fields need to be added to the connection profile support in the playground
- [ ] sendMessageSize (a value specified in megabyes). It needs to be a number not a string
- [ ] receiveMessageSize (a value specified in megabyes). It needs to be a number not a string
- [ ] commonCert  - this should be the actual certificate object not a path to it

**Comment by caroline-church** [comment]
@davidkel @nklincoln Is this still needed or can we close this issue?

**Comment by nklincoln** [comment]
@caroline-church @davidkel  - is this to go in still?

**Comment by sstone1** [comment]
Closing, we don't need this in the playground. As part of the common connection profile work that @caroline-church is working on, we'll be able to import and use any valid Fabric connection profile. Settings like message size are an advanced feature.
