### ISSUE TITLE
Update wiki to include tutorial for creating a hyperledger fabric v1 composer solution

### ISSUE THREAD

**Issue by uchibeke** [hyperledger/composer#1101]
***Issue is fixed in https://github.com/uchibeke/composer-wiki/issues/1. It just needs to be merged***

The tutorial for Creating a Hyperledger Composer Solution in https://github.com/hyperledger/composer/wiki/Tutorial-2 does not work for Hyperledger fabric v1. 

## Context
The commands for deploying a business network locally will not work for hlfv1 because the `-p` option is not specified in the tutorial

## Expected Behavior
For v1, this is what works: 

`composer network deploy --archiveFile basic-sample-network.bna  -p hlfv1 -i admin -s adminpw`
  - basic-sample-network.bna: The .bna file in the cwd
  - hlfv1: The connection profile to use
  - admin: The user name of the admin is `admin`

You can verify that the network has been deployed by typing:

`composer network ping -n my-network -p hlfv1 -i admin -s adminpw`
  - my-network: The name of the network to test
  - admin: The user name of the admin is `admin`
  - adminpw: The password of the user admin 

## Actual Behavior
`composer network deploy -a my-network.bna -i admin -s Xurw3yU9zI0l`

`composer network ping -n my-network -i admin -s Xurw3yU9zI0l`

## Possible Fix
I have added a new wiki page adapted from the current wiki page. Wiki page that fixes this issue is https://github.com/uchibeke/composer-wiki/blob/master/Composer-Solution-For-v1.md in https://github.com/uchibeke/composer-wiki

## Steps to Reproduce
1. Start an instance of hlfv1
2. Follow tutorial, https://github.com/hyperledger/composer/wiki/Tutorial-2, to create a new business network
3. Tutorial will not work for hlfv1 

## Context
Found issue while trying to set up a local business network

## Your Environment

* Version used: Hyperledger Fabric v1
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version: Mac Os X
* Link to your project:  Updated solution can be found in https://github.com/uchibeke/composer-wiki

**Comment by dselman** [comment]
Tutorial has been updated to v1 and merged into docs. Thanks for your input.
