### ISSUE TITLE
As a user I would like to validate a connection profile

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1102]
There are 3 ways to create a connection profile
- use playground (and export as required)
- use a text editor (and import into playground if for use by playground)
- copy an existing one (perhaps created by getting started etc)

but how do you know that connection profile is valid or still valid and works with your currently installed toolset ?

a cli tool to validate it and if possible check connectivity is possible would be great, eg
```
composer connprof validate -f connection.json
```
or
```
composer connprof validate -p MyhandCrankedProfile
```

on top of this how about being able to import/export connection profiles or even generate environment variable formats
```
composer connprof export -o aProfile -f ./MyProfile.json -e ./myprofile_env.sh
```

**Comment by sstone1** [comment]
I think close this. With common connection profiles, any validation needs to be performed by the Fabric Node.js SDK and it's up to them to provide good error reporting for invalid connection profiles.  Also, connection profile specific commands don't make sense anymore in the new ID card world.
