### ISSUE TITLE
Tutorial for getting started with playground needs re-arranging.

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1107]
https://hyperledger.github.io/composer/tutorials/getting-started-playground.html

This whole page starts off trying to describe docker, docker-compose then trying to install a local fabric before you even get into how to install playground and run playground.

I think it would be better to start with how to run playground through our hosted offerings first, then move on to installing it locally using npm. playground doesn't require a fabric to work with as it has an embedded runtime for testing.

A more advanced section should describe how to install and get working a fabric runtime but this is going to be a common thing among other tutorials so doesn't need to be replicated here. 
From there describe the ability to create or import connection profiles.

There should be a section on using the docker container with a warning about the complexities of trying to get it to connect to a locally running fabric (not a problem if you want to connect to a remote fabric or use the web connector inside playground which is the embedded runtime)
(see https://stackoverflow.com/questions/44117260/docker-version-of-composer-playground-is-not-able-to-connect-to-local-hlf-1-0-0 for a description of what you need to do to make it work with hlfv1 alpha)

**Comment by sstone1** [comment]
Folding this into #912 which will rewrite all of these docs.
