### ISSUE TITLE
recent jsonata changes prevent playground from launching

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1121]
PR #1029 modifies the jsonata version and adds an exclude to the composer webpack.
Unfortunately the above changes prevent Playground from building and launching.

Recreate:
- Pull all latest code
- Build
- Launch
- Go to http://localhost:3000/editor
- Observe console output indicating error

Alternatively, try using bluemix unstable at https://composer-playground-unstable.mybluemix.net/editor

Current workaround:
- Drop jsonata level (and remove preceeding ^) in packages/composer-playground/package.json
- Remove exclude in packages/composer-playground/config/webpack.common.js

**Comment by sstone1** [comment]
Fixed in #1125.
