### ISSUE TITLE
ACL rules may have duplicate names

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1123]
When defining an ACL rule set, it is currently possible to define the same name rules without error.

For instance, working from the Basic Sample Network, the following ACL file content is valid:
`/**
 * Sample access control list.
 */
rule Default {
    description: "Allow all participants access to all resources"
    participant: "ANY"
    operation: ALL
    resource: "org.acme.sample"
    action: ALLOW
}

rule Default {
    description: "Allow all participants access to all resources"
    participant: "ANY"
    operation: ALL
    resource: "org.acme.sample"
    action: ALLOW
}`

Whilst the rule names are not used, and it is the content that is important, we should probably be catching this case to prevent the user getting into a confusing situation with regards to possible rule precedence.

I would have expected a validation error to be thrown in the above case

**Comment by shachisharma** [comment]
I can look into this problem
