### ISSUE TITLE
As a user, I want to be able to call new transactions from within TP functions

### ISSUE THREAD

**Issue by pospi** [hyperledger/composer#1127]
It would be great if transactions could spawn further transactions once executed. For example there may be cases where both the asset to be acted upon and the operation to be performed needs to be determined at runtime- such an enhancement would make this possible in the trusted environment of the chaincode logic.

I have heard rumours on rocket.chat that this feature is being considered, so I'm just logging it here for posterity (;

**Comment by sstone1** [comment]
We have briefly discussed two routes for this:
1) Adding a `submitTransaction` variant to the runtime API.
2) Allowing transactions to be triggered by events.
