### ISSUE TITLE
As a contributor I'd like to be able to have a Travis-ci build complete in a reasonable time

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#1141]
## Context
Work has happened over time to get the build speeds down whilst maintaining a quality CI/CD pipeline.
This is work though is never finished as the content keeps changing over time.

Time to look again.. assertions are that

1. Merge conflicts have started to occur again that hold up total elapsed time.
2. Some parts of the build are redundant

## Expected Behavior
Ideally builds should be down to 20mins. 

## Actual Behavior
...too...long..

## Possible Fix

1. Remove the Fabric v0.6 from the build
2. If the pull request only contains docs changes then only run the docs part of the build.

    Ideally, this could be achieved by within the scripts reviewing the files are in the pull request. A concern is that information is probably not included within the TRAVIS kick off data. The low tech alternative is to build docs ONLY if the PR title contains :docs: `:docs:`   Have to trust people of course.

3. Not being able to merge if you branch is out of date, is a choice we have opted in to.  We could therefore
   3.1. Opt out of this, but run everything
   3.2. Remove the system tests from every build - but keep the requirement for everything to merged. Schedule regular (hourly) system builds - that should stop the line if they detect failures.

**Comment by jt-nti** [comment]
Is there any reason not to pull the docs out into a separate repo with an independent build?

**Comment by dselman** [comment]
The docs build currently runs the JSDoc build as well -- so an unstable docs build should contain the JSDoc for unstable code. However, I agree that there might be a better way of doing this? We also tied the release process together, so that the docs and the code where released as a unit -- ensuring that they could not get out of sync.

**Comment by dselman** [comment]
Regarding "stopping the line". In my experience this doesn't work... Inevitably people keep working and the build is broken.

**Comment by mbwhite** [comment]
Info from Travis-CI
- Cron jobs can be rescheduled to a specific time - we need to tell them when and they can do it via their admin commands. 
- getting the diffs is possible  and have sent details of the commands required.

**Comment by mbwhite** [comment]
Another way of showing what changes went into this build

https://github.com/melpa/melpa/blob/master/travis-changed-files

**Comment by mbwhite** [comment]
Additional idea:  After a PR build has completed ok, and been reviewed this then git-merged.  Post fit-merge another Travis build runs - this 'merge build' that does a publish to npm docker, and the unstable docs site. 

For the majority of PRs this is pointless as these modules are never going to get used.  And will be superceded within potentially minutes. 

Therefore only do the publish on the daily cron build (perhaps also an interim lunchtime build)

**Comment by sstone1** [comment]
One thing we need to resolve is that the Docker images only get built in the merge + publish part of the build, rather than the main part of the build. We need to build those more regularly, preferably in a PR as well, so we can ensure that nobody breaks the Docker builds. Unfortunately that currently requires that we publish them to an npm registry though 😢

**Comment by sstone1** [comment]
Also, publishing only on the daily cron build does not fit in with our hopes and dreams of being a diverse team with respect to contributors - depending on where you are in the world, you may end up having to wait 23h to pull down the unstable modules - in the case that you need to verify something. That's really not ideal!

**Comment by sstone1** [comment]
We should maybe stop trying to trim time off of the Travis builds and turn our attention onto using the Jenkins service provided by the Hyperledger project - we'll be able to make the biggest gains by using faster build machines, and by having more than 5 of them at once.

**Comment by caroline-church** [comment]
Is it possible to cancel a build if it is out of date there is no point in a build running if it can't be merged

**Comment by sstone1** [comment]
No actions here; strategy is to migrate to Jenkins for multi-platform builds and "throw your own hardware at it" support in CIP #3134.
