### ISSUE TITLE
In hlf v1 connection profile, the hostname field when specifying a certificate should be de-emphasised

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1163]
The Hostname field is most likely a development option only and as such should somehow be de-emphasised when specifying a certificate for connection.
It could be hidden in an "Advanced" Section dropdown or maybe a checkbox which displays the field when checked.

**Comment by sstone1** [comment]
> most likely a development option

If this is the case, I vote we drop it from the UI and only make it available via the JSON format.

**Comment by sstone1** [comment]
@davidkel can you decide what to do with this one please? See my previous comment for my thoughts, happy to discuss though 👍

**Comment by davidkel** [comment]
Will remove the field from playground, if absolutely desperate you can import a profile with it in.
