### ISSUE TITLE
Document new Import Identity command

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1164]
Composer identity import command:-

```
composer identity import [options]

Options:
  --help                       Show help  [boolean]
  -v, --version                Show version number  [boolean]
  --connectionProfileName, -p  The connection profile name  [string] [required]
  --userId, -u                 The user ID for the new identity  [string] [required]
  --signerCertFile, -c         signerCert path  [string] [required]
  --keyFile, -k                key file  [string] [required]
```

**Comment by davidkel** [comment]
The composer identity import command is to be used to import HLFV1 peer admin identities into your profile defined keyValStore so that you can use that identity to deploy business networks to that peer.
All the options are required. The userId doesn't have to match any information defined in the signer certificate of the admin identity for the peer, it is purely a label for your own convenience. An example of the call is

```
composer identity import -p hlfv1 -u Org1PeerAdmin -c admin.pem -k 9022d671ceedbb24af3ea69b5a8136cc64203df6b9920e26f48123fcfcb1d2e9_sk
```
Then when you want to deploy a business network you should use this identity as follows
```
composer network deploy -p hlfv1 -a mybusinessnetwork.bna -i Org1PeerAdmin -s <ANYTHING>
```
(The <ANYTHING> means you have to put something here, but it can be anything you like as it isn't used.
For playground you would add a new identity when connecting to a connection profile, specify the user id as Org1PeerAdmin and again the user secret can be anything as it is never used.

**Comment by sstone1** [comment]
This looks like it has been done.

**Comment by sstone1** [comment]
@davidkel please change "signerCertFile" to "publicKey" and "keyFile" to "privateKey" to use commonly understood terms - needs both code and doc updates.

**Comment by sstone1** [comment]
APIs need changing to reflect previous comment as well.

**Comment by davidkel** [comment]
new help output
```
cli.js identity import [options]

Options:
  --help                       Show help  [boolean]
  -v, --version                Show version number  [boolean]
  --connectionProfileName, -p  The connection profile name  [string] [required]
  --userId, -u                 The user ID for the new identity  [string] [required]
  --publicKeyFile, -c          File containing the public key  [string] [required]
  --privateKeyFile, -k         File containing the private key  [string] [required]
```

new example
```
node cli.js identity import -p hlfv1 -u PeerAdmin -c /home/vagrant/src/fabric-composer/packages/composer-systests/hlfv1/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/signcerts/Admin@org1.example.com-cert.pem -k /home/vagrant/src/fabric-composer/packages/composer-systests/hlfv1/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/keystore/9022d671ceedbb24af3ea69b5a8136cc64203df6b9920e26f48123fcfcb1d2e9_sk 
```

**Comment by EdProsser** [comment]
Will put these in for the release this week. :)
