### ISSUE TITLE
Include Client TypeScript Interface Generator

### ISSUE THREAD

**Issue by opiepj** [hyperledger/composer#1173]
Feature -- Client TypeScript Interface Generator (Application Agnostic)

## Context

The Angular generator creates an interface that reflects your business models. However you cannot update it. It would be cool do this across all applications.

## Expected Behavior

Within the composer cli we should be able to run "update" or something to generate a new TypeScript definition file.

## Actual Behavior

This capability does not exist

**Comment by opiepj** [comment]
Feel free to assign to me.

**Comment by opiepj** [comment]
Also, will see if I can incorporate #400 as well.

**Comment by opiepj** [comment]
@sstone1 Tried running `composer generator create --archiveFile dist/my-network.bna --format Typescript --outputDir ./dev/go-app` but getting the error:

`Error: Unrecognised type: object, value: BusinessNetworkDefinition`

**Comment by dselman** [comment]
This is a bug in the Typescript generator -- it assumes we are visiting a ModelManager, not a BusinessNetworkDefinition.

**Comment by opiepj** [comment]
Looks like it's working now, thanks!
