### ISSUE TITLE
Prevent Duplicate Namespaces

### ISSUE THREAD

**Issue by opiepj** [hyperledger/composer#1174]
Need to throw an error when a user tries to use the same model namespace more than once. Namespaces are unique.

## Context

During the archive creation stage, we put the namespaces in a model manager. It's likely that we are not checking if the model namespace has already been registered. For new developers, this is an issue as this leads to unknown reasons why they cannot access their models. We need to prevent users from mishandling the namespace logic.

## Expected Behavior

If duplicate namespaces are used then an error should be thrown stating that the namespace is being used more than once.

## Actual Behavior

Nothing.

## Possible Fix

During the compilation stage, create a check within the model manager to prevent duplicate namespaces.

**Comment by shachisharma** [comment]
I will fix this problem

**Comment by shachisharma** [comment]
Currently, the model manager does not check for duplicate name space, instead if a name space already exists, the corresponding model file gets overwritten by model manager.
