### ISSUE TITLE
GitHub API Exceed message thrown mid fetch is not very well presented

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1176]
If, during the action of drawing down GitHub hosted projects for import within Playground, the API limit is reached, the thrown error is not presented by the error dialogue very cleanly

![image](https://cloud.githubusercontent.com/assets/8394544/26823748/a5e02fa2-4aa6-11e7-8e7b-71e459445ad1.png)

## Context
The message is not very well presented, and only the message payload is being shown to the user

## Expected Behavior
Message should be nicely formatted

## Actual Behavior
Message unformatted

## Steps to Reproduce
Tricky, but if local, edit code to continually pull down samples, then action that path. Consider that you get to do this once an hour though ....

**Comment by sstone1** [comment]
No longer a problem now that we have removed the GitHub sample downloader.
