### ISSUE TITLE
As a user, I can subscribe to events (using webhooks or websockets) from the REST server

### ISSUE THREAD

**Issue by gcharters** [hyperledger/composer#1177]
As a client of the blockchain, I'd like to be able to register to be notified of key Blockchain events.  I'd like to do this through a REST API exposed using Swagger by Composer.

Composer's support for Swagger provides an easy way for API enabled runtimes to call the Blockchain.  Composer currently allows clients to query the blockchain and invoke transactions, but provides no way to know when key events happen in the blockchain.  For example, if another systems invokes a transaction on another peer there is no notification that this has happened.  Blockchain does have an eventing mechanism, but it is not exposed via Composer.

This issue is to request that Events support be added to Composer using a mechanism like Web Hooks (aka Open API callbacks).  The available events would be described on the Composer Swagger APIs and clients would be able to register Callback APIs to be called when these events occurs.

## Context
See above.  This is a feature enhancement request, not a bug.

## Expected Behavior
N/A

## Actual Behavior
N/A

## Possible Fix
N/A

## Steps to Reproduce
N/A

## Existing issues

- [ x ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
No equivalent request found.

## Context
It significantly limits the integration possibilities enabled by Composer.

## Your Environment
N/A

**Comment by joeswashington** [comment]
Ditto, if we can have this feature implemented soon!

**Comment by LarissaAuberger** [comment]
We in IBM BPM can't wait to see this user story implemented :-)

**Comment by opiepj** [comment]
Hey @sstone1 I just got back from vacation, I noticed you have a web runtime event service. Could I just hook that service into the composer rest server? How hard would it be to do that?

**Comment by opiepj** [comment]
@sstone1 #1655 completed this in release 10.1

**Comment by caroline-church** [comment]
@sstone1 can we close this issue now or is there more to do?

**Comment by opiepj** [comment]
@caroline-church How would you subscribe to the events on the composer rest server

**Comment by sstone1** [comment]
@opiepj here are some docs that will be included in the next release: https://hyperledger.github.io/composer/unstable/integrating/publishing-events.html

All of the code is in the current release, so you can use those instructions today.

**Comment by opiepj** [comment]
@sstone1 perfect thank you!
