### ISSUE TITLE
Dragging and dropping a script or model file into the Playground import/replace dialog opens the file.

### ISSUE THREAD

**Issue by EdProsser** [hyperledger/composer#1183]
When in the 'Import/Replace' dialog in the Playground UI, if you drag a script or model file into the box marked: "Drop here to upload or browse" the browser opens the file dropped in the current tab rather than uploading it to Playground.

## Context

Dropping a script or model file into the drag and drop box opens the file in the current tab, replacing the Playground.

Firefox and Chrome, Mac.

## Expected Behaviour

When dropping files, they are uploaded to the playground.

## Actual Behaviour

The files open in your current tab.

**Comment by caroline-church** [comment]
done so closing
