### ISSUE TITLE
Composer Tutorials - a new user can follow them with minimum friction

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1190]
We have 2 Tutorials in our doc, one for using the web playground and one for using the development environment:

1. https://hyperledger.github.io/composer/tutorials/playground-guide.html
2. https://hyperledger.github.io/composer/tutorials/developer-guide.html

These could use some love.  Job 1 is to re-capture and clean up all the screenshots.  Also, review the ones we have and decide whether they're the right ones to have in there.

Then just generally anything we can do to make sure they're easy and enjoyable for a brand new user to follow.  Some guerilla-testing on unsuspecting Composer-newbies might be a good approach to take :)

I'm leaving this one with @Tobias-Hunter for when he gets back from holidays!

**Comment by EdProsser** [comment]
I'm also going through for clarity of language.

**Comment by sstone1** [comment]
@EdProsser @Tobias-Hunter is this now complete after v0.8.0?

**Comment by Tobias-Hunter** [comment]
@sstone1 Still working on this...
✅  to the developer tutorial
❌ to the playground tutorial

**Comment by Tobias-Hunter** [comment]
Submitted in my PR #1312, closing issue now!
