### ISSUE TITLE
Problem calling PrivateVehicleTransfer transaction

### ISSUE THREAD

**Issue by gcharters** [hyperledger/composer#1195]
I'm trying to call the PrivateVehicleTransfer transaction from the vehicle lifecycle sample. Can someone tell me what a valid set of values for the data would be? I seem to be having particular problems with the "buyer" and "seller" entries, which I think are identified by email. I've tried a raw email value, and I've also tried values of the form I get back from the API (e.g. resource:composer.base.Person#bob@bob.com or even resource:org.acme.vehicle.lifecycle.PrivateOwner#bob@bob.com). Irrespective of the form, I get this error: "message": "Error: Object with ID '[Participant:composer.base.Person $sysregistries]' in collection with ID '%!!(MISSING)s(MISSING)' does not exist". Many thanks for any help. 

## Context
An example of the json I'm sending using API Explorer is:

{
  "$class": "org.vda.PrivateVehicleTransfer",
  "seller": "bob@bob.com",
  "timestamp": "2017-06-05T12:45:08.780Z",
  "buyer": "gra@gra.com",
  "vehicle": "1234"
}

The two PrivateOwners defined in the system are:

[
  {
    "$class": "org.acme.vehicle.lifecycle.PrivateOwner",
    "email": "bob@bob.com",
    "title": "Mr",
    "firstName": "Bob",
    "lastName": "Bobson",
    "middleNames": [
      "Bobby"
    ],
    "gender": "MALE",
    "nationalities": [
      "British"
    ],
    "contactDetails": {
      "$class": "composer.base.ContactDetails",
      "email": "bob@bob.com",
      "mobilePhone": "+4411111111",
      "homePhone": "+4422222222",
      "address": {
        "$class": "composer.base.Address",
        "city": "Bobton",
        "country": "England",
        "locality": "Local",
        "region": "Hampshire",
        "street": "Bobhouse",
        "street2": "Bob Road",
        "postalCode": "BB11 1BB"
      }
    },
    "birthDetails": {
      "$class": "composer.base.BirthDetails",
      "dateOfBirth": "2017-06-05T12:45:08.710Z",
      "placeOfBirth": "Bobton"
    }
  },
  {
    "$class": "org.acme.vehicle.lifecycle.PrivateOwner",
    "email": "gra@gra.com",
    "title": "Mr",
    "firstName": "Gra",
    "lastName": "Grason",
    "middleNames": [
      "Gradle"
    ],
    "gender": "MALE",
    "nationalities": [
      "United States"
    ],
    "contactDetails": {
      "$class": "composer.base.ContactDetails",
      "email": "gra@gra.com",
      "mobilePhone": "+4410101010",
      "homePhone": "+4412121212",
      "address": {
        "$class": "composer.base.Address",
        "city": "Graton",
        "country": "United States",
        "locality": "Local",
        "region": "New Hampshire",
        "street": "Gra Villa",
        "street2": "Gra Avenue",
        "postalCode": "2342SB"
      }
    },
    "birthDetails": {
      "$class": "composer.base.BirthDetails",
      "dateOfBirth": "2017-06-06T10:45:08.710Z",
      "placeOfBirth": "Graton"
    }
  }
]

The Vehicles are defined as:

[
  {
    "$class": "org.vda.Vehicle",
    "vin": "1234",
    "vehicleDetails": {
      "$class": "org.vda.VehicleDetails",
      "make": "Ford",
      "modelType": "Ka",
      "colour": "Red",
      "vin": "1234",
      "bodyType": "Hatchback",
      "taxationClass": "PETROL_CAR",
      "co2": 89,
      "typeOfFuel": "Petrol",
      "numberOfSeats": 5
    },
    "vehicleStatus": "ACTIVE",
    "owner": "resource:composer.base.Person#bob@bob.com",
    "numberPlate": "AA12 AAA"
  },
  {
    "$class": "org.vda.Vehicle",
    "vin": "1235",
    "vehicleDetails": {
      "$class": "org.vda.VehicleDetails",
      "make": "Fiat",
      "modelType": "Punto",
      "colour": "Green",
      "vin": "1235",
      "bodyType": "Hatchback",
      "taxationClass": "PETROL_CAR",
      "co2": 93,
      "typeOfFuel": "Petrol",
      "numberOfSeats": 5
    },
    "vehicleStatus": "ACTIVE",
    "owner": "resource:composer.base.Person#bob@bob.com",
    "numberPlate": "BB12 BBB"
  }
]

The error I see on the composer-rest-server is:

Unhandled error for request POST /api/PrivateVehicleTransfer: Error: Error: Object with ID '[Participant:composer.base.Person $sysregistries]' in collection with ID '%!!(MISSING)s(MISSING)' does not exist
    at /home/charters/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17

## Expected Behavior
The transaction should work

## Actual Behavior
The transaction doesn't work

## Possible Fix
No idea

## Steps to Reproduce
In API Explorer
1. Create two PrivateOwners
2. Create a Vehicle assigning it to one of the Owners.
3.  Call PrivateVehicleTransfer transaction to transfer the Vehicle to the other Owner

## Existing issues
- [x ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)
Suggestion was to open an issue

## Context
Trying to create a demo integrating a Java server with Hyperledger.  Demo is blocked.

## Your Environment
* Version used: hlfv1
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node 6.9.5 Composer 0.7.0
* Operating System and version (desktop or mobile): Ubuntu desktop
* Link to your project: N/A

**Comment by gcharters** [comment]
This is the .bna file I deployed.  Note, I renamed it's extension to .zip to allow it to be attached to the issue.

[vehicleLifecycleNetwork.zip](https://github.com/hyperledger/composer/files/1057685/vehicleLifecycleNetwork.zip)

**Comment by dselman** [comment]
Here is the transaction payload that is submitted by the unit test:

```
{"$class":"org.vda.PrivateVehicleTransfer","seller":"resource:org.acme.vehicle.lifecycle.PrivateOwner#dan","buyer":"resource:org.acme.vehicle.lifecycle.PrivateOwner#simon","transactionId":"3aa3cdb5-2552-4f69-96af-8458ecfcdbea","vehicle":"resource:org.vda.Vehicle#123456789","timestamp":"2017-06-07T11:10:04.799Z"}
```

**Comment by gcharters** [comment]
I've just tried the following:

{
  "$class": "org.vda.PrivateVehicleTransfer",
  "seller": "resource:org.acme.vehicle.lifecycle.PrivateOwner#bob@bob.com",
  "buyer": "resource:org.acme.vehicle.lifecycle.PrivateOwner#gra@gra.com",
 "transactionId":"3aa3cdb5-2552-4f69-96af-8458ecfcdbea",
  "vehicle": "resource:org.vda.Vehicle#1234",
  "timestamp": "2017-06-08T15:38:51.054Z"
}

And it gives me this error:

"message": "The `PrivateVehicleTransfer` instance is not valid. Details: `transactionId` can't be set (value: \"3aa3cdb5-2552-4f69-96af-8...bea\").",

Which I think means I should not be providing the transactionId.

If I remove the transactionId, I get the error I had previously:

"message": "Error: Object with ID '[Participant:composer.base.Person $sysregistries]' in collection with ID '%!!(MISSING)s(MISSING)' does not exist",

The seller, vehicle and buyer details are all as in the original report and were submitted through API Explorer.

**Comment by gcharters** [comment]
FYI, I just tried the ScrapVehicle transaction, which doesn't ask you to specify any participant info (e.g. owner).  This is what I provided:

{
  "$class": "org.vda.ScrapVehicle",
  "vehicle": "resource:org.vda.Vehicle#1234",
  "timestamp": "2017-06-09T12:13:48.147Z"
}

The error I got was the same:

"message": "Error: Object with ID '[Participant:composer.base.Person $sysregistries]' in collection with ID '%!!(MISSING)s(MISSING)' does not exist",

Has anyone tried using API Explorer to add the PrivateOwner and Vehicle entries shown in the initial report and then call a transaction to see if they can reproduce the problem?

**Comment by gcharters** [comment]
I don't know if this is related, but when I create anything through API Explorer, the result on the POST always has null null for the identifier.  For example, here's a result from creating a new PrivateOwner:

{
  "$class": "org.acme.vehicle.lifecycle.PrivateOwner",
  "email": [
    null,
    null
  ],
  "title": "Mr",
  "firstName": "Berty",
  "lastName": "Bertson",
...

**Comment by gcharters** [comment]
@dselman - Hi, do you know if someone's tried using API Explorer to input the data from my original report to reproduce the problem?  I'm pretty stuck with this sample until I can get this issue resolved :(

**Comment by sstone1** [comment]
@gcharters the [null, null] problem got fixed in the last release.

**Comment by sstone1** [comment]
Both the Vehicle asset and the PrivateVehicleTransfer transaction accept relationships to the abstract participant composer.base.Person:

```
asset Vehicle identified by vin {
  o String vin
  o VehicleDetails vehicleDetails
  o VehicleStatus vehicleStatus
  --> Person owner optional
  o String numberPlate optional
  o String suspiciousMessage optional
  o VehicleTransferLogEntry[] logEntries optional
}

transaction PrivateVehicleTransfer extends VehicleTransaction {
  --> Person seller
  --> Person buyer
  o String specialNotes optional
}
```

This (rather poor!) error message means that we're trying to look for the composer.base.Person participant registry but it does not exist:
`Error: Object with ID 'Participant:composer.base.Person' in collection with ID '$sysregistries' does not exist`

That participant registry does not exist because we do not create registries for abstract types.

We are looking for this registry because the vehicles supplied originally contain fully qualified relationships, but they do not include the right type:

```
{
"$class": "org.vda.Vehicle",
"vin": "1234",
"vehicleDetails": {
"$class": "org.vda.VehicleDetails",
"make": "Ford",
"modelType": "Ka",
"colour": "Red",
"vin": "1234",
"bodyType": "Hatchback",
"taxationClass": "PETROL_CAR",
"co2": 89,
"typeOfFuel": "Petrol",
"numberOfSeats": 5
},
"vehicleStatus": "ACTIVE",
"owner": "resource:composer.base.Person#bob@bob.com", <-- this is the problem
"numberPlate": "AA12 AAA"
},
```

The relationships in the owner field need to contain the right type, for example:
`"owner": "resource:org.acme.vehicle.lifecycle.PrivateOwner#bob@bob.com"`

@gcharters can you update your vehicles to contain the correct relationships and try again please?

**Comment by gcharters** [comment]
@sstone1 - thanks.  That worked. :) It's not clear to me how the user of the API should know to use these prefixes, other than through experience.  Is there something I'm missing?

**Comment by sstone1** [comment]
@gcharters no you're quite right, I think at a minimum we need some documentation in this area; a topic along the lines of "Interacting with a REST API for a business network" could describe these requirements.

**Comment by dselman** [comment]
I will write some docs on relationships in general, as this is turning into a FAQ.

**Comment by gcharters** [comment]
Thanks, @sstone1 - There are a couple of areas in the Composer API where I feel like I'm having to specify information that Composer should know.  I know I've mentioned one before, which is the $class.  It would seem to me the the endpoint URL being exposed determines the Type of the resource and so providing $class is duplication.  Similarly with these qualifiers, the endpoint determines the transaction type and the transaction type is specific to the resource type, which defines the type of the identity.  Emails are already unique and so I had hoped composer would know to look for "resource:org.acme.vehicle.lifecycle.PrivateOwner#bob@bob.com" when I specify "bob@bob.com" as opposed to me having to specify the fully qualified identifier.  I guess I'm looking for Composer to use more of the context of each API.

Perhaps there are good reasons why it can't, but as someone who only understands the externals, it doesn't feel quite right.

Regarding documentation, maybe some additional information could also be generated into the field description.  It currently says, "The instance identifier for this type" but maybe it could provide an example or mention the prefix.  Annoyingly, API Explorer doesn't seem to show this documentation, and neither does the Java client generation, having them do this in the future would not be unreasonable.  I'd really like to get to the point where people don't have to read the swagger json.

Anyway, I hope this helps you with one user's perspective.  Overall, I think Composer is awesome, and these are just things that I've stumbled on and I suspect others might.

**Comment by gcharters** [comment]
@sstone1 - I've just read back through #610 and think that my comments on the API design are addressed by that...
