### ISSUE TITLE
Closing Local Playground 

### ISSUE THREAD

**Issue by quoder** [hyperledger/composer#1198]
## Context

I can create a local playground in my system using the below command:
`curl -sSL https://hyperledger.github.io/composer/install-hlfv1.sh | bash`
Now, I want to close this playground. How do I close it?

## Possible Fix
`docker ps -aq | xargs docker rm -f`
`docker images -aq | xargs docker rmi -f`
But these commands would rather completely remove the local playground and hence running the playground again would require complete reinstallation.

## Your Environment

* Version used: Hyperledger Composer v1
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by dselman** [comment]
You can use `docker stop` to stop execution of a docker container.

**Comment by quoder** [comment]
Using `docker stop` did not close the Local Playground running at port 8080

**Comment by anand4321** [comment]
I have used all the docker commands, but still http://localhost:8080 opens the playground. How to gracefully stop the composer and restart it.

**Comment by jissgist123** [comment]
> I have used all the docker commands, but still http://localhost:8080 opens the playground. How to gracefully stop the composer and restart it.

Just restart your machine

**Comment by jissgist123** [comment]
Just restart your machine to close playground.

**Comment by FrancescoCommisso** [comment]
If you dont want to restart your machine you could use:

sudo lsof -i tcp:8080

to get the process id that the playground is running at and then use:

kill -9 <pid>

to kill the process
