### ISSUE TITLE
Drag & Drop broken for Add File

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1209]
Can't figure out what the exact recreate steps are here, sorry :(

I'm testing in Chrome, clicking the + Add File button, then dragging in a .cto file.  Sometimes, it works fine.  Other times, instead of displaying the drop-target (which has an illustration), nothing renders in the modal, and if I drop the file it just opens it as text in my browser.

First time this happened, clearing all my browser history and cache fixed it.  The same thing did not fix it on subsequent tests.

The file I'm trying to import is causing an error (I think there's a filename or namespace clash going on), so that could be some hint at a recreate?

**Comment by EdMoffatt** [comment]
Dang, sorry, scratch that - I still get the same thing happening when the first thing that I try to upload is a file that won't error on Add :/  Ok, well I'm out of clues as to how to recreate, sorry!

**Comment by sstone1** [comment]
Such dupe, much close:
Dragging and dropping a script or model file into the Playground import/replace dialog opens the file. #1183
