### ISSUE TITLE
Ctrl-Z action in code mirror has unexpected results

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1217]
Ctrl-Z action reverses edits in the code mirror. Which is nice. However, if you have been editing multiple files, and start to control-z, you end up pulling the contents of the previously edited file(s) into the code mirror for the currently edited file ... meaning that you can end up swapping out the content of a model file for a script file.

## Context
Ctrl-Z moves back in time too far

## Expected Behavior
You should only be able to reverse edits to a file that are relevant to that file

## Actual Behavior
You can convert a model file into a script file.

## Possible Fix
Limit scope of code mirror

## Steps to Reproduce
Open playground
edit model file
edit script file
edit ACL file
ctrl-z on ACL file repeatedly ... observe ACL transformation

## Context
reversing generic edit, resulting in trashing my file

## Your Environment
Ubuntu, Chrome, staged playground

**Comment by sstone1** [comment]
P3 and no action in three months; clearly not important and never going to get fixed, so closing.
