### ISSUE TITLE
Peer review comments for HLFv1 next support

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#1222]
`packages/composer-admin/lib/adminconnection.js`

See comments in #1164; please change "signerCertFile" to "publicKey" and "keyFile" to "privateKey" to use commonly understood terms - needs both code and doc updates.

```
+                if (!connectionManager.importIdentity || typeof connectionManager.importIdentity !== 'function') {
+                    throw new Error('the connector doesn\'t support identity import');
+                }
```

Why is this _here_ - this should be removed and moved into the base ConnectionManager class (which is meant to define the connector interface.

`packages/composer-connector-hlfv1/lib/hlfwalletproxy.js`

```
+        let self = this;
+        return new Promise(function(resolve, reject) {
+            resolve(self);
+        });
```

What is this for?! Returning things from constructors is very weird JavaScript (for any language really) - please get rid of this. Also, it could just be written as `return Promise.resolve(this)`. `self` is no longer needed with arrow functions.

`packages/composer-runtime-hlfv1/identityservice.go`

```
-	certStart := bytes.IndexAny(creator, "----BEGIN CERTIFICATE-----")
+	//byte array below represents -----BEGIN CERTIFICATE-----
+	certStart := bytes.Index(creator,[]byte{45,45,45,45,45,66,69,71,73,78,32,67,69,82,84,73,70,73,67,65,84,69,45,45,45,45,45})
```

Why the byte array - can't we code this as []byte("----BEGIN CERTIFICATE----") ?

**Comment by davidkel** [comment]
- done name change (not the docs though)
- changed hlfproxy to return Promise.resolve(this); Don't blame me for that its a requirement of the api that it returns a promise. It's not good I know but what can you do ?
- changed identity service as I didn't know you could do that in go (just used the sample given in the defect as it worked)
- have moved the check out about importIdentity.

**Comment by davidkel** [comment]
jira raised
