### ISSUE TITLE
As a user I can define queries using a domain specific language

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#1234]
## Context

Composer queries should be specified using a domain specific language, expressed in terms of the assets, participants and transaction types as modelled in the user's CTO files.

The query language must be complied to the CouchDB Mango query language, so needs similar expressivity:
http://docs.couchdb.org/en/2.0.0/api/database/find.html#sort-syntax

- selection by type of resource
- selection by conditions on properties of the resource (including sub-properties)
- multilevel sorting by properties (ASC, DESC)
- limit the number of resources returned
- skip resources to provide pagination support

In addition the queries should be parameterizable, such that the caller of the client can supply named parameter values.

### Examples

```
query Q8 {
    description: "Select 10 Drivers called Dan Selman"
    statement: SELECT org.acme.Driver WHERE (firstName=='Dan' AND lastName=='Selman') LIMIT 10
}

query Q18 {
    description: "Select all drivers aged older than PARAM" 
    statement: 
        SELECT org.acme.Driver 
            WHERE (_$ageParam < age)
                ORDER BY [lastName ASC, firstName DESC]
                    LIMIT _$limitParam
                        SKIP _$skipParam

}
```

**Comment by dselman** [comment]
First cut of this has been merged. Will open addition issues for any enhancements needed.

**Comment by xuanyue202** [comment]
Hi Dan, 
I know this has been implemented. But I have a suggestion on this. This feature is already very cool. It looks very friendly to SQL programmers. The following changes might make it even more friendly :)

1. Functionally identical to your example:

```
 SELECT * FROM org.acme.Driver 
            WHERE (_$ageParam < age)
                ORDER BY [lastName ASC, firstName DESC]
                    LIMIT _$limitParam
                        SKIP _$skipParam
```

2. projection 

```
 SELECT firstName, lastName FROM org.acme.Driver 
            WHERE (_$ageParam < age)
                ORDER BY [lastName ASC, firstName DESC]
                    LIMIT _$limitParam
                        SKIP _$skipParam
```

3. JSONata for transformation
```
 SELECT jsonata('{"name": firstName & " " & lastName, "age":  age}') FROM org.acme.Driver 
            WHERE (_$ageParam < age)
                ORDER BY [lastName ASC, firstName DESC]
                    LIMIT _$limitParam
                        SKIP _$skipParam
```
