### ISSUE TITLE
As a Playground user I would like to be able to add an ACL file

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#1237]
## Context
As it stands currently, if I want to edit an ACL file in playground I need to start by importing a network that already has an ACL file. 

I can't create one via the playground ui.  

Frustrating for users - if they start from nothing. 

## Expected Behavior
Where the create file options are, there should be an ACL option as well.

**Comment by sstone1** [comment]
Duplicate of:
As an end user I can add a permissions.acl file in the Playground #505
