### ISSUE TITLE
As a Playground user I can export/import the data

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#1240]
## Context
You can export as a BNA archive, the structure of the network - but you can't do anything with the data. 

The export/import functions from a deployed network should not be a complex operation.

In addition the sample networks, could have a feature within the model portion to have a set of sample data that could be preloaded if wished.

**Comment by sstone1** [comment]
As far as I know, nobody is working on this at the moment or planning to work on it, so closing. 
If somebody wishes to work on this in the future, then please reopen this issue or open a new issue.
