### ISSUE TITLE
Investigate multiple registrations of the exit listener in the system tests

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1246]
We should check to see what is causing this and why we might have multiple calls to register exit listeners. 
The warning is
```
  Access control system tests
Calling Client.connect('composer-systest', 'systest.accesscontrols', 'admin', 'adminpw') ...
Calling Client.connect('composer-systest', 'systest.accesscontrols', 'cd2d010d-5111-45da-a6f6-20bb85bc9f81', 'GYGAdOrapMvd') ...
Calling Client.connect('composer-systest', 'systest.accesscontrols', '1bdd7c5a-48d0-4f66-acf8-542d989ad586', 'YAehBBNFoxXY') ...
    ✓ should be able to enforce read access permissions on an asset registry (818ms)
Calling Client.connect('composer-systest', 'systest.accesscontrols', 'admin', 'adminpw') ...
Calling Client.connect('composer-systest', 'systest.accesscontrols', '9f67a068-91c4-4302-9499-b237fafcba6d', 'uURwVHONcDVJ') ...
Calling Client.connect('composer-systest', 'systest.accesscontrols', '08cbe09b-6d93-47c8-a63e-5b7fb03684f1', 'LJeKFOVbuaRl') ...
(node:11909) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
    ✓ should be able to enforce read access permissions on a participant registry (792ms)
Calling Client.connect('composer-systest', 'systest.accesscontrols', 'admin', 'adminpw') ...
```

**Comment by davidkel** [comment]
reported on Rocket chat the following snippet called 11 times also gives a warning of possible EventEmitter memory leak detected
```
var bizNetworkConnection = new BusinessNetworkConnection();
bizNetworkConnection.connect("hlfv1", "org.acme.biznet", "admin", "adminpw")
.then(function (result) {
   console.log("connection success ")
   console.log("user " + bizNetworkConnection.securityContext.getUser())
   bizNetworkConnection.disconnect().then(function () { 
      console.log("user2 "+bizNetworkConnection.securityContext)
      bizNetworkConnection=null
   })
```

**Comment by rmoedt** [comment]
We also notice this everytime we create more then 10 connections to composer, even though we disconnect the connections after we are done with them.

**Comment by davidkel** [comment]
So a single application, if it creates multiple connections then for each connection we register an event listener on exit, but never remove on disconnect. So if you sequentially connect/disconnect on the same object or different objects then you will get this message. It isn't a problem (apart from the using of memory) as the exit handler won't perform any action as checks are in place to see if anything needs to be done. 
So for the sequential case we could remove the exit handler when disconnect is called.
In the concurrent case where a single app could make requests concurrently and wait for the responses then exit listeners will be setup and if the requests are all made before responses come back and the client application disconnects then there is no way to avoid the message except to increase the limit as mentioned by the message. We want to keep the exit handlers in place to ensure good cleanup.

**Comment by caroline-church** [comment]
@mbwhite can you take a look at this please?

**Comment by mbwhite** [comment]
Suggested design:

- Within the ConnectionManager (or other central place) register a single event listener for 'exit'
- When this event is called, all the connection managers are told to exit
- Same processing logic as today can be enacted within the connection.
