### ISSUE TITLE
Document connection profiles for alpha2/beta1/rc

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1254]
Connection profiles have changed slightly since alpha1. The following changes are
- deployWaitTime has been removed
- invokeWaitTime has been removed
- timeout has been added and is optional: This is a single timeout for each request made to peers and orderers. We should note that some commands for example `composer network deploy` may make several sequential requests and the timeout will be applied individually to each request.
- globalcert has been added and is optional: This allows you to define a single tls cert across all peers and orderers who do not have their own explicit cert defined.
- maxSendSize has been addedand is optional : This controls the size limit of outbound grpc messages being sent to orderers and peers. grpc defines a default if this is not set. -1 means no restriction. The value is specified on Mb
- maxRecvSize has been added and is optional: This controls the size linit of inbound grpc messages being received from ordererers and peers. grpc defines a default if this is not set. -1 means no restriction. The value is specified on Mb

an example of all the possible options is shown here
```
{
    "type": "hlfv1",
    "orderers": [
        {
            "url": "grpcs://",
            "cert": ""
        },
        {
            "url": "grpcs://",
            "cert": ""
        }
    ],
    "ca": {
            "url:" "https://",
            "trustedRoots": "",
            "verify": true
    },
    "peers": [
        {
            "requestURL": "grpcs://",
            "eventURL": "grpcs://",
            "cert": ""
        },
        {
            "requestURL": "grpcs://",
            "eventURL": "grpcs://",
            "cert": ""
        }
    ],
    "keyValStore": "/YOUR_HOME_DIR/.your-own-key-store",
    "channel": "mychannel",
    "mspID": "Org1MSP",
    "timeout": 300,
    "globalcert": "",
    "maxSendSize": 10,
    "maxRecvSize": 15
}
```

**Comment by EdProsser** [comment]
This has been updated now.

**Comment by davidkel** [comment]
Oops, just remembered another bit. In the ca section
```
"ca": {
            "url:" "https://",
            "name":""
            "trustedRoots": "",
            "verify": true
    },
```
there is now a name field. It is optional however it's likely ca's will be defining a name so likely to be frequently required.

**Comment by EdProsser** [comment]
This is now up to date. :)
