### ISSUE TITLE
Provide ability to upgrade composer runtime for a deployed business network

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1262]
Use the fabric 1.0 ability to upgrade chaincode to allow admins to upgrade the composer runtime.
(more details to follow)

**Comment by sstone1** [comment]
This is not a P1, sorry @davidkel - dropping to P2.

**Comment by davidkel** [comment]
@sstone1  Is it less important than dynamic tracing turning on/off as that is set at P1 and on my list todo next ? I thought this would be more useful for end users given updating the rest server means having to redeploy for example. No worries if it is more important, just wanted to confirm.

**Comment by sstone1** [comment]
@davidkel confirmed - logging is more important.

And I'm not sure I follow - a newer REST server is able to communicate with an older chaincode as far as I know? We use semantic versioning to check that the client level is greater than or equal to the chaincode level. If you deploy a newer chaincode using a newer level of the Composer CLI and don't upgrade the REST server at the same time, it will fail with the version mismatch and there's nothing we can do about that.

Being able to upgrade the Composer runtime is important in the long run but not as important as Node.js chaincode, system level ACLs, removing the admin super user, etc.

**Comment by davidkel** [comment]
@sstone1 ok, my mistake, I thought I had seen issues on rocket chat where a new deploy was required due to upgraded client capabilities

**Comment by sstone1** [comment]
Closing and using https://github.com/hyperledger/composer/issues/1294 instead.
