### ISSUE TITLE
Yeoman generator for business network needs improvements

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#1267]
@14gracel we need some work to the business network generator - it's a bit inconsistent with the Angular generator, and there's odd behaviour like that described in #1182. IMHO these are the changes we need:

Text changes to initial questions - please note the case 😉 
```
Welcome to the Hyperledger Composer Skeleton Application Generator <-- Replace Skeleton Application Generator with project generator
? Please select the type of Application: <-- Replace Application with project
  CLI Application 
  Angular 2 Application <-- Can you drop the 2 whilst you're in here, as it's Angular 4 now
❯ Skeleton Business Network <-- Remove Skeleton, none of the others have this
```

Remove this question:
`? Do you only want to generate a model? No`

If we want to generate a model only project, that should be a separate option in the initial question. Also don't create empty test folders for model only projects!

The following options are inconsistent with the ones in the Angular generator. Please can we use similar question text across the generators? For example, don't have `Who is the author` in one and `Author name` in the other.

Business network:
```
? What is the business network's name? biznet
? What is the business network's namespace? org.acme.biznet
? Describe the business network such description
? Who is the author? Simon Stone
? Which license do you want to use? Apache-2 <-- option not present below, and default license is wrong
```

Angular:
```
? What is the name of the application you wish to generate?: angular-app
? Description of the application: Skeleton Hyperledger Composer Angular2 project
? Author name: Simon Stone
? Author email: sstone1@uk.ibm.com <-- option not present above
? What is the Business Network Identifier?: digitalproperty-network
```

**Comment by 14gracel** [comment]
Solved in #1338
