### ISSUE TITLE
1-click installer creates composer.sh but refers to non existent shell script

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1278]
Output from running the 1-click installer
```
Please use 'composer.sh' to re-start
rm: cannot remove '/home/ubuntu/testagain/install-hlfv1-unstable.sh': No such file or directory
```
but that shell script is never created. Also at the top of the script is
```
ME=`basename "$0"`
if [ "${ME}" = "install-hlfv1{{ENV}}.sh" ]; then
  echo "Please re-run as >   cat install-hlfv1{{ENV}}.sh | bash"
  exit 1
fi
```
which also isn't available. It would be if the curl command in the 1-click installer was designed to save the file but it doesn't rather than to stream to bash

**Comment by sstone1** [comment]
@mbwhite can you clean this up please?

**Comment by mbwhite** [comment]
Have removed the unrequired delete at the end of the file.  I think it would be prudent to keep the lines at the top... Someboyd is going to miss of the pipe to bash - (maybe spotting it's a .sh file that is being curled). If they just download it and run it - they get that error message. 

In normal use case it gets ignored and removed... But just in case!
