### ISSUE TITLE
When using playground when I hover over the various artifacts the bar cursor is shown

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1282]
Using Chrome, If I hover over the text of 
```
Model File
models/com.biz.cto
```
(but applies to the logic and acl sections as well)
then I see the vertical bar cursor which implies I can edit that text, but can't In fact it is a clickable area to switch displaying of the code but this isn't what the mouse doesn't visually reflect that

**Comment by jdp1g09** [comment]
@davidkel am I right in saying you're referring to the side-menu on the left of the 'Define' page here?
