### ISSUE TITLE
Node-RED page has incorrect formatting

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#1287]
https://hyperledger.github.io/composer/integrating/node-red.html

I think this should be a formatted list:

You can use the Hyperledger Composer Node-RED contribution to: - Submit transactions - Read and update assets and participants - Subscribe to events

`contribution` should be replaced with `nodes`

**Comment by EdProsser** [comment]
Fixed. Will go into this week's PR.

**Comment by caroline-church** [comment]
@EdProsser can this now be closed?
