### ISSUE TITLE
Installing Playground locally issues

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#1289]
Comments from me and @davidkel from Slack earlier which aren't captured in an issue AFAICS.

I'd be a fan of deleting as many of the specific references to alpha/beta/RC as possible as they're a pain to maintain, unless we can turn them into a tag and manage them from one place?

https://hyperledger.github.io/composer/unstable/introduction/solution-architecture.html refers to alpha1 in the text and in the graphic

This needs corrections:
https://hyperledger.github.io/composer/unstable/business-network/bnd-deploy.html

> Hyperledger Fabric Beta
should be
> Hyperledger Fabric v1.0 beta

> These security changes mean that Hyperledger Composer cannot support older versions of Hyperledger Fabric v1.0 (e.g. alpha 1).
this isn't really that accurate and is confusing - the APIs aren't even the same. We should state our supported environments on one page (don't know where that is though). New reference topic?
 
There's a few typos and grammar errors as well

https://hyperledger.github.io/composer/installing/using-playground-locally.html

> This tutorial will take you through how to install and run the Hyperledger Composer Playground on your local machine. It also creates an instance of Hyperledger Fabric v1.0-Alpha1.

 It should be:

> Hyperledger Fabric v1.0 beta 1

https://hyperledger.github.io/composer/unstable/installing/using-playground-locally.html
I think the following text doesn’t convey what is going on quite right
```Admin user's identities and crypto material must be available to the peer at deployment. To make that identity and its crypto material available, your must import it to your local keyValStore directory before deploying the business network.
```
The Admin crypto material must be available to the peer when it starts. In order for composer to be able to use the Peer Admin identity you must import the Peer Admin crypto material into your local keyValStore directory before you can deploy a business network using that imported identity

[12:10] 
https://hyperledger.github.io/composer/unstable/installing/development-tools.html
somewhere on this page I think we need to add that the development server you download will create a `PeerAdmin` identity for use in deploying business networks when you run the `createComposerProfile.sh` script. Be worth emphasing that there is no enrollment secret but one currently needs to be provided for the Command line and as such the value used can be anything

[12:11] 
https://hyperledger.github.io/composer/unstable/business-network/bnd-deploy.html
this needs updating with the same text as using-playground-locally.html

**Comment by EdProsser** [comment]
- [ ] https://hyperledger.github.io/composer/unstable/introduction/solution-architecture.html refers to alpha1 in the text and in the graphic

- https://hyperledger.github.io/composer/unstable/business-network/bnd-deploy.html
  - [ ] Hyperledger Fabric Beta should be Hyperledger Fabric v1.0 beta
  - [ ] These security changes mean that Hyperledger Composer cannot support older versions of Hyperledger Fabric v1.0 (e.g. alpha 1). <-- this isn't really that accurate and is confusing - the APIs aren't even the same. We should state our supported environments on one page (don't know where that is though). New reference topic?

- https://hyperledger.github.io/composer/installing/using-playground-locally.html
  - [ ] Hyperledger Fabric v1.0-Alpha1. Should be --> Hyperledger Fabric v1.0 beta 1

- https://hyperledger.github.io/composer/unstable/installing/using-playground-locally.html
  - [ ] I think the following text doesn’t convey what is going on quite right. "The Admin crypto material must be available to the peer when it starts. In order for composer to be able to use the Peer Admin identity you must import the Peer Admin crypto material into your local keyValStore directory before you can deploy a business network using that imported identity"

- https://hyperledger.github.io/composer/unstable/installing/development-tools.html
  - [ ] We need to add that the development server you download will create a PeerAdmin identity for use in deploying business networks when you run the createComposerProfile.sh script. Be worth emphasing that there is no enrollment secret but one currently needs to be provided for the Command line and as such the value used can be anything

- https://hyperledger.github.io/composer/unstable/business-network/bnd-deploy.html
  - [ ] This needs updating with the same text as using-playground-locally.html

**Comment by caroline-church** [comment]
@EdProsser can this be closed?
