### ISSUE TITLE
As a user, identities are mapped to participants using public key signatures

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#1291]
Currently Blockchain identities are mapped to participants in a participant registry using the enrolment ID of the enrolment certificate. This mapping is stored on the Blockchain in the identity registry. This was great when we only supported Hyperledger Fabric v0.6, as certificates had to come from the singleton membership services, and there was no way to get duplicate enrolment IDs.

However this is no longer the case when using Hyperledger Fabric v1.0. The same enrolment ID can be used across multiple organisations, for example for two organisations there may be an admin@org1 and an admin@org2. Additionally, Hyperledger Fabric CA is optional at v1.0, and so there may not be an enrolment ID at all to rely on.

We need to change the identity registry such that it stores a mapping of public keys to participants. I propose that we use the public key fingerprint or thumbprint for the "key" of the mapping, which is generated by hashing the contents of the public key using something like SHA-2.

The gotcha here is that when we issue a Blockchain identity to a participant, we do not get their public key, so we cannot store the public key fingerprint into the identity registry. The public key is only generated when the user is given the enrolment ID and secret and goes through the enrolment process. So there are two options here:

1. Drop support for issuing identities, instead asking the user to provide an existing public key that we can then bind to a participant (see #1290 for information). This is not great as it means the user issuing the Blockchain identity has to figure out how to drive the CA APIs to generate a new Blockchain identity, give that to the target user to enrol, who must pass the generated public key back for the user to bind to the participant. Yuk!

2. Implement some kind of handshake process which uses the enrolment secret as a one-time password at the first time the target user tries to connect to the business network:
   1. New Blockchain identity created, generates enrolment ID and secret.
   2. New enrolment ID, hash of enrolment secret, and participant ID is stored in the identity registry by submitting a modified issue identity transaction.
   3. Enrolment ID and secret are manually passed to target user.
   4. Target user uses enrolment ID and enrolment secret to enrol and get the Blockchain identity.
   5. Target user connects to deployed business network and sends a ping query.
   6. Business network throws error saying "thou must submit first time connect transaction".
   7. Target user submits the new first time connect transaction with the hash of enrolment secret.
   8. First time connect transaction validates enrolment ID and hash of enrolment secret, and stores the target users public key fingerprint into the identity registry.
   9. Target user can now interact with the business network, and the business network uses public key fingerprint matching to identify the user.

**Comment by xuanyue202** [comment]
Hi Simon, I read your new design about the identity and think there might be a problem for the current implementation. Currently hash(PEM.raw) is used as the Identifier. Such design fails to capture the use-case where user re-enrolls a certificate (the old one get expired) or enrolls multiple certificates at the same time (maxEnrollments!=1) and want to use a single identity to represent himself. Each time CA issues a new cert, the fields of Serial Number and potentially Valid From/To will change, which makes hash(PEM.raw) a different value. I am not sure why we do not simply use hash(Common Name, Issuer) as the identifier?

PS. I also left the same comments on RocketChat. But I think putting it here is more convenient for tracking. Thanks

**Comment by sstone1** [comment]
Moving debate around the identifier to #1761.
