### ISSUE TITLE
As a network manager, I can upgrade a business network to a later version of Composer

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#1294]
In Hyperledger Fabric v0.6, the deploy processing was easy. The network starter sent a single deploy transaction to the Blockchain which included the Composer runtime (chaincode/smart contract) and the business network definition. This transaction installed the Composer runtime onto all of the peer nodes and started it. 

In Hyperledger Fabric v1.0, this process is now a lot more involved. There are now multiple actions - some that are performed within an organisation, some that are performed across a consortium (a set of organisations). The network start process is now:

1. Each organisation in the business network must **install** the Composer runtime on all of their endorsing peer nodes. This simply installs the Composer runtime into the file system of those endorsing peer nodes, nothing starts running at this point. The user performing this action must be a peer administrator.
2. Someone from the consortium must **instantiate** the Composer runtime across all of the endorsing peer nodes in the network. This is a single transaction and is subject to an instantiation policy which is configured by the administrators who set up the network in the first place. The transaction starts the installed Composer runtime and calls the `Init` function. The instantiation policy defines which users are able to perform this action.

At a later point in time, the consortium may decide to move to a later version of the Composer runtime to pick up new functionality and fixes. This is a similar process to network start:

1. Each organisation in the business network must **install** the **new version** of the Composer runtime on all of their endorsing peer nodes. This simply installs the new version of the Composer runtime into the file system of those endorsing peer nodes, nothing starts running at this point. The existing instantiated version remains running. Again, the user performing this action must be a peer administrator.
2. Someone from the consortium must **upgrade** the Composer runtime across all of the endorsing peer nodes in the network. This is a single transaction and is subject to an instantiation policy which is configured by the administrators who set up the network in the first place. The transaction starts the the new version of the installed Composer runtime and calls the `Init` function. Importantly the world state and ledger remain in the same state. Again, the instantiation policy defines which users are able to perform this action.

Note that one _interesting_ design decision from the Hyperledger Fabric team is the lack of ability to install the Composer runtime once and instantiate it with multiple names. This means that we have no choice but to install the Composer runtime for each business network, and give it the name of the business network. We have a JIRA open for this: https://jira.hyperledger.org/browse/FAB-3016. The dream is to be able to install the Composer runtime once, maybe even preinstall it, and then just instantiate it for each business network.

This user story is specifically focusing on separating the second step, upgrade, from the deploy processing so that someone from the consortium can run it across all of the endorsing peer nodes in this network.

I propose the following changes:

1. Add `upgrade` to the connector API, `Connection.upgrade(businessNetworkName)`.
2. Expose `upgrade` through the administrative API, `AdminConnection.upgrade(businessNetworkName)`.
3. Expose `upgrade` through the CLI, `composer network upgrade`.

**Comment by davidkel** [comment]
One problem encountered is the issue of runtime resources migration. Take for example the changes to runtime from 0.9.2 to 0.10.0. The runtime resources changed as follows
1. creation of a new metanetwork entry in $sysdata collection
2. a new system Asset registry called Identity was created
3. the removal of the old identity system.
Upgrading the runtime from 0.9.2 to 0.10.0 in this example would require creation of the new assets and migration of any old identity information into the new identity system. This in itself is a complex migration issue, but what if someone was trying to upgrade the runtime from say 0.7.5 or even 0.5.9 where more migration actions would be required or maybe just not possible.
This kind of problem will require a lot more thought on how to tackle and what restrictions might need to be put in place, plus real world migration testing.
This issue will not cover this so an upgrade will only be possible on a semver micro version change, ie from x.y.(z1) to x.y.(z2). changes to the minor or major version of composer means that upgrade will not be possible, even if the runtime doesn't have any breaking resource changes to it.

**Comment by davidkel** [comment]
Completed added Ed in for documentation

**Comment by davidkel** [comment]
```
composer network upgrade [options]

Options:
  --help                       Show help  [boolean]
  -v, --version                Show version number  [boolean]
  --businessNetworkName, -n    The business network name whose runtime will be upgraded  [string] [required]
  --connectionProfileName, -p  The connection profile name  [string] [required]
  --upgradeId, -i              The id of the user permitted to upgrade the runtime  [string] [required]
  --upgradeSecret, -s          The secret of the user permitted to upgrade the runtime, if required  [string]
```
