### ISSUE TITLE
Sample JSON in Playground tutorial not usable as-is

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#1303]
## Context
Playground tutorial at [https://hyperledger.github.io/composer/tutorials/playground-guide.html](https://hyperledger.github.io/composer/tutorials/playground-guide.html).

## Expected Behavior
Copy&paste of sample JSON into Playground should work as-is.

## Actual Behavior
Namespace mismatch with model causes an error.

## Possible Fix
Change the namespace in the doc examples to match the model.

**Comment by Tobias-Hunter** [comment]
This should be covered #1312 as the Playground Guide is being updated completely!
