### ISSUE TITLE
Documentation is incorrect for Local Install

### ISSUE THREAD

**Issue by Tobias-Hunter** [hyperledger/composer#1314]
![image](https://user-images.githubusercontent.com/25635381/27284602-54838668-54f1-11e7-8424-7c753ccc54bc.png)

The Documentation is incorrect here, we connect to the `hlfabric` Connection Profile by default.

Steps to reproduce: https://hyperledger.github.io/composer/installing/using-playground-locally.html
Run through install & it will open the Playground with the `hlfabric` connected!

**Comment by alexsicart** [comment]
Hi @Tobias-Hunter can you close this issue?

Cheers!
