### ISSUE TITLE
Next steps incorrect

### ISSUE THREAD

**Issue by Tobias-Hunter** [hyperledger/composer#1316]
![image](https://user-images.githubusercontent.com/25635381/27284879-668e149e-54f2-11e7-885b-6743a9970ac3.png)

When the new Playground tutorial is introduced this will be incorrect, as the tutorial will now walk you through the Commodities Network & not the Car Auction Network! 

https://hyperledger.github.io/composer/installing/using-playground-locally.html

**Comment by EdProsser** [comment]
This is also fixed.

**Comment by caroline-church** [comment]
@EdProsser Can this be closed?
