### ISSUE TITLE
Editing the active connection profile in Playground causes issues

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1317]
## Context
Local Playground install, connected using hlfabric connection profile.  Click to edit this connection profile and change the name (e.g. I changed it to "hlfv1")
## Expected Behavior
Edit should work, and Playground continue to behave as normal.

## Actual Behavior
A couple of bugs emerge:
- No tick next to any of the connection profiles to show which is in use (so it looks like "none is in use).
- Trying to switch to any IDs causes multiple errors (guessing it's looking for a connection profile with the old name)
- Deploying any changes to the Business Network Definition also fails: "Error: Failed to load connection profile hlfabric. Error was Error: ENOENT: No such file or directory., '/.composer-connection-profiles/hlfabric/connection.json'"

## Possible Fix
I think we need to cascade through some changes to other places when the name of a Connection Profile is changed.

## Steps to Reproduce
1. Install local Playground
2. Go to Connection Profiles page
3. Edit the name of the hlfabric profile
4. Observe the lack of tick, try to switch IDs or edit the Business Network Definition and Deploy the changes.

## Your Environment
Current stable version, MacOS, Chrome

**Comment by sstone1** [comment]
Pretty sure this will have been solved by ID cards!
