### ISSUE TITLE
Removing an ID from the wallet should prompt a confirmation

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1320]
## Context
Removing IDs from the wallet just happens, no confirmation.  If you know the admin secret, that's ok because you can fix things.  If you don't, and you remove the last ID you had that was capable of issuing other IDs, you're in a bit of a jam.

## Expected Behavior
We should probably just be a little more cautious and add a confirm modal on removal.
Something like this perhaps:
![image](https://user-images.githubusercontent.com/7454304/27286886-a9ef276c-54f9-11e7-955f-fbdc1ae9dc0b.png)

## Actual Behavior
Remove works, no prompt to confirm.

## Possible Fix
Add a prompt, innit.  Suggest it could be a little like this:

## Steps to Reproduce
1. Create a participant
2. Issue that participant an ID
3. Add that ID to your wallet
4. Remove it

## Your Environment
Latest stable, MacOS, Chrome

**Comment by caroline-church** [comment]
fixed so closing
