### ISSUE TITLE
invalid validation errors for namespaces in cto files

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1327]
If a cto file contains a namespace that starts with a "i", it is shown in error, for instance

`namespace this.that.more` is fine, but
`namespace this.is.error` will show in error at the ".i" location

## Context
Trying to add a model with a .i namespace entry is not posisble

## Expected Behavior
I should be able to name my namespace without avoiding certain characters

## Actual Behavior
I have to avoid a vowel to get a valid namespace

## Steps to Reproduce
1. If using VSCode plugin, create cto file, type `namespace this.is.error`
2. if using playground, edit namespace to have a ".i" in the name

## Your Environment
Ubuntu, chrome, vscode

**Comment by dselman** [comment]
`this` is a keyword in the grammar (which is based on the JS grammar), so it cannot be used in an identifier. A namespace is declared as a set of identifiers separated by `.`
