### ISSUE TITLE
Add Insurer to the Vehicle Lifecycle sample

### ISSUE THREAD

**Issue by gcharters** [hyperledger/composer#1341]
I'd like to use the vehicle lifecycle sample to demonstration an integration scenario that seems to fit well with the Insurer participant.  This participant, and other aspects of insurance are not currently modelled/implemented in the sample.  This issue covers extending the models and network code to support the Insurer.  I'm proposing the provision of an application for the insurer be covered by a separate issue as it is not required in order to extend the business network for the Insurer and can be added later.

I'm happy to provide pull requests for the above but would appreciate feedback on ideas before I commit too much to code.  I'll add thoughts as comments to this issue and any input would be greatly appreciated.  Many thanks.

## Context
N/A

## Expected Behavior
N/A

## Actual Behavior
N/A

## Possible Fix
N/A

## Steps to Reproduce
N/A

## Existing issues
N/A

## Context
N/A

## Your Environment
N/A

**Comment by gcharters** [comment]
Below are my thoughts on changes to the Vehicle Lifecycle sample to support the Insurer participant.  Comments would be appreciated.

## vehicle.cto

Create a Company type of Insurer (analogous to the ScrapMerchant)

```
participant Insurer extends Company {
}
```

## vda.cto

Define the details required for insurance.

- the insurance company
- the policyNumber
- the expiry date (last valid date)
- the timestamp (is this the timestamp the things was created in blockchain or outside blockchain?  I'm thinking it's the former)

```
concept InsuranceDetails {
  --> Insurer insurer
  o String policyNumber
  o Date expiry
  o DateTime timestamp
}
```

Add InsuranceDetails to the Vehicle asset.  I considered having it on VehicleDetails but I think that concept is purely about describing the car.

```
asset Vehicle identified by vin {
  o String vin
  o VehicleDetails vehicleDetails
  o VehicleStatus vehicleStatus
  o InsuranceDetails insuranceDetails optional
  --> Person owner optional
  o String numberPlate optional
  o String suspiciousMessage optional
  o VehicleTransferLogEntry[] logEntries optional
}
```

A transaction to update the vehicle with Insurance information (analogous to ScrapVehicle).  I included the "logEntries" because it was in ScrapVehicle, but I don't understand how it is meant to be used.  Is this useful and if so, how is it used?

```
transaction InsureVehicle extends VehicleTransaction {
  o VehicleTransaction[] logEntries optional
}
```

**Comment by dselman** [comment]
Moved to: https://github.com/hyperledger/composer-sample-applications/issues/52
