### ISSUE TITLE
Composer playground not importing model cto files

### ISSUE THREAD

**Issue by gcharters** [hyperledger/composer#1355]
I'm trying to drag-n-drop individual .cto files into the Composer playground.  The files are those provided with the vehicle-lifecycle-model.  When I drag-n-drop the file into the "Add a file..." dialog, it correctly detects how many transactions, etc there are, but oftentimes, when I click the "Add" button, nothing happens.  I have not found a way to import the vda.cto file at all.  Sometimes the vehicle.cto file will import, but often it won't

BTW, given the direction to create more modular/reusable models, it might be good to add a bulk upload capability.  Maybe it already exists and I haven't found it yet.

## Context
I consider this a bug because I should be able to add cto files and be told of errors.  This silently fails to add the file.

## Expected Behavior
I should be able to add .cto files

## Actual Behavior
The cto files I add are often ignored (don't appear to import but I don't get an error message).

## Possible Fix
Make the "add" work.

## Steps to Reproduce

1.  Checkout the composer-sample-models repository
2.  Visit http://composer-playground.mybluemix.net
3.  Add each of the cto files from composer-sample-models/packages/vehicle-lifecycle-model/models
4.  Check to see if all the files have imported.

## Existing issues
- [ x] [GitHub Issues](https://github.com/hyperledger/composer/issues)
None found

## Context
Means I can't experiment with model changes easily on the online playground.

## Your Environment

* Version used: N/A
* Environment name and version (e.g. Chrome 39, node.js 5.4):  Tried with Firefox and Chrome 
* Operating System and version (desktop or mobile): Windows 10
* Link to your project: N/A

**Comment by caroline-church** [comment]
done so closing
