### ISSUE TITLE
Protractor Test Addition for GitHub Authentication and BND Import

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1360]
#863 component and building from #1309
- add test that performs import and resource verification of imported samples, driven from the Import 
operation.
- this is made simpler from the recent change to using npm for importing samples

## Context
Manual validation is a waste of time and prone to error. Let's make this automated. 

## Expected Behavior
No human validation required = more time coding features.

## Actual Behavior
time wasted

**Comment by caroline-church** [comment]
@nklincoln can this be closed as don't we now have this?
