### ISSUE TITLE
Embedded connector extremely slow in 0.8 release

### ISSUE THREAD

**Issue by pospi** [hyperledger/composer#1366]
Unsure if this might already be resolved in 0.8.1 (possibly symptomatic of #1263?), but I am finding the embedded connector to be extremely slow since upgrading to 0.8.0.

Here's some output from debugging code I've added:

```
Thu, 22 Jun 2017 08:39:33 GMT composer:test:init initing BrowserFS
Thu, 22 Jun 2017 08:39:41 GMT composer:test:init creating new admin connection
Thu, 22 Jun 2017 08:39:41 GMT composer:test:init registering connection manager
Thu, 22 Jun 2017 08:39:41 GMT composer:test:init creating connection profile
Thu, 22 Jun 2017 08:39:41 GMT composer:test:init connecting...
Thu, 22 Jun 2017 08:39:41 GMT composer:test:init Connected. Load network definintion...
Thu, 22 Jun 2017 08:39:42 GMT composer:test:init Definition OK. Deploying...
Thu, 22 Jun 2017 08:39:42 GMT composer:test:init Deployment OK.
Thu, 22 Jun 2017 08:39:42 GMT composer:test:init Connecting to deployed Composer network...
Thu, 22 Jun 2017 08:41:59 GMT composer:test:init Connection OK- ready for tests!
Thu, 22 Jun 2017 08:41:59 GMT composer:test:ops Running asset creation transaction...
Thu, 22 Jun 2017 08:44:23 GMT composer:test:ops Transaction completed.
Thu, 22 Jun 2017 08:44:23 GMT composer:test:ops Running asset creation transaction...
Thu, 22 Jun 2017 08:46:50 GMT composer:test:ops Transaction completed.
Thu, 22 Jun 2017 08:46:50 GMT composer:test:ops Running asset creation transaction...
Thu, 22 Jun 2017 08:49:09 GMT composer:test:ops Transaction completed.
Thu, 22 Jun 2017 08:49:09 GMT composer:test:ops Running asset creation transaction...
Thu, 22 Jun 2017 08:51:26 GMT composer:test:ops Transaction completed.
Thu, 22 Jun 2017 08:51:26 GMT composer:test:ops Running asset creation transaction...
Thu, 22 Jun 2017 08:53:43 GMT composer:test:ops Transaction completed.
Thu, 22 Jun 2017 08:53:43 GMT composer:test:ops Getting all assets of test.net.model.SimpleAsset type
Thu, 22 Jun 2017 08:54:59 GMT composer:test:ops Assets retrieved
```

So it's taking over 2 minutes to connect and run each transaction; for invokes and queries alike. For some reason the `AdminConnection` seems to be fine but `BusinessNetworkConnection` is super slow. In addition one of my CPU cores is maxed out the whole time it's waiting.

This all used to run in a matter of seconds on 0.7.6; my entire test suite would finish in under a minute and certainly not trigger the test runner's abort timeout like it's currently doing when run with timeouts enabled.

For completeness my workstation is an Intel i7 5500U (2.4GHz) with 8GB RAM.

**Comment by dselman** [comment]
Interesting. Can you describe what operations your test performs. Just simple create/get assets via submitting transactions?

**Comment by pospi** [comment]
Yep, the creation is done with a normal transaction (`bnc.submitTransaction`) which uses `getAssetRegistry` and `assetRegistry.add` within the chaincode runtime. Retrieving them is done with `AssetRegistry.getAll`, in the case of this particular test.

**Comment by pospi** [comment]
Actually, sorry @dselman my mistake- the connection has no timeout issues; our connection handshake checks for an admin participant (`getParticipantRegistry` & `ParticipantRegistry.get`) when connecting so it looks like all the long waits are on reading records from the blockchain. Affects both participants and assets.

**Comment by sstone1** [comment]
@pospi please can you retest on the latest release? We are unable to recreate this problem.
