### ISSUE TITLE
A Section on Operational requirements to configure Composer to work with Hyperledger Fabric V1 are required

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1376]
With our one click installs and dev server setups we create an easy development environment not requiring any work to get up and running using a real hyperledger fabric v1.0 system. We have information about what is required to ensure hyperledger composer is able to work with Hyperledger Fabric 1.0 but it isn't consolidated into a single place. So If you have a pre-configured environment what do you need to do in order to be use hyperledger composer with it.

1. A Connection Profile - Point to the details about V1 connection profiles
2. Importing Of Peer and Channel Admin credentials - point to the import identity command

Provide a concrete example based on the fabric-dev-server setup

**Comment by davidkel** [comment]
Further now this should include
- start/deploy options specific to hlfv1
- identity issue options specific to hlfv1 (eg how to set affiliation and role)
- equivalent API calls that show how to supply these options.

**Comment by davidkel** [comment]
I think this will be covered as part of the tutorial Simon is doing for The hyperledger fabric BYFN.

**Comment by sstone1** [comment]
Looks like it 👍
