### ISSUE TITLE
Move playground prereq info out of doc and include tutorial link in the playground

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#1379]
If someone is trying to use the playground with a browser that is likely to cause massive issues, we should warn them directly in the UI. It would also be useful to include a link to the tutorial.

## Context

Even though anyone can get to the online playground directly, and there is a "Try it online" button on the first page of the Hyperledger Composer site, there is prereq information in the documentation, along with suggestions on what to do next. Having an 'install' guide to "Try Online Playground" is pretty odd to begin with, and the method of launching the playground in that topic is an unfriendly link...

> The Online Playground can be accessed here: composer-playground.mybluemix.net

## Expected Behavior

I should be able to go directly to the playground without requiring information from the documentation.

## Actual Behavior

The documentation contains a topic about 'installing' the online playground, which mentions 'modern browsers', requirement for a github account, and links to tutorials.

## Possible Fix

- [ ] Add basic checking to the playground to warn someone if they are likely to experience problems due to an outdated browser. (Ideally based on the functionality required, not specific browsers!)

- [ ] Add link to tutorial and any other useful information to the splash screen

- [ ] Remove redundant information from documentation

**Comment by Tobias-Hunter** [comment]
![splash_screen](https://user-images.githubusercontent.com/25635381/27486803-aa7dbb84-5829-11e7-927b-737f2f477f7a.gif)

Here's something I've been working on @jt-nti - will need help with the tests!

**Comment by EdMoffatt** [comment]
When I last spoke to @Tobias-Hunter about this, I know he was thinking that having "Follow the Tutorial" as the primary action *before* it's built into the Playground feels kinda weird.  I see his point too - it's odd that the primary action immediately takes me *away* from Playground.

As such, Toby's suggestion was that we keep the main call to action we have now ("Let's Blockchain!") and add a much less prominent link to open the Tutorial, that'll be best for now.

@jt-nti and I also had a brief discussion about what a user would see if we detect that they're using an unsupported browser...  So I've thrown together a quick mockup of what the splash behaviour might be in those 2 situations:

![image](https://user-images.githubusercontent.com/7454304/27794231-33ed8bfc-5ff9-11e7-8aa6-5f5b78cb90ea.png)

Happy to discuss thoughts!

I'm also gonna now go find the footer bar issue and see whether "Playground Tutorial" might be a useful link to ad in there too (if there's room and it makes sense!)

**Comment by Tobias-Hunter** [comment]
Really like this @EdMoffatt, perhaps we could include something here with clearing local storage? 🤔

**Comment by jt-nti** [comment]
@Tobias-Hunter @EdMoffatt just opened #1447 re: clearing local storage

**Comment by EdMoffatt** [comment]
The aspiration of 1447 is good!  Makes sense to track that work separately, so for this piece I think all we need is an illustration for the "Unsupported Browser" case, and the design is ready to go.  As our resident illustration king, I assign Toby :)

**Comment by Tobias-Hunter** [comment]
![image](https://user-images.githubusercontent.com/25635381/27864867-4230ba78-6188-11e7-98f5-890d3b8957d9.png)
This is my favourite illustration so far, will pull together a hi-fi for this modal now!

**Comment by Tobias-Hunter** [comment]
![fabric composer playground define 2 copy 92](https://user-images.githubusercontent.com/25635381/27871276-16ea9360-619d-11e7-968f-87a1d45a5df2.png)

Hi-Fis for the Unsupported Browser page, which is similar to our 404 page! 🤘🏻
Here is the illustration file: [unsupport TMH v0.1.svg.zip](https://github.com/hyperledger/composer/files/1125142/unsupport.TMH.v0.1.svg.zip)

**Comment by winslet** [comment]
looks good to me, lets ship it! 🌮
