### ISSUE TITLE
As a user I can import/export connection profiles to/from Composer Playground

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#139]

**Comment by EdMoffatt** [comment]
Just leaving a note to point out this is explicitly *not* in the latest low-fis, because they're concentrated for now on the "online Playground", which will not support swapping of connection profiles yet.

**Comment by EdMoffatt** [comment]
Designs for this now available on Box: https://ibm.box.com/s/xovw0ppvduultzrhkauiokvqxg97d0no

This includes the change of having the web Playground not include a Connection Profiles page at all, but instead a "Get local version" link, which is on the nitpicks list with me assigned...  That change also relies on the footer bar being there to display the version and contact info...  A few changes that need to be done together stacking up here ;)

Anyhow, over to @winslet next on this one for Visual Design!

**Comment by EdMoffatt** [comment]
Capturing some discussions today...

1. Rather than have new profile creation in a modal, we're instead going to offer import (drag/drop) or selecting v0.6 or v1.0.  If they select one of the Fabric version options, they then hit Add, and what they get is a new, empty connection profile in edit mode.

2. Actions on a profile that's in edit mode are Cancel and Save

3. If you cancel on a newly created profile, that just gets rid of it

4. If you Save a connection profile that doesn't work...  That's fine.  You've just left a broken one there.

5. If you then try to Use a broken one...  We need to fail connecting and fall back to the one they were using previously.

6. If you try to Save edits to the one you're using, and they have the effect of breaking it...  We should probably help you avoid that.  Suggest one way would be to store the previous state, and then if Saving the changes means that the connection fails, revert back to the previous working version (and display an inline alert saying that the deploy failed, and we've rolled you back to the previous working configuration).

7. If you *really* want to break a profile you're using, you can always switch over to the Web Browser profile (which it will not be possible to delete), and then wreck your other profile to your heart's content ;) [legitimately though, you might actually be wanting to get ready for a new peer coming up or something sensible, not just "wrecking it" ;) ]

**Comment by winslet** [comment]
Okaaay this is a big one, hope this all makes sense...

**TIP** The best way to digest this is alongside the click through prototype here: https://xd.adobe.com/view/ed7a097f-014e-42e7-aae9-83a95f82d8a8/


### Connection Profile Page - Basic

![fabric composer playground define 2 copy 98](https://cloud.githubusercontent.com/assets/13980028/24200174/2721f1c4-0f04-11e7-8418-2d50809e8eb6.png)

### Connection Profile Page - Edit selected (when in use)

![fabric composer playground define 2 copy 96](https://cloud.githubusercontent.com/assets/13980028/24200186/3783694e-0f04-11e7-87bd-4baf368abb03.png)

### Connection Profile Export

![fabric composer playground define 2 copy 93](https://cloud.githubusercontent.com/assets/13980028/24200255/7b7c816c-0f04-11e7-8a0f-2fefb2e0f480.png)

### Import/Create connection profile modal

![fabric composer playground define 2 copy 94](https://cloud.githubusercontent.com/assets/13980028/24200285/9b9fe984-0f04-11e7-9808-6e10f1697a53.png)

#### & File upload...

![fabric composer playground define 2 copy 101](https://cloud.githubusercontent.com/assets/13980028/24200316/b473ea50-0f04-11e7-8c4a-61d8615acd3e.png)

### Create connection profile - v0.6

![fabric composer playground define 2 copy 94](https://cloud.githubusercontent.com/assets/13980028/24200338/c6e8881c-0f04-11e7-8ec3-ae79ea229dcf.png)
--
![fabric composer playground define 2 copy 97](https://cloud.githubusercontent.com/assets/13980028/24200346/cdcba614-0f04-11e7-8c7d-64a49f7c3621.png)
--
![fabric composer playground define 2 copy 95](https://cloud.githubusercontent.com/assets/13980028/24200358/d817b766-0f04-11e7-920a-9c2d7ed20751.png)

### Create Connection profile v1.0

![fabric composer playground define 2 copy 100](https://cloud.githubusercontent.com/assets/13980028/24200379/e9bdccbc-0f04-11e7-9033-b751e1910825.png)
--
![fabric composer playground define 2 copy 99](https://cloud.githubusercontent.com/assets/13980028/24200432/f171c30a-0f04-11e7-94d3-2706e8f0efed.png)
--
![fabric composer playground define 2 copy 102](https://cloud.githubusercontent.com/assets/13980028/24200438/f898a5ae-0f04-11e7-9cd1-a57e5a874145.png)

### Image Assets & Marketch

**Marketch:** [Connection_Profiles_FC_SW_1.zip](https://github.com/fabric-composer/fabric-composer/files/861551/Connection_Profiles_FC_SW_1.zip)
**Illustration:** [Zip_Upload_Illustration.zip](https://github.com/fabric-composer/fabric-composer/files/861550/Zip_Upload_Illustration.zip)

**Comment by winslet** [comment]
# Updates following conversation on 23/3 re: v1.0 screens

### Creating or editing a connection profile if v1.0

![fabric composer playground define 2 copy 103](https://cloud.githubusercontent.com/assets/13980028/24257814/c0fcecec-0fe3-11e7-8320-5021202f980c.png)

### Certificate upload/copy paste

![fabric composer playground define 2 copy 105](https://cloud.githubusercontent.com/assets/13980028/24257829/cf17d5bc-0fe3-11e7-825b-f13aa016c0c4.png)

### Error state on required fields and hover state for certificate buttons

![fabric composer playground define 2 copy 104](https://cloud.githubusercontent.com/assets/13980028/24257850/dbc37cf8-0fe3-11e7-8eb8-121a658de114.png)

@Jakeeyturner let me know if you've got any questions?

**Comment by winslet** [comment]
Update: 

### Saved screen for v1.0 profiles

![fabric composer playground define 2 copy 102](https://cloud.githubusercontent.com/assets/13980028/24258336/58006cd0-0fe5-11e7-9dc2-a3e9f264be14.png)

**Comment by Jakeeyturner** [comment]
We will need to provide some kind of feedback to a user interacting with a form. If their input isn't valid and doesn't meet the criteria (e.g. required field, must be a url, must be a number, etc.) we should give them a reason as to why it's not valid. I notice that we should underline the input box if the current value is invalid, but I don't feel like this is sufficient from a users perspective.

I think my quick implementation might need some design love!
![capture](https://cloud.githubusercontent.com/assets/10009752/24461461/15c49018-1499-11e7-8314-99801ce4741a.PNG)

**Comment by Jakeeyturner** [comment]
Assuming the user decides to upload certificates for the orderers and peers which means TLS is enabled, should we allow users to edit and view these certificates? This hasn't been covered by the hifis and I'm unsure what should happen in this case.

**Comment by winslet** [comment]
@Jakeeyturner re the error fields, hopefully the below will be useful:

![text entry fields](https://cloud.githubusercontent.com/assets/13980028/24699134/e95d24ac-19ea-11e7-8b0a-30d73af550d3.png)

**Marketch:** 
[Text_Entry_Fields.zip](https://github.com/fabric-composer/fabric-composer/files/895765/Text_Entry_Fields.zip)

Per the second question, im not sure I totally understand, if they are going back to edit a previously entered certificate, if when they selected the certificate icon we could take them back to the modal shown here: https://cloud.githubusercontent.com/assets/13980028/24257829/cf17d5bc-0fe3-11e7-825b-f13aa016c0c4.png would that solve the problem?

**Comment by Jakeeyturner** [comment]
Thanks @winslet, those will definitely help.

Regarding my second point, your hifis cover editing certificates (my mistake!).
What I actually meant to say was that, when I view a V1 connection profile, should I be able to click something and see the certificates for each peer and orderer? - https://cloud.githubusercontent.com/assets/13980028/24258336/58006cd0-0fe5-11e7-9dc2-a3e9f264be14.png

**Comment by Tobias-Hunter** [comment]
.XD File Box Link: https://ibm.box.com/s/sgz0uhb37c6x81zt7jp4qgxfcnvm0edr

Talked through this with @winslet, any questions don't hesitate to ask! 😛

**Comment by EdMoffatt** [comment]
Suggested copy tweaks for ya, @winslet and @Tobias-Hunter :

DIALOG BOX TITLE:
Connect with an identity

COPY BELOW THE LIST OF IDs:
Don’t have an ID & Secret?  An existing user of this Connection Profile will need to issue you one.

BUTTONS:
Cancel, Connect

ON THE “NEW IDENTITY” TAB, LABELS FOR INPUT BOXES:
ID Name:
Secret:

FAIL STATE ON “Connect” CLICK FOR AN ID FROM WALLET: The identity was not accepted by this Connection Profile.  Please try another.

FAIL STATE ON “Connect” CLICK FOR AN ID NAME/SECRET PAIR:
The ID name and/or secret you entered is incorrect, please try again!

(This is based on looking at how we label things on other screens!)

**Comment by winslet** [comment]
Here come the hifi's!

(again please follow Toby's XD link above for the full flow - or drop me a message if any questions).

### 1. Connect with a pre-existing identity

![fabric composer playground define 2 copy 93](https://cloud.githubusercontent.com/assets/13980028/24856714/9c0cf62c-1ddd-11e7-9d16-233cf7fc4b61.png)
![fabric composer playground define 2 copy 94](https://cloud.githubusercontent.com/assets/13980028/24856722/9ff6e4be-1ddd-11e7-8c67-6aeed36944c9.png)
![fabric composer playground define 2 copy 95](https://cloud.githubusercontent.com/assets/13980028/24856726/a31446b4-1ddd-11e7-9df6-65509b49d040.png)
![fabric composer playground define 2 copy 96](https://cloud.githubusercontent.com/assets/13980028/24856731/a5f59982-1ddd-11e7-9ee1-7306d804998e.png)

### 2. Connect with a new Identity

![fabric composer playground define 2 copy 97](https://cloud.githubusercontent.com/assets/13980028/24856751/b45182b6-1ddd-11e7-8870-3fd4f76b59ca.png)
![fabric composer playground define 2 copy 98](https://cloud.githubusercontent.com/assets/13980028/24856754/b685628c-1ddd-11e7-9414-9be96fdcd41b.png)
![fabric composer playground define 2 copy 99](https://cloud.githubusercontent.com/assets/13980028/24856758/b924aa2a-1ddd-11e7-92b5-d4df64981dac.png)
 
**Marketch:
[Verify_Identity_FC_SW_1.zip](https://github.com/fabric-composer/fabric-composer/files/909700/Verify_Identity_FC_SW_1.zip)

@Jakeeyturner any more questions or need any edge case designs let me know 👍 
**

**Comment by EdMoffatt** [comment]
Moving this one over to Playback 4.  It's also currently waiting on the work that @Tobias-Hunter is doing on #655 - so Toby should post the relevant parts of those designs here once done too, to unblock @Jakeeyturner ;)

**Comment by Tobias-Hunter** [comment]
@Jakeeyturner Should be unblocked already with those Hi-Fi's! 😉
