### ISSUE TITLE
Cannot create ACL file in playground

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#1392]
It doesn't look like there is a way to create an ACL file in the playground.

## Context

I had the playground open with no ACL files while trying to create a new business network from scratch. It only seems to be possible to create .cto or .js files when adding a file.

## Expected Behavior

Importing an existing .acl file should work (it used to?)

## Actual Behavior

The .acl doesn't seem to appear in playground after importing even though no errors were reported

## Steps to Reproduce

1. Open playground
2. Import .acl file
3. Check .acl file exists in playground

**Comment by sstone1** [comment]
Fixed, try out: http://composer-playground-unstable.mybluemix.net/
