### ISSUE TITLE
As a new user, I should be able to understand the modelling language from the reference documentation.

### ISSUE THREAD

**Issue by EdProsser** [hyperledger/composer#1398]
Currently, the reference docs for the modelling language aren't _bad_, but they don't do a good job of expressing the limits and potential of the language.

I'd like to sit down with @sstone1 or @dselman and go through them, so I can update the language reference to the standard of the rest of our docs.

**Comment by alexsicart** [comment]
Hi @EdProsser is already solve your issue?

Cheers!
