### ISSUE TITLE
When starting playground I get the error t:Failed to find namespace org.acme

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1401]
![image](https://user-images.githubusercontent.com/25582377/27645695-9d54e1a0-5c1e-11e7-9d67-8eb1117285c7.png)

recording just in case it hasn't been fixed yet. I see this, Jeff Garratt also saw this.

**Comment by davidkel** [comment]
then you get
![image](https://user-images.githubusercontent.com/25582377/27645748-ce0f2d28-5c1e-11e7-9d09-c5739b83ced1.png)

**Comment by dselman** [comment]
What version?

**Comment by davidkel** [comment]
Not quite latest, about 5 commits behind. Wanted to record it somewhere for now, don't think it is my code change that has caused it.

**Comment by davidkel** [comment]
Moved to the latest commit, incognito window so clean local storage and the first thing I get presented with is
![image](https://user-images.githubusercontent.com/25582377/27653302-96a2e07e-5c36-11e7-91a1-1bbbd7056939.png)

**Comment by davidkel** [comment]
Guess it is because the samples currently aren't system model aware yet.
