### ISSUE TITLE
As a Playground user, I can deploy new Business Networks to existing Connection Profiles

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1414]
From the My Wallet screen, a user should be able to click the "Deploy" icon/button next to the name of a Connection Profile (the sub-headings that ID Cards are organise into on this screen) and deploy a new business network.

If certificates are already available for Installing and Starting Business Networks on that Connection Profile, the flow will go as follows:

1. Name the new Business Network
2. Provide a description
3. Choose the sample network to base it off of - the files from said network will be loaded in as the starting point for the new business network

The main screen to hi-fi for this is this one:
![deploy new 01](https://user-images.githubusercontent.com/7454304/27698768-fbba8c14-5cef-11e7-9fda-7bcc5d0955e0.png)
(The panel on the right should populate as options on left are filled in or selected.  By default the "Basic Sample Network" is selected, so that info will be there along with the connection profile that is being deployed to.  The name and description get added as the user fills them out, then the Deploy button becomes active.  Clicking a different sample to base the network off will result in the content on the right updating too.

We also need to consider what happens if the user has not yet provided the certificates needed to install and/or start business networks on this connection profile (or if the ones they have stored are no longer being accepted).
This case is covered in #1426

**Comment by winslet** [comment]
Please see #1426 for hifi's on this one 🎃

**Comment by EdMoffatt** [comment]
Paging @EdProsser - according to the mass derision of the team, "This new Business Network is **based off of** this template" is not very good English and stuff.

Could you please suggest a better wording for that bit over on the right hand side of the mockups where it says "BASED OFF OF:" ?  Thanks 🌾

**Comment by EdMoffatt** [comment]
Swooping back here to answer the question "what if you click "IMPORT/REPLACE" from inside a Business Network (i.e. from the Define tab):

![image](https://user-images.githubusercontent.com/7454304/28514714-f828ac36-7052-11e7-941a-af80f945e9e5.png)

Obviously that's just one screen ;)  The actual full UX is shown in thid here XD mockup: https://xd.adobe.com/view/da1a417d-97c0-4e88-ae91-8edde3e2c251/

I'll assign this one over to Sam for his attention next!

**Comment by winslet** [comment]
Hifi's!

### Selecting import/replace
![fabric composer playground define 2 copy 92](https://user-images.githubusercontent.com/13980028/28516408-0da896f6-7059-11e7-823a-e68a0139d774.png)

### Drag n drop state
![fabric composer playground define 2 copy 95](https://user-images.githubusercontent.com/13980028/28516445-2de986c8-7059-11e7-85f6-cc704b291f55.png)

### Drag n drop post upload 
![fabric composer playground define 2 copy 94](https://user-images.githubusercontent.com/13980028/28516462-40324478-7059-11e7-944f-934731fcb0dc.png)

### Selecting other business network
![fabric composer playground define 2 copy 93](https://user-images.githubusercontent.com/13980028/28516484-544c43be-7059-11e7-87b8-975f34ef42cb.png)

### Deploy notification
![fabric composer playground define 2 copy 87](https://user-images.githubusercontent.com/13980028/28516764-4682de72-705a-11e7-94d7-2c8e379071e5.png)

**Assets:**
Available in this issue: https://github.com/hyperledger/composer/issues/657

**Marketch:**
[Import_Replace_SW_1.zip](https://github.com/hyperledger/composer/files/1169356/Import_Replace_SW_1.zip)


Any questions lemme know! 🍟

**Comment by caroline-church** [comment]
done so closing
