### ISSUE TITLE
As a Playground user, I can import an ID Card into My Wallet

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1415]
Child of #902 

Clicking the "Import ID Card" button on the "My Wallet" screen should result in a slide-in menu on the left where a .cid file can be dropped, or the user can browse to find one:

![import 01](https://user-images.githubusercontent.com/7454304/27699456-40fff9a6-5cf2-11e7-9efd-28265c036a28.png)
![import 02](https://user-images.githubusercontent.com/7454304/27699458-41161830-5cf2-11e7-907b-b9582b617567.png)
![import 03](https://user-images.githubusercontent.com/7454304/27699459-4116c1fe-5cf2-11e7-9007-ba0bd29219d9.png)
![import 04](https://user-images.githubusercontent.com/7454304/27699460-411838ea-5cf2-11e7-9920-dc812c55accd.png)

**Comment by winslet** [comment]
Hifi's:

### User selects "import ID card"

![transaction registry copy 4](https://user-images.githubusercontent.com/13980028/27799258-60f901c2-600c-11e7-986d-57e01d2d6fc7.png)

### Panel slides in from left allowing user to upload .cid (composer ID) files via drag n drop or by clicking "browse"

![transaction registry copy 5](https://user-images.githubusercontent.com/13980028/27799286-7f31f478-600c-11e7-95fc-49e36a1f7ac6.png)

### We preview the card information (allowing the user to click the cross in the top right of the card to return to the previous screen). This is also where the "import" button becomes active

![transaction registry copy 6](https://user-images.githubusercontent.com/13980028/27799317-a2ab431e-600c-11e7-8cd4-69996a640e90.png)

### User clicks import and is notified that a new ID card has been added

![transaction registry copy 8](https://user-images.githubusercontent.com/13980028/27799344-b5be0590-600c-11e7-848c-90e54d64941c.png)


Marketch:
[Composer_Import_CID_File.zip](https://github.com/hyperledger/composer/files/1120004/Composer_Import_CID_File.zip)

New upload image with CID file:
[CID_Upload.zip](https://github.com/hyperledger/composer/files/1120005/CID_Upload.zip)

Any questions let me know! 🍔

**Comment by winslet** [comment]
**Update**

Could we please add in a slight background grey-out behind the slide section eg:

![image](https://user-images.githubusercontent.com/13980028/27822122-77a53a7c-609c-11e7-942f-7fe05f9e383d.png)

Thanks!

**Comment by winslet** [comment]
@jt-nti new .card illustration here:

[CARD_upload.zip](https://github.com/hyperledger/composer/files/1158657/CARD_upload.zip)

<img width="182" alt="card_upload 2x" src="https://user-images.githubusercontent.com/13980028/28360438-570c5c28-6c6d-11e7-9d4e-b43c8067c0cf.png">

**Comment by jt-nti** [comment]
Example **.card** file which should connect to a one script installed composer network (rename to **hlfv1.card**)...


[hlfv1.zip](https://github.com/hyperledger/composer/files/1207720/hlfv1.zip)

**Comment by jt-nti** [comment]
Done
