### ISSUE TITLE
As a Playground user, I can create a new ID Card by manually entering details

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1423]
Child of #902 .

ID Cards can be imported as shown in #1415 

They can also be created via the following flow:

1. Click the "Create ID Card" button on the My Wallet screen
2. Select from existing Connection Profiles, or a new hlfv1 or v0.6 profile
3. (iff new profile was selected) define that new profile
4. Provide either: i) ID + Secret or ii) Business Network name + Public Key + Private Key + give the ID Card a name

This is laid out in this mockup (click through the different options to see all the different paths):
https://xd.adobe.com/view/5529d694-9d75-4d51-822c-c1d25cb358c8/

A few useful key screens for hi-fi treatment...

Connection Profile selection when there are quite a few Connection Profiles (this number seems pretty ridiculous to me, but you never know ;) ):
![loadsaconnectionprofiles](https://user-images.githubusercontent.com/7454304/27732945-926ecc2e-5d8b-11e7-8969-c3700831a84b.png)
(There should probably be some sort of ordering to the existing Connection Profiles - the ordering here should match the ordering in the My Wallets screen, so we should either be displaying them in the order they were added, or alphabetical order.  No strong preference from me.)

Then there's the existing "Create Connection Profile" content, placed in a different context - the low-fis are VERY low-detail here because we should be seeking to re-use existing content from elsewhere in the UI :)
![create id 02](https://user-images.githubusercontent.com/7454304/27735025-6c2d5882-5d95-11e7-85f0-398c09ec78b6.png)
**NOTE: Since we're not doing the "create one then edit it" model anymore, I'd prefer to have an empty name that the user is required to fill out than what we currently do (give it a default name).**

Then there's placing the existing "provide me an ID + Secret" content to re-position from elsewhere in the existing UI...
![create id 03](https://user-images.githubusercontent.com/7454304/27735069-a744d56c-5d95-11e7-9944-6a0d778f04bf.png)

And we also want to support creating an ID by specifying the business network name + providing certificates.  This isn't supported yet, but will mirror some similar certificate-upload stuff on deploying a new business network - #1414 .  Need something that will support either copy/paste of certificate contents or upload of a .pem file:
![create id 04](https://user-images.githubusercontent.com/7454304/27735112-d45fab80-5d95-11e7-849c-d5e1f376822b.png)

I think that's about it for this one!

**Comment by winslet** [comment]
Hifis!

Same order as above:

![transaction registry copy 24](https://user-images.githubusercontent.com/13980028/28115777-2c14170a-66fe-11e7-8c29-a03ede72815a.png)

![transaction registry copy 25](https://user-images.githubusercontent.com/13980028/28115789-3821137c-66fe-11e7-9021-dcea85d29f60.png)

![transaction registry copy 26](https://user-images.githubusercontent.com/13980028/28115795-3d2475ee-66fe-11e7-89d4-680084468369.png)

![transaction registry copy 27](https://user-images.githubusercontent.com/13980028/28115797-4293e49c-66fe-11e7-8d35-0b3b6a722428.png)

**Marketch:**
[Composer_ID_Creation_SW_2.zip](https://github.com/hyperledger/composer/files/1141810/Composer_ID_Creation_SW_2.zip)

I dont believe there's any more assets needed here, please let me know if you have any questions or if I have missed anything 🍔

**Comment by caroline-church** [comment]
done so closing
