### ISSUE TITLE
As a Playground user, I can edit connection profile details from the My Wallet screen

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1425]
Child of #902 

This one should hopefully be able to re-use work done on #1423 .  So much so that I don't think we'll even need any separate hi-fis, so just assigning @winslet for his awareness of all the work here rather than to ask him to do anything :)

User needs to be able to access an editable version of the connection profile info by clicking the edit button next to its name in the My Wallets screen.

If they make any changes, the save button at the bottom will activate.

![edit profile 1](https://user-images.githubusercontent.com/7454304/27735867-8985f458-5d99-11e7-956e-99eb5f6dfaeb.png)
![edit profile 2](https://user-images.githubusercontent.com/7454304/27735868-89862bd0-5d99-11e7-8df7-10e617656117.png)
![edit profile 3](https://user-images.githubusercontent.com/7454304/27735866-8985a304-5d99-11e7-998d-cc5752aae7c7.png)

**Comment by EdMoffatt** [comment]
Because we're looking for some stuff that can be started on in Sam's holiday absence, and because this screen seems reasonably safe since it's mostly re-using existing content...  Here's my bash at a hi-fi ;)

![edit connection profile](https://user-images.githubusercontent.com/7454304/27875267-7cfde096-61aa-11e7-948a-508df8e21664.png)

- The arrow+"My Wallet" are a button that has the same effect as "Cancel".
- The Save button will also take you back to My Wallets (as well as saving any changes, obviously)
- The form has been extended wider than it is in the current UI, since we have more space.  The area left empty on the RHS is enough to allow the "side-slide-in" component to also fit there if needed - see the work @jt-nti is doing on #1415 for reference!
- I've also removed the sort of "this is a tile" look that the current UI had, and just made the whole background white, because the tile look just doesn't seem to fit so much in this context!
- The Cancel/Save buttons are left aligned because I have this mental model of the My Wallets screen being on the far left and other stuff sort of sitting off to the right of it...

**Comment by winslet** [comment]
Slight update to the above since working on some other wallet stuff:

![transaction registry copy 20](https://user-images.githubusercontent.com/13980028/28018334-c998748e-6574-11e7-8bd2-c82e143d154a.png)

Not many changes from the original, we're going to keep the background white section. Dont think we've got any new assets.

**Marketch:**
[Composer_Wallet_Edit_SW_2.zip](https://github.com/hyperledger/composer/files/1135471/Composer_Wallet_Edit_SW_2.zip)

Any questions/problems please let me know 🐎

**Comment by caroline-church** [comment]
done
