### ISSUE TITLE
Playground should prompt the user to edit certificate details if a Deploy fails

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1426]
Child of #902 

Issue #1414 covers the case of "no certificates present" and "certificates present, and they work".

There is also a failure state that Playground should handle, where certificates *are* present, but when we try to deploy it doesn't work - e.g. because they or not the correct certificates or because the Fabric config has changed to require different certificates.

In this case, the flow would be:

1. User clicks Deploy button on the My Wallets page to deploy a new business network
2. Certificates are present, so we don't prompt them
3. They configure the business network they want to deploy and hit the deploy button
4. Deploy fails - error message offers 2 options: "Cancel" or "Edit Certificates"
5. Cancel returns the user to My Wallets or...
6. "Edit Certificates" retains the info about the network the user is trying to deploy in the right-hand-section of the screen, but replaces the main left-hand-content with the "provide certificates" screen for them to swap out the certificates
7. The user can try again by clicking the Deploy button again
8. If it works, excellent :)  If it fails, they're looping back to step 4. of this flow

This is another one that I don't think should need any hi-fi work from @winslet , but I'm assigning him anyway for his awareness.  Should be able to make this work entirely with existing components I hope!

![failure to deploy 1](https://user-images.githubusercontent.com/7454304/27736754-76e7e4d8-5d9d-11e7-9d2e-65b382850f44.png)
![failure to deploy 2](https://user-images.githubusercontent.com/7454304/27736755-76ea3ef4-5d9d-11e7-9a01-b36bde966ed0.png)
![failure to deploy 3](https://user-images.githubusercontent.com/7454304/27736753-76e78772-5d9d-11e7-8f19-a256b49ab20a.png)

**Comment by winslet** [comment]
Hifi's! (after much discussion)

### Deploy new business network 

![transaction registry copy 21](https://user-images.githubusercontent.com/13980028/28071230-3e726404-6647-11e7-9b2f-7bbe7e983302.png)

### Deployment failed (no certificates)

![transaction registry copy 22](https://user-images.githubusercontent.com/13980028/28071288-6675649c-6647-11e7-8f2c-a079aea00d29.png)

### Certificate addition

![transaction registry copy 23](https://user-images.githubusercontent.com/13980028/28071298-7238ab7c-6647-11e7-9a99-ac2d8dfbd772.png)

**Marketch:**
[Composer_Wallet_Deployment_SW_2.zip](https://github.com/hyperledger/composer/files/1139042/Composer_Wallet_Deployment_SW_2.zip)

**New Assets:** 
All of these can be found in the existing issue #657 please refer to the assets uploaded there for new images. 

Thanks and any questions please let me know! 🌯

**Comment by caroline-church** [comment]
@winslet What does the import screen look like if you haven't selected a network?

**Comment by winslet** [comment]
@caroline-church we would like to select one by default - can it be the Basic Sample Network plz :)

**Comment by caroline-church** [comment]
@winslet What should it look like if you are importing from the editor screen?

**Comment by caroline-church** [comment]
@winslet what should it look like before you have typed a network name and description?

**Comment by winslet** [comment]
@caroline-church 

1. This is the file import/replace? We do not have a final design for this yet. Is that needed imminently? 

2. Placeholder text this please:

![image](https://user-images.githubusercontent.com/13980028/28307444-d24138d8-6b9a-11e7-91b5-ed7b51f09e89.png)

**Comment by caroline-church** [comment]
@winslet 

1. Is it going to be completely different from deploying a new network or just a little bit different as you won't need to set the name or the description?

2. What should you see on the bar on the right when you just have the place holder text?

**Comment by winslet** [comment]
@caroline-church 

1. Probably more likely to be similar than different? (we honest have not thought about this yet - so that is an educated guess).

2. Will this work? :) 
![image](https://user-images.githubusercontent.com/13980028/28308312-b256c486-6b9d-11e7-807c-1908938b2c1f.png)

**Comment by caroline-church** [comment]
@winslet yeah thats good thanks :)

**Comment by caroline-church** [comment]
@winslet If you are dragging on dropping a file what should it look like?

**Comment by EdMoffatt** [comment]
I'm gonna bump this one down to a P2, as I think we agreed that dealing with a failed Deploy like this won't be in our first pass implementation of ID Cards.  Obviously we'll come back to it after some testing of the first pass!

**Comment by sstone1** [comment]
As far as I know, nobody is working on this at the moment or planning to work on it, so closing. 
If somebody wishes to work on this in the future, then please reopen this issue or open a new issue.
