### ISSUE TITLE
As a Playground user, I can remove an ID from My Wallet

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1428]
Child of #902 

Pretty simple one, shouldn't require any hi-fis!

Clicking the trash-can icon on an ID Card should result in a modal to confirm that you want to remove that ID card.  That modal should use the red primary button that we use on delete actions elsewhere in the UI.  If the user confirms the action, a top-right-style notification will confirm that it worked.

![delete 1](https://user-images.githubusercontent.com/7454304/27737290-829976a0-5d9f-11e7-8b8b-505c24640b0a.png)
![delete 2](https://user-images.githubusercontent.com/7454304/27737289-82989b90-5d9f-11e7-9a98-6a87a928b1f5.png)
![delete 3](https://user-images.githubusercontent.com/7454304/27737291-829dae3c-5d9f-11e7-8040-7d530cdd9bd2.png)

**Comment by winslet** [comment]
Hifis:

### Hover state on delete button:

![transaction registry copy 10](https://user-images.githubusercontent.com/13980028/27823798-4d97a03e-60a2-11e7-9bc1-f045c7126294.png)

### Confirm deletion modal

![transaction registry copy 11](https://user-images.githubusercontent.com/13980028/27823820-5abb9f40-60a2-11e7-9f65-01f294d1ab87.png)

### Removal notification

**Comment by caroline-church** [comment]
assigned to Joe Pavitt

**Comment by caroline-church** [comment]
done so closing
