### ISSUE TITLE
The Diagnostics page needs an overhaul.

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1435]
The diagnostics page is out of date and doesn't explain things well
https://hyperledger.github.io/composer/problems/diagnostics.html

For example
- references to some config module and what looks like an old getting started definition but there is no explanation on what the config module is, where the file should go and how all of this works or good examples of how or why you would do this. 
- Chaincode container diagnostics is limited and only refers to v0.6. We should include information pertinent to v1.0

Ideally we should provide information about how to get diagnostic information for all components
- User Applications
- Business Networks
- CLI
- Rest Server
- Playground
- Composer Runtime
- Fabric

**Comment by alexvicegrab** [comment]
Hello, is there any progress on this? It's rather unclear how to debug HL Composer and set up Winston to work. Even a basic example and the location where the config file should go would be helpful, as well as how to make this work when running:

```
composer network start
```

rather than

```
node Application.js
```

**Comment by davidkel** [comment]
The new diagnostics page hasa lot of info, but still doesn't cover all the composer components plus is not really designed to help users help themselves or to describe how to gather diagnostics easily for use by others. If we improve this page, hopefully we can just reference it as a place for people to help themselves.
