### ISSUE TITLE
Rest Server should have dynamic logging capabilities

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1436]
The Rest server is a long running server and there could be a need to get diagnostic information from it without having to stop and start it. We should look at how to provide dynamic logging control of the rest server for diagnostic purposes.

**Comment by sstone1** [comment]
As far as I know, nobody is working on this at the moment or planning to work on it, so closing. 
If somebody wishes to work on this in the future, then please reopen this issue or open a new issue.
