### ISSUE TITLE
As a user, I want the API documentation to follow the same format as the rest of the documentation.

### ISSUE THREAD

**Issue by EdProsser** [hyperledger/composer#1445]
There's a bunch of things which the API documentation does differently. User experience might be better if there was more parity between the API docs and the main site. 

- Styling and visual appearance.
- You cannot navigate back to the docs from the API docs (!!)
- Table of contents has disappeared! 
- The content is laid out... inexplicably.

I think this needs a combination of some love from @winslet, @mbwhite, and I to decide how to restructure the information in here from a technical, info architecture, and design perspective.

**Comment by mbwhite** [comment]
The Documentation.js tool can parse the src, and produce Markdown - as this is unstyled, it can easily drop into the Jekyll build of the site. It parses the same types of jsdoc comments. 

What you can't alter though is the overal structure of the Markdown document. (Unless editing it afterwards). This does mean that basic form is fixed - I've included a screenshot of what this looks like for one class.  The links need addressing (and that can be done as part of the Jekyll build), and the diagrams are not included (I've not copied them to the correct place). 

I am undecided on the overall format, whilst visually it is harmonious, and is tidy. Not sure that it is really that strong. 

![image](https://user-images.githubusercontent.com/6673453/30472486-88c7b0fa-99f4-11e7-8682-469c6cf49dff.png)

@EdProsser @winslet @EdMoffatt    What are your views gentlemen? I'm persisting the work in a branch in my fork of composer. So the work is not lost but can be parked if we desire.

**Comment by winslet** [comment]
@mbwhite personally I feel this is a great improvement on the current API docs, even having them inside the current docs site greatly improves the experience, I would be interested to know why you feel it isnt working for you at this point?

@EdMoffatt any views?

**Comment by EdMoffatt** [comment]
Yeah, I really like having it there in the docs too :)  I think there are a few things that would make me feel even better about it...

- It feel like there might be too many top-level nav items on the docs now?
- Particularly when going through the modules in the API ref, an additional layer of heirarchy seems like it would be useful
- I think we need a way to differently style examples that a user may need to copy/paste and other code examples.  The API doc will have *lots* of code snippets that it's very unlikely nobody wants to Copy, so having the button there starts to irk me more ;)

**Comment by winslet** [comment]
Having chatted about this, the thing that seems to be a regression is the lack of search, im happy to put this in and then worry about it, but we are tracking a solution here: #914 but it will probably need more support from the main development team.

**Comment by mbwhite** [comment]
Delivered now; feedback will result in additional styling.
