### ISSUE TITLE
Composer Playground in Local doesn't let you change profile if a wrong profile is in Local Storage

### ISSUE THREAD

**Issue by LittlePea13** [hyperledger/composer#1458]
## Context

When you try to use Playground locally, if there was a wrong connection profile in Local Storage, an Error message appears related to your wrong profile, but once you close the messages the Playground site shows the Get Local Version button in the top right, instead of the globe in order to be able to change the profile.

## Expected Behavior
I think it would be convenient to be able to change the profile to a working one as well as maybe raising a message saying your connection profile is wrong, change it.

## Actual Behavior
Right now clearing the Local Storage is a workaround to get to change the connection profile to a desired one

## Steps to Reproduce
1. Have a wrong Profile in Local Storage, i.e. with a wrong name for the CA
2. Run a Fabric with your deployed business network, etc
3. Start Composer Playground locally with docker run --name composer-playground --publish 8080:8080 --detach hyperledger/composer-playground
4. A message saying something is wrong will show up when you access the playground.
5. The Get Local Version button will show in the top right instead of the globe.

## Your Environment
I'm using Chrome latest version on an Ubuntu 16.04 TLS, with both latest versions of Fabric (beta) and Composer (0.9).

**Comment by caroline-church** [comment]
closing as i don't think this is a problem any more now we have business network cards, if a card has an invalid connection profile when you try and connect to that network it will give you an error but there will be no problems after that. Feel free to reopen if you do feel this is still a problem
