### ISSUE TITLE
Playground should disable "Submit Transaction" when no transactions are defined

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1471]
The Submit Transaction button is available to click (and brings up the modal for transaction submission) even when no transactions are defined.  It should be disabled.

Easiest way to recreate is to  Import the "Empty Business Network", then straight away hit up the Test tab.

**Comment by anarancio** [comment]
I think the code is fine, it has a validation of no-transactions.
If you look in the html of the "submit transaction" button you can see it will disable if there're not transactions (https://github.com/hyperledger/composer/blob/6da2143c9e421f8f7e06a4c9396fab9ceb56616c/packages/composer-playground/src/app/test/test.component.html#L39).

But you still have some valid transactions to submit like RevokeIdentity, IssueIdentity, etc...

make sense?

**Comment by sstone1** [comment]
P3 and no action in three months; clearly not important and never going to get fixed, so closing.
