### ISSUE TITLE
Composer Playground Identity issue needs to support connector specific options

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1474]
#606 will allow connector specific options for the identity issue command, but playground will need to be able to do something similar. See details in referenced issue to see the kind of things required for hlf v1.

**Comment by sstone1** [comment]
As far as I know, nobody is working on this at the moment or planning to work on it, so closing. 
If somebody wishes to work on this in the future, then please reopen this issue or open a new issue.
