### ISSUE TITLE
Code Coverage: composer-common/lib/codegen/fromjs

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1493]
Currently missing regression tests.

This folder and all content is being skipped by code coverage metrics through setting in composer-common/package.json `"nyc": {
    "exclude": [ ~` content

During test addition it will be required to remove the file inclusion from the above json array and then run tests.

Required test additions:
- [x] apisignituregeneratior.js
- [x] plantumlgenerator.js

**Comment by awjh-ibm** [comment]
The two files that are required as additions in this appear to have been added in PR #2320 which referenced #1495

**Comment by mbwhite** [comment]
The code coverage work for this issue has been completed; the changes have been pushed to my branch
https://github.com/mbwhite/composer/tree/issue-14932-coverage
