### ISSUE TITLE
Code Coverage: composer-common/lib/codegen

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1495]
Currently missing regression tests.

This folder and all content is being skipped by code coverage metrics through setting in composer-common/package.json `"nyc": {
    "exclude": [ ~` content

During test addition it will be required to remove the file inclusion from the above json array and then run tests.

Required test additions:
- [ ] codegen.js
- [x] filewriter.js
- [ ] javascriptparser.js
- [ ] jsonwriter.js
- [ ] parsejs.js
- [x] writer.js

**Comment by mbwhite** [comment]
Latest updates have been pushed into my own branch... getting there.
