### ISSUE TITLE
Playground errors begin with "t:" for some reason!

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1497]
Errors in the Playground editor, the message starts with "t:".

To recreate, open Playground, load in the Basic Sample, then stick an error into any of your files.  You'll see something like this:

![image](https://user-images.githubusercontent.com/7454304/27907436-8ad869bc-623f-11e7-8be3-c809551aca04.png)

Also, some error types seem to be missing line numbers - seems to be on mentions of undefined namespaces, like:
![image](https://user-images.githubusercontent.com/7454304/27907475-b95091ca-623f-11e7-87c9-f3ad1f102eda.png)
(In that example, my model file defines org.acme.sample.foo)

**Comment by KaiUsher** [comment]
@EdMoffatt The initial point of this issue appears to be fixed upstream. The second point seems to revolve around whether you believe the model file is an error or the script/acl files are the error(s).
Would you like this to be fixed by specifying the line/function where the error is detected, or hold off for the resolution of #1530 ?

**Comment by EdMoffatt** [comment]
Hey @KaiUsher - what do you mean "fixed upstream"?  Is there another issue that addresses this?  Current unstable Playground exhibits the problem as far as I can see.

Even with work on #1530, I think we'd still consider the Script/ACL file to be in error if they were using something that wasn't defined in the Model file.  1530 will just mean that we don't throw away the changes to that file if they were made in the Edit view.

I'm not sure if there's much we can do to display line numbers in this particular case, I'm just wondering :)  So for example, to construct a super-simple case...

1) Load in Basic-Sample-Network
2) Go to the ACL file
3) Change line 6 to say "participant: "org.acme.sample.SampleParticipantFoo"
4) Error message will be "t: Failed to find class org.acme.sample.SampleParticipantFoo"

I posit that if possible, that error should be "Failed to find class org.acme.sample.SampleParticipantFoo: line 6, column blah" (where blah is a number that I cannot be bothered to count out ;) )

**Comment by KaiUsher** [comment]
@EdMoffatt I can confirm that the current unstable Playground has the issue with errors starting with 't:', however having just pulled from master and running locally to work on this issue that is no longer the case.

I'll look in to adapting the errors on the Script/ACL files to indicate the line where the 'failed to find class' error is detected!

**Comment by markcastle3** [comment]
@KaiUsher how is this one progressing ?

**Comment by davidkel** [comment]
As far as I can see this problem hasn't been fixed I can still see this errors starting with a 't:' in 0.16.0 and I assume that master won't be any different.

**Comment by mahoney1** [comment]
This t: error is also caused when a user (inadvertently)tries to factor in/model a 'transactionId` (reserved identifier in transaction supertype).  Reported in v0.16.0 - S/Overflow exists for this below.
https://stackoverflow.com/questions/47671333/how-to-resolve-this-error-t-identifier-cannot-extend-from-super-type-on-hyper

**Comment by davidkel** [comment]
As this has been marked stale and is such a minor issue, may as well close it now.
