### ISSUE TITLE
As a user, I can select between "built by us" and community samples

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#1509]
This came up on the community call today, and I think it is worthy of a GitHub issue to track the discussion. Now is a good time to do something in this area, especially as we are doing some work to the way we display samples in the playground, and I think the engineering to do this is pretty small.

Currently the Hyperledger Composer team maintain a set of sample business networks in [composer-sample-networks](https://github.com/hyperledger/composer-sample-networks/tree/master/packages). These sample business networks are regularly pushed to npm by our Travis CI builds and are tagged with `composer`, `composer-network`, and have a maintainer of `hyperledger-ci`.

We want the community to publish as sample (or not sample!) business networks as possible, so that they can be used as a learning aid for other users. However, I do not think that the Hyperledger Composer team want to take on the responsibility of maintaining all of these samples under one repository - it could be a significant undertaking to maintain 100s - 1000s of samples. There is also a licensing question here; some users may be willing to publish their sample business networks, but not under the Apache-2.0 license, which we would be unable to accept into the Hyperledger repositories.

I think that we should allow the user to switch between "Built by the Hyperledger Composer team" samples and "Community" samples in the sample import wizard. The difference being:

"Built by the Hyperledger Composer team" - must have keywords `composer`, `composer-network`, and a maintainer of `hyperledger-ci`.
"Community" - must have keywords `composer` and `composer-network`.

That way anybody can publish a sample business network to npm and have it findable and available to import within Composer Playground, but importantly we get the protection of not having a bunch of potentially "junk" samples appear in our primary recommended list.

If we do this, we need to consider showing more information about each community sample:

- The license
- A link to the package on npmjs.com, or a link to the project website
- Number of downloads?

The npm APIs also have references to popularity, quality, and maintenance metrics which may be useful in sorting the wheat from the chaff!

As mentioned at the top, I think the engineering work for this is small. We need some kind of "toggle" to switch between the two, and depending on the setting of that toggle we will send different things in our search string to the npm registry.

**Comment by sstone1** [comment]
@EdMoffatt @Tobias-Hunter as discussed earlier.
@dselman you weren't on the call, so be interesting to hear your input.

**Comment by dselman** [comment]
Sounds like a great idea. I'd love something similar for models as well, once we get onto that.

**Comment by Tobias-Hunter** [comment]
In preparation for this I have made changes to *all* of the README.md files in our Sample Networks. These should now walk a user being able to use that model to create relevant Participants and Assets to submitting Transactions for each model! Please see the changes here:
https://github.com/hyperledger/composer-sample-networks/pull/71

I have made improvements to the styling of the README's within the Playground here:
https://github.com/hyperledger/composer/pull/1532

I have updated the designs for the behaviour of our README.md files, which should allow Community members to provide better README.md files so others are able to consume their models! Find the designs here: 
https://github.com/hyperledger/composer/issues/1560

Next, I'm going to look into the behaviour when viewing potential models to import & how we separate out these models! 🌭

**Comment by sstone1** [comment]
As far as I know, nobody is working on this at the moment or planning to work on it, so closing. 
If somebody wishes to work on this in the future, then please reopen this issue or open a new issue.
