### ISSUE TITLE
Developer tutorial ultimately leads to a deployment error

### ISSUE THREAD

**Issue by abrinckm** [hyperledger/composer#1510]
## Context
After walking through the developers tutorial, everything went well as expected until the section "Deploy to the Running Hyperledger Fabric". Executing the command `composer network deploy -a my-network.bna -p hlfv1 -i PeerAdmin -s randomString` as instructed results in the error `Error: error trying deploy. Error: Failed to deserialize creator identity, err MSP Org1MSP is unknown Command failed`. 

I have setup the Fabric exactly as instructed and have these running containers: 

```
[fabric@hledger ~]$ docker ps
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                            NAMES
91fe18518c8d        hyperledger/fabric-peer:x86_64-1.0.0-rc1      "peer node start --pe"   6 minutes ago       Up 6 minutes        0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp   peer0.org1.example.com
68259a92aca4        hyperledger/fabric-ca:x86_64-1.0.0-rc1        "sh -c 'fabric-ca-ser"   6 minutes ago       Up 6 minutes        0.0.0.0:7054->7054/tcp                           ca.org1.example.com
c6eac7a1c19e        hyperledger/fabric-orderer:x86_64-1.0.0-rc1   "orderer"                6 minutes ago       Up 6 minutes        0.0.0.0:7050->7050/tcp                           orderer.example.com
037a44588273        hyperledger/fabric-couchdb:x86_64-1.0.0-rc1   "tini -- /docker-entr"   6 minutes ago       Up 6 minutes        4369/tcp, 9100/tcp, 0.0.0.0:5984->5984/tcp       couchdb
```

## Expected Behavior
According to the tutorial I should have seen this message:
`Command succeeded`

## Actual Behavior
Instead received this message:
`Error: error trying deploy. Error: Failed to deserialize creator identity, err MSP Org1MSP is unknown Command failed`

## Possible Fix
Edit the MSP Id. Except I have no idea how!

## Steps to Reproduce
1. Follow the [installation instructions](https://hyperledger.github.io/composer/installing/development-tools.html) in step 2 exactly as instructed.
2. Follow the [developers guide](https://hyperledger.github.io/composer/tutorials/developer-guide.html) exactly as instructed.

## Existing issues
I have searched for this issue and found nothing.

## Context
I was trying to accomplish completing the tutorial and learn fabric composer.

## Your Environment

* Version used: 
[fabric@hledger ~]$ composer -v

composer-cli                   v0.9.1
composer-admin                 v0.9.1
composer-client                v0.9.1
composer-common                v0.9.1
composer-runtime-hlf           v0.9.1
composer-runtime-hlfv1         v0.9.1

* Environment name and version (e.g. Chrome 39, node.js 5.4):
[fabric@hledger ~]$ node -v
v6.10.0

* Operating System and version (desktop or mobile):
[fabric@hledger ~]$ cat /etc/system-release
Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Comment by abrinckm** [comment]
and docker version is:

`[fabric@hledger fabric-tools]$ docker -v
Docker version 1.12.6, build 1398f24/1.12.6`

**Comment by abrinckm** [comment]
The issue was my docker version. I thought I had upgraded my docker version for RHEL, however RHEL only supports docker version up to v1.12 and it does not upgrade to v1.13. So to fix, I installed docker-latest and switched from docker to docker-latest.

**Comment by marryton007** [comment]
It's issue on my mac:

My environment: mac 10.12.5
~/work/fabric-composer/my-network/dist docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:38 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:54:55 2017
 OS/Arch:      linux/amd64
 Experimental: true

~/work/fabric-composer/my-network/dist docker-compose version
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
