### ISSUE TITLE
Timeout expired when deploying a .bna

### ISSUE THREAD

**Issue by LittlePea13** [hyperledger/composer#1514]
## Context

Using the Fabric (RC1) development environment provided in Composer Tutorials, deploying a custom .bna, I get a 
`Error: error trying deploy. Error: error trying instantiate chaincode. Error: Failed to execute transaction (Timeout expired while executing transaction)
Command failed`

## Expected Behavior

The business network should be deployed

## Actual Behavior

An error appeared and the network is not deployed.

## Possible Fix

Right now, adding 
`- CORE_CHAINCODE_EXECUTETIMEOUT=90s`
as an environment variable on docker-compose.yml for peer0.org1.example.com solved the problem. 

## Steps to Reproduce

1. Set the developer environment as in https://hyperledger.github.io/composer/installing/development-tools.html
2. Start the Fabric, create the Composer Profile
3. Try to deploy a .bna using `composer network deploy -a bonusetis.bna -p hlfv1 -i PeerAdmin -s randomString`
4. An error will show up as:
```Deploying business network from archive: bonusetis.bna
Business network definition:
	Identifier: bonusetis@0.0.2
	Description: The Blockchain for Bonusetis

✖ Deploying business network definition. This may take a minute...

Error: error trying deploy. Error: error trying instantiate chaincode. Error: Failed to execute transaction (Timeout expired while executing transaction)
Command failed
```

## Your Environment

* Latest version of development tools, (Fabric RC1, composer 0.9.1)
* Ubuntu 16.04 TLS 

[trace_31910.log.zip](https://github.com/hyperledger/composer/files/1131430/trace_31910.log.zip)

[bonusetis.zip](https://github.com/hyperledger/composer/files/1131541/bonusetis.zip)

**Comment by sstone1** [comment]
Believe this is due to this ACL condition:

```
condition: (r.apportionments.findIndex(function(element){
  		if(element.getIdentifier() === (r.getIdentifier()+p.getIdentifier()))
  			return element;
	}) > -1)
```

We have seen in the past that complex ACL conditions like this can cause the ACL parser to spend a long time parsing ACL files when deployed.

@LittlePea13 you can try fixing this using a new feature in 0.9.1 where ACL conditions can reference JavaScript functions in script files:

ACL condition:

```
condition: (checkApportionments(r, p))
```

Script file:

```
function checkApportionments(r, p) {
  return r.apportionments.findIndex(function(element){
  		if(element.getIdentifier() === (r.getIdentifier()+p.getIdentifier()))
  			return element;
	}) > -1;
}
```

**Comment by LittlePea13** [comment]
It worked like a charm with your tip @sstone1, thank you. Will start using separate script for ACL functions.

**Comment by sstone1** [comment]
This should be resolved "properly" when we pick up Fabric v1.1 and Node.js chaincode support, but closing for now as there's nothing we can really do about it.

**Comment by eloff** [comment]
FYI I ran into this issue deploying a custom business network on Ubuntu 16.04 with hlfv1. The ACL was trivial, so it must have other causes as well. I tried LittlePea13's fix and that worked. If it hadn't been for him I don't think I would have got past it. I am using version 1.0.

**Comment by mystbrent** [comment]
![image](https://user-images.githubusercontent.com/22728407/52164870-643c4e80-2733-11e9-89ce-71bebf3231b4.png)
Same error 😢
