### ISSUE TITLE
using an abstract object with   transactions in the .cto file

### ISSUE THREAD

**Issue by hadyrashwan** [hyperledger/composer#1517]
## Context
I did define the following but did break after rc 1.0 rollout 
```
abstract concept abstractX {
     o String txId
     --> xc item1
     --> xcx  item2
}
transaction applyX identified by txId extends abstractX  {}
```
which did fire an error after a successful deployment 

`t: Instance 5653cc88-d8a6-47eb-8705-878fd1e29cb0 has a property named timestamp which is not declared in org.acme
`
I think it can be solved by just defining the timestamp, but I did find that basic sample network example is updated to not have the identifier when defining the transaction.

I did duplicate the transaction definition and removed the abstraction for now.

but nor the vs code plugin or the playground did highlight the problem
## Expected Behavior
Error message in both the playground and vs code for not following the syntax
## Actual Behavior
nothing just try it and see the error 
## Steps to Reproduce
1- add the following code to your definition
2 - create the .bna file and deploy it 
3-  try to call the transaction
```
abstract concept abstractX {
     o String txId
     --> xc item1
     --> xcx  item2
}
transaction applyX identified by txId extends abstractX  {}
```
## Context
not a big Issue but I'm new to the blockchain, and I didn't expect it at first and thought it's something major, to realize a week later when I had time to look that it was trivial.
## Your Environment
Hosted playground version

**Comment by sstone1** [comment]
Seems to be lots of bugs here:

- Transactions can extend concepts, when they shouldn't be able to.
- Transactions can specify identifiers, when they shouldn't be able to.
- Transactions can specify identifiers where the identifying property is in a base class - to me, this seems a bit weird, but happy to hear otherwise.

@dselman FYI
@mbwhite some of this is left over debt for #920 so assigning to you 😉

**Comment by dselman** [comment]
1. Transactions extending concepts is definitely a bug. We even have a TODO in the code to check that the type of the super type is compatible.
2. This doesn't add much value and can be removed
3. See above.
