### ISSUE TITLE
 Invalid host header

### ISSUE THREAD

**Issue by pvrbharg** [hyperledger/composer#1518]
[HLComposer-InvalidHostHeaderIssueDoc.docx](https://github.com/hyperledger/composer/files/1134111/HLComposer-InvalidHostHeaderIssueDoc.docx)

I am running a Hyperledger Composer developer sandbox with tutorial in IBM Skytap cloud instance. When I access the endpoint from inside hosting server URL all is well. The URL is:
[http://localhost:4200|http://localhost:4200/]
If I try to access the same end point from a public tier - I am seeing the error. What configuration should I be doing in order to access the end point from outside hosting server.

How to replicate the issue:

Get the sample up and running from Composer developer tutorial and try to access endpoint from a not hosting machine browser URL.

See my attachment above. Thanks.

**Comment by dstarina** [comment]
I have tried this workaround: Edit the following line in node_modules/webpack-dev-server/lib/Server.js (line 425):
change to
return true;

Now the web app opens - however, shows the following error when trying to do anything: "Error: Could not connect to REST server. Please check your configuration details"

**Comment by pvrbharg** [comment]
So the workaround is not a good answer since it creates a new problem while not being sure if it solves the underlying reported original issue.

**Comment by dselman** [comment]
We have no expertise to help with this -- not a Composer issue.

**Comment by smugamerican** [comment]
This solution worked for me and was the only way I could access my fabric app on my Ubuntu virtual machine from Windows. I'd like to make this a setting in one of the configuration files, but I'm not sure where the best place to put it is. Any suggestions? Should I create another issue?

**Comment by gente21** [comment]
I managed to get around this by:

1. Upgrading my angular-cli: [https://stackoverflow.com/questions/43931986/how-to-upgrade-angular-cli-to-the-latest-version](https://stackoverflow.com/questions/43931986/how-to-upgrade-angular-cli-to-the-latest-version)

2. Changing this line on my package.json:
```
"start": "ng serve"

To:

"start": "ng serve --host 0.0.0.0 --disable-host-check"
```

I hope this can help somebody :P
