### ISSUE TITLE
Tutorial misleadingly states that it was written against v0.8

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#1525]
Developer tutorial states at the top "Note: this tutorial was written against Hyperledger Composer v0.8 on Ubuntu Linux running with Hyperledger Fabric v1.0 "

But the content of the model files require v0.9+ !!

**Comment by markcastle3** [comment]
@mahoney1 did you say you would look at this one ?

**Comment by mahoney1** [comment]
yes, and I've submitted a PR request to change it to refer to contemporary version FYI -> https://github.com/hyperledger/composer/pull/1534
