### ISSUE TITLE
As a contributor, I no longer have to maintain support for Fabric v0.6

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#1535]
This contributor story will deprecate and remove support for Hyperledger Fabric v0.6.

This entails:
- Removing the runtime container module `composer-runtime-hlf`
- Removing the connector module `composer-connector-hlf`
- Removing Fabric v0.6 leftovers from the CLI
- Removing Fabric v0.6 connection profiles from the playground
- Removing Fabric v0.6 references from the documentation
- Plus more!

**Comment by sstone1** [comment]
Have marked Hyperledger Fabric v0.6 support as deprecated in v0.10.0.
It will be completely removed in v0.11.0.

**Comment by kletkeman** [comment]
So is it correct to say that support for v0.6 will be dropped in 2 to 3 weeks, according to your past release schedule (v0.8.0 June 15, v0.9.0 July 1, v0.10.0 July 20)?

**Comment by sstone1** [comment]
@kletkeman it depends on how we progress with other work - we bump up the middle digit when we make a change that is incompatible with previous versions. There are quite a few incompatible changes lined up over the next month.

**Comment by davidkel** [comment]
Clarification of certain aspects of V0.6 removal
- we need to remove all of the code in the CLI that creates a HLFv0.6 connection profile when one is not specified. I am in favour of removing all of that code completely - get rid of defaultProfile - and force the user to always specify a connection profile.
👍 1  
All of our documentation tells users to `-p hlfv1`
I think it would be less confusing and if we actually get some requirements for it then we can add it back in later.
