### ISSUE TITLE
Composer not generating radio button / checkbox for Enums

### ISSUE THREAD

**Issue by coder-ajay** [hyperledger/composer#1541]
## Context

In default marbles-network example, the enums 'size' and 'colours' generate textfields in angular2 UI from Yeoman generator. It seems to be a bug since we already have String data type for textfields.

## Expected Behavior

It should generate either radio buttons or checkboxes in Angular2 UI.
## Actual Behavior

It generates textfield just like a String variable.
## Steps to Reproduce

1. Run the marbles-network example as is.
2. Click on 'add asset' button
3. For 'size' and 'colour', the popup shows text fields

## Existing issues

- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues/1083)

## Context

I am trying to implement radio button / checkboxes. This bug does not show me the options that are available to select from. User may not know what the default options are to choose from.

## Your Environment

* Version used:
-- composer-cli                   v0.9.1
-- composer-admin                 v0.9.1
-- composer-client                v0.9.1
-- composer-common                v0.9.1
-- composer-runtime-hlf           v0.9.1
-- composer-runtime-hlfv1         v0.9.1

* Environment name and version:
-- Chome v56.0.2924.87 (64-bit)
-- node v6.11
-- git v2.13.2
-- npm v3.10.9
-- Docker version 17.06.0-ce, build 02c1d87
-- docker-compose version 1.14.0, build c7bdf9e

* Operating System and version (desktop or mobile):
-- MacOS Sierra
-- Version 10.12.5 (16F73)
-- Desktop

* Link to your project:
-- Default marbles-network project

**Comment by ilfrich** [comment]
Is anyone already working on this? If not, I could help. @sstone1

**Comment by sstone1** [comment]
The generator now generates some very nice radio buttons for enumerations.
Many thanks to @ilfrich!
