### ISSUE TITLE
Allow README.md files to be editable in Playground

### ISSUE THREAD

**Issue by Tobias-Hunter** [hyperledger/composer#1560]
Currently a user is unable to edit a README.md file within the Playground. A user should be able to edit a README.md file within the Playground just like any other file. 

If the user imports an Empty Business Network, then the README.md will be blank in the ‘Preiview’ display. If they switch to the ‘Edit” display then they will get the guide layout outlined here: https://github.com/hyperledger/composer-sample-networks/wiki/Editing-Contributing-README.md-File-Guide however this is commented out! 

.XD Click-through to show suggested behaviour: https://xd.adobe.com/view/d8b0e112-c16b-499a-beb9-4a57d78887f0/

🍌

**Comment by prasoc** [comment]
Working on it

**Comment by EdMoffatt** [comment]
It looks to me like this is possible in the latest release!

Should we close this issue, @prasoc @caroline-church - or is there still work to do here?

As a side note, I feel like we'll probably need another issue to think about the UI for this panel - at the moment, it's a different way of editing the version, the Readme and the package.json.
Might be a good opportunity to have a bit of a workshop session on this if people are up for it!

**Comment by prasoc** [comment]
@EdMoffatt Yes, it has been added :) I thought it would be closed automatically - I do not have privileges to close it however.

Hmm well I stuck very closely to the design document to style and place the panel, the new buttons do stick out a little when you're in markdown "Preview" mode... I am happy to help out in with a workshop session!

**Comment by caroline-church** [comment]
Yes we can now close this

**Comment by EdMoffatt** [comment]
Yeah, think you nailed implementing the design @prasoc - nice one :)

Im more thinking that now we're adding more file types and ways of editing them, maybe we have a broader session to look at navigation and editing in general in the Define tab...  I'll get you involved when I set something up :D
