### ISSUE TITLE
Add cookie/tracking notification to playground and website

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#1565]
Both the playground and website use Google Analytics to track usage and visitor data. They should both disclose this to conform to relevant laws and the Google Analytics licence agreement.

See https://www.google.com/analytics/terms/us.html

**Comment by EdMoffatt** [comment]
Just putting some more notes on what I think we need to do for this...

From the Ts & Cs, it sounds like we must "clearly display a link to https://www.google.com/policies/privacy/partners/" - they suggest putting it under a "Privacy Policy" section.

This sounds like we could create a page in the reference section of the documentation, and that we then also need to link to it in the Playground and the Website - the footer bar seems like a fairly standard place to put it.

So I'd suggest we want something like...

![image](https://user-images.githubusercontent.com/7454304/28719670-aaa19cd6-73a2-11e7-908e-3b18d77650cf.png)

And then also:

![image](https://user-images.githubusercontent.com/7454304/28719866-5218e0aa-73a3-11e7-9329-89bbe52d7c82.png)


Aaaaaand also:

![image](https://user-images.githubusercontent.com/7454304/28719925-8c2c766c-73a3-11e7-955c-fbdd7f9d9933.png)

(That's changing "Legal" to "License" too, as "legal" sorta sounds like it could also be the Privacy Policy stuff.

I guess the alternative would be a "Legal" section in the doc, which has License and Privacy Policy as sub-sections, then we can still just display "Legal" in the Playground, and link to that top level page.
