### ISSUE TITLE
Playground attempts to list deployed chaincodes with a user who doesn't have authority

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1577]
Raising this to ensure that the new identities implementation solves this issue.

![clipboard - july 15 2017 9-55 pm](https://user-images.githubusercontent.com/25582377/28246612-072bcb84-6a16-11e7-8777-cff0f30f9677.png)

**Comment by caroline-church** [comment]
This will be fixed when we switch to ID cards so documenting the problem for now
