### ISSUE TITLE
Playground may be attempting to deploy more than once

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1578]
Multiple people have seen this
![image](https://user-images.githubusercontent.com/25582377/28246636-9d1ddf7e-6a16-11e7-8888-9eeab734ed32.png)

Also I saw this once which could be the same problem just different error due to timing
![image](https://user-images.githubusercontent.com/25582377/28246645-b96ed69c-6a16-11e7-8f40-9adb2464a489.png)

**Comment by sstone1** [comment]
I suspect this no longer occurs due to the removal of the automatic deploy as part of ID cards, so closing - it can be reopened if needed.
