### ISSUE TITLE
Documentation on how to add participants and issue identity needs correction

### ISSUE THREAD

**Issue by LarissaAuberger** [hyperledger/composer#1589]
In https://hyperledger.github.io/composer/managing/participant-add.html
The command line to add participant should include -p hlfv1 and the password has to be changed to adminpw 

In https://hyperledger.github.io/composer/managing/identity-issue.html
The command line to issue an identity should include -p hlfv1 and the password has to be changed to adminpw

In https://hyperledger.github.io/composer/managing/identity-issue.html 
The command line to test connection to the business network should include -p hlfv1

**Comment by LarissaAuberger** [comment]
Same issue for revoking an identify of a participant: https://hyperledger.github.io/composer/managing/identity-revoke.html
Command line should include -p hlfc1 and admin password has to be changed

**Comment by davidkel** [comment]
These examples were originally for HLF v0.6 where a profile didn't need to be specified and that was the password. We should convert these to HLF V1 examples as noted above as that is now our default runtime example. However for all our CLI examples we should be explicit that
`-p hlfv1` is using a development fabric profile and other profiles could be used
`-i admin -s adminpw` are again based on our development fabric setup and other identities and secrets could be used.

**Comment by sstone1** [comment]
I'm doing this as part of my identity registry changes.

**Comment by davidkel** [comment]
Need to check to see if this is now complete and then can close it off.

**Comment by sstone1** [comment]
This has been done.
