### ISSUE TITLE
As a Developer using Composer, there are some 'mmm that is odd' parts of the API & tools

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#1591]
Background: when developed the System ACLs, and the network doc tool - I wrote the test apps as scenarios to properly explore that function that was needed.  With a 'developer using composer', rather than a 'developer of composer' hat this raised the following questions. (all to be prefixed with IMHO)

- [ ] Why in some APIs are there a 'namespace' and a 'type' whereas in others there is just the Fully Qualified name, this is inconsistent for no specific reason.
- [ ] The API, in general, is sound, however, there is this split between composer-admin, composer-client and composer-common (ignoring composer-runtime). 
Admin contains, the AdminConnection (the clue is in the name as to what this does)
The other is the BusinessNetworkDefinition - but that is just as useful and essential for all types of Apps.
Summary: the admin module doesn't add any value.
- [ ] There are a number of missing exports that make using introspection incredibly difficult. 
- [ ] CLIs are great - but once you get past using a few in a script, you need to have RAW output to them.
and/or expose the exports of the cmd function so they can be called programmatically (having tested this - there is no code change except an export)
- [ ] Structure of the BNA is a bit odd - the ACLs and Query files are very easy to 'lose' as they are not in subdirectories. The other files are in subdirectories - so the ACLs and Queries should be as well. (they may not have multiple files today - but tomorrow could well have)

Nice to haves:
- [ ] Clean up CLIs so they all match composer network deploy in output - and also so they report success only when successful
- [ ] Generator function in the `composer generate` to create stub JS file from CTO transaction defn.
- [ ] Correct the log file generation level... (been meaning to do this for ages)

**Comment by dselman** [comment]
For the record, I would like to maintain the separation between the admin API and the client API. The admin API is intended for people building applications that administer networks (not connecting to them), whereas the client API is all about connecting to a network and interacting with it. The distinction is somewhat subtle, but important.

**Comment by davidkel** [comment]
@mbwhite I thought I had dome some work on cleaning up the CLIs so they do only report success on success and fail on fail. Did I miss some ?

**Comment by sstone1** [comment]
> and/or expose the exports of the cmd function so they can be called programmatically (having tested this - there is no code change except an export)

Why wouldn't you just use the client or admin APIs? The CLI should be a thin wrapper around those 😕 

> CLIs are great - but once you get past using a few in a script, you need to have RAW output to them.

I agree with this one - any CLI command where we are listing data, we should offer a `-json` flag to just print the data so it can be easily consumed by a Bash/Python script.

> Why in some APIs are there a 'namespace' and a 'type'

I find this split annoying when coding and I'm not sure what benefit it provides.

I'll add a new one:

[ ] Remove all the camelCaseLongOptionNames and replace with long-option-name like every single other popular CLI in existence today 😉

**Comment by sstone1** [comment]
As far as I know, nobody is working on this at the moment or planning to work on it, so closing. 
If somebody wishes to work on this in the future, then please reopen this issue or open a new issue.
