### ISSUE TITLE
As a user I notice logs of trace files and a logs directory

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#1603]
There is a trace file created per process run and a logs directory. This is caused because of an inaccurate setting of the default logging statements. 

By default, there are two logging locations stderr, and a file. This is fine but currently, the file is set to the INFO level and not the ERROR level which be more appropriate for defaults. 

* Adjust the directory name to be `composer-logs` from `logs`
* Alter name of trace file to be  `trace-20170715-123123-0.log`  date and time (with suffix if needed for distinguishing.

/cc @sstone1  @dselman  as maintainers slight externals change

**Comment by sstone1** [comment]
Didn't this get fixed as part of a PR that I reviewed the other day?

**Comment by mbwhite** [comment]
@sstone1 yes it did...
