### ISSUE TITLE
filter isn't working

### ISSUE THREAD

**Issue by cansado2930** [hyperledger/composer#1605]
Composer-rest-server works but when I requests assets for example with a filter {"limit":1}, it answers with all assets

## Context
I have tried with limit, order, where,... and I haven't got the result that it should be

## Expected Behavior
The case of limit, I expects that it answer with n results when m > n

## Actual Behavior
It always sends m results instead of n when m>n

## Possible Fix
There are some bug or the description isn't clear in order to do filter. Could you help me?

## Steps to Reproduce
1-create 3 assets
2-get asset --> 3 asset are sent
3-get asset with filter {"limit":1} --> 3 assets are sent

## Context
It is very important for me because the blockchain have a lot of data and I need to filter it on blockchain instead of having to process all data on other backend in order to show on web/mobile app
## Your Environment
* Version used: hlfv1
* Environment name and version :last version of Ubuntu, Firefox, nodejs and docker.
* Operating System and version (desktop or mobile): Ubuntu 16lts

**Comment by sstone1** [comment]
@cansado2930 the LoopBack filter query syntax has not been implemented, and we don't have plans to implement it. Instead, please check out the complex query functionality that we have introduced.

You can define queries in `queries.qry` files using the Composer query language:
https://github.com/hyperledger/composer-sample-networks/blob/master/packages/trade-network/queries.qry

You can then call them programmatically from a transaction processor function using the `query` function:
https://github.com/hyperledger/composer-sample-networks/blob/master/packages/trade-network/lib/logic.js#L46

Alternatively, you can call them using the Node.js client APIs in `composer-common`:
https://github.com/hyperledger/composer/blob/master/packages/composer-systests/systest/queries.js#L272

Finally, in Composer v0.10.0, the REST API automatically generates GET routes for each query that you define in a query file 😄
