### ISSUE TITLE
Everything looks good!

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#1608]
The everything looks good file validation message is shown even when the playground has gone horribly wrong...

![image](https://user-images.githubusercontent.com/3535067/28374227-0ac6e8fe-6c9c-11e7-88b8-6853fb766220.png)

## Context

I was getting all sorts of error dialogs in the playground which eventually left an unpopulated Define editor tab, but there was still a cheery 'Everything looks good!' when it really wasn't

## Expected Behavior

Only show the everything looks validation when there is something to validate

## Actual Behavior

Message is displayed when it shouldn't be

## Steps to Reproduce

Tricky. I had some left over stuff in local storage which was causing problems. That shouldn't happen but seems to reasonably often.

## Context

I was opening the Composer Playground immediately after running the single-command local install script

## Your Environment

* Browser environment: OSX Safari 10.1.1 
* Operating System and version (desktop or mobile): Linux ubuntu-xenial 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by alexsicart** [comment]
Hi @jt-nti do you know if this error is already solve?

Cheers!!

**Comment by caroline-church** [comment]
fixed so closing
