### ISSUE TITLE
Incorrect doc/comments for factory.newConcept

### ISSUE THREAD

**Issue by theophoric** [hyperledger/composer#1610]
## Context

Documentation for concepts is inaccurate -- appears to have been copied from resource.

pics:
from [common factory docs](https://hyperledger.github.io/composer/jsdoc/module-composer-common.Factory.html#newConcept__anchor):
![screenshot 2017-07-19 09 17 32](https://user-images.githubusercontent.com/322054/28378023-9860289e-6c63-11e7-95ed-44a1f914ed35.png)

from [runtime factory docs](https://hyperledger.github.io/composer/jsdoc/module-composer-runtime.Factory.html#newConcept__anchor):
![screenshot 2017-07-19 09 17 51](https://user-images.githubusercontent.com/322054/28378027-9a56cef0-6c63-11e7-8685-77266946af29.png)

## Expected Behavior

Concept docs
## Actual Behavior

Resource-y docs
## Possible Fix

Update doc coments
## Steps to Reproduce
1. check out [runtime factory docs](https://hyperledger.github.io/composer/jsdoc/module-composer-runtime.Factory.html#newConcept__anchor)
2. check out [common factory docs](https://hyperledger.github.io/composer/jsdoc/module-composer-common.Factory.html#newConcept__anchor)

**Comment by dselman** [comment]
Fixed
