### ISSUE TITLE
Documentation on "Installing and developing with Hyperledger Composer" needs correction

### ISSUE THREAD

**Issue by LarissaAuberger** [hyperledger/composer#1613]
## Context
The documentation refers to prereqs-ubuntu.sh, but it is not available anymore.
https://hyperledger.github.io/composer/installing/development-tools.html

## Expected Behavior

Please provide instructions on how to install Hyperledger Fabric/Composer prereqs without prereqs-ubuntu.sh. Thanks.

**Comment by davidkel** [comment]
This is a duplicate of #1587 which has been fixed and will go out in the next release. The referenced issue also has a workaround you can use for now.

**Comment by davidkel** [comment]
This should now be fixed on the website

**Comment by LarissaAuberger** [comment]
Thanks!
