### ISSUE TITLE
System transactions appear in the playground

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#1616]
The transaction type dropdown in the submit transaction dialog lists all the system transactions,
along with transactions belonging to the business network

## Context

Running [playground release validation](https://github.com/hyperledger/composer/blob/master/contrib-notes/release-process/playground-validation.md#test-and-id-page).

## Expected Behavior

I only expected to see transactions defined in the business network, as before

## Actual Behavior

![image](https://user-images.githubusercontent.com/3535067/28411600-2b61c316-6d39-11e7-9d3b-fcb37a76be70.png)

## Possible Fix

Filter out system transactions? Distinguish between business network and system transactions? Add a separate button/dialog/mechanism for running system transactions? Something else- tagging design!!!

**Comment by sstone1** [comment]
We don't want system transactions in this list - they should all be exposed via first class operations elsewhere in the playground. This is my boo boo, so I'll clean it up.

**Comment by sstone1** [comment]
Fixed in PR https://github.com/hyperledger/composer/pull/1644.
