### ISSUE TITLE
Long error messages hidden by buttons/UI elements in dialog footer

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#1617]
![image](https://user-images.githubusercontent.com/3535067/28413052-20073d5c-6d3e-11e7-9d02-429f7f22c818.png)

## Expected Behavior

Able to read validation errors

## Actual Behavior

Long validation errors obscured

## Possible Fix

Don't hide validation errors

## Steps to Reproduce

Edit json in submit transaction dialog (I deleted a character in the manufacturer resource)

## Existing issues

This problem has been noted before but I could not find any github issue

**Comment by KaiUsher** [comment]
This was discussed earlier with @EdMoffatt! Similar situation with incorrect alignment is prevalent in other test dialogs too, such as when creating a participant/asset.

![screen shot 2017-07-20 at 11 38 14](https://user-images.githubusercontent.com/16639383/28417492-3f9801d0-6d50-11e7-8c1f-598b2c6e92af.png)

**Comment by EdMoffatt** [comment]
Slopey-shoulders time :)  Think this would be worth @winslet taking a look at, to hi-fi up and show how we should be constructing these things!

We should probably have a little check of the alignment and sizing of all the various bits of text we have in there, and then it'd be useful to see "no error", "one-line error" and "multi-line error" to establish how stuff shifts around to display the error messages.

**Comment by winslet** [comment]
Hmm im playing around and this may not be an easy fix if we would like to get it right. If I can come up with a catch all solution itll be on here as soon as.

**Comment by caroline-church** [comment]
This has been fixed so closing
