### ISSUE TITLE
Unnecessary scroll bar in Playground

### ISSUE THREAD

**Issue by 14gracel** [hyperledger/composer#1621]
![image](https://user-images.githubusercontent.com/17450713/28417437-0321d2b2-6d50-11e7-9404-6f2892191692.png)

## Expected Behavior
There should only be two scroll bars, one for the list of files and one for the code editor

## Actual Behavior
There is an extra scroll bar on the entire window

## Your Environment
* Google Chrome Version 59.0.3071.115 (Official Build) **(64-bit)**
* Mac OS Sierra

**Comment by sstone1** [comment]
@caroline-church anything we can do about all of these scrollbar issues?

**Comment by caroline-church** [comment]
Yes when people make code changes the reviewer needs to actually try the code to make sure they haven't caused extra scroll bars

**Comment by sstone1** [comment]
Maybe we should dedicate a penguin for scroll bar breakages? 🐧

**Comment by caroline-church** [comment]
I think a penguin should go to reviewers who don't review properly

**Comment by markcastle3** [comment]
Is this rea

**Comment by caroline-church** [comment]
This should be fixed by https://github.com/hyperledger/composer/pull/1711

**Comment by caroline-church** [comment]
fixed so closing
