### ISSUE TITLE
Relationship query parameters require fully-qualified syntax 

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1622]
When using the rest server to perform queries, the input for query by trader required me to enter the trader as 
```
resource:org.acme.trading.Trader#TR1
```
Other interactions such as issue identoty when the FQI is required would not include the text `resource:` and this is an exposure of internals.
My first attempt when prompted was
`TR1` as that is the name I gave it originally and I also tried `org.acme.trading.Trader#TR1`, both failed but these 2 would seem the obvious ones someone would want to use.

**Comment by sstone1** [comment]
> Other interactions such as issue identoty when the FQI is required would not include the text resource: and this is an exposure of internals.
This has actually been changed so that we use the `resource:` syntax for identity operations.

**Comment by sstone1** [comment]
Tagging as enhancement as this is one of those "working as designed, but not as usable as it could be" type situations.

**Comment by fenglianxu** [comment]
Ideally this would require a regex support for query feature enhancement. 
eg. owner == $regex 
 $regex = TR1$ 

Find out all the owner that ends with TR1

**Comment by sstone1** [comment]
As far as I know, nobody is working on this at the moment or planning to work on it, so closing. 
If somebody wishes to work on this in the future, then please reopen this issue or open a new issue.
