### ISSUE TITLE
If a second playground connects to the same fabric where another playground is using, any created assets/transactions are wiped

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1627]
The following problem was reported where a user started a hyperledger fabric v1 system and started playground to connect to it. They then did some asset/participant creation and transaction invocation.
A second playground was started and connected to the same hyperledger fabric system and the initial data created by the first playground user was lost.

**Comment by caroline-church** [comment]
I just tried this out and the only way i could make the assets/participants go away was if i imported a business network.

**Comment by EdMoffatt** [comment]
Wondering whether it's worth also doc'ing along with this one that you're going to have a bad time if you have 2 users interacting with the same Playground connected to a fabric e.g. if you stand up Playground on a publicly accessible IP, and give that out to other devs.

Essentially, Playground only validates the changes you're making against the state of the network that it knew of before you started editing...  So if another user has come in and changed the business network "underneath" it, it'll still let that second user deploy their changes, most likely totally blasting away whatever the first user had done.

**Comment by EdProsser** [comment]
I'm not keen on documenting the ways users can screw up. If there's no way we can design it so that users don't fall off a bridge then I'll add a topic to the docs, but I feel like we should be adding railings to the bridge rather than adding signage saying "PSA: Don't fall off."

**Comment by markcastle3** [comment]
@sstone1 can we get an agreement on the way forward for this please ?

**Comment by caroline-church** [comment]
We need to know what circumstances this happens in first. The only way I know of is if you import a new business network.

**Comment by sstone1** [comment]
We should spend the minimum amount of time on this one. Multiple concurrent business network editors is not a scenario we care about at this time 😉 

@EdProsser I think we just need a single disclaimer sentence along the lines of "do not use multiple playground instances to edit business networks at the same time" (as Caroline suggests, this can only happen during an update/import operation).

**Comment by EdProsser** [comment]
I've added some text into the new playground section.

**Comment by EdProsser** [comment]
The text got added, can this issue close? @sstone1 @caroline-church @EdMoffatt

**Comment by EdMoffatt** [comment]
It's lookin' good to me.  We've delivered the level of fix we're looking to achieve for now, so I say close it!

**Comment by caroline-church** [comment]
Closing
