### ISSUE TITLE
Investigate to see if it is possible to support Windows 10 WSL

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1628]
Could we support composer running in this environment ? Not sure and obviously trying to use the pre-reqs to install docker isn't going to work, but it would be worth a little bit of investigation. 

If docker can be called from it to drive docker for windows and docker-compose works, otherwise it may be possible to do a sort of 2 step approach. One part starting the development server and WSL running the cli, rest server, playground.

Another thing to consider is that it is more capable if developer mode is turned on.

**Comment by prasoc** [comment]
I use WSL to develop, too. Docker for Windows works quite well, but you wouldn't be able to complete all of the set up steps from within "npm install". 

Also one feature which there isn't a solution is setting up a test environment for Karma to run. 
WSL has an [issue opening Chrome](https://github.com/Microsoft/BashOnWindows/issues/2235#issuecomment-309801275), but the comment says that we could stub a few features to allow Chrome to work - I don't feel that this is up to us to solve however.

**Comment by prasoc** [comment]
There's also an issue with `require("os").networkInterfaces()" being undefined in the Bash prompt. 

A small fix (a bit of a hack) is to go into:

```composer/node_modules/macaddress/index.js```

and add below the top line the following:

```os.networkInterfaces = () => ({});```

**Comment by davidkel** [comment]
@prasoc Have you managed to install composer-cli, composer-rest-server and composer-playground successfully in WSL or are you focussing more on trying to create a development environment for developing composer itself ? 
The first step of this journey was to try to see how to see if there was a simple way to get composer users up and running on a windows platform (without having to install the microsoft compilers, python and openssl source libraries for example) So WSL seemed like a possibility. 
What level of Windows 10 are you and have you turned on Windows 10 developer mode ? WSL may have some improvements in the latest "Creators" Update and turning on developer mode enhances WSL apparently.

**Comment by davidkel** [comment]
Running on Windows 10 Home Creator update with development mode enabled for WSL which is based on Trusty (not the 16.04LTS in windows store which will be generally available in the autumn rather than just insider users now)
- Have a simpler version of prereqs-ubuntu.sh to install some basic stuff
- installed composer-cli and composer-playground and both execute 
- It should be possible to access the docker command line interface from Bash if you have installed Docker for Windows (see https://blog.jayway.com/2017/04/19/running-docker-on-bash-on-windows/)

The final part would be to test that you can run docker-compose from the bash shell. 
If that is the case then we should have a simpler environment than trying to do a native windows implementation that will work for windows users who meet the pre-reqs.

**Comment by im89097733** [comment]
@davidkel thanks for earlier response and pointing me here. For my own edification I have been proceeding to further understand the ecosystem wrt local playground install and eventual full local dev environment on my Windows 10.  Hopefully my dump below is mutually helpful.

So to summarize I have Win 10 Pro with HV and Docker/Docker Compose latest versions.
I am up against a problem where the command below fails.

docker exec peer0.org1.example.com peer channel create -o orderer.example.com:7050 -c composerchannel -f /etc/hyperledger/configtx/composer-channel.tx

the detailed error is this:
Error: channel create configuration tx file not found open C:/Users/Mark/AppData/Local/GitHub/PortableGit_f02737a78695063deace08e96d5042710d3e32db/etc/hyperledger/configtx/composer-channel.tx: no such file or directory

And, for sure when I look into that  location i do not see the config.  However, when I bash into the docker instance for peer0 i see the config where expected.

So there seems to be some break in the lower mapping in the peer channel create.

Q: is there something I can do to hack this? 

UPDATE: when I bash into peer0 and run the peer channel create -o orderer.example.com:7050 -c composerchannel -f /etc/hyperledger/configtx/composer-channel.tx it runs as expected without obvious error...

UPDATE:  I just realized I am not actually using WSL proper but the environment i get with Git Shell atop of powershell.  Is this a non starter? Or are there merits to seeing if this arch path will work?

Cheers.

**Comment by davidkel** [comment]
@im89097733 The Git Shell is probably some sort of MinGW environment which I haven't played with as yet. I wanted to focus on WSL first purely because I think it would provide a more complete linux environment, and also if you are on the Creator Update then as per the link I posted it should be easy to invoke docker commands from it and I would hope docker-compose would also work seemlessly as well.

**Comment by im89097733** [comment]
I missed the part in that link about binding/proxying the wsl docker to the windows docker.  I was trying to avoid a WSL docker engine..but I see that the link explains how to keep the engine in windows.  So I will try that.  Although I still think i am just a trick away from getting Git Shell working.

Thanks

**Comment by prasoc** [comment]
@im89097733 yeah we're using WSL (for Windows 10). 

There isn't a Linux kernel below it, however, (which Docker requires) so Docker needs to be external to the environment and ported in. 

Using this command: `export DOCKER_HOST='tcp://0.0.0.0:2375'` and then running the command `ln -s /mnt/c /c` to allow git to translate Windows paths to Linux paths gets me very far in running HL containers.

Having some issues with the certificates, too. Will get some detailed analysis of where it's failing, but it's in a different place than the error you're getting.

**Comment by im89097733** [comment]
@prasoc @davidkel @mbwhite 
Ok I have local composer playground on Windows 10 Pro Hyper-V without WSL (but with Git Shell) working.
Of course, I had to hack the scripts and do a 2 pass.  but it works and if someone else can hack the nested payload in install-hlfv1.sh then it should be good all around.  (pretty sure my hacks don't bust linux.. I will test)

It is possible I missed documenting some of the hacks so let me know if you try this and it does not work.
hacks follow:
Pre-Req
=========
Windows 10 Pro (or other supporting Hyper-V)
Hyper-V turned on in BIOS if necessary
Docker and Docker Composer installed
Git Shell on Windows

Steps
======
1) open Git Shell
2) run Bash
3) create a playground directory and cd into it
4) run the curl from here: https://hyperledger.github.io/composer/installing/using-playground-locally.html
5) make the changes listed below
6) ./composer.sh stop
7) ./composer.sh
8) launch browser to port 8080 and enjoy
 
Changes to HL Composer install
==========================================

startFabric.sh (in the hlfv1 directory)
===========================================
line 21 => insert '/' at 106
line 24 => insert '/' at 41
line 34 => comment out
line 44 => comment out


composer.sh
======================
line 65 => insert '/' at 28
line 66 => insert '/' at 46
line 93 => change or ignore the false error message

**Comment by im89097733** [comment]
Just leaving a note to say that the script hacks listed above work on Amazon Linux instance... so if the payload inside of the install-hlfv1.sh is modified accordingly then you will have a single click cross platform solution...although testing on just one type of Linux is not definitive.  And, of course, Windows Users will require Git Shell for bash compatibility.  No WSL and dual docker configurations required,

**Comment by davidkel** [comment]
WSL for driving a local fabric, a couple of issues to account for.
The scripts and users use the `docker` command but from wsl you need to type `docker.exe` to get it to invoke.
The same applies for docker-compose (can't use a local one you need to use the one shipped with docker for windows as a local python one won't be able to communicate with the hyperv virtual machine where the linux vm to host docker images is running). 
2 problems with docker-compose on WSL, first is that it doesn't like the console encoding of cp65001. You need to invoke /mnt/c/Windows/System32/chcp.com 437 to change to a supported encoding. The other is the script passes the name of the file as seen within bash, but docker-compose.exe can't resolve that path as effectively it is a native windows process outside of the WSL dynamic translation. It would be possible to pre-pend a path to the windows location (may not work as supposedly that directory my not be accessible from a windows binary) or copy the file to a known windows path and have the script call the right one.

**Comment by davidkel** [comment]
My Conclusions for this are
1. Don't use WSL to drive and run a local fabric environment. We could take the Git Shell solution presented above, but ideally the scripts should be native windows shell or power shell scripts
2. The same would apply for the one-click install for playground and Vehicle LifeCycle Demo
3. Use WSL for CLI such as composer-cli, composer-hyperledger-generator, composer-rest-server, and CLI for playground with a setup script to run which excludes docker and docker-compose) and this provides an environment where everything can be done bar from fabric control and a slightly configured docker container.

**Comment by davidkel** [comment]
Script to ensure CLI pre-reqs are installed.
```
#!/bin/bash

# Usage:
#
# ./prereqs-wslbash.sh
#

# Exit on any failure
set -e

# Update package lists
echo "# Updating package lists"
sudo apt-get update

# Install Git
echo "# Installing GitHub"
sudo apt-get -y install git

# Install nvm dependencies
echo "# Installing nvm dependencies"
sudo apt-get -y install build-essential libssl-dev

# Execute nvm installation script
echo "# Executing nvm installation script"
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash

# Set up nvm environment without restarting the shell
export NVM_DIR="${HOME}/.nvm"
[ -s "${NVM_DIR}/nvm.sh" ] && . "${NVM_DIR}/nvm.sh"
[ -s "${NVM_DIR}/bash_completion" ] && . "${NVM_DIR}/bash_completion"

# Install node
echo "# Installing nodeJS"
nvm install --lts

# Configure nvm to use version 6.9.5
nvm use --lts
nvm alias default 'lts/*'

# Install the latest version of npm
echo "# Installing npm"
npm install npm@latest -g

# Ensure that CA certificates are installed
sudo apt-get -y install apt-transport-https ca-certificates

# Install python v2 if required
set +e
COUNT="$(python -V 2>&1 | grep -c 2.)"
if [ ${COUNT} -ne 1 ]
then
   sudo apt-get install -y python-minimal
fi


# Print installation details for user
echo ''
echo 'Installation completed, versions installed are:'
echo ''
echo -n 'Node:           '
node --version
echo -n 'npm:            '
npm --version
echo -n 'Python:         '
python -V

# Print reminder of need to logout in order for these changes to take effect!
echo ''
echo "Please logout then login before continuing."
```

**Comment by sstone1** [comment]
Let's keep all Windows related stuff under one item please in #65.
