### ISSUE TITLE
JavaScript API documentation not available from left bar navigation link

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1632]
go to https://hyperledger.github.io/composer/
click on Docs at top right
go via the left hand navigation and wait for the reference index menu to expand
then click on API documentation

Note there isn't any what to get to the Actual API documentation (or if there is I and Dave Gorman couldn't find it)

One path to it is to click on the Reference Index menu item itself
then you can click on the Javascript APIs link to get to the API documentation

**Comment by EdProsser** [comment]
This is fixed. :)
