### ISSUE TITLE
Improve the experience of the Angular2 Skeleton App so it is more helpful in getting started

### ISSUE THREAD

**Issue by winslet** [hyperledger/composer#1635]
We would like to improve the overall UI and experience a user gets when they generate the Angular2 skeleton app locally.

This relates to issue #400 

Prereqs
- Understand the problems faced in issue #400 (there is currently no UI for participants and transactions).
- Understand the development pipeline for how this is built to see how easy it is to change the ui.
- Research what changes could benefit the users of this application.
- Potentially use the styling from the playground to influence this app.

**Comment by sstone1** [comment]
Replaced by CIP #3136.
