### ISSUE TITLE
As a user I would like to be able to add a photo to an ID card

### ISSUE THREAD

**Issue by winslet** [hyperledger/composer#1636]
It was originally proposed that photos should be able to be used for easy identification of ID cards.

We need to work out a way to easily upload images to ID cards both during the creation step and editing after.

This relates to the hifi's seen in issue #1412 

eg.

![transaction registry copy 3](https://user-images.githubusercontent.com/13980028/27737620-b1bcc7e2-5da0-11e7-8f92-9c1c8968ac84.png)

**Comment by sstone1** [comment]
As far as I know, nobody is working on this at the moment or planning to work on it, so closing. 
If somebody wishes to work on this in the future, then please reopen this issue or open a new issue.
