### ISSUE TITLE
Query Order expression is failing

### ISSUE THREAD

**Issue by hernaramiro08** [hyperledger/composer#1640]
Nowadays, I am trying to define the sorting for a query's results, but I am getting multiple errors

## Context
The queries order expression is throwing multiple errors.

## Expected Behavior
I would expect get the query results ordered by a given field

## Actual Behavior
I have defined a Trader participant with the following properties:

1.- traderId
2.- firstName
3.- lastName
4.- age

When I try to sort by firstName and lastName using the expression "ORDER BY [lastName ASC, firstName DESC]", I get an error menssage "Couch DB Error:unsupported_mixed_sort, Status Code:400, Reason:Sorts currently only support a single direction for all fields.)"

When I try to sort by just one field using the expression "ORDER BY [age DESC]", I get an error menssage "error trying to query chaincode. Error: chaincode error (status: 500, message: Error: http: read on closed response body)"

## Steps to Reproduce
1. I have defined two queries:
2. The first one is:
query Q1{
  description: "Select all traders older than 18."
  statement:
      SELECT org.acme.mynetwork.Trader
          WHERE (18 < age)
            ORDER BY [lastName ASC, firstName DESC]
}

3. The second one is:
query Q2{
  description: "Select all traders older than an age given."
  statement:
      SELECT org.acme.mynetwork.Trader
          WHERE (_$ageParam < age)
            ORDER BY [age DESC]
}

## Your Environment
* Version used: Hyperledger Composer v0.10.0
* Environment name and version: Node v6.11.1, Docker v17.06.0-ce
* Operating System and version (desktop or mobile): Fedora 25 WorkStation

**Comment by sstone1** [comment]
This looks a limitation in CouchDB that we may need to block in our query validator.
> Couch DB Error:unsupported_mixed_sort, Status Code:400, Reason:Sorts currently only support a single direction for all fields.

**Comment by fenglianxu** [comment]
I assign this to myself and have a investigation to see what we need to block in our query validator.

**Comment by hernandezramiro** [comment]
Thank you for your feedback and support @fenglianxu @sstone1

**Comment by dselman** [comment]
Note that query validation (checking references to model elements) is going in under:
https://github.com/hyperledger/composer/pull/1656

**Comment by arnabsutar** [comment]
I am also facing the same issue.

**Comment by fenglianxu** [comment]
I tested this from the CouchDB UI with below Mango query:
{
  "selector": {
    "data.age": {
      "$gt": 18
    }},"sort":[{"data.lastName":"asc"},{"data.firstName":"desc"}]
  }

and I have got below error:
**Sorts currently only support a single direction for all fields.**
This is limitation of CouchDB and we have two options for this issue:

1. Composer Sort validation can throw an exception on an unsupported mixture directions -- stop sending this query to the chaincode but will need to change code again when couchdb starts to support this mixture sort issue. 
2. Leave this implementation as how it works today  -- this issue will be gone once couchdb supports this mixture sort issue. 

When I tested this from the CouchDB UI with blow test case:
{
  "selector": {
    "data.age": {
      "$gt": 18
    }},"sort":[{"data.age":"desc"}]
  }
I got this error:
Unknown Error: mango_idx :: {no_usable_index,missing_sort_index}
This issue needs further investigation on this.

**Comment by hernandezramiro** [comment]
@fenglianxu thank you for your feedback. Please, let me know if there is anything I can do for you.

**Comment by nileshjagtap1916** [comment]
I am also having same issue. Please let me know if there is any work around.

**Comment by benjy** [comment]
I have the same issue with only one direction and one sort field.

Example query:

```
query selectLatestDataFiles {
  description: "Select latest data files"
  statement:
      SELECT example.com.DataFile
          ORDER BY [createdTime DESC]
}

```

From the logs

```
Rewritten query with data wrapper: {"limit":10000,"selector":{"$and":[{"chaincodeid":"aws-network"},{"data.$class":"example.com.DataFile","data.$registryId":"example.com.DataFile","data.$registryType":"Asset"}]},"skip":0,"sort":[{"data.url":"desc"}]}
```

```
Couch DB Error:unknown_error,  Status Code:500 Internal Server Error  Reason:Unknown Error: mango_idx :: {no_usable_index,missing_sort_index}
```

**Comment by benjy** [comment]
You can temporarily make this work by going to the CouchDB UI and adding the index.

E.g.

* Go to: http://localhost:5984/_utils/#database/composerchannel/_index
* Create an index like this:

```
{
  "index": {
    "fields": [
      "data.createdTime"
    ]
  },
  "type": "json"
}
```

**Comment by davidkel** [comment]
@andrew-coleman as you mentioned this, here is an issue regarding the order direction which has been around for a while :-)
