### ISSUE TITLE
 Deployed chain-code (0.9.2) is incompatible with client (0.10.0)

### ISSUE THREAD

**Issue by LarissaAuberger** [hyperledger/composer#1645]
I deployed the digitalproperty-network and try to use composer-rest-server to access the network.
This fails with the error: Deployed chain-code (0.9.2) is incompatible with client (0.10.0).
Please provide a workaround or guidance on how to fix this temporarily. Thanks!

## Context
composer -version shows

composer-cli                   v0.10.0
composer-admin                 v0.10.0
composer-client                v0.10.0
composer-common                v0.10.0
composer-runtime-hlf           v0.10.0
composer-runtime-hlfv1         v0.10.0

Digitalproperty Network is cloned via
git clone https://github.com/hyperledger/composer-sample-applications.git
npm run deployNetwork and npm test ran without problems.
npm run listAssets shows a list of two assets.

However, composer-rest-server -p hlfv1 -n digitalproperty-network -i xxx-s xxx -N always returns with error:
Deployed chain-code (0.9.2) is incompatible with client (0.10.0)

## Expected Behavior
Composer should be able to handle the business network

## Actual Behavior
composer-rest-server -p hlfv1 -n digitalproperty-network -i xxx-s xxx -N always 
returns with error
Deployed chain-code (0.9.2) is incompatible with client (0.10.0)

## Possible Fix
Backward compatibility or consistent packaging.

## Existing issues
This issue sounds similar 
https://github.com/hyperledger/composer/issues/959

## Your Environment
Ubuntu Linux

$ node --version
v6.11.1
$ npm --version
5.3.0
$ docker --version
Docker version 17.06.0-ce, build 02c1d87
$ docker-compose --version
docker-compose version 1.13.0, build 1719ceb

**Comment by sstone1** [comment]
Fixed in https://github.com/hyperledger/composer-sample-applications/pull/73.
Need to pull the latest changes to composer-sample-applications, remove all installed modules (`git clean -xdf` or `rm -rf node_modules`), and try again.

**Comment by LarissaAuberger** [comment]
Thanks for the fix, Simon - works fine now.
