### ISSUE TITLE
Error message reveals user secret

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1653]
It is possible to reveal the user secret by triggering a specific error when using identities. This is present in the embedded runtime.

![image](https://user-images.githubusercontent.com/8394544/28532101-c4c7f444-7090-11e7-9fda-8c812b2a86e3.png)

## Context
Experimenting with ID addition to wallet, managed to reveal my user secret

## Expected Behavior
Should never reveal user secret in an error message

## Actual Behavior
Can see user secret in error message

## Possible Fix
Don't show user secret in error message

## Steps to Reproduce
1. Create participant
2. Issue ID to participant (do not add to wallet)
3. Add to wallet - specify userID correctly, but input an invalid secret
4. Try to use newly created ID 

## Your Environment
Ubuntu/Chrome - also on staged

**Comment by sstone1** [comment]
This isn't a P1. It only applies to our simulated Blockchain runtimes - either the embedded runtime (in memory) or the web runtime (in the browser local storage). For these runtimes, you can easily get at the secret using a debugger or by inspecting browser local storage.

**Comment by sstone1** [comment]
Dropping to P3; there's no security exposure here as this only applies to the simulated Blockchain runtime environments (embedded & web).

**Comment by sstone1** [comment]
P3 and no action in three months; clearly not important and never going to get fixed, so closing.
