### ISSUE TITLE
Composer Playground does not update list of assets in Test pane after a deploy

### ISSUE THREAD

**Issue by silliman** [hyperledger/composer#1654]
## Context

When I update a model file in the Hyperledger Composer Playground to add a new asset and then click the Deploy button, the new asset does not appear in the list of assets when the Test link is clicked. If I do a second Deploy without any changes from the first deploy- e.g., if I just add a space into the file in order to activate the Deploy button, and change nothing else-  then the new asset appears when I click the Test link.  

I first observed this behavior with Composer 0.10.0.

## Expected Behavior

I expect the new asset to appear after the Deploy, without having to do a second deploy.

## Actual Behavior

I need to do a second, "no-op" Deploy before the new asset appears

## Steps to Reproduce

1.   Install composer, composer-playground locally and start it, i.e.:
> npm install -g composer
> npm install -g composer-playground
> composer-playground
2.  Browse to http://localhost:8080
3.   In the sample network loaded by default, update the model file to add a second asset, e.g.:
>asset SecondSampleAsset identified by assetId {
>  o String assetId
>  --> SampleParticipant owner
>  o String value
>}
4. Click the Deploy button.  
5. Click the Test link near the top and the new asset is not listed
6. Make a trivial change to the Model file that doesn't actually change any model definitions,  such as just adding a space anywhere in the file in order to activate the Deploy button
7. Click the Deploy button.
8. Click the Test link and now the new asset is listed.

I have observed this behavior both when using the Web profile (as in the above steps) or while connected to a Hyperledger Fabric v1.0.0 network.

**NOTE** I suspect this may be related as I also have just observed this starting with Composer 0.10.0, and I can write a separate issue if necessary. 
1.  Deploy a Hyperledger Composer Business network into Hyperledger Fabric v1.0.0, e.g. digitalproperty-network from the hyperledger/composer-sample-applications GitHub repo
2.  Import that network's *.bna file into Hyperledger Composer Playground
3.  Modify the model file in the Hyperledger Composer Playground, e.g. add a new asset
4.  Deploy the changed file in the Playground  (twice, because of the bug described in this issue)
5.  Export the *.bna file from the Playground
6.  It takes a *second* `composer network update ...` command in order for the new asset to appear in the output of a `composer network list` command.

## Your Environment

This behavior did not occur in prior Composer versions I have worked with, including 0.8.x and 0.9.x
I have observed this behavior in Chrome and Firefox, and with the playground running in an Ubuntu 16.04.2 VM on my laptop and with it running in an Ubuntu 16.04.2 instance running on Linux on IBM Z

**Comment by dselman** [comment]
@caroline-church can you get someone to try to reproduce please.

**Comment by jt-nti** [comment]
@mbwhite has been able to reproduce this on the command line;

- Deploy a network
- Add a new asset
- Update the network
- New registry is not created
- Add new field to the repo
- Update the network
- New repo will appear

**Comment by jt-nti** [comment]
Log collected with `docker logs dev-peer0.org1.example.com-org-acme-biznet-0.11.0 > cclog.txt 2>&1`...

[cclog.txt](https://github.com/hyperledger/composer/files/1199791/cclog.txt)

**Comment by mbwhite** [comment]
Going to spend a couple of minutes this morning taking a quick look at some the Runtime code. 
Registry creation is around the areas I've been looking at recently.

This plays into the discussion on how the data is migrated between versions of a business network model.

**Comment by caroline-church** [comment]
fixed so closing
