### ISSUE TITLE
Wording on the ID Dropdown above Logout should be "ID Registry"

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1662]
Text on the dropdown in the top right after logging in to a business network should just be:

"ID Registry"

(As opposed to "ID Repository" and then the name of the connection profile).

As discussed in show 'n' tell - we don't actually think the other stuff is useful :)

**Comment by nklincoln** [comment]
Righto - easy one this - minor edit in the app.component.html file (lines 42-43)
