### ISSUE TITLE
CLI Required to be able to create an ID Card which can be imported into Playground

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1671]
As part of the staging of the release of ID Card support in playground, there will be a need for a CLI that can create an ID Card which can be imported into playground (as playground will not support adding certificates to begin with)

The input to the CLI will be Options such as 
- Public Cert, Private Key PEM files (optional)
- The name of this identity
- The role this identity might have (optional)
- The secret of this identity (if registered but not activated, ie no PEM files) (optional)
Either the crypto material or the secret must be provided though.
- The name of the connection profile to include
- The output filename (or output location)

The proposal is 
`composer card create ...`

**Comment by mbwhite** [comment]
A `composer card create`  that takes the different components and forms up an archive... needed to support 

https://github.com/hyperledger/composer/issues/2448

**Comment by bestbeforetoday** [comment]
Resolved by #2487
