### ISSUE TITLE
"Updating Hyperledger Composer" Guide Doesn't Work

### ISSUE THREAD

**Issue by pansoft34** [hyperledger/composer#1678]
## Context
When I tried to update my Composer version from 0.9.2 to 0.10.0, I followed the "Updating Hyperledger Composer" procedure, found under the "Managing Index"; however, after running the given commands, when I went to run a tutorial script, I was told that my composer version wasn't compatible.

## Expected Behavior
Tutorial Script should have run without issues.

## Actual Behavior
I received an error, saying that my versions weren't compatible

## Possible Fix
I realized that the update procedure told me to uninstall and reinstall "generator-fabric-composer". I believe that it should be "generator-hyperledger-composer" instead. When I used the latter, everything updated and my script ran without error.

**Comment by dselman** [comment]
Correct, it should be `generator-hyperledger-composer`

**Comment by EdProsser** [comment]
Oops... Will fix.
