### ISSUE TITLE
Developer tutorial uses npm install to build the BNA

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#1687]
The developer tutorial uses `npm install` to build the BNA.

`npm install` is for installing dependencies of a module.
`npm run prepublish` is for "preparing" the module before publishing to npm. In this case, we "prepare" the module by building the BNA, so that the BNA is included in the module published to npm.

All of the Composer sample networks have a `prepublish` target in the `package.json` file to create the BNA.

`npm install` used to run `npm run prepublish`, but this is deprecated behaviour and will be removed at some point. It looks like after threatening to do this in npm@5 they postponed the change.

Under "Generate the Business Network Archive", we should split these steps into:

1. Run `npm install` to install the devDependencies for building the BNA.
2. Run `npm run prepublish` to package the business network into a BNA file.

Users should only be running 2. when they want to repackage the business network into a BNA file, not 1.

**Comment by mahoney1** [comment]
I'll get this changed.. Do note that in its present state an `npm run prepublish` will not create an archive (BNA) a second time around (referring to Rocketchat thread about 'rebuilding an archive').  So in the Developer tutorial, the user runs a composer archive command to 'rebuild' a BNA (or say, for example a Composer user is iteratively adding to/editing any sample network files). So for any sample network, the 'prepublish' builds the BNA first time (all good) - after that, the 'dist' directory already exists so prepublish won't write a new BNA. Its a behaviour thing, but just for awareness.  The user could add a `"rebuild": "composer archive create --sourceType dir --sourceName . -a ./dist/my-network.bna"` to their package.json if they see fit.

**Comment by sstone1** [comment]
@mahoney1 the developer guide under "Update your package.json file" asks them to add a whole bunch of stuff, including the "prepublish" target that builds the BNA.

**Comment by mahoney1** [comment]
The npm install behaviour is updated, and the prepublish sequence is added to the Developer Tutorial.

**Comment by sstone1** [comment]
Closing as it looks like @mahoney1 has done the needful!
