### ISSUE TITLE
For Cucumber tests, support all primitive types in tables

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#1693]
_As a_ user developing a business network,
_I want_ to write Cucumber tests using tables to describe resources that have fields that are not only strings,
_so that_ I don't need to use JSON to describe simple resources.

## Context

When writing Cucumber tests, resources can be described in either table format or as JSON arrays. Table format is much easier for the less technical user, but all fields in the table are treated as strings so this approach is unusable for real-world models, which invariably contain fields of types other than string.

This story aims to automatically convert string values in tables into the type specified in the model, for only the primitive types:
- Boolean
- DateTime
- Double
- Integer
- Long

**Comment by sstone1** [comment]
Awesome! Good stuff @bestbeforetoday.
