### ISSUE TITLE
Pre-requisite node requirements update

### ISSUE THREAD

**Issue by AntCole** [hyperledger/composer#1694]
Docs only state Node V7 is not supported, does not mention V8

## Context
Please specify if V8 of Node is not supported

![image](https://user-images.githubusercontent.com/22615744/28721529-97e7c77c-73a8-11e7-8cb8-e5037f8ceb3f.png)

https://hyperledger.github.io/composer/installing/development-tools.html

**Comment by EdProsser** [comment]
v8 is not supported.
