### ISSUE TITLE
Ability to change Composer Pool size by doing an upgrade

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1700]
Upgrade has to go from x.y.z to x.y.z+1 I believe, but it may be possible to do something like
x.y.z to x.y.z.1 to x.y.z.2 and the .1, .2 etc is provided to allow for pool size changes.

Not sure how important this will be so creating issue for discussion.

**Comment by sstone1** [comment]
As discussed, not important as the pool will go away soon when we switch to Node.js chaincode.
