### ISSUE TITLE
As a Playground user I should be able to specify CA specific options when issuing Identities

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1704]
Couldn't find this in our current list of issues.

CAs could have special options which require the ability to specify these options generically.
The CLI supports this already
Playground doesn't.
For example The Fabric CA server requires Identities to have an affiliation and role. The connector uses hardcoded defaults unless otherwise specified of 'org1' for affiliation and 'client' for role. If a CA has been setup with different affiliation names then unless you specify the correct affiliation then creating a new identity will fail. All the other options do not stop creating an identity.

**Comment by sstone1** [comment]
As far as I know, nobody is working on this at the moment or planning to work on it, so closing. 
If somebody wishes to work on this in the future, then please reopen this issue or open a new issue.
