### ISSUE TITLE
CLI test coverage needs improvement

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1707]
The current CLI unit test coverage is a little low and could do with improvement on coverage; some functions are currently untested, which we should aim to address as soon as possible

## Expected Behavior
 - composer-cli/lib/cmds &/lib/cmds (untested)
 - composer-cli/lib/cmds/network & /lib (untested items and low coverage)
 - composer-cli/lib/cmds/runtime & lib (low coverage)
 - composer-cli/lib/cmds/archive & lib (low coverage)
 - composer-cli/lib/cmds/generator & lib (low coverage)
 - composer-cli/lib/cmds/utils (low coverage)

**Comment by nklincoln** [comment]
#2235 would help this 👍

**Comment by samjsmith** [comment]
@nklincoln test coverage doesn't look that low to me from running locally Nick but I'll try to plug the gaps in the couple of JS files that aren't 100%
![image](https://user-images.githubusercontent.com/16335033/33674888-cb0f58ba-daa8-11e7-8471-9f292ee60eba.png)
