### ISSUE TITLE
error query of asset where filter by owner

### ISSUE THREAD

**Issue by cansado2930** [hyperledger/composer#1726]
When I try to do the following query, it launchs an error:
Query: SELECT org.tmp.tmp2.Contract WHERE (client == _$client) ORDER BY dateContract DESC LIMIT 10
Model:
asset Contract identified by contractId {
  o String contractId
  o DateTime dateContract optional
  o Double cost
  -->Member client 
  -->Business business
}
Error trying to query chaincode. Error: chaincode error (status: 500, message: Error: http: read on closed response body).
On the other hand, other queries works for example SELECT org.tmp.tmp2.Contract WHERE (cost> _$cost)
What are I doing bad?
Thanks you

## Context
I need to do filter of number of items that network give me.

## Expected Behavior
I wish an array of items where are max 10 items, order by date and items are from a specific client.

## Actual Behavior
It launchs error while other queries works correctly

## Steps to Reproduce
On sample query project, if you execute the query of search by owner with the id, it launchs error.

## Your Environment
* Version used: hlfv1
* Environment name and version :last version of Ubuntu, Firefox, nodejs and docker
* Operating System and version (desktop or mobile): Ubuntu 16lts

**Comment by fenglianxu** [comment]
Can you run this query please?
Query: SELECT org.tmp.tmp2.Contract WHERE (client == _$client) ORDER BY dateContract DESC 
What are your Member and Client model defined?

**Comment by cansado2930** [comment]
Thank for your answer, I have tried it and launchs same error. Model of Member and Bussiness are:

abstract participant User identified by Id {
  o String Id
  o String name
  o String email
}

participant Member extends User{
  o Double balance
}

participant Business extends User {
  o Double balance
  o Boolean verifiedAccount
}
Thanks you

**Comment by ykcai** [comment]
Anyone update on this issue? I am also seeing the same problems

**Comment by sstone1** [comment]
Need to reproduce and diagnose this. This error message `Error: http: read on closed response body` suggests that Fabric or CouchDB are failing/crashing to handle the query we're sending.

**Comment by ykcai** [comment]
You can work around this by added a index in the CouchDB either locally or remotely https://stackoverflow.com/questions/45919898/order-by-not-working-in-named-query/46572338#46572338

**Comment by markcastle3** [comment]
@nklincoln fancy taking a look at this one ?

**Comment by PPCM** [comment]
I have the same issue and I resolved it with the work around, but it's not easy to find right fields to describe.
Is it possible to imagine a new keyword in CTO file which describe indexes?

**Comment by fenglianxu** [comment]
@PPCM @cansado2930 @ykcai  Here are the steps to make your query work:
Query: SELECT org.tmp.tmp2.Contract WHERE (client == _$client) ORDER BY [dateContract DESC] LIMIT 10

1. create an index with any property other than the default _id in couchDB per @ykcai instruction
2. create a query model as above and deploy your business network on Fabric runtime
3. run composer rest server to see find out your query name
4. provide the client field with a full resource string at REST server explorer eg. in my test case I have a owner has a full resource value: **resource:org.acme.trading.Trader#Trader2**
You should be able to see the query results back. 

Currently Fabric has limitations support below features:
1. API to create an index with non-id fields 
2. ORDER BY 
3. LIMIT
This is not a defect and we will support all of them once Fabric support them.  I close this defect now.

**Comment by kletkeman** [comment]
Well, I get to differ. I just ran into the issue and there is no mention in the docs that this feature is unsupported. So it is definitely a defect until you explicitly state **unsupported** against all the advanced query features in all the documents.
