### ISSUE TITLE
Performance of the systest dropped considerably after Historian

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#1734]
Performance of the sys tests has dropped considerably since the
Historian has been introduced. We've had to split out the systest to 2 groups again.

**Comment by sstone1** [comment]
Historian should never have been merged with a known massive performance degradation!

**Comment by mbwhite** [comment]
@sstone1 @nklincoln  Updates to the code have been made to improve performance. 
Latest flame graphs indicate that bottlenecks are now within the GRPC code.

I'm going to close this therefore..
