### ISSUE TITLE
Drag and Drop on add file not right

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#1742]
Dragging and dropping has several problems:
- [ ] If you drag and drop a file on add file in the bluemix version the animation doesn't work
- [ ] The model changes size on drag enter
- [ ] The drop area doesn't disappear after drop
- [ ] If you leave the drag area the drag area doesn't unexpand

**Comment by alexsicart** [comment]
Hi @caroline-church I've tried and has a lot of problems, I'll try to solve and make a pull request!

**Comment by alexsicart** [comment]
It's working without problem right now

**Comment by alexsicart** [comment]
In which browser do you have this problem?

**Comment by caroline-church** [comment]
It is in chrome that you have a problem

**Comment by markcastle3** [comment]
@caroline-church is this still happening ?

**Comment by caroline-church** [comment]
yes this still happens

**Comment by sstone1** [comment]
P3 and no action in three months; clearly not important and never going to get fixed, so closing.
