### ISSUE TITLE
Copy button on example code is overlaying the text.

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1743]
There are many cases on the website where example code that has a copy button is having some of it's text being overlayed by the copy button itself and so you cannot read the text (although the copy will copy the full text). An example (but not limited to this one) is shown here for the Rest server TLS security page.

![image](https://user-images.githubusercontent.com/25582377/28924914-2ecd11f4-785b-11e7-9e4f-2bdf152dfad7.png)

here the copy button has hidden the `-k` that precedes the `/tmp/key.pem` parameter value

**Comment by winslet** [comment]
Fix is in #2057 closing for now.
