### ISSUE TITLE
Spinners on buttons cause buttons to grow

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1744]
There are multiple places where a user clicks on an action button and this then results in a spinner being placed inside the button until the action completes.

This is great, but it makes the button grow in size ... wouldnt it be so much nicer if the button retained its original size when the spinner appeared?

## Context
Looking at the button size mismatch hurts my eyes

## Expected Behavior
Spinner appears in button without size change

## Actual Behavior
Anger. Disappointment. Sadness. 

## Possible Fix
UI magic.

## Known locations:
1. import/replace model (the Deploy button)
2. create New Asset/ participant modal (create new button)
3. submit transaction modal (submit button)
4. connect modal (when switching profiles)

**Comment by caroline-church** [comment]
done so closing
