### ISSUE TITLE
Unable to view Historian registry in Safari browser

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1748]
When on the Test/Transactions page of Playground, the Historian registry is not visible.

It is visible in other browsers.

## Context/Expected Behavior
As a safari user, using a supported browser, I would expect to use all the Playground features...I cannot view/use Historian and (worse) have no way to inspect my transactions when I am testing my BN

## Actual Behavior
Only see page background

## Steps to Reproduce
Navigate to playground (staged or local), create a participant, look at transactions ... just a grey background. :penguin:

**Comment by alexsicart** [comment]
Hi @nklincoln there is a clear problem with the historian registry in Safari browser, I'll take a look and  try to make a pull request with the problem solved.

Cheers for submitting the pull request :)

**Comment by alexsicart** [comment]
This problem is already solved, this issue can be close?

Cheers!

**Comment by caroline-church** [comment]
Fixed so closing
