### ISSUE TITLE
Remove Fabric 0.6 mentions from the docs

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1749]
We've announced that we're deprecating support for Fabric v0.6, so we should remove instructions relating to 0.6 from our docs.  This issue is a hitlist of things to take out in our next minor-bump release!

- [x] PAGE: Introduction CHANGE: Edit the diagram to not mention v0.6 (suggest we could just have "Hyperledger Fabric" on there, and cut it down to 2 things at the bottom!)

- [x] PAGE: Installing a development environment CHANGE: Step 2: Starting Hyperledger Fabric, point 2...  Talks about choosing which version to use.  We should remove all mention of 0.6.  Although it's the default, we should probably still leave in an instruction to run the "export FABRIC_VERSION=hlfv1" because a) it doesn't do any harm and b) in the weird case that the user had set it to something different earlier on in the same terminal session, this'll make sure it's set correctly before they proceed.

- [x] PAGE: Installing a development environment CHANGE: Step 2: Starting Hyperledger Fabric, point 3...  Offers "If you want to swap between v0.6 and v1.0" < we should remove that sentence.

- [x] PAGE: Developer Guide CHANGE: Should remove the disclaimer about not using v0.6 (once it's not mentioned anywhere in the docs, we don't need to specify not to pick that option!)

**Comment by EdProsser** [comment]
oh wait, just realised @hannahrayner is assigned.

@hannahrayner Have you made any of these changes yet?

**Comment by EdMoffatt** [comment]
Hey Ed - Hannah's still getting set up ready to make changes and use Git and stuff.

Figured this would be a nice, contained bit of work for her to tackle as her first work item (includes some diagram edits too, so it's useful that she knows Illustrator) :)

Is that ok with you?  Hannah should definitely put down for the PR review :)

**Comment by EdProsser** [comment]
Yeah totally ok, here's the list of files affected in text only (there might be some more in diagram form):
- developer-guide.md
- connectionprofile.md
- call-out.md
- development-tools.md
- query.md

**Comment by winslet** [comment]
Diagram sorted with #2041 looks like we're all good.
