### ISSUE TITLE
Identity docs, CLI help and variable names refer to public key which isn't correct.

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1752]
To avoid further confusion we should ensure that we don't use public key for what is really the signer certificate. However people are not used to calling them the signer certificate so we should change all references both in the documentation, CLI help, API help etc to refer to them as public certificates (variable names of signerCert would be acceptable).

This is mainly a documentation issue but some of the documentation is in the source code rather than the website

**Comment by sstone1** [comment]
Can we just call it `certificate` please - I don't think "public certificate" is a thing, and the "signer" prefix is redundant unless we also prefix it to "privateKey".

**Comment by sstone1** [comment]
P3 and no action in three months; clearly not important and never going to get fixed, so closing.
