### ISSUE TITLE
Increase query test coverage for composer REST Server

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1754]
Current testing for queries in REST server needs to be increased to cover the supported types that users will be implementing. When extending the tests, the tests and test data should be constructed in such a way that different items are being matched, rather than the same items each time.

Double
 - Greater than
 - Less than

Integer
 - Greater than
 - Less than

Long
 - Equal to
 - Greater than
 - Less than
 - Not existing

Boolean
 - True
 - False

Timestamp
- Greater than or equal to
- Less than

String  
 - equal   
 - not equal

note that match and does not match are not supported yet. 

Enum
  - defined value
  - undefined value

Complex Query
 - timestamp and boolean
 - string and integer
 - supported and unsupported type

Transaction
 - ~~By ID~~
 - ~~By string content~~
 - By transaction type

Asset
 - By ID
 - By string content

Participant
 - By ID
 - By string content

**Comment by fenglianxu** [comment]
Below test case to query transactions by a specific transaction property is invalid. This is because the transaction namespace and the transaction property name space are different.  This is not supported at moment. 
Transaction
    By ID
    By string content

**Comment by fenglianxu** [comment]
The Timestamp test case is not currently supported for the rich query in Fabric. You specify the Datetime in the Composer query language just as limit but won't query the the expected results. 
We can move this test case until Fabric supports the Datetime in the rich query. 
Timestamp
    Greater than
    Less than

**Comment by fenglianxu** [comment]
The Timestamp only works as a string in CouchDB and there is a bug in the REST layer to parse the Datetime value in a string format to be a real value which does not exist in the couchDB database.

**Comment by fenglianxu** [comment]
close this issue now
