### ISSUE TITLE
TypeScript Generation does not Output Imports when Models Import Namespaces from Other Files

### ISSUE THREAD

**Issue by ScottMorris** [hyperledger/composer#1756]
When generating TypeScript code using `composer generator create`, and the models import namespaces that are from other model files, the generated TypeScript is missing the imports referencing the other TypeScript classes generated in separate files.

## Context

Without the imports the TypeScript code will not compile and cause applications relying on them, like the Angular app, to fair to build.

## Expected Behavior

The import statements should reference namespaces in other generated files.

## Actual Behavior

The import references are missing, causing the generated TypeScript classes to fail to compile when there are property types that rely on other classes from other namespaces.

## Possible Fix

Have the TypeScript code generator include import statements referencing the other generated namespaces.

## Steps to Reproduce

1. Create models with references to namespaces in other CTO files.
2. Run `composer generator create`.
3. Inspect/Try to compile the generated TypeScript.

## Existing issues

When asking about the issue in Rocket Chat it was [recommended to submit a GitHub Issue](https://chat.hyperledger.org/channel/composer?msg=hyCq33PwyZggsE6Y9).

## Context

I was trying to run the Angular app and it would not run without me manually adding in the import statements.

## Your Environment

* Version used: Composer v0.10.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node v6.11.1
* Operating System and version (desktop or mobile): Linux Mint 18.2
* Link to your project: https://github.com/ScottMorris/sampleBusinessNetwork

**Comment by alexsicart** [comment]
Hi @ScottMorris I've tried to follow your steps, and the `composer generator create` doesn't work, I've already installed the client.

**Comment by ScottMorris** [comment]
Hi @alexsicart, when you say it doesn't work what does it do?  Here are two sample files that spilt the type declarations across multiple files.

`org.acme.vehicle.auction.cto`
```
/**
 * Defines a data model for a blind vehicle auction - assets & transactions
 */
namespace org.acme.vehicle.auction
import org.acme.vehicle.auction.participant.*

asset Vehicle identified by vin {
  o String vin
  --> Member owner
}

enum ListingState {
  o FOR_SALE
  o RESERVE_NOT_MET
  o SOLD
}

asset VehicleListing identified by listingId {
  o String listingId
  o Double reservePrice
  o String description
  o ListingState state
  o Offer[] offers optional
  --> Vehicle vehicle
}

transaction Offer {
  o Double bidPrice
  --> VehicleListing listing
  --> Member member
}

transaction CloseBidding {
  --> VehicleListing listing
}
```

`org.acme.vehicle.auction.participant.cto`
```
/**
 * Defines a data model for a blind vehicle auction - participants
 */
namespace org.acme.vehicle.auction.participant

abstract participant User identified by email {
  o String email
  o String firstName
  o String lastName
}

participant Member extends User {
  o Double balance
}

participant Auctioneer extends User {
}
```
