### ISSUE TITLE
Images in playground do not display in Edge

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#1758]
Very simply when using the Edge browser, all the main images in the Playground render as black 

![image](https://user-images.githubusercontent.com/6673453/28963728-1826f0a8-7902-11e7-8dfa-0a2d42cb431d.png)

**Comment by alexsicart** [comment]
Hi @mbwhite I've tried to do the same as you in edge, and occurs the same. I'll try to make a pull request with the problem solved.

Cheers!

**Comment by sstone1** [comment]
P3 and no action in three months; clearly not important and never going to get fixed, so closing.
