### ISSUE TITLE
Failed to load connection profile hlfabric.

### ISSUE THREAD

**Issue by alexsicart** [hyperledger/composer#1759]
## Context

I was following the youtube tutorial(https://www.youtube.com/watch?v=fdFUsrsv5iw&t=1795s) to install with yo an Angular 2 Application, running Business Network with this identifier, org.acme.biznet (provided in the youtube example) and using this profile connection, hlfabric, gives me several errors. With the default options and following the data provided by the video. I think maybe is a bug. If it's not a bug, something wrong with my steps, I will change to stackoverflow.

## Expected Behavior
The expected behavior is the creation of an angular app with this network connection as in the example is showed.
## Actual Behavior
The actual Behavior is the returning of this specific error:

Error: Failed to load connection profile hlfabric. Error was Error: ENOENT: no such file or directory, open '/Users/unicorn/.composer-connection-profiles/hlfabric/connection.json'
    at fs.readFile.then.catch (/usr/local/lib/node_modules/generator-fabric-composer/node_modules/composer-common/lib/fsconnectionprofilestore.js:87:23)

## Possible Fix
I tried to install the Angular 2 app following the default steps or without connecting to a running business network and gives me error as well.

## Steps to Reproduce
 ➜   yo
? 'Allo Alex! What would you like to do? Fabric Composer
? Please select the type of Application: Angular2 Application
You can run this generator using: 'yo fabric-composer:angular'
Welcome to the Angular2 skeleton app generator
? Do you want to connect to a running Business Network? Yes
? What is the name of the application you wish to generate?: angular-app
? Description of the application: Skeleton Fabric Composer Angular2 project
? Author name: Alex Sicart Ramos
? Author email: alex@sharge.io
? What is the Business Network Identifier?: org.acme.biznet
? What is the Connection Profile to use? hlfabric
? Enrollment id: admin

## Your Environment
Mac 10.12.6
Node.js: 6.11.2
NPM:  5.3.0
Python: 2.7.10

**Comment by davidkel** [comment]
The video is quite old and things will have moved on a lot since then.
It would be worth you having a look at the tutorials on our web site to help get you started. 
see https://hyperledger.github.io/composer/

**Comment by alexsicart** [comment]
@davidkel Thank you very much :) So, ti would be good to eliminate the video from the getting started with building an app, for future contributors, no?
