### ISSUE TITLE
Playground tutorial is out of date following the addition of Historian

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1763]
The Addition of Historian has replaced the Default Transaction Registry, however in the online tutorials, it is still shown as (and referred to as) the old Default Transaction registry - not the default Historian registry. 

It would be super nice if these could match up.

## Context
When following a tutorial, the tutorial should match what the user is seeing

## Expected Behavior
Steps in tutorial match exactly the user experience

## Actual Behavior
"why do i see a default historian instead of the default transaction registry?"

## Possible Fix
Update turorial images and text

**Comment by alexsicart** [comment]
Hello @nklincoln I recommend you to follow this tutorials https://hyperledger.github.io/composer/tutorials they are already up to date, and cool. Keep in mind to have node 6.11.1, and not 8.2.1. :) I started yesterday, learning hyperledger with youtube videos no updated & it was frustrating. That tutorial is so cool. 

Cheers!!

**Comment by EdProsser** [comment]
This will be fixed in the update to tutorial today.
