### ISSUE TITLE
Need to understand how to stop and restart Composer REST server

### ISSUE THREAD

**Issue by LarissaAuberger** [hyperledger/composer#1768]
I noticed that  the command cat installers/hlfv1/install.sh | bash starts the  Composer REST server on port 3000.
I need to re-start the REST server using different parameters as specified in the install.sh, e.g. I want to enable security for the REST API.
Just restarting the composer using 
composer-rest-server -p hlfv1 -n org-acme-biznet -i PeerAdmin -s xxx -S true
leads to message

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at module.exports.promise.then.then (/home/ehtest/.nvm/versions/node/v6.11.0/lib/node_modules/composer-rest-server/cli.js:148:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)

... which is correct - port 3000 is already busy...

What would be the correct procedure?

## Expected Behavior
Need documentation on how to restart the REST server with desired parameters.

## Actual Behavior
REST server is started when install.sh is performed, but the parameters are not as desired

## Possible Fix
Documentation on the correct procedure

Thank you!
Larissa

**Comment by davidkel** [comment]
Do we document the -P option to change the port of the rest server ? We should probably provide a reference section for the rest server command line options in the same way we do the other CLI options.
We should also update the various screen captures etc to cover the new options when going through interactive mode.

**Comment by davidkel** [comment]
@LarissaAuberger To get help about composer rest server options you can do 
`composer-rest-server --help`

**Comment by LarissaAuberger** [comment]
David, thanks for your response.
composer-rest-server does not show options on how to stop the server... 

I killed the process on my Ubuntu and then performed composer-rest-server with the desired options. Is this the normal procedure?
Thanks!

**Comment by davidkel** [comment]
@LarissaAuberger That's the correct way to stop the rest server. I don't believe there is a need for it to perform any shutdown operations.

**Comment by hackneycrypto** [comment]
> David, thanks for your response.
> composer-rest-server does not show options on how to stop the server...
> 
> I killed the process on my Ubuntu and then performed composer-rest-server with the desired options. Is this the normal procedure?
> Thanks!

Hi - I need to to the same thing. I'm a newbie and not sure how you killed the process. I'm running Fabric via Docker containers. If I kill or delete the Docker container that is running the Fabric node then it does not stop/remove the REST server. It still runs on the port. Do you know how I kill this so I can run again with different settings on the same port? Thanks.
