### ISSUE TITLE
Web profile lets you add new ids even if not issuer

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#1770]
Using the web profile if i create a new identity "bob", without setting it as an issuer; then switch to it. i can then issue other identities even though "bob" shouldn't be allowed

**Comment by alexsicart** [comment]
Hi @caroline-church I'm trying to solve the problem, in which example is happening this problem? All the examples happens the same? I tried with tradeCommodity, and only let me create one name for identity.

Cheers :)

**Comment by caroline-church** [comment]
This is how to recreate

1. Ensure you are using the web profile with the basic-sample business network
2. Create a participant called `bob`
3. Issue an identity `userId: bob, participant:bob`
4 switch to using identity `bob`
5 issue an identity `userid bob2, participant bob`

step 5 should fail as bob is not an issuer
