### ISSUE TITLE
Developer tutorial is out of date following the addition of Historian

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1775]
Related to #1763 

Following the Historian addition, the aspects of the Developer tutorial (Import into Playground and Test section) that deal with Transactions need some updated images to reflect the UI changes that went in.

## Context
When following a tutorial, the tutorial should match what the user is seeing

## Expected Behavior
Steps in tutorial match exactly the user experience

## Actual Behavior
"why do i see a default historian instead of the default transaction registry?"

## Possible Fix
Update tutorial images (and text?) in relevant section

**Comment by mahoney1** [comment]
all in hand. Got the new screens sorted, will change in Dev Guide this week.
