### ISSUE TITLE
User is not enrolled after configuring github authentication and adding a blockchain identity to the default wallet and setting it as default

### ISSUE THREAD

**Issue by LarissaAuberger** [hyperledger/composer#1776]
I am setting up secure REST API using github authentication strategy.
I am using the provided vehicle-lifecycle-network.
After authentication the enrolled user can't use the REST API, this message is presented:
Error trying login and get user Context. Error: Error trying to enroll user. Error: Enrollment failed with errors [[{\"code\":400,\"message\":\"Authorization failure\"}]]

## Context
I followed these instructions in the Hyperledger Composer tutorial to enable REST API authentication:
https://hyperledger.github.io/composer/integrating/enabling-rest-authentication.html

1. Configuring REST Server to use github authentication strategy worked. I am redirected to github when I navigate to http://myhost:3000/auth/github and back after authentication. I authenticate using a dedicated user "cooluser2"
2. I added the blockchain identity called "cooluser2" to the default wallet.
Get /wallets/{id}/identities returns
[
  {
    "enrollmentID": "cooluser2",
    "enrollmentSecret": "xxxxxxxxxxxx",
    "id": 1
  }
]

Note: The identity is also part of my business network, I can list it using "composer identity list -p hlfv1 -n 'org-acme-biznet' -i admin -s adminpw"
List all identities in the business network org-acme-biznet
-
  $class:      org.hyperledger.composer.system.Identity
  identityId:  4688ac2e719e5d81407aec20f6d19a4ced113f8356f0a18689ed7cbad4b99d91
  name:        cooluser2
  issuer:      27c582d674ddf0f230854814b7cfd04553f3d0eac55e37d915386c614a5a1de9
  certificate:
    """
      -----BEGIN CERTIFICATE-----
***********
      -----END CERTIFICATE-----

    """
  state:       ACTIVATED
  participant: resource:org.acme.vehicle.lifecycle.manufacturer.Manufacturer#coolcars

3. I defined this blockchain identitiy as the default identity for the default wallet.

According to the tutorial REST API calls should succeed now.
But GET /system/ping (and other REST API operations) shows

{
  "error": {
    "statusCode": 500,
    "name": "Error",
    "message": "Error trying login and get user Context. Error: Error trying to enroll user. Error: Enrollment failed with errors [[{\"code\":400,\"message\":\"Authorization failure\"}]]",
    "stack": "Error: Error trying login and get user Context. Error: Error trying to enroll user. Error: Enrollment failed with errors [[{\"code\":400,\"message\":\"Authorization failure\"}]]\n    at client.getUserContext.then.then.catch (/home/ehtest/.nvm/versions/node/v6.11.2/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:292:34)\n    at process._tickCallback (internal/process/next_tick.js:109:7)"
  }
}

I assume that further configuration steps are required.

## Expected Behavior
User should be authorized 

## Actual Behavior
User is not yet authorized

## Possible Fix
May be the documentation is missing further required steps
Or configuration is not accepted yet (how can I check that the correct default user is used?)
May be the mapping between the user authenticated to github and the blockchain identitiy does not (yet) work?

## Steps to Reproduce
Follow the configuration steps in 
https://hyperledger.github.io/composer/integrating/enabling-rest-authentication.html
and see that user is not authenticated

## Your Environment
Ubuntu

composer --version

composer-cli                   v0.11.0
composer-admin                 v0.11.0
composer-client                v0.11.0
composer-common                v0.11.0
composer-runtime-hlf           v0.11.0
composer-runtime-hlfv1         v0.11.0

composer-rest-server --version
composer-rest-server           v0.11.0
composer-client                v0.11.0
composer-common                v0.11.0
composer-runtime-hlf           v0.11.0
composer-runtime-hlfv1         v0.11.0

**Comment by davidkel** [comment]
I'm not able to recreate this. It works for me and the only way I can see that this would not work is if the secret entered was not correct.
You can look in the CA logs to see what the problem might be, for example
`docker logs ca.org1.example.com` 
Here is an example where I explicitly got the secret wrong which produces the same error as described here
```
2017/08/08 06:04:41 [DEBUG] Received request
POST /api/v1/enroll
Authorization: Basic SmFja0RhbmllbHM6VVJCR21qSmxtTkVU
{"caName":"ca.org1.example.com","certificate_request":"-----BEGIN CERTIFICATE REQUEST-----\r\nMIHTMHgCAQAwFjEUMBIGA1UEAwwLSmFja0RhbmllbHMwWTATBgcqhkjOPQIBBggq\r\nhkjOPQMBBwNCAAQCFhukaRherM+iV7Fm0pHHNvHXPcs6kORP8wepZQMHPE96kwNu\r\ngWP+dgDqwiz2z4NS/2ZTBcyPuWvtuklTbTZyoAAwDAYIKoZIzj0EAwIFAANJADBG\r\nAiEAoifxnIVvvsAq9M25PiL0ugrd9So8OasfI9qadbtXHcUCIQCmjC5pOvM1SotN\r\nCRnkbAWAAJOmuHeiqwOUrPBmNNsa9g==\r\n-----END CERTIFICATE REQUEST-----\r\n"}
2017/08/08 06:04:41 [DEBUG] Directing traffic to CA ca.org1.example.com
2017/08/08 06:04:41 [DEBUG] DB: Getting identity JackDaniels
2017/08/08 06:04:41 [DEBUG] DB: Login user JackDaniels with max enrollments of -1 and state of 0
2017/08/08 06:04:41 [DEBUG] Failed to login 'JackDaniels': Password mismatch: crypto/bcrypt: hashedPassword is not the hash of the given password
```

**Comment by LarissaAuberger** [comment]
Hi Dave, thanks for your helpful comment. Indeed, this is what I see in the log ("Password mismatch: crypto/bcrypt: hashedPassword is not the hash of the given password").
The user already has been enrolled when I tested the connection to the business network via
composer network ping -p hlfv1 -n 'org-acme-biznet' -i cooluser2 -s KmsoppxkvSVN

Therefore, in Post /wallets/{id}/identities  I specified the user and user's certificate that I see when I list identities for my business network.
Please confirm that using this certificate as enrollmentSecret is correct.
Thanks!
Larissa

**Comment by davidkel** [comment]
For the Post of /wallets/{id}/identities you should specify the user and the user's secret. The rest server will use that information to request the certificates and store them in your wallet managed by the rest server. The rest server will use those certificates to interact with the fabric and business network.

**Comment by sstone1** [comment]
> Please confirm that using this certificate as enrollmentSecret is correct.
This is not correct. It needs to be the enrolment secret.
The REST server does not yet support importing an existing certificate into the wallet.

**Comment by LarissaAuberger** [comment]
I tried both - the enrollment secret and the certificate and both don't work.

**Comment by davidkel** [comment]
@LarissaAuberger It has to be the enrollment secret that is provided when you issue the identity. The list shows that the identity has been activated, so it looks like it was enrolled at some point and certificates were downloaded. There was a bug in the rest server where it would lose the ability to find the certificates and attempt to re-enroll the user but the re-enroll attempt to work and new certifcates would be obtained but then because the user is activated with different certificates you would get an error saying the user was not registered. 
Could you try moving to 0.11.3 which has a fix for this problem in the rest server and see if the problem still exists ?

**Comment by zupan** [comment]
@davidkel I am facing the same exact problem. I just updated all dependencies from 0.10.1 to 0.11.3 and I cannot query from my application nor directly from REST server.
` composer-rest-server --version` and `composer --version` are both showing 0.11.3 for all packages.

When looking at the logs from CA I can see that my identity was successfully logged in.

**Comment by markcastle3** [comment]
Since we haven't heard anything we will close this, please reopen if you still see this issue ?

**Comment by majestade** [comment]
i have the same issue... did you solve the problem @LarissaAuberger ?

**Comment by MrTaiji** [comment]
Same problem as @majestade here, but only with non-Admin ID cards.
Has probably something to do with the access control, but I am not sure how and why because all functions I am trying to execute via REST inteface are working without problems in the Playground with regular User ID Cards.
