### ISSUE TITLE
A user with multiple IDs should be able to see which can be used to issue other IDs

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1777]
Capturing a little hangover from #817 

We need to make sure that as we work on ID cards, we still give the user information about which IDs they can use to issue other IDs (assigning to design first to check we have a solution for this in the designs, then will update and hand over to Caroline for dev assignment!).

**Comment by sstone1** [comment]
Such dupe, much close:
IDs screen should indicate which IDs can issue other IDs #1321
