### ISSUE TITLE
Revoking an ID not in My Wallet offers Remove option too - error, infinite loading spinner, UI panel until re-load

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1778]
**Recreate Steps:**

1. Import any sample network (the Basic Sample will do)
2. Head to the Test tab and create a Participant
3. Head to the IDs tab, and make sure you're admin (not PeerAdmin) so that you can issue IDs
4. Issue a new ID to the Participant you created
5. Do not put that ID in your wallet
6. Click the "Revoke" button on that ID

![image](https://user-images.githubusercontent.com/7454304/29026998-833c1ed8-7b76-11e7-9a3c-ae6f57717e61.png)

**Expected Result:**

ID is Revoked, success message, ID shows as Revoked on the ID Page.

**Actual Result:**

User is asked if they want to Remove the ID from their Wallet (even though it isn't in there):
![image](https://user-images.githubusercontent.com/7454304/29027061-d977d6b6-7b76-11e7-8608-9851bbc51096.png)

Clicking Remove on this dialogue creates some further issues:
![image](https://user-images.githubusercontent.com/7454304/29027076-e8d59a6c-7b76-11e7-9e82-20d5aebdf375.png)
(Fair enough: it's not there after all)

![image](https://user-images.githubusercontent.com/7454304/29027083-f5bfb80c-7b76-11e7-9da3-501d1204f0c6.png)
(A spinner that will never go away, as this action will never complete)

Hit refresh to get somewhere and...
![image](https://user-images.githubusercontent.com/7454304/29027097-09df6800-7b77-11e7-832c-35a3f2534197.png)
(All my IDs are gone!!)

Heading back to the root URL (just localhost:8080) fixes the issue

**Comment by davidkel** [comment]
I noticed that I had created 2 participants. When I did this, one of them got revoked and the other got deleted by the looks of things.

**Comment by caroline-church** [comment]
Fixed so closing
