### ISSUE TITLE
There are no docs to describe events and the rest server

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#1788]
When i generate a rest server it asks if i want to enable event publication over WebSockets. There is no information in the docs that describe how to do this

**Comment by caroline-church** [comment]
I worked out how to do this. Was actually quite simple but i didn't immediately know

This is some sample javascript that i used to make it work

```
const WebSocket = require('ws');

const ws = new WebSocket('http://localhost:3000');

ws.on('message', function incoming(data) {
  console.log(data);
});
```

**Comment by sstone1** [comment]
This has been delivered.
