### ISSUE TITLE
Wrong link in "Integrating Existing Systems" Doc

### ISSUE THREAD

**Issue by rthatcher** [hyperledger/composer#1789]
This Doc: 
  https://hyperledger.github.io/composer/integrating/integrating-index.html

The link under "Securing the REST server using HTTPS and TLS"  is wrong:
  ( https://hyperledger.github.io/composer/integrating/enabling-rest-authentication.html )
I think it should be:
  https://hyperledger.github.io/composer/integrating/securing-the-rest-server.html

**Comment by harrika1982** [comment]
@EdProsser -- can you assign to me?
