### ISSUE TITLE
Documentation nitpicks

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#1798]
A selection of documentation niggles following recent release validations:

- [x] There are no scroll bars for the main content, or the navigation (OSX/Safari). This is more noticeable on longer pages, such as the [query tutorial](https://hyperledger.github.io/composer/tutorials/queries.html) **Sam** (See #2168)

- [x] The [Installing and running Hyperledger Composer Playground locally](https://hyperledger.github.io/composer/installing/using-playground-locally.html) page has some confusing (unnecessary?) content from 'Deploying business networks to Hyperledger Fabric v1.0' onward. It seems like this can be safely ignored when using the script shown just above. (There probably needs to be a separate page for that content somewhere, possibly in the reference or maybe as part of a more manual install process? Not sure.

- [x] The diagram on [Installing and developing with Hyperledger Composer](https://hyperledger.github.io/composer/installing/development-tools.html) should be redone to "look all pretty and stuff"

- [x] [Installing and developing with Hyperledger Composer](https://hyperledger.github.io/composer/installing/development-tools.html) prereqs are shown as a code block with copy button

- [x] [Installing and developing with Hyperledger Composer](https://hyperledger.github.io/composer/installing/development-tools.html) has prereqs which include operating system, however there is nothing similar on the [Installing and running Hyperledger Composer Playground locally](https://hyperledger.github.io/composer/installing/using-playground-locally.html) which could result in people trying a local install on Windows (at least I assume that this still won't work)

- [x] [Tutorials landing page](https://hyperledger.github.io/composer/tutorials/tutorials.html) only mentions the first two tutorials, not the query one. (Do we need to update that page's design to allow for more tutorials in future?)

- [x] If there are multiple "Related Links" at the bottom of a page, they all appear on one line, so look sort of like just one long link

- [x] Diagram on the [Business Network Definition](https://hyperledger.github.io/composer/business-network/businessnetworkdefinition.html) page needs updating to include query files

- [x] The system model on [Hyperledger Composer Modeling Language](https://hyperledger.github.io/composer/reference/cto_language.html) is out of date

- [x] The BasicEvent definition on the [Emitting Events](https://hyperledger.github.io/composer/business-network/publishing-events.html) page still includes `identified by` which should not be necessary now that Events are defined in the system model

- [x] The [documentation](https://hyperledger.github.io/composer/reference/composer.network.undeploy.html) for the CLI command `composer network undeploy` does not match the command, it should be:
![image](https://user-images.githubusercontent.com/8394544/29082639-0395b05c-7c5e-11e7-9f21-adfee229a008.png)

- [x] The [Hyperledger Composer Archive Create](https://hyperledger.github.io/composer/reference/composer.archive.create.html) command documentation is out of date. It should be:
```
composer archive create --archiveFile digitialPropertyNetwork.zip --sourceType module --sourceName digitalproperty-network

Options:
  --help             Show help  [boolean]
  -v, --version      Show version number  [boolean]
  --archiveFile, -a  Business network archive file name. Default is based on the Identifier of the BusinessNetwork  [string]
  --sourceType, -t   The type of the input containg the files used to create the archive [ module | dir ]  [required]
  --sourceName, -n   The Location to create the archive from e.g. NPM module directory or Name of the npm module to use  [required]
```

- [x] The [Querying business network data](https://hyperledger.github.io/composer/business-network/query.html) page links to the API documentation landing page for information on how to use queries however it would be nicer to directly link to the relevant APIs directly.

- [x] The [Hyperledger Composer Query Language](https://hyperledger.github.io/composer/reference/query-language.html) reference page currently seems a bit thin

- ~~The [Transaction Processor Functions](https://hyperledger.github.io/composer/reference/js_scripts.html) reference page is also very thin on detail.  It uses the "mozart" model, which is odd, and the example transactions really do nothing much, so aren't super illustrative!~~ Opened #1862 to track this larger piece of work.

**Comment by jt-nti** [comment]
cc: @EdProsser @EdMoffatt

**Comment by mqmatt** [comment]
Particularly agree with point two above... the “Deploying business networks to Hyperledger Fabric v1.0” section of the Playground install page is frankly horrible. It talks about a whole bunch of concepts that have not been introduced and that the user may not be familiar when trying to install Playground: identities, admin users, “crypto material”, keyValStore directories, the composer command, secrets, certificates, peers, common names are not explained at all - and I don’t think we should be at this stage (the user is trying to install Playground).

I think that this whole section could be moved elsewhere (e.g. Developing Business Networks) without losing anything important. Alternatively, the section could be replaced with something like “The Playground will only work in simulation mode in the browser or against an instance of Hyperledger Fabric V1.0. When running against Hyperledger Fabric V1.0 there are some additional considerations around userids and passwords. Please see [new topic] for more details."

**Comment by davidkel** [comment]
As it contains the issue about missing scroll bars on our website for example in the tutorials and people have been contacting me to mention this as being a problem for them.

**Comment by EdProsser** [comment]
We still reference 'Log Out' in the playground tutorial.
Also the My Wallet screen name is now My Business networks.

**Comment by davidkel** [comment]
Have extracted out the ACL documentation into another issue as it is more than a nitpick now given it's expanded capabilities see #2373
