### ISSUE TITLE
Composer Archive List CLI command fails if not given correct args

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1800]
Running `composer archive list`  without specifying any arguments results in the output of an error message instead of anything useful.

## Expected Behavior
Would hope that the item you are trying to list was at least required, or fail gracefully if nothing is specified

## Actual Behavior
Search is performed on `undefined` and results in failure

![image](https://user-images.githubusercontent.com/8394544/29082290-fac34986-7c5c-11e7-88cc-645974faaf18.png)

## Possible Fix
sanitize input

## Steps to Reproduce
1. run `composer archive list`
2. observe

## Your Environment
* Version used: v0.11.1
* Operating System and version (desktop or mobile): linux

**Comment by sstone1** [comment]
Fix has been delivered.
