### ISSUE TITLE
Composer NetworkList -r flag only works on Assets

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1804]
The -r flag is documented to enable restriction of the listing to *any* registry, but seemingly only supports the Asset registry

## Context
`composer network list -n <x> -p <x> -i <x> -s <x>` will return a list of various registries defined, and the docs indicate that a `-r <registry>` will restrict the list to only that registry.

By working with a deployed basic-sample-network it is possible to restrict via `-r org.acme.sample.SampleAsset`, but not the Participant registry via `org.acme.sample.SampleParticipant`

![image](https://user-images.githubusercontent.com/8394544/29083308-367c81ce-7c60-11e7-8f27-ad0f6680cce0.png)

This would indicate that it is only actually possible to restrict based upon Assets, in which case this requires documentation, or there is an error in the code preventing the intended code action.

## Expected Behavior
Either documentation tells user to only restrict on Assets or the command works

## Actual Behavior
as image above

## Steps to Reproduce
1. run indicated command on a deployed basic sample network

## Your Environment

* Version used: v 0.11.1
* Operating System and version (desktop or mobile): linux

**Comment by mbwhite** [comment]
as just discussed with Caroline... any registry (inc system) should be able to be read via this option. (subject to the ACLs letting you of course!)

**Comment by caroline-church** [comment]
done so closing
