### ISSUE TITLE
Composer identity issue fails for participant ids containing colons

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1805]
If running a `composer identity issue` command, to issue an identity to an existing participant, the command will fail if the participant id contains a colon, with the return error message complaining about not being able to find the namespace.

## Context
trying to issue an identity to a default generated participant id, issue correct command, error returned instead of success.

## Expected Behavior
Identity is issued

## Actual Behavior
![image](https://user-images.githubusercontent.com/8394544/29083698-7a6f16fc-7c61-11e7-8660-9f0ab6c7a058.png)

## Steps to Reproduce
1. Deploy basic sample network
2. Create participants that have a colon in their identifier
3. Try to issue an identity

## Your Environment
* Version used: v0.11.1
* Operating System and version (desktop or mobile): Linux desktop

**Comment by bestbeforetoday** [comment]
Fails using the "legacy" resource URI format, e.g. `org.acme.sample.SampleParticipant#participantId:111`. Works using the fully qualified URI format, e.g. `resource:org.acme.sample.SampleParticipant#participantId:111`.

Since we explicitly try to support the legacy format, we should probably do this correctly. The alternative (which is worth thinking about) is to explicitly disallow the legacy format.

**Comment by sstone1** [comment]
@nklincoln @bestbeforetoday resource URIs are standard URIs and follow the rules set forth by the internet gods in RFC 3986.

https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax

> Strings of data octets within a URI are represented as characters. Permitted characters within a URI are the ASCII characters for the lowercase and uppercase letters of the modern English alphabet, the Arabic numerals, hyphen, period, underscore, and tilde.[11] **Octets represented by any other character must be percent-encoded.**

So, the correct format is: `resource:org.acme.sample.SampleParticipant#participantId%3A111`

Any fixes done as part of this issue should be to make the URI parsing code stricter and more compliant with the URI specification.

**Comment by sstone1** [comment]
Missed the colon in the spec, sorry - but the point still stands for other characters.
Agree on the command line, but the code for handling that should be restricted to the command line only, and it should convert invalid URIs into valid URIs. You should not be able to store invalid URIs on the Blockchain.

**Comment by bestbeforetoday** [comment]
@sstone1 Does `encodeURI(this.id)` not ensure that the URIs we generate encode any unsafe characters in the fragment portion?
