### ISSUE TITLE
Selecting 'Optional properties' overwrites any fields I have entered values for.

### ISSUE THREAD

**Issue by mqmatt** [hyperledger/composer#1816]
## Context
Creating a new participant or asset or transaction in Playground 0.11.2. Selecting or deselecting the ‘Optional Properties’ checkbox overwrites any fields I have already entered values for.

## Expected Behavior
When selecting 'Optional Properties' I would expect the JSON data structure to be augmented with the optional fields, and all other fields left alone.
I would expect the optional fields to be removed when I deselect the box (even if I have changed them), and all other fields left alone.

## Actual Behavior
All fields are reset to default/test values.

## Your Environment
* Version used: Playground 0.11.2.
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox

**Comment by bestbeforetoday** [comment]
The behaviour is as-designed, even if it isn't ideal and introduces confusion, so I don't think this is really a bug despite still being important.

# Background

When the dialog first loads, it is populated with "empty" data, which is mostly empty strings, zeros etc. Clicking Generate Random Data populates the dialog with "sample" data.

The idea is that:
- If the Optional Properties checkbox is un-ticked, only mandatory (non-optional) properties are generated.
- If the Optional Properties checkbox is ticked, all properties are generated.

The default is un-ticked. Changing the state of the Optional Properties checkbox triggers a re-generation of "empty" data. Any data generation overwrites the entire content of the dialog. It is the combination of these two behaviours that causes the confusion.

"I un/tick the Optional Properties checkbox and the only thing I see is my participantId change."
"I un/tick the Optional Properties checkbox and it's wiped out the data I typed in."

# Possible solutions

Some ideas for solutions, some of which are probably significantly less great that others.
1. The state of the Optional Properties checkbox only affects the behaviour of the Generate Random Data link. State changes of the checkbox do nothing.
2. Ticking the Optional Properties checkbox adds any missing optional properties, using "empty" values; existing property values are left unchanged. Unticking the checkbox has no immediate effect.
3. (Similar to 2)  Ticking the Optional Properties checkbox adds any missing optional properties, using "empty" values; existing property values are left unchanged. Unticking the checkbox removes any optional properties that have been defined.

**Comment by awjh-ibm** [comment]
Was a decision reached for this bug? If so I will work on a solution.

**Comment by EdMoffatt** [comment]
Adding back the bug tag (sorry, Mark!) because we're using "P2 + Bug" to look for the top priority items at the moment, and this one should be on that list.  (Will give some design feedback on the proposed solution shortly too!)

**Comment by EdMoffatt** [comment]
Solution (3) in Mark's suggestions above sounds like the closest to what the issue is asking for.  It also seems the most useful based on observations of people trying to work with this functionality, so agree we should go ahead with that one.
