### ISSUE TITLE
Historian displays '<system>' instead of 'admin'.

### ISSUE THREAD

**Issue by mqmatt** [hyperledger/composer#1817]
## Context
After issuing transactions on behalf of the admin user, they are displayed in the Historian's Participant ID field as '\<system\>'.

## Expected Behavior
I would expect that the 'admin' user is listed explicitly.

## Actual Behavior
The Historian shows '\<system\>'.

## Your Environment
* Version used: Playground 0.11.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox

**Comment by neeravarora** [comment]
@caroline-church @m-g-k  please assign this issue to me .

**Comment by caroline-church** [comment]
This is fixed by https://github.com/hyperledger/composer/pull/1867
