### ISSUE TITLE
Ordering and Naming of columns in Historian is confusing

### ISSUE THREAD

**Issue by mqmatt** [hyperledger/composer#1818]
## Context
Ordering and naming of columns in the Playground Historian registry is a little confusing. “ID” should be called “Transaction ID” to distinguish from “Participant ID”. I also suggest reordering the columns so that the most important information is first (suggest Timestamp).
Particularly, I’m not sure what the relevance of transaction ID is in this view. I would move it after ‘Transaction Type” or remove it entirely.

## Expected Behavior
1) "ID" is renamed "Transaction ID"
2) "Transaction ID" is removed or moved further to the right.

## Your Environment

* Version used: Playground 0.11.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox

**Comment by sstone1** [comment]
Merging with #1895 as part of a general "lets redesign the historian UI based on feedback" item.
