### ISSUE TITLE
Typing required before I can select participant when issuing identity

### ISSUE THREAD

**Issue by mqmatt** [hyperledger/composer#1820]
## Context
When issuing a new identity in Playground 0.11.2 in Firefox, I have to start typing the Participant’s name (or a character from the name) before a drop down box appears. It would be useful to list the available participants without having to type anything.

## Expected Behavior
The 'Participant' field can be populated entirely by mouse clicks.

## Actual Behavior
I have to type a subset of the participant's name before I can select it.

## Possible Fix
Allow a click in the text field to produce a drop down list of available participants; alternatively, provide a button to the side which lists the participants.

## Steps to Reproduce
1. In playground click 'Issue new ID'
2. Click the 'Participant*' text field
3. I can't see which participants are available in the registry until I start typing.

## Your Environment
* Version used: Playground 0.11.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox

**Comment by jt-nti** [comment]
Item two on #649 would address this issue

**Comment by jt-nti** [comment]
Related comment from @rthatcher 

>When Issuing a new Identity from the ID Registry the type-ahead for the Participant seems to match on the fully qualified name of the participant e.g. resource:org.acme.vehicle.lifecycle.PrivateOwner#anna. I think the match includes the whole namespace AND the word 'resource:'. When the field is complete you can remove 'resource:' from the front and the ID is still issued OK.

**Comment by caroline-church** [comment]
The problem with showing participants when you just click is what if you had lots and lots of them, this would cause problems. If you limited the number you returned you would get the problem that people would expect to see the one they wanted in the list and if it was towards the end of the alphabet it wouldn't be there. For this reason closing, feel free to open it again if you can think of a solution that would address this problem
