### ISSUE TITLE
Intermittent Travis Build failure

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1824]
Travis is proving unreliable with the builds, is this an issue with Travis, the way we have structured our project, and result of varying dependencies, or something else?

We really need to investigate the build reliability so that we don't continue to waste time down the line trying to convince Travis to build the project.

## Context
Builds fail for no apparent or repeatable reason. 

## Expected Behavior
The build gods to be forever in our favour.

## Actual Behavior
"Why you fail build, why?"

## Context
Trying to look for a green build. 

### Suggestions
- building of the docker images only check to see if playground npm module available, it should also check that composer-cli and composer-rest-server npm modules are available as we have seen docker build failures due to not being able to get an npm module

**Comment by sstone1** [comment]
Closing as there's no actionable items here, or logs to diagnose the problems.
