### ISSUE TITLE
Can't import new BNA into Playground when running as limited user

### ISSUE THREAD

**Issue by mqmatt** [hyperledger/composer#1827]
## Context
In Playground (0.11.2) If I'm running under the context of a user with limited rights, I'm not able to replace the contents of my workspace with a new BNA file.
I am running in simulation mode, so not against a real Fabric instance.

The error I get is:
`t: Participant 'org.acme.vehicle.auction.Member#matt' does not have 'READ' access to resource 'org.hyperledger.composer.system.AssetRegistry#org.hyperledger.composer.system.Identity'`

## Expected Behavior
I would expect to be always able to start anew and import a new project.

## Steps to Reproduce
1. Import and deploy (say) Car Auction
2. Issue a new identity no admin rights
3. Switch to that user's context
4. Try importing a new sample - error is produced

## Your Environment
* Version used: Playground 0.11.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox

**Comment by sstone1** [comment]
Bouncing to @EdMoffatt as this is looks like more of a general "if I screw up my business network, how do I recover" scenario we should cater for in the playground.
