### ISSUE TITLE
Dev Tutorial requires ACL update

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1829]
Dev tutorial specifies an ACL rule set that is missing the required system acl rules, and there is a corrupt image file in there.

Would be best to fix them at the same time :small_airplane: 

## Context
Dev guide cucumber tests should pass, and images should render

## Actual Behavior
Cucumber tests fail, but pass when the acl rules are updated to include system rules

## Possible Fix
Edit!

## Steps to Reproduce
Follow dev guide

**Comment by mahoney1** [comment]
completed - added System ACLs, replaced corrupt img file (one each for dev and query)
