### ISSUE TITLE
The 'Deploying and Updating Business Networks' document only covers Deploying

### ISSUE THREAD

**Issue by rthatcher** [hyperledger/composer#1834]
This doc:
https://hyperledger.github.io/composer/business-network/bnd-deploy.html
entitled '**Deploying and Updating Business Networks**'
Does not mention/reference the composer network update command. (only deploy)

Also are we now recommending, composer runtime install and composer network start instead of deploy?

**Comment by davidkel** [comment]
It looks like the deploy page has been updated and also there is now a section on upgrading a deployed business network so I think we can close this issue.
