### ISSUE TITLE
Various updates to Developer Tutorial needed

### ISSUE THREAD

**Issue by mqmatt** [hyperledger/composer#1836]
## Context
I found various documentation problems against the Developer Guide Tutorial (https://hyperledger.github.io/composer/tutorials/developer-guide.html) when run against Composer 0.11.2, due mainly to recent updates.
The headings below refer to sections in the documentation. 

**“Update your package.json file"**
- [ ] Instructions are not as clear as they could be, for example: "(Note: Add a timeout to the "test" command line and remove the 'deploy' line after 'test' - as we will not be publishing this network to the npm package manager).” takes a lot of parsing. People are likely to fall over this.
My “test” parameter is “npm run test-inner”. Do I need to change it to "mocha --recursive -t 4000” as shown in the screengrab or not? This isn’t made clear in the text.
Either you need to explain what mocha, nyc, npm, “test”, “test-inner”, “test-cover” etc. will actually do - or be completely explicit in the instructions about what the user needs to change in the JSON - stuff like "Change x to y”. At this stage, I suggest the latter.
- [ ] Also, the Copy button here isn’t particularly useful as it will also copy the ellipsis at the end.

**“Generate the business network archive"**
- [ ] Replace "You should see the following output:” with “Among the output you should see the following:” :o)

**“Import into playground and test"**
- [ ] First sentence. If you’ve followed the instructions you’ll already be in the top level folder. Suggest changing "Change directory to your toplevel project folder (my-network)” to “Ensure that you are in the top level project folder (my-network)”.
- [ ] New screenshots needed to show Historian

**“Deploy to running Hyperledger Fabric"**
- [ ] The output of network ping needs to be updated to show latest Composer version

**“Generate REST API"**
- [ ] Not all questions have suggested answers: (1) Need to tell the user whether to enable event publication over web sockets or not. (2) Need to tell the user whether to enable TLS or not.
[ ] I suggest also putting the suggested answers inside the text as well as the screenshot, in case the screenshot does not render correctly.

**“Test REST API"**
- [ ] Move the POST /Trader screenshot down slightly, so that it appears *after* the instruction to press “Try it Out”. Currently it’s displayed too soon.

**"Generate your Skeleton Web Application"**
- [ ] Again, put suggested answers in the text as well as the screenshot in case the screenshot does not render correctly.
- [ ] Also, needs a suggested answer for the License question.
- [ ] Remove the bit about the home directory: "my-app" is not necessarily created in the home directory. When I ran it, it was placed inside the current directory (my-network/my-app). The suggested command (cd my-app) works OK though.

(By the way, when I ran the npm start command I did get the error
```
Error: Error trying to ping. Error: Composer runtime (0.11.2-20170809083654) is not compatible with client (0.11.1)
[1]     at _checkRuntimeVersions.then.catch (/Users/mpl/dev/composer-latest/my-network/my-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:696:34)
```
which may well be something out of step on my part, because of running on unstable. The app was generated successfully and started OK however.)

**Comment by mahoney1** [comment]
hi Matt, thanks firstly for the feedback. I think you may not have been sent/used the link to the 'unstable' doc (rather than stable - ie your link above) for Thurs QA testing -  normally its 'unstable' https://hyperledger.github.io/composer/unstable/tutorials/developer-guide.html  (which itself has been since been automatically today (with changes) - ie the 'docs build' process updates the 'unstable' branch in github. Anyway, Rob T or myself will take your comments and apply them to the current edition, thanks for that.

**Comment by EdProsser** [comment]
@mahoney1 I'm gonna assume that this is done, because the PR referenced it?

**Comment by mahoney1** [comment]
yes @EdProsser this is done, will close now.
