### ISSUE TITLE
Provide documentation for CLI command identity request

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1854]
Not enough time to get the documentation in for this command, so we should get it documented when we can.

```
composer identity request [options]

Options:
  --help                       Show help  [boolean]
  -v, --version                Show version number  [boolean]
  --connectionProfileName, -p  The connection profile name  [string] [required]
  --enrollId, -i               The enrollment ID of the user  [string] [required]
  --enrollSecret, -s           The enrollment secret of the user  [string]
  --path, -d                   path where to store the certificates and key  [string]
```
Please also feel free to recommend better help text on --path option. It's not very good.

**Comment by davidkel** [comment]
see #1927 as to whether we will make this command official or will drop it.

**Comment by davidkel** [comment]
Closing as we won't document this command.

**Comment by erNail** [comment]
Since the command is used in the new tutorial [Deploying to a multi-organization Hyperledger Fabric](https://hyperledger.github.io/composer/tutorials/deploy-to-fabric-multi-org.html), it might be worth documenting it.

**Comment by davidkel** [comment]
The plan is to drop this command when fabric release binary images of fabric-ca-client and the tutorial will be updated accordingly. Since the move to cards this command is also not practical to replace the original intention changing what used to be a single command into 4 commands.
