### ISSUE TITLE
Historian system test debt

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#1857]
Historian snuck in with no system tests. Well, pointless system tests that don't do anything.

As per my comments in #55, I have no idea how this was allowed in. The system tests should have been completed before the feature was merged. This test debt needs resolving ASAP. 

https://github.com/hyperledger/composer/blob/master/packages/composer-systests/systest/historian.js

**Comment by mbwhite** [comment]
Leaving #55 open - the above changes will be going in as part of ... https://github.com/hyperledger/composer/pull/2026
