### ISSUE TITLE
Agree Revised Playground Navigation Structure

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1860]
As we've added more functionality to Playground (yay!), our existing navigation designs are starting to stretch at the seams a little (boo!).  So, we should revisit this.  A few of the things we know are a little "janky" at the moment...

1. DEFINE tab left-hand navigation.  This does not scale very well to lots of files - what can we do here to facilitate working with a lot of files in a business network definition?

2. TEST tab left-hand navigation.  Again, when models were only Assets, Participants and Transactions, the headings here worked well.  Now though, we have "Transactions" as a heading for just the "Historian" - which is where you go to see your Events and Transactions.  Do we need to re-name things here?  Do Queries need to surface anywhere?  What about a section for them?  All these things and more, to be discussed.

3. IDs section.  Is it still sensible for it to live up in the top left to get there?  Or with the ID Cards screen, should that just be where you log out?  And then where do you go to do admin on IDs?

There may be other things we want to look at here too.  Might be a good idea to kick this one off with a workshop session??

**Comment by sstone1** [comment]
As far as I know, nobody is working on this at the moment or planning to work on it, so closing. 
If somebody wishes to work on this in the future, then please reopen this issue or open a new issue.
