### ISSUE TITLE
As a user, I have tutorials that show me how to work with existing Hyperledger Fabric instances

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1866]
When the 1-click install was created it was before the new fabric security model. 
Support was added to work with the new level of fabric but there wasn't a way to get the Peer Credentials into Playground so a temporary fix was done such that the fabric-dev-server shipped with pre-imported credentials which are then copied to the credentials folder and playground was configured to know these were present.
This was a temporary solution until we had playground support.

This issue is to cover the discussion on whether we should leave this in. 2 competing arguments are
- Leave them in because it makes it easy for people
- Take it out because it is hiding a necessary part of using playground in the real world.

From the many questions from users it seems that the understanding around how fabric security works and how composer handles that is not clear. One of the contributors to this is that composer does hide things to make it easier but then it leads people down the wrong path of understanding.

I think this is something we need to discuss which is the best way forward and to address the impact doing either way has through alternative means, such as documentation and examples

**Comment by sstone1** [comment]
A 1-click install that does not automatically wire together the things being installed is not user friendly in the slightest. Bear in mind that a lot of users who running the 1-click install will be first time users with minimal Composer and Fabric experience, and making the first step "go and hunt for random PEM files on your disk" is not going to help them learn.

However, we do need much better documentation, perhaps in tutorial format, around connecting the Composer tools to an existing Fabric instance. Currently the tutorials that we have walk through:
- Working in the cloud playground (simulated Fabric)
- Using playground locally (precanned Fabric)
- Configuring a developer environment (precanned Fabric)
We really need another tutorial that guides you through through the steps of deploying a realistic network:
- Building a Fabric network (this is really just a link to the Fabric documentation)
- Connecting Composer Playground & CLIs etc. to the Fabric network, by building connection profiles or business network cards, grabbing the right certs, etc.
- Deploying a Composer business network to a multi-org Fabric network, with all the different install & instantiate steps required to do that, along with endorsement policies.

**Comment by sstone1** [comment]
I think we have enough in this space now.
