### ISSUE TITLE
generate random data can produce undesirable words

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#1869]
Sometimes when generating random data for assets, participants, and transactions the result can include words that aren't desirable. This should be fixed to stop this happening

**Comment by jt-nti** [comment]
Is this just a theoretical problem, or has someone reported which undesirable words should be excluded? I had an, admittedly very quick, skim through the words and they seem ok to me, although I could certainly imagine combinations could be potentially problematic. Not sure how that could be avoided. Train Watson to reject undesirable random text?!
A more serious possibility would be to stop using a dictionary of English words. Maybe something like https://www.npmjs.com/package/lorem-ipsum instead?

**Comment by caroline-church** [comment]
No a certain combination occurred that we wouldn't want. Yes using Lorem
ipsum would probs be better
