### ISSUE TITLE
The favicon doesn't show in firefox

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#1876]
In firefox the favicon appears as the angular logo instead of the conga blocks

**Comment by Jakeeyturner** [comment]
Just tested with Firefox 55.0.3 and it seems to show fine. I expect the favicon hasn't been updated because of the browser cache.
![firefox](https://user-images.githubusercontent.com/10009752/30649483-4c001306-9e18-11e7-9c6b-db21530a8880.PNG)

**Comment by sstone1** [comment]
Works for me!
