### ISSUE TITLE
Web Playground must handle ID Card import

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1885]
This came up during discussion today.

Web Playground can only be used with the "Web Browser" connection profile.  Previously we made sure of this by replacing the part of the UI you can click on to switch them.

Now though, ID Cards are the things that dictate what you connect to.  Therefore, potentially a user can import an ID Card e.g. for a local Fabric runtime on their laptop, into the Web Playground.

We need to handle this.  Somehow XD  Assigning to Sam and Caroline to start with, to figure out how we should handle it!

**Comment by caroline-church** [comment]
Think we should remove import id card we could also probably remove create id card. The only problem you would have might be that you would have the same local-storage so we would need to hide id cards that weren't for web profile
