### ISSUE TITLE
Playground 'community' link: page not found

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#1893]
The _Community_ link in the bottom-right of the Playground UI links to [https://hyperledger.github.io/composer/support/index.html](https://hyperledger.github.io/composer/support/index.html). I get page not found for this link.

Playground v0.11.3 on Bluemix.
Using Safari on Mac.

**Comment by neeravarora** [comment]
@bestbeforetoday Community link is actually pointing to https://hyperledger.github.io/composer/support/support-index.html.

**Comment by sstone1** [comment]
Broken for me on latest public playground.
