### ISSUE TITLE
Docs Link Checker Does Not Fail Build When Detecting Broken Links

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1897]
We run a link checker against the documentation within the build to make sure there are no broken links introduced. If broken links are detected, a notification is printed in the logs and left for someone to manually check.

A detected broken link should automatically fail the build.

## Context
Visually checking a log for broken links is not practical.

## Expected Behavior
Broken link = broken build

## Actual Behavior
Broken link != broken build

## Possible Fix
Either make the link checker force a fail, or have a process check the logs to search for the broken links text, then fail as appropriate.

## Steps to Reproduce
1) Break every link in the docs, or just one, it depends on how many links you like to destroy and how much of a point you want to prove.
2) Deliver the broken link docs
3) Watch the build pass
4) Watch the manual checking process get forgotten and all the broken links get rolled out into the release.

## Context
All I wanted to do was follow a link. A single link.

**Comment by mbwhite** [comment]
Changed the script to break and return an error.
