### ISSUE TITLE
Misleading Error Code when attempting to GET a non existent asset with REST server

### ISSUE THREAD

**Issue by rthatcher** [hyperledger/composer#1903]
Issuing a GET request for a non-existent asset the error I see is:

  "error": {
    "statusCode": 404,
    "name": "Error",
    "message": "Unknown \"Commodity\" id \"FCOX\".",
    "status": 404,
    "code": "MODEL_NOT_FOUND",
    "stack": "Error: Unknown \"Commodity\" id \"FCOX\".\n   ...
 

The MODEL_NOT_FOUND makes me worry that my business model can't be found rather than my asset.

Issuing a PUT request or a DELETE request for a non-existent asset don't show that code:

  "error": {
    "statusCode": 404,
    "name": "Error",
    "message": "Error trying invoke chaincode. Error: chaincode error (status: 500, message: Error: Object with ID 'COAL' in collection with ID 'Asset:org.acme.mynetwork.Commodity' does not exist)",
    "status": 404,
    "stack": "Error: Error trying invoke chaincode   ...

**Comment by sstone1** [comment]
I'm closing this as a limitation. I know it's not great but it's the default error message provided by LoopBack; there's very little we can do about it.
