### ISSUE TITLE
Removal of references to IBM/ Mozart/ Concerto Text from sample-networks

### ISSUE THREAD

**Issue by hannahrayner** [hyperledger/composer#1904]
## Context
Opened up in VS to search for traces of 'IBM', 'Mozart' and 'Concerto' and then remove. 

## Expected Behavior
For search feature to identify words such as 'IBM', 'Mozart' and 'Concerto' through 'search' feature and then manually delete/ replace as appropriate. 

## Actual Behavior
After deploying the animal tracking network, VS Code Search couldn't identify any words within text, despite me knowing they exist within the text. 

![image](https://user-images.githubusercontent.com/30467939/29417848-774484d2-8362-11e7-9e50-0f8977e942ec.png)

Above showing text in playground

![screen shot 2017-08-17 at 15 45 38](https://user-images.githubusercontent.com/30467939/29418038-268014ac-8363-11e7-897f-c6fd7b922fd6.png)

Above showing the search feature in VS Code

## Possible Fix
 Bug fix so that we can find all mentions of 'IBM', 'Mozart' and 'Concerto' and remove.

## Your Environment
Include as many relevant details about the environment you experienced the bug in
* Version used: 0.11.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): VS Code 1.14.2
* Operating System and version (desktop or mobile): Mac
* Link to your project:

**Comment by m-g-k** [comment]
@hannahrayner VSCode will exclude the node_modules folder from the search by default. Remove the exclusion and your search should work fine...

**Comment by EllisHenderson** [comment]
https://github.com/hyperledger/composer-sample-models/pull/38
https://github.com/hyperledger/composer-sample-networks/pull/102
