### ISSUE TITLE
Provide ability to not allow participant to override timestamp on a transaction

### ISSUE THREAD

**Issue by DennisM330** [hyperledger/composer#1908]
Need to provide the ability to not allow participant to overide timestamp on a transaction
## Context

A participant should not be able to override the time that a transaction is sent. Currently, every transaction automatically has a timestamp field that can be populated and submitted by the participant, allowing the participant to override the time that the transaction was submitted.

## Expected Behavior

Composer should determine the time a transaction is sent.  Provide the ability to disable a participant overriding the transaction time. 

## Actual Behavior

A user can override the time on a transaction.

**Comment by shacshar** [comment]
Composer can override the timestamp in submitTransaction ensuring that all transactions has a timestamp filled by the composer._

**Comment by DennisM330** [comment]
Yes, but the application developer can inadvertently or intentionally issue a call to the composer-rest-server and pass in the date/timestamp and, in essence, provide a date/timestamp that is not accurate as to when the business transaction transpired.

**Comment by sstone1** [comment]
We just need to forcibly set the timestamp in `composer-client` and override anything the user specifies.
