### ISSUE TITLE
Generally Improving Vehicle Lifecycle Demo

### ISSUE THREAD

**Issue by AntCole** [hyperledger/composer#1911]
(Hopefully this is not a duplicate but cant find the one I thought I made)

# Model Files

##  Simplify the composer files

**Model Files**
- [x] Simplify and cut out all items not used in demo (except scrap merchant)
- [x] Arrange model file items into logical files (eg for Car builder, Manufacturer, VDA, base/other)

**Script Files**
- [ ] Arrange script items into logical files (eg for Car builder, Manufacturer, VDA, setup)
- [ ] have one setup transaction to deploy a number of vehicles into the system that can be used to query 

**ACL Files**
- [ ] find a way to show off ACLs in the demo (work with Simon)

# Update the front end apps
**Car Builder App**
- [ ] Remove login screen
- [ ] Bring in car images that swipe sideways (to encourage swiping more)
- [x] Remove the arrow (->)from buttons 
- [x] Auto open the trim view once previous item chosen
- [x] Grey out 'Purchase + Build' button until car can be built (once make & color are chosen)
- [ ] Better indication an item has been selected (eg big bold box around color chosen or seat selection)
- [ ] More prominent tick on left of page next once the vehicles option has been chosen
- [x] change the 'back' button icon (currently hidden as the 'A' logo) to look like a back button
- [ ] Add a home button to reset & build new car
- [ ] Add some indication reached end of order and user should now look at the manufacturing app
- [ ] View previous orders page

**Manufacturer App**
- [ ] Make the order# match the order number shown in the Car builder app
- [ ] Add a view to show the car details (options added to car) - possibly click 'show details' button on the car
- [ ] The whole left side pane does not do anything - remove it (possibly ask the design guys or Simon if they have any ideas)
- [ ] The bottom graphs do not do anything, remove them or make them show something mildly useful (possibly ask the design guys or Simon if they have any ideas)
                   
**VDA App**
- [ ] The VDA part of the demo sometimes doesnt display the blocks. Anything we can do to fix that?
- [ ] Make the search bar work for order number (the one the Car builder app shows) or VIN number or Vehicle Make or other relevant things(show off queries? - ask Simon)
- [ ] Blocks viewer at top of page cannot scroll left/right
- [ ] Make it when click on a block from the Blocks viewer at top, it jumps to the relevant transaction below??
- [ ] Use the suspicious vehicles section to show off Queries? (ask Simon) or remove suspicious vehicles section if not
- [ ] Better define and explain reasons cars shown as suspicious
- [ ] Can see transaction details for suspicious vehicles
- [x] Remove buttons that do not do anything
- [x] in the last Day/Week/Month selector in top right
- [x] last Day/Week/Month selector above recent transactions
- [x] Change the items at top that look like tabs to look more like statistics:
     - Owner issued
     - VIN Assigned
     - Registered Vehicles
- [x] List who submitted the transactions properly in the transactions list (currently all show as system rather than Paul the buyer or manufacturer
- [x] Change 'Liam Grace' to 'System Admin' in transaction list

**Scrap Merchant App**
- [ ] Add a scrap merchant app using the Yo tooling
- [ ] Enable security login for the scrap merchant?? or one of the other apps?

# Deployment Options
**Simplify the self install process**
- [ ] An installer to install the demo with no lines of terminal script showing
- [ ] Install with as few terminal lines as possible
- [ ] Stop the installer from removing ALL docker images and only remove required images
- [ ] Update the VM image with the updated Demo and put onto SKYTAP

# Other
- [x] Is there a way we could more easily show what goes on the ledger/ blockchain
- [ ] Could we add a connection profile
- [ ] use the new identity cards somehow

**Comment by AntCole** [comment]
updated with Kathryn's thoughts for improvements

**Comment by markcastle3** [comment]
@AntCole is this the latest state of play ?

**Comment by sstone1** [comment]
Replaced by CIP #3130.
