### ISSUE TITLE
BusinessNetworkConnection getFactory not part of TypeScript defs

### ISSUE THREAD

**Issue by johnbentleyii** [hyperledger/composer#1926]
## Context
When using composer-client npm package with Angular.js, the BusinessNetworkConnection TypeScript mapping does include the getFactory method. This method is required for making connections.

## Expected Behavior
The getFactory method should be available in TypeScript.

## Actual Behavior
The getFactory method is not available in TypeScript.

## Possible Fix
Add "getFactory(): any;" to "export class BusinessNetworkConnection"

## Context
Cannot move forward with AngularJS App.

**Comment by sstone1** [comment]
@johnbentleyii `getFactory` is not on `BusinessNetworkConnection`. It's on `BusinessNetworkDefinition`, you need to do something like:

```
const bnc = new BusinessNetworkConnection();
// connect code omitted
const bnd = bnc.getBusinessNetwork();
const factory = bnd.getFactory();
```

**Comment by atbe** [comment]
@sstone1 then the documentation should reflect this. [This page](https://hyperledger.github.io/composer/managing/participant-add.html) is deceiving, see line below:

` ``
let businessNetworkConnection = new BusinessNetworkConnection();
...
       let factory = businessNetworkConnection.getFactory();
```
