### ISSUE TITLE
Identities Nitpicks

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#1930]
Please add any nitpicks you find on identities to this issue

- [x] (1) login page doesn't refresh when local storage is invalid __- must fix__ *Caroline*

- [x] (2) No ordering of identity cards on login screen **Caroline**

<img width="1274" alt="screen shot 2017-08-21 at 14 30 06" src="https://user-images.githubusercontent.com/7118158/29521492-b61d83f2-867d-11e7-9cf9-b9fd5c8b8d93.png">

- [x] (3) Identity cards are not a nice neat uniform size 😉 __- should fix__ **Caroline**

<img width="624" alt="screen shot 2017-08-21 at 13 50 47" src="https://user-images.githubusercontent.com/7118158/29520139-e58aba98-8677-11e7-98c1-5cedebcbc789.png">

- [ ] (4) Back button does not work as expected on deploy or create card pages

- [x] (5) Keep getting the "Let's Blockchain!" popup on the login screen- I'm already blockchaining!!! - got a seperate issue for this

- [ ] (6) Googly eyes on create card radio buttons (OSX/Chrome)

![image](https://user-images.githubusercontent.com/3535067/29520978-73dad3a2-867b-11e7-9182-cd394259e2c8.png)

- [ ] (7) **Save** button on create card connection profile page should be **Next**

- [x] (8) Connection profile names are not sorted on create card page **Caroline**

- [ ] (9) Nothing to see here image is borked

<img width="584" alt="screen shot 2017-08-21 at 13 41 58" src="https://user-images.githubusercontent.com/7118158/29519826-b60aa96e-8676-11e7-9525-627039f9f4c7.png">

(Looks like the empty registry image is borked as well)

- [x] (10) Revoke identity dialog says "remove identity" - should be "revoke identity" __-must fix__ **Caroline**

<img width="723" alt="screen shot 2017-08-21 at 13 52 40" src="https://user-images.githubusercontent.com/7118158/29520175-0d8bfbce-8678-11e7-9af6-cce441638897.png">

- [x] (11) Long identity name handling is not great (although unrealistic I admit) __-must fix__

<img width="370" alt="screen shot 2017-08-21 at 14 03 12" src="https://user-images.githubusercontent.com/7118158/29520616-b5352af2-8679-11e7-9020-e5cbe1629055.png">

- [x] (12) Deploy button should say **Update**

- [x] (13) Naming of Empty Business Network import is against all naming conventions permitted for business network names __-must fix__ **Caroline**

- [x] (14) *So now what do I do?* Is it necessary to prevent the user being able to delete all of the identities? Currently, you can delete the initial ID and by doing so you get to the state seen below.
![screen shot 2017-08-21 at 15 07 10](https://user-images.githubusercontent.com/16639383/29522865-c915aa0c-8682-11e7-8d82-095543a1c707.png) (suggestion is to stop this being deleted) __- must fix__

Not ideal but we'll prevent the 'special' web profile admin (PeerAdmin+ChannelAdmin) card being deleted for now - **JT**

- [x] (15) No error message on Basic Information screen
![image](https://user-images.githubusercontent.com/26481967/29520610-aaec334c-8679-11e7-9d8d-5824ce6a5a71.png) __- should fix__ **nick**

- [x] (16) This looks a bit naff - should we hide the slidey thing before showing the popup?

<img width="1055" alt="screen shot 2017-08-21 at 15 16 54" src="https://user-images.githubusercontent.com/7118158/29523164-00a6df4e-8684-11e7-8090-d75942177194.png"> __- must fix__

- [x] (17) It should not be possible to create a card using the web profile. (The create card button is disabled on the hosted version anyway, so this only applies to a local install.) __- must fix__ **Caroline**

- [x] (18) On create id cards business network name should be required __-must fix__ **Caroline**

- [ ] (19) Hitting _Return_ on the keyboard on the *Create ID Card* dialog doesn’t submit the form (i.e. click _Create_), even though the Create button appears to be highlighted. Have to _Tab_ to or click on the Create button first. Not sure if this is intentional, but feels a bit weird.

**Comment by RJackson1234** [comment]
(12) No error message on Basic Information screen
![image](https://user-images.githubusercontent.com/26481967/29520610-aaec334c-8679-11e7-9d8d-5824ce6a5a71.png)

**Comment by sstone1** [comment]
(15) Random sorting order for ID cards (we gonna sort by ID name or business network name?)

<img width="1274" alt="screen shot 2017-08-21 at 14 30 06" src="https://user-images.githubusercontent.com/7118158/29521492-b61d83f2-867d-11e7-9cf9-b9fd5c8b8d93.png">

**Comment by winslet** [comment]
(16) the hover state font weight needs to be increased to 400 (looks like its currently 100-300)
<img width="662" alt="image" src="https://user-images.githubusercontent.com/13980028/29521654-4d58fa6c-867e-11e7-9353-ec7c361f777e.png">

**Comment by davidkel** [comment]
(17) Import an id.card with a card.card file in the credentials part of the card. When I export that identity it adds a card.card file into the exported id.card and it's size is different to the one in the original id.card. However this file wasn't meant to be there so what got exported ?

**Comment by jt-nti** [comment]
(19) I don't think the doc is in yet but, just in case it get's missed, the existing tutorials need updating to include identity cards

**Comment by KaiUsher** [comment]
(20) *So now what do I do?* Is it necessary to prevent the user being able to delete all of the identities? Currently, you can delete the initial ID and by doing so you get to the state seen below.
![screen shot 2017-08-21 at 15 07 10](https://user-images.githubusercontent.com/16639383/29522865-c915aa0c-8682-11e7-8d82-095543a1c707.png)

**Comment by winslet** [comment]
(21) Selected samples should have a 2px solid border in import/replace slidey thingy
eg:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/13980028/29522941-1148a658-8683-11e7-85e5-a9001bb3d210.png">

Marked in green are my 2 changes:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/13980028/29522957-1cdeb7fa-8683-11e7-9619-091b9263bb47.png">

**Comment by KaiUsher** [comment]
(23) When choosing a sample to start with, the selected sample should have a border. This works correctly on all samples other than the Empty Business Network - if you select this sample the border disappears once the cursor is removed.

![screen shot 2017-08-21 at 15 15 22](https://user-images.githubusercontent.com/16639383/29523150-ec52e808-8683-11e7-8b46-51e15b92be1e.png)

**Comment by davidkel** [comment]
Hovering of the left side (Sorry can't capture the image) on the words "Web <business_network_name>" pops up a hover image that provides no benefit and is annoying.

**Comment by winslet** [comment]
(23) Delete Icon is too small across the site and does not use the pixel perfect version for smaller screens:

Currently:
<img width="325" alt="image" src="https://user-images.githubusercontent.com/13980028/29523082-a510da40-8683-11e7-831d-baa887aa702a.png">

Would be good to have the `height: 20px` 

Also if the SVG for the delete icon could be: 
[bin_small_sw.svg.zip](https://github.com/hyperledger/composer/files/1239061/bin_small_sw.svg.zip)

That would be brills :) (across the site)

**Comment by jt-nti** [comment]
(27) It should not be possible to create a card using the web profile. (The create card button is disabled on the hosted version anyway, so this only applies to a local install.)

**Comment by mbwhite** [comment]
- [ ] Edge Browser - create new identity button doesn't respond

**Comment by jt-nti** [comment]
(31) It would be nice if the name/description defaulted to the name/description of the selected network when deploying

**Comment by sstone1** [comment]
Nothing to indicate that I can scroll down (I have another connection profile down there!)

![screen shot 2017-08-21 at 15 30 18](https://user-images.githubusercontent.com/7118158/29523680-b55f68ec-8685-11e7-9119-e86779c0ed75.png)

**Comment by KaiUsher** [comment]
(who knows) Background issues on the import/replace network panel. I am currently seeing this:
![screen shot 2017-08-21 at 15 28 31](https://user-images.githubusercontent.com/16639383/29523671-adb08efa-8685-11e7-8f09-8b835e651878.png)
and I should be seeing this:
<img width="574" alt="screen shot 2017-08-21 at 15 28 48" src="https://user-images.githubusercontent.com/16639383/29523710-c9b44128-8685-11e7-93a6-2d0f6e7af3c0.png">

**Comment by winslet** [comment]
(28) Same as above in terms of illustration but also happening on registries now? Something strange has happened :o 

<img width="802" alt="image" src="https://user-images.githubusercontent.com/13980028/29523824-1a44b096-8686-11e7-8049-3fb958b749af.png">

**Comment by jt-nti** [comment]
(Some number/UUID) Progress spinner wobbles on OSX/Chrome when deploying network

![image](https://user-images.githubusercontent.com/3535067/29524278-4a772afe-8687-11e7-9dd2-3209777b8f1d.png)

**Comment by jt-nti** [comment]
(Another number) Identities don't seem to be sorted on the identity registry page

![image](https://user-images.githubusercontent.com/3535067/29529010-05b34984-8696-11e7-8a52-20de4fa45fc6.png)

**Comment by jt-nti** [comment]
(99) Not obvious what PeerAdmin and ChannelAdmin mean on some of the cards, and how they got there (it's not something exposed when creating cards):

![image](https://user-images.githubusercontent.com/3535067/29560064-c029e3b2-8728-11e7-9ac6-369db6528e1c.png)

**Comment by jt-nti** [comment]
(101) There is no way to tell if an ID card contains certificates or not. (Exporting cards with an unused secret vs enrolled credentials have pretty important implications.)

**Comment by KaiUsher** [comment]
This is using basic-sample-network, with two identities, so you can picture the scene. If you use one ID and add a query file to the network (where previously no .qry exists), and then change to the other/new identity, Playground tries to display a query file that does not exist in the editor.

![screen shot 2017-08-23 at 16 44 06](https://user-images.githubusercontent.com/16639383/29625278-2a6326b2-8823-11e7-969f-4152fe000c7c.png)

**Comment by jt-nti** [comment]
Moving remaining nitpicks to #2044
