### ISSUE TITLE
Playground fails to work in firefox if you set never remember history in privacy options

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1935]
![image](https://user-images.githubusercontent.com/25582377/29520992-808400ba-867b-11e7-9698-509420948582.png)

shows the screen received with 2 errors, 1 overlapping the other.

**Comment by sstone1** [comment]
See last comment from @caroline-church in: https://github.com/hyperledger/composer/issues/1600
We should add a check to try using local storage and throw an error modal saying it's not supported.

**Comment by sstone1** [comment]
P3 and no action in three months; clearly not important and never going to get fixed, so closing.
