### ISSUE TITLE
Editing the version of sample networks should take you directly to the package.json file editor

### ISSUE THREAD

**Issue by winslet** [hyperledger/composer#1937]
As it says on the tin, the current experience is kinda confusing what with the description being there too.

The suggestion is to remove the description and have the version number only with the edit pencil, once the edit icon is selected we go directly to the package.json edit screen.

_Current screen for reference_

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/13980028/29522134-23ed0cc0-8680-11e7-97b8-e31b021db0be.png">

**Comment by caroline-church** [comment]
done so closing
