### ISSUE TITLE
Completely fresh playground and empty composer directories, failed to deploy with error

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1938]
- Start with fresh docker container of the playground image
- Clear local storage
- import an id card (with keyValStore pointing to /home/composer/.composer-credentials)
- press the obvious deploy button
- provide a valid name
- Press deploy network

![image](https://user-images.githubusercontent.com/25582377/29522424-f0b6dee8-8680-11e7-89ee-8c681e2fc27e.png)

press OK
![image](https://user-images.githubusercontent.com/25582377/29522446-04588ad2-8681-11e7-849d-d4b84b810ad3.png)
Press OK
![image](https://user-images.githubusercontent.com/25582377/29522475-1d2f60b2-8681-11e7-8b4d-e9f977de7fea.png)

**Comment by caroline-church** [comment]
This happens because the connection profile doesn't get created on the file system until connect happens but import identity needs to be called before this and have the profile there

**Comment by magicliang** [comment]
I also met this, actually this file is created, but Composer insist seeking a find under home of user "composer":

{
    "type": "hlfv1",
    "orderers": [
       { "url" : "grpc://localhost:7050" }
    ],
    "ca": { "url": "http://localhost:7054",
            "name": "ca.org1.example.com"
    },
    "peers": [
        {
            "requestURL": "grpc://localhost:7051",
            "eventURL": "grpc://localhost:7053"
        }
    ],
    "keyValStore": "/Users/magicliang/.composer-credentials",
    "channel": "composerchannel",
    "mspID": "Org1MSP",
    "timeout": "300"
}

I don't know how to fix it if target file exists.

**Comment by magicliang** [comment]
And this only happens in my default browser Safari.

If I input localhost:8080 into chrome, I can see correct web page. Is that related to stale cache?

**Comment by caroline-church** [comment]
Can you describe exactly what you are doing and what error are you getting?
Also what version of composer do you have?

**Comment by magicliang** [comment]
Yes。

What I am doing:

I am keeping trying to run local composer playground to test my republish .bna file.

I use this to setup the composer environment:

curl -sSL https://hyperledger.github.io/composer/install-hlfv1.sh | bash

I am keep input "./composer.sh"  and "./composer.sh stop " in the composer folder.

My default browser is Safari. So every time ./composer.sh will open a new window of localhost:8080.

Then I see the error of this issue: 

![image](https://user-images.githubusercontent.com/3182954/31041657-b40c5480-a55e-11e7-8adf-6288a78d4c15.png)

If input localhost:8080 into other browser like Chrome/Firefox, I can see the website correctly.

Environment:

macOS Sierra 10.12.6 

Safari 10.1.2

Not quite sure what composer version I am using, but it should be latest one.

**Comment by caroline-church** [comment]
I would suggest deleting the card that isn't working and recreating it. You
could always export the card from chrome/Firefox and import it into safari
and see if that works

**Comment by markcastle3** [comment]
Is this something that could be moved to stackoverflow ?

**Comment by DavraYoung** [comment]
Try to clean the cash of the page, that helped me in case where ID null error occured.
