### ISSUE TITLE
File icon for .qry files not displaying correctly on the add file modal

### ISSUE THREAD

**Issue by KaiUsher** [hyperledger/composer#1941]
When adding a .qry file using the browse/drag-and-drop option the file icon is displayed incorrectly - the text on the icon appears to have far too high of a font weight.
Using Chrome on Mac.

## Expected Behavior
The text on the icon should be of a suitable weight - the correct style icon can be seem when importing any other file type...

![screen shot 2017-08-21 at 15 54 02](https://user-images.githubusercontent.com/16639383/29524906-0200e182-8689-11e7-8fe6-23edc3f61d13.png)

## Actual Behavior
The .qry text is practically unreadable...

![screen shot 2017-08-21 at 15 46 28](https://user-images.githubusercontent.com/16639383/29524939-15acd7d6-8689-11e7-92b6-fe6cf9de78aa.png)

## Steps to Reproduce
1. Select '+ Add a file...'
2. Drag-and-drop or browse to a .qry file on your computer.
3. See the bad icon!

**Comment by sstone1** [comment]
P3 and no action in three months; clearly not important and never going to get fixed, so closing.
