### ISSUE TITLE
Pooling of business network connections

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#1953]
_As an_ application developer
_I need to_ write applications that pool or otherwise reuse business network connections
_so that_ I can build robust and scalable Blockchain applications

## Details

There is significant overhead involved in establishing a new business network connection. Additionally, if they are not closed correctly by client application code then the build-up of open connections can cause issues.

Best practice is to reuse connections (or perhaps use connection pooling to achieve this reuse more transparently to the application code). This best practice is not always obvious to application developers, and implementing well featured and robust connection pooling can be non-trivial.

This enhancement is to improve the client development experience in this area. Possible options include:
- Publish a sample and/or article describing this best practice and including example code, perhaps using a 3rd-party connection pooling module.
- Include connection pooling capability directly in the Composer code.

**Comment by sstone1** [comment]
As far as I know, nobody is working on this at the moment or planning to work on it, so closing. 
If somebody wishes to work on this in the future, then please reopen this issue or open a new issue.
