### ISSUE TITLE
As a user, I can rename (change the identifier) of an existing resource

### ISSUE THREAD

**Issue by mqmatt** [hyperledger/composer#1957]
## Context
It is not possible to edit a registry object's key field (the one used by 'identified by'). Attempting to do so results in an error.

## Expected Behavior
The relevant field of the asset/participant is updated.

## Actual Behavior
I get the error message "Error: Object with ID '[new identifier]' in collection with ID '[Class]' does not exist", where [new identifier] is the new identifier for the object I'm trying to update, and [Class] is the name of the asset/participant class.
The object is not updated.

## Steps to Reproduce
1. In Playground, import or create a sample network (I tried Car Auction and Hello World, but should work with any).
2. Switch to the Test tab and add a participant or asset to a registry.
3. Click the 'Edit' button next to the asset or participant
4. Modify a key field (one that is used by 'identified by').
5. Click 'Update'
6. Error: Object with ID '[new identifier]' in collection with ID '[Class]' does not exist

## Your Environment
* Version used: v0.11.3
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome
* Operating System and version (desktop or mobile): MacOS

**Comment by sstone1** [comment]
@mqmatt yeah, `rename` (or whatever we want to call that operation) is not supported at the moment. It might be something we disable for now (with an obvious error message) and then revisit later.
