### ISSUE TITLE
As a user, I can specify the enrolment secret of a new identity instead of having one generated

### ISSUE THREAD

**Issue by nasht00** [hyperledger/composer#1970]
Running `composer identity issue --help` mentions this parameter:

` --enrollSecret, -s           The enrollment secret of the user  [string]`

Yet, using this option seems to have no effect on the secret:

```
nathanh-mbp:~ nathanh$ composer identity issue -p hlfv1 -n 'vbc-network' -i admin -s adminpw -u sam1 -a "resource:MyParticipant#sam" -s "sam"

An identity was issued to the participant 'resource:MyParticipant#sam'
The participant can now connect to the business network with the following details:
  userID = sam1
  userSecret = QgXoOOLAYQmM
```

**Comment by rahianeja** [comment]
userSecret is generated by the fabric and assigned to specific user. However, --enrollSecret present in --help shows, it should be possible. Can remove --enrollSecret from command or need to enable this functionality..

**Comment by sstone1** [comment]
@nasht00 @rahianeja this parameter is for passing the enrolment secret of the identity used to issue the identity, not the enrolment secret for the new identity being issued. All of the Composer commands have the same set of `-i` enrolment ID and `-s` enrolment secret parameters.

**Comment by awjh-ibm** [comment]
Is this still valid? Using the composer identity issue now creates a card file rather than an ID and secret pair?

**Comment by jt-nti** [comment]
The `-i` enrolment ID and `-s` enrolment secret parameters no longer exist so closing this issue
