### ISSUE TITLE
"Let's Blockchain" appears too frequently

### ISSUE THREAD

**Issue by hannahrayner** [hyperledger/composer#1972]
Modal "Let's Blockchain" appears too frequently when users have already started _using Blockchain_. 

![screen shot 2017-08-23 at 09 40 18](https://user-images.githubusercontent.com/30467939/29606759-290bceb8-87e7-11e7-9a0a-c54754d02096.png)

**Comment by nklincoln** [comment]
@hannahrayner ... is this still a current issue?
