### ISSUE TITLE
Organising the ID registry, including where it should go and what it should do

### ISSUE THREAD

**Issue by winslet** [hyperledger/composer#1976]
This is as yet not full understood or scoped however it surrounds the use of the ID registry now that there is a card view of your wallet, do we need both?

eg. this registry
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/13980028/29612434-30661ac6-87f9-11e7-8891-2151ba9487dc.png">

now that id cards exist:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/13980028/29612449-40d46b74-87f9-11e7-87b5-d766c5cda999.png">

**Comment by jt-nti** [comment]
From @davidkel

> ![image](https://user-images.githubusercontent.com/25582377/29918476-7b3568a0-8e3d-11e7-92a6-1e5e72ec802a.png)
> This seems confusing to me. From the screen it isn’t obvious what is going on here, ie the top section are my identities that are in my wallet and the bottom section are Participants in the network that have been associated with ids. If I delete an identity from my wallet I have this screen left and now I have the concept of an ID name which isn’t actually valid anymore as that ID name no longer exists, and then what can I do about it ? What if I issue a new identity with the same name ? Which is what I did after revoking the Original one
> ![image](https://user-images.githubusercontent.com/25582377/29918643-0d2677ea-8e3e-11e7-909b-16597f2c567a.png)
> So I then connected with admin and tried to switch to Dave, it came up with the same error but now tells me Dave is in use
> ![image](https://user-images.githubusercontent.com/25582377/29918703-469470e0-8e3e-11e7-85c9-5f0f6286ed9b.png)
>
