### ISSUE TITLE
Using the v0.12.0 playground on safari throws breaking error

### ISSUE THREAD

**Issue by winslet** [hyperledger/composer#1982]
Loading up the unstable version of playground using the one click install and viewing in safari throws a:

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/13980028/29621362-6a902b50-8818-11e7-9769-d97c4e95d9d6.png">

with the following printed to the console:

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/13980028/29621385-765ef916-8818-11e7-8c28-3e597162d462.png">

This error continues into the playground if you click through and the same error is thrown if you try and connect to a card/business network.

**Comment by caroline-church** [comment]
This is due to the connection profile store changes

**Comment by caroline-church** [comment]
closing as this is now be fixed

**Comment by sstone1** [comment]
Not totally fixed it seems...

**Comment by sstone1** [comment]
...and now fixed 😉
