### ISSUE TITLE
Docs Nitpicks for ID Cards

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1983]
A few items to be noted before they get lost:

Doc Pages:
https://hyperledger.github.io/composer/unstable/managing/managingindex.html
- ID cards are currently a Playground only concept, I don't really get the impression of that from here and am concerned that people will start trying to create their own via a non-existing CLI command option

https://hyperledger.github.io/composer/unstable/managing/id-cards-playground.html
 - This completely covers the point above. But It would be nice if there could be a one-liner in a higher level that says "Playground Only"
- Confused title "Creating an ID card using from the Wallet" 
- Meta-data code block is missing a comma (invalid json)

**Comment by RJackson1234** [comment]
Identities and ID cards in the Hyperledger Composer Playground  (SECTION)

In the Hyperledger Composer Playground, there is a wallet.... this intro needs to be included in the ID card section ....and is the first time wallet is mention (but we don't explain what it is)

**Comment by RJackson1234** [comment]
ID cards can be used in the Hyperledger Composer Playground to manage identities for different business networks and connection profiles......we say that 'can' be used, does that mean there are other ways or is this THE way to use them?

**Comment by jt-nti** [comment]
There is not enough information to successfully create an ID card manually. There needs to be more explicit detail about the exact filenames, layout, etc., what the roles mean, where to get the files/information, and so on. It might be useful to include a template ID card zip which can be downloaded and edited.
