### ISSUE TITLE
Playground Tutorial Needs Some Love

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1984]
The Playground tutorial is the first point of call for all uses of well, the Hyperledger Composer product ... it needs to be as slick as possible ... and is missing some essential information. This issue will try to contain as much of the required information as possible, and mainly a brain dump on things that we may wish to include.

- Step 0 is wrong (the introduction). What we are *now* doing is guiding the user on accessing a deployed business network via a specific user identity, through the use of ID Cards, and then editing that business network definition and *updating* the business network with the new definition.

- Step 1 is wrong. Nothing is loaded, you are taken to the Wallet page, from which you can well, do wallet things. But what are "wallet things" ? Good question, we need a screen shot and a description of what the options are, what they do and why. Yes it's a tutorial, but I won't read the words, I'll look at the pretty pictures and grep for the info i'm interested in. Somewhere in that info there should be information on the "deployed business networks that I can access" which is the replacement for the "basic-sample-network is imported by default".

- Step 2 is correct, but a little insufficient. If we have really extended the description blurb in step 1, then we still should be providing a concrete golden path through to the what we want them to do....the best way to do that would be with a gif animation as is done in lower stages. We could guide the user into accessing the deployed basic-sample-network via the admin user, though selection/use of the admin ID Card.

- Step 3 is in the wrong place. It should be Step 4, or at least follow after some more explaining. We need to show the user what they should expect to see, and where things are. For instance, after connecting to a business network, we are taken to the editor ... this needs some kind of description - an annotated diagram of sorts so that people not only know where things are but what they do. In latter sections we ask a user to open a file from the navigator ... it would have been nice if we had let them know what it is in advance. Proposal here is a screen capture, with sections marked out describing what is what.

- Steps 3/4/5 would follow on much more nicely given a higher level diagram showing the layout of the editor.

- Step 6 is wrong. We no longer 'deploy' we 'Update'. This will require a few more words around the subject, and a completely new gif animation that uses the newer playground

- Step 7. Love the gif, nice and helpful, but again we take people somewhere and then don't tell them where they are, where things are, or what they can do with them. Yup, another image with descriptors would be nice here.

- Step 10. Needs splitting out - once we have performed the transaction we can inspect the assets/participants directly. *Then* we can introduce the Historian in more detail. The Historian image is out of date and needs to be replaced with the new column labeling.

**Comment by mqmatt** [comment]
Step 1: I'm not sure many users will know how to run localStorage.clear(). Either we need to tell user's exactly what to do or remove this step.

**Comment by nklincoln** [comment]
So, following more thinking, maybe what we have revealed is a need for Playground to have its own high level entry in the Docs, within which all Playground components/operations are described. This would leave the Tutorial free to be a little more "whizz-through", with a few links to the main Playground documentation for detailed explanation?

Somehow it does seem a little strange that Playground doesn't really have any serious documentation behind it.

@sstone1 @caroline-church @EdProsser  - any thoughts on this?

**Comment by mqmatt** [comment]
Hey Nick - more playground docs is certainly a good thing. It might make sense to split Playground docs out for some parts, I'd caution against splitting everything. Parts of the doc already make the playground as being completely disjointed from the dev tools. The two installation guides for example make it very difficult for users to switch from the playground-only install to the developer tools install - they look like they're written by two different dev teams.
Topics that introduce concepts should certainly be shared - that way you have a clear distinction between the presentation layer and the underlying model, which should be the same for both web, commandline and API.

**Comment by jt-nti** [comment]
**Note:** all the animated screen shots will be out of date now, even if they are not directly related to ID cards (the top navigation has changed)

**Comment by EdProsser** [comment]
@jt-nti This is why images/videos in docs are huge overhead compared to the text. Also, multiply it by translation for extra fun.
