### ISSUE TITLE
Tooltip/prompt on web playground to help you get started

### ISSUE THREAD

**Issue by winslet** [hyperledger/composer#1994]
As above...we need to give people a bit of a prompt to get started as quickly as they can on the web playground. 

My suggestion:
![transaction registry copy 30](https://user-images.githubusercontent.com/13980028/29670823-cbbc1908-88df-11e7-8200-e4dc7f1d555d.png)

## Behaviour
The first time someone enters the playground we show this tooltip directly after they click "lets blockchain" we do not wait for them to hover over the connect button. We carry on showing this until they interact with the page in some way (eg click to deploy another network/upload id card etc etc). 

Im happy with us using the same styling as what we have on the current tooltips. But can we increase the font weight to be 400 (from memory it was looking very "light").

Thanks any questions gimme a shout! 🥑

**Comment by caroline-church** [comment]
@winslet  Added the tooltip component for this, not sure if we want to keep the issue with the new designs

**Comment by winslet** [comment]
Replaced with #2009
