### ISSUE TITLE
As a composer developer, I wish to use third-party javascript libraries in my transactions

### ISSUE THREAD

**Issue by jonathan-yk-tan** [hyperledger/composer#1995]
This is more of a feature request than a bug : 
When developing composer transactions, I wish to use third-party javascript libraries for example to perform HTTP GETs or signing data

## Expected Behavior
Able to import javascript libraries

## Steps to Reproduce
1. import and node.js library into a transaction file

## Existing issues
https://stackoverflow.com/questions/45061533/can-hyperledger-composer-transactions-support-third-party-javascript-libraries-n

## Context
Trying to use other javscript/node.js libraries to perform calls like HTTP GET and 

## Your Environment

* Version used: 0.11.3
* Environment name and version (e.g. Chrome 39, node.js 5.4): Version 60.0.3112.90 (Official Build) (64-bit) , 
* Operating System and version (desktop or mobile):Mac OSX Sierra
* Link to your project:

**Comment by sstone1** [comment]
Note that we are providing built in HTTP support - there is a `post` function at the moment, but we are also looking at extending this to support other HTTP verbs (#1843).

**Comment by nasht00** [comment]
I'd like to add my vote for this feature. Not specifically for HTTP, but for various modules we are looking to use (encryption, rules engine)

**Comment by sstone1** [comment]
Replaced by CIP #3169.
