### ISSUE TITLE
Is it possible to call secured composer APIs from server side(node)

### ISSUE THREAD

**Issue by razik29** [hyperledger/composer#1996]
### Introduction

We have a simple webapp(no angular) being served by nodejs. We are trying to hit a **secured composer API** present in another server instance(AWS) with different ports.

This works very well when we hit the api after authorization(github oauth) **from the client side(frontend)** using simple JQuery AJAX call and `withCredentials: true` parameter like so:

This works:
```
$.ajax({
  url: "http://apidomain:3000/api/system/ping",
  dataType: 'JSON',
  method: method,
  xhrFields: {
    withCredentials: true
  },
  ... 
```

### Issue

Now when we make the **same api call initiated from the server side(node), it fails**. Giving us **401: Authorization Required** error.

So my question stands - Is it possible to call secured composer APIs from server side(node) ? If anyone has tried this before please let us know.

Any help would be very much appreciated.

**Comment by sstone1** [comment]
It is possible today but with great difficulty - the API token must be extracted from a cookie that is stored in the web browser when you authenticate. We need to expose the API token somehow through the Composer REST server interface for this use case.

**Comment by razik29** [comment]
Thanks @sstone1 - Yes, we have already tried extracting the cookies as you mentioned but there seems to be **only 2 cookies after authentication** namely `GA`(assuming Google Analytics) and `connect.sid` and there are no signs of `access_token` cookie(even if checked from the browser).

But surprisingly, from the web browser when we take a look at the request made to the secured api after authentication, it seems to be carrying a third `access_token`(JWT) cookie which is found anywhere on the browser end.

**Comment by sstone1** [comment]
Not sure if this is the problem, but you will not be able to find the `access_token` cookie by looking at your application - it will only be available when you point the web browser at the REST server and then inspect the cookies. From your post above that means looking at the cookies for `http://apidomain:3000/explorer`.

There is an update going into the next release that will add the access token to the REST explorer UI in the REST server. I've also updated the documentation to state how you can get the access token from the REST server and use it with any HTTP or REST client. You can read a preview of that here: https://hyperledger.github.io/composer/unstable/integrating/enabling-rest-authentication.html

All of those changes have been delivered (just not released yet) so closing.

**Comment by razik29** [comment]
Yes, I have gone through the PR and I am especially interested in the addition of access token coming on the next release. Definitely looking forward for that change.

Regarding the same @sstone1 just had a **minor clarification** -- does the access token change with every successful authentication/session based(meaning we would have to dynamically fetch this from an api and use it on the subsequent requests) or static one-time token(we could just generated token once and use it across multiple authentications)

**Comment by Rmannn** [comment]
For users that are looking for a way to decode the cookie...

to get a token generated by the rest-server, you could use this snippet as example, here we use the jwt passport-jwt to secure the rest server, but you can use it with your favorite provider.
You must use the module request with a "jar" 
```js
import jwt from 'jsonwebtoken'
import request from 'request-promise'

const app = express()
app.get('/admin-token', async (req, res, next) => {
    //generate a signed token
    var token = jwt.sign({ sub: '123456', username: "myname" }, 'secret');
    try {
        //start the request with a cookie jar
        const j = request.jar()
        const restServerDomain = 'http://localhost:3000/'
        const response = await request({
            uri: restServerDomain + 'auth/jwt/callback',
            headers: { 'Authorization': 'Bearer ' + token },
            resolveWithFullResponse: true,
            jar: j
        })
        //get the cookies from the request and decode them to find the key access_token
        const cookies = j.getCookies('http://localhost:3000')
        console.log(cookies)
        let accessToken
        cookies.forEach(c => c.key === "access_token" ? accessToken = decodeURIComponent(c.value) : null)
        const error = new Error('No access token found')
        if (!accessToken) throw error
        const matches = accessToken.match(/^s:(.+?)\./)
        if (!matches) throw error
        accessToken = matches[1];
        //respond to clients with the token to use in subrequest to the rest server
        res.json({ access_token: accessToken })
    } catch (e) {
        return next(e)
    }
})
app.listen(3002, (e) => {
    if (e) {
        return console.log(e)
    }
    console.log('Listening on 3002')
})
```

**Comment by HoneyShahOX** [comment]
There should be a way of calling secured rest api from server side. Can't we get access_token in the response of any web service where we pass token?

**Comment by JBGodilo** [comment]
@sstone1 just wondering if the changes you mentioned above about adding the access_token to the rest explorer UI was already implemented. The thing is, we've a project today that uses passport jwt for authentication if we can't seem to use still the above strategy which is to use the access_token directly to the rest server. I don't know if we are just doing it the wrong way. Do you have a more a detailed documentation about it?   ##Thank you.

**Comment by irkochos** [comment]
> For users that are looking for a way to decode the cookie...
> 
> to get a token generated by the rest-server, you could use this snippet as example, here we use the jwt passport-jwt to secure the rest server, but you can use it with your favorite provider.
> You must use the module request with a "jar"
> 
> ```js
> import jwt from 'jsonwebtoken'
> import request from 'request-promise'
> 
> const app = express()
> app.get('/admin-token', async (req, res, next) => {
>     //generate a signed token
>     var token = jwt.sign({ id:"myuseruniqueid", sub: '123456', username: "myname" }, 'secret');
>     try {
>         //start the request with a cookie jar
>         const j = request.jar()
>         const restServerDomain = 'http://localhost:3000'
>         await request({
>             uri: restServerDomain + '/auth/jwt/callback',
>             headers: { 'Authorization': 'Bearer ' + token },
>             jar: j
>         })
>         //get the cookies from the request and decode them to find the key access_token
>         const cookies = j.getCookies(restServerDomain)
>         let accessToken
>         cookies.forEach(c => c.key === "access_token" ? accessToken = decodeURIComponent(c.value) : null)
>         const error = new Error('No access token found')
>         if (!accessToken) throw error
>         const matches = accessToken.match(/^s:(.+?)\./)
>         if (!matches) throw error
>         accessToken = matches[1];
>         //respond to clients with the token to use in subrequest to the rest server
>         res.json({ access_token: accessToken })
>     } catch (e) {
>         return next(e)
>     }
> })
> app.listen(3002, (e) => {
>     if (e) {
>         return console.log(e)
>     }
>     console.log('Listening on 3002')
> })
> ```

Hi @Rmannn yhanks for this snippet, please if that is possible in my angular app, cauze i need to retraive the access_token from the rest server cookie, is that is possible.
