### ISSUE TITLE
Video with volume on Queries Guide tutorial (Playground Docs)

### ISSUE THREAD

**Issue by georgschultz** [hyperledger/composer#1998]
## Context

A video with volume is on the Queries Guide.
## Expected Behavior

A video without volume should play.
## Actual Behavior

The video plays with volume.

**Comment by markcastle3** [comment]
@EdMoffatt can you please re-record this video or strip the audio?

**Comment by EdMoffatt** [comment]
@hannahrayner - I think you mentioned re-doing some videos for the Tutorials - was this one you already looked at, or one you could also take a look at? :)

**Comment by fenglianxu** [comment]
@EdMoffatt I have sent the updated query video to Paul. If this is not updated and you need the latest video, I can send this to you.

**Comment by mahoney1** [comment]
now that I'm back, will update the video today .
