### ISSUE TITLE
A Robust Concept Libary

### ISSUE THREAD

**Issue by adrianblakey** [hyperledger/composer#2001]
Composer Concepts are like complex data types and a useful modelling artifact. They provide representational power to the model and greatly simplify the specification of an Asset by factoring out several related attributes into a single reusable concept. Also, the basic composer types are missing important features to accurately represent basic things like - money.

However since concepts lack encapsulation, functionality that should be closely associated with the concept has to be coded in functions with a risk that similar functionality shall be repeated in several places throughout the code.

## Context
This is not a bug but a feature request to improve the power of concepts to make them more like first class data types than "structs" and to create a library of robust, commonly needed concepts that would greatly speed up developing applications by being able to rely on these concepts and reuse them.

The idea would be to provide say a org.hyperledger.composer.concepts library that could be included/required both in a model file and in javascript transactions and clients. There are a few obvious candidates for what might go in a simple first version - like BigDecimal, Currency, Duration, Address, Phone, EmailAddress, Blob (which could be extended by mime types for jpeg/tiff/microsoft binarys ...)

## Expected Behavior
For example, in the model file:

var concept = require('org/hyperledger/composer/concepts');

asset Foo {
 o concept.BigDecimal openingBalance
 o concept.Duration accountClosingPeriod
}

or like java say:

import org.hyperledger.composer.concept.*
asset Foo {

 o org.hyperledger.composer.concept.BigDecimal balance
 o Music toMyEars
}

Then in a javascript:

var concept = require('org/hyperledger/composer/concepts');
var balance = new concept.BigDecimal('100.25');
var deposit = new concept.BigDecimal('20.50');
var total = concept.BigDecimal.add([ balance, deposit ])

My javascript creativity runs out at this point :-) and there would need to be some pro-forma javascript to facilitate creating and extending a concept library.

**Comment by sstone1** [comment]
I think in most cases here you're not really after concepts. Decimal, Duration, Blob are really new primitive types that require enhancements to the modelling language and serialiser. 

Address is definitely a concept though. We actually have some `composer.*` model libraries on npm (published as `composer.base`) that contain exactly this:
https://github.com/hyperledger/composer-sample-models/blob/master/packages/composer.base/models/base.cto#L57

Some of the others, Phone and EmailAddress are (I think) strings with validators attached. I seem to remember discussing adding some sort of `typedef` style functionality where you can define a primitive type with a validator as another type:

`typedef EmailAddress String validator=".*?@.*?"`

Passing to @dselman as modelling stuff is his domain and he needs to doc how you make use of the `composer.*` model libraries on npm 😉

**Comment by adrianblakey** [comment]
Yeah well maybe. I think I want extensible types not a fixed set of primitive types. 

I don't know if I really agree about Phone, EmailAddress - because if they are Concepts (or Types) and not constrained attributes, you'd think that some sort of application generator could render them meaningfully in the UI as say micro-formats.

**Comment by dselman** [comment]
I think we are discussing three things here:

1. Reusable libraries of models: we already have most of the technology in place to support this, with many models already published to npm, and used by business networks. The biggest missing piece is the ability for a model to import types from another model, and have those imports resolved from the model library (npm).

2. Additional primitive types. Agree that some additions may be useful, but I think we've covered the 80% - we should let user requirements drive the prioritization of the rest.

3. The ability to reuse validators across primtive types (aka facets). I agree that this would be a useful addition in some cases. The workaround at the moment is to wrap them in a concept and to reuse that.

Please open issues for (2) and (3) so we can move the more detailed discussion. (1) already has an issue open.
