### ISSUE TITLE
Invoking Transactions on a Timer

### ISSUE THREAD

**Issue by adrianblakey** [hyperledger/composer#2002]
An application can be modeled as a collection of user-initiated transactions and time-initiated transactions. The former are well supported by the playground and REST server. Support for the latter would be a nice feature.

## Context
Not a bug, a feature suggestion. This might be implemented outside Composer as say a cron job, however some small amount of support in the code generator would produce a far better integrated and useful solution.

## Expected Behavior
How about adding an annotation to transactions that used the cron syntax to define when a specific transaction shall be run and provide an open source implementation of a cron daemon (implemented in nodejs/docker). The code generation would scan the annotations and create a "crontab" for the cron daemon.

Suggested syntax  for "ontime" e.g.

/*
* @ontime 59 23 31 12 5 *
* From the cron docs - one minute  before the end of year if the last day of the year is Friday
* @param {org.acme.mynetwork.RunMe} runMe
* @return Promise
* @transaction
*/
function RunMe(runMe) {
...

**Comment by sstone1** [comment]
I don't think this is as trivial as suggested:

1. Only one participant can submit each transaction. There is no support in Hyperledger Fabric for a decentralised scheduler service. Which participants are responsible for submitting the transactions? How is this specified?
2. How does one specify the inputs to each transaction, in the case that the transaction is not just a trivial empty definition?

There are also many well tested open source cron/scheduler solutions, and Composer neatly ties into these with very little effort. You can use the `composer transaction submit` CLI, drive the REST API using something like curl, or even programatically using the Node.js APIs within something like OpenWhisk or AWS Lambda. 

It's unlikely that my team will look at this - the cost of implementing it does not seem worth the benefits, given the existing mechanisms for doing this - we're happy to accept contributions though 😉

**Comment by dselman** [comment]
Scheduled jobs and temporal logic for decentralised systems is a massive can of worms (which I know fairly well from previous products I have worked on). I agree that scheduled submission of transactions should be handled on the client side. E.g. a Node-RED flow, IFTT or OpenWhisk could be used to drive scheduled transactions.

**Comment by huanggze** [comment]
Even though this issue is closed, I still see the need for scheduled transactions. For example, a marketable asset ( airline time slot) has a time-decay feature (distinct from permanent assets like diamond). The asset should be gone when it reaches the end time. There must be a way to allow a smart contract to update itself (e.g. to remove the past slot from the market). Obviously, it is impossible for asset owners to do that because of no motivation.

This thought is originally from my current project, distributed airline time slot trading. I hope it is relevant. Looking forward to better solutions, Thanks

**Comment by mtsammy40** [comment]
I do believe that timed transactions are invaluable in some use cases. Just throwing it out there.

**Comment by tomszero** [comment]
I agree @sstone1 . Although it seems as a useful concept, the implementation requires to rethink how transactions are submitted and added to the blockchain using the Fabric framework. At the end, it's more practical to handle it on the client side, just as @dselman suggest it.
