### ISSUE TITLE
Model Event Listeners

### ISSUE THREAD

**Issue by adrianblakey** [hyperledger/composer#2003]
Events are obviously a useful feature, however they are programmatically invoked in the flow of a transaction and are somewhat limited and hidden in code. If there were some system-defined listeners for specific events that were tied to model objects, they could be a much richer facility and behave more like database triggers for example.

## Context
Could we implement some specific model event listeners that we could tie to specific model events such as:

- OnTransactionStart
- OnTransactionCommit
- OnTransactionFail/Abort
- OnObjectCreation
- OnObjectUpdate
- OnObjectAdd
- OnRelationshipCreate
- OnAttributeSet/Get

This would make an application less "programmatic" and more declarative and perhaps easier to understand. There are also many use cases for this capability. OnTransactionStart could say create objects needed for the transaction to run successfully. OnTransactionFail - could do clean up ...

The different types of callbacks would pass not only the event object but some appropriate context to the transaction (a Transaction object?) that would be available to the transaction itself.

## Expected Behavior
Again more syntax in the transaction comments.

Model ...
event MyStartEvent {
// You can have attributes and relationships here and there is nothing to stop you
// running it with emit(event) in code
}
Transaction ...
/*
* @onTransactionStart MyStartEvent
* @param {org.acme.mynetwork.RunIt} RunIt - the RunIt transaction instance
 * @return {Promise} Asset Registry Promise
 * @transaction
*/
function RunIt(runIt) {
...

**Comment by sstone1** [comment]
It's not clear from the above - what are you suggesting handles these events? From the example it looks like the RunIt transaction emits a MyStartEvent when the transaction starts. Is there a missing JavaScript function that sits inside the business network definition to handle the MyStartEvent?
