### ISSUE TITLE
"My Wallets" Screen can be confusing - changing the way a user launches into the product

### ISSUE THREAD

**Issue by winslet** [hyperledger/composer#2009]
Due to the new "My Wallets" screen, we need to figure out how to help our users get to the product as easily and quickly as possible. The flow below should help this:

1. Standard "lets blockchain" modal appears - nothing different here.

2. When clicking through, we would like to remove the current "default" of having the basic sample network there to click on. We would like to replace it with the following:

![transaction registry copy 30](https://user-images.githubusercontent.com/13980028/29716025-a8417032-89a1-11e7-9468-baba2c7a8a0d.png)

The big changes are the "deploy new business network" button as well as the question mark on the right hand side "Confused about this screen...."

3. And a hover state for that button (we can make this more obvious if it is not on your screens - please let me know).

![transaction registry copy 33](https://user-images.githubusercontent.com/13980028/29716083-e8303066-89a1-11e7-8ef2-b7381abb0a8b.png)

4. Clicking on that link will take you to the "deploy new business network" screen as per usual:

![transaction registry copy 28](https://user-images.githubusercontent.com/13980028/29716114-0cf3dd58-89a2-11e7-82d6-0ebef03cf2f6.png)

Also note the duplication of the question mark on the right hand side, providing a link to the new playground tutorial being worked on.

5. If you have deployed a network, the semi transparent button is still there:

![transaction registry copy 32](https://user-images.githubusercontent.com/13980028/29716174-3f2cb34e-89a2-11e7-9735-2298336d2030.png)

6. Extra points: What happens if you do not have access to create a business network - 

(please modify the copy to suit, I think there is probably a better way of wording this @EdProsser do you have any views?)
![transaction registry copy 34](https://user-images.githubusercontent.com/13980028/29716353-f1b4970c-89a2-11e7-998f-44da873bfaf2.png)

**New Assets:**
[Wallet_assets_2.zip](https://github.com/hyperledger/composer/files/1251984/Wallet_assets_2.zip)

**Marketch:**
[Composer_Wallet_SW_3.zip](https://github.com/hyperledger/composer/files/1251980/Composer_Wallet_SW_3.zip)

Any questions lemme know! 🍏

**Comment by sstone1** [comment]
This is a test to summon our designers, paging @hyperledger/composer-designers!

**Comment by jt-nti** [comment]
Done
