### ISSUE TITLE
Support for Unique Identifier Generation

### ISSUE THREAD

**Issue by adrianblakey** [hyperledger/composer#2013]
Please consider providing a function the guarantees it returns a universally unique identifier that can be used as an identifier for Assets and Participants.

## Context
It's often not possible (and I'd content never possible in real data) to find an attribute that uniquely identifies an instance of an entity type (Asset or Participant). Since the model mandates its inclusion  it's necessary to be able to conjure up an abstract universally unique identifier.

## Expected Behavior
Please could we provide a javascript function that returns say a UUID - some long random, meaningless string so that the function guarantees to never emit the same string again in say 100m years.

**Comment by dselman** [comment]
Such JS functions exist (they are pretty easy to write), check StackOverflow - however using them on the server side is incompatible with a distributed blockchain based approach, where each peer needs to achieve consensus with all other peers for the transaction to be committed. The execution of chain code needs to be deterministic -- given a set of inputs / state it must *always* compute the same set of outputs (updates to the ledger and emitted events). 

So, that rules out UUID generations, Math.random(), using the current datetime in chain code etc.
