### ISSUE TITLE
Rethink the Need For Identifiers

### ISSUE THREAD

**Issue by adrianblakey** [hyperledger/composer#2014]
Please think about the need for "identified by".

## Context
Identity is uniquely represented by a specific attribute of an entity type (Asset, Participant) that must have a unique value. I'd content (but can't prove) that there is no attribute of any entity type that is ever unique. Therefore it's essential that the identifier value is a meaningless, system-generated, universally unique, value. If not it's an application defect waiting to happen.

Further, if the identifier value is never externalized (it's a sort of relocatable address) the system can also take more responsibility for the model and abstract away and provision functions like for example "bless", "transmogrify" - runtime type conversion - which can later in the development cycle of the product add huge new capabilities.

If "identified by" was removed the system still needs a capability to locate a specific object. The only two I can think of are:

- Value based searches on specific attribute values.
- A namespace in which specific important objects can be tagged.

The first one is obvious and has its own issues - do we go down the relational path of polluting the model (like in SQL) with "index by" or do we index every attribute value and invert the whole thing? or do we employ some statistical mechanism that watches access paths and "does the right thing" ...

The second one (name spaces) has been used before with some success with object databases like Ontos and Genstone. In the case of Ontos the name space was hierarchical - like a file system. There were functions to navigate this space and add/delete and make association between symbols (a data type) and the hidden object references. (There was a never a guarantee that these relationships would be maintained in the event an object reference was changed by the system).

The application used the names space by sparsely populating it with the names (tags) of specific important objects - like the root object of an object graph e.g. in a say a company->dept->employee model the one and only company object would be referenced in the name space like: COMPANYA->hidden_company_object_reference. The priming query would be to retrieve this special one and then using graph traversal primitives locate the target object. The underlying mechanisms activated (read into memory) the graph as it was being traversed.

Alternatively the target object could be retrieved directly using a value based query - without activating the graph.

The trade off here is modeling purity versus a lot of complex code to implement it, however if there was another way to do this that improved the model without significant cost and complexity, that could scale ...

**Comment by dselman** [comment]
I am going to close this because Hyperledger Fabric's store is based on a Key-Value store, with the keys being strings and the values being arbitrary bytes. Composer stores resources in the KV store using a compound key <resource type> <resource id>.

Identifiers are also used to expose resources over REST, using the standard GET/PUT/POST etc verbs.

Identifiers do not need to be universally unique, only unique within the scope of their resource type. I.e. it is fine to have a Car resource with the identifier ABC and a Driver resource with the identifier ABC.
