### ISSUE TITLE
Documentation- Fabric Versioning updates needed

### ISSUE THREAD

**Issue by harrika1982** [hyperledger/composer#2015]
Some of the images in the documentation show the incorrect version of Fabric
## Context
HEre's the link to the page: https://hyperledger.github.io/composer/introduction/solution-architecture.html

This image needs to be updated with 0.6 deprecated and updating Fabric to 1.0 GA
<img width="760" alt="screen shot 2017-08-28 at 4 10 53 pm" src="https://user-images.githubusercontent.com/15254733/29791612-8eba23d6-8c0b-11e7-92e8-ba3d21115909.png">
﻿﻿

## Context

Causes confusion about the versions of Fabric which are supported. 

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by sstone1** [comment]
@winslet one for you I think - can you just change it to say "Hyperledger Fabric" with no version numbers please?

**Comment by winslet** [comment]
@sstone1 @harrika1982 Sounds good, ive got a whole bunch of doc illustration updates to do this week so ill tie this in.

**Comment by winslet** [comment]
This is what it is looking like right now:

![image](https://user-images.githubusercontent.com/13980028/29870398-245b4f04-8d7f-11e7-84a7-af6c383eced1.png)

Any feedback would be good in the next couple of hours @sstone1 @harrika1982 👍

**Comment by winslet** [comment]
Sorted with #2041
