### ISSUE TITLE
A Process for Installing Composer on Red Hat Enterprise Linux

### ISSUE THREAD

**Issue by adrianblakey** [hyperledger/composer#2028]
There is excellent support for installing on MacOs and Ubuntu but it's a bit of a black hole for RHEL. Those of us who have to labor in IT are faced with the reality of running on RH which has some slight quirks.

## Context
I needed this and got it to work so I'll answer my own request below and given a bit of spare time create the doc and pull request. But in the meantime probably better that it's written down somewhere at least ...

## Expected Behavior
Composer installed and running on RHEL.

## Actual Behavior
Composer installed and running on RHEL.

## Steps to Reproduce
Prerequisites:

A mostly virgin RHEL 7.3 instance (in my case running on AWS)

As root.

Step 1 - install Docker CE

Note: Since docker has split its release into EE and CE Red Hat no longer distributes docker and CE must be installed.

1.0 Just in case an old docker is on the machine:
yum erase docker
rm -rf /var/lib/docker/
1.1 Install the following RH packages:
yum install -y yum-utils device-mapper-persistent-data lvm2
1.2 Set up the docker repo and yum install it
wget https://download.docker.com/linux/centos/docker-ce.repo
yum-config-manager --add-repo docker-ce.repo
yum makecache fast
1.3 Install the selinux dependency.
wget ftp://195.220.108.108/linux/centos/7.3.1611/extras/x86_64/Packages/container-selinux-2.9-4.el7.noarch.rpm
rpm -i container-selinux-2.9-4.el7.noarch.rpm
1.4 Set up a service daemon
mkdir -p /etc/systemd/system/docker.service.d/
cat > /etc/systemd/system/docker.service.d/docker.conf
[Service]
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2375 -H unix://var/run/docker.sock
ctl-d
1.5 Expose the DOCKER_HOST port (insecurely) externally:
cat > > /etc/docker/daemon.json
{
    "insecure-registries" : [ "the_fqdn_of_the_machine:2375" ]
}
ctl-d
1.6 Install docker CE
yum install docker-ce
1.7 Start the daemon
systemctl daemon-reload
systemctl restart docker
1.8 Make sure it's running:
docker ps

2 Install docker-compose
2.1 curl -L https://github.com/docker/compose/releases/download/1.14.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

3. Install git

Note: the version of git supplied by RH is (of course) old as the hills. So install from source.

3.1. Remove any vestiges.
yum erase git
3.2. Grab some recent sources.
curl -L https://www.kernel.org/pub/software/scm/git/git-2.14.1.tar.xz | tar -Jxv -C /usr/src
3.3. Install packages needed to make it.
yum install curl-devel expat-devel gettext-devel openssl-devel zlib-devel
yum install gcc perl-ExtUtils-MakeMaker
yum install curl-devel
3.4 Make it
./configure --with-curl --with-expat
./make
./make test
./make install
export PATH=/usr/local/bin:$PATH
git --version

3. Install NodeJS
Note: yet again RH does their best to provide something - but it's old ...
3.1 Follow the instruction here: https://nodejs.org/en/download/package-manager/
3.2 If you've installed docker and git you might not need the build tools - but 
sudo yum groupinstall 'Development Tools'
3.3 curl --silent --location https://rpm.nodesource.com/setup_6.11.2 | sudo bash -
3.4 sudo yum -y install nodejs
3.5 Once node is installed update npm: npm install npm@latest -g

## Context
Install composer

## Your Environment

* Operating System and version (desktop or mobile): RHEL 7.3

**Comment by jdockter** [comment]
For 1.3, I had to go to, ftp://195.220.108.108/linux/centos/7.4.1708/extras/x86_64/Packages/container-selinux-2.21-1.el7.noarch.rpm

For 1.4, I had to add an extra ExecStart= to clear before , per https://github.com/moby/moby/issues/14491
