### ISSUE TITLE
As a playground user I can assign roles to a new ID card

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#2032]
When I create a new ID card, I need to be able to assign roles to the identity in that ID card (such as PeerAdmin or ChannelAdmin), so that I can use the new ID card to install and start a new business network.

**Comment by jt-nti** [comment]
Related to #1985

**Comment by winslet** [comment]
**Hifis:**

![transaction registry copy 31](https://user-images.githubusercontent.com/13980028/30166274-bf25b5cc-93da-11e7-9164-364db2850a4b.png)

**Code for checkboxes:**

https://codepen.io/the_winslet/pen/QyzZLJ

Any questions let me know! 🍫
