### ISSUE TITLE
Identities Nitpicks II - Attack Of The Nitpicks

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#2044]
Please leave any new identities nitpicks **as comments** on this issue.

I'll take care of combining them with the left over nitpicks from #1930 as a checklist here...

# Current nitpicks

- [ ] Back button does not work as expected on deploy or create card pages

- [ ] Googly eyes on create card radio buttons (OSX/Chrome)

![image](https://user-images.githubusercontent.com/3535067/29520978-73dad3a2-867b-11e7-9182-cd394259e2c8.png)

- [x] **Save** button on create card connection profile page should be **Next**

- [x] Long identity name handling is not great (although unrealistic I admit) . **nick**

<img width="370" alt="screen shot 2017-08-21 at 14 03 12" src="https://user-images.githubusercontent.com/7118158/29520616-b5352af2-8679-11e7-9020-e5cbe1629055.png">

- [x] Hitting _Return_ on the keyboard on the *Create ID Card* dialog doesn’t submit the form (i.e. click _Create_), even though the Create button appears to be highlighted. Have to _Tab_ to or click on the Create button first. Not sure if this is intentional, but feels a bit weird.  **nick**

- [x] Inconsistent capitalization in table - **In Use** vs **ISSUED**
![image](https://user-images.githubusercontent.com/26481967/29521068-cb1fecec-867b-11e7-89f6-7cd87db49929.png) **nick**

- [ ] Import an id.card with a card.card file in the credentials part of the card. When I export that identity it adds a card.card file into the exported id.card and it's size is different to the one in the original id.card. However this file wasn't meant to be there so what got exported ?

- [ ] 'Drop here to upload or browse' container seems to have a border issue. When hovering over it the border is dashed, but upon moving the cursor away it quickly changes to a solid border before fading away. This is also the only import option that has such a slow fade.

- [ ] Not obvious **ID Registry** is clickable

![image](https://user-images.githubusercontent.com/25582377/29522965-25398290-8683-11e7-9797-538151d3cc5c.png)

If I hover over it, I think it changes colour (and it really is only a very slight change). Hovering over Log Out is a bit more obvious
Also note that the dropdown icon never changes next to admin @winslet  what do you suggest for this?

- [ ] Hovering of the left side (Sorry can't capture the image) on the words "Web 

- [x] It would be nice if the name/description defaulted to the name/description of the selected network when deploying

- [x] When importing a BNA file, why are the business network name and the description not filled out for me - even though I've uploaded the BNA?  The details are in the BNA's DNA

- [ ] Nothing to indicate that I can scroll down (I have another connection profile down there!)

![screen shot 2017-08-21 at 15 30 18](https://user-images.githubusercontent.com/7118158/29523680-b55f68ec-8685-11e7-9119-e86779c0ed75.png)

- [ ] The heading and buttons should scroll with the rest of the login page content **JT**

- [x] Identities don't seem to be sorted on the identity registry page **Caroline**

![image](https://user-images.githubusercontent.com/3535067/29529010-05b34984-8696-11e7-8a52-20de4fa45fc6.png)

- [ ] There is no way to tell if an ID card will be exported with enrollment secret or certificate/privateKey. (Exporting cards with an unused secret vs enrolled credentials have pretty important implications.)

- [ ] This is using basic-sample-network, with two identities, so you can picture the scene. If you use one ID and add a query file to the network (where previously no .qry exists), and then change to the other/new identity, Playground tries to display a query file that does not exist in the editor.

![screen shot 2017-08-23 at 16 44 06](https://user-images.githubusercontent.com/16639383/29625278-2a6326b2-8823-11e7-969f-4152fe000c7c.png)

(Probably should have taken a better screenshot... there is no Query File in the nav either)

- [x] Playground tutorial link is missing from login page on a local playground install after one-script-install - see #2054

- [x] When I start creating a new Business Network and give a name and a description to it, I'm able to write more than the text field actually allows.  **Caroline**

![issue_720](https://user-images.githubusercontent.com/31318197/29917039-8f8bb8ae-8e38-11e7-9761-b67e8ddb165e.png)

- [ ] If I import a network with the same name as a sample network and select it, both are selected

<img width="228" alt="screen shot 2017-08-31 at 10 43 08" src="https://user-images.githubusercontent.com/7118158/29917387-c25e3814-8e39-11e7-86f7-7b8f0e94949a.png">

- [x] Reword titles on the login screen. Suggestions: do not to use the overloaded term 'Wallet' (@davidkel); replace 'Identities for <profile-name>' with 'Identity cards for <profile-name>' (@dselman) 

![image](https://user-images.githubusercontent.com/25582377/29919022-91dcecd4-8e3f-11e7-83d6-16b2dd3cb1f6.png)

- [ ] On _Deploy New Business Network_ screen, there is no visual indicator that the _Name_ field is mandatory and that the _Description_ field is optional.

- [ ] When selecting the Admin option when creating an ID card, it would be more helpful if both Peer Admin and Channel Admin were both selected by default **JT**

![image](https://user-images.githubusercontent.com/3535067/30558677-2d0f2d48-9caa-11e7-942d-8e424dcc0ef3.png)

# Known issues

- ~~As a user, I can issue an identity to a participant and download an ID card to give to them~~ #1955 Fixed!

- Organising the ID registry, including where it should go and what it should do #1976 

- ~~As a playground user i can create an id card with certificates~~ #1985 Fixed!

- ~~As a playground user I can assign roles to a new ID card~~ #2032 Fixed!

- ~~Esc results in error being thrown~~ #1958 Fixed!

- Playground running in Edge: Create New Identity button not responsive #2128

**Comment by davidkel** [comment]
![image](https://user-images.githubusercontent.com/25582377/29917119-dd9af2e4-8e38-11e7-8a8e-abf83760754e.png)
in define there was a summary, clicked edit couldn't find a way back, clicked test then define returned me to above screen which has a pen and eye underlined implying view mode but still looks like edit mode for the file.

**Comment by georgschultz** [comment]
![issue_720](https://user-images.githubusercontent.com/31318197/29917039-8f8bb8ae-8e38-11e7-9761-b67e8ddb165e.png)

When I start creating a new Business Network and give a name and a description to it, I'm able to write more than the text field actually allows.

**Comment by sstone1** [comment]
<img width="321" alt="screen shot 2017-08-31 at 10 41 15" src="https://user-images.githubusercontent.com/7118158/29917377-ba9df86c-8e39-11e7-946f-f22b3c1aa206.png">

- [ ] These sample networks need different icons

<img width="228" alt="screen shot 2017-08-31 at 10 43 08" src="https://user-images.githubusercontent.com/7118158/29917387-c25e3814-8e39-11e7-86f7-7b8f0e94949a.png">

- [ ] If I import a network with the same name as a sample network and select it, both are selected

**Comment by davidkel** [comment]
![image](https://user-images.githubusercontent.com/25582377/29917421-df9a26d6-8e39-11e7-8a0d-12bfa928d290.png)
browser window not big enough, modal is clipped with no way to scroll

**Comment by mbwhite** [comment]
- [ ] When entering a business network name, error are highlighted - with the phrase 'alpha-numeric lowercase'.  yet  -  is also accepted and is only non-alpha-numeric that is.

**Comment by davidkel** [comment]
![image](https://user-images.githubusercontent.com/25582377/29917856-2aa0aa00-8e3b-11e7-88bc-ddefc16e4447.png)
Option 1 is an interesting one to present someone using the web profile :slightly_smiling_face:
Option 2 it’s not obvious to me that “+ Add to my Wallet” is actually a button to click

**Comment by jt-nti** [comment]
Not really identity related but leaving this here for now...

Create a new model file then immediately delete it gives and error:

![image](https://user-images.githubusercontent.com/3535067/29918070-ef0fc614-8e3b-11e7-9c5f-77e31d7116b2.png)

**Comment by davidkel** [comment]
![image](https://user-images.githubusercontent.com/25582377/29918073-f0ccb1f6-8e3b-11e7-820d-622afd3c0ecf.png)
should we show the download icon if nothing will ever enable it ?

**Comment by EllisHenderson** [comment]
<img width="1121" alt="screen shot 2017-08-31 at 11 00 00" src="https://user-images.githubusercontent.com/15138976/29918082-f6aa5bfa-8e3b-11e7-807c-b52becab55ac.png">

If you create an additional model file and then delete it, the above error message is displayed.

<img width="997" alt="screen shot 2017-08-31 at 11 00 18" src="https://user-images.githubusercontent.com/15138976/29918081-f6a98c0c-8e3b-11e7-8b3c-93d88fe1fc86.png">

The remaining model file then shows the same content as the README and deletes any code which was previously written in the model file.

**Comment by davidkel** [comment]
![image](https://user-images.githubusercontent.com/25582377/29918476-7b3568a0-8e3d-11e7-92a6-1e5e72ec802a.png)
This seems confusing to me. From the screen it isn’t obvious what is going on here, ie the top section are my identities that are in my wallet and the bottom section are Participants in the network that have been associated with ids. If I delete an identity from my wallet I have this screen left and now I have the concept of an ID name which isn’t actually valid anymore as that ID name no longer exists

**Comment by georgschultz** [comment]
when you click update, the pop up window says something like "Deployed successfully". Actually it should say "Update successfully" or something like that

**Comment by bestbeforetoday** [comment]
On _Deploy New Business Network_ screen, there is no visual indicator that the _Name_ field is mandatory and that the _Description_ field is optional.

**Comment by mbwhite** [comment]
- [ ] When importing a BNA file, why are the business network name and the description not filled out for me - even though I've uploaded the BNA?  The details are in the BNA's DNA

**Comment by davidkel** [comment]
Should we call this panel a wallet any more ?
![image](https://user-images.githubusercontent.com/25582377/29919022-91dcecd4-8e3f-11e7-83d6-16b2dd3cb1f6.png)

**Comment by EdMoffatt** [comment]
- After the single line install, you get an empty set of cards for web browser, and then below that is your card for the hlfabric runtime.  This looks a bit odd, especially if you stick with using hlfabric and never deploy anything to the web browser...  Suggest we could have Web Browser always at the *bottom* of the list?  That way if you have any cards for *real* Fabrics then they appear at the top (as we assume that if you're at the stage of connecting to real Fabrics, they're probably more important to you than the Web Browser profile at that point)

**Comment by davidkel** [comment]
@jt-nti are any of these something need to be fixed for the 0.16.0 release ?

**Comment by jt-nti** [comment]
@davidkel it would be nice to fix a few more but I don't think they're high priority for 0.16.0

**Comment by sstone1** [comment]
No real updates for ages; closing.

**Comment by jt-nti** [comment]
Re: Back button does not work as expected on deploy or create card pages

Back button issues are back in #2860!
