### ISSUE TITLE
Default file when connecting to a network should always be the ReadMe

### ISSUE THREAD

**Issue by KaiUsher** [hyperledger/composer#2047]
When you connect to a business network, the default file which is displayed should be the ReadMe file. However, the default file currently depends on which file was last selected before logging out. This also remains across different IDs - if you log out of one ID/network with ACL selected, when you log in to another the ACL will be selected.

## Expected Behaviour
The ReadMe file should always be the default file.

## Actual Behaviour
The default file is whichever file was last in the editor of a business network.

## Steps to Reproduce
1. Create a network.
2. Connect to the network and select something other than the ReadMe file.
3. Log out and create a new identity/network.
4. Connect to the new network and see the ReadMe is not selected.

**Comment by caroline-church** [comment]
Fixed so closing
