### ISSUE TITLE
As a user I want to resolve the relationships in query results

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#2051]
## Context
Users need to be able to execute named and dynamic queries, and resolve the relationships in the assets/participants/transactions in the result set.

## Expected Behavior
Should be able to set a flag to optionally resolve relationships.

## Actual Behavior
Not currently supported.

## Possible Fix
Add a flag to automatically resolve relationships. Note however that the resolved relationship must be filtered by the ACL engine. If the ACL engine prohibits access what should the behaviour be?

**Comment by nklincoln** [comment]
@sstone1 - this appears to have been fixed upstream now?

**Comment by fenglianxu** [comment]
@nklincoln We have added **resolve** filter to enable this via filter query not for the named query yet. This is still a valid story for the named query.

**Comment by fenglianxu** [comment]
@dselman The **resolve** is supported via filter feature not for the named query. This has been done already.  We are not going to support this for the named query per a discussion between @mahoney1 and @sstone1.
I can close this item now.
