### ISSUE TITLE
As a user I want to use aggregates in queries

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#2052]
## Context
Users need to be able to perform basic statistical aggregation (e.g. COUNT) over the result set from a query.

## Expected Behavior
Extend CQL to support aggregation operators, and compile those to CouchDB Mango expressions for execution by Mango.

## Actual Behavior
Not supported.

## Possible Fix
How does the ACL engine get applied?

**Comment by mgcox** [comment]
this is an essential request to almost all business use-cases
