### ISSUE TITLE
As a user, when I issue a new identity I am not mislead into treating the secret as a password

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2056]
When we issue a new identity we automatically define maxenrollments for -1. This has lead to confusion about the roll of secrets looking like passwords as well as the problem where 2 users who enroll (or a user who enrolls again) only the first certificate issued that is activated into the identity registry will be authorised. All other users get the reponse that the id has not been registered.
This relates to #1761

**Comment by sstone1** [comment]
We should definitely do this; it would enforce the fact that this is a one-time secret. There's not really a good use case for being able to enroll multiple times, and leaving the enrollment ID available for unlimited re-enrollment with an 8-character secret by default seems like a bit of a security hole for me.

Happy to have a connector specific option to cater for users who accept what they're getting into by changing it from 1.

**Comment by davidkel** [comment]
A further question will on this is what happens when the certificate expires ? what will be the documented process for obtaining a new certificate and rebinding it to the participant ?
There may be more scenarios which we should provide documentation for. Eg revoking a current identity and binding a new one etc

**Comment by davidkel** [comment]
Final note, playground will not support the ability to change the max enrollments option. It's defined here #1704

**Comment by davidkel** [comment]
If a cert expires, does the fabric ca then allow you to enroll using the same name again ? because you cannot re-enroll. This may all be related to the revoke, re-enroll capabilities of the fabric-ca that we still need to look into.
As a side here are the security scenarios to consider for documentation
1. User loses their one and only copy of crypto material
2. Admin wants to revokes that certificate on composer (composer runtime maintains a blacklist of all revoked certs) and assign a new certificate to the same participant.
3. Certificate expires 

This change doesn't introduce any more problems (outside of the admin id) because if you bind a user to an identity, then someone enrolls that identity and tries to use it they won't be allowed to use it for the participant the original one is bound to. Users get the problem because they mess up the keyValStore or point to a different place for it and as such say the user has not been registered as it pulls down a new certificate and as that certificate isn't bound to a participant it says the id has not been registered. This change would help in that scenario because that error would not be shown but rather one from the CA saying cannot enroll that id (or whatever error it decides to output).

So in retrospect I don't think we need any specific documentation associated with this change, but we do need to provide documentation about how composer does security and to address the above example scenarios

**Comment by davidkel** [comment]
Now in master
