### ISSUE TITLE
Identity in Playground cannot be used in Rest-Server - The current identity has not been registered

### ISSUE THREAD

**Issue by caveman7** [hyperledger/composer#2065]
## Context
Identity issued in Composer Playground can only be used in composer-rest-server if it is not yet activated. Likewise, identity issued in Composer Playground cannot be used in composer-rest-server once it is activated in Composer Playground. By "cannot be used", the error message is "The current identity has not been registered"

## Expected Behavior
All identities can be used across Playground, REST Server and CLI

## Actual Behavior
Already described in context

## Steps to Reproduce

**Scenario 1**
1. Start the fabric using ./composer.sh command
2. Deploy a .bna file via Composer Playground. I used a customized version of the perishable-network
3. Connect to the network and run the SetupDemo transaction to provision the participants (creating participants manually is also OK)
![screen shot 2017-09-06 at 10 47 09 am](https://user-images.githubusercontent.com/21098213/30093720-7c2942fa-92f1-11e7-9696-65ec64d3a230.png)
4. Go to ID Registry (as admin) and issue a new identity for one of the participants (in this case grower_banana)
![screen shot 2017-09-06 at 10 54 39 am](https://user-images.githubusercontent.com/21098213/30093774-d56cc788-92f1-11e7-8793-fb2135d0dbef.png)
![screen shot 2017-09-06 at 10 56 33 am](https://user-images.githubusercontent.com/21098213/30093808-150c093a-92f2-11e7-80fd-0b128bd21dab.png)
5. Do not use the participant i.e. the status should stay **ISSUED**, not **ACTIVATED**
6. Setup authentication for composer-rest-server. In my case, I used LDAP
`export COMPOSER_PROVIDERS='{ "ldap": { "provider": "ldap", "authScheme": "ldap", "module": "passport-ldapauth", "authPath": "/auth/ldap", "successRedirect": "/", "failureRedirect": "/failure", "session": false, "json": true, "profileAttributesFromLDAP": { "login": "uid", "username": "uid", "displayName": "givenName", "email": "mail", "externalId": "uid" }, "server": { "url": "ldap://ldap.xxx.com:389", "bindDn": "uid=aldred,ou=Users,o=xxx,dc=xxx,dc=com", "bindCredentials": "caveman", "searchBase": "ou=Users,o=xxx,dc=xxx,dc=com", "searchFilter": "(uid={{username}})" } } }'`
7. Start composer-rest-server with the -m true flag  
`composer-rest-server -p hlfv1 -n perishable-network-custom -i admin -s adminpw -N never -m true`
8. Perform authentication
![screen shot 2017-09-06 at 11 06 16 am](https://user-images.githubusercontent.com/21098213/30094023-713a43a6-92f3-11e7-851f-06c11202fa90.png)
9. Insert the enrollment ID and Secret and set the default identity
![screen shot 2017-09-06 at 11 07 16 am](https://user-images.githubusercontent.com/21098213/30094035-97880c3c-92f3-11e7-8888-a87951590738.png)
![screen shot 2017-09-06 at 11 08 45 am](https://user-images.githubusercontent.com/21098213/30094067-c815bf8e-92f3-11e7-878f-a0bfc7715eef.png)
10. Invoke one of the APIs. As seen, it is successful.
![screen shot 2017-09-06 at 11 09 44 am](https://user-images.githubusercontent.com/21098213/30094089-f307e230-92f3-11e7-8d90-fc3e3b7c210d.png)
11. Back to Composer Playground, click "Use Now" in the participant (i.e. grower_banana)
![screen shot 2017-09-06 at 11 30 56 am](https://user-images.githubusercontent.com/21098213/30094504-e49c3b9e-92f6-11e7-98b1-e4099696e6ae.png)

**Scenario 2**
1-4 Same as Scenario 1
5 Click **Use Now** on the the participant in which the identity is issued (grower_banana)
![screen shot 2017-09-06 at 11 37 52 am](https://user-images.githubusercontent.com/21098213/30094692-ebd81fb2-92f7-11e7-9052-9c319577b4a4.png)
6-9 Same as Scenario 2
10 Invoke one of the APIs. As seen, it is unsuccessful
![screen shot 2017-09-06 at 11 44 04 am](https://user-images.githubusercontent.com/21098213/30094821-d7073838-92f8-11e7-98cd-20a18860a301.png)

## Your Environment

* Version used: 0.12.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome  60.0.3112.113. node.js 6.10.3
* Operating System and version (desktop or mobile): macOS Sierra 10.12.6
* Link to your project: Custom .bna file: https://github.com/caveman7/perishable-network-custom

**Comment by davidkel** [comment]
This is a consequence of #1761

**Comment by sstone1** [comment]
This is also working as designed.

We see a lot of misunderstanding around the enrollment secret - it might not be the case here - but in general, a lot of users end up treating the generated enrollment secret as a password. The enrollment secret is a token that you can pass to the Fabric CA in exchange for an enrollment certificate. The enrollment certificate is used to sign transactions and is used to identify you on the Blockchain.

We need to guide our users towards proper management of their enrollment certificates, and we will do that by restricting the default number of maximum enrollments to 1 in issue #2056. This was the behaviour in Fabric v0.6, and the behaviour was much more indicative as to what was going on under the covers. I am asking @jt-nti to add a warning message in playground around this behaviour as well.
