### ISSUE TITLE
Investigate using VSCode editor component and Language Server for Playground

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#207]
The existing CodeMirror component used for editing CTO files is functionally limited and the syntax highlighting rules are hard to maintain and keep in sync with the parser.

It would be much more powerful to use the VSCode editor component, and the full Language Server implementation developed by mgk. The Language Server uses the ModelManager and parser to validate CTO files.

https://github.com/Microsoft/monaco-editor
https://code.visualstudio.com/blogs/2016/06/27/common-language-protocol

The goal of this issue is to perform a technical investigation of the feasibility of using the VSCode component inside an Angular application, tied to a Node.js Language Server.

**Comment by mbwhite** [comment]
Initial thoughts

- Monaco doesn't have direct support for the Language Server Protocol; rather it has client side formatting and (limited) validation.
- A number of github projects have taken the 'smarts' from VSCode and made them available as extras to Monaco - see for example https://github.com/Microsoft/vscode-json-languageservice/tree/master/src/services - which has taken the JSON from VSCode and pulled it into Monaco. Likewise with the CSS support
- A closer project is https://github.com/mbana/monaco-go which is using websockets to talk to the language server and provide a go implementation.  Still looking very experimental

First thoughts are that the full stack Monaco -> TCP/IP -> LanguageServer is new ground with higher risk. 

(1) Incorporate the Monaco editor in the Playground - it's a good editor and we could client side highlighting support etc. 
(2) Make the Language server available and easy to stand up for those that might be interested
(3) Investigate how easy it would be to follow Microsoft's lead and replicate what they did for CSS/JSON. Not yet compared the code to see how much similarity there is. 

Plan to look at (3) and see the feasibility of that and go from there.

**Comment by mbwhite** [comment]
Test repo created for this. 

https://github.com/mbwhite/monaco-composer/blob/master/README.md

**Comment by mbwhite** [comment]
Update: we can certainly move to use the Monaco editor - however the first stage is going to be to have to be based on a plugin variant of the MS JSON or CSS.  It would help to set the stage for future use of the Language server.

**Comment by winslet** [comment]
@Tobias-Hunter could you pull out the hex codes you put in for the current code editor? 

I have a couple of updates to the background colour of the code editor which we can sync on 👍

**Comment by Tobias-Hunter** [comment]
Current UI Hex Codes:
Background: #424747
Comment & Line Number: #B2B9B9
Keyword: #FEDB96
Variable: #B0BEF3
Variable 2: #FF9F9F
Anything not defined above: #FFFFFF

Although I do wonder if these will align the Monaco editor!

**Comment by mbwhite** [comment]
thanks - will give it a go and see what happens!

**Comment by mbwhite** [comment]
(1) Updated the https://github.com/mbwhite/monaco-composer repo and we've got some basic colour highlighting and swapping between languages
(2) However looking at the Angular2 integration - there's a bit of a snag... see https://github.com/Microsoft/monaco-editor/issues/18#issuecomment-261289582

This doesn't look that straightforward to bring in Angular-2

**Comment by caroline-church** [comment]
That snag doesn't look too bad i think we will be able to work around it like they have done

**Comment by winslet** [comment]
update to @Tobias-Hunter 's codes above: 

Background colour: #393F4F
and if we need it a highlight background colour: #262A35 

@mbwhite is there a way you could screengrab the current document which contains all the css variables so we can try and add any further colours if we need to? (im not sure how many values the monaco editor has) 👍 cant wait to get it in!

**Comment by EdMoffatt** [comment]
Shifting this over from Playback 3 to Playback 4, as it looks like we're still working on it

**Comment by dselman** [comment]
This also seems to be based on Monaco:
https://sourcegraph.com/github.com/sourcegraph/checkup/-/blob/CONTRIBUTING.md

**Comment by sstone1** [comment]
Closing as this is blocked and won't happen any time soon.

**Comment by dselman** [comment]
There seems to have been some progress made on making this easier:
https://github.com/TypeFox/monaco-languageclient

**Comment by dselman** [comment]
@m-g-k fancy taking a look at this?

**Comment by sstone1** [comment]
As far as I know, nobody is working on this at the moment or planning to work on it, so closing. 
If somebody wishes to work on this in the future, then please reopen this issue or open a new issue.
