### ISSUE TITLE
REST Server docs niggles

### ISSUE THREAD

**Issue by awjh-ibm** [hyperledger/composer#2077]
# Generating a REST API
- Outdated screenshots for the composer and swagger API view.
- Link and text under "Looking at the generated APIs" uses 0.0.0.0 instead of localhost which is referenced by the composer rest server screen and other parts of the doc.

# Publishing events from the REST server
- Page doesn't make it clear that events needs to be specified in .bna, users who are using their tutorial files won't see any events in the testing with wscat.

# Enabling authentication for the REST server
- Rogue "=======" at bottom of doc.

# Enabling multiple user mode for the REST server
- Bottom of "Starting the REST server with multiple user mode enabled" section where doc informs user of their error could link to "Enabling authentication for the REST server" doc as that is where the information to solve the issue is.
- No clarity on which users can be registered, on tutorial files admin can be registered with adminpw but TRADER1 and TRADER2 can't. Admin also returns with a null for the participant field when using GET /system/ping

# Deploying the REST server for a business network
- No informing the user that the value within <> should be changed in the section to copy for item 2 of the section "Run the REST server in a Docker Container - with no security (eg. Dev/Test)"

**Comment by caroline-church** [comment]
done so closing
