### ISSUE TITLE
System runs out of memory after making few API calls using v0.12.0

### ISSUE THREAD

**Issue by NikhilNanjappa** [hyperledger/composer#2081]
Hi @davidkel , as per [your suggestion comment](https://chat.hyperledger.org/channel/composer?msg=5sTMEyPwyEP3sNGhR), please find below more details of the issue below.

### Issue
After upgrading to latest `v0.12.0`, we are facing significant memory consumption of the API server. Making API calls for a few times (around 15 to 20), especially the POST ones, the system runs out of memory and the API becomes unresponsive giving `Timeout error`.

Any suggestions or minimum/recommended requirements using the new version ?

### Environment
We use AWS free tier (t2.micro) with 1 GB of RAM and 7.5 GB of EBS.
We use the hlfv1 and the composer version is 0.12.0. And composer runs with the default loopback memory storage for the identities.

### Measurements taken
We use `htop` utility and some of the linux commands (ex. free) to monitor RAM and CPU usage time to time. CPU usage always looked fine but there are issues with the memory usage as we go on hitting the APIs. The memory being used by the `chaincode` process increases as API calls increase and the system becomes un-responsive when 55% to 60% of the memory allocated to `chaincode` process or in other words if the free memory being down to 66 MB or less.

**Htop screenshot**
![image](https://user-images.githubusercontent.com/5576981/30164458-832493aa-93d4-11e7-9e44-e9ffdbce8b60.png)

**Free command screenshot**
![image](https://user-images.githubusercontent.com/5576981/30164481-95ebafdc-93d4-11e7-93b7-40a19212c71d.png)

> Note: We did not get this problem with the previous version (`0.11.0`).  But that version does not come with the transactions list query, so there was a chance of us not hitting enough API calls in the previous versions.

**Comment by davidkel** [comment]
Our minimum recommended memory if you want to run both a real Hyperledger fabric runtime and single business network inside of it is 4Gb. I am really surprised you ever got it working all of this running in a single VM with just 1Gb of memory

**Comment by NikhilNanjappa** [comment]
@davidkel - Thanks for confirming the minimum recommendation. 

On a different note though, do you know using the 'passport github strategy' how to logout of the authenticated client from the rest server because using the `/logout` does not seem to log the user out.

**Comment by sstone1** [comment]
Closing as @NikhilNanjappa needs more memory! Note that Node.js chaincode support in Fabric should hopefully reduce our memory consumption by quite a bit once it is delivered.
