### ISSUE TITLE
Business network deployment error because of bad certificate parsing

### ISSUE THREAD

**Issue by fsegouin** [hyperledger/composer#2090]
## Context

Looks like it's a go error from the certificate parsing method. Unsure if it's a bug from `composer` or my certificates. Certificates were created by following the tutorial.

Command:
```
composer network deploy -p hlfv1 -a network@0.0.1.bna -i PeerAdmin -s foo
```

## Expected Behavior

Should return `Command succeeded`.

## Actual Behavior

Here is the error returned:

```
✖ Deploying business network definition. This may take a minute...

Error: Error trying deploy. Error: Error trying install chaincode. Error: Failed to deserialize creator identity, err ParseCertificate failed asn1: structure error: tags don't match (2 vs {class:0 tag:6 length:7 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @2

Command failed
```

## Possible Fix

By issuing new certificates? Haven't tested as I just followed the tutorial from A to Z and did not try to issue my own.

*Note*: deploying via the Composer Playground does work.

## Steps to Reproduce

1. Follow the developers tutorial
2. Create a new business network from the yo generator
3. Use `composer archive create` to create the .bna file
4. Try to deploy the network with `composer network deploy`

## Existing issues

No issues found matching this error.

## Context

Went through the developers tutorial without issues, then created my own business network, exported it as a .bna file and tried to deploy it.

## Your Environment

* Version used:
```
$ composer -v
v0.12.0
```
```
$ docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:12:06 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
* Operating System and version: macOS 10.12.6

**Comment by davidkel** [comment]
The error here doesn't come from composer, it is a fabric message. I would suggest raising an jira against hyperledger fabric. It sounds like you tried to generate your own certificates and so there could be some requirement that fabric has for certificate generation.
