### ISSUE TITLE
As a user, I can safely migrate my Composer solutions to newer versions of Composer

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#2097]
A top level epic for migration. We need to perform manual testing and analysis of our existing migration capability, using `composer network upgrade`, to determine how easy and safe it is for users to pick up new versions of Composer.

I say manual testing, paging @nklincoln to consider the possibility of automated migration testing.

- [ ] #2513 Better checking when no migration required to allow network upgrade

**Comment by smartapp-ep** [comment]
The ability or options for production business network to upgrade runtime and import old data is one of the critical barrier we are faced with, if this is unlikely in forseeable roadmap, what'd be the high level suggestion or work around? i think at least application developers can develop some db scripts if the schema change of each minor release is provided? or what would be the advice? look forward to any feedbacks.
