### ISSUE TITLE
As a user, I can use the historian to track business network log level changes

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#2099]
The historian should track the business network log level changes. This will mean turning the business network set log level operation into a proper system transaction.

**Comment by mbwhite** [comment]
.. in addition the *resetBusinessNetwork* and *undeploy* network are not transactions.

They can be, no problem.  As part of the #1623 I can add in Network level protection for log changes. Without making it a full transaciton.

**Comment by mbwhite** [comment]
*Status*: 
Waiting until post release 0.13.2 - as this will require updating version to 0.14.0
