### ISSUE TITLE
As a user, I want to run Composer using Node.js v8.x

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#2100]
`fabric-client` can now be used on Node.js v8.x (thanks to a gRPC upgrade), which means that Composer now runs correctly against Node.js v6.x (supported today) and Node.js v8.x.

We should provide full support for Node.js v8.x. Full support requires that we run regular automated unit and system tests against Node.js v8.x, which means updating the Travis configuration.

On a related note, Fabric v1.1 will be introducing support for Node.js chaincode, and will come with Node.js v8.x. Once this is out, and we switch to it, we will drop support for Node.js v6.x and just depend on Node.js v8.x everywhere. This is good for the users (latest levels of language and features) and good for us contributors (latest levels of language and features)!
- [ ] change travis build from 6 to 8
- [ ] change docker files to build from node 8 rather than node 6
- [ ] change package.json files to be node >=8, npm >=5
- [ ] prereqs.sh + documentation

**Comment by davidkel** [comment]
see #2361 as this has has possibily caused issues in being able to support node 8 client side.

**Comment by davidkel** [comment]
It builds in travis if I disable jsdoc generation. It fails due to a change in node 8.5 as described here
https://github.com/jsdoc3/jsdoc/issues/1438
Hopefully simple to fix

**Comment by davidkel** [comment]
Yep simple to fix, builds run clean in travis using node 8.
