### ISSUE TITLE
Serviceability: Problem determination difficult due to [Object object] references

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2104]
The logs contain to many [Object object] references for parameters, return values etc for example
```
@JS : CompiledAclBundle        :execute()                 Function threw error [object Object]
@JS : CompiledAclBundle        :execute()                 < false
```
What error did the function throw ?

This is just one example. 
The is the result of how the logging message is constructed

**Comment by ScottMorris** [comment]
I've been running into this all afternoon.  It has been making debugging the ACL rules a big pain.

From what I've found it has come from `compiledaclbundle.js` (as suggested by the `CompiledAclBundle` Logger name.) and the code that logs the error is,
```
// Execute the function.
const functionName = aclRule.getName();
const func = bundle[functionName];
let funcResult;
try {
    LOG.debug(method, 'Executing function', functionName);
    funcResult = func(resource, participant, transaction);
    LOG.debug(method, 'Function returned', funcResult);
} catch (e) {
    LOG.debug(method, 'Function threw error', e); //<---- Error Message from here
}
```
I'm wondering if it is possible to just append `.message` to `e`, assuming it is throwing an `Error` object, which should output the message.

**Comment by ScottMorris** [comment]
I've setup the composer dev environment to test out my theory on this.  By changing the log statement in the catch block to use `e.message` instead of just `e` the error that is thrown will have its message output in the log.

Here is an example of the output.
```
@JS : CompiledAclBundle       :execute()                Executing function AssignedPeopleCanAddNotes
@JS : CompiledAclBundle       :execute()                Function threw error cannot read property 'toString' of undefined
```

If this is something people want I don't mind submitting a pull request.  I'm just not sure where or what to test for writing a unit test for it.

**Comment by ScottMorris** [comment]
I just noticed I'm still seeing the `Error: Unhandled promise rejection` at the end of the log file after there is an error with an ACL rule, but I haven't tracked this any further.  In my log file it looks like
```
Error: Unhandled promise rejection {}
    at [anon] (/chaincode/input/src/composer/vendor/gopkg.in/olebedev/go-duktape.v3/duk_console.c:55) internal
    at error () native strict preventsyield
    at [anon] (eval:2) strict
    at [anon] (eval:1)
    at [anon] (eval:2) strict
    at [anon] (eval:1)
    at [anon] (eval:1)
    at [anon] (eval:1) preventsyield
    at call () native strict preventsyield
    at [anon] (eval:1) preventsyield
```
