### ISSUE TITLE
Github passport may now not work for rest server authentication

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2109]
A couple of comments have appeared on rocket chat regarding this and now there is a stackoverflow question (possibly from the same person)
https://stackoverflow.com/questions/46164640/github-passport-strategy-for-composer
it suggests that the npm module passport-github now doesn't work (as github have upgraded their api) and that there is a new npm module passport-github2 which has been published from a fork of the original code
We should investigate and update our documentation accordingly if required.

**Comment by rthatcher** [comment]
REST server with authentication working as documented here:
  https://hyperledger.github.io/composer/integrating/enabling-rest-authentication.html
Using v0.12.1

Stackoverflow user has confirmed now working.  I think the argument for authentication on the REST server changed from -S to -a and an old version of the doc was being used.
