### ISSUE TITLE
As a user I have a utility to bulk upload assets and participants

### ISSUE THREAD

**Issue by UdayanDeshmukh** [hyperledger/composer#2119]
Would like to upload JSON format datafile into Hyperledger Composer Asset Registry.

## Context
Most of the Master records data is captured in one of the Enterprise applications of their choice by commercial Organizations. In order to facilitate transition to / assimilation of Blockchain Technology into their existing Technology Platform, there would be a need for ability to extract Master data records from their current legacy applications and upload into the Hyperledger Assets/Participants Registry. Going forward this feature/ability will allow them to keep the Participant Registry in sync with the Master Data captured in off-chain Applications. 

## Expected Behavior
This feature will allow JSON formatted datafile (Thousands/Millions) containing the records extracted from legacy applications to be uploaded into the Hyperledger Registry either as a Batch job to begin with.

## Actual Behavior
I'm given to understand this ability exists in the REST APIs available in Hyperledger - but there is no documentation or sample code available anywhere that I can learn / leverage from.

## Possible Fix
make some sample code available which can be tried out in Online Playground just like the half a dozen sample applications currently available in there.

## Steps to Reproduce
Not applicable

## Existing issues
I have had a chat with experts on the Rocketchat.
But I haven't yet been able to locate any relevant source that I can leverage / learn from. 

I have today posted a question on Stackoverflow as following:

https://stackoverflow.com/questions/46185606/would-like-to-upload-json-format-datafile-into-hyperledger-composer-asset-regist

## Context
Lack of availability of this ability will be a massive show-stopper for large Enterprises looking to adapt Distributed Ledger Technology.

## Your Environment
Hyperldger Composer Online Playground
Ubuntu VM installed on Windows 7 Laptop

**Comment by sillysachin** [comment]
This is a valid requirement. Manual data seeding one json at a time is time consuming. Alternate is writing short upload loop scripts in python to invoke rest service. Would prefer a direct option by hyperledger rest service.
