### ISSUE TITLE
How to Work with Related Data in Hyperledger Composer - 

### ISSUE THREAD

**Issue by AtreyeeBiswas** [hyperledger/composer#2121]
Participant:
{
  "$class": "org.acme.sample.Customer",
  "Customer_ID": "10001",
  "First_Name": "Tobias",
   "Customer_Segment": "P"
}
 if Account.Condition

Asset:
{
  "$class": "org.acme.sample.Account",
  "Account_No": "1",
  "Account_Holder": "resource:org.acme.sample.Customer#10001",
  "ConditionCheck": "3000"
}

Transaction : Update Participant.Type
--> Asset
check Value ... if Asset.ConditionCheck>2000 then the Asset Owner's Type has to be changed
Need to update the participant.type of participant > who is the owner of the Asset

i.e. Update Participant.Type = "X" where Participant.PID = Asset.APID

How to implement this logic - I am not sure how to retrieve the Participant here without passing the participant PID as an input to the transaction

**Comment by dselman** [comment]
Please use StackOverflow for questions.

You can call `getParticipantRegisty("fullyQualifiedName")`

**Comment by AtreyeeBiswas** [comment]
Sure, Thanks
