### ISSUE TITLE
Styling loads before data on Test panel view switch

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#2126]
When changing between registries (and/or Historian) in the Test panel, the switch first changes the styling, *then* the data.  So say you have one asset, and 12 things in your Historian.  You switch from the Historian to the Asset Registry, and for a brief moment it looks like there are 12 assets, and then they disappear and you see just the 1.

Tagging @caroline-church as we were just talking about this!

Not sure the best way to solve!

**Comment by markcastle3** [comment]
closing as a duplicate #2227
