### ISSUE TITLE
ID Cards do not re-sort until a refresh

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#2127]
## Context
Ordering of cards on the My Wallet screen changes after refreshing (in typical use)

## Expected Behavior
Cards should be sorted when a user gets to the screen in the same way that they will be after a refresh, so that things don't move around on refresh

## Actual Behavior
Cards are sorted in the order they were added to the wallet until refresh, whereupon they are alphabetically sorted.

## Possible Fix
Re-sort alphabetically whenever the My Wallet panel is loaded?

## Steps to Reproduce
1. In web playground, deploy a business network
2. Create a participant, then issue some IDs - name them in non-alphabetical order as you're creating them (and adding them to your wallet)
3. Log Out back to the My Wallet screen, observe the order of the cards
4. Refresh the page.  Observe the changed order of the cards.

## Your Environment
* Playground v0.12.2
* Linux
* Firefox

Lets tag @caroline-church and @jt-nti , as they were just discussing this with me :)

**Comment by sstone1** [comment]
P3 and no action in three months; clearly not important and never going to get fixed, so closing.
