### ISSUE TITLE
Test view should not switch to Historian after a Transaction is submitted

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#2129]
## Context
When testing a business network, upon submitting a transaction, the view currently switches to Historian.

## Expected Behavior
I think this probably *is* the expected behaviour, but I now disagree with it ;)  Discuss!

## Possible Fix
I think the view should stay on whatever you were on when you clicked "Submit Transaction".

## Why does Ed think this?
- The Historian is not necessarily the most useful view to show that the transaction worked.  e.g. in Commodity Trading, checking the Asset to see that the owner has changed is pretty useful.
- It makes the whole decision to pull out the "Submit Transaction" button as the primary action on *all* pages feel weird.  I feel like we did that because we thought "it's more understandable for users if they have to switch the the appropriate registry before performing CRUD operations, but they should be able to submit transactions from any of the panels!".  This makes sense if you're looking to see how a sequence of trades affect the assets in the asset registry: you just stay there whilst submitting the transactions.  Switching to the Historian in between each one is kinda annoying in that situation.
- We also explicitly added the "that transaction was successful" modal so that you can know a Transaction worked without switching to that view.
- It feels like if we think you should be in the Historian after you submit a transaction, then we should do the same thing we did with other registries and have you go there *then* submit the transaction...  Given the way we've got things laid out, I *think* what we probably intended was to *not* switch to the Historian in between each transaction.

That's my monologue over - thought I'd just raise this as an issue and let people debate whether they agree ;)

**Comment by sstone1** [comment]
This has been fixed by @caroline-church!
