### ISSUE TITLE
Possible to create model files with the same name in playground

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#2132]
It's possible to create multiple files with the name _org.acme.model.cto_ in the playground.

## Context

The uniqueness of model file names seems to be based off the namespace rather that the actual file name. The playground is actually really confusing as it is since as soon as you change the namespace in the model file, e.g. when following the playground tutorial, the file name is misleading.

## Expected Behavior

It shouldn't be possible to have more than one file with the same name

## Actual Behavior

It is possible to have more than one file with the same name

## Possible Fix

Name new model files, model.cto, model0.cto, model1.cto, etc. in the same way as script files, i.e. rather than pretending that the file name is the same as the namespace, and make sure the file names are unique

Alternatively, ensure that the model file name **is** always the same as the namespace and ensure they are unique

## Steps to Reproduce

1. Add a model file to a blank business network
2. Change the namespace
3. Add a second file to the business network
4. Enjoy

**Comment by sstone1** [comment]
P3 and no action in three months; clearly not important and never going to get fixed, so closing.
