### ISSUE TITLE
Automated pre-release verification of sample networks

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2135]
_As a_ composer maintainer
_I want_ release builds to perform automated verification of sample networks
_so that_ verification does not need to be run manually for every release

The [runtime validation](https://github.com/hyperledger/composer/blob/master/contrib-notes/release-process/runtime-validation.md) script currently suggests manually running the unit tests for all of the sample business networks against the unstable version of the composer. This is tedious. It would be good if this testing was run automatically for release builds.

**Comment by nklincoln** [comment]
@bestbeforetoday - I believe that this is now covered by #2899
