### ISSUE TITLE
Create ID Card certificates don't work

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#2144]
If i try and create an id card using certificates with \n in they don't work. Also when the create failed an id card was still created

**Comment by KaiUsher** [comment]
Would you be able to provide the steps for a recreate on the second part of this issue please!

**Comment by caroline-church** [comment]
If you recreate part one that recreates part two

**Comment by KaiUsher** [comment]
Closing this issue as the first part has been completed. Will open a new issue to deal with the second part.
