### ISSUE TITLE
Loopback query test modifications required

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#2145]
Currently the loopback query tests go a little too far in setting up mocks in the beforeEach() stage, and includes setting up a mock for the query process that should in fact be tested.

To be more explicit in this issue:
 - Each of the tests under `describe('#executeQuery' ...) ` need to be modified
 - Each need to include verification that the busnetConnection.query(x, y) was called with what we would expect, based on the code that operates prior to it
 - This means that each test needs to include the following:

` sinon.assert.calledWith(mockBusinessNetworkConnection.query, {things i should be called with });`

 - This will at least give us confidence that the mapping operation that converts the parameters from the retrieved query, into that passed to the busnet query, is correct.

 - We should also investigate some edge cases, such as passing in null/undef as a query parameter etc

**Comment by fenglianxu** [comment]
To clarify this is the loopback query not same as the  REST server query test did in the #1754.

**Comment by fenglianxu** [comment]
reopen it as I accidentally clicked on the close button.
