### ISSUE TITLE
What's up with the SVGs?!

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#2146]
Something funny is going on with SVGs in the playground. For example...

- Images are shadows of their former selves on Edge (see #1758)

- The nothing to see here image and the empty registry image are borked

<img width="584" alt="screen shot 2017-08-21 at 13 41 58" src="https://user-images.githubusercontent.com/7118158/29519826-b60aa96e-8676-11e7-9525-627039f9f4c7.png">

<img width="802" alt="image" src="https://user-images.githubusercontent.com/13980028/29523824-1a44b096-8686-11e7-8049-3fb958b749af.png">

**Comment by markcastle3** [comment]
@winslet could you take a look at this please?

**Comment by EdMoffatt** [comment]
I'll take a look at this one :)

**Comment by markcastle3** [comment]
@EdMoffatt is there much more left to do on this one ?

**Comment by EdMoffatt** [comment]
This one is fixed!  Closing...
