### ISSUE TITLE
Pre-deploy summary of networks looks like it wrongly counts system-types

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#2149]
We have a little preview of "what's in this business network" before you deploy, with the aim of getting an idea how complex this nusiness network is.

These numbers are higher than I'd expect, and my guess is they're also counting system types.

For example, see the Basic Sample Network:

![image](https://user-images.githubusercontent.com/7454304/30476259-61e424d4-9a01-11e7-99c3-faf26b605d59.png)

Seeing that "Hello World" includes 15 transaction types just *looks* wrong.  I know they're all out by the same amount, but I think it's more reassuring that "yup, this is a nice simple one, good to start with", if it says 1 asset, 1 participant and 1 transaction.

So, if it *is* system types getting included then imo we should exclude those.

**Comment by EdMoffatt** [comment]
Tagging @caroline-church for her thoughts :)

**Comment by caroline-church** [comment]
Yes we should exclude system types

**Comment by mbwhite** [comment]
The Playground goes direct to the ModelManager to get the participants etc. This includes system types.
Suggest mod to the modelmanager api, like in other places so that be default they return types excluding system, but pass a boolean and they do return system types,.
