### ISSUE TITLE
As a user, I can create a new ID card by importing certificates from disk

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#2150]
We now have a new option to create a new ID card by copying and pasting certificates into the playground:

<img width="1085" alt="screen shot 2017-09-15 at 11 31 21" src="https://user-images.githubusercontent.com/7118158/30478642-c607fdd4-9a09-11e7-81e0-031b4c5c0749.png">

What would really polish this off nicely is the ability to import certificates from disk as well 👍

**Comment by winslet** [comment]
Question: just to confirm, I think the answer is 2, but how many certificates are needing to be uploaded here? Is it one or two? (is the private key a separate cert?)

**Comment by sstone1** [comment]
@winslet the certificate will be one PEM file and then the private key will be another PEM file.

**Comment by winslet** [comment]
In the original designs: https://github.com/hyperledger/composer/issues/1423

See the last screenshot 👍
