### ISSUE TITLE
Reduce Web profile confusion

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#2154]
During testing of the new ID card functionality, some confusion emerged over what the Web profile was, and what its purpose is. While more documentation might help, it would be good to improve the playground to make things clearer

## Context

It's not immediately obvious that the Web profile is not something that can be shared with other people, especially when accessing a hosted playground on the web somewhere. Web implies connected, whereas the Web profile is actually entirely local 

## Expected Behavior

I should be able to easily understand what the Web profile is and what it's for

## Actual Behavior

The Web profile is not very web-like

## Possible Fix

A new name could really help here. Instead of Web profile, something like Local, Personal, Disconnected, Private, etc. might make things clearer.

In addition, moving identities for the Web profile below the 'real' Hyperledger Fabric profiles, with a short description, e.g. 'A profile to quickly test without connecting to a blockchain runtime,' could all help guide users before they need to consult the documentation for a full explanation.

From @EdMoffatt 

> After the single line install, you get an empty set of cards for web browser, and then below that is your card for the hlfabric runtime. This looks a bit odd, especially if you stick with using hlfabric and never deploy anything to the web browser... Suggest we could have Web Browser always at the bottom of the list? That way if you have any cards for real Fabrics then they appear at the top (as we assume that if you're at the stage of connecting to real Fabrics, they're probably more important to you than the Web Browser profile at that point)

Tagging this with design and docs to get feedback on final design/wordings

**Comment by EdMoffatt** [comment]
Just bumping this up our collective conscience, as Tracy and @sstone1 saw people getting confused by this at the hackathon this weekend, and I just watched over the shoulder of another new user tripping over it ;)

> Re-order so that "Web Browser" is always at the bottom - totally agree

> Change the name of "Web Browser" - I think we all want to do this, and also we're not sure what we want to change it to yet ;)  Here are some of the options I've heard thrown around...

- Local
- Personal
- Disconnected
- Private
- Emulated Blockchain
- Simulated Blockchain

We *could* also look to do something with a little info icon on this particular connection, something to draw attention to the fact it's not like the others...  Something like...

![image](https://user-images.githubusercontent.com/7454304/31133054-4d2c9b4e-a856-11e7-9873-f25b91500f78.png)

**Comment by jt-nti** [comment]
@EdMoffatt How about something like _Private Emulation_? _Emulated Blockchain_ (singular) doesn't seem quite right- isn't each network in the browser a separate emulated blockchain? Making it a plural _Emulated Blockchains_ would fix that but Blockchain seems like a given, while Private might be a useful clue that they are something you can't share?

**Comment by EdMoffatt** [comment]
"Private" seems like a good word to include in there :)  I think "Emulation" is feeling like a bit of a weird word to me (I know, all just opinions here!)...
Maybe something like "Private, Emulated" or "Private, Simulated" or "Emulated (Private)" or "Simulated (Private)"?

**Comment by EdMoffatt** [comment]
We should totally do a "describe what it is succinctly, then ask a bunch of randomers what they would name it" exercise on this :)  Assigning to Hannah to do this!
