### ISSUE TITLE
As a user, I can easily debug my access control rules

### ISSUE THREAD

**Issue by ScottMorris** [hyperledger/composer#2156]
I've been having issues with running external JavaScript functions from the _conditions_ section of the rules.  One thing that would be nice is to support logging in external ACL JavaScript files.

## Context
When working with ACLs sometimes things go wrong and errors are thrown, or the logic is complex and needs to be debugged.

## Expected Behavior
I'm expecting there is a way to debug the ACL rule conditions (predicates).  Something like `LOG.debug` (and other log functions).

## Actual Behavior
`LOG` doesn't seem to import and work, so ACL rules are almost black boxes.

## Existing issues
As suggested by @davidkel on [#composer on RocketChat](https://chat.hyperledger.org/channel/composer?msg=35qkCJMYyrmz78qkA) the logging is lacking.

## Context
My co-worker and I have been developing a business network and have been having issue with ACL rules, from them throwing errors and not working even if they look correct, to them working even when logically they aren't correct.  When we tried to dive deeper into them we found them to be a black box.

## Your Environment

* Version used: Composer 12.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 61, NodeJS 6.11
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS, Linux Mint 18.2

**Comment by EdMoffatt** [comment]
Just gonna tag @hannahrayner on this one for her awareness - she's going to be doing some investigation into any improvements we can make to ACL editing, and it sounds like this issue will be a good example of some of the current difficulties!

**Comment by ScottMorris** [comment]
I've updated the issue discription to be more complete.  I've also made some notes on issue #2104 about errors being logged at a lower level in the `compiledaclbundle.js`.

**Comment by lbotsch** [comment]
@ScottMorris I had the exact same issue. The only way I found to get any feedback out of the ACL helper functions is running the network in embedded mode (in my unit tests, see [Developer Guide](https://hyperledger.github.io/composer/tutorials/developer-guide.html#write-unit-tests)) and using console.log inside the helper functions. This will output to the console running npm test

**Comment by ScottMorris** [comment]
@ibotsch We were trying to use the unit tests to test the rules and they worked fine, but when we deployed them they failed.  It seemed like the Identifiers were being handled differently.
