### ISSUE TITLE
Query: the third condition fails with unknown operator "0"

### ISSUE THREAD

**Issue by nasht00** [hyperledger/composer#2160]
Let's assume this simple query:

```
query MySimpleQuery {
  description: "Select all stuff where widget is PARAM"
  statement:
    SELECT my.Stuff
    WHERE (widget == _$widget)
}
```

This works fine.
Now let's add another `AND`:

```
query MySimpleQuery {
  description: "Select all stuff where widget is PARAM"
  statement:
    SELECT my.Stuff
    WHERE (widget == _$widget AND widget == _$widget)
}
```

This still works fine (redundant but still).
Now let's add a third:

```
query MySimpleQuery {
  description: "Select all stuff where widget is PARAM"
  statement:
    SELECT my.Stuff
    WHERE (widget == _$widget AND widget == _$widget AND widget == _$widget)
}
```

Result: 

> Error: unknown operator "0" - should be one of $eq, $lte, $lt, $gt, $gte, $exists, $ne, $in, $nin, $size, $mod, $regex, $elemMatch, $type or $all

Now of course in my real world scenario it's not 3 times the same param, it's `WHERE (contract == _$contract AND status == 'ACTIVE' AND startDate < _$startDate)`.
But to remove the possibility of something wrong with one of my conditions I tested with 3 times the same param and got the same error ...

To help with debugging, here are some more test cases:

- `WHERE (contract == _$contract AND status == 'ACTIVE' AND startDate < _$startDate)` 🔴 
- `WHERE (contract == _$contract OR status == 'ACTIVE' AND startDate < _$startDate)` ✅ 
- `WHERE (contract == _$contract AND status == 'ACTIVE' OR startDate < _$startDate)` 🔴 
- `WHERE (contract == _$contract OR status == 'ACTIVE' OR startDate < _$startDate)` ✅ 
- `WHERE (contract == _$contract AND (startDate <= _$startDate AND status == 'ACTIVE' ))` 🔴 

I hope it helps.

**Comment by fenglianxu** [comment]
These issues occur when using PouchDB and work fine at rest server with CouchDB.  I will continue to look at the PouchDB implementation.

**Comment by fenglianxu** [comment]
Here are all test cases I have done with PouchDB:
A AND B AND C --> failed
(A AND B) OR C --> failed
A OR (B AND C) --> failed
A AND (B OR C) --> passed
(A OR B) AND C --> passed
A OR B OR C --> passed
A, B and C are the Where conditions, for example : A  can represent the first condition contract == _$contract reported in this defect, B and C can be the second and the third condition. 
Basically PouchDB find() method does not like the AND to link two or more simple conditions, A AND B, B AND C, and A AND B AND C above test cases. The AND can be used for a mixture of complex condition, eg one of the operand has the OR operator.
CouchDB supports all above test cases. This is a limitation of the PouchDB I have also verified above test cases in  PouchDB website. : http://nolanlawson.github.io/pouchdb-find/
We have three options here:
1. change our query compiler to use AND only when one of the operand has the OR operator. 
2. change the query string in the pouchdbdataservice.js 
3. raise a defect to PouchDB and wait for their fix.

Option 1 will change the queryString for both PouchDB and CouchDB services, this need more test effort.
Option 2 is for PouchDB specifically but it's not a good solution. This will replace the condition $and to be a default one as below
'$or': 
      [ { '$and': 
           [ { 'bond.isMatured': { '$eq': true } },
             { 'bond.currency': { '$eq': 'GBP' } } ] },
        { 'bond.dayCount': { '$lte': 2000000 } } ]     ==>
'$or': 
      [ { 
            'bond.isMatured': { '$eq': true } ,
              'bond.currency': { '$eq': 'GBP' } },
        { 'bond.dayCount': { '$lte': 2000000 } } ]

Option 3 might take long time

@sstone1 Can you let me know your view on this please?

**Comment by fenglianxu** [comment]
@sstone1 I took the option 1 and this option won't affect CouchDB query as the CouchDB  query supports both explicit 'AND'  or implicit 'AND' format.

**Comment by fenglianxu** [comment]
close this one now
