### ISSUE TITLE
Runtime support for ID cards

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2172]
_As a_ user of Composer
_I want to_ use only ID cards to describe identities for connecting to business networks
_so that_ identities are portable and I have a consistent experience across both CLI and Playground

**Comment by mbwhite** [comment]
To help focus on the order of the stories I created https://github.com/hyperledger/composer/issues/2448

That is end-end scenario of a round-trip developer interaction. 

At present this needs some code coverage to be completed but is essentially complete.

**Comment by mbwhite** [comment]
14.2 has been released minus https://github.com/hyperledger/composer/pull/2456.

Confirming with @sstone1 this means the 'big switch over' has to happen in the next release.
Hence will pull out the code for the dual support. And move to going full native.
