### ISSUE TITLE
Update karma to work with Firefox

### ISSUE THREAD

**Issue by harsha544** [hyperledger/composer#2180]
Composer Unit-tests currently make use of google-chrome browser which is not available for ppc64le arch, hence update relevant changes to work with Firefox instead, which is available across all arch.

**Comment by mikailcetinkaya** [comment]
will you make a pull request

**Comment by harsha544** [comment]
Here's my latest PR https://github.com/hyperledger/composer/pull/2261 
Would need JS expert to help resolve the issues uncovered due to the introduction of the above PR.

**Comment by jt-nti** [comment]
This issue still needs work, I have a branch that was building on travis, unfortunately the Protractor e2e tests still use Chrome. It looks like switching e2e tests to Firefox is unlikely to be straightforward and I'm away for a week so I am not currently working on this issue. If anyone can help, here is what I had so far...

https://github.com/jt-nti/hyperledger-composer/tree/2180-karma-firefox
