### ISSUE TITLE
Asset attributes with a type of Double are unable to have a default value

### ISSUE THREAD

**Issue by acshea** [hyperledger/composer#2187]
## Context
If an asset has a Double field with a default value, a JSON error is thrown

## Expected Behavior
A given asset should be able to have a default value set for a Double

## Actual Behavior
When a default value is set, creating an instance using the Factory.newResource() function does not work. Invalid JSON is returned, with a value of 'NaN' included against the attribute.

Although this issue was found using the SDK, it can also be reproduced easily in Playground by doing the following:

## Steps to Reproduce
1. Open Composer Playground
2. Deploy sample network
3. Add Double field to SampleAsset with a default of 0.0, then deploy
4. Try and create a new instance of the asset

The following error appears:

Error: Generated invalid JSON: {"$class":"org.acme.sample.SampleAsset","assetId":"assetId:1008","owner":"resource:org.acme.sample.SampleParticipant#participantId:0025","value":"","a":NaN}

## Context
Trying to add defaults to some Double values to enforce a default value

## Your Environment
* Version used: 12.2
* Operating System and version (desktop or mobile): Mac OS

**Comment by vijaymca** [comment]
It resolved after I changed code with dot(.0) as below

` o Double construction default = 50000000.0`
 ` o Double debris_removal default = 35000000.0`
  `o Double named_strom default = 100000000.0`
 ` o Double earth_movement default = 100000000.0`
  `o Double exp_costs_and_ext_expense default=50000000.0`
