### ISSUE TITLE
As a contributor having granular Travis builds would save time

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#2192]
At the moment the build process is an 'all or nothing' item, where all regression tests are run irrespective of what has been changed. This is time consuming and unnecessary in certain circumstances.

For instance:
 - A doc change should only require a doc build
 - A playground change should only require a playground build

There are of course exceptions:
 - A runtime change modifies code used by Playground, so that should be built ... though we dont want to build the docs too.

## Context
Waiting for builds to build, when parts of the build dont really need to build, is building up frustration

## Expected Behavior
Only test what changes

## Actual Behavior
Test everything

## Possible Fix
Dont test everything all the time

**Comment by sstone1** [comment]
No actions here; strategy is to migrate to Jenkins for multi-platform builds and "throw your own hardware at it" support in CIP #3134.
