### ISSUE TITLE
Runtime update has broken web profile

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#2195]
When trying to update a busnet in playground, when using the web profile, the result is an error - connection to a fabric does not have this problem

**Comment by mbwhite** [comment]
With the update Business Network now being a business network transaction it follows a slightly different code path. The connectors used to have an update method defined in them.  

The update method was left in the web and proxy connectors. Hence the failure.

(should state that is the current working theory - initial investigations confirm this

**Comment by nklincoln** [comment]
validated on latest playground build
