### ISSUE TITLE
Deleting Secondary Model File on the web profile empty-business-network erases contents of the remaining Model File

### ISSUE THREAD

**Issue by EllisHenderson** [hyperledger/composer#2197]
## Expected Behavior
Second Model File would be deleted without impacting remaining files. 

## Actual Behavior
Upon deletion of the second Model File, an error occurs and the contents of the original/remaining Model File are visibly wiped. Following error occurs:

<img width="1255" alt="screen shot 2017-09-21 at 11 10 27" src="https://user-images.githubusercontent.com/15138976/30692402-48c3c538-9ec3-11e7-8938-6cbca07141e8.png">

<img width="1255" alt="screen shot 2017-09-21 at 11 33 40" src="https://user-images.githubusercontent.com/15138976/30692406-4cc90eea-9ec3-11e7-828d-f6cf75e10878.png">

<img width="1251" alt="screen shot 2017-09-21 at 11 33 56" src="https://user-images.githubusercontent.com/15138976/30692410-510f8fba-9ec3-11e7-9af8-b4e4fe36d83b.png">

## Steps to Reproduce
1. Create an empty-sample-network in the Web Profile and connect. 
2. Add a Model File, Script File and Access Control - following the instructions on the PlayGround Tutorial. 
3. Add a second Model File.
4. Delete the second Model File.

**Comment by dselman** [comment]
@caroline-church sounds bad, I've raised the priority.

**Comment by caroline-church** [comment]
This has been fixed so closing
