### ISSUE TITLE
Historian Docs nitpicks

### ISSUE THREAD

**Issue by jpayne23** [hyperledger/composer#2200]
1.  transactionId doesn't have a type in the description, every other attribute does have a type. This appears in the 'Hyperledger Composer Historian' section in the 'HistorianRecord assets' subsection.

2. At the end of 'HistorianRecord assets' subsection, there is different styling used for 'HistorianAsset'. Throughout the section previously there is special styling for it whereas at the end of this subsection 'HistorianAsset' appears in plain text.

**Comment by dselman** [comment]
@EdProsser please review
