### ISSUE TITLE
ID Card docs outdated

### ISSUE THREAD

**Issue by jpayne23** [hyperledger/composer#2201]
For the 'Creating an ID Card', 'Creating ID Card Credentials' and 'Connecting using Credentials' subsections, the information given are outdated.

- In 'Creating an ID Card', step 7 is no longer required as there is no popup to let the user add credentials to the Wallet after clicking the Create New button. The gif showing this process also needs updating as a result.

- For 'Creating ID Card Credentials', you can no longer complete the steps. It is due to the same reason as described above but the result of it in this section is that you cannot get the User ID and Secret through the method given. This means I wasn't able to finish this subsection successfully.

- For 'Connecting using Credentials', you are unable to use either method given because there is no Connect using Credentials button on the My Wallet page anymore

**Comment by dselman** [comment]
@EdProsser is this still the case?

**Comment by jpayne23** [comment]
Just noticed this is the same issue as #2188

**Comment by nklincoln** [comment]
closing duplicate issue, retaining this item, thought note that the mp4 captures are no out of date ... maybe consider removing them in favour of selective screen captures?

**Comment by caroline-church** [comment]
The docs should now also refer to id cards being called business network cards
