### ISSUE TITLE
Historian screen doesn't handle reduced width well

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#2205]
Historian adds ellipses if the text won't fit, but there's no hover to see the full text...

![image](https://user-images.githubusercontent.com/3535067/30741176-b6f315ae-9f8b-11e7-98f6-b91dadf7f144.png)

**Comment by sstone1** [comment]
Duplicate of:
Historian content is cramped and ellipsis used for UUID and action link #1895
