### ISSUE TITLE
Perform playground version checks synchronously and early as possible

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#2208]
dselman 9:00 AM 
It looks like with 0.13.0 we have to clear local storage manually to get playgound to work. Anyone else see that?

harsha 12:03 PM
I was seeing this with 012.2 too

sstone1 7:11 AM 
playground seems to fall over before it gets to the part that checks the versions don't match and offers the clear local storage option
you can also get error modals mixed with clear local storage modals
@jtonline can we improve that?

jtonline 8:23 AM
@sstone1 would be nice not to have error modals or clear local storage modals. https://github.com/hyperledger/composer/issues/1447 has been about for a while but you could also open a new issue to try and do the checks earlier?

**Comment by markcastle3** [comment]
@caroline-church are you able to take a look at this one.
