### ISSUE TITLE
Need for standard naming convention for npm modules

### ISSUE THREAD

**Issue by stcroppe** [hyperledger/composer#2213]
## Description

There already exists a node_module in the npm registry called composer -> [doowb/composer -> https://github.com/doowb/composer]. So when you try to use npm install locally it gets confused and the installation fails.

## Problem Experienced
Ideally the GitHub Hyperledger composer project could be registered with npm such that the command 
 npm install hyperledger/composer

              or 

npm install hyperledger-composer

            or 
npm install hlf-composer

can be used to download and install the node sdk and its dependencies. Right now this is hit and miss and only seems to work in the GitHub desktop when you have pulled a pristine clone. 
## Expected Behavior
one of the commands suggested above should drive the installation process in the developers folder of choice using npm directly.

## Actual Behavior

└─[0] <> npm install
npm WARN deprecated fs-promise@1.0.0: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm ERR! code ETARGET
npm ERR! notarget No matching version found for composer@^0.13.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'basic-sample-network'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stcroppe/.npm/_logs/2017-09-22T17_23_55_441Z-debug.log
[2017-09-22T17_19_16_257Z-debug.txt](https://github.com/hyperledger/composer/files/1325467/2017-09-22T17_19_16_257Z-debug.txt)

At the end of this log the composer confusion shows up as...

4545 silly currentTree ├── composer@0.13.1.                                <---- hlf composer
4545 silly currentTree ├── mailcomposer@4.0.1
4546 silly idealTree ├── composer@0.14.2.                                    <-----  doowb composer
4546 silly idealTree ├── loopback-connector-composer@0.11.3
4546 silly idealTree ├── mailcomposer@4.0.1
[2017-09-22T17_23_55_441Z-debug.txt](https://github.com/hyperledger/composer/files/1325470/2017-09-22T17_23_55_441Z-debug.txt)

## Steps to Reproduce

1. create a test directory
2. install node and npm if you don't have it
3. execute npm install composer
4. composer 0.4.2 is downloaded

This would be the default behaviour when you run npm install and require composer ^0.13.0 since 0.14.2 is a more recent pack :-)

## Your Environment

* Version used: 0.13.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): nodejs 8.5.0, npm 5.3.0
* Operating System and version (desktop or mobile):MacOs High Sierra RC

**Comment by sstone1** [comment]
@stcroppe there is no Hyperledger Composer module called `composer` - all of our modules have a suffix applied to them, for example `composer-cli` or `composer-rest-server`. So I'm not sure how you can get into this situation:

```
4545 silly currentTree ├── composer@0.13.1. <---- hlf composer
4545 silly currentTree ├── mailcomposer@4.0.1
4546 silly idealTree ├── composer@0.14.2. <----- doowb composer
```

**Comment by stcroppe** [comment]
Hi Simon:

I can install composer if I use git desktop however there are several issues here which I think you should consider if you want adoption. Bearing in mind you are targeting this at node developers who may want to create a dependency on this project in their own. 

1. If you try to install Hyperledger composer as described by 'npm install' docs.

i.e. 'npm install hyperledger/composer' (which would be the easiest way to install for nodejs if it worked) there is an error produced due to missing dependencies...

2. If you actually look at the package.json file that you are directed to on GitHub here:
https://github.com/hyperledger/composer/blob/master/package.json

you will see that the package.json file is named composer

`  "name": "composer",
  "description": "You must install [Lerna](https://lernajs.io) to build this multi-package repository.",
  "version": "0.13.1",
  "main": "index.js",`

I realise that this is merely a container to bring down docker files and other dependent modules and packages but I think you might make Hyperledger composer more accessible if you fix the package.json naming and enable composer to be accessed through a simple 'npm install Hyperledger/composer" command. 

Hope this makes sense.

Cheers
______________________________________________________________


npm install failure:
`└─[0] <> npm install hyperledger/composer

> composer@0.13.1 postinstall /Users/stcroppe/Development/testLoad/node_modules/composer
> npm run pkgcheck && npm run bootstrap


> composer@0.13.1 pkgcheck /Users/stcroppe/Development/testLoad/node_modules/composer
> node ./scripts/pkgcheck.js

module.js:529
    throw err;
    ^

Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/stcroppe/Development/testLoad/node_modules/composer/scripts/pkgcheck.js:19:16)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! composer@0.13.1 pkgcheck: `node ./scripts/pkgcheck.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the composer@0.13.1 pkgcheck script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stcroppe/.npm/_logs/2017-09-23T07_17_09_921Z-debug.log
npm WARN enoent ENOENT: no such file or directory, open '/Users/stcroppe/Development/testLoad/package.json'
npm WARN testLoad No description
npm WARN testLoad No repository field.
npm WARN testLoad No README data
npm WARN testLoad No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! composer@0.13.1 postinstall: `npm run pkgcheck && npm run bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the composer@0.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`
