### ISSUE TITLE
Prereq: Fabric Node.js SDK should support failover between Fabric components

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2217]
An area that needs to be looked into in conjunction with the Hyperledger fabric team is how do you implement fault tolerance for a fabric network ? I am not aware this is built into the core fabric so should the capability be built into the node sdk as part of the new connection profile support proposed. If the reliance is to be pushed back to the application developers then how could composer support this and what capabilities are required from fabric and the node-sdk in order to allow composer system architects to realize this capability within their solutions using composer.

**Comment by sstone1** [comment]
> should the capability be built into the node sdk as part of the new connection profile support proposed

Yep - this belongs in the Fabric Node.js SDK. Now that Fabric "owns" the connection profile, all connection management operations like failover between different peers belong in Fabric as well.

**Comment by davidkel** [comment]
Yep, need to raise a JIRA and keep this issue to track how that JIRA progresses.

**Comment by davidkel** [comment]
https://jira.hyperledger.org/browse/FAB-8331

**Comment by davidkel** [comment]
Closing due to node-sdk starting to look into this.
