### ISSUE TITLE
ID cards are still created if there is an error with the creation

### ISSUE THREAD

**Issue by KaiUsher** [hyperledger/composer#2219]
If the creation of an ID card fails for whatever reason, the ID card is still created and added to the wallet - this ID is useless as trying to use it will only result in an error. Therefore, in such a situation, an ID card should not be created and added to the wallet.

## Expected Behavior
If there is an error in the creation of an ID card the user should be informed before the ID card is created and added to their wallet.

## Actual Behavior
When there is an error in the creation of an ID card, an unusable card is added to the wallet.

**Comment by caroline-church** [comment]
done so closing
