### ISSUE TITLE
When adding a file from disk, you cannot replace the file with one of the same type.

### ISSUE THREAD

**Issue by KaiUsher** [hyperledger/composer#2226]
When choosing a file to import from disk, the initial selection works as expected, but if you then try to change that selection for another file of the same type, the import will not work. This however is not the case if the chosen file is changed for one of a different type.

This behaviour has been noted when adding a file to Playground via the 'Add a file+' button and also whilst developing the functionality of being able to create ID cards with certificates from disk ( #2150 ). Therefore, it is likely to be an issue with the file-importer component.

## Expected Behavior
If I choose to import a file from disk when adding a new file to Playground I should be able to change the file for one of the same type and be able to import it.

## Actual Behavior
If I select a .cto file, for example, and then decide to change it for a different .cto file, the second file is not loaded into Playground.

## Steps to Reproduce
1. Select 'Add a file+'.
2. Browse to a .cto file, and select it.
3. Click 'Remove file'.
4. Repeat step 2, but choose a different .cto file.
5. Notice the second file is not imported.

**Comment by awjh-ibm** [comment]
I was unable to replicate this in Mac Firefox. What were your environment settings?

**Comment by awjh-ibm** [comment]
Unable to replicate in FF, Safari or Chrome on Mac and on Chrome and FF on Ubuntu
