### ISSUE TITLE
Playground doesn't transition well from historian to asset registry

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2227]
[example_mp4.zip](https://github.com/hyperledger/composer/files/1330980/example_mp4.zip)

**Comment by sstone1** [comment]
A summary of the video - when you move between different registries, the list you were seeing seems to persist for a second or so before it is replaced. So if you go from historian to an asset registry, you briefly see historian entries in the asset registry.

**Comment by sstone1** [comment]
P3 and no action in three months; clearly not important and never going to get fixed, so closing.
