### ISSUE TITLE
Composer allows me to add transaction objects to an asset registry

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2228]
![image](https://user-images.githubusercontent.com/25582377/30831752-9740ce88-a240-11e7-8ba1-f5c9a238ca76.png)

**Comment by davidkel** [comment]
I created a transaction that creates an a LandTitle asset. I invoke the transaction to create the asset. The transaction completes successfully but when I view the asset registry, it shows me the transaction that created the asset and not the asset that was created.

**Comment by markcastle3** [comment]
@EllisHenderson can you take a look at this please ?

**Comment by caroline-church** [comment]
fixed so closing
