### ISSUE TITLE
Submit option is not visible while creating Participant in marbles-network 0.1.7 tutorial (Cannot Scroll down)

### ISSUE THREAD

**Issue by atulv3nom** [hyperledger/composer#2233]
## Context
I am working with the Hyperledger tutorial marbles-network 0.1.7 tutorial on Online Hyperledger Composer Playground. When I am creating a participant in the tutorial, submit button is not visible. Additionally, scrolling is disabled on this page.

I tried the workaround to enter in full screen mode in Chrome (F11 key) and then clicking submit. It would be good to introduce scrolling on this window as this problem will persist in lower resolution systems.

## Expected Behavior
Create option should be visible in the browser by default while creating Assets/Participants/Transactions

## Actual Behaviour
The option is not visible and goes out of the current view. Scrolling is not available on this screen and I have to enter into full screen mode to select it.

## Possible Fix
Scrolling should be introduced on this dialogue box/screen or the Create/Submit should be visible by default.

## Steps to Reproduce
1. Screen Resolution: 1366*768
2. Browser: Google Chrome Version 60.0.3112.113 (Official Build) (32-bit)
3. Operating System: Windows 10 Pro
4. Link: https://composer-playground.mybluemix.net/
5. Example/Tutorial Link: https://github.com/hyperledger/composer-sample-networks/tree/master/packages/marbles-network

Default View

![default view](https://user-images.githubusercontent.com/17270157/30862024-3490bf96-a2ea-11e7-9a96-10d50d5a68b1.jpg)

Full Screen

![full screen](https://user-images.githubusercontent.com/17270157/30862025-34933eb0-a2ea-11e7-8ec2-d521c5315f9d.jpg)

## Context
I was trying to create Assets/Participants/Transactions on the online platform.

## Your Environment
* Screen Resolution: 1366*768
* Environment name and version: Google Chrome Version 60.0.3112.113 (Official Build) (32-bit)
* Operating System and version: Windows 10 Pro
* Link to your project: https://github.com/hyperledger/composer-sample-networks/tree/master/packages/marbles-network

**Comment by sstone1** [comment]
I've seen multiple people hit this, the other option is to `Ctrl`+`-` to zoom out.

**Comment by caroline-church** [comment]
done so closing
