### ISSUE TITLE
Remove Shell capabilities from Composer CLI

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2235]
The shell capabilities probably add no benefit, there are no real tests or documentation for it and also pull in composer-rest-server (although it may not make use of that at all).
This is an opportunity to reduce unnecessary code, improve the CLI code coverage and reduce the size and time spent installing composer-cli both for users and the docker images.

**Comment by sstone1** [comment]
The options are:
- Test and document the shell
- Remove the shell until it can be test and documented

Alternatively it could be pulled out into a separate module that lives in `composer-tools` which is a bit of a dumping ground for "untested" code.

**Comment by sstone1** [comment]
Assigning to @mbwhite who wrote the shell.

**Comment by mbwhite** [comment]
Status:
Have a branch with this in progress..

**Comment by mbwhite** [comment]
Resolved in #2876
