### ISSUE TITLE
Basic GET API calls return no results on a multi org, multi peer fabric network

### ISSUE THREAD

**Issue by paulxuereb** [hyperledger/composer#2239]
## Context
Composer's REST API seems to have a bug with GET calls on multi org, multi peer networks. Creating a record in the asset registry and then running a GET with no params or filters returns no results

## Expected Behavior
All records in the asset registry should be returned

## Actual Behavior
No records are returned

## Possible Fix

Running a GET with no parameters or filters should return all records

## Steps to Reproduce
1. Create a multi org, multi peer fabric network
2. Import identities from the fabric network into composer using composer identity import
3. Create a composer connection profile for org1 & org2
4. Download the composer sample project carauction-network
5. Composer archive create ... for the carauction-network
6. Composer runtime install ... for org1 for the network carauction-network
7. Composer runtime install ... for org2 for the network carauction-network
8. Composer network start ... on consortium profile incorporating all peers
9. Create the rest API on org1 using composer-rest-server ...
10. Browse to http://localhost:3000/explorer, list the operations for the Auctioneer object
11. Create a new instance of the Auctioneer model, setting the parameters appropriately, wait for response code and body to indicate success
12: Run the GET /Auctioneer 'find all instances of the model matched by a filter from the data source' operation, passing no parameter in the filter field. This calls http://localhost:3000/api/Auctioneer/ , should return the record created in step 11 - but doesn't

## Existing issues
Raised on rocket chat

## Context
I am trying to interact with a network i have built, which has the same results as the bug described here, but thought that it was worth listing a sample project which has the same result.

This worked fine before upgrading composer today

## Your Environment

Hyperledger Fabric v1
Composer v0.13.0

**Comment by mikailcetinkaya** [comment]
0.13.2 is out , try

**Comment by paulxuereb** [comment]
mikailcetinkaya, it doesn't look like anyone has picked this up yet. It wasn't part of v0.13.2

**Comment by davidkel** [comment]
Given that we are now at 0.16.6 for HLF 1.0 and 0.18.1 for HLF 1.1, if there was a problem then it will have been fixed now as we have introduced many automated tests that cover this scenario. If it is still an issue then please open a new github issue.
