### ISSUE TITLE
ID Page cannot deal with long names (with a xxl bna-name)

### ISSUE THREAD

**Issue by georgschultz** [hyperledger/composer#2246]
Ability to destroy the id card Page with a very long bna-name

![screen shot 2017-09-28 at 11 51 09](https://user-images.githubusercontent.com/31318197/30962903-76e5998e-a443-11e7-91fc-de9ecfffa7c7.png)

## Your Environment
Ubuntu-Firefox browser

**Comment by winslet** [comment]
lulz yeah, this is an edge case but we should definitely fix this. Could we truncate the name at an intelligent point based on the width of the screen? (eg 70%)

Im going to hold off on making a design for this, if you have any more questions lemme know 🌮

**Comment by caroline-church** [comment]
Fixed so closing
