### ISSUE TITLE
Editing of the package.json is no longer possible

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#2247]
Within playground, editing the package.json file is no longer possible and results in all changes causing an error, which prevent saving of the file and subsequent update of the package file.

**Comment by caroline-church** [comment]
assign to to awjh-ibm

**Comment by EdMoffatt** [comment]
Just a little note playing around with this just now...  It appears that if you edit something (e.g. the version or the description), you get an error...  But then if I, say, click on the Script file, then back to the ReadMe to hit edit on package.json again, I still see my changes there...  And the Update button is enabled and everything.

I'm on Chrome, Mac, v0.13.1.

I know it's still a bug, but it doesn't seem to be quite the same behaviour reported in the issue, so I thought I'd mention it ;)
