### ISSUE TITLE
Invalid filename error not clear

### ISSUE THREAD

**Issue by jpayne23** [hyperledger/composer#2250]
## Context
On the staged Composer Playground, if you use invalid characters (non alphanumeric) while updating a filename you will get an error. However there is no information shown about why this is an error. Shown below in screenshot:

![screen shot 2017-09-28 at 14 22 11](https://user-images.githubusercontent.com/9744866/30968818-72a55f52-a458-11e7-9a6d-26397004bfc0.png)

## Expected Behavior
Error gets displayed with information to help the user fix the problem. Preferably the error would appear once the invalid character is input, rather than on the submit of the update.

## Actual Behavior
After clicking off the textbox to edit the filename, the textbox turns red and prevents the update from happening.

## Possible Fix
The error message is given but hidden behind the script box. Screenshot below shows where the error message is by bringing it in front of the script box.

![screen shot 2017-09-28 at 14 23 12](https://user-images.githubusercontent.com/9744866/30968867-a2dc3f10-a458-11e7-8bb2-04cca9ab01f1.png)

## Steps to Reproduce
1. Import a business network into Composer Playground
2. Choose to view a model, script or access control file
3. Click the edit icon by the file name above the script box.
4. Add a non alpha numeric character to the filename
5. Click off the edit filename textbox and error is shown

## Existing issues
None found

## Context
Minor inconvenience as it wasn't clear what was a valid format for a filename.

## Your Environment
Using the staged Composer Playground on desktop on Firefox version 52.3.0, running on Mac version 10.12.6

**Comment by awjh-ibm** [comment]
Fixed as part of fix to issue #2352
