### ISSUE TITLE
Enable basic re-skinning of the playground

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#2251]
Allow minor modifications of playground at build/deploy time, e.g. name, style, doc links etc.

## Context

This should enable Composer Playground to be hosted as part of a product offering if required

## Expected Behavior

Name and styling of the playground should be customisable without branching the code. Other aspects that need to be varied depending on the deployment:

- Google analytics property ID - **must not use the same ID as the current hosted playground**
- Different stylesheets - is it possible to have stylesheets compiled from separate repos loaded in?
- Links to documentation - otherwise a hosted version of the playground which is updated less frequently would link to more recent documentation, causing much comfusion
- Different set of sample networks - i.e. make the npm sample network lookup configurable
- Others? (TBC)

## Actual Behavior

Currently not possible

## Possible Fix

Could be done with build time or server side templating, or via a configuration file/options at deploy time

**Comment by jt-nti** [comment]
Google analytics ID is now configurable following PR #2791

**Comment by awjh-ibm** [comment]
Links, page title and banner text are now configurable following PR #2732
