### ISSUE TITLE
As a first time Composer user, I can immediately work out how to get started

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#2269]
We've received feedback that the introduction of ID Cards has led to some first time users struggling to know where to get started in the Composer Playground.  The "Deploy New Business Network" option is seen as too much choice by some, and some of the terminology ("ID Cards" versus "Business Network Cards" has been the subject of enthusiastic discussion in the community ;) ).

Here's the suggested "next chunk of work" to improve on the implementation of ID Cards:

(1) Make some wording updates to arrive at terminology the community is more in favour of.

On the main landing page (composer-playground.mybluemix.net)
- [ ] "My Wallet" > "My Business Networks"
- [ ] "Identity Cards for <connection_profile>" > "Connection: <connection_profile>"

On the other pages, in the "ID Dropdown" (e.g. on composer-playground.mybluemix.net/editor)
- [ ] "Log Out" > "My Business Networks" in the dropdown you get when you click the name of the ID in the top right.

(2) Replace the "Not sure where to start? View our Playground tutorial" message with a "Hello Composer" tile.  This tile will provide the same link to the tutorial, and also a convenient shortcut to:

- Deploy a new Business Network called my-basic-sample, with description "The Composer basic sample network", then connect to it using the ID "Admin" and show the user the "Define" view.

Here's the design for that tile:
![image](https://user-images.githubusercontent.com/7454304/31074330-fb22b4da-a767-11e7-9f83-8742dbb889a4.png)

Here's the SVG for the illustration on that tile:
https://ibm.box.com/s/5d1obwji3vgdawcnsn6mni97n4nlfvzi

So the end result should be that there are wording changes, and also the first time a user heads to web Playground, they see that "Hello Composer" tile as well as the "Deploy New Business Network" option.  (And then, much like the current "Not sure where to start?" message, the tile goes away once they've got at least one business network to be working on).

**Comment by caroline-church** [comment]
Done so closing
