### ISSUE TITLE
Local storage not cleared between different installations

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#2275]
This is a big PITA for me and I'm sure many others.

Due to the way we abuse browser local storage, data persists across completely different installations of Hyperledger Composer that use the same hostname and port.

For example, if you run the vehicle lifecycle demo, then run the single line installer, the single line installer pops up a browser that still has the vehicle lifecycle business network card in it (and nothing else).

We need to either:
- Maintain some kind of "install ID" in the playground Docker container so that when the container is recreated, the "install ID" changes, and we can detect reinstalls and blat local storage.
-or-
- Use the local file system via the proxy connector to store ID cards for the non-cloud-hosted-playground, which will sort the problem as the ID cards directory will be blatted when the playground Docker container is blatted.

**Comment by EdMoffatt** [comment]
Chat over on Rocket.Chat suggests everyone in favour of the second option so far (just capturing that note here in case anyone sees this and wants to violently disagree ;) )

**Comment by caroline-church** [comment]
done so closing
