### ISSUE TITLE
As a Playground user, I need to be able to rectify a non-function connection profile configuration

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#228]
Playground is caching credentials in localStorage for the active connection profile. If this is set to HL and you restart HL, or the user used to connect is no longer present, then Playground will hang on the connect.

**Comment by dselman** [comment]
Workaround is to clear localStorage. On Firefox you can open the developer tools, go to the console and type `localStorage.clear()` and then refresh the page.

**Comment by EdMoffatt** [comment]
Clearing out things from the Playback 3 milestone.
I'm not clear from the current discussion whether this is something we'd plan to fix in Playback 4, but I'll assign it to that for now.

**Comment by bestbeforetoday** [comment]
Think this should be a scenario we deal with as part of identity registry. This will remove (or change) the use of local storage, so making any fix prior to that redundant.

**Comment by sstone1** [comment]
Closing, if this issue still exists please raise specific issues.
