### ISSUE TITLE
As a potential contributor, I can find a Vagrant image to get coding quickly

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#2283]
As discussed in the community call on 04/10/2017, there was interest in having access to a Vagrant image that allows potential contributors to get contributing quickly without having to set up a development environment.

As long as we don't force people to use Vagrant, I'm cool with this, and I'm pretty sure @jt-nti, @mbwhite or @davidkel have done something in this space!

**Comment by jt-nti** [comment]
Sounds like an excellent idea! David has a [ComposerVagrant](https://github.com/davidkel/ComposerVagrant) project and I use [composer-quickstart-vagrant](https://github.com/jt-nti/composer-quickstart-vagrant) for running Composer, i.e. rather than developing for it.

**Comment by erNail** [comment]
I've also added the vagrant box i'm currently using to GitHub: [hyperledger-composer-box](https://github.com/erNail/composer-vagrant-box)

**Comment by jt-nti** [comment]
I've updated/moved my vagrant project. [composer-devenv](https://github.com/jt-nti/composer-devenv) will now optionally install a complete development environment for latest or next versions. Any feedback most welcome.

**Comment by sstone1** [comment]
@jt-nti already has this sorted (see above), so closing.
