### ISSUE TITLE
Text overflow problem in playground txn successful notification

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#2295]
Text overflows from the Submit Transaction Successful notification in the playground

## Context

Submitted a transaction while following the playground tutorial

## Expected Behavior

Notifications should be big enough for the text they contain

## Actual Behavior

Text overflows

![image](https://user-images.githubusercontent.com/3535067/31230562-524e29f8-a9dc-11e7-8928-188b296cdf9b.png)

## Possible Fix

Make the notifications bigger, or change the design- lots of notifications collecting in the top right already get in the way so making them bigger could make things worse.

Alternatively, better word wrapping (including breaks inside the long ID string) would probably work.

## Steps to Reproduce

1. Follow playground tutorial
2. Submit transaction
3. Enjoy notification overflow

## Your Environment

* Version used: 0.13.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): Safari 10.1.2
* Operating System and version (desktop or mobile): OSX (desktop)

**Comment by jt-nti** [comment]
@bestbeforetoday reports that this also happens on Mac/Firefox

**Comment by sstone1** [comment]
P3 and no action in three months; clearly not important and never going to get fixed, so closing.
