### ISSUE TITLE
As a user, I don't see a business network card for the web runtime if any "real" cards exist

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#2296]
Having web and Fabric v1.0 business network cards shown together just causes confusion.
Currently the web ones are shown at the top, which mean users jump to using it.
This results in "I deployed a business network! Why doesn't my REST server work?" problems.
We are looking at moving it to the bottom.

I can't think of a good use case for having the web one shown when a card for a real Hyperledger Fabric instance exists - why wouldn't i just use that instead?

**Comment by caroline-church** [comment]
i agree with moving it to the bottom

**Comment by sstone1** [comment]
Believe this has already been done.
