### ISSUE TITLE
Filter Test Tweaks

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#2298]
As discussed, the current filter tests could do with a few tweaks to assist with the test clarity

loopback-connector-composer/test/filterparser has 100% code coverage, but is missing some explicit isolated tests for methods that are currently being driven by parseWhereCondition. 
- parseObjectValue is currently only forcing two errors to be thrown, parseWhereCondition tests are currently forcing the remainder, so should move the tests to be under parseObjectValue
- isDateTime also needs to test the false conditions (null, object, string, int, undefined etc)
- isPrimitiveType is missing explicit tests for error condition (null or undefined) and valid condition (string, number or boolean)

#2454 now contains the changes needed for composer-rest-server

**Comment by fenglianxu** [comment]
close this issue now as it is merged.
