### ISSUE TITLE
As a developer I want access to the documentation

### ISSUE THREAD

**Issue by rynchase** [hyperledger/composer#2301]
I am getting a 404 on https://hyperledger.github.io/composer/jsdoc/index.html I was directed to that URL from the composer documentation site.

## Context
I am trying to build an application and would like to have access to the composer-client documentation.

## Expected Behavior
I would expect the documentation to be there.

## Actual Behavior
There is a 404 page.

## Steps to Reproduce
1. Go to url https://hyperledger.github.io/composer/jsdoc/index.html

**Comment by mikailcetinkaya** [comment]
Please try : https://hyperledger.github.io/composer/introduction/introduction.html
and do not forget to close issue if done

**Comment by nklincoln** [comment]
@rynchase - it is unclear if you have tried to link to the stated url from the current website, or if you were trying to access through a saved link. As mentioned above, the API reference is now in the main documentation:  https://hyperledger.github.io/composer/api-doc-inline/api-doc-index.html

**Comment by davidkel** [comment]
There is a broken link in our documentation. I have raised a github issue 
https://github.com/hyperledger/composer/issues/2326
If there are any more please could you update this issue.

**Comment by winslet** [comment]
Fixed with PR https://github.com/hyperledger/composer/issues/2325

Closing for now.
