### ISSUE TITLE
Yeoman Generator docs need updating

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#2308]
There's definitely some out of date stuff in the Generator docs.  Noticed it here: https://hyperledger.github.io/composer/business-network/bnd-create.html

If I run it right now, latest build, I see:
![image](https://user-images.githubusercontent.com/7454304/31280717-2a6eee6c-aaa5-11e7-91c6-186cf3ebc450.png)

And in the doc the options offered are different:
![image](https://user-images.githubusercontent.com/7454304/31280729-38c25ac6-aaa5-11e7-9142-25e01db44bd7.png)

There's another issue under P2 Bugs that talks about the generated CLI application, so I'll just go find that one and reference it, as it sounds like there might be some further updates to go in soon that we should stay up to date with :)

**Comment by EdMoffatt** [comment]
#1913 is the related issue I was thinking of!

**Comment by nklincoln** [comment]
probably falls under the remit of #3136

**Comment by davidkel** [comment]
The output of yo generator has now been updated in the docs.
