### ISSUE TITLE
Connection failures when using TLS to multiple peers.

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2314]
This was reported on RC a while back. An issue was already raised regarding this problem
https://github.com/grpc/grpc/issues/12642

As you increase the number of peers in a connection profile the likelyhood of hitting this problem increases. According to RC once they had 4 peers it was almost always.

It may also have become a problem when fabric-client changed its dependency from 1.2.4 to the latest grpc code which at the time was 1.6.0

I have raised a JIRA https://jira.hyperledger.org/browse/FAB-6266 to ensure hyperledger fabric are also aware of this issue.

**Comment by davidkel** [comment]
@jt-nti FYI as I see you had to fix grpc to a specific version due to an issue with fabric-ca-client. Also when we fix our final levels which will fix the grpc level we want to ensure we include the level that contains the required grpc fix (as of 1.6.6 release, there is no fix yet)

**Comment by jt-nti** [comment]
@davidkel we should be taking the grpc dependency out of our module ASAP, unfortunately there's no sign of a fabric fix yet...

https://jira.hyperledger.org/browse/FAB-6425

Is there someone we can nudge?

**Comment by davidkel** [comment]
grpc 1.7.1 hasn't fixed the problem. The build occasionally fails with this problem and as the number of peers increase the problem will be worse. Fabric really should be chasing the grpc folks about this. The Jira is now set to highest but really we need to find some way to get the grpc folks to get involved more. A comment on the forum suggests it could be a boringssl problem.

**Comment by davidkel** [comment]
The workaround is to add a x00 to the end of the cert in the node-sdk. It looks like the fix has gone into the master branch, but not into the release branch and so there isn't a soln for 1.0.x fabrics (ie no 1.0.5 fabric node sdk with a fix in).

**Comment by davidkel** [comment]
This workaround has gone into the node-sdk 1.1-alpha and already those builds are far more reliable.

**Comment by davidkel** [comment]
node sdk 1.0.3 contains the workaround as well. This will be included in the next release of the 0.16.x release
