### ISSUE TITLE
https://hyperledger.github.io/composer/jsdoc/index.html not found

### ISSUE THREAD

**Issue by danielsun1106** [hyperledger/composer#2315]
1) Visit `https://hyperledger.github.io/composer/jsdoc/index.html` 
2) Get the following error messages:

```
Oh no!…there’s no blockchain here :(

If you fancy telling us about this please raise an issue on our Github
```

**Comment by davidkel** [comment]
@danielsun1106 did you just try this url yourself or was it a link from somewhere ? If it was a link could you please say where the link is as it is an invalid link.

**Comment by danielsun1106** [comment]
@davidkel I visited the link directly from my browser. It is still broken now...

**Comment by davidkel** [comment]
@danielsun1106 that link is now not valid as it looks like the api reference documentation has been restructured. So using directly isn't going to work. However if there were links to it from within our documentation then that would need to be fixed.

**Comment by davidkel** [comment]
So the issue I have raised about a broken link is
https://github.com/hyperledger/composer/issues/2326
Another person raised a similar issue here
https://github.com/hyperledger/composer/issues/2301 and note that it says the url is now not a valid url so won't work if directly used.
