### ISSUE TITLE
Possibility to enable grpc keepalive

### ISSUE THREAD

**Issue by vadimuvin** [hyperledger/composer#2317]
In our cloud setup we need to enable grpc keepalive on all connections from composer, as otherwise the load balancer we use clothes them after 15 min of inactivity. This results in various timeouts in the Composer app.

## Context

It is possible to enable keepalive in the node SDK by specifying additional connection parameters, such as 

```
{
    'grpc.keepalive_timeout_ms': 60000,
    'grpc.http2.max_pings_without_data': 0,
    'grpc.keepalive_time_ms': 400000,
    'grpc.keepalive_permit_without_calls': 1,
}
```

However, it seems that there is currently no possibility to set these options in the composer-connector.

## Expected Behavior

It should be possible to enable grpc keepalive in the composer-connector.

## Actual Behavior

Composer-connector connection parameters are hardcoded and do not include keepalive-related parameters as seen here:
https://github.com/hyperledger/composer/blob/3f38f4b0a150bf65c2e9a41030b611859c0fa8f1/packages/composer-connector-hlfv1/lib/hlfconnectionmanager.js#L106-L130

## Possible Fix
It should be possible to specify additional parameters in the connection profile file.

## Steps to Reproduce

Run any composer app in the Docker Swarm, the connections will timeout after 15 min.

## Your Environment
- Composer 0.13.2

**Comment by davidkel** [comment]
Support for this is now available in the latest version of composer 0.17 as it makes use of the Common Connection Profile defined by the node-sdk which includes support for these options.
