### ISSUE TITLE
Work required to establish a v0.14.0 releases

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#2319]
A number of breaking changes will be going into the v0.14.0 release that is planned for this week. 
This issue is to track the essential work and checks that need to take place prior to this occurring. 

As per normal release schedule, this is expected Thursday 12th October 2017 

This is tracking these and making sure that none are forgotten. Expecting this issue to be closed on release when notes have been captured in contrib notes.

- [x] 1: update all tutorials (including vids) to get past the 'no admin' roles
- [ ] 2: update validation guides
- [x] 3: version bump all samples (and remove/prune lower versioning bound)
- [x] 4: version bump node red nodes (tools)
- [ ] 5: check one line installer still works
- [x] 6: update (fix) VLC network
- [x] 7: Create a doc in the contrib notes about the effects of version updates  <--use this issue to 
- [ ] 8: API changes to remove 'escaped' methods (to mark methods as deprecated)
- [x] 9: TX Function updates for the Reset business network
- [x] 10: Add banner to homepage announcing release and pointing to release notes

**Comment by mbwhite** [comment]
FYI Will be working on 9, 8 in due course.

**Comment by EdMoffatt** [comment]
FYI, I'll work on 10.  And I'll also keep an eye out for whether I can pick up 1 when we have a preview in an unstable build to screengrab from :)

**Comment by mbwhite** [comment]
I've descoped item 6 - we'll have a similar version bump in a few weeks.
Out of runway, will do a PR with @deprecated as a warning.
