### ISSUE TITLE
composer runtime API documentation is missing as of 2017/Oct/10th

### ISSUE THREAD

**Issue by ibmamnt** [hyperledger/composer#2325]
Summary:
 Composer Runtime API documentation is missing as of 2017/Oct/10th release.
 https://hyperledger.github.io/composer/api-doc-inline/api-doc-index.html

Details:
 Request of issue came from my question related to APIs which can be used inside transaction processor.  

 https://stackoverflow.com/questions/46657117/what-apis-can-be-used-inside-transaction-processor

**Comment by jt-nti** [comment]
There is currently a copy of the old style jsdocs API documentation available which still includes the runtime module if that helps for now...

http://bit.ly/hcapi

(It is likely to go away once the API documentation has been fixed on the main website, with the search function back, so don't rely on links staying around.)

**Comment by nklincoln** [comment]
dropping priority on this item as the original api docs have been temporarily reinstated

**Comment by mbwhite** [comment]
A DRAFT of the newly styled docs, with runtime is [available ](https://mbwhite.github.io/api-doc/composer/unstable/api-doc-inline/client-businessnetworkconnection.html)

Please do add comments.

**Comment by mbwhite** [comment]
Contained with PR #2494
