### ISSUE TITLE
The auto expanding TOC on web page is awkward to use and not very accessible

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2327]
Users have reported that the auto expanding TOC on hover isn't a great experience.
I find it actually rather awkward to use and does get to be a bit annoying. I also tried to use it in chrome just using the keyboard and found that it was difficult and actually doesn't work properly. So this in itself is a problem in that our website is not very usable accessibility wise.

Here is an example of the mess the TOC gets in and all I did was try to tab through the sections
![image](https://user-images.githubusercontent.com/25582377/31375280-ec8e27ce-ad98-11e7-9375-51a0cf81b047.png)

**Comment by EdProsser** [comment]
Could we change to the more traditional (or antiquated depending on your viewpoint) arrow system?

> Text -- unexpanded
V Text  -- expanded

Click the arrow to expand or collapse etc. @winslet ?

**Comment by winslet** [comment]
Yeah we could, im currently looking at how we could modify the docs styling anyway so this could be pulled into that work potentially.

**Comment by winslet** [comment]
These are the interactions we would like to implement:

![artboard](https://user-images.githubusercontent.com/13980028/31667159-8507fcc0-b346-11e7-9a1d-571296141251.png)

This sorta thing is out of my development knowledge so it will need some real help! @caroline-church what are the chances of getting some time on this dyou think?

**Comment by caroline-church** [comment]
Depends what sort of help you want? If it's my time to do it not very likely, if it's just some help I can try and help

**Comment by EdMoffatt** [comment]
I'll add this to my list of stuff to have a bash at this week :)  Might not get everything working, but I'll try and make some progress on it!

**Comment by EdMoffatt** [comment]
@mahoney1 mentioned yesterday that there's an impending need for another level of nested navigation, as we move to add more Tutorials.  We should add this to the requirements as we're looking at this issue.

We should also note that there was some discussion yesterday around the idea of pulling the API docs back out into a separate page but maintaining the same header as the main page (so e.g. we'd have "API" up there in the top right along with Docs).  So we'd need to update these bits...

![image](https://user-images.githubusercontent.com/7454304/32268325-802ca150-bee6-11e7-87ca-c2b1db61518c.png)

![image](https://user-images.githubusercontent.com/7454304/32268327-85c242fa-bee6-11e7-9312-2233ae1c7be8.png)
