### ISSUE TITLE
Documentation required for defining cards and connection profiles in environment variables

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2328]
I tried to find information about the various environment variables that composer can use to avoid using the file system for connection profiles and id cards but was not able to find any.

We need to provide this documentation.

**Comment by davidkel** [comment]
So with the release of cards, the current situation is this
1. Playground has a concept for defining stuff in an environment variable called COMPOSER_CONFIG
2. The CLI, REST Server and Client APIs have another definition for COMPOSER_CONFIG which is based on Connection Profiles, it allows you to define 1 or more connection profiles but this is probably not valid now for the new card based environment, so it's probably not correct and we need to come up with a card based solution.

**Comment by sstone1** [comment]
Replaced by CIP #3121.
