### ISSUE TITLE
More information about the Wallet API required

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2329]
We have a wallet api that allows you to store certificate information in alternative storage systems as opposed to the keyValStore entry in a connection profile.
The only example of this api and how to use it is here
https://github.com/sstone1/sample-bluemix-composer-app
We need to provide official documentation for this very useful feature.

I don't know of the wallet api and usage will be affected by the upcoming id card implementation
@bestbeforetoday should be able to provide more information.

**Comment by sstone1** [comment]
Replaced by CIP #3121.
