### ISSUE TITLE
Support cards in 'composer network' commands

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2333]
**As a** user of Composer
**I want** to use business network cards with `composer network` commands
**so that** I do not need to specify connection profile, business network name, enrollment ID and enrollment secret explicitly on every command

Add support for a `--card` parameter to the following `composer network` sub-commands (in rough priority order):
- [x] deploy
- [x] start
- [x] ping
- [x] list
- [x] update
- [x] upgrade
- [x] undeploy
- [x] loglevel
- [x] download

**Comment by mbwhite** [comment]
Will split out the list and deploy

**Comment by mbwhite** [comment]
I've pushed changes for this support - there is a connectWithCard API added that can be used at present.

**Comment by bestbeforetoday** [comment]
Note that when a card that contains certificates is used, we need to use those certificates to connect, and not any enrollment secret that may (or may not) exist in the card.

**Comment by mbwhite** [comment]
Yes - I think we need a separate issue to cover that as it's below the level of the actual CLI commands. 
Latest PR has updates for the deploy commands to be card native.

**Comment by mbwhite** [comment]
Merged into the composer runtime-idcards branch https://github.com/hyperledger/composer/pull/2495
