### ISSUE TITLE
Support cards in 'composer runtime install' command

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2334]
**As a** user of Composer
**I want** to use business network cards with `composer runtime install` command
**so that** I do not need to specify connection profile, business network name, enrollment ID and enrollment secret explicitly

Add support for a `--card` parameter.

**Comment by mbwhite** [comment]
See PR https://github.com/hyperledger/composer/pull/2456

**Comment by mbwhite** [comment]
See PR #2500
