### ISSUE TITLE
Support cards in 'composer identity' commands

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2336]
**As a** user of Composer
**I want** to use business network cards with `composer identity` commands
**so that** I do not need to specify connection profile, business network name, enrollment ID and enrollment secret explicitly

Add support for a `--card` parameter to the following `composer identity` sub-commands (in rough priority order):
- [x] issue
- [x] bind
- [x] list
- [x] revoke

## Notes
It would be ideal if the `composer identity issue` and `composer identity bind` commands could produce a card that could then be sent to the participant. With _bind_, this is a bit trickier, as you will only have the certificate (the public bit) of the participants identity. I guess you could build a partial card with what you have.

**Comment by mbwhite** [comment]
We need to be able to get an ID Card to roundtrip ID cards from playground to app and back again. 
Therefore tackling the issue command to resolve to a ID card

**Comment by mbwhite** [comment]
Update: now pushing all changes to the *runtime-idcards* branch; updating those identity commands that I believe are still needed; leaving the others to be remove in a later story

- [ ] Issue Identity
- [ ] Bind Identity -->  Believed to be redunant?
- [ ] List Identitiies
- [ ] Request --> Believed to be redundant
- [ ] Revoke

**Comment by bestbeforetoday** [comment]
`composer identity bind` still to do.
