### ISSUE TITLE
API Docs link is broken

### ISSUE THREAD

**Issue by chsriman** [hyperledger/composer#2345]
The link https://hyperledger.github.io/composer/jsdoc/index.html is broken

**Comment by winslet** [comment]
hey @chsriman as an immediate help for you, the API reference documentation has been moved into the main docs site at https://hyperledger.github.io/composer/api-doc-inline/api-doc-index.html

But you raise a great point, we should put a redirect on that URL.

I think @mbwhite is looking into sorting this as we speak. 👍

**Comment by mbwhite** [comment]
See pr #2346

**Comment by winslet** [comment]
Merged so closing.

**Comment by winslet** [comment]
Merged so closing 👍
