### ISSUE TITLE
Deploy Button can be active when invalid characters are present

### ISSUE THREAD

**Issue by samjsmith** [hyperledger/composer#2355]
When editing a business network, Playground allows users to edit the name of the business network and the files contained in it. Certain special characters are not allowed e.g. `!`
However, in the Define tab, it is possible to edit filenames and the business network name to give them valid names, thus enabling the 'Deploy' button.
However, users can then re-edit, introduce invalid characters and the 'Deploy' button remains available. 
When clicked, it seems as though the Deploy happens, but uses the values that were previously flagged as being valid. 

## Expected Behavior

The deploy button should be disabled whenever an invalid character is added

## Actual Behavior

The deploy button was enabled

## Steps to Reproduce

Described above

## Context

General testing of the Playground UI

## Your Environment

* Version used: 14 unstable
* Environment name and version (e.g. Chrome 39, node.js 5.4): FFox 
* Operating System and version (desktop or mobile): Mac

**Comment by sstone1** [comment]
P3 and no action in three months; clearly not important and never going to get fixed, so closing.
