### ISSUE TITLE
Copy button for examples in the docs hide information

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2356]
![image](https://user-images.githubusercontent.com/25582377/31496099-f32d293a-af51-11e7-964a-8ea40427617e.png)

Note that a rather important `-S` option is actually hidden. Without it you get some horrible error message (which will have another issue raised about it).

**Comment by winslet** [comment]
hmm previous fix https://github.com/hyperledger/composer/pull/2057/ doesn't seem to have worked properly :/ ill see what we can do...

**Comment by winslet** [comment]
Fix in #2392 - looks like it was a one line fix to make sure the right hand padding was correct 👍
