### ISSUE TITLE
Initial start/deploy binding defaults to the start/deploy identity if no other identity is provided

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2362]
Existing users (unless they read the release notes) are likely going to end up binding the NetworkAdmin to PeerAdmin (as that is a fabric id required to deploy). Given we have tried really hard to advise that PeerAdmin should only ever be used at deployment and never in the context of a business network the current implementation can make it too easy to do. Also with issue identity you really need to be an issuer as well as someone with authority to perform the issue transaction (this is noted in the docs however) and PeerAdmin isn't an issuer.

Some considerations to perhaps make this a bit more user friendly for discussion
1. Maybe a safer approach would be to not allow deployment or start without providing an initial identity to bind to a networkadmin rather than allowing it and binding to the Channel Admin identity as the business network admin.
2. Display a warning or prompt the user to continue if that's what they want
3. Output a message to say who was bound as a NetworkAdmin

**Comment by sstone1** [comment]
Believe this is no longer applicable now.
