### ISSUE TITLE
composer identity issue requires an identity that has multiple roles in order to work

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2363]
Composer identity issue the following abilities
1. It requires CA issuer authority (CA type role) 
2. It requires the ability to invoke IssueIdentity transaction (BN type role)
3. it requires the ability to connect to a network (BM Type role)

If an organisation wanted to be able to separate these out then currently there is no way to do so. The likelyhood means that 2 and 3 will be a network administrator bound at start/deploy time and would then have to also be an issuer as well in order for identity issue to work.

Is it worth considering being able to perform this via 2 separate actions
1. Be able to register and request certs for an identity
2. Be able to associate that registration either via issue or bind depending on whether the certs were requested.

**Comment by sstone1** [comment]
@davidkel they could use the `fabric-ca-client` command to register a new ID, get the participant to enrol, and the participant to send their certificate to another participant with access to `BindIdentity`.

**Comment by davidkel** [comment]
@sstone1 they could (but a bit nasty to have to get the source and compile from scratch). Could we in the future be using other CA Servers where we might want to try to have a common capability ?

**Comment by sstone1** [comment]
Closing as per discussions around `fabric-ca-client`.
