### ISSUE TITLE
If an id card contains both certificates and an enrollment secret, it looks like the enrollment secret is used over the certificates

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2374]
If someone creates an id card by hand as described in our documentation and includes both certificates and an enrollment secret. The certificates should be used and not the enrollment secret but it looks like the enrollment secret is used always if present.

**Comment by markcastle3** [comment]
@KaiUsher are you able to look at this one ?

**Comment by markcastle3** [comment]
@KaiUsher did you get a chance to look at this one ?

**Comment by mbwhite** [comment]
Based on the recent changes this has been resolved... if this has regressed do please re-open it..
