### ISSUE TITLE
On playground when creating connection profiles, eventhub definitions should be optional

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2375]
In order to support multi-org topologies where you want to connect to peers in another organisation, event hubs definitions for other orgs are most likely not required so mustn't be a required field.

**Comment by caroline-church** [comment]
@awjh-ibm can you make sure this bugs gets incorporated into the common connection profile work please

**Comment by davidkel** [comment]
@caroline-church @awjh-ibm This isn't relevant to the common connection profile. It is really only relevant to how we do things now. In the CCP world it should be defined
