### ISSUE TITLE
HLF 1.1 feature to distinguish between client and server certificates.

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2377]
The following capability is being added to Hyperledger Fabric and is currently scheduled to be in their 1.1 release, may have an impact on composer. 
see https://jira.hyperledger.org/browse/FAB-3621 and https://jira.hyperledger.org/browse/FAB-5664
FAB-5664 is likely going to be tech preview in 1.1 (with a feature toggle) which means for composer to work with 1.1 we might not need to support this capability initially.

**Comment by sstone1** [comment]
No impact on Composer spotted from the preview and alpha builds; closing.
