### ISSUE TITLE
Deploy empty business network in Playground causes errors

### ISSUE THREAD

**Issue by samjsmith** [hyperledger/composer#2380]
## Context

It looks like a bug.

## Expected Behavior

The dev console shows lots of errors when you select the Empty Business Network to be deployed in the Playground UI.  The card at the side is also lacking information.

## Actual Behavior

The errors should be dealt with gracefully and maybe the 'Contains' section should say 'Empty' or something

## Steps to Reproduce

1. Log on to playground
2. Click `Deploy a Business Network` card
3. Open Browser dev tools
4. Select `Empty Business Network`
5. Observe errors
![image](https://user-images.githubusercontent.com/16335033/31608752-6c906af2-b269-11e7-8f07-257852566b41.png)
![image](https://user-images.githubusercontent.com/16335033/31608761-7089ee12-b269-11e7-86f3-292c1af80e6c.png)

## Context

Just a nitpick really

## Your Environment

* Version used: 14
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome
* Operating System and version (desktop or mobile): Mac
* Link to your project:

**Comment by awjh-ibm** [comment]
this appears to be a bug with the fix I implemented for #2149
