### ISSUE TITLE
404 from Documentation page

### ISSUE THREAD

**Issue by samjsmith** [hyperledger/composer#2381]
1. Go here: https://hyperledger.github.io/composer/introduction/introduction.html
2. Search for something.
3. Click one of the Titles in the LHS and get sent to `https://hyperledger.github.io/tutorials/tutorials.html` which is missing the `composer` part of the fragment according to @mbwhite

**Comment by mbwhite** [comment]
The search page is at a different directory level, therefore the sidebar links were wrong. Corrected.

**Comment by mbwhite** [comment]
I did spot the search box wasn't getting focus when clicked.. added the jquery to support that.
