### ISSUE TITLE
When creating a new transaction in VS Code the editor autocompletes with an identifier field

### ISSUE THREAD

**Issue by pastadin** [hyperledger/composer#2385]
As the name suggests, when you use the autocomplete feature in VS Code to write a new transaction the result is this:

`transaction transactionName identified by transactionKey {
  o String transactionKey
}`

Given that identifiers are no longer used in the model files, the following should be used:

`transaction transactionName {
  o String transactionKey
}`

**Comment by sstone1** [comment]
@m-g-k can you look at this please?

**Comment by m-g-k** [comment]
Sure, np :-)

**Comment by m-g-k** [comment]
This is now fixed in the latest version of the VSCode plugin (v0.15.0).  FYI, "Event" snippets also had the same "identified by" issue and are now fixed along with "Transactions".
