### ISSUE TITLE
As a Business Network administrator I want to be able to modify the endorsement policy of a running network

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2386]
Scenario:
Consider a multiorg fabric setup. Which currently has 2 orgs defined with a policy that both orgs must endorse. Then Org3 joins and they want to also endorse before a transaction is committed, currently there is no way to do that through composer. Composer may not support that capability but it's a question that gets asked. So how would one do it ?

**Comment by mikailcetinkaya** [comment]
Updating channel artifact created when channel is also created. configtxgen tool usage on http://hyperledger-fabric.readthedocs.io/en/latest/build_network.html

**Comment by sstone1** [comment]
@davidkel is this not something that can be achieved via a chaincode upgrade call?

**Comment by davidkel** [comment]
@sstone1 you can pass the endorsement policy on an upgrade (and we should add support for that as we currently don't support doing that). But that doesn't feel the right approach for just changing the endorsement policy as it may run the upgrade path of the init call of the chaincode and it may not upgrade unless you have a new version to upgrade to, but I haven't tried it so worth adding support and trying it out. I suspect there must be some other way to perform a config update of this type but I don't see that (outside of deploy/start/upgrade) it's something composer needs to support but it would be useful to know and point to some fabric documentation as part of our guide on how composer interacts with fabric (still needs to be written), along side the requests we get for describing endorsement policies etc.

**Comment by mikailcetinkaya** [comment]
@davidkel i am willing to participate on this. But donot know where to start

**Comment by Rmannn** [comment]
Any news or docs to update policies without upgrading ?
Should we update the channel to do it ?

**Comment by davidkel** [comment]
@Rmannn This won't be added to the 0.16.x release of composer. In the `next` version of composer this is now possible, however the limitation is that you have to do it during a runtime upgrade and this is a big limitation. There are big changes coming to how we deploy a business network internally in the next release which will provide a much better way to upgrade and be able to alter the endorsement policy.

**Comment by Rmannn** [comment]
Thank you @davidkel for clarifications.
