### ISSUE TITLE
As a network deployer I would like the ability to turn off explorer and swagger.json from the rest server

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2388]
The rest server exists for end user applications such as UI applications to interact with a business network. The explorer and possibly swagger.json exist purely for use in a development environment and not a production environment. Therefore it would be good to have switches that can disable each in order to not expose capabilities of a rest server that are not required.

**Comment by sstone1** [comment]
Not going to do this unless raised as a user requirement, so closing.
