### ISSUE TITLE
As a user if I query historian can I get the results in commit order.

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2389]
I don't believe you can't use transaction timestamp to guarantee the commit order here. The transaction timestamp (whether it is from composer or fabric) is when the client submits the transaction, it then must transfer over the network to the BN to be executed, then the endorsement results have to be sent back, then those endorsements have to be sent to the orderer, the orderer has the capability to change the order before sending to the peer to actually commit the blocks. So it is unlikely that this is a safe assumption.

This could very well require help from HLF in order to work out how to make this achievable.

**Comment by sstone1** [comment]
Closing as we're not going to look at this until we get requirements from users.
I assume it is possible today to use the transaction IDs in the historian along with the transaction IDs in the blocks returned by the Fabric IDs to order the list of historian records?
This could lead into a whole epic here around how we map Composer transactions to Fabric transactions and blocks, and make the aggregated information available via some sort of operational tool.
