### ISSUE TITLE
on CLI multiple same options can result in strange error messages

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2390]
For example consider this
`composer participant add -p hlfv1 -i PeerAdmin -s f -d '{"$class":"org.hyperledger.composer.system.NetworkAdmin#fred"}' -n digitalproperty-network -n`

gave the error
`Error: Illegal value for Message.Field .protos.ChaincodeID.name of type string: object (no array expected)`
which isn't very helpful.
The CLI's themselves should be policing these and giving useful error messages. The is just one example, there are likely to be others.

**Comment by mbwhite** [comment]
Yes; there are others - it requires custom error handling;

See `card\lib\createCommand` for the approach.  This should be moved into a general fn... yargs doens't have a 'singleton' marker for options.

**Comment by davidkel** [comment]
Think this has been addressed now ? guess if it hasn't and it is an issue it will get raised again.
