### ISSUE TITLE
Update / re-import business network cards using CLI

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2397]
**As a** user of Composer
**I want** to update a previously imported business network card using the CLI
**so that** I can modify card details, such as the connection profile

## Design Issues

What is the preferred approach to achieving this? Some ideas to consider...
1. `composer card delete` followed by `composer card import`. `composer card import` of a previously imported card is an error.
1. `composer card update` command. `composer card import` of a previously imported card is an error.
1. `composer card import` overwrites existing card (optionally with a warning message).
1. Supplying an additional parameter to `composer card import` allows an overwrite (maybe... `--force`, `--overwrite`, `--update`). Import of a previously imported card without this option is an error. What should the behaviour be if the additional option is supplied and this is not a re-import?

**Comment by mbwhite** [comment]
Option #1 is a common paradigm  - and for the moment this can be followed by using other stories.

No specific value in doing a dedicated update command at present.

**Comment by bestbeforetoday** [comment]
Going with option 1, which means the `composer card import` command should error when importing a card with a name matching a previously imported card.

**Comment by mbwhite** [comment]
https://github.com/hyperledger/composer/pull/2456 has initial support for these with card Create, Export now available. 

However the next issue to addres here is the export/import of certificates
