### ISSUE TITLE
Possible timing issue where hlfv1 connector can miss a transaction committed event

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2399]
There is a small window of opportunity where a transaction is sent to the orderer which sends it to the peer which then commits it which then emits the event. Once the success message is received by the orderer the connector sets up the listeners for the commit event and there is a possibility that the event is emitted before the connector has an opportunity to setup the event listeners on all the peers.

To fix this we should register the listeners before sending the message to the orderer, but if there is a failure, cancel the listening otherwise wait for the events as normal.

**Comment by davidkel** [comment]
This will be addressed with the CCP work

**Comment by davidkel** [comment]
@sstone1 should this be considered for the final composer version that supports 1.0.x ?

**Comment by sstone1** [comment]
@davidkel I'll take as many bug fixes as we can squeeze in 😄

**Comment by davidkel** [comment]
@sstone1 ok, I will put this one in, cheers

**Comment by davidkel** [comment]
Closing as now complete.
