### ISSUE TITLE
Refactor Playground to use card-based APIs

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2401]
Once card-based APIs are in place and working on AdminConnection and BusinessNetworkConnection, all the Playground code will need to be refactored to use these new APIs.

**Comment by mbwhite** [comment]
Playground is today using the same connect calls as previously; it's stable and working. 

As such I don't think that at this stage we should attempt to modify this.

**Comment by bestbeforetoday** [comment]
We absolutely do have to modify Playground before we can declare the runtime card native.

**Comment by caroline-church** [comment]
done so closing
