### ISSUE TITLE
As a maintainer, I can easily access code coverage information

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#241]
I'd like to see us try out the use of Coveralls (https://coveralls.io) in our continuous integration system.
There are two features I like:

1. Code coverage levels are visible outside of the logs of our Travis CI builds, and can be viewed online at all useful levels (project, directory, file, line).
2. Code coverage level changes can be made visible on a PR similar to a Travis CI pass/fail, so maintainers can easily see if someone is trying to merge a large amount of untested code.

Coveralls is free for open source projects, so there should be no blocker to trying it out.

**Comment by mbwhite** [comment]
@sstone1  I've signed-up to test my own repos..  Only issue I can see is do we need to combine the coverage stats.
