### ISSUE TITLE
Import Business Network Card in Playground throws error

### ISSUE THREAD

**Issue by erNail** [hyperledger/composer#2416]
When trying to import a manually created Business Network Card into a local playground installation, the following error is thrown: `Required connection field not found: name`.

## Context

Following the [documentation](https://hyperledger.github.io/composer/playground/id-cards-playground.html), i've created a `connection.json` and a `metadata.json`:

```
//connection.json
{
    "type": "hlfv1",
    "orderers": [
       { "url" : "grpc://localhost:7050" }
    ],
    "ca": { "url": "http://localhost:7054", 
            "name": "ca.org1.example.com"
    },
    "peers": [
        {
            "requestURL": "grpc://localhost:7051",
            "eventURL": "grpc://localhost:7053"
        }
    ],
    "keyValStore": "/home/vagrant/.composer-credentials",
    "channel": "composerchannel",
    "mspID": "Org1MSP",
    "timeout": "300"
}
```

```
//metadata.json
{
    "name": "PeerAdmin",
    "description": "A valid Business Network Card",
    "businessNetwork": "maintenance-network",
    "enrollmentId": "admin",
    "enrollmentSecret": "adminpw",
    "roles": [
		"PeerAdmin"
    ]
}
```

After that, i zipped the files using `zip -r PeerAdmin.card .`. Now, when trying to import the card in a local playground installation, the error `Required connection field not found: name` is thrown.

Note: An fabric instance with a deployed network is running. It was deployed using `composer network deploy -a maintenance-network.bna -p hlfv1 -i PeerAdmin -s randomString -A admin -S`, and is pingable. The local playground was started using `composer-playground`.

## Expected Behavior

The import should be successfull.

## Actual Behavior

The import fails.

## Possible fix
I guess that the `connection.json` has to contain a `name` field ? That would be useful to add to the documentation about manually creating business network cards.

## Steps to Reproduce

1. Start the Playground locally using 'composer-playground'
2. Rename the [PeerAdmin.zip](https://github.com/hyperledger/composer/files/1398073/PeerAdmin.zip) to `PeerAdmin.card`
3. In the Playground, click `Import Business Network Card`
4. Drag and Drop the `PeerAdmin.card`

## Context

I'm trying to connect to my business-network using Playground.

## Your Environment

* Version used: Playground v0.14.0
* Operating System and version (desktop or mobile): Ubuntu 16.04 Vagrant VM

**Comment by caroline-church** [comment]
We do now require that connection profiles have a name. There is however a place in the docs that show them without a name that should be updated

**Comment by EdProsser** [comment]
The documentation has now been updated, so closing the issue. :)

**Comment by mostafaelsayyad** [comment]
@EdProsser 
I just updated the composer and I still have this error when creating new card to be used in the deploy command
Here's my command 
composer card create --file myCard.card --businessNetworkName perishable-network --connectionProfileFile $HOME/.composer-connection-profiles/hlfv1/connection.json --user admin --enrollSecret adminpw

thanks in advance
