### ISSUE TITLE
Test tab goes into error state if regex in model is changed and no longer fits already created assets/participants. 

### ISSUE THREAD

**Issue by EllisHenderson** [hyperledger/composer#2420]
If you create a field with a regex (for example; String test regex=/[a-z]/), create an asset or participant and then change the regex to no longer meet the requirements of the already created asset/participant (for example, String test regex=/[1-9]/), the test tab will go into an error state.

In this state, you are no longer able to view the contents of the affected registry and if your model violation is in an asset, upon clicking the asset registry the participant registry will still be displayed. Upon trying to create a new asset/registry, an error message will appear saying it's failed however the asset/participant will still get created and added to the registry - you just aren't able to see it. 

This allows for you to be able to create fields with conflicting regex's, putting the test tab into an irreversible error state since you can't view the registry to delete the problematic asset/participant. 

 

1. Create a basic-sample-network.
2. Add the following field to either SampleAsset or SampleParticipant in the model; 
            o String test regex=/[a-z]/
3. Create an asset or participant, depending on where you added the above field. 
4. Change the field to the following; 
           o String test regex=/[1-9]/
5. Attempt to view either the asset or participant registry, depending on what you created in step 3. 
6. Add a new asset or participant, meeting the standards of the new regex created in step 4. 

@EdMoffatt 
@sstone1

**Comment by sstone1** [comment]
Fixed in:
Issue2485 Filter returned objects to remove model-invalid instances #2597
