### ISSUE TITLE
As a Composer user, it would be nice to have a guide on how best to secure a bus-net

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#2424]
Composer enables multiple levels of security. There is the concept of PeerAdmin, ChannelAdmin, NetworkAdmin, as well as the ability to tune ACL rules.

It would be nice to have a concrete guide on all of this and how (best practice) to move from having a completely unlocked basic-sample-network, to locking it down in a meaningful way

**Comment by davidkel** [comment]
👍   This document will need to be written in the context of Hyperledger fabric as composer could be used with different underlying engines.
