### ISSUE TITLE
Protractor Scenario Test of Identity Export/Import/Revoke

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#2427]
As part of desired required scenario testing, an identity export/import/revoke establishing as a dedicated Protractor scenario test.

There is a pre-req here for a fabric instance to be created for use by the Playground.

This scenario involves:
- Import or create a business network
- Create a participant
- Open the Identity Registry and issuing of an ID Card for the participant
- Export the card
- Logout and import the ID card
- Login under the new credentials
- Open the Identity registry and inspect identity status in identity registry
- Change user in registry
- Revoke the identity that was created

**Comment by davidkel** [comment]
Closing as no further work will be done to playground as playground is only a tool for getting started with composer and not a production type tool.
