### ISSUE TITLE
Protractor Scenario Testing of Composer Playground

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#2428]
Playground Protractor testing should be extended to cover key user scenarios. This will result in single user-flows to ensure the golden path experience remains unbroken.

The required scenarios are:
- [x] Documented tutorial #2425
- [ ] Issue/Revoke ID: Import/create a bus-net, create participants, issue an ID Card and import immediately, logout and log back in under the newly issued ID. Inspect identity status in identity registry. Change user and revoke the ID. #2426
- [ ] Export/Import/Revoke ID: As above, but export ID. Logout, import ID, then access bus-net under newly imported ID Card. Inspect identity status in identity registry. Change user and revoke the ID. #2427

**Comment by davidkel** [comment]
Closing as no further work will be done to playground as playground is only a tool for getting started with composer and not a production type tool.
