### ISSUE TITLE
status: 500, message: Error: The current identity has not been registered: admin

### ISSUE THREAD

**Issue by LarissaAuberger** [hyperledger/composer#2430]
When performing operations such as   composer participant add -p hlfv1 -n 'vehicle-lifecycle-network' -i admin -s adminpw
as documented in e.g. https://hyperledger.github.io/composer/managing/participant-add.html
I see the message
status: 500, message: Error: The current identity has not been registered: admin

## Expected Behavior
1. The doc has to be fixed with correct operation.
There are more of these, e.g. issuing a new identity:
https://hyperledger.github.io/composer/managing/identity-issue.html

2. Need to understand how to perform these operations now

## Your Environment
npm --version
5.5.1

docker --version
Docker version 17.09.0-ce, build afdb6d4

docker-compose --version
docker-compose version 1.13.0, build 1719ceb

composer --version
v0.14.0

**Comment by LarissaAuberger** [comment]
BTW: I read relase notes https://github.com/hyperledger/composer/releases/tag/v0.14.0
However, I did not deploy BNAs using composer network deploy, but by running
cd packages/vehicle-lifecycle
cat installers/hlfv1/install.sh |bash
as descreibed in https://github.com/hyperledger/composer-sample-applications/tree/master/packages/vehicle-lifecycle

May be, this has to be fixed either.

**Comment by davidkel** [comment]
@LarissaAuberger you could only use the CLI if you have imported the correct admin identity that is being used by the vehicle lifecycle demo. By running the command and not having imported that admin identity you have enrolled another identity called admin which is not the same as the admin identity that has been registered by the composer runtime and is being used by the demo.

**Comment by LarissaAuberger** [comment]
@davidkel The release notes say "When running composer network deploy and composer network start, in addition to the normal parameters you would use, you should also include -A admin -S to bind the admin identity as a network admin participant. " However, composer network deploy and composer network start was done by the install.sh (I guess) and not by myself .  Should I have fixed install.sh first? Is there any option to correct the behavior now?

**Comment by davidkel** [comment]
@LarissaAuberger the admin identity has been bound to the network admin participant, but it is a different one to the one you are using with the CLI. The CLI didn't have an id called admin so it went to the fabric ca server to get one and got a new one, but it is a different identity called admin and is not the one that has been bound into the network admin participant.

**Comment by LarissaAuberger** [comment]
yes, I understand this - but how can I fix this now and bind it to the correct admin?

**Comment by DomainPrime** [comment]
@LarissaAuberger I ran into the same issue. I reran through the tutorial and noticed that the deployment command was different from when I did it back in the beginning of Sept. So I updated my composer and cli and was able to get everything working. I'm on composer 0.14.3

**Comment by cooluser2** [comment]
@DomainPrime, thanks for your response. Yes, I worked with David and finally it worked for me, too. I am closing this issue now.

**Comment by LarissaAuberger** [comment]
@DomainPrime , thanks for your response. Yes, I worked with Dave and finally it worked for me, too. I am closing this issue now.

**Comment by LarissaAuberger** [comment]
@nikosheng  Hi Nico, this worked for me:

When you ran the install of the business network there is a directory created called (in my install) composer-data-latest. In that directory you should see a .composer-credentials directory. You need to modify the connection profile you use with the CLI and change the keyValStore property to point to that directory.

So, after I changed keyValStore to (you need the full path):
"keyValStore": /......./vehicle-lifecycle/composer-data-latest/.composer-credentials
everything worked fine, because now the network uses the registered admin identity.

Hope this helps.

**Comment by nikosheng** [comment]
@LarissaAuberger Thanks Larissa. I also found out there is another solution. 

Since it is a identity registration issue, there is a command "composer identity" which could list all the identity your fabric has, and you could verify their status. Therefore, what we need to do is to first bind the identity such as person-1 to your chaincode participant, then import the person-1.card to composer wallet. Finally you could set person-1 as default identity, then it is authorized to manipulate the business network
