### ISSUE TITLE
help needed in composer-connector-hlfv1 package

### ISSUE THREAD

**Issue by sm86** [hyperledger/composer#2436]
## Context
I am trying to follow the tutorial guide: https://hyperledger.github.io/composer/tutorials/developer-guide.html

When I run the command:
`composer network deploy -a my-network.bna -p hlfv1 -i PeerAdmin -s randomString -A admin -S`

## Actual Behavior 
Error: Failed to load connector module "composer-connector-hlfv1" for connection profile "hlfv1". Module version mismatch. Expected 48, got 57.-Module version mismatch. Expected 48, got 57.-Module version mismatch. 

## Your Environment
* Version used: v0.14.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): Ubuntu 16.04, Node 6.11.4, npm 5.5.1

**Comment by davidkel** [comment]
Looks like you've done an npm install using node 8 and now you a trying to run it under node 6. When you installed it will have compiled native modules tied to the version of node you used when you did an npm install. You can't then change the level of node with the same modules. You will need to either uninstall and re-install or if you have written an application using the composer apis, delete the node_modules directory and do an npm install again.

**Comment by sm86** [comment]
Thank you @davidkel . That worked! 
The problem was while I was following steps in https://hyperledger.github.io/composer/installing/development-tools.html ./downloadfabric.sh had modified the current Node version to 6.x from 8.x. I have used nvm to port back.
