### ISSUE TITLE
Composer-CLI generates the BNA file [throw Error]: Failed to find class org.hyperledger.composer.system.NetworkAdmin 

### ISSUE THREAD

**Issue by aprilsnows** [hyperledger/composer#2439]
## Context
Get problem when use composer-cli to generate BNA file:
```
mkdirp ./dist && composer archive create --sourceType dir --sourceName . -a ./dist/hyperledger-composer-supply-chain-network.bna
```

## Expected Behavior
Should generate BNA file without errors

## Actual Behavior:
Error: Failed to find class org.hyperledger.composer.system.NetworkAdmin 
Error details:
```

> hyperledger-composer-supply-chain-network@0.1.0 prepublish 
> mkdirp ./dist && composer archive create --sourceType dir --sourceName . -a ./dist/hyperledger-composer-supply-chain-network.bna


Creating Business Network Archive


Looking for package.json of Business Network Definition
	Input directory: /.../node_modules/composer-cli/node_modules/yargs/yargs.js:1079
      else throw err
           ^

IllegalModelException: Failed to find class org.hyperledger.composer.system.NetworkAdmin 
    at ModelBinding.validate (/../node_modules/composer-common/lib/acl/modelbinding.js:178:23)
    at AclRule.validate (/.../node_modules/composer-common/lib/acl/aclrule.js:123:30)
    at rules.forEach (/.../node_modules/composer-common/lib/acl/aclfile.js:106:21)
    at Array.forEach (native)
    at AclFile.validate (/.../hyperledger-composer-supply-chain-network/node_modules/composer-common/lib/acl/aclfile.js:105:20)
    at AclManager.setAclFile (/.../node_modules/composer-common/lib/aclmanager.js:69:17)
    at Function.fromDirectory (/.../node_modules/composer-common/lib/businessnetworkdefinition.js:531:49)
    at Function.handler (/.../node_modules/composer-cli/lib/cmds/archive/lib/create.js:80:42)
    at Object.module.exports.handler (/.../node_modules/composer-cli/lib/cmds/archive/createCommand.js:31:30)
    at Object.self.runCommand (/.../node_modules/composer-cli/node_modules/yargs/lib/command.js:233:22)
```

related rule in ACL file:
```
rule NetworkAdminUser {
    description: "Grant business network administrators full access to user resources"
    participant: "org.hyperledger.composer.system.NetworkAdmin"
    operation: ALL
    resource: "**"
    action: ALLOW
}

```

## Possible Fix

This bug might relate to breaking release about the right of business network administrator (https://github.com/hyperledger/composer/releases/tag/v0.14.0)

## Steps to Reproduce

1. git clone git@github.com:aprilsnows/hyperledger-composer-supply-chain-network.git
2. cd hyperledger-composer-supply-chain-network
3. mkdir dist
4. composer archive create -a dist/hyperledger-composer-supply-chain-network.bna --sourceType dir --sourceName .

## Existing issues

No existing issues found so far

## Context

This bug stops me generating achieve file.

## Your Environment
* Version used:
* Environment name and version: node.js v6.10.0, composer-cli v0.14.1
* Operating System and version (desktop or mobile): macOS High Sierra (version 10.13)
* Link to your project: https://github.com/aprilsnows/hyperledger-composer-supply-chain-network

**Comment by aprilsnows** [comment]
No one faced this issue?

**Comment by shiseki** [comment]
Hi, I got the same problem with the old version of composer. I installed the latest version of composer (v0.14.2) with "npm install -g composer-cli", then the composer archive create completed successfully with a .bna file created. I suppose the older version of composer does not recognize NetworkAdmin.

**Comment by aprilsnows** [comment]
Great for you to fix the issue. But not good luck for me. I also try to update the version of composer to v0.14.2, but it still throws the same error.

**Comment by shiseki** [comment]
I updated composer-admin and composer-client to v0.14.2 as well as composer-cli. Did you updated them also? Here is extract from my package.json:  
"devDependencies": {
    "browserfs": "^1.2.0",
    "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "composer-admin": "^0.14.0",
    "composer-cli": "^0.14.0",
    "composer-client": "^0.14.0",
    "composer-connector-embedded": "^0.14.0",
    "composer-cucumber-steps": "^0.14.0",
    "cucumber": "^2.2.0",
    "eslint": "^3.6.1",
    "istanbul": "^0.4.5",
    "jsdoc": "^3.4.1",
    "license-check": "^1.1.5",
    "mkdirp": "^0.5.1",
    "mocha": "^3.2.0",
    "moment": "^2.17.1",
    "nyc": "^11.0.2"
  }

**Comment by shiseki** [comment]
Although my composer archive create completed successfully, when I tried to deploy the created .bna file with "composer network deploy", it failed with the following message: IllegalModelException: Failed to find class org.hyperledger.composer.system.NetworkAdmin 
It seems that something is wrong with NetworkAdmin.

**Comment by aprilsnows** [comment]
Thanks! After I updating all the composer-related packages in devDependencies, it works!
```
    "composer-admin": "^0.14.2",
    "composer-cli": "^0.14.2",
    "composer-client": "^0.14.2",
    "composer-connector-embedded": "^0.14.2",
    "composer-cucumber-steps": "^0.14.2",
```

**Comment by aprilsnows** [comment]
For the problem of deploying, I don't have any problems. Double check the version of your **global** composer-cli ?

```
composer -v
v0.14.2
```

**Comment by shiseki** [comment]
You are exactly right! My global composer-cli was of old version. I updated it and composer network deploy completed successfully. Thanks a lot.

**Comment by aprilsnows** [comment]
Welcome! I think we can close this issue.
