### ISSUE TITLE
As a end developer I want to be able to go from a cli deployed business network to playground

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#2448]
## Context
As a developer of Composer, I want to be able to go from a deployed network on the command line to view it inside of playground for demo purposes.

```
$ composer archive create --sourceType dir --sourceName . -a ./dist/bgn.bnacomposer archive create --sourceType dir --sourceName . -a ./dist/bgn.bna
$ composer network deploy -p hlfv1 -i PeerAdmin -s elephant -a ./dist/bgn.bna  -A admin -S

# create the admin business network card
$ composer card create -n block-game --file admin.card -j ~/.composer-connection-profiles/hlfv1/connection.json -i admin -s adminpw
$ composer card import --file admin.card

# create the new participant (not cardified yet)
$  composer participant add -p hlfv1 -i admin -s adminpw -n block-game -d '{"$class" : "org.example.game.core.Player",  "name"  : "Chloe", "tilesHeld": [] }'

$ composer identity issuecard --card admin@block-game --file chloe.card -u Chloe -a org.example.game.core.Player#Chloe --issuer

$ composer network list --card Chloe@block-game
```

Then start up Playground
- Import Chloe's card,
- Create new participant
- Create new identity
- Export identity

Then in CLI

```
$ composer card import --file alice.card
$ composer network list --card alice@block-game
```

**Comment by EdMoffatt** [comment]
Actually properly reading this flow carefully, there are a few bits I have questions on (that will probably fall out in a demo or documentation!):

1. What are all the arguments on issuecard?  I think I can guess at most of them, but -a to specify the Participant certainly seems odd, and having a command with "card" in it and then including a --card on it also seems kinda weird - if I didn't include that, would issuecard issue something other than a card?

2. When importing the card into Playground, where will it be?  Could the command line perhaps output a success message along the lines of "chloe.card was successfully created, and stored in <file_path>".

There are probably a ton of little bits like this to look at with the CLI: would love to do a pass through some time and check we're outputting as much useful feedback as we can etc :)  Maybe in my total ignorance of how it's supposed to work I'll suggest something usefu
l, who knows?!

**Comment by mbwhite** [comment]
@EdMoffatt good points - yes the CLI needs a walk over to make sure it's consistent. Been meaning to do it for ages !

1) Identity issue ideally should be card native command - but at present making it do either card or full details is was a bit trickty coding wise... so for the moment put it separately.  

The -a is what the `identity issue` command uses to refer to the actual participant reference. 

2) the --file is a path name so you could add a larger path.

**Comment by mbwhite** [comment]
Current feature branch 'runtime-idcards' and these sequence of commands is good to get a network deployed, 

```
cat ~/.composer-credentials/PeerAdmin | jq -r .enrollment.identity.certificate > PeerAdmin.cert  
cp ~/.composer-credentials/114aab0e76bf0c78308f89efc4b8c9423e31568da0c340ca187a9b17aa9a4457-priv key-private
composer card create  -j ~/.composer-connection-profiles/hlfv1/connection.json -u PeerAdmin -c PeerAdmin.cert -k key-private -r PeerAdmin

composer card import --file ./_cards/PeerAdmin@hlfv1.card 
composer network deploy --archiveFile ./packages/block-game-network/dist/bgn.bna --card PeerAdmin@hlfv1 -A admin -S 

composer card create -n block-game --file ./_cards/admin.card -j ~/.composer-connection-profiles/hlfv1/connection.json -u admin -s adminpw
composer card import --file ./_cards/admin.card 
composer card list        
composer network list --card admin@block-game

composer participant add --card admin@block-game -d '{"$class" : "org.example.game.core.GameNetworkAdmin",  "participantId"  : "AliceAndrews"}'
composer identity issue --card admin@block-game -u AliceAndrews -a org.example.game.core.GameNetworkAdmin#AliceAndrews --file ./_cards/AliceAndrews@block-game.card  
composer card import --file ./_cards/AliceAndrews@block-game.card    
composer card list                                                                                                                         
composer network list --card AliceAndrews@block-game                                                                                

```

**Comment by bestbeforetoday** [comment]
I think the card changes now delivered make this possible, and I have created a business network with the CLI, exported the business network card and then used it in Playground to connect successfully.
