### ISSUE TITLE
"yo hyperledger-composer:cli"  then "npm install" fails

### ISSUE THREAD

**Issue by chevdor** [hyperledger/composer#2457]
yo hyperledger-composer:cli`then `npm install` fails with `ERROR: manifest for hyperledger/fabric-peer:latest not found

## Context
It should not fail

## Expected Behavior
It does not fail...

## Actual Behavior
It fails :)

## Steps to Reproduce
`yo hyperledger-composer:cli`
then 
`npm install`

**Comment by sstone1** [comment]
Duplicate of:
Yeoman generator for CLI applications is out of date #1913
