### ISSUE TITLE
As a user I would like to be able to export a business network card from playground and use it in the CLI

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2459]
If I use the 1 line installer then this sets up an environment and runs playground in docker connected to a local dockerised fabric network. If I export the id card I then can't import it for use by the CLI because the connection profile it specifies is specific to the docker network and not the native environment.
Conversely if I export a card that is usable by the CLI, I cannot import it into a dockerised playground. 

The problem really is that the cards are not fully portable when everything is run locally and there is a mixture of native and dockerised environments running composer services.

We could just document this restriction of course.

**Comment by sstone1** [comment]
No more one line installer, so no need for this.
