### ISSUE TITLE
As a User I want to be able to use an BN card with already enrolled certs as the Discovery ID

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2461]
The rest server can use the file system for it's discovery identity and as such this can be pre-imported before starting the rest server.

If however I change the datasource to mongodb, then there isn't a way to preload the discovery identity into mongodb and would have to rely on enrollment to get the identity, but this identity may already have been enrolled and registered in the composer runtime which means thaqt it will fail either because the re-enrolled identity won't match the registered one (identity has not been registered), or the identity cannot be enrolled again.

Suggestion is that the discovery Identity defined when running the rest server will come from the file system card store and not from the defined datasource used by the rest server for wallets

**Comment by davidkel** [comment]
In order to be able to use mongo db, you can do the following to ensure discovery works
- composer network deploy -a mynetwork.bna -p hlfv1 -i PeerAdmin -s f -A admin -S
- composer-rest-server -p hlfv1 -n digitalproperty-network -i admin -s adminpw -N never
Important, you MUST run the rest server straight after deployment. Do not try to use the admin identity at all (eg composer network ping) otherwise you will enroll and register the admin identity into your local keyValStore. The rest server would then enroll a different admin identity and store it into mongodb and that identity will not be registered in the runtime.

**Comment by sstone1** [comment]
Fixed in latest code.

**Comment by leowyennhan** [comment]
@sstone1  has this been solved? Cause its not working on my end.
