### ISSUE TITLE
Playground Editor Validation Bugs

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#2464]
Issues found in the testfest

- [x] Editing Namespace
- [x] files aren't changed correctly when change network
- [x] current editor file isn't correct when change networks
- [x] new files can be added correctly

**Comment by caroline-church** [comment]
If package.json is left in error the changes aren't persisted

**Comment by nklincoln** [comment]
Linked model files:
 - Using vehicle lifecycle demo, change the base.cto, it will invalidate all other (linked) model files. Move to other model file(s) to fix them up, original (base.cto) file becomes invalid. Cannot fix the cyclic error :-(

**Comment by KaiUsher** [comment]
If two different networks/samples are in 'My Business Networks' and one has an error, that file will be displayed in the other network.

1. Deploy basic-sample-network.
2. Deploy animal-tracking-network.
3. Create error in model file of animal-tracking-network.
4. Connect to the basic-sample-network.
5. See animal-tracking-network file.

**Comment by caroline-church** [comment]
If you change the name space in the model file then fix all the problems in the acl file. The message says everything looks good but there is a red dot next to the acl file

**Comment by hancockp-at-ibm** [comment]
I clicked on the pencil icon to edit package.json, the title changes to "Editing package.json" but there is no way to get button to get out of edit mode.
I changed to the Test panel and then back to Define. The title changes back to V0.1.10 with the pencil icon but the text is still in edit mode. 
The anonymous icons on the top right of the panel which I think are 'preview' and 'raw code' do not work after going into edit mode

**Comment by RJackson1234** [comment]
Error created in Script file which was then corrected ... resulting screen is...

![image](https://user-images.githubusercontent.com/26481967/31952500-9af9a33e-b8d8-11e7-9b73-56f3a9ee2807.png)

**Comment by RJackson1234** [comment]
![image](https://user-images.githubusercontent.com/26481967/31952528-b673d684-b8d8-11e7-995d-d1f0be2905ea.png)

**Comment by KaiUsher** [comment]
If you create an error in a file the update button will become unclickable. However, if you then switch to the test tab and switch back again, the update button is clickable with the error still present.

**Comment by caroline-church** [comment]
If you edit the namespace then leave it in error, go to the test tab and come back you get an error model about the namespace

**Comment by EllisHenderson** [comment]
If you create a business network, then go back to my business networks, create another business network and attempt to connect to it -- it will have the same contents as the first business network.

**Comment by EllisHenderson** [comment]
If you change the namespace in a model file to throw an error, then change to a different model file, then change back to the model file with the changed namespace, the contents of the original model file will disappear. 

Below it will also say everything looks fine, whilst continuing to show an error on the left hand column where the files are located.

**Comment by EllisHenderson** [comment]
<img width="1256" alt="screen shot 2017-10-26 at 10 53 59" src="https://user-images.githubusercontent.com/15138976/32047091-dd3c6366-ba3c-11e7-9106-5fa2b49a2f6e.png">

Tested this on both Chrome/Safari -- When refreshing the playground within a business network the playground gets stuck in this error state. Unable to press any buttons, only way out is to clear local storage manually and refresh.

**Comment by caroline-church** [comment]
fixed in pr https://github.com/hyperledger/composer/pull/2496 so closing
