### ISSUE TITLE
Remove duplication of code to obtain user home directory

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2470]
There are several instances in the code of creating a path based on the user home directory similar to this:
```javascript
const homedir = require('homedir');
...
const h = homedir();
if (h) {
    return path.resolve(h, '.composer-connection-profiles');
} else {
    return path.resolve('/', '.composer-connection-profiles');
}
```
This should be replaced by use of `Util.homeDirectory()` in _composer-common_, for example:
```javascript
const composerUtil = require('composer-common').Util;
...
return path.join(composerUtil.homeDirectory(), '.composer-connection-profiles');
```
Note that `Util.homeDirectory()` handles the case where a home directory cannot be identified so no special-case code is required by the caller.

**Comment by sstone1** [comment]
Closing; no action since raised over three months ago and obviously not important.
