### ISSUE TITLE
Playground docs for Business Networks page do not match UI

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2476]
The buttons in the top-right of the screenshot and accompanying documentation for the [_Business Networks_ page](https://hyperledger.github.io/composer/playground/playground-index.html) do not match the Playground UI. The documentation mentions the **Connect using credentials** button, which is not called **Create Business Network Card**.

**Comment by sstone1** [comment]
P3 and no action in three months; clearly not important and never going to get fixed, so closing.
