### ISSUE TITLE
Update Fabric dev server scripts to create a PeerAdmin card

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2484]
**As a** Composer deployer
**I want** to have a PeerAdmin card available after running the one-line install
**so that** I immediately use my Composer install without manually creating and importing a Business Network Card

**Comment by mbwhite** [comment]
I've added a new script called `createPeerAdminCard.sh`.  This can be run in the same manner as any of the scripts such as `startFabric.sh`

This though needs to use the `composer-cli` and there is a version check for this at the start. Also it uses jq that is a central part of ubuntu.  (aside if thisisn't available then we just keep a copy of the certificate available)

This will create a peer admin card, and import it.

Therefore the typicaly dev flow would be

```
$ unzip fabric-dev-servers.zip
$ ./fabric-dev-servers/startFabric.sh
$ ./fabric-dev-servers/createPeerAdminCard.sh
$ composer network deploy --archiveFile ./packages/block-game-network/dist/bgn.bna --card PeerAdmin@hlfv1 -A admin -S 
$ composer card create -n block-game --file ./_cards/admin.card -j ~/.composer-connection-profiles/hlfv1/connection.json -u admin -s adminpw
$ composer card import --file ./_cards/admin.card 
$ composer card list        
$ composer network list --card admin@block-game
```

**Comment by mbwhite** [comment]
Resolved in PR # https://github.com/hyperledger/composer-tools/pull/64
