### ISSUE TITLE
composer card export/import command

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2486]
**As a** user of Composer
**I want** to export business network cards from my Composer runtime
**so that** I can either import them myself into another system, or send them to somebody else

Add a `composer card export` command.

Mandatory parameters:
- `--card` Name of the card to export.

Optional parameters:
- `--file` Name of the file to export to; defaults to _cardName.card_.

**Comment by mbwhite** [comment]
Changes are ready for this - but waiting for other items in QA to go in first - as they fix code coverage issues. I can't push this until that is.

**Comment by mbwhite** [comment]
Added the import as well to match. This will pull out the certificates and do an identity import if needed.
