### ISSUE TITLE
composer card create command

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2487]
**As a** user of Composer
**I want** to create business network card archives from a connection profile, business network name and user credentials
**so that** I do not have to manually create a card archive in order to use these details to deploy or connect to a business network

Add a `composer card create` command.

Mandatory parameters:
- `--connectionProfile` Connection profile file name.
- `--user` Name of the identity for the card.

Optional parameters:
- `--file` File name of the card archive to be created. Default is _userName@businessNetworkName.card_ if the card includes a business network name; otherwise _userName@connectionProfileName.card_.
- `--businessNetwork` Name of the business network this card is associated with.
- `--enrollmentSecret` Secret used to obtain user credentials (certificate and private key) when this card is used.
- `--certificate` File containing the user certificate.
- `--privateKey` File containing the user private key.
- `--role` A role name for this card. Can be specified multiple times to assign multiple roles. Used only for special administrative roles: PeerAdmin, ChannelAdmin.

**Comment by mbwhite** [comment]
See PR #2507

**Comment by bestbeforetoday** [comment]
@EdMoffatt How should this command behave if only one of _certificate_ and _privateKey_ is specified? Really they need both to be useful. We could:
1. Just set the ones specified regardless because... hopefully they know what they're doing and that's what they want? Perhaps with a warning message.
1. Fail the command with an appropriate error message.

**Comment by sstone1** [comment]
@bestbeforetoday @mbwhite please can you guys provide a description of the `Issuer` role and where/what this role is used for? I was only aware of `PeerAdmin` and `ChannelAdmin`.

**Comment by mbwhite** [comment]
```composer card create [options]

Creates a business network card from individual components

Card options
  --file, -f                   File name of the card archive to be created  [string]
  --businessNetworkName, -n    The business network name  [string]
  --connectionProfileFile, -j  Filename of the connection profile json file  [string] [required]
  --user, -u                   The name of the identity for the card  [string] [required]
  --enrollSecret, -s           The enrollment secret of the user  [string]
  --certificate, -c            File containing the user's certificate.  [string]
  --privateKey, -k             File containing the user's private key  [string]
  --role, -r                   The role for this card can, specify as many as needed  [choices: "PeerAdmin", "ChannelAdmin", "Issuer"]

Options:
  --help         Show help  [boolean]
  -v, --version  Show version number  [boolean]

```

Using std yargs features, the role can be specified by `--role PeerAdmin --role ChannelAdmin`  this makes use of the yargs validation features so therefore is standard (and saves us coding it).

What we have coded is checks that give - should either the secret & credentials (or part of) are given. Or not both the cert and private key. 

"Either the enrollSecret or the privateKey and certificate combination should be specified"
"privateKey and certificate should both be specified"

Also I opted to make clear it was a connectionProfile *file* name not the name of the profile. We've used *connectionProfile* extensively with users up to know and it changing it's meaning would confused.

**Comment by bestbeforetoday** [comment]
I like allowing multiple instances of `--role` to specify multiple roles rather than parsing the value, especially if that is standard behaviour for yargs.

The other changes I am much less happy with. Let's get @EdMoffatt to offer some design input.

**Comment by EdMoffatt** [comment]
Apologies for slowing things down here, but I've been trying to write a response and then each thing I go to write I go look something else up I realise there's more to understand and reference.  Just leaving this comment to say "sorry, I've gotta get my head around this better before I can weigh in"!

**Comment by bsanil68** [comment]
Hi  ,

while   using   composer  card import   i am getting  a  Error: Client.createUser  parameter 'opts mspid ' is required .  do  i need  a  identity other than the  fabric  certificates  for  admin that  i have used  to create the  card  ....please help.. Could not  find documentation on this  ....

**Comment by phal0r** [comment]
@bsanil68 
I had the same issue and there are 2 places in the connection profile, where you can define the organization name. Make sure, that the strings are equal. This fixed the issue for me.
