### ISSUE TITLE
Missing a sample --networkAdminEnrollSecret (-S) on documentation for 0.14.0+

### ISSUE THREAD

**Issue by ykcai** [hyperledger/composer#2502]
Documentation for `Deploying and Updating Business Networks` on https://hyperledger.github.io/composer/business-network/bnd-deploy.html is missing a sample --networkAdminEnrollSecret (-S)

The sample code has: 
```
composer network deploy -p connectionProfileName -a <BusinessNetworkDefinition>.bna
-i <Your EnrollmentID> -s <Your EnrollmentSecret>
-A admin -S
```

However it should have: 
```
composer network deploy -p connectionProfileName -a <BusinessNetworkDefinition>.bna
-i <Your EnrollmentID> -s <Your EnrollmentSecret>
-A admin -S adminpw
```

**Comment by sstone1** [comment]
The `-S` in this command is a boolean flag, not an actual enrolment secret. You must specify whether or not a business network admin is going to use an *existing* enrolment secret (`-S`) or an existing certificate  (`-C /path/to/cert.pem`).
