### ISSUE TITLE
Cannot deploy .bna. Error: Error trying login and get user Context

### ISSUE THREAD

**Issue by LuisBrime** [hyperledger/composer#2503]
## Context

I was able to deploy my business network a few days ago and I made some changes to the .acl and .cto files and had to deploy again in order to test in Playground, I used the following command: 
`composer network deploy -a aletheia-network.bna -p hlfv1 -i PeerAdmin -s randomString -A admin -S`
And the following error appeared:

> Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{"code":400,"message":"Authorization failure"}]]

I've tried using admin and adminpw, and it tries to deploy the network but fails with an authorization error for INSTALL because de identity is not an admin.

## Your Environment

* Version used: v0.14.2
* Operating System and version (desktop or mobile): macOS Sierra 10.12.6

**Comment by ykcai** [comment]
I think this is related to https://github.com/hyperledger/composer/issues/2502 and maybe also look at the breaking changes for `v0.14.0`?

**Comment by LuisBrime** [comment]
Just tried that and still the same error appears. A friend downloaded the whole project and he could deploy it. I'm thinking maybe my composer profile is wrong but I can't tell why.

**Comment by LuisBrime** [comment]
I just tore appart Fabric and create again the profile and now I can deploy the .bna, not sure what went wrong but I needed to solve that asap.

**Comment by sstone1** [comment]
This error:
> Error: Enrollment failed with errors [[{"code":400,"message":"Authorization failure"}]]

Means that Composer attempted to enrol the specified identity (PeerAdmin) against the Fabric CA. This identity is not registered with the Fabric CA, so you get the authorization error.

Composer will only do this if the certificates for that identity are not in the `keyValStore` directory specified in the Composer connection profile. 

The sample Fabric scripts in `fabric-dev-servers` will import the certificates for the PeerAdmin identity into your `keyValStore` directory. If you're using another Fabric configuration, you need to import your own peer administrator certificates.

**Comment by booboothefool** [comment]
@sstone1 Could you clarify the difference between card, certificate, identity?

I am not sure what `keyValStore` is supposed to contain.

`connection.json+cert.pem+key.pem=card`. Importing card puts it into `~/.composer/card`. So what needs to go into the `keyValStore` directly?

Is the `keyValStore` still needed? have read accounts on here that it was removed.

**Comment by jfobrien29** [comment]
@sstone1 This is the key question! I'm sure @booboothefool has solved this by now but I am facing the same issue
