### ISSUE TITLE
Error: The current identity has not been registered: admin -- for 2nd org

### ISSUE THREAD

**Issue by denisglotov** [hyperledger/composer#2505]
After upgrading to Composer 0.14, I cannot run composer-rest-server, or just ping, for the 2nd organization.

## Context
My orgs use different MSP, as Fabric recommends.
I use `-A admin -S` as suggested in release notes:
```
composer network deploy -a dist/my-network.bna -p mainorg -i MainPeerAdmin -s randomString -A admin -S
composer network deploy -a dist/my-network.bna -p org2 -i Org2PeerAdmin -s randomString -A admin -S
```

And for the 1st org, things work, but for the 2nd, I get the error:
```
$ composer network ping -n my-network -p mainorg -i admin -s adminpw
The connection to the network was successfully tested: my-network
        version: 0.14.1
        participant: org.hyperledger.composer.system.NetworkAdmin#admin

Command succeeded

$ composer network ping -n my-network -p org2 -i admin -s adminpw                                                                                 
Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin)
Command failed
```

Does the composer support working on behalf of the several organization?

On Composer 0.13.2 things worked fine.

## Your Environment
```
denis@node007:~$ composer-rest-server --version
v0.14.1
denis@node007:~$ composer --version
v0.14.1
denis@node007:~$ docker --version
Docker version 17.09.0-ce, build afdb6d4
denis@node007:~$ docker-compose --version
docker-compose version 1.13.0, build 1719ceb
denis@node007:~$ uname
Linux
```

**Comment by sstone1** [comment]
The `composer network deploy` command performs both a Fabric chaincode install and instantiate operation. This is not the way we would recommend doing this for a multi organisation business network - and actually, I'm surprised you're not getting errors as part of the second deploy command.

Each organisation should perform the Fabric chaincode install on the peers for that organisation only, and then one of the organisations should perform the Fabric chaincode instantiate operation across all of the peers for both organisations.
 
Composer includes two commands for separating the install and instantiate operations. They are:
 
composer runtime install which performs the chaincode install
-and-
composer network start which performs the chaincode instantiate
 
Each command requires different connection profiles:
 
composer runtime install should be given a connection profile that only contains the URLs of the peers for the organisation performing the install operation.
 
composer network start should be given a connection profile that contains the URLs of all of the peers for both of the organisations in the channel, but only the event hub URL for that organisation.
 
This means that in your two organisation configuration, you need four connection profiles:
 
1. A connection profile for Org1 to use during "runtime install" with just the peers for Org1
2. A connection profile for Org2 to use during "runtime install" with just the peers for Org2
3. A connection profile for Org1 to use during "network start" and subsequent transactions with the peers for Org1 and Org2, but only the event hub for Org1.
4. A connection profile for Org2 to for subsequent transactions with the peers for Org1 and Org2, but only the event hub for Org2.
 
The second thing I note is that you do not supply an endorsement policy, meaning the default endorsement policy is in effect. You probably do not want this as this means that only one of the organisations has to sign (endorse) the transactions.
 
You should specify an endorsement policy that specifies that both organisations must sign all the transactions. You can see some information on how to do that as part of "network start" on this page:
 
https://hyperledger.github.io/composer/reference/composer.network.start.html
 
The endorsement policy format is a JSON format defined by the Fabric Node.js SDK.

Finally, for multi organisation deployments, you cannot use enrolment secrets. Whenever you bind an enrolment secret to an identity, only somebody in the same organisation can use that enrolment secret to access the business network.

You need to specify certificates for your business network administrators instead by using the `-C` flag.

**Comment by denisglotov** [comment]
Thank you for the info, just tried this, but still error: Invalid results returned ::FORBIDDEN.

So I duplicated my connection profiles and now have: _mainorg_, _org2_, _mainorgtx_, _org2tx_.
Transaction connections _mainorgtx_ and _org2tx_ reference keyValStore: .composer-credentials/mainorg and .composer-credentials/org2, same as mainorg and org2 connections, did I get your idea right?

Now I set up the network as the following:
```
composer identity import -p mainorg -u MainPeerAdmin -c crypto-config/.../Admin@mainorg-cert.pem -k crypto-config/.../..._sk
composer identity import -p org2 -u Org2PeerAdmin -c crypto-config/.../Admin@org2-cert.pem -k crypto-config/.../..._sk
composer runtime install -n my-network -p org2 -i Org2PeerAdmin -s randomString
composer runtime install -n my-network -p mainorg -i MainPeerAdmin -s randomString
composer network start -a dist/my-network.bna -p mainorgtx -i MainPeerAdmin -s randomString -A admin -S
```
The commands runs fine, both chaincode instances appear (one for each org). But when I start composer-rest-servers, the mainorg's one is fine, but org2's one fails:
```
$ ~/bin/composer-rest-server -p org2tx -n my-network -i admin -s adminpw -N never -w true
Discovering types from business network definition ...
Connection fails: Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Error: Invalid results returned ::FORBIDDEN
It will be retried for the next request.
Exception: Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Error: Invalid results returned ::FORBIDDEN
Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Error: Invalid results returned ::FORBIDDEN
    at client.getUserContext.then.then.catch (/home/denis/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:302:34)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Although permission.acl does not contain anything related to orgs.

**Comment by denisglotov** [comment]
I didn't get you last phrase:
> You need to specify certificates for your business network administrators instead by using the -C flag.
To which commands did you suggested to specify -C?

**Comment by denisglotov** [comment]
Created a new issue https://github.com/hyperledger/composer/issues/2585 because this one was closed.
