### ISSUE TITLE
ESLint disabled for composer-sample-networks lib directories

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2510]
The `.eslintignore` files within the _composer-sample-networks_ packages include the `lib` directory, where the sample network code is contained. Probably this code should be checked by:
1. Removing the `lib` directory from `.eslintignore`.
2. Modifying `.eslintrc.yml` to provide appropriate checking for the JavaScript level used in the sample network code, and to include globally accessible functions such as `emit` and `query`.

**Comment by andrew-coleman** [comment]
All the sample networks have now been refactored to use ES7 syntax (async/await instead of promise chains) and ESLint has been enabled for all lib directories
