### ISSUE TITLE
Cucumber test compare items in wrong order

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#2518]
reported by @ldesrosi

The cucumber tests rely on a method called compareResource to ensure that the results from a transaction meets the expected results from the cucumber table.

The output provided by the cucumber tests were confusing because in some cases the actual vs expected parameters had been inverted when calling the compareResource function. While it was the expected results that were not properly being parsed it was giving the impression that the actual results were wrong.

**Comment by ldesrosi** [comment]
FYI @nklincoln I just submitted a new pull request with the correct information.

**Comment by sstone1** [comment]
Closing as fixed!
