### ISSUE TITLE
Whitespace in-front of field is considered a String

### ISSUE THREAD

**Issue by EllisHenderson** [hyperledger/composer#2531]
When creating a field in playground (for example: o String test), any whitespace in front of the field name is considered a String.

**Comment by sstone1** [comment]
@EllisHenderson could you add a bit more detail about what exactly is wrong?

**Comment by EllisHenderson** [comment]
I'm not too sure how to explain this further other than giving some examples.

Let's say you create the following field:

```
o String test 

```
There is one space between String and test. The problem is that any additional spaces are considered as strings/part of the field name 

For
```
o String  test

```

The field name would not be 
```
test
```

it would be
```
 test
```

**Comment by EllisHenderson** [comment]
Had a go at replicating this in playground and seems to be fixed
