### ISSUE TITLE
Playground transaction submission doesn't set the $class definition correctly.

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2540]
For example on the online playground for the Vehicle Lifecycle Network.
![image](https://user-images.githubusercontent.com/25582377/32367040-977da690-c078-11e7-885b-d3bc43eae116.png)

no matter which transaction is selected the $class definition never changes from PlaceOrder

**Comment by davidkel** [comment]
Not just online, just downloaded and ran locally with web browser runtime and same.

**Comment by nklincoln** [comment]
So it would appear that the issue revolves around the delivery within #2322, and the existence of multiple Transactions

**Comment by nklincoln** [comment]
appears linked to #2538

**Comment by davidkel** [comment]
Workaround for now is to change the $class value to the correct fully qualified transaction name of the transaction you are trying to submit. You can determine that from the .cto file of your model.

**Comment by berndoostrum** [comment]
This workaround doesnt work for me. Only one of my transaction types can be done, the other ones fail with the same errors.
