### ISSUE TITLE
Perishable Network NPM Tests failing

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2541]
Raised in RC and this is the output

```
  1 passing (2s)
  3 failing

  1) Perishable Shipping Network #shipment should receive nothing for a late shipment:

      AssertionError: expected 5000 to equal 2500
      + expected - actual

      -5000
      +2500

      at businessNetworkConnection.submitTransaction.then.then.then.then (test/perishable.js:134:53)
      at process._tickCallback (internal/process/next_tick.js:103:7)

  2) Perishable Shipping Network #shipment should apply penalty for min temperature violation:

      AssertionError: expected 6500 to equal 4000
      + expected - actual

      -6500
      +4000

      at businessNetworkConnection.submitTransaction.then.then.then.then (test/perishable.js:169:53)
      at process._tickCallback (internal/process/next_tick.js:103:7)

  3) Perishable Shipping Network #shipment should apply penalty for max temperature violation:

      AssertionError: expected 7500 to equal 5000
      + expected - actual

      -7500
      +5000

      at businessNetworkConnection.submitTransaction.then.then.then.then (test/perishable.js:204:53)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```
RC user suggested that a change to the embedded runtime has caused the tests to fail.

**Comment by davidkel** [comment]
Perishable networks test time based scenarios and simulate this by setting the transaction timestamp. A change in 0.14.2 stops anyone from setting the timestamp now. These tests are now not possible.

**Comment by davidkel** [comment]
Maybe the profile for the embedded connector could have a flag to allow user generated transaction timestamps for unit test purposes.

**Comment by davidkel** [comment]
@sstone1 Do we want to be able to support unit tests that simulate periods of time ? or try to fix the unit tests (but it may not be possible and might have to be deleted, I've not had a chance to go into details of it).

**Comment by nklincoln** [comment]
The tests were trying to overwite a timestamp value on the transaction, which is now prevented. It is possible to get around this time based problem using sinon fakeTimers - advance the javascript clock before running the transaction.

This has been completed and a PR submitted to the sample networks repro
