### ISSUE TITLE
Problem exposing my business network as a REST API

### ISSUE THREAD

**Issue by MiguelinMiki** [hyperledger/composer#2559]
When I try to expose my business network as a rest api doesn't work. I'm acting from command line with 
cs-offerings/scripts scripts provided.
## Context

I'm trying to deploy my business network in a blockchain 'server' on a free cluster at bluemix blockchain service platform. In order to do that I'm trying to expose my network as a REST API like explained in this link:
[https://ibm-blockchain.github.io/paid/interacting/](https://ibm-blockchain.github.io/paid/interacting/)

## Expected Behavior

When executing 
`./create/create_composer-rest-server.sh --paid --business-network-id INSERT_BIZNET_NAME`
it's supposed to run a rest service in my kubernetes cluster.

## Actual Behavior

Actually, when I execute that, the service starts loading but gets an error...:
`Error on cloud load balancer a13723fb2c18a11e7bf218ad3907a8f0 for service default/composer-rest-server with UID 13723fb2-c18a-11e7-bf21-8ad3907a8f0f: Failed to get available cloud provider IPs for load balancer services: Clusters with one node must use services of type NodePort. See https://console.ng.bluemix.net/docs/containers/container_index.html for details.`

## Possible Fix

How can I get an external IP for my REST API? I guess it failed because '--paid' argument but, I tried without that and has the same result.

**Comment by davidkel** [comment]
@MiguelinMiki Sorry, we can't help with this, you need to contact IBM bluemix for support on this.
