### ISSUE TITLE
New Participant window blank after uploading modified .bna file (modified .cto file)

### ISSUE THREAD

**Issue by swiftguy121** [hyperledger/composer#2564]
Modified a .cto file, created a .bna file using CLI on my laptop and then imported the .bna file into the online playground. When I try to create a participant I get a blank window like above, any pointers if I missed anything while generating the .bna file ? BTW Im trying to modify the "perishable network" which i downloaded from HL sample networks.

PFA .cto file and the screenshot

[perishable-cto.txt](https://github.com/hyperledger/composer/files/1443984/perishable-cto.txt)

<img width="717" alt="screen shot 2017-11-05 at 4 56 21 pm" src="https://user-images.githubusercontent.com/12661339/32414594-987d0ca0-c250-11e7-8c08-2e7116a7fa93.png">
[perishable-cto.txt](https://github.com/hyperledger/composer/files/1443985/perishable-cto.txt)

**Comment by caroline-church** [comment]
@awjh-ibm can this now be closed?
