### ISSUE TITLE
Azure AD OAuth2 fails with ValidationError: The `user` instance is not valid...

### ISSUE THREAD

**Issue by denisglotov** [hyperledger/composer#2565]
I configured Azure active directory OUATH2 strategy for composer-rest-server auth. Strategy works, but its reply cases error.

## Context
When I browse /auth/azure, I get to https://login.microsoftonline.com with authentication screen, enter credentials, give a consent, then return to composer-rest-server and get the following error:
```
Unhandled error for request GET /auth/azure_ad_oauth2/callback?code=AQA...IAA&session_state=f6e...593: ValidationError: The `user` instance is not valid. Details: `email` is invalid (value: "undefined@loopback.azure_...com").
    at /home/denis/node_modules/loopback-datasource-juggler/lib/dao.js:1248:16
    at ModelConstructor.<anonymous> (/home/denis/node_modules/loopback-datasource-juggler/lib/validations.js:578:13)
    at ModelConstructor.next (/home/denis/node_modules/loopback-datasource-juggler/lib/hooks.js:93:12)
    at done (/home/denis/node_modules/loopback-datasource-juggler/lib/validations.js:575:25)
    at /home/denis/node_modules/loopback-datasource-juggler/lib/validations.js:653:7
    at ModelConstructor.<anonymous> (/home/denis/node_modules/loopback-datasource-juggler/lib/validations.js:434:5)
    at /home/denis/node_modules/loopback-datasource-juggler/lib/dao.js:2112:9
    at /home/denis/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1012:9
    at /home/denis/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:359:16
    at eachOfArrayLike (/home/denis/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:928:9)
    at eachOf (/home/denis/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:990:5)
    at _asyncMap (/home/denis/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1005:5)
    at Object.map (/home/denis/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:995:16)
    at allCb (/home/denis/node_modules/loopback-datasource-juggler/lib/dao.js:2026:13)
    at /home/denis/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:512:7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```
I added `console.log(obj)` to node_modules/loopback-datasource-juggler/lib/dao.js:1243 and it shows ```{"username":"azure-ad.undefined","email":"undefined@loopback.azure_ad_oauth2.com"}``` just prior the error.

When I use GitHub auth, that works well for me, the same log shows ```{"username":"github.denisglotov","email":"denisglotov@loopback.github.com"}```.

I use https://github.com/auth0/passport-azure-ad-oauth2 with the following config:
```
export COMPOSER_PROVIDERS='{
  "azure_ad_oauth2": {
    "provider": "azure-ad",
    "module": "passport-azure-ad-oauth2",
    "strategy": "AzureAdOAuth2Strategy",
    "clientID": "dd8...eaa",
    "clientSecret": "ijN...IQA=",
    "tenant": "mytennant.onmicrosoft.com",
    "resource": "dd8...eaa",
    "authPath": "/auth/azure",
    "callbackURL": "/auth/azure_ad_oauth2/callback",
    "successRedirect": "/",
    "failureRedirect": "/"
  },
}'
```

## Your Environment
```
denis@node007:~$ composer-rest-server -v
v0.14.1
denis@node007:~$ npm info loopback-datasource-juggler | grep version
  versions:
  version: '3.13.0',
denis@node007:~$ npm info passport | grep version
  versions:
  version: '0.4.0',
denis@node007:~$ npm info passport-azure-ad-oauth2 | grep version
  versions: [ '0.0.1', '0.0.2', '0.0.3', '0.0.4' ],
  version: '0.0.4',
denis@node007:~$ uname
Linux
```

**Comment by sstone1** [comment]
@denisglotov we need to figure out what the correct property for identifying the AD user is - the `undefined` means its not `username` and it's not `id`. Can you help with this please?

There is a function called `profileToUser` that converts AD (or any Passport provider) user profiles into LoopBack user models. This function is in the file `lib/models/user-identity.js` in the `loopback-component-passport` module.

Can you log out the profile that is passed in?

```
function profileToUser(provider, profile, options) {
// new code
  console.log(provider, JSON.stringify(profile), options);
// end of new code
```

Thanks!

**Comment by denisglotov** [comment]
@sstone1, here is the output:
```
azure-ad {"provider":"azure_ad_oauth2"} { provider: 'azure-ad',
  module: 'passport-azure-ad-oauth2',
  strategy: 'AzureAdOAuth2Strategy',
  clientID: 'dd8...eaa',
  clientSecret: 'ijNwVaZRkVFqz9Qu/jIRZTfNQzLweVDlRIQjZsGaIQA=',
  tenant: 'mytennant.onmicrosoft.com',
  resource: 'dd8...eaa',
  authPath: '/auth/azure',
  callbackURL: '/auth/azure_ad_oauth2/callback',
  successRedirect: '/',
  failureRedirect: '/',
  session: true }
```

(sorry for the late reply, for some strange reason I just saw your reply only now. I am online in the rocket chat, wrote a private message to you there, please feel free to ping me there about this issue too)

**Comment by denisglotov** [comment]
@sstone1, this might be what we are looking for:
```
// currently we can't find a way to exchange access token by user info (see userProfile implementation), so
  // you will need a jwt-package like https://github.com/auth0/node-jsonwebtoken to decode id_token and get waad profile
  var waadProfile = profile || jwt.decode(params.id_token);
```
taken from https://github.com/auth0/passport-azure-ad-oauth2 readme.

**Comment by sagarpomal** [comment]
@denisglotov were you able to resolve this? Facing same issue.

**Comment by denisglotov** [comment]
@sagarpomal, no unfortunately

**Comment by sagarpomal** [comment]
Thanks @denisglotov 

@sstone1 can you please help with this? Or tell us the workaround?

**Comment by mrudav-shukla** [comment]
I'm facing the same issue. It works in most of the cases. However, for some cases, it has this same error. I'm using passport-jwt for authorization.

**Comment by JuliusBrain** [comment]
Hi,

I'm having a problem getting the profile.id. I get error saying ```TypeError: Cannot read property 'match' of undefined

if (usernameOrId.match(/[^A-Za-z0-9\.\-_]/))```

Profile.id is undefined and I have no way of getting an user id. I provide in a config a scope with a profile added to it.
