### ISSUE TITLE
Docs say it's possible to control access to a property of an asset with ACL

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2566]
![image](https://user-images.githubusercontent.com/25582377/32430424-2760c198-c2c7-11e7-90c0-b882cc93b148.png)

on https://hyperledger.github.io/composer/reference/acl_language.html the text is
```
There are two types of ACL rules: simple ACL rules and conditional ACL rules. Simple rules are used to control access to a namespace, asset or property of an asset by a participant type or participant instance.
```
I didn't think we had this capability yet.

**Comment by sstone1** [comment]
P3 and no action in three months; clearly not important and never going to get fixed, so closing.
