### ISSUE TITLE
Can't deploy new business network on local playground with no internet connection

### ISSUE THREAD

**Issue by jpayne23** [hyperledger/composer#2568]
## Context

Using:
- Mac
- Firefox
- local playground

With no internet connection I am unable to deploy a new business network to local playground. I can get to the page to deploy a new business network but the page just tries to load and then times out.

Below screenshot shows what is seen when initially going to the page.

<img width="961" alt="screen shot 2017-11-06 at 09 32 38" src="https://user-images.githubusercontent.com/9744866/32434867-37aff0ea-c2d7-11e7-8fb5-ca43828ecfdc.png">

Below screenshot shows what is seen when the page loads.

![screen shot 2017-11-06 at 09 33 50](https://user-images.githubusercontent.com/9744866/32434983-933dfa06-c2d7-11e7-9760-fdb22dceadd4.png)

Going into the console, the error shown is.

![screen shot 2017-11-06 at 09 40 55](https://user-images.githubusercontent.com/9744866/32435001-9f712e74-c2d7-11e7-972a-19420ddacd46.png)

## Expected Behavior

Should still let me deploy a business network by importing a local bna file.

## Actual Behavior

Can't do anything through playground to do with deploying a new business network

## Possible Fix

Looks like there is no check to see if the sample network list is empty and errors when referencing an element in the list which doesn't exist.

## Steps to Reproduce

1. Turn off internet
2. Start Playground locally
3. Click 'Deploy a new business network'

## Existing issues

Issue looks to come from the same problem given in issue #2552, thought it was still worth adding this as an issue.

## Context
Can't work with a local playground if I have no internet connection

## Your Environment
* Version: 0.14.3
* Firefox
* Mac OS

**Comment by caroline-church** [comment]
done so closing
