### ISSUE TITLE
Transactions conflicts

### ISSUE THREAD

**Issue by emekwi** [hyperledger/composer#2574]
hello, 
while testing the car-auction example in composer i am getting this error ``` t: Instance org.acme.vehicle.auction.Offer#a50881fc-59d3-4982-bd9e-7af1d5531642 missing required field bidPrice``` when i run the closebidding transaction.
It seems like the issue is the transactions that are conflicting. I am using the online hyperledger.

**Comment by nklincoln** [comment]
Hi,

Thanks for raising the issue - it is currently being addressed under #2540

It would appear that the json content that describes Transactions/Assets/Participants is no longer being generated correctly. You should be able to perform the action through manually entering the complete required json content until the fix is made

**Comment by emekwi** [comment]
Hello, thank you for the feedback. As  I am using the online hyperledger can you please help and tell me how to manually enter the complete required json content ??
I am new at hyperledger but I want to be able to solve the issue.

**Comment by sstone1** [comment]
@emekwi you will need to put in JSON for the transaction. Here is an example for the `Offer` transaction:

```
{
  "$class": "org.acme.vehicle.auction.Offer",
  "bidPrice": 0,
  "listing": "resource:org.acme.vehicle.auction.VehicleListing#9437",
  "member": "resource:org.acme.vehicle.auction.Member#5628"
}
```

Alternatively you can use the "unstable" build of playground which has the latest changes from master, including the fix in:

http://composer-playground-unstable.mybluemix.net

We will deliver a release tomorrow (Thursday) including the fix.
