### ISSUE TITLE
Favicon sometimes displays as angular shield 

### ISSUE THREAD

**Issue by awjh-ibm** [hyperledger/composer#2594]
When running the playground the icon in the tab sometimes renders as the angular shield rather than green conga.

Found in MacOS Firefox.

![screen shot 2017-11-07 at 11 24 54](https://user-images.githubusercontent.com/31732124/32491360-50b0c66e-c3ae-11e7-9f30-677ea6c72b0d.png)

Possible fix remove angular icon as PNGs for favicons for set sizes/systems e.g. android-icon-36x36.png

**Comment by sstone1** [comment]
P3 and no action in three months; clearly not important and never going to get fixed, so closing.
