### ISSUE TITLE
Unit tests for 'network deploy/start' commands leaving card files in working directory

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2618]
The unit tests in `packages/composer-cli/test/network/deploy.js` are writing out two card files to the working directory, which are not being cleaned up after the tests. This makes adding the correct file changes to Git after running the tests more error-prone and cumbersome.

Files could be written to a temporary directory that is deleted after the test runs, or the file write could be stubbed out.

**Comment by davidkel** [comment]
The start unit test also writes a card called `mycardfile`

**Comment by mbwhite** [comment]
Being resolved in pr #3208
