### ISSUE TITLE
bad card creation on network start and network deploy

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2622]
these commands create a card of the id you are binding into NetworkAdmin participant however if you go via the -A and -S route, the card will not be valid because it has no secret. If you go via the -A and -C route, the card will not be valid because it has no private key.

When I ran the command as follows 
```
composer network start -c FabricAdmin@FabricNoKeystore -a ../composer-sample-networks/packages/digitalproperty-network/dist/digitalproperty-network.bna -A admin -S -f badadmin
```
And I went to look at the card created I saw
```
├── badadmin.zip
├── connection.json
├── credentials
│   ├── certificate
│   └── privateKey
└── metadata.json
```
certificate and privateKey were empty files
metadata.json was
```
{"version":1,"userName":"admin","businessNetwork":"digitalproperty-network","enrollmentSecret":"adminpw"}
```

**Comment by davidkel** [comment]
Would also be good to output the name of the card that was created. I know the name of the file, what I didn't know was the card name it generated which was
`admin@digitalproperty-network`

**Comment by bestbeforetoday** [comment]
The zero-length certificate and privateKey files looks to be a duple of #2630, and there is a fix on it's way in for that in pull request #2633.

**Comment by mbwhite** [comment]
Yes I believe those PRs/issues will resolve the issues; the output formatting is also something I have updates for post work with @EdMoffatt 

As these in a sense are cosmetic not functional - I've not done them as yet.  Though they are a very valuable usability feature.

**Comment by mbwhite** [comment]
Closing as functional items are resolved
