### ISSUE TITLE
As a user I need to know if a card is sharable or not.

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2641]
Cards which only have secrets in them are single shot cards. They can only be used once really and as soon as they are imported they should be pinged. Cards with full credentials in a **potentially** shareable. 

The other aspect that affects whether a card is sharable and how you can share it is the urls in it's connection profile. For example if the urls are localhost you can share them across composer components that have been installed using npm install but they won't work putting them into locally running dockerised composer components. Conversely if they have dockerised urls, then they can be shared across containers that are connected to the same network but are not sharable otherwise.

**Comment by davidkel** [comment]
Cards can be in 1 of 3 states
1. Only has a secret
2. Only has a public key (If you use deploy/start with the -A and -C options, the card will not be valid because it has no private key)
3. Has both public and private key

**Comment by bestbeforetoday** [comment]
The `composer card list --name` command allows the user to identify whether an installed card contains a secret and/or credentials.

The connection profile URLs seem to be an issue for Common Connection Profiles in general. Other than providing a mechanism to more easily allow the user to look at the connection profile within an installed card to determine how shareable it is, it is not obvious to me what we can do to solve this at the Composer level.

Closing for now. Re-open if there is something specific we could/should be doing in Composer.
