### ISSUE TITLE
Using playground URL including the 'test' element fails

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#2642]
Using a URL for playground eg `composer-playground-unstable.mybluemix.net/test`
This gives a test window, but without any details - it is unresponsive.

You need to refresh the page. Ideally this URL should redirect you.
![image](https://user-images.githubusercontent.com/6673453/32600590-01636676-c538-11e7-9b8f-1c36a81ab713.png)

**Comment by caroline-church** [comment]
done so closing
