### ISSUE TITLE
Exporting after an import uses the original networks file name

### ISSUE THREAD

**Issue by awjh-ibm** [hyperledger/composer#2643]
Starting playground and creating a network then replacing this with another network means that when exporting the new network the export file has the file name of the original file.

Steps to reproduce:
- Open playground with a network e.g. Vehicle Lifecycle
- Use the import button to replace the network with another e.g. Bond
- Click export, file name will be vehicle-lifecycle-network.bna but contents the bond network

**Comment by awjh-ibm** [comment]
@winslet or @EdMoffatt could you offer a designers perspective it is working techinally correctly but is this functionality confusing for users

**Comment by sstone1** [comment]
P3 and no action in three months; clearly not important and never going to get fixed, so closing.
