### ISSUE TITLE
Improve 'Access control' section of Playground tutorial 

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#2655]
## Context

Following recent changes to system ACLs and the inclusion of an ACL in the empty-business-network, the playground tutorial does not provide a suitable starting point for issuing/using identities.

## Expected Behavior

Since ACLs and identities are such a fundamental aspect of business networks, it would be nice if the playground tutorial provided a bit more information up front. For example, the 'Access control' section could explain some ACL basics to grant Trader participants to connect to the business (they currently cannot) and see/submit appropriate transactions. It would be even better if the following sections then involved issuing an identity, connecting with this new identity and used the new identity in the 'Transferring the commodity between the participants' section.

## Actual Behavior

The tutorial builds a business network where the only participant cannot even connect to the network and simply refers to the full documentation for ACLs

## Possible Fix

Include a snippet to add to or replace the default empty-business-network ACL file which gives the Trader participant suitable access. Bonus points for issuing a trader identity and using it to submit the transaction.

**Comment by jt-nti** [comment]
Looks like the new developer tutorial is slightly different in that it has the any access ACL rules. It might be nice if both tutorials used the same ACL

**Comment by andyrichardson** [comment]
Added to this, there is little information on ACL usage with transactions

    rule SampleConditionalRuleWithTransaction {
        description: "Description of the ACL rule"
        participant(m): "org.example.SampleParticipant"
        operation: READ, CREATE, UPDATE
        resource(v): "org.example.SampleAsset"
        transaction(tx): "org.example.SampleTransaction"
        condition: (v.owner.getIdentifier() == m.getIdentifier())
        action: ALLOW
    }

Unanswered questions include:
 * why does the code state `transaction(tx):` as opposed to `transaction:`
 * is it possible add a condition which takes into account the transaction arguments/variables
