### ISSUE TITLE
Playground only supports .card as an extension whereas CLI will use what is given .card or otherwise

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2656]
Created a card in CLI but didn't give it a .card extension. And I can use this file in the cli and probably rest server explorer as well (but I didn't test that). However I couldn't import it into playground until I changed the extension to .card.

**Comment by sstone1** [comment]
I don't think we need two issues for how we handle the `.card` extension; if there's anything else needed on top of the PR attached to #3183 move it into #3183.
