### ISSUE TITLE
Cannot import card into Playground that does not contain keyValStore in connection.json

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2657]
Exported a card from the rest server (with certs) tried to import into playground and it fails with error

![image](https://user-images.githubusercontent.com/25582377/32608744-3a555a12-c555-11e7-997c-ad26dfc4fa52.png)

appears that playground still requires a connection profile to have a keyValStore specified (although the error messages refers to other properties such as wallet or card name). The reference to wallet in this error message should be removed. We won't have a wallet definition in connection profiles.

see #2401 which may resolve this.

**Comment by sstone1** [comment]
Merging with #2675 as we don't need two issues to cover this.
