### ISSUE TITLE
Composer rest server returns Connect Failed error after shutting down container of one peer

### ISSUE THREAD

**Issue by labcoinpoc** [hyperledger/composer#2668]
## Context

Now my composer rest server works fine on a fabric network with 1 org and 4 peers. All 4 peers IP address are in connection profile. If I shut down the container of one peer. Rest server returns error when sending transaction. error message:

```
Unhandled error for request POST /api/User: Error: Error trying invoke business network. Error: Connect Failed
    at _initializeChannel.then.then.then.then.catch (/root/.nvm/versions/node/v6.11.3/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:853:34)
```

## Expected Behavior

The Connect Failed error should be ignored and receive as many endorsements as possible before timeout.

## Your Environment

* Version used: Composer 0.14.3  Hyperledger Fabric1.0.3 
* Environment name and version (e.g. Chrome 39, node.js 5.4):Nodejs 6.11.3 
* Operating System and version (desktop or mobile): Centos 7
* Link to your project:

**Comment by sstone1** [comment]
@davidkel please can you investigate this problem and see if it's something Composer is doing wrong or something that we need the Fabric team to handle in the Node.js SDK (in which case please raise a JIRA). I would suspect the latter will be the case as they will "own" connection management in Fabric v1.1 when we move to common connection profiles.

**Comment by davidkel** [comment]
I tried it with a 2 peer network and I can see that 1 peer responds with an endorsement while the node sdk returns with an error for that peer. 
```
This is a response
{ version: 1,
  timestamp: null,
  response: { status: 200, message: 'OK', payload: <Buffer > },
  payload: <Buffer 0a 20 84 a7 77 ce fa 9b b2 02 b5 cf 25 bb 25 4e 5b be 8f 33 27 d1 bf 6f be f7 56 00 91 b9 98 94 49 89 12 c8 1c 0a b2 1b 12 86 1b 0a 17 64 69 67 69 74 ... >,
  endorsement:
   { endorser: <Buffer 0a 07 4f 72 67 32 4d 53 50 12 fc 05 2d 2d 2d 2d 2d 42 45 47 49 4e 20 2d 2d 2d 2d 2d 0a 4d 49 49 43 47 44 43 43 41 62 2b 67 41 77 49 42 41 67 49 51 51 ... >,
     signature: <Buffer 30 44 02 20 04 aa 0c e0 21 17 16 5f a4 75 f5 f1 f0 67 f3 59 24 90 28 d7 a4 0a ff e4 cf c6 fa dd bd 80 13 75 02 20 31 ed 20 33 c2 b0 9e e8 56 53 0d 47 ... > } }
This is a response
{ Error: Connect Failed
    at /home/vagrant/src/fabric-composer/node_modules/grpc/src/node/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
```
Based on the connection profile we have to try to send a request to the peers listed. If any response is an error then we just throw an error and terminate the request. What we could do is log any error responses, but if there is at least 1 response we can remove the error responses and send the remaining non error responses and let endorsement policies handle it. Of course if all error then we would terminate the request.

**Comment by davidkel** [comment]
Merged into master now.

**Comment by labcoinpoc** [comment]
@davidkel Thanks for your work! 
I am testing the version 0.15.1. Seems like the changes cause other issue. New error shows when sending transaction after shutting down one container. Error Message:
```
(node:21071) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Error: The event hub has not been connected to the event source
(node:21071) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 7)
Unhandled error for request POST /api/User: Error: Error trying invoke business network. Error: The event hub has not been connected to the event source
    at _initializeChannel.then.then.then.then.catch (/root/.nvm/versions/node/v6.11.3/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:888:34)
    at process._tickCallback (internal/process/next_tick.js:109:7)
``` 
I checked the blockchain, actually this transaction was written into the chain successfully. 
After that I restart the container, the above error keeps showing when sending transactions. But in blockchain the reading and writing work fine.

**Comment by davidkel** [comment]
This is due to attempting to register for tx events when a peer is down. Unfortunately it also now highlights that if you bring the peer back up then it won't attempt to re-establish the connection to the event hub.

**Comment by davidkel** [comment]
Supporting the ability to tolerate unavailable peers requires more work around other areas and so I have created issue #2799 to list the required considerations.
