### ISSUE TITLE
Grammatical issue developer guide

### ISSUE THREAD

**Issue by pradeeppadmarajaiah** [hyperledger/composer#2669]
Minor Grammatical issue in the developer guide

## Context
https://hyperledger.github.io/composer/tutorials/developer-guide.html 
Deploying the business network tab

## Expected Behavior
**Deploying a business network requires Hyperledger Composer to be installed on the peer**, then the business network archive (.bna) must be sent to the peer, and a new participant, identity, and associated card must be created to be the network administrator.

## Actual Behavior
Deploying a business **network to the requires the Hyperledger Composer chaincode** to be installed on the peer, then the business network archive (.bna) must be sent to the peer, and a new participant, identity, and associated card must be created to be the network administrator.

**Comment by EdProsser** [comment]
This is a problem with a dead variable replacement link, which has since been corrected. A fix will go out this week. :)

**Comment by sstone1** [comment]
Looks OK to me.
