### ISSUE TITLE
Improve docker images

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#2673]
## Context

There are a few niggles with the current docker images which it would be good to fix

- [x] composer-cli

- [x] composer-playground

- [x] composer-rest-server

## Expected Behavior

- Global node modules should not be installed using the node user provided by the base image 

- The composer-cli entrypoint should be the composer command

## Actual Behavior

Node modules are installed as root, the composer command is not properly wrapped in the composer-cli image, and yarn is removed for no obvious reason

**Comment by sstone1** [comment]
> yarn is removed for no obvious reason

Didn't you make this change @jt-nti 😂

**Comment by jt-nti** [comment]
@sstone1 true. I also know what the reason was and who asked for it :)

If anyone is interested, I'd appreciate any feedback on the changes so far, which should be in the last commit on this branch -> https://github.com/jt-nti/hyperledger-composer/tree/2673-docker-images

Thanks
