### ISSUE TITLE
Vehicle Lifecycle demo needs to be updated to Composer 0.15.x

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2684]
Currently it is pinned to 0.14.2 but it should be updated to 0.15.x release

**Comment by nklincoln** [comment]
Hi @davidkel - the VLD was intentionally pinned at that level

**Comment by davidkel** [comment]
Hi @nklincoln it was pinned only because there wasn't enough time to update the scripts for the new card functions. It still needs to be done so we can unpin the VLD.

**Comment by davidkel** [comment]
Now complete
