### ISSUE TITLE
Move, restructure and deliver a better API docs experience

### ISSUE THREAD

**Issue by winslet** [hyperledger/composer#2695]
Currently the API docs live in the same doc structure as the main documentation. This has some limitations to the experience we would prefer to deliver, some of the limitations today are:
- Left hand navigation is unwieldy
- The information hierarchy leaves something to be desired
- Compared to other API documentation around the web there is certain functionality we could provide better, eg more code examples, different page design.

Potential solution:
- Leave the current url structure of https://hyperledger.github.io/composer/api but build a new jekyll template which will work better with the different type of information found within API docs. 
- Break down the navigation into the `admin api` `client api` `common api` `runtime api` along with look into listing commands in other ways.

We are a big fan of the Mozilla API docs due to their volume of examples and navigation (https://developer.mozilla.org/en-US/docs/Web/API/ANGLE_instanced_arrays) also the style of API documentation where we split across panels navigation/information/examples seems to be very prevalent right now (eg https://monzo.com/docs/#acquire-an-access-token), how we can do this needs more investigation on the jekyll front.

**Comment by winslet** [comment]
@EdProsser FYI we're looking into this now, will give you periodic updates when we kick off.

**Comment by sstone1** [comment]
Replaced by CIP #3377.
