### ISSUE TITLE
As a user of a Mac machine I should have pre-requisite installation instructions

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#27]
The install for pre-reqs needs to include documentation for Mac OS:
https://fabric-composer.github.io/tasks/prerequisites.html

**Comment by sstone1** [comment]
Public Travis has the ability to execute builds on Mac OS X, we could also try and automate the execution of some of the tests (maybe the Getting Started system tests that @14gracel built) on Mac OS X.

**Comment by sstone1** [comment]
Not an issue right now, closing until it resurfaces.
