### ISSUE TITLE
As a user I can using the runtime API to create an instance of a transaction

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#2703]
## Context
TP functions may need to create transactions so they can serialize them to invoke external services via `post(...)`.

## Expected Behavior
Can call `getFactory().newTransaction(...)` from a TP function.

## Actual Behavior
The `newTransaction(...)` method is missing from the runtime factory API.

## Possible Fix
Add `newTransaction(...)` to the runtime API. Ensure that the client can set the transaction id so that it is deterministic.

## Steps to Reproduce
1. N/A

## Existing issues
N/A

## Context
Trying to `post` to an external service that expects to receive a serialized transaction.

## Your Environment
* Version used: 0.15
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by davidkel** [comment]
The runtime api newResource states in the docs that you can use it to create a new transaction if you need something now.
```
        /**
         * Create a new resource (an instance of an asset, participant, or transaction). The
         * properties of the new instance should be set as standard JavaScript
         * object properties. The new instance can then be stored in a registry
         * using the appropriate registry APIs, for example {@link AssetRegistry}.
```
