### ISSUE TITLE
Remove pre-card API

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2718]
Once everything uses the card-based versions of `AdminConnection.connect()` and `BusinessNetworkConnection.connect()`, remove `AdminConnection.connectWithDetails()` and `BusinessNetworkConnection.connectWithDetails()`.

Code specific to those code-paths can also be removed, such as `ConnectionProfileStore`.

**Comment by caroline-church** [comment]
done so closing
