### ISSUE TITLE
HTTP_PROXY - Installing and running Hyperledger Composer Playground locally behind a proxy

### ISSUE THREAD

**Issue by deionut** [hyperledger/composer#2729]
First the success story: I successfully ran the playground tutorial ( https://hyperledger.github.io/composer/tutorials/playground-guide.html ) locally on an Ubuntu 16.04 VirtualBox image in a network with no proxies. I first ran the prereqs-ubuntu.sh as detailed on https://hyperledger.github.io/composer/installing/development-tools.html followed by installing Hyperledger Composer development tools (all the npm installs steps).
After that I ran the install-hlfv1.sh script as detailed on https://hyperledger.github.io/composer/installing/using-playground-locally.html

At the end of it the browser opened localhost:8080 and I was able to deploy a new tutorial-network based on the empty-business-network template. I was then able to connect to the business network.

Now the fail story: I can't follow the same steps on a network behind a proxy.
I am running Ubuntu 16.04 installed nativelly (dual boot along Windows 10). My Ubuntu is configured correctly to use the proxy; my $home/.bashrc and /etc/environment have defined the following env variables:

export http_proxy=http://my.proxy.com:8080
export https_proxy=$http_proxy
export ftp_proxy=$http_proxy
export no_proxy=localhost,127.0.0.1

export HTTP_PROXY=$http_proxy
export HTTPS_PROXY=$http_proxy
export FTP_PROXY=$http_proxy
export NO_PROXY=localhost,127.0.0.1

I also edited /etc/sudoers to add the following line:
Defaults	env_keep = "http_proxy https_proxy ftp_proxy no_proxy HTTP_PROXY HTTPS_PROXY FTP_PROXY NO_PROXY"

I also modified in Gnome desktop: System Settings->Network->Network proxy accordingly

I successfully ran the prereqs-ubuntu.sh script and all the npm installs.

I configured docker with the proxy settings as detailed here: https://docs.docker.com/engine/admin/systemd/#httphttps-proxy

I am able to successfully run the ./startFabric.sh script as is, without any changes. docker ps lists the hlfv1 fabric containers up and running.

The issues start when trying to run the composer: I ran the install-hlfv1.sh script, the browser opens the composer on localhost:8080 but when I click on the "Deploy a new business network" link there is a continuous spinning wheel in the next page in place of the network templates.
The docker logs for composer-playground show the following error:

0|composer | PlaygroundAPI           :createServer()           Playground API started on port 8080 
0|composer | PlaygroundAPI           :createServer()           < 
0|composer | Composer                :main()                   > 
0|composer | NPM                     :/api/getSampleList()     > 
0|composer | NPM                     :getSampleNames()         > 
0|composer | info
0|composer |  
0|composer | attempt
0|composer |  registry request try #1 at 11:25:55
0|composer | http
0|composer |  
0|composer | request
0|composer |  GET https://registry.npmjs.org/-/v1/search?text=keywords%3Acomposer-network%20maintainer%3Ahyperledger-ci
0|composer | info
0|composer |  retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:443
0|composer | info 
0|composer | attempt registry request try #2 at 11:26:05
0|composer | http request
0|composer |  GET https://registry.npmjs.org/-/v1/search?text=keywords%3Acomposer-network%20maintainer%3Ahyperledger-ci
0|composer | info
0|composer |  retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:443
0|composer | info
0|composer |  attempt registry request try #3 at 11:27:05
0|composer | http request
0|composer |  GET https://registry.npmjs.org/-/v1/search?text=keywords%3Acomposer-network%20maintainer%3Ahyperledger-ci
0|composer | NPM                     :getSampleNames()         Error: connect ECONNREFUSED 151.101.16.162:443 
0|composer | NPM                     :getSampleNames()         < 

I fixed this by editing the docker-compose-playground.yml to add the proxy env variables:

    environment:
      http_proxy: http://my.proxy.com:8080
      https_proxy: http://my.proxy.com:8080
      no_proxy: ca.org1.example.com,orderer.example.com,peer0.org1.example.com,couchdb,localhost,127.0.0.1,127.0.0.11
      COMPOSER_CONFIG: >
        {.........................

I now get the list of template networks. I choose the empty-business-network template but when I click the "Deploy" button I get the following error:

`Error: Failed to load connection profile ce0f135f7a63287ab86f0dcc0732e185c1a60d62-hlfabric. Error was Error: ENOENT: no such file or directory, open '/home/composer/.composer-connection-profiles/ce0f135f7a63287ab86f0dcc0732e185c1a60d62-hlfabric/connection.json'`

The docker logs for composer-playground now show:

0|composer | ConnectorServer         :constructor()            < 
0|composer | ConnectorServer         :connectionProfileStoreLo > ce0f135f7a63287ab86f0dcc0732e185c1a60d62-hlfabric
0|composer | FSConnectionProfileStore:load()                   Failed to loaded connection profile ce0f135f7a63287ab86f0dcc0732e185c1a60d62-hlfabric {"stack":["{Error}ENOENT: no such file or directory, open '/home/composer/.composer-connection-profiles/ce0f135f7a63287ab86f0dcc0732e185c1a60d62-hlfabric/connection.json' Error: ENOENT: no such file or directory, open '/home/composer/.composer-connection-profiles/ce0f135f7a63287ab86f0dcc0732e185c1a60d62-hlfabric/connection.json'"]}
0|composer | ConnectorServer         :Error: Failed to load co undefined 
0|composer | ConnectorServer         :connectionProfileStoreLo < 

I modified the file fabric-scripts/hlfv1/composer/docker-compose.yml to add the same lines as above for all 4 containers (ca.org1.example.com, orderer.example.com, peer0.org1.example.com, couchdb), e.g.

    environment:
      - http_proxy=http://my.proxy.com:8080
      - https_proxy=http://my.proxy.com:8080
      - no_proxy=ca.org1.example.com,orderer.example.com,peer0.org1.example.com,couchdb,localhost,127.0.0.1,127.0.0.11

but when I click the "Deploy" button I get the exact same error as before.

Can anyone help? Was anyone able to run the composer-playground locally behind a network proxy?

**Comment by deionut** [comment]
One issue might be that both my http_proxy and the composer-playground use the same port 8080. I changed docker-compose-playground.yml to change the port to 8088:

  composer:
    container_name: composer
    image: hyperledger/composer-playground
    ports:
      - '8088:8088'

Now directing the browser to localhost:8088 gives an ERR_SOCKET_NOT_CONNECTED error and the docker logs for composer-playground show that it is still trying to use the old 8080 port:

0|composer | PlaygroundAPI           :createServer()           > 8080, false
0|composer | ConnectionProfileManager:constructor()            Created a new ConnectionProfileManager {"fs":{"constants":{"O_RDONLY":0,"O_WRONLY":1,"O_RDWR":2,"S_IFMT":61440,"S_IFREG":32768,"S_IFDIR":16384,"S_IFCHR":8192,"S_IFBLK":24576,"S_IFIFO":4096,"S_IFLNK":40960,"S_IFSOCK":49152,"O_CREAT":64,"O_EXCL":128,"O_NOCTTY":256,"O_TRUNC":512,"O_APPEND":1024,"O_DIRECTORY":65536,"O_NOATIME":262144,"O_NOFOLLOW":131072,"O_SYNC":1052672,"O_DSYNC":4096,"O_DIRECT":16384,"O_NONBLOCK":2048,"S_IRWXU":448,"S_IRUSR":256,"S_IWUSR":128,"S_IXUSR":64,"S_IRWXG":56,"S_IRGRP":32,"S_IWGRP":16,"S_IXGRP":8,"S_IRWXO":7,"S_IROTH":4,"S_IWOTH":2,"S_IXOTH":1,"F_OK":0,"R_OK":4,"W_OK":2,"X_OK":1,"UV_FS_COPYFILE_EXCL":1,"COPYFILE_EXCL":1},"F_OK":0,"R_OK":4,"W_OK":2,"X_OK":1}}
0|composer | PlaygroundAPI           :createServer()           Playground API started on port 8080 
0|composer | PlaygroundAPI           :createServer()           < 
0|composer | Composer                :main()                   >

**Comment by deionut** [comment]
From the official playground guide it was not clear what the difference was between the 2 options: the web-browser connection and the hlfabric connection. The youtube tutorials made it clear that the web-browser connection is just a dummy in browser connection with no connection whatsoever to a running fabric. I need to get the connection to the locally installed hlfabric working behind a proxy, so I am reopening this issue. Can anyone help in configuring a local fabric and composer running behind a proxy?

**Comment by deionut** [comment]
I was able to deploy the tutorial-network to the proper composer, ping-ed it successfully and generated the REST server. So the only issue is when deploying a network with the composer-playground locally, but for testing my network I can just as well use the browser connection. Closing this issue.

**Comment by deionut** [comment]
Again I am having issues with hyperledger composer behind a proxy; the version of hyperledger fabric is 1.1.0 (and 1.1.0alpha also has the same problem). The version of hyperledger composer is 0.18.2 (and 0.17.6 also has the same problem).
I managed to successfully **startFabric.sh** and **composer runtime install --card PeerAdmin@hlfv1 --businessNetworkName mynetwork**

However when I try to start my network with

**composer network start --card PeerAdmin@hlfv1 --networkAdmin admin --networkAdminEnrollSecret adminpw --archiveFile mynetwork.bna --file networkadmin.card**

I get the following errors:

Starting business network from archive: mynetwork.bna
Business network definition:
        Identifier: mynetwork@0.0.3
        Description: Some network

Processing these Network Admins:
        userName: admin

â Starting business network definition. This may take a minute...
Error: Error trying to instantiate composer runtime. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://registry.npmjs.org/composer-runtime failed, reason: connect ECONNREFUSED 151.101.16.162:443
npm ERR!     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at ClientRequest.emit (events.js:211:7)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:387:9)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at TLSSocket.emit (events.js:211:7)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR!     at _combinedTickCallback (internal/process/next_tick.js:138:11)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR!  { FetchError: request to https://registry.npmjs.org/composer-runtime failed, reason: connect ECONNREFUSED 151.101.16.162:443
npm ERR!     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at ClientRequest.emit (events.js:211:7)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:387:9)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at TLSSocket.emit (events.js:211:7)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR!     at _combinedTickCallback (internal/process/next_tick.js:138:11)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR!   message: 'request to https://registry.npmjs.org/composer-runtime failed, reason: connect ECONNREFUSED 151.101.16.162:443',
npm ERR!   type: 'system',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   stack: 'FetchError: request to https://registry.npmjs.org/composer-runtime failed, reason: connect ECONNREFUSED 151.101.16.162:443\n    at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)\n    at emitOne (events.js:116:13)\n    at ClientRequest.emit (events.js:211:7)\n    at TLSSocket.socketErrorListener (_http_client.js:387:9)\n    at emitOne (events.js:116:13)\n    at TLSSocket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)',
npm ERR!   parent: 'composer-runtime-hlfv1' }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-28T13_44_44_246Z-debug.log
"

Command failed

I have no problem however with fabric version 1.0.4 and composer version 0.16.6

**Comment by deionut** [comment]
It works with hyperledger fabric version 1.1.0 and hyperledger composer version 0.16.6. So I guess the issue is with the composer, it broke the proxy functionality between 0.16.6 and 0.17.6 ...

**Comment by dpalmeira** [comment]
Hey Stale, I have the same problem, and it does NOT work
https://github.com/hyperledger/composer/issues/3731

I'm facing this problem installing Hyperledger dev env in a Vbox with Ubuntu 16.04 and using latest versions of npm, node, Hyperledger, etc., and behind a corporate proxy. I'm using CNTLM in local vbox, then Playground and Start command line fails!

Could you help to resolve it?

**Comment by dpalmeira** [comment]
Any help? the error is still there.

**Comment by dpalmeira** [comment]
Resolved!
https://github.com/hyperledger/composer/issues/3731

**Comment by davidkel** [comment]
closing as resolved.
