### ISSUE TITLE
Documentation which requires changing for BN Cards

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2737]
- [x] https://hyperledger.github.io/composer/playground/id-cards-playground.html the metadata information, image is not part of the metadata anymore
- [x] https://hyperledger.github.io/composer/business-network/bnd-deploy.html needs to be updated for the new cli options it currently is not correct
- [x] https://hyperledger.github.io/composer/managing/identity-issue.html the code sample and the cli sample are now out of date and won't work
- [x] https://hyperledger.github.io/composer/managing/participant-add.html the code sample and cli sample are now out of date and won't work
- [x] https://hyperledger.github.io/composer/managing/identity-bind.html the code sample and cli sample are now out of date and won't work
- [x] https://hyperledger.github.io/composer/managing/identity-list.html  the code sample and cli sample are now out of date and won't work
- [x] https://hyperledger.github.io/composer/managing/identity-revoke.html  the code sample and cli sample are now out of date and won't work
- [x] https://hyperledger.github.io/composer/problems/diagnostics.html refers to connection profiles in the wrong location, plus the information there is out of date
- [x] https://hyperledger.github.io/composer/reference/connectionprofile.html is now out of date due to changes for cards
- [x] https://hyperledger.github.io/composer/applications/node.html is now out of date, shows using connect with a profile

**Comment by mbwhite** [comment]
*Diagnostics* page; the last section needs to be reworded to say look at the output of *docker ps*
And see the name of the container - the network name will be encoded within that.

**Comment by mbwhite** [comment]
*Writing applications*
Worth stressing taht the config module is NOT part of Composer, but a 3rd party node module used for general application configuration
```
this.cardName= config.get('cardname');
```

```
this.bizNetworkConnection.connect(this.cardName)
.then((result) => {
  this.businessNetworkDefinition = result;
});
```

the rest is the same..

**Comment by mbwhite** [comment]
*Connection Profiles*  I would ditch the first 3 steps as there are no directories containg these any more

Simplest profile as used for our dev servers
```
{
    "type": "hlfv1",
    "orderers": [
       { "url" : "grpc://localhost:7050" }
    ],
    "ca": { "url": "http://localhost:7054", 
            "name": "ca.org1.example.com"
    },
    "peers": [
        {
            "requestURL": "grpc://localhost:7051",
            "eventURL": "grpc://localhost:7053"
        }
    ],
    "keyValStore": "${HOME}/.composer-credentials",
    "channel": "composerchannel",
    "mspID": "Org1MSP",
    "timeout": "300"
}
```

And for our two org non-tls systests.
```
 connectionProfileOrg1 = {
                            type: 'hlfv1',
                            name: 'hlfv1org1',
                            orderers: [
                                'grpc://localhost:7050'
                            ],
                            ca: {
                                url: 'http://localhost:7054',
                                name: 'ca.org1.example.com'
                            },
                            peers: [
                                {
                                    requestURL: 'grpc://localhost:7051',
                                    eventURL: 'grpc://localhost:7053'
                                },
                                {
                                    requestURL: 'grpc://localhost:8051'
                                }
                            ],
                            channel: 'composerchannel',
                            mspID: 'Org1MSP',
                            timeout: '300',

                        };
                        connectionProfileOrg2 = {
                            type: 'hlfv1',
                            name: 'hlfv1org2',
                            orderers: [
                                'grpc://localhost:7050'
                            ],
                            ca: {
                                url: 'http://localhost:8054',
                                name: 'ca.org2.example.com'
                            },
                            peers: [
                                {
                                    requestURL: 'grpc://localhost:8051',
                                    eventURL: 'grpc://localhost:8053'
                                },
                                {
                                    requestURL: 'grpc://localhost:7051',
                                }
                            ],
                            channel: 'composerchannel',
                            mspID: 'Org2MSP',
                            timeout: '300',

                        };```

**Comment by caroline-church** [comment]
done so closing
