### ISSUE TITLE
Connect now arrow renders on new line on Linux FF

### ISSUE THREAD

**Issue by awjh-ibm** [hyperledger/composer#2739]
In the list of deployed business networks on the login page the connect now arrow appears below the text. Tested using Ubuntu and Firefox 47.0

![screen shot 2017-11-16 at 10 27 02](https://user-images.githubusercontent.com/31732124/32886490-b8b0322a-cab8-11e7-90ff-aff1b78b133b.png)

**Comment by awjh-ibm** [comment]
Updated to FF 57 and renders as expected

**Comment by caroline-church** [comment]
closing as works in later versions
