### ISSUE TITLE
AdminConnection.importCard() behaviour is not consistent between hlf and embedded connectors

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2741]
Currently the embedded (and therefore likely also the web) connector errors if the same identity is imported more than once. The error is from PouchDB. This is not consistent with the behaviour documented for `AdminConnection.importCard()`, which explicitly allows the re-import of a card of the same name. Coincidentally, the Fabric connector does not error in this scenario so behaviour of `AdminConnection.connect()` differs depending on which connector is used.

A side-effect of this behaviour is that, when using the embedded connector, user code (such as business network unit tests) need to do additional work to ensure that the same card is not imported more than once across an entire test suite run. This additional work is not required if using the fabric connector, where `AdminConnection.importCard()` does not error on re-import of an existing card.

Likely the correct solution is for `AdminConnection.importCard()` to check whether a card being imported is already present in the card store (`cardStore.has()`) and, if so, explicitly remove the identity associated with the existing card from the connector prior to importing the new identity from the new card.

**Comment by davidkel** [comment]
included for 0.15.2 release.
