### ISSUE TITLE
Infinite loading wheel when running playground locally offline.

### ISSUE THREAD

**Issue by EdProsser** [hyperledger/composer#2742]
## Context

After installing `composer-playground@unstable` and running `composer-playground` the playground does not open in a browser tab by default, but it does load a browser. 

Then after I navigate to localhost:8080 the playground loads as normal, but when I try to deploy a new network after disconnecting from the internet, I get an infinite loading wheel.

## Expected Behavior

Loads correctly, minus the npm based samples.

## Actual Behavior

Infini-wheel.

## Steps to Reproduce
1. `npm install -g composer-playground@unstable`
2. `composer-playground`
3. Go to localhost:8080/login
4. Disconnect from network.
5. Click deploy new business network.

**Comment by samjsmith** [comment]
The workaround for this is to have a working network connection. 
Fix is probably in the composer-playground-api layer then.

**Comment by caroline-church** [comment]
Fixed this by reducing the max timeout and retry count but retry count does not work see https://github.com/npm/npm-registry-client/issues/162.

**Comment by caroline-church** [comment]
done so closing
