### ISSUE TITLE
Create network admin cards on programmatic start of business network

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2753]
**As a** blockchain application developer
**I want** to programmatically define network administrative identities when creating a business network
**so that** I can either use these identities myself to connect to the business network, or send them to somebody else so that they can connect to the business network

Remove `AdminConnection.deploy()`, so the changes below only need to be applied to `AdminConnection.start()`. Keep the `composer network deploy` CLI (for now), but update it to use the install/start API.

`AdminConnection.start()` needs to have an additional mandatory parameter that is an array of objects describing the required admin identities, of the following form (matching the `IdCard` definitions):
```javascript
[
    {
        userName: String,
        enrollmentSecret: String,
        certificate: String
    },
    ...
]
```
Each object must specify _userName_, and exactly one of _enrollmentSecret_ or _certificate_.

There needs to be capability for client code to pass in additional bootstrap transactions, to be run in addition to the set up of the network admin identities.

`AdminConnection.start()` should create business network cards for each of these requested identities, using the name of the business network being deployed and the connection profile from the card being used for deployment, as the `composer network start` and `composer network deploy` CLI commands do. The bootstrap transaction code to achieve this already exists in the CLI commands. An array of the newly created cards should be returned, enabling the calling code to either:
- Call `AdminConnection.importCard()` for immediate use of the admin identity.
- Call `IdCard.toArchive()` to save the card for later use.

The `composer network start` and `composer network deploy` commands need to be updated in-line with this new AdminConnection API. Updates to samples and test code are outside of the scope of this story.

**Comment by mbwhite** [comment]
To clairfy:

That bootstrap transactions are in ADDITION to the list of network admins, they are not mutually exclusive.  The array of networks admins must be given.

**Comment by mbwhite** [comment]
## CLI Commands
This affects the `network deploy` `network start` commands.

### network deploy
Options wise this remains as before:

```
Deploy Options
  --loglevel, -l                     The initial loglevel to set  [choices: "INFO", "WARNING", "ERROR", "DEBUG"]
  --file, -f                         File name of the card to be created  [string]
  --archiveFile, -a                  The business network archive file name  [string] [required]
  --networkAdmin, -A                 The identity name of the business network administrator  [string] [required]
  --networkAdminCertificateFile, -C  The certificate of the business network administrator  [string]
  --networkAdminEnrollSecret
  --card, -c                         The cardname to use to deploy the network  [string] [required]
```

Internally this needs to move to use the `adminconnection.install` and `adminconnection.start`
This will then be reflected in the output that will show a separate 'install' and 'start' phase


## `network start`
Internally this will use the start api with it's changes. 
To properly support this via the cli requires some changes to the options to give the same level of control.

The current 
```
  --networkAdmin, -A                 The identity name of the business network administrator  [string] [required]
  --networkAdminCertificateFile, -C  The certificate of the business network administrator  [string]
  --networkAdminSecret, -S           The enrollment secret for the business network administrator  [string]
```
Options will be honoured to create a single card. The change is permit options of this form
```
--networkAdmin.id[.index] <user id>
--networkAdmin.secret[.index] <secret>
--networkAdmin.cert[.index] <certificate file>
--networkAdmin.file[.index] <filenameof the card>
``

As before either the secret or certificate file should be supplied. The file is optional and a default name will be created in the cwd.

The index is an optional suffiix that links together the options. For example

```
"composer network start 
   --archiveFile ${DIR}/network.bna 
   --card PeerAdmin@hlfv1 

  --networkAdmin.id.1 adminA 
  --networkAdmin.secret.1 adminpw 
  
  --networkAdmin.id.2 adminB 
  --networkAdmin.secret.2 adminpw 
  --networkAdmin.file.2 ./_cards/admin.card"
```
This will create two cards for *adminB* and *adminA*.  AdminB's card will be written to a specific file. 
Due to the index, it is possible to have individual admins use either secrets or certificates. And to only write some cards to different locations. The index does not have to a number - so long as it the same. 

Suggested stick to numbers or a-z for the index to avoid issues with shell parsing.

The order of the options as well is not important as well due to the index.

**Comment by mbwhite** [comment]
# API updates
The Amin API has been updated to support this.

## `adminConnection.startOptions`

*Arguments:* change here is to the `startOptions` structure. This now takes an option `NetworkAdmins` that is an array of  
```
    {
        userName: String,
        enrollmentSecret: String,
        certificate: String
    },
```
A certificate or enrollmentSecret should be given;  the CLI uses the same structure, so may add a file: option to help it link the userName to the filename.

*Returns:* the return is a map of created IdCards. Key is the userName

## Example
```
    let cards = await adminConnection.start(businessNetworkDefinition, { networkAdmins: [ {userName : 'admin', secret:'adminpw'} ] });  
    let userCard = cards.get('admin');
```

**Comment by hchaturv** [comment]
Currently on composer v0.16.5 - The following command returns an error -
composer network start --archiveFile rt_new@0.0.1.bna --card PeerAdmin@hlfv1 --networkAdmin.id.1 adminA --networkAdmin.secret.1 adminpw --networkAdmin.file.1 networkadmin1.card --networkAdmin.id.2 adminB --networkAdmin.secret.2 adminpw --networkAdmin.file.2 networkadmin2.card

Error - You must specify certificate files or enrollment secrets for all network administrators
Command failed
