### ISSUE TITLE
Broken link to the playground's tutorial

### ISSUE THREAD

**Issue by lucasdf** [hyperledger/composer#2754]
The main page of the [playground](http://composer-playground.mybluemix.net/login) points to the link https://hyperledger.github.io/composer/tutorials/playground-guide.html , which is broken.

The file [guide-validations.md](https://github.com/hyperledger/composer/blob/master/contrib-notes/release-process/guide-validation.md) have broken links to the playground tutorial and developer tutorial.

**Comment by nklincoln** [comment]
Thanks for raising the issue - the link within the 'getting started' business network card is broken, but the lower footer link is pointing to the correct page location.
