### ISSUE TITLE
The CLI and API should throw an error if you try to use a card without a business network to connect to a business network

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2755]
On RC I see a lot of these (commands being used vary of course)
```
composer identity list -c PeerAdmin@hlfv1
it got me this error
Error: Error trying to ping. Error: Error trying to query business network. Error: Missing "chaincodeId" parameter in the proposal request
```
The error comes from the connector, but in 0.15.1 it's changed now to say no business network however the CLI and as an extra the API should be able to detect if a card has a business network or not and report a problem if it's trying to do something that requires a business network.

**Comment by davidkel** [comment]
Actually this is a regression I think in the move to cards because the CLI at least would require you to use -n if needed and wouldn't work otherwise

**Comment by mbwhite** [comment]
![image](https://user-images.githubusercontent.com/6673453/33130113-25fed6da-cf8a-11e7-83ad-73d0b69e046a.png)

**Comment by mbwhite** [comment]
@davidkel  these look to be fixed with the updated work.  so I'll close this off.
