### ISSUE TITLE
Linting error "keyword 'const' is reserved" in a package created with the generator

### ISSUE THREAD

**Issue by lucasdf** [hyperledger/composer#2766]
## Context
After running `eslint .` in an application created using the generator, Eslint displays the following error for the file `/test/logic.js`:
`  6:1  error  Parsing error: The keyword 'const' is reserved`

Since the eslint configuration file is bundled with the generated application, the generated application should not have any linting error.

## Possible Fix
I fixed it by adding `ecmaVersion: 6` inside the option `parserOptions` in the file `.eslintrc.yml`. Most likely the application will run in a Node environment running ecma6, so it seems to be a good fix.

## Steps to Reproduce
- Create an application using `yo hyperledger-composer:businessnetwork`
- Run `eslint .`inside the application directory

**Comment by sstone1** [comment]
`ecmaVersion: 6` this will not work as the eslint rules apply to both the `lib` folder (containing transaction processor functions that must be ES5) and the `test` folder (containing tests that can be ES5/6/7). Separate eslint configurations are required for both folders, but in 0.17.0 we will allow ES5/6/7 in both folders and we only need one eslint configuration.

**Comment by sstone1** [comment]
Rolling into #3385.

**Comment by davidphanva** [comment]
@sstone1 I'm having the same issue.  How do I know if I have 0.17.0 or how do I switch to that version?

Thanks.
