### ISSUE TITLE
REST Server Example JSON shows Object instead of string after including a Concept

### ISSUE THREAD

**Issue by rthatcher** [hyperledger/composer#2780]
Using this model excerpt:
```
namespace org.acme.biznet

concept Address {
  o String street
  o String city
  o String country
}

asset Field identified by fieldId {
o String fieldId
o Address address
--> Farmer owner
}
```

When the REST server provides the Example Value, the referenced Farmer owner is shown as an object instead of a string value.
```
{
  "$class": "org.acme.biznet.Field",
  "fieldId": "string",
  "address": {
    "$class": "org.acme.biznet.Address",
    "street": "string",
    "city": "string",
    "country": "string",
    "id": "string"
  },
  "owner": {}
}
```

composer-rest-server v0.15.1

**Comment by fenglianxu** [comment]
@rthatcher This works as designed now. The relationship type has been changed to **any** rather than a **String** now.  The object shown in the json is correct. I close this defect.
