### ISSUE TITLE
current identity has not been registered: Admin@org1.example.com

### ISSUE THREAD

**Issue by rajadilipkolli** [hyperledger/composer#2805]
I am new to Hyperledger, after following steps given [here ](https://hyperledger.github.io/composer/unstable//tutorials/deploy-to-fabric-single-org.html) I got my business card got created :PeerAdmin@fabric-network.card

Question/Observations:
1)When I open play ground(http://localhost:8080),I dont see above business card.Is this expected?
2)When I am trying to import this card manually ,I am getting this error:

![image](https://user-images.githubusercontent.com/24761580/33128519-ab7d805e-cfb2-11e7-9334-4688377aac8f.png)

Please suggest how to fix the issue.

**Comment by davidkel** [comment]
@rajadilipkolli Could you try again with 0.16 of composer. Playground installed using npm install should now see cards in your card store that you have imported using the CLI as they will share the same card store on your local file system
