### ISSUE TITLE
Insufficient documentation for query use

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#2836]
It is possible to use multiple operators within a query file. In fact we support:
-SELECT is a mandatory operator, and by default defines the registry and asset or participant type that is to be returned.
-FROM is an optional operator which defines a different registry to query.
-WHERE is an optional operator which defines the conditions to be applied to the registry data.
-AND is an optional operator which defines additional conditions.
-OR is an optional operator which defines alternative conditions.
-CONTAINS is an optional operator that defines conditions for array values
-ORDER BY is an optional operator which defines the sorting or results.
-SKIP is an optional operator which defines the number of results to skip.
-LIMIT is an optional operator which defines the maximum number of results to return from a query, by default limit is set at 25.

However, we do not document how to use all of the above.

We need examples on how to use each statement operator

We also need to explain the limitations on query, for instance the inability to query across asset registries.

The above are issues that are found in hackathons, and general usage ... we *really* need to get ahead of the curve here and help the users.

## Context
Trying to find out how to perform a query that returns results based on using anything other than the most basic query options.

## Expected Behavior
documentation should document what is possible?

## Actual Behavior
Sadness - I have to look up the tests to see the correct syntax for queries

## Possible Fix
Add to the documentation

**Comment by varun-raj** [comment]
https://github.com/hyperledger/composer/pull/3321

**Comment by atishaya11** [comment]
Using hyperledger composer, I am facing difficulty in writing the queries. I wrote a query with multiple conditions using 'AND' but the results are not according to those conditions. Please look into this.
