### ISSUE TITLE
staged/web playground wants network admin card name specified

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#2837]
When deploying a new business network in the staged playground, I am given a mandatory option for naming the business network card that will be generated upon deploy.
 - this makes no sense for the staged playground and should be hidden on staged instances (and/or a web profile target)
 - the text could do with refinement to make sense 

<img width="1029" alt="screen shot 2017-11-25 at 10 57 54" src="https://user-images.githubusercontent.com/8394544/33229458-96e4d646-d1cf-11e7-9018-aab0e146eee2.png">

**Comment by sstone1** [comment]
>>> Nick Lincoln [10:31 AM]
think that might even be irrelevant now?
