### ISSUE TITLE
When clicking on the "Start the lab" button, there is no blockchain 

### ISSUE THREAD

**Issue by newtorob** [hyperledger/composer#2843]
## Context

Going through the IBM Blockchain Foundation Developer course, I got to Lab 1: Create a Hyperledger Composer solution and once the "start the lab" button is clicked, you are taken to a "There is no blockchain here" page. 

## Expected Behavior

should be able to start a lab

## Actual Behavior

Cannot start the lab

## Possible Fix

Issue a fix to the link?

**Comment by rohanpinto** [comment]
+1

**Comment by targetblockchain** [comment]
facing same problem

**Comment by sstone1** [comment]
The IBM site needs updating; I've asked the IBM team responsible for this to take a look.
