### ISSUE TITLE
Cannot specify location of card store to CLI commands

### ISSUE THREAD

**Issue by samjsmith** [hyperledger/composer#2854]
As per the title although I think you could argue whether it's required or not.

 I can specify a card store programmatically via the API with something like this:
```
            const cardStoreOptions = {
                'storePath' : '/tmp/CardStore'
            };
            const fileSystemCardStore = new FileSystemCardStore(cardStoreOptions);
            const adminConnectionOptions = {
                'cardStore' : fileSystemCardStore
            };
            const adminConnection = new AdminConnection(adminConnectionOptions);
```

Then there's no way to tell the CLI that this is where my card store is, I'm stuck with `$HOME/.composer` (wherever that is depending on who I am).  I was slightly disappointed.

**Comment by sstone1** [comment]
Replaced by CIP #3121.
