### ISSUE TITLE
As a developer I would like the embedded connector to behave the same as the hlfv1 connector wrt to identity handling

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2857]
example from RC given
```
businessNetworkConnection.issueIdentity(NS + '#' + userData.id, userData.user);
....      
var userCard = new IdCard({...});
userCard.setCredentials(credentials);
...
adminConnection.importCard(userCardName, userCard);
....
businessNetworkConnection.connect(userCardName))
...
```
However, importCard() throws an error that the identity already exists

**Comment by nasht00** [comment]
This issue is preventing us from running unit tests

**Comment by davidkel** [comment]
See also https://github.com/hyperledger/composer/issues/3023 regarding the embedded connector.

**Comment by davidkel** [comment]
The embedded connector isn't going to simulate a separate CA and Connector wallet. Basically it is going to be a wallet that requires an initial secret if created through identity issue, but it should be close enough to a real environment for unit test and development testing purposes. The above example still won't work because of the use of `setCredentials`. Those credentials won't have been registered to the runtime so you will get the error similar to
```
Error: The current identity, with the name 'admin@fabric' and the identifier 'b8f15ae01a978a5142922725877eb2312c618f4e99161c5cec1c31a2494c890f', has not been registered
```
The pattern of use for both unit testing will be the same as running against a real fabric and it will be something like

```
    let newID = await businessNetworkConnection.issueIdentity(namespace + '.Issuer#dave', 'dave');
    const userMetadata = {
        version: 1,
        userName: 'dave',
        'businessNetwork': 'bond-network',
        'enrollmentSecret': newID.userSecret
    };
    const daveCard = new IdCard(userMetadata, connectionProfile);
    await adminConnection.importCard('daveCard', daveCard);
    await businessNetworkConnection.disconnect();
    await businessNetworkConnection.connect('daveCard');
    console.log(await businessNetworkConnection.ping());
```

It could be possible to provide credentials for the id card but it would have to satisfy the following conditions
1. That identity was already registered to the runtime (ie bound and activated to another participant)
2. Must have the same issuer as the the identity that invoked identity issue. 
So this doesn't seem a likely approach when working with the issueIdentity api and so not a pattern worth documenting.
