### ISSUE TITLE
Navigating using the browser's back feature doesn't perform as expected.

### ISSUE THREAD

**Issue by KaiUsher** [hyperledger/composer#2860]
Pressing back on the browser doesn't perform as expected, i.e. it sends you to an unexpected page.

Steps to reproduce:
1. From the my business networks page, press 'Deploy a new business network'.
2. Press back from the browser toolbar / go back any other way (such as Mac touchpad gesture).
3. Get lost, confused and maybe a little scared.

**Comment by jt-nti** [comment]
Back button does not work as expected on deploy or create card pages :(
