### ISSUE TITLE
Yo Generator Update

### ISSUE THREAD

**Issue by johnjayasingh** [hyperledger/composer#2870]
Please update the hyperledger-composer generator for yo. 

## Context
So many features such as wallet and authorization are added in the composer rest server. but the generator is not accomadating all features.

## Expected Behavior
Please provide an update such that it can handle multi user mode and autorizations

## Actual Behavior
Could not do any actions in the generated angular code because we are not specifing any business card using api and no ui is available at the moment.

## Possible Fix
Autorization and Identity issue and  Wallet import functions can be added top of the generated code.

## Steps to Reproduce
NA

## Existing issues
No

## Context
Could not utilize the existing generator due to lack of feature accomadation

## Your Environment
* Version used: 0.15.2 composer and 2.0 yo 
* Environment name and version (e.g. Chrome 39, node.js 5.4): NA
* Operating System and version (desktop or mobile): Mac High Sierra
* Link to your project:

**Comment by sstone1** [comment]
Folding into:
Angular2 app generated by "yo fabric-composer" does not have UI for Participants or Transactions #400
