### ISSUE TITLE
Can't issue Identities from CLI

### ISSUE THREAD

**Issue by samjsmith** [hyperledger/composer#2873]
I used the CLI to start a network with this: `composer network start --card TestPeerAdmin@org1 --networkAdmin admin --networkAdminEnrollSecret adminpw --archiveFile /tmp/basic-sample-network.bna --file /tmp/networkadmin.card`

Then I created some participants and tried to issue then with an identity with this: `composer identity issue --card admin@basic-sample-network -u bobsId -a "resource:org.acme.sample.SampleParticipant#bob"`

But got this: `Issue identity and create Network Card for: bobsId\n\nError: fabric-ca request register failed with errors [[{"code":400,"message":"Authorization failure"}]]`  
Ignore crazy formatting there.

My networkadmin.card that got created (and that I then imported) has this in it
```composer card list --name admin@basic-sample-network
userName:            admin
description:         
businessNetworkName: basic-sample-network
roles:               none
connectionProfile: 
  name:    hlfv1
  type:    hlfv1
  channel: composerchannel
secretSet:           Secret set
credentialsSet:      Credentials set
```

I think that the `roles: none` is stopping me from issuing the Identity. I don't know how to tell the start cli command to make me an admin (or at least someone who can issue identities).

**Comment by davidkel** [comment]
@samjsmith So here are the steps I followed I have already imported the fabric admin card
```
$ composer runtime install -n digitalproperty-network -c FabricAdmin@test
⠸ Installing runtime for business network digitalproperty-network. This may take a minute.../home/vagrant/src/fabric-composer/packages/composer-runtime-hlfv1
✔ Installing runtime for business network digitalproperty-network. This may take a minute...

Command succeeded

$ composer network start -c FabricAdmin@test -a ~/bna/digitalproperty-network.bna -A admin -S adminpw
Starting business network from archive: /home/vagrant/bna/digitalproperty-network.bna
Business network definition:
	Identifier: digitalproperty-network@0.1.12
	Description: Digital Property Network

Processing these Network Admins:
	userName: admin

✔ Starting business network definition. This may take a minute...
Successfully created business network card:
	Filename: admin@digitalproperty-network.card

Command succeeded

$ composer card import -f admin@digitalproperty-network.card

Successfully imported business network card
	Card file: admin@digitalproperty-network.card
	Card name: admin@digitalproperty-network

Command succeeded

$ composer participant add -c admin@digitalproperty-network -d '{"$class":"net.biz.digitalPropertyNetwork.Person","personId":"P1", "firstName":"Jack", "lastName":"Daniels"}'
Participant was added to participant registry.

Command succeeded

$ composer identity issue -u Jack -a net.biz.digitalPropertyNetwork.Person#P1 -c admin@digitalproperty-network
Issue identity and create Network Card for: Jack

✔ Issuing identity. This may take a few seconds...

Successfully created business network card file to
	Output file: Jack@digitalproperty-network.card

Command succeeded
```
The roles in a card are only specific to playground. They aren't required for the CLI or Rest Server, so that isn't your problem. Not sure what your problem is but it would appear the admin id in your card is not the one currently known to the ca server.

**Comment by samjsmith** [comment]
@davidkel thanks ever so much for trying that for me Dave, much appreciated.  I'll go through my testcase today and see if I can spot what I've done wrong.

**Comment by pong-pantola** [comment]
Hi @samjsmith.  I encountered the same problem.  I'm not sure if our scenario is the same.  

But before you import the admin's card, you might want to delete first just in case there is an old version of the card:
composer card delete --name admin@mynetwork
composer card import -f admin.card

**Comment by samjsmith** [comment]
Need to make sure that the whole of the $HOME/.composer directory is deleted!

**Comment by DalderupMaurice** [comment]
@pong-pantola his solution of deleting the existing admin card worked for me!
`composer card delete --name admin@mynetwork`
