### ISSUE TITLE
Modifying the model file at runtime

### ISSUE THREAD

**Issue by pradeeppadmarajaiah** [hyperledger/composer#2875]
Is there a way to modify the model file @runtime to add a new attribute or create new resource (Asset, Transaction, event) schema itself.

For Example : Car has a three attribute (id,name,vinnumber) , later i decided to add a new attribute called (carOwnerName).  

I don't want to change and deploy again. Wanted to add new attribute at run time

**Comment by davidkel** [comment]
@pradeeppadmarajaiah you can use `composer network update` to update a business network with a new version. Which I believe is what you want.

**Comment by pradeeppadmarajaiah** [comment]
No David. I want create or modify the file schema of the resource on the fly

**Comment by davidkel** [comment]
Only way of doing that is to use playground and the web profile rather than communicating with a real fabric. When you press update it it modifies it.
It is not possible at all using a real fabric.

**Comment by pradeeppadmarajaiah** [comment]
Can this type of feature will be added in future ??

**Comment by sstone1** [comment]
We would not plan on adding this feature. Models (along with scripts, access control rules, queries) form part of the business network definition, which is equivalent to a smart contract. All participants must agree on all parts of the business network definition, and any kind of dynamic model updates would bypass the agreement steps. The command `composer network update` allows you to update models inside a running business network and preserve data, but you must package the new model files into a new BNA file.

**Comment by dselman** [comment]
👍🏽
