### ISSUE TITLE
Can I use same enrollment secret id to authenticate the my application

### ISSUE THREAD

**Issue by pradeeppadmarajaiah** [hyperledger/composer#2877]
I wanted to build an authenticated application.  I create the user in composer wallet.

Can i use the same authentication credentials to login into the application and use it for resource creation on composer ??. If yes, Could please provide the documentation?

**Comment by sstone1** [comment]
@pradeeppadmarajaiah no you cannot; the enrollment secret is not a password, and cannot be used as a form of authentication. It is a one time token that can be given to the Fabric CA in exchange for a new certificate. You must use a Passport strategy to authenticate users via the REST APIs, or set up your own authentication when using the JavaScript APIs.
