### ISSUE TITLE
Work through "multi org" Tutorial to identify pain points

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#2881]
It is *awesome* that we now have a multi-org tutorial here:
https://hyperledger.github.io/composer/tutorials/deploy-to-fabric-multi-org.html

This articulates exactly what the current experience is for a user trying to achieve this.  Everyone I know who has followed the instructions (and indeed Simon who wrote them) has reacted with "oh lord, this is horrible!".

Perfect opportunity to treat this as a Design exercise...  We have our As Is Scenario, we should identify the biggest pain points, come up with ideas to address them and prioritise, then draw up what the experience would be if we deliver those ideas (To Be Scenario).

I'm aware this may actually create ideas for Fabric rather than Composer, but we can always raise them as issues against Fabric and make suggestions for other Hyperledger projects based on the work we do on Composer, right? :)

**Comment by sstone1** [comment]
Can confirm, experience is terrible.

**Comment by Mayur5** [comment]
Completely agree. Happy to serve as end user guinea pig as part of the 'design exercise'.

**Comment by jt-nti** [comment]
Looks like there are a couple of other issues regarding the multi org tutorial as well:

- Suggested updates to the multi-org tutorial #3119
- Improve multi-org tutorial #3148
