### ISSUE TITLE
Publish stable, 0.16.x, documentation

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#2886]
## Context

The first stable release is now available 🎉

## Expected Behavior

I should be able to easily find the stable release and its associated documentation even when unstable versions of Composer are released

## Actual Behavior

We currently only have a copy of the documentation for the weekly releases, which will soon be the unstable 0.17.x versions, and another for the last automated build

There is no information in the documentation about there being a stable release or how to install it

## Possible Fix

Add information about the stable release to the landing page and provide a link to a 0.16.x copy of the documentation, with associated 0.16.x single script installer etc.

**Comment by jt-nti** [comment]
@sstone1 @markcastle3 marking this as a P1 as this probably needs doing before the next release, otherwise the docs are liable to flip flop between 0.16.x and 0.17.x

**Comment by jt-nti** [comment]
Latest plan from @mbwhite @winslet @sstone1 

- composer/stable (the new default landing page for 0.16.x docs)

- composer/latest (the previous default for last tagged 0.17.x release from master)

- composer/unstable (unchanged)

There should be a way to switch between the three versions of the docs, possibly using a drop down ... or an animated spinning conga line

**Comment by mbwhite** [comment]
First step in pr #2919  - this has been run on a master : unstable build.
