### ISSUE TITLE
Improve Playground Tests

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#2887]
Alot of the playground tests use too many mocks and are driven from the component rather than the template. This issue aims to address this

- [x] basic modals
- [x] common
- [ ] editor
- [x] editor/addFile
- [x] editor/editorFile - **Caroline**
- [x] footer
- [x] identity
- [x] identity/identity-issued - **Caroline**
- [ ] identity/issue-identity
- [ ] deploy
- [ ] login
- [ ] login/create-identity-card
- [ ] login/edit-card-credentials
- [ ] login/import-identity
- [ ] services
- [ ] test
- [ ] test/registry
- [ ] test/resource
- [ ] test/transaction
- [ ] test/view-transaction
- [ ] version-check
- [ ] welcome

**Comment by davidkel** [comment]
Closing as no further improvements will be made to playground.
