### ISSUE TITLE
consistent use of the option for referencing a card in the card store.

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2892]
If I look at the commands eg, runtime install, network deploy they use the --card or -c option to reference a card in the card store. 
All the card commands such as import, delete, export, list all use the --name or -n option to reference a card in the card store.

We should be consistent across our CLI.

**Comment by sstone1** [comment]
@bestbeforetoday @mbwhite any comments on this one?

**Comment by bestbeforetoday** [comment]
The `--card` option specifies the card that is used to perform the action. The `compose card` commands do not use a card to perform an action, so using `--card` instead of name might be viewed as inconsistent meaning of the `--card` parameter. Probably a call for a designer though.

**Comment by sstone1** [comment]
After using the commands for a while I agree with @davidkel, the use of `-c` and `-n` depending on the command to refer to the name of a business network card in the card store is just confusing. Would vote we drop `-n` and consistently use `-c` everywhere.
