### ISSUE TITLE
As an administrator I want to be able to specify a card file as the discovery ID for composer rest server

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2897]
Currently when you start the rest server, you can specify a card name and that card must already exist in the file system card store.

With the case of the docker rest server this is a problem because in order for the container to work it requires an already populated card store, but doing it this way means there are permission problems that can occur depending on how the card store was set up and mounted into the container.

A simpler solution to consider would be to be able to mount a directory that contained card files and a command line option to import that card file when the rest server starts, with the option to do overwrite if a card already exists, do nothing or throw an error.

**Comment by DennisM330** [comment]
This is needed in order to adopt business network cards and move to later versions of hyperledger composer.

**Comment by sstone1** [comment]
We don't want to do this (FYI @nikkkola), this is replaced by CIP #3121. Cloud wallets are the way forwards - prime the cloud wallet store and configure the REST servers to point at that.
