### ISSUE TITLE
As a user I need guidance on how to create portable business cards

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2898]
There has been so much confusion over the ability to share cards across components and between users. The first aspect being "Single Use Only" Cards which are cards that have only a secret in them. 
The second comes from connection profiles which are specific to a particular network setup.
For example the use of localhost is fine for a local machine but cannot be used to connect to the same fabric if the card is then imported into a docker container running a composer component. Also the use of localhost means you cannot give it to a colleague if you want them to be able to connect to your fabric. 
The other issue is using urls which use the docker hostnames within the fabric network on a specific docker network. Fine if the everything that is going to communicate with that fabric is local AND connected to the docker network but not much use otherwise.
The new createPeerAdminCard.sh in the dev-servers package allows to to specify a different hostname to localhost so that teh devserver package can be setup on a different machine to allow it to be shared.
The final part is using path names for tls certs either relative or absolute which may not be resolvable elsewhere. The solution here is to embed the cert into the connection profile.

What we need to do is provide guidance on how to create portable business network cards in the documentation, providing advice on when to use localhost, docker hostname etc and the effect of doing so, along with cards that only have secrets in and the issues these create (ie multiple enrolment and the identity not being registered in the runtime although they appear to be the same because they have the same name)

**Comment by davidkel** [comment]
I've currently labelled this as a bug as 
1. it's not an enhancement
2. It is an issue constantly being hit by users especially around the docs with using the rest server custom docker image where they expect it to work following on from using the dev server.

**Comment by rthatcher** [comment]
Seeing the issue with People who have created cards in Playground Container and then move to the CLI.

Using the IP Address of the Host Machine is likely to cause some problems for Developers...
In the 'Office' you get the same Office DHCP address for say 3 days - then after a long weekend you return to the office and get a different DHCP addresses.  If a developer uses the same machine at Home then again a different IP a few hours later.  Perhaps the Hostname of the Host machine would be better?

**Comment by davidkel** [comment]
So it would seem that there is no simple way to automate the creation of a card's connection profile. So the best thing I can think of currently is that in our dev server setup and 1-line install at card creation time we should prompt the user to choose
```
- Select from the following to use as the host for the connection profile url:
1) Your ip address (xx.xx.xx.xx)
2) Your hostname (hostname)
3) localhost (DANGEROUS, card will have limited sharing capabilities)

```

**Comment by davidkel** [comment]
Closing as I don't think this is ever going to be a priority.
