### ISSUE TITLE
REST Server Docs - Problems with "Deploying" Doc and other Nitpicks

### ISSUE THREAD

**Issue by rthatcher** [hyperledger/composer#2908]
- [ ] Until we get a solution for Issue #2898 - we need to say something about Cards with Localhost in them.

- [ ] In the 'deploying the Rest server' doc - when describing the Network Admin card and the recommendation to use certificates - should we show the command `composer card list -n admin@my-network` and look for credentials set at the bottom of the output?

- [ ] In the 'deploying the Rest server' doc - should we mention that the ~/.composer folder needs to have write access for UID 1000: GID 1000 ?

The Publishing Events Doc Includes the COMPOSER_WEBSOCKETS=true environment variable as an alternative to using -w on the command line, 
- [ ] BUT The Enabling authentication doc does not describe using COMPOSER_AUTHENTICATION=true
 - [ ]  AND The enabling multiuser doc does not describe using COMPOSER_MULTIUSER=true environment variable

- [ ] This reference doc https://hyperledger.github.io/composer//reference/rest-server is missing COMPOSER_WEBSOCKETS=true

**Comment by rajadilipkolli** [comment]
After following these steps:https://hyperledger.github.io/composer//integrating/deploying-the-rest-server
I see below errros when I run this "docker logs -f rest":

| It will be retried for the next request.
0|composer | Exception: Error: Card not found: admin@dam-network
0|composer | { Error: Card not found: admin@dam-network
0|composer |     at IdCard.fromDirectory.catch.cause (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/cardstore/filesystemcardstore.js:74:27)
0|composer |     at <anonymous>
0|composer |   cause: 
0|composer |    { Error: Unable to read card directory: /home/composer/.composer/cards/admin@dam-network
0|composer |     at newErrorWithCause (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/idcard.js:36:19)
0|composer |     at fs.stat.catch.cause (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/idcard.js:323:19)
0|composer |     at <anonymous>
0|composer |      cause: 
0|composer |       { Error: EACCES: permission denied, stat '/home/composer/.composer/cards/admin@dam-network'
0|composer |         errno: -13,
0|composer |         code: 'EACCES',
0|composer |         syscall: 'stat',
0|composer |         path: '/home/composer/.composer/cards/admin@dam-network' } } } 

After reading @rthatcher above comments to give 1000:1000 access to~/.composer I did this but no luck so far:
sudo chown 1000:1000 ~/.composer

**Comment by davidkel** [comment]
In response to `In the 'deploying the Rest server' doc - should we mention that the ~/.composer folder needs to have write access for UID 1000: GID 1000 ?`
I don't think we should be providing documentation about this. This will only work under specific circumstances and is really just a plaster around the fact the documentation and capabilities of the rest server should describe a more robust and capable way of handling the discovery id.

**Comment by davidkel** [comment]
It looks like the OAUTH tutorial is also using the rest server docker image and so will also encounter these sorts of problems. Maybe now we should move these all to using a remotely hosted wallet backed card store such as redis ?

**Comment by rthatcher** [comment]
Most of these doc issues picked up in this PR:
https://github.com/hyperledger/composer/pull/4104
