### ISSUE TITLE
Storing asset of type A into registry B

### ISSUE THREAD

**Issue by nasht00** [hyperledger/composer#2909]
Following the code examples, I've been storing all my assets of type A into the A registry, and assets of type B into the B registry.

Today, by mistake I stored an asset of type B into a A registry:

```
return getAssetRegistry(WIDGET_A).then(function(registry) {
        return registry.add(myWidgetB);
    });
```

No errors.
Then I ran `composer network list` and this is what I see:

```
  com.WidgetA: 
    id:           com.WidgetA
    name:         Asset registry for com.WidgetA
    registryType: Asset
    assets: 
      my-widget-B: 
        $class:             com.WidgetB
        id:                 my-widget-B
        name:               nnname
```

As you can see, an asset of class `com.WidgetB` sits inside a registry called `com.WidgetA`.
By the way their definitions are not the same.

So, is this a bug? Or did I misunderstand registries?
Are they in fact just arbitrary buckets?

**Comment by sstone1** [comment]
> Are they in fact just arbitrary buckets?

This; we create default registries for each concrete type that you model, but you can also create your own registries. For example, I might create an asset registry called "SimonsAssets" and I might fill it with my Vehicle, my House, etc.

**Comment by nasht00** [comment]
And what is the relationship between types and registries? What effects do those registries have?
I mean, is it bad to create a registry called "everything" and to just put everything there?
Is it to make identifiers unique for each asset type?
