### ISSUE TITLE
Business Network Card Secret is ALWAYS Set

### ISSUE THREAD

**Issue by rthatcher** [hyperledger/composer#2912]
When using the command `composer card list -n fred@tutorial-network` the output shows values for secretSet and credentialsSet.

## Context
It is a little odd that when the credentials are set and the secret is now redundant that the secret remains.  (If the secret is manually deleted from metadata.json then the composer card list correctly shows 'No Secret set'.)

## Expected Behavior
When Credentials are set and the secret is nolonger valid - the composer code that sets the credentials should remove the secret from metadata.json.

## Context
Helping users to understand the one-time secret is more difficult when the secret persists in the card.

## Your Environment
Composer v0.16.0 - and v0.15.* I think.

**Comment by davidkel** [comment]
@rthatcher Is the problem the fact the secret remains in the metadata.json (which most users are not aware of) or that fact that the command reports both a secret and credentials being set. I would say that it doesn't matter that the secret remains in the metadata.json anymore but how the information is reported, so how about this as a suggestion
If the card is still going to use a secret because no certs have been downloaded 
```
userName:            PeerAdmin
description:
businessNetworkName:
identityId:          114aab0e76bf0c78308f89efc4b8c9423e31568da0c340ca187a9b17aa9a4457
roles:
  - PeerAdmin
  - ChannelAdmin
connectionProfile:
  name:   hlfv1
  x-type: hlfv1
credentials
   user not enrolled, secret will be used to enroll
```
```
userName:            PeerAdmin
description:
businessNetworkName:
identityId:          114aab0e76bf0c78308f89efc4b8c9423e31568da0c340ca187a9b17aa9a4457
roles:
  - PeerAdmin
  - ChannelAdmin
connectionProfile:
  name:   hlfv1
  x-type: hlfv1
credentials
   user has been enrolled, certificate and private key present
```
Or words to that effect (Wordsmithing welcome :-)  )

**Comment by davidkel** [comment]
Ideally I would also like to have it report on a card file as well, but that would be something for the future.

**Comment by rthatcher** [comment]
Removing the secret from the metadata seems less important.  Providing clarity that either the Secret or Cert/Key is active is the important bit to help users (and support staff) understand the state of the identity/card.  The words suggested above do differentiate between the states and use the right terminology.  Maybe adding 'one-time' in front of secret would help too.
