### ISSUE TITLE
Support Latest Emcascript features in TP functions With Node.js Container support

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2917]
Basic change probably is just change the instantiation of JavascriptParser with ecmascript value of 5 and change it to 8, add some unit tests to check for async/await examples.

At some point we would need to update the samples eslint checking to allow version 8 as well.

**Comment by dselman** [comment]
Using `await` in TP functions would make them much more readable and cuts out a big learning curve for developers that are not familiar with Promises.
