### ISSUE TITLE
Loopback Connector Integration Tests not used and mention Concerto

### ISSUE THREAD

**Issue by samjsmith** [hyperledger/composer#292]
These tests aren't used in the build and we have a decent unit test coverage for this component now anyway.  I think we should delete these from this package and use them as the basis for some new integration tests in the composer-rest-server package instead.

It's hard to write unit tests for that package but it does need some integration tests and I believe these would form a decent foundation.

@sstone1 and @dselman is this ok with you guys?

**Comment by sstone1** [comment]
I've deleted these integration tests as they are now redundant. I recently added full testing for the REST server by using `chai-http` and the embedded runtime. I started adding full testing for the LoopBack connector (by driving the PersistedModel methods) and that can be seen here: /Users/sstone1/git/composer/packages/loopback-connector-composer/test/assets.js

Closing issue.
