### ISSUE TITLE
The Multi-org tutorial creates non sharable Business Network cards

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2922]
The multi-org tutorial needs to promote creating business network cards in the right way that ensures they satisfy the goal of a business network card, ie that they can be shared. There are 2 issues with the way the tutorial currently does this.
1. It uses 'localhost' but does not explain that this means you cannot share the card to a user on another system or with the dockerised components running locally.
2. It uses file paths for the certs which actually isn't a documented feature and also makes the card unusable in a docker environment as well as being given to other users. The certs should be embedded into the connection profile.

There is an opportunity for composer card create to extract file paths and embed the contents into the connection profile as part of the creation, however when the CCP comes it would probably mean that the code would still have to maintain a knowledge of the format unless we can get the node sdk to provide the capability on out behalf.

**Comment by davidkel** [comment]
Should be addressed in the CCP version of this tutorial (ie 0.17, master, next whatever you want to call it). This now only applies to 0.16.x

**Comment by davidkel** [comment]
Probably not worth the effect to address for 0.16.x has been addressed in master.

**Comment by davidkel** [comment]
@lesleyannjordan Given that 0.19 (and 0.19 has resolved this) is now the latest replacing 0.16 I don't think there is a need for this issue anymore. What do you think ?

**Comment by lesleyannjordan** [comment]
Agreed
