### ISSUE TITLE
As a deployer if a Common Connection Profile specifies certs as file names I would like my created card to still be portable

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2923]
The Common Connection Profile supports cert definition as being embedded in the profile document or referenced. If we build a card that is shareable, then we need to handle these references. There are 2 ways we could do this
1. update the references somehow and pull the files into the card, such that when the connection profile is parsed by the node-sdk it can find the files in the card store.
2. remove the references and embed the certificates.
Option 2 is the easier way to handle this, but it's unlikely there are the apis in the node-sdk to perform this type of capability so composer doesn't have to know anything about the CCP structure. We will need to look at this and perhaps create a Jira or a pull request to allow this.

**Comment by davidkel** [comment]
When we create the card we could also consider resolving environment variables such as $HOME etc for file paths such as `"$HOME/ca-certs/orderer.zonenet/tls/ca.crt"`

**Comment by elenduuche** [comment]
So packaging the referenced cert files with the .card file during `composer card create ...` is an approach to achieve better portability of cards.

**Comment by davidkel** [comment]
Closing to be included in a future CIP

**Comment by litong01** [comment]
please see this issue. https://github.com/hyperledger/composer/issues/3623, including many certs in a json file is not good at all. as the referenced issue (which should not have been closed) indicated, connection profile should be made a set of files (suggest as tar.gz). Which is normally how certificates being delivered any way. Inclusion certs in a text file like json destroys pretty much every good thing about json. Alter certificate file is not a good thing at all.
