### ISSUE TITLE
Tutorial is no longer valid with the command "yo hyperledger-composer:businessnetwork"

### ISSUE THREAD

**Issue by mrappard** [hyperledger/composer#2929]
## Context

In the tutorial on 

https://hyperledger.github.io/composer/tutorials/developer-tutorial.html

it asks you to run 

yo hyperledger-composer:businessnetwork

This will generate a project with a improper "test/logic.js"  file

that will generate the Error

 Error: No network administrators or bootstrap transactions are specified

at line 68

->

## Expected Behavior

Not Throw an Error

## Actual Behavior
Throw an Error

## Possible Fix
Add either a network administrator or bootstrap transaction to line 68 of the created project at  "test/logic.js" 

## Steps to Reproduce
Run the command

yo hyperledger-composer:businessnetwork

run the tests

**Comment by davidkel** [comment]
I suspect you haven't got an upto date version of the generator.

I did the following
- npm install -g yo
- npm install -g generator-hyperledger-composer (which installed version 0.16.0)
- yo hyperledger-generator:businessnetwork
- changed to the directory where the generator output the code
- npm install
- npm test
```
dave@ubuntu:~/test1$ npm test

> test1@0.0.1 test /home/dave/test1
> mocha --recursive



  #org.example.biznet
    ChangeAssetValue()
      ✓ should change the value property of SampleAsset to newValue (100ms)


  1 passing (2s)
```
