### ISSUE TITLE
New Feature : Auto Increment field in Composer

### ISSUE THREAD

**Issue by pradeeppadmarajaiah** [hyperledger/composer#2931]
Is there any auto_increment field type is available when creating an Asset, Participant instance. 

For example, Asset/Participant id should be autogenerated field and should be created at runtime, instead of mentioning the value at the application level.

I can achieve it by creating a transaction processor function to check the list of asset and add 1 to increment as an alternative.

Looking for new a feature(This is a common feature in other platforms) which will help multiple developers while building an application.

Regards,
Pradeep P

**Comment by dselman** [comment]
This feature is problematic in a distributed, consensus-based, system like Hyperledger Fabric. Each peer processing a transaction would compute the next ID concurrently and if there was disagreement about the next ID then the transaction would be rolled back. This could lead to hard to debug race conditions and failures under load.

It is much safer (and faster) to compute the next ID once on the client, and to pass it in with the incoming transaction.

**Comment by Daniel-Szego** [comment]
you can query all the assets in your code, count them and increment by one. It will probably cause problems, if you want to create several assets in the same round, but otherwise, it should work. Here is an example code: 
https://danielszego.blogspot.com/2018/09/fabric-composer-tips-and-tricks-auto.html
