### ISSUE TITLE
Need for DCO Sign-Off not contained in Contribution Guidelines

### ISSUE THREAD

**Issue by mwittig** [hyperledger/composer#2932]
## Context

Apparently, all composer-related projects of the hyperledger organisation require a [DCO sign-off](https://developercertificate.org/) for submissions to the project, i.e. the [DCO robot](https://github.com/apps/dco) checks commit messages as part of pull requests submitted.  As far as I can see, the DCO requirement isn't highlighted as part of the contribution guidelines of the [hyperledger composer project](https://github.com/hyperledger/composer/blob/master/CONTRIBUTING.md).

## Expected Behavior

DCO Sign-Off requirement should be described as part of guidelines.

## Actual Behavior

DCO Sign-Off isn't mentioned at all.

## Possible Fix

I am happy to contribute a paragraph on the matter for review

**Comment by davidkel** [comment]
Contrib notes have been updated with other information and have included some info on this in the master branch.
