### ISSUE TITLE
Unnecessary code to get playground version

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#2936]
It looks like the playground inherited code from when the composer command line used
to show versions of the different composer modules instead of a single version, none
of which is actually required.

It would be more straightforward/reliable to get the playground version directly from the
package.json file as the command line now does.

**Comment by sstone1** [comment]
:+1: from me, the nasty grep code does not work on platforms without grep either.

**Comment by jt-nti** [comment]
All done
