### ISSUE TITLE
Assets are not getting updated with Composer 0.16

### ISSUE THREAD

**Issue by sanjay-saxena** [hyperledger/composer#2942]
With `Composer 0.10.1`, my assets would get updated correctly in the JS transaction processing functions. However, with `Composer 0.16.0`, the asset is not getting updated.

The repo is [here](https://github.com/sanjay-saxena/subrogation-network) on github. You can follow these steps to create the business network archive:

```
$ git clone https://github.com/sanjay-saxena/subrogation-network
$ cd subrogation-network
$ npm install
$ ./scripts/createArchive.sh
```

Once the `.bna` is created, you can import it in the [playground](http://composer-playground.mybluemix.net/). Click on the `Test` menu item and submit `Bootstrap` transaction with the default payload.

You can see various assets(`Claim`, `Policy`) and participants(`Adjustor`, `Agent`, `Admin`, `PolicyHolder`)  that got created by the `Bootstrap` transaction.

Now, select `AssignPrimaryAgent` from the transaction drop-down and use the following JSON payload:

```
{
  "$class": "org.example.subrogation.AssignPrimaryAgent",
  "primaryAgent": "resource:org.example.subrogation.Agent#alfred.pennyworth@example.com",
  "claim": "resource:org.example.subrogation.Claim#C1"
}
```

to submit the transaction. The corresponding transaction processing function `onAssignPrimaryAgent()` defined in `lib/logic.js` looks like this:

```
/**
 * Assigns specified primary agent to the specified Claim. When a new primary
 * agent is assigned to a Claim, it's status changes to UNDER_REVIEW as new
 * set of eyes will be looking at the Claim.
 *
 * @param {org.example.subrogation.AssignPrimaryAgent} txn -- AssignPrimaryAgent transaction
 * @transaction
 */
function onAssignPrimaryAgent(txn) {
    // Validation
    ....
    var oldStatus = txn.claim.status;
    txn.claim.primaryAgent = txn.primaryAgent;
    txn.claim.status = 'UNDER_REVIEW';
    txn.claim.lastUpdatedAt = txn.timestamp;
    txn.claim.lastUpdatedBy = getCurrentParticipant();

    return getAssetRegistry(CLAIM)
          .then(function(claimRegistry) {
              dispatchStatusUpdateEvent(txn, oldStatus);
              claimRegistry.update(txn.claim);
          }
    );
}
```

The following fields -- `primaryAgent`, `status`, `lastUpdatedAt`, and `lastUpdatedBy`--  of `Claim C1` should have been updated as shown above. However, even after refreshing the browser, the `Claim C1` does not show the updated fields.

Thinking that it might be a quirk in the playground, I tried the same thing by deploying the business network archive to `Hyperledger Fabric 1.0.4`. I generated the angular-app that resulted in the REST endpoints to be made available. I used the REST endpoint to submit the `AssignPrimaryAgent`  transaction by posting the JSON payload and then tried to see if the `Claim C1` was updated(once again using the REST endpoint). However, `Claim C1` was still not updated. Note that there are no errors reported to indicate that something has gone wrong.

Since this used to work with `Composer 0.10.1`, I am wondering if anything has changed. 
## Expected Behavior
Assets must be getting updated with `Composer 0.16.1`.

## Actual Behavior
Assets are not getting updated with `Composer 0.16.1`.

## Steps to Reproduce
See above.

## Context
See above.

## Your Environment

* Version used: 0.1.6.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node 8.9.1
* Operating System and version (desktop or mobile): Mac OSX 10.12
* Link to your project: https://github.com/sanjay-saxena/subrogation-network

**Comment by EllisHenderson** [comment]
Returning the result of the claim update should resolve this. 

What you want to do is return the promise that will be resolved once the asset has been updated in the registry, which isn't what's being doing by the code currently.

``` return claimRegistry.update(txn.claim); ```

**Comment by sanjay-saxena** [comment]
Thanks for your suggestion, @EllisHenderson! It did resolve the issue.

However, I am wondering is this a backward compatibility issue? If it is, was it called out in the release notes or any such place for folks to update their business logic before upgrading?
