### ISSUE TITLE
Authorization error whileEnabling multiple user mode for the REST server

### ISSUE THREAD

**Issue by rajadilipkolli** [hyperledger/composer#2943]
I am using hyperledger 0.16.0

As part of enabling multi user mode for [REST server](https://hyperledger.github.io/composer//integrating/enabling-multiuser) I have setup these:

1)Installed Github-passport
2)Exported COMPOSER_PROVIDERS
3)started REST: composer-rest-server -c admin@xyz-network -n never -m true 
4)Created a new participant(krishn) and assigned identity
5)Imported above created card using POST Wallet API
6)While calling GET/ Wallet ,I am able to see imported wallet as Default

Issue:
While calling /PING I am getting this error:
401:Authorization Required

Please suggest.

Another Observation:
1)When I went through "metadata.json" file of above created identity card I found user didnt have any ROLES assigned.Is this expected?

**Comment by sstone1** [comment]
@rajadilipkolli if you get a 401 Authorization Required, it means you have not authenticated using GitHub. Please follow the steps to access the `/auth/github` API.
