### ISSUE TITLE
Yo Generator Angular don't work for tutorial

### ISSUE THREAD

**Issue by greatgonzoitaly** [hyperledger/composer#2945]
## Context
In the tutorial on

[https://hyperledger.github.io/composer/tutorials/developer-tutorial.html](url)

The business network works very good!
I try to generate a Angular Skeleton App using yeoman, all works fine.
I navigate to localhost:4200 and the application load correctly.
But when I try to click on the drop-down menu of Asset and later on the item Commodity nothing appear.

## Expected Behavior
When I click on Commodity Item a new page where I can manage the assets appear

## Actual Behavior
When I click on Commodity Item nothing happens

## Your Environment
* Version used: all version of composer and tools are 0.16 and the yo generator is update
* Environment name and version (Docker Engine 17.09, Docker-Compose 1.16.1, Node 8.9.1, Npm 5.5.1, Git 2.10.1, Python ):
* Operating System and version (Mac OS X 10.12.6):

**Comment by nklincoln** [comment]
Possibly resolved under #2986

**Comment by greatgonzoitaly** [comment]
Yes I confirm. Solved under #2986. Today I have update Yo and the problem was solved.
