### ISSUE TITLE
Composer network deploy CLI has lost capability

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2952]
The `composer network deploy` cli used to call the connector deploy. The hlfv1 connector deploy has logic to make decisions about how to manage runtime install and instantiation. The CLI has now circumvented this and just calls install followed by start effectively breaking the capability of deploy for anything except simple use cases.

**Comment by davidkel** [comment]
This only needs to be fixed in 0.16.x branch. Deploy is going to be removed in the master branch.

**Comment by samjsmith** [comment]
@davidkel we're struggling to see what capability has been lost here. 
Can you effectively achieve the same thing with `install` and `start` as you do with `deploy`?
If so, we could remove the doc to `deploy` which would also solve issue #2951.

**Comment by samjsmith** [comment]
also, this would effectively solve #2845 since that is also related to the deploy command.

**Comment by samjsmith** [comment]
@davidkel don't worry about this now. I think we've decided on a way forward :)

**Comment by samjsmith** [comment]
Proposal is to change this doc to replace `composer network deploy` with `composer network start` as this seems to be the only place in the doc where it is mentioned to users other than reference pages.
