### ISSUE TITLE
Publish stable, 0.16.x, web playground

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#2961]
Related to #2886

## Context

The current recommendation is that people use 0.16.x to begin their blockchain adventures, and only try the latest/unstable code if they have a particular reason to. There will soon be stable, latest and unstable versions of the doc for this reason, but there also needs to be a stable deployment of the web playground to go with the stable docs!

## Expected Behavior

When I choose to try the online playground in the stable docs, I should end up on a version of the playground that matches the documentation!

## Actual Behavior

There are currently only latest and unstable deployments of the playground and these are not properly linked to from the equivalent docs

## Possible Fix

Deploy the latest playground to composer-playground-latest.mybluemix.net and use the data/links.yml configuration in the docs to link to the correct playground from each version of the docs

**Comment by mbwhite** [comment]
#2966 has code to support different URLs for the stable/latest playgrounds
