### ISSUE TITLE
Unhelpful error message if specifying identified by on a transaction.

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2973]
If you define a transaction as follows
```
transaction SampleTransaction identified by transactionId {
  o String transactionId
}
```
you get an error 
`t: Identifier cannot extend from super type.`
which isn't very meaningful

Change it to 
```
transaction SampleTransaction identified by transactionId1 {
  o String transactionId1
}
```
And you get
`t: Transaction should not specify an identifying field. Line 6 column 1, to line 8 column 2.
`
More meaningful and has information of where to look.

**Comment by davidkel** [comment]
So a fix went into validation to try to handle the 2 scenarios
```
namespace com.testing

abstract asset p1 identified by a1 {
   o String a1
}
asset p2 identified by a1 extends p1 {
   o String a2
}
```
the fix and test are actually broken, also transaction validation should be done before calling the superclass. The original issue was 
#2607

**Comment by bstolman** [comment]
Hello all! What was the exact fix for this?

**Comment by ezmoneySniper** [comment]
transactionId is already reserved (you don't need to model/define it - a transaction Id is returned when a transaction is submitted - Or call the field something else if you are using it for your own transaction purposes) - the Docs do mention this about transactionId https://hyperledger.github.io/composer/latest/reference/cto_language

you do not use 'identified by' in your definition of the transaction - unlike Participants and Assets

its mentioned in
