### ISSUE TITLE
Restserver docker not working

### ISSUE THREAD

**Issue by rajadilipkolli** [hyperledger/composer#2985]
## Context
I am using composer version 0.16.0 and want to use rest server as a docker image as mentioned in [this](https://hyperledger.github.io/composer/integrating/deploying-the-rest-server.html) tutorial.

I have reached end step and when I see logs by issuing command `docker logs -f rest` I get below error

```

App [composer-rest-server] with id [0] and pid [128], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:composer-rest-server id:0
PM2        | App name:composer-rest-server id:0 online
0|composer | WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
0|composer | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
0|composer | Discovering types from business network definition ...
0|composer | Connection fails: Error: Card not found: admin@dam-network
0|composer | It will be retried for the next request.
0|composer | Exception: Error: Card not found: admin@dam-network
0|composer | { Error: Card not found: admin@dam-network
0|composer |     at IdCard.fromDirectory.catch.cause (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/cardstore/filesystemcardstore.js:74:27)
0|composer |     at <anonymous>
0|composer |   cause: 
0|composer |    { Error: Unable to read card directory: /home/composer/.composer/cards/admin@dam-network
0|composer |     at newErrorWithCause (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/idcard.js:36:19)
0|composer |     at fs.stat.catch.cause (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/idcard.js:323:19)
0|composer |     at <anonymous>
0|composer |      cause: 
0|composer |       { Error: EACCES: permission denied, stat '/home/composer/.composer/cards/admin@dam-network'
0|composer |         errno: -13,
0|composer |         code: 'EACCES',
0|composer |         syscall: 'stat',
0|composer |         path: '/home/composer/.composer/cards/admin@dam-network' } } }

```

## Expected Behavior
This should run normally

**Comment by rajadilipkolli** [comment]
@lesleyannjordan  It is fixed after issuing chmod -R 777 ~/.composer. I would like to know what is the exact permission that should be given to ~/.composer so that cards can be copied to docker rest container?

**Comment by manishgupta1968** [comment]
@rajadilipkolli Hi Raja. I am right now struggling with a similar issue as yours. Could you pls tell a little more pedantically, how you issued the chmod command. I am using the IBM Blockchain on Kubernetes (free) to tryout.


0|composer |       { Error: ENOENT: no such file or directory, stat '/home/composer/.composer/cards/admin@my-basic-sample'
0|composer |         errno: -2,
0|composer |         code: 'ENOENT',
0|composer |         syscall: 'stat',
0|composer |         path: '/home/composer/.composer/cards/admin@my-basic-sample' } } }
PM2        | App [composer-rest-server] with id [0] and pid [208], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:composer-rest-server id:0
PM2        | App name:composer-rest-server id:0 online
0|composer | WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
0|composer | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
0|composer | Discovering types from business network definition ...
0|composer | Connection fails: Error: Card not found: admin@my-basic-sample
0|composer | It will be retried for the next request.
0|composer | Exception: Error: Card not found: admin@my-basic-sample
0|composer | { Error: Card not found: admin@my-basic-sample
0|composer |     at IdCard.fromDirectory.catch.cause (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/cardstore/filesystemcardstore.js:74:27)
0|composer |     at <anonymous>
0|composer |   cause: 
0|composer |    { Error: Unable to read card directory: /home/composer/.composer/cards/admin@my-basic-sample
0|composer |     at newErrorWithCause (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/idcard.js:36:19)
0|composer |     at fs.stat.catch.cause (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/idcard.js:323:19)
0|composer |     at <anonymous>
0|composer |      cause: 
0|composer |       { Error: ENOENT: no such file or directory, stat '/home/composer/.composer/cards/admin@my-basic-sample'
Logs from 12/11/17 11:05 AM to 12/11/17 11:06 AM

**Comment by rajadilipkolli** [comment]
@manishgupta1968  When a new card is created it gets copied in the /home/<<username>>/.composer/cards directory so I have given 777 permission to this folder after which when I used rest docker container it is able to copy card to docker container.

**Comment by sstone1** [comment]
Sounds like it is working now.

**Comment by rajadilipkolli** [comment]
@sstone1 It is working but I would like to know what is the correct permissions what I need to provide to directory `/home/username/.composer/cards` , I am not inclining to provide 777 permission.
