### ISSUE TITLE
Business network name displayed on log in page when using browser back button

### ISSUE THREAD

**Issue by KaiUsher** [hyperledger/composer#2987]
If you log in to a business network and then use the browser's back button the title on the top banner still displays the business network name and not _Hyperledger Composer Playground_. If you get back to the log in page via properly logging out this is not the case.

## Steps to Reproduce
1. Create and log in to a business network.
2. 'Go back' using the browser's back button.
3. Notice title at the top left incorrectly displays the business network name.

**Comment by awjh-ibm** [comment]
I have a fix for this but it will rely on PR #2905 going in first
