### ISSUE TITLE
Deploy of Stable Composer-playground/docs fails

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#2990]
Due to a the way the TRAVIS_BUILD env variable works, it gets set to the same as the TAG.

Therefore we need to adjust the build to use a regular expression. 
```
elif [[ "${TRAVIS_BRANCH}" =~ v0\.16\.[0-9]{1,2} ]]; then
```

**Comment by jt-nti** [comment]
Think this is the related Travis issue https://github.com/travis-ci/travis-ci/issues/4745
