### ISSUE TITLE
composer card create should import card by default

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#2992]
Creating a card currently only creates a .card file but does not import it ready for use. There are situations when someone will need to create a card but not use it, i.e. to give to someone else, however this behaviour is counterintuitive for new/most users who will be creating a card to use themselves.

## Expected Behavior

A card created using the `composer card create` should be created in the card store by default

## Actual Behavior

The `composer card create` command only creates a .card file which must then be imported

## Possible Fix

1. Make the _--file, -f_ argument optional. Import the card automatically if it is not specified, or create the .card file without importing if it is specified
2. Add an explicit flag to specify whether the new card should be imported or not

**Comment by davidkel** [comment]
Duplicate of https://github.com/hyperledger/composer/issues/2893
But this one has more detail :-)

**Comment by sstone1** [comment]
My vote is for option 2.
