### ISSUE TITLE
Installing dev env doc only has fabric zip instructions

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#3000]
## Context

Hyperledger Composer does not currently support Windows. Linux environments are more likely to include the tools to extract files from a `.tar.gz` archive, than a `.zip` archive, and OSX can also unpack `.tar.gz` archives.

## Expected Behavior

The `.tar.gz` file should be primary/only option for for installing the fabric development server in the development environment installation instructions

## Actual Behavior

The latest docs have removed the `.tar.gz` instructions and only left the `.zip` option

## Possible Fix

1. Remove `.zip` option and replace it with the `.tar.gz` instructions, or

2. Add `.tar.gz` instructions above the `.zip` option and keep both

**Comment by sstone1** [comment]
@davidkel has already done this.
