### ISSUE TITLE
Script changes to properly support multiple releases

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#3003]
The recent v0.16.2 highlighted that the current scripts that power the releases are not properly able to cope with the concept of a 'latest' (stable) release and a 'next' (beta if you will) release.

This issue is track the changes that are required to support this. 

NOTE: Keep Watching this for updates....
Discussion please in https://github.com/orgs/hyperledger/teams/composer-contributors/discussions/1

| Release           |  Playground URL                                 | Docs URL                              | NPM tag          | Docker tag |
| :--------         |  :--                                            | :--                                   | :--              | :--        |
| **v0.16.x**       |                                                 |                                       |                  |            |
| Candidate Builds  | composer-playground-unstable.mybluemix.net      | ...io/composer/unstable/xxx.html      | @unstable        | n/a        |
| Release (DEFAULT) | composer-playground.mybluemix.net               | ...io/composer/xxx.html               | @latest          | @latest    |
|                   |                                                 |                                       |                  |            |
| **v0.17.x**       |                                                 |                                       |                  |            |
| Candidate Builds  | composer-playground-next-unstable.mybluemix.net | ...io/composer/next-unstable/xxx.html | @next-unstable         | n/a        |
| Release           | composer-playground-next.mybluemix.net          | ...io/composer/next/xxx.html          | @next            | @next      |

*Defn:*  Candidate Builds means any merged build is possible to be made the released build. This includes both the overnight cron build
and regular builds.  i.e. any good build could be potentially released.

The docs pages will be structured as below... a single landing page that primarily refers to the latest documentation (v0.16.x currently)
It may wish to include links to the next documentation. The rest of the documentation does not have a landing page. Rather the entry point
is the introduction page.

```
hyperledger.github.io
└── composer
    ├── index.html
    ├── introduction
    │   └── introduction.html
    ├── latest-unstable
    │   └── introduction
    │       └── introduction.html
    ├── next
    │   └── introduction
    │       └── introduction.html
    └── next-unstable
        └── introduction
            └── introduction.html
```

**Comment by mbwhite** [comment]
There are 7 build tasks

- {}
- env: DOCS=full FC_TASK=docs
- env: FVTEST=embedded,proxy,web FC_TASK=systest
- env: FVTEST=hlfv1-1_tls FC_TASK=systest
- env: FVTEST=hlfv1-2_tls FC_TASK=systest
- env: INTEST=hlfv1 FC_TASK=systest
- env: INTEST=e2e FC_TASK=systest

**Comment by sstone1** [comment]
This must be done by now 😉
