### ISSUE TITLE
Can connect to an identity which is bound to a participant that no longer exists

### ISSUE THREAD

**Issue by EllisHenderson** [hyperledger/composer#3011]
Trying to use an ID after the participant it is bound to has been deleted throws an error. I would expect this interaction to stop here and the ID not to be used, however what actually happens is you use the ID and can't do anything within the business network as a result. 

It is possible to get out of this state by going back to the ID Registry and using a valid ID. 

Steps to reproduce; 

1. Deploy and connect to a Business Network
2. Create a participant
3. Create a new ID using the participant you created in step 2. 
4. Go to the participant registry and delete the participant you created in step 2.
5. Go to the ID registry and try to use the ID created in step 3. (This should throw an error: "The current identity is bound to a participant that does not exist")
6. Try to do anything within the Business Network.

**Comment by awjh-ibm** [comment]
An extension to this is that a user whilst using an identity bound to a participant can delete that participant. This causes playground to throw errors when the user clicks stating their identity is bound to a participant that doesn't exist. They are able to get out of this by getting to the ID registry page and switching to another participant.

**Comment by awjh-ibm** [comment]
Simplest solution may be to just destroy any identity that is linked to participant that is deleted.

Another that I have worked on is to leave the identity in but alert the user and prevent them from selecting them (screenshot below) 

![screen shot 2017-12-21 at 14 00 19](https://user-images.githubusercontent.com/31732124/34258896-f38ed4f4-e657-11e7-9672-4b473e93b99a.png)

In the above solution when the identities are loaded they are compared against the list of participants for the network (which are retrieved in the same manner as the list when issuing an identity) and if the participant doesn't exist the message 'IDENTIFIER NOT FOUND' occurs.
