### ISSUE TITLE
As a User I don't get any benefit using the 1 line installer over alternative approaches

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#3019]
There is little benefit to the 1 line installer now as playground can pick up cards loaded into the card store. 

This item is about removing the 1 line installer from the code base and updating the tutorial docs that reference it appropriately.

**Comment by davidkel** [comment]
@EdMoffatt Reassigning to me as we need to completely remove all references to the 1-line installer.

**Comment by EdMoffatt** [comment]
Going to tackle this one today (just had a chat with Dave about it).  The plan is to fully remove the One Line Installer from the unstable docs now, as the instructions will soon cease to work!
