### ISSUE TITLE
Fetch an particular attribute from a resource using Query Langauge

### ISSUE THREAD

**Issue by pradeeppadmarajaiah** [hyperledger/composer#3020]
How to fetch a particular attribute from a resource using Query Langauge.

For example, for all the Employees, I need fetch email from the Employee participant. (Similar to get specific columns in the table: SELECT email from the employee)

There is a sample query in the doc to fetch all Employee attributes.

query Q1{ description: "Select all Employees older than" statement: SELECT org.acme.Employee }

**Comment by sstone1** [comment]
This is not possible today, and it is not something we are considering adding. You currently need to query all of the Employee participants, and then you can select the attributes you want on the client side in your application.
