### ISSUE TITLE
"Failed to add object with ID 'PeerAdmin' as the object already exists" error when try to split tests into multiple files

### ISSUE THREAD

**Issue by deanzaka** [hyperledger/composer#3023]
when running mocha test with multiple files, calling importCard for PeerAdmin multiple times will result a "Failed to add object with ID 'PeerAdmin' as the object already exists" error.

## Context

I need to split my test files into multiple files. Since the cards are get reset on each file, I need to call importCard for each files. Problem is, for PeerAdmin, because we provide a 'fake credentials' it used importIdentity which doesn't check if the object already exist in db or not before calling identities.add
(check for importIdentity in 'node_modules/composer-connector-embedded/lib/embeddedconnectionmanager.js')

In comparison, for other user (admin, etc), when we call issueIdentity it will call createIdentity which do check if the object already exist in db or not before calling identities.add
(check for createIdentity in 'node_modules/composer-connector-embedded/lib/embeddedconnection.js')

## Expected Behavior

I should be able to use importCard for 'PeerAdmin' in each of my test files

## Actual Behavior

I can't use importCard multiple times for 'PeerAdmin' because the object is already exist in db

## Possible Fix

add a validation to check if object already exist in db for importIdentity in 'node_modules/composer-connector-embedded/lib/embeddedconnectionmanager.js', just like in createIdentity in 'node_modules/composer-connector-embedded/lib/embeddedconnection.js'

## Steps to Reproduce

1. Use any sample from composer-network-samples/packages
2. Make a duplicate of sample.js under test folder so we have multiple test files now
3. run `npm run test-inner`

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by davidkel** [comment]
The embedded connector needs to manage identities differently. The issue for this is #2857 
I will reference this issue there and close it, and when that issue is addressed it should provide a clearer behaviour around unit testing identity operations in the embedded connector
