### ISSUE TITLE
--defaultchain flag should be removed from docker-compose.yml

### ISSUE THREAD

**Issue by bh4rtp** [hyperledger/composer#3024]
the `--defaultchain` flag was removed from the latest fabric. so the `docker-compose.yml` file should be revised in the configuration of `peer0.org1.example.com`. the start command can be changed from
`command: peer node start --peer-defaultchain=false`
to be
`command: peer node start`

**Comment by sstone1** [comment]
@bh4rtp we will make any required changes as we pick up Fabric releases - currently we are using Fabric v1.1 preview and we will switch to the Fabric v1.1 alpha. We will not make changes for interim builds.
