### ISSUE TITLE
Data Collection Tool

### ISSUE THREAD

**Issue by lesleyannjordan** [hyperledger/composer#3051]
# Abstract
A new commandline tool for collecting all relevant information from a users system.

# Motivation
<Why are we doing this?>
As a support/service engineer I would like an automated and easy way to capture a clients system and environment information so I can accurately replicate the system and have a reliable chance to reproduce scenarios.

# Specification
<What are we proposing to do?>
As a start collect environment variables, operating system versions, CPU/memory, installed npm packages, list of business network cards - anything that can aid in problem detection.

# Rationale
<Why are we proposing to do it this way?>
Outlined in the motivation section of this document.

# Backwards compatibility
<Who does it break?>
This is an application of composer and thus will not make any breaking changes to composer itself.

# Test cases
<How are we going to test it?>
Appropriate tests should be defined and run against simulated common environment scenarios.   Automated tests will be implemented where possible.

# Implementation
<Who is going to do it?>
The service team will  implement this using the specification outlined above and will deliver it via pull request to the composer repository.

# Copyright

This document is licensed under the Creative Commons Attribution 4.0 International Public License.

**Comment by jt-nti** [comment]
Should this be part of the composer cli, e.g. `composer report create` or a completely separate tool?

**Comment by lesleyannjordan** [comment]
**Initial Discussion of possible work parts:**

Define a mechanism for the tool to call and capture and package (zip) the information for attachment to tickets.
Node information capture
Container information capture
Logs


**Below is a initial proposal template of information to be included in a service ticket:**

1. - The problem title
2. - Background context
3. - Composer version
4. - Operating System/version
5. - What steps you took to reach your current situation or state
6. - Any supporting logs, script or model files - so as to help troubleshoot or identify where the problem lies.

The Data Collection Tool should aim to provide an easy process to provide information for steps 3, 4 and possible 6

**Comment by mbwhite** [comment]
Some additional thoughts

- #2993  defined a directory under `~/.composer` where the log files go if there is no other specification. Could be a useful location
- For capturing the chaincode container (runtime details) this should be defined as a system transaction.
That can then route back all the information. (Tempted to add this temporarily as it could be useful to create all the log level trace points for testing!)

**Comment by samjsmith** [comment]
PR #85 added a new `gatherData.sh` shell script to the hyperledger/composer-tools project which was written as a prototype for the sort of thing that we want to capture. It gets the following data:

Current versions of:
- OS via uname
- NodeJS
- NPM
- CLI
- docker-compose
- docker
Information about currently running docker containers via `docker ps`
Information about current business network cards via `composer card list`
It extracts docker logs for all currently running containers

It then packages these files up into a single `.zip` file in the `/tmp/` directory.

**Comment by jt-nti** [comment]
On the subject of system transactions to collect additional data from specific business networks, ACL control could be an issue if we use system transactions- it seems reasonably likely that the first time anyone would realise they needed to grant a participant access to the report transaction would be when they already have a problem and no permission to run the report transaction!

@mbwhite mentioned that there is an alternative (used by getLogLevel?) that anyone could run, and we should at least use that for basic info. Perhaps network name and version?

**Comment by bestbeforetoday** [comment]
Tried running (with Composer 0.17.3) in a directory where I didn't have write permission and got this (not super-friendly) output:
```
$ composer-report

Writing Node.js report to file: node-report.20180201.110804.6763.001.txt
Node.js report completed

Writing Node.js report to file: node-report.20180201.110804.6763.002.txt


#
# Fatal error in ../deps/v8/src/handles.h, line 212
# Check failed: (location_) != nullptr.
#
Illegal instruction: 4
```

**Comment by samjsmith** [comment]
Thanks Mark, we probably just need to test wrtite access before running node-report like [this](https://nodejs.org/api/fs.html#fs_fs_accesssync_path_mode)

**Comment by jt-nti** [comment]
@samjsmith I'm doing an update to include the composer report version in the report at the moment, so I'll add that check in as well

**Comment by jt-nti** [comment]
Initial work is done. Rather than keep this issue open indefinitely, any additional data collection should be added through follow on issues
