### ISSUE TITLE
Standalone Chaincode Executable Tool

### ISSUE THREAD

**Issue by lesleyannjordan** [hyperledger/composer#3052]
# Abstract
A new tool which enables the running of the Huperledger Composer v0.16.x runtime with Go/Duktape in a standalone executable.

# Motivation
<Why are we doing this?>
As a service engineer I would like a standalone tool which given a BNA file and some sample data can stub the Blockchain network and enable me to run and debug the chaincode stack.

Provides a 'mud bath' environment for replicating and testing client scenarios without the need to fully stand up the Blockchain network.

# Specification
<What are we proposing to do?>

# Rationale
<Why are we proposing to do it this way?>
Outlined in the motivation section of this document.

# Backwards compatibility
<Who does it break?>
This is a new standalone tool and thus will not make any breaking changes to composer.

# Test cases
<How are we going to test it?>
Appropriate tests should be defined and run against simulated common environment scenarios.   Automated tests will be implemented where possible.

# Implementation
<Who is going to do it?>
The service team will  implement this using the specification outlined above and will deliver it via pull request to the composer repository.

# Copyright
This document is licensed under the Creative Commons Attribution 4.0 International Public License.

**Comment by jt-nti** [comment]
See https://github.com/hyperledger/composer/blob/master/contrib-notes/coding-guidelines.md#how-to-run-local-code-inside-a-real-fabric for related info

**Comment by lesleyannjordan** [comment]
Closing; Given that 0.19 is now the latest replacing 0.16 we won't do any further enhancements for 0.16.x in this respect.
