### ISSUE TITLE
As a user I want the sample-networks to work for stable and next releases

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#3054]
We have a single master branch for sample-networks at the moment. The samples contain both implementation and unit tests. There are a couple of issues regarding 0.16.x and master.
- for the implementation we want to demonstrate async/await and remove promise chains but these implementations will only work in the master branch
- The unit tests use the embedded connector to specify that connector for 0.16.x you use the `type` property but for the master you use the `x-type` property. So the current samples unit tests will not run against master
- The package.json files are fixed to a specific level of composer for the unit tests
We need a strategy to split the sample networks. The generated BNAs are still compatible with both 0.16.x and master

**Comment by davidkel** [comment]
Be aware that this may require changes to the 0.16.x branch docs as it points to master when referencing the composer-sample-networks

**Comment by sstone1** [comment]
@markcastle3 no idea why this was assigned to me and @caroline-church, there was no part of this work that _required_ a maintainer role. I've done most of it anyway, but someone else should pick up the remaining work around documentation.

**Comment by davidkel** [comment]
Closing now as should be complete
