### ISSUE TITLE
The following documentation requires review/updates

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#3060]
The following pages have been changed. There is a need for review and test, plus fix some formatting issues and add page links
- [x] https://hyperledger.github.io/composer/next-unstable/managing/connector-information
- [x] https://hyperledger.github.io/composer/next-unstable/reference/connectionprofile
- [x] https://hyperledger.github.io/composer/next-unstable/tutorials/deploy-to-fabric-single-org
- [x] https://hyperledger.github.io/composer/next-unstable/tutorials/deploy-to-fabric-multi-org
- [x] https://hyperledger.github.io/composer/next-unstable/installing/development-tools 
- [x] https://hyperledger.github.io/composer/next-unstable/integrating/deploying-the-rest-server
(missed a :next off the second example - need to fix)

The following will be changed but hasn't yet #3019 
- [ ] https://hyperledger.github.io/composer/next-unstable/installing/using-playground-locally

**Comment by samjsmith** [comment]
Just reviewing the links above:

- [ ] https://hyperledger.github.io/composer/next-unstable/managing/connector-information
Needs the parameter/example for Identity Issue
Has a TBD section for Connection Profiles at the bottom - maybe this needs to be removed now?

- [ ] https://hyperledger.github.io/composer/next-unstable/tutorials/deploy-to-fabric-single-org
Step 8 misses out the fact that a file with a default name of `admin@tutorial-network.card` has been auto generated. This name comes is just `admin@` the name of the business network in the BNA with a `.card` extension.  You can override this with the `-f` option.
Other than that, it's a really good tutorial!
