### ISSUE TITLE
As a user I need to be able to guarantee events are received from Composer transactions

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#3067]
The node-sdk is implementing a new channel event capability. However this is the comment regarding guarantee-ing events.
```
The events are ephemeral, such that if a registered listener
 * crashed when the event is published, the listener will miss the event.
 * There are several techniques to compensate for missed events due to client crashes:
 * <li>register block event listeners and record the block numbers received, such that
 *     when the next block arrives and its number is not the next in sequence, then
 *     the application knows exactly which block events have been missed. It can then use
 *     [queryBlock]{@link Channel#queryBlock} to get those missed blocks from the target peer.
 * <li>use a message queue to catch all the block events. With many robust message queue
 *     implementations available today, you will be guaranteed to not miss an event. A
 *     fabric event listener can be written in any programming language. The following
 *     implementations can be used as reference to write the necessary glue code between
 *     the fabric event stream and a message queue:
```
A node-sdk user would have to  do something in order to handle this. I would guess at this time the node-sdk is not going to offer any capability in this area.
This issue is for discussion about what we will offer composer users (if anything) in this area. It should also be noted offering no support and trying to push this back onto the fabric node-sdk implementation should at least result in documentation describing expectation.

**Comment by santhosh-ktec** [comment]
I guess providing options to publish events to Kafka would solve. The events can be guaranteed of delivery based on the kafka retention policy set and the listening client can listen or ignore missed events if they want by adjusting their offset.
