### ISSUE TITLE
As a developer, i should be able to call protected Rest APIs that require authorization token in the request headers

### ISSUE THREAD

**Issue by elenduuche** [hyperledger/composer#3071]
As a developer, i should be able to call a protected rest api, that **expects an authorization token** in the request header, using composer-runtime api's `post()` method.

## Context
I tried to call a Rest API that requires i provide an authorisation token. This call fails because the `post()` method, does not accept request header data. Hence, my call always fails. Support for request headers is critical for production, as most Rest APIs in production are protected.

## Expected Behavior
I should be able to supply request headers, in to meet the request header requirement of Rest APIs that require authentication/authorization.

## Actual Behavior
Today, the `post()` method does not support **request headers**, hence the post fail with an *authorization failed error*.

## Your Environment

* Version used: composer version 0.15.1
* Node.js 8.9.1
* MacOS 10.13.2

**Comment by sstone1** [comment]
Folding this into #3092.
