### ISSUE TITLE
Go log points should include transaction Id

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#3073]
If you start the fabric network with `CORE_CHAINCODE_LOGGING_LEVEL=DEBUG` on the peer then you are able to control composer runtime logging through the `composer network loglevel` command. However if you don't have this environment variable set or set to debug, then `composer network loglevel` only changes the logging level of Go chaincode and doesn't affect the composer javascript runtime meaning you cannot get any debug about from the main runtime code dynamically.

Also we should really include a short TxId, and optionally the composer index in the output so it's possible to tie the flows together within the single log output.

**Comment by davidkel** [comment]
Just as worrying but it looks like messages were lost as well from the chaincode. Looking at a log there were definitely missing log entries.

**Comment by davidkel** [comment]
ok, the problem is here
https://github.com/hyperledger/composer/blob/v0.16.x/packages/composer-common/lib/log/logger.js#L93
as the Go chaincode is passing the log level of 'DEBUG' and probably ignoring any error thrown. As the logger only recognises lower case strings we should convert it to lower case first.

**Comment by davidkel** [comment]
This code in LoggingService.getLogInserts would add the required short transaction id to the javascript code
```
        if loggingService.Stub != nil {
                result = append(result, "[" + loggingService.Stub.GetTxID()[0:8] + "] ")
        }
```
but we would need to add it for all the Go level logging calls, so we should centralise the logging for the Go code to handle this. Also we seem to be passing into the logs memory addresses and I cannot see a useful application of this information as yet so maybe we should look at better information in the Go Logging code.

**Comment by mbwhite** [comment]
Fyi, Lord of tracing features resolved by pr in waiting. Didn't managed to get it before the holidays

**Comment by davidkel** [comment]
In summary, the final piece here is that all the logging in the Go code should output the associated transaction id. This potentially touches all the log statements in the go code. However what we have may be good enough now for 0.16.x so can consider closing this issue and opening a new one.

**Comment by davidkel** [comment]
@lesleyannjordan should we consider closing this one ? I don't believe we need to do any further enhancements for 0.16.x in this respect.

**Comment by lesleyannjordan** [comment]
Agree
