### ISSUE TITLE
Writing node.js applications documentation is causing confusion

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#3076]
https://hyperledger.github.io/composer/stable/applications/node
there are examples that reference a `config` module. 

New developers assume this is part of our api and just expect it to work, we should remove references from the documentation to the config module, this may be that this page shouldn't reference an existing example which relies on the config module or we should change the example to not use the config module.

**Comment by davidkel** [comment]
Only applies to 0.16.x now as samples and docs have been changed for master.

**Comment by davidkel** [comment]
@lesleyannjordan Given that 0.19 (and 0.19 has resolved this) is now the latest replacing 0.16 I don't think there is a need for this issue anymore. What do you think ?

**Comment by lesleyannjordan** [comment]
Agreed, closing ticket
