### ISSUE TITLE
How to read 0.17 documentation?

### ISSUE THREAD

**Issue by nasht00** [hyperledger/composer#3077]
In the release notes for 0.16.1 (and 0.16.2? Are they duplicates?) it says:

> This week we have made changes to enable documentation availability for both of these branches as they diverge.

Yet it does not say *how* to access this documentation.

I want to start playing with 0.17 so see if it will solve some advanced issues I had.

**Comment by nasht00** [comment]
So I cloned the repo, ran the documentation locally and saw that the url contained the word `unstable`. Then I tried https://hyperledger.github.io/composer/unstable/introduction/introduction.html and it works.

So maybe we just need a link somewhere to get there.

**Comment by davidkel** [comment]
@nasht00 release points to the current 0.16 version of the docs, unstable points to the unpublished release for the next 0.16 fix release. next points to the official 0.17 release (which isn't out yet) and next-unstable points to the latestunpublished release for the 0.17 (and future releases).

**Comment by sstone1** [comment]
We'll be looking at making it easier to discover the 0.17 documentation as part of the 0.17 release, which is still in-progress.
