### ISSUE TITLE
Want to fetch all the relational data from Transaction history

### ISSUE THREAD

**Issue by purandam** [hyperledger/composer#3083]
I am using Node Js with Hyperledger Composer.  Using "getTransactionRegistry()" able to fetch the Transaction Id but I need to get asset and participant from the transaction object.
Time of Transaction declaration I am using the instance of Asset & Participate . 
So using the Transaction object I can also fetch the related Asset & Participate detail.
Note : I can fetch the data from asset or participant registry.
But I unable get all those details from Transaction object. Please tell me how can I get those data using transaction object.

**Comment by sstone1** [comment]
@purandam this is working as intended; you must resolve the relationships yourself, which is what you're already doing:
>  I can fetch the data from asset or participant registry.
Fetching back the entire asset/participant/transaction graph automatically is a bad idea as it could be huge.
