### ISSUE TITLE
Create a card with javascript API

### ISSUE THREAD

**Issue by PPCM** [hyperledger/composer#3088]
There is no exemple, no method to generate a card programmatically with the javascript API client.
In the documentation, we can find method BusinessNetworkConnection.issueIdentity, but I have the following error:

```
(node:6827) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: fabric-ca request register failed with errors [[{"code":0,"message":"Identity 'admin' may not register type 'client'"}]]
```
An exeample, will be be welcomed

## Expected Behavior
It will be great if cards could be generated with the API and not only with cli command.
The idea is to have the same behavior than cli commands:
```
composer identity issue -c admin@test-network -f partacipant.card -u newUser -a "com.test.testParticipant#newUserId"
composer card import --file participant.card
```

**Comment by sstone1** [comment]
We have issue #2767 which is for card enabling the identity management APIs.
You can refer to the source for `composer identity issue` to see how it calls BusinessNetworkConnection.issueIdentity and creates a business network card from the result:
https://github.com/hyperledger/composer/blob/master/packages/composer-cli/lib/cmds/identity/lib/issue.js#L59
