### ISSUE TITLE
As a user, I have access to a standard HTTP client in my transaction processor functions

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#3092]
## Abstract

Provide a standard HTTP client for developers to use in their transaction processor functions, so they can easily make any calls to external HTTP services.

## Motivation

The runtime API, used by transaction processor functions, currently includes a function called `post` that can be used to make an HTTP POST call to a remote HTTP server. This is being used by at least several people to integrate external logic into their transactions, for example calling out to an external rules engine.

The documentation for this _experimental_ feature is here:
https://hyperledger.github.io/composer/stable/integrating/call-out

Note that the documentation touches on the risks of calling out to external services, namely non-deterministic transactions. Because the call is made by all peers (organisations) endorsing the transaction, the call will likely be made multiple times (so it should be idempotent) and the external service may return different data to each peer (so may cause consensus failures). 

Today, the `post` function is backed by a runtime container HTTP service that uses the right HTTP API for that platform. These APIs are:

- Embedded runtime - `request` (npm module)
- Web runtime - `xhr` (npm module)
- HLFv1.0 runtime - `net/http` (Go package)
- HLFv1.1 runtime - `request` (npm module)

In order to add additional functionality to this API, such as additional verbs (#1843) or authentication support (#3071), currently we have to write and maintain a bunch of custom code to pass through to the right HTTP API which is a lot of effort for not much gain.

## Specification

I propose that we:

- Deprecate and remove the `post` function from the runtime API, along with the runtime container HTTP service that powers it.

- Include the `request` module and expose it to all transaction processor functions as a built-in module in the same way that we do for the `assert` module (see [scriptcompiler.js](https://github.com/hyperledger/composer/blob/master/packages/composer-runtime/lib/scriptcompiler.js#L54)).

  This would allow transaction processor functions to make use of the `request` module as follows:

  ```
  const response = await request.get('http://foo.com');
  const response = await request.post('http://foo.com', { body: 'woop woop' });
  ```

- We will not extend the `request` module with the ability to serialise and parse Composer resources to and from JSON. Instead, we will make it possible to serialise a Composer resource to JSON using the standard JavaScript mechanisms, `JSON.stringify`, by getting `Typed.toJSON` to use a `Serializer` instance instead of just throwing an error.

- If and when the ability for a user to require external modules is delivered in the future, look to remove the `request` module as a built-in and instead let the user explicitly include it in their dependencies.

## Rationale

The `request` module is the defacto standard HTTP client for Node.js applications, and since we have Node.js (or JavaScript) everywhere it makes sense to just use it as-is without trying to wrap it in our own API layers.

Without the ability to handle Composer resources, users would have to write their own code to use a `Serializer` to parse/serialize a Composer resource to and from a JSON payload. This is what the existing code for `post` does, _but_ it does have to expose the serializer options directly to allow the user to control the serialization behaviour. I'm not sure if this is worth it - would welcome comments:

With built-in Composer resource handling:
```
const resource = /* get me a resource */
const response = request.post('http://foo.com', { body: resource });
```

Without built-in Composer resource handling:
```
const resource = /* get me a resource */
const body = getSerializer().toJSON(resource);
const response = request.post('http://foo.com', { body });
```

We agreed not to add built-in Composer resource handling in favour of updating the code to make it possible to serialise Composer resources to JSON using standard JavaScript mechanisms. This is more familiar to JavaScript developers and will work with a wide range of third party libraries without additional wrappers.

## Backwards Compatibility

The `post` function will be deprecated and then removed, which means that existing transaction processor functions may have to change. A version bump will be needed for that change. Since we are still pre-1.0, I am OK with forcing this change on users - especially as the API is marked as experimental.

## Test Cases

Extend the existing functional tests for `post` so that they cover a variety of HTTP calls using the `request` module (different HTTP methods, additional HTTP headers, etc). Ideally we'd remove the dependency on a random Bluemix service I'm not sure anybody has control over anymore 😉 

## Implementation

I propose that I will implement this as described above and deliver via a pull request; I already have the basics working locally in a sandbox.

## Copyright

This document is licensed under the Creative Commons Attribution 4.0 International Public License.

**Comment by samjsmith** [comment]
Exposing the options on the serializer allows disabling validation of model objects and also working with incomplete object graphs.  So I can imagine scenarios where you could get yourself into a bit of a mess.  Having said that, there are myriad other ways you could get into a mess from within a transaction so I don't think it's too big a deal :)

**Comment by dselman** [comment]
I think this makes sense. The auto serialization/deserialization of composer types is convenient (but not required). If it is removed my fear is that people will just pass the resource in the request body, which will then blow up because the resource cannot be serialized to JSON.

**Comment by sstone1** [comment]
@dselman what if instead of trying to patch `request` to do the right thing, we tried to get `Typed.toJSON` to use a `Serializer` instance under the covers so that anybody can more easily serialise resources? It is a _bit_ annoying that you can't just do `JSON.stringify(asset)`.

**Comment by dselman** [comment]
That would work for the happy path, as long as we don’t lose the ability to also specify options for serialisation for advanced users. E.g. by using the serialiser explicitly.

**Comment by sstone1** [comment]
@dselman that sounds good to me. The `getSerializer` call will still be there so advanced users have full control over the serialisation, and everyone else will just get `toJSON` behaviour that uses the `Serializer` and its default options. I've updated the doc to reflect this.

If there's no more comments, it would be good to get some formal approvals from the maintainers so we can proceed (that means you too @caroline-church).
