### ISSUE TITLE
Issuing a New Identity - Doc has a crucial step missing

### ISSUE THREAD

**Issue by rthatcher** [hyperledger/composer#3103]
This Doc:
[https://hyperledger.github.io/composer/managing/identity-issue.html](url)

Has `composer identity issue ...`  then `composer network ping`  but it needs a `composer card import ...` before the ping, otherwise the ping fails

**Comment by Navdevl** [comment]
@rthatcher Hope the documentation will be clear to the users.

**Comment by jt-nti** [comment]
Thanks for the PR @Navdevl! I've assigned #3185 to @EdProsser to review
