### ISSUE TITLE
Unintuitive query syntax behavior

### ISSUE THREAD

**Issue by RobTS** [hyperledger/composer#3112]
When concatenating several WHERE conditions using AND in buildQuery, results will vary depending on the use of parentheses, leading me to believe there is an issue with the query to couchDB mapping for combining more than two conditions using AND operators.

More specifically, the following two queries, using the same inputs, will return different results, with only the latter being correct, the former returning older results as well:

```
SELECT org.test.Appointment WHERE (someNumber == _$someNumber AND arrivalDate >= _$start AND arrivalDate < _$end)
```

and

```
SELECT org.test.Appointment WHERE (someNumber == _$someNumber AND (arrivalDate >= _$start AND arrivalDate < _$end))
```

 
## Context

This goes against my and probably the public's understanding of how the AND operator functions in an SQL context.

## Expected Behavior

The expressions should be equivalent and lead to the same results.

## Actual Behavior

They are not delivering the same results, so they do not seem to be equivalent.

## Possible Fix

Use parentheses for more than two expressions you are concatenating? Seems to work with OR though, if we believe this doc: https://hyperledger.github.io/composer/business-network/historian.html

## Steps to Reproduce

1. Fill your database with simple objects containing a Date.
2. Filter by some condition AND Date between x and y, using the syntax above.
3. Depending on your parentheses use, older posts will show up or not.
4. Change the parentheses and be surprised with a different result.

## Existing issues

None found

## Your Environment

composer-client@0.16.2
│  ├─ composer-common@0.16.2
│  ├─ composer-connector-hlfv1@0.16.2
│  └─ uuid@3.0.1

MacOS

**Comment by RobTS** [comment]
Sample method for testing:

```

const getSomethingForParamAndTime = (someParam, start, end) => {
  let query = MainConnection.buildQuery('SELECT org.test.TestObject WHERE (someParam == _$someParam AND (arrivalDate >= _$start AND arrivalDate < _$end))');
  return Registries.MainConnection.query(query, { someParam, start, end })
};

```

**Comment by RobTS** [comment]
Related to #2978, I guess.

**Comment by fenglianxu** [comment]
@RobTS This issue has now been fixed, would you like to test it with our current master code stream?

**Comment by sstone1** [comment]
Fixed, please reopen if you find it is still a problem.
