### ISSUE TITLE
Unable to download newly created card from rest server explorer

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#3116]
composer-rest-server Multi-User
My workflow ...
1. Configure and start REST server for MultiUser using network admin as the card, (not using Mongo - just in memory)
2. Logged in via Github - all OK
3 Imported the Network Admin card (the version with the certificates) - all good, I can GET participants and Assets
4. Issued an Identity for one of the Participants - all good a .card file was downloaded to default downloads folder
5. Tried to Import this newly created .card file - and have this error:
{
"error": {
"statusCode": 500,
"name": "Error",
"message": "Corrupted zip or bug: expected 2 records in central dir, got 0",
"stack": "Error: Corrupted zip or bug: expected 2 records in central dir, got 0\n at ZipEntries.readCentralDir (/home/ibm/.nvm/versions/node/v8.9.0/lib/node_modules/composer-rest-server/node_modules/jszip/lib/zipEntries.js:146:23)\n at ZipEntries.load (/home/ibm/.nvm/versions/node/v8.9.0/lib/node_modules/composer-rest-server/node_modules/jszip/lib/zipEntries.js:257:14)\n at /home/ibm/.nvm/versions/node/v8.9.0/lib/node_modules/composer-rest-server/node_modules/jszip/lib/load.js:49:20\n at <anonymous>"
}

![image](https://user-images.githubusercontent.com/25582377/34682884-4207852e-f498-11e7-9aff-ef98e93c1856.png)

This might only be a problem for master, not the 0.16.x branch, but we should test this.

**Comment by sstone1** [comment]
@andrew-coleman this looks related to the problem you fixed by adding `application/json` to the list of `produces`; if `application/json` is selected (the default) then the card is corrupt, if you select `application/octet-stream` then the card is OK.

Can you take a look please?

**Comment by davidkel** [comment]
Have re-opened #2647
