### ISSUE TITLE
Suggested updates to the multi-org tutorial

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#3119]
Comments on the docs at https://hyperledger.github.io/composer/next-unstable/tutorials/deploy-to-fabric-multi-org

### Prereqs..
- Worth adding that the dev tools are not required for this tutorial as scripts from the fabic-samples repo will peform the same tasks
- Wasn't clear what the latest was referring to?
- The fabric tutorial that is cited is only needed for the setup components. Assert that we should refer to http://hyperledger-fabric.readthedocs.io/en/latest/samples.html directly, with the comment that the git report that should be cloned is Simon's *not* the one listed... 

### Step one
- Rephrase the 2nd paragraph as this composer tutorial uses the same scripts as the Fabric tutorial but with a slightly different set of options... 
- Note that the script doesn't always return you to the command line. 
- The card deletion - these are the cards that will be created - if the tutorial is run before worth making sure they have been deleted ahead of time. 

### Connection Profiles

It wasn't clear what or how many files were needed to be created before starting. I stopped deleted the files and then created a separate file system structure to hold these files. 

"It is recommened to create a temporary working directory to create the Composer connection profiles, and the network cards.."

```
mkdir -p /tmp/composer/org1
mkdir -p /tmp/composer/org2
```

In the connection profile - there are two extra commas...  search for ` "peer1.org1.example.com", ` and remove the trailing comma

In the two sets of `awk` commands change the paths to be  `/tmp/composer/org1/ca-org1.txt` and `/tmp/composer/org2/ca-org2.txt`  to reflect the suggested directory structure

The extract of the certificate file isn't formatting correctly. 

Similarly, the `/tmp/ca-orderer.txt` should be  `/tmp/composer/ca-orderer.txt`
Update the file... we should give an awk/sed script to do this....

Save the file to `connection-network.json` and then issue these commands to create profiles for the two orgs

```
cd /tmp/composer
cp connection-network.json ./org1/connection-org1.json
cp connection-network.json ./org2/connection-org2.json

```

### Card import steps.

The composer card import statements need to have the `--name` added

```
composer card import -f PeerAdmin@byfn-network-org1.card  --name PeerAdmin@byfn-network-org1
composer card import -f PeerAdmin@byfn-network-org2.card  --name PeerAdmin@byfn-network-org2
```

... not yet got any further..

**Comment by davidkel** [comment]
@EdProsser I am assuming this has done now ?

**Comment by EdProsser** [comment]
Yeah it's done. Forgot to close it. :)
