### ISSUE TITLE
Expose Fabric Shim Api

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#3120]
## Abstract
Extend the transaction processor function API so that a composer user can directly call the Fabric shim API

## Motivation
Currently whenever new function is added to the fabric api this cannot be used by composer users and has to be wrapped in a composer api inorder to expose the new function. When users decide to use composer and later find it doesn't have function that they require such as cross-channel query and encryption and greater historian support, they don't have to switch to using just fabric they can call out to the fabric api and use the native function.

## Specification

I propose that we add a new function to transaction processor functions that when called then allows you to call any of the fabric api's. The user would then be responsible for dealing with any data returned.

Below is an example of how it might be written in the transaction processor function.

```
const response = await getNativeApi().invokeChaincode(myChainCode, [arg1, arg2, arg3], myChannel)

// do something here with response

```

I also propose that two samples are written to show how this feature could be used. The first would show a cross-channel query and the second would show extended use of the historian.

For the web and embedded runtimes and error would be thrown if a native api was called.

## Rationale

There is no other way to implement this feature.

## Backwards Compatibility

This functionality will not cause any breaking changes.

## Test Cases

The existing transaction processor tests would be extended and new integration tests will be added.

## Implementation

I propose that I will implement this as described above and deliver via a pull request.

## Copyright

This document is licensed under the Creative Commons Attribution 4.0 International Public License.

**Comment by dselman** [comment]
Makes sense as a stop-gap measure, but it obviously ties the TP logic to Fabric and it now won't run in Playground or in Node.js - which will complicate deployment and testing. At a minimum we should think about how to identify networks that are using native Fabric APIs so that the runtime can reject them if it is not Fabric, rather than getting an obscure runtime error.

**Comment by nasht00** [comment]
Wouldn't https://github.com/hyperledger/composer/issues/3160 solve this requirement as well?
Or does one prerequisites the other?

**Comment by sstone1** [comment]
@nasht00 issue #3160 is purely changes to the operational model which will not change the programming model at all. Issue #3120 adds the Fabric shim API to the existing Composer runtime API so people can make use of it today. Issue #3169 is a longer term piece of work that covers updates to the programming and operational model, and may result in the APIs in this issue moving around or changing.
