### ISSUE TITLE
v16.03 Logging Issues

### ISSUE THREAD

**Issue by samjsmith** [hyperledger/composer#3123]
- [ ] Default logging level should not be DEBUG so that time isn't wasted issuing log statements.  

- [ ] When you change the log level then an incorrect message is issued
```
samsmith:cli-test# composer network loglevel --card admin@my-basic-sample -l ERROR
The logging level was successfully changed for: undefined
```

- [ ] The help for the command, the log levels are listed in the wrong order
Currently is `-newlevel, -l  the new logging level  [choices: "INFO", "WARNING", "ERROR", "DEBUG"]`
Should be `ERROR, WARNING, INFO, DEBUG`

- [ ] We set the loglevel to ERROR and issued some bad commands but no errors were listed in the log.  This could be because there are no errors issued from any of the codepaths that we executed but it would be good to verify that.
I did manage to get an ERROR in the log by deploying a BNA with a transaction function that included `console.error('this is a terrible error');` as the first statement, then I submitted the transaction and the error did appear in the log so we know it is working for users' errors.

**Comment by davidkel** [comment]
Default logging level is meant to be debug as it is a development server, not a production server and it is set to debug there, not in the code itself
Response for setting loglevel is already raised here #3074 
The choices for what values are acceptable is a very minor niggle.
I will change the priority of this as I don't think there is any reason to ever put this minor change into the 0.16.x branch

**Comment by lesleyannjordan** [comment]
Update on the ERROR loglevel part of this ticket.  During testing of  0.17.x I was able to see ERROR logs when issuing step 9 of the CLI validation https://github.com/hyperledger/composer/wiki/CLI-Validation

**Comment by mbwhite** [comment]
See also #2993

**Comment by mbwhite** [comment]
There are updates for v0.17. stream logging in #2993 - not assesed how these could be 'back ported'

**Comment by lesleyannjordan** [comment]
Closing; Given that 0.19 is now the latest replacing 0.16 we won't do any further enhancements for 0.16.x in this respect.
