### ISSUE TITLE
Automatic version bump broken in v0.16.x branch

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#3128]
The automatic version bump is trying to push the changes to master, even on the v0.16.x branch:

https://github.com/hyperledger/composer/blob/v0.16.x/.travis/deploy.sh#L226

**Comment by lesleyannjordan** [comment]
0.16.4 build failed - 

_~/build/hyperledger/composer
Switched to a new branch 'master'
....
node -e "console.log(require('${DIR}/package.json').version)"
[master ea3728d] Automatic version bump to 0.16.5
 25 files changed, 98 insertions(+), 98 deletions(-)
error: src refspec v0.16.x does not match any._

Looks like we are trying to switch to master branch in deploy script

https://github.com/hyperledger/composer/blob/v0.16.x/.travis/deploy.sh#L215

 _git checkout -b master_

**Comment by lesleyannjordan** [comment]
0.16.6 build failed with the following error:

_fatal: 'upstream/v0.16.x' is not a commit and a branch 'v0.16.x' cannot be created from it_
