### ISSUE TITLE
Document that you cannot install composer-cli as the root user on Ubuntu

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#313]
`npm install composer-cli -g` when running as root will fail on Ubuntu due to a permissions issue. Also `nvm` doesn't like being installed as root.

We should add this as a note to the quick start or prereqs.

**Comment by mbwhite** [comment]
@EdProsser  - wondering if you'd like to grab this one and I can show you how the docs build process works??

**Comment by EdProsser** [comment]
@mbwhite Sure! I'll come and speak to you in a minute.

**Comment by caroline-church** [comment]
@EdProsser Is this in your backlog of stuff to do?

**Comment by EdProsser** [comment]
Put a warning against using the command as the root user in the places this command appears in the docs. It'll be in my next PR after I've checked the pages look ok.
