### ISSUE TITLE
issuing an ID with the "allow this participant to issue ID's' box doesnt work

### ISSUE THREAD

**Issue by winslet** [hyperledger/composer#3137]
It seems as though you cannot issue an ID sometimes, this is the flow myself @caroline-church went through:

1. Issue an ID from the ~command line~ **update: from the playground** and share it with someone else.
2. Login with that card from the Playground
3. Create a new participant
4. Try and issue an ID to that new participant, with the checkbox to allow them to issue new ID's checked.

It seems the error lives in step 4. But im not sure whether the prior steps are also a cause.

This is the error:

![image](https://user-images.githubusercontent.com/13980028/34821610-3e762dae-f6bc-11e7-8364-422aa6780103.png)

**Comment by awjh-ibm** [comment]
This also occurs with cards that you create and use on your own without sharing
