### ISSUE TITLE
Please may I have some cucumber documentation?

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#3146]
## Context

I have just started developing a business network and I know that testing is a good thing(tm). I remember hearing all these fabulous things about using cucumber to test business networks but when I search the documentation, there are no results

## Expected Behavior

Cucumber testing magic is documented

## Actual Behavior

Cucumber testing magic is not documented

## Possible Fix

- Use [Simon's post](https://medium.com/@mrsimonstone/test-your-blockchain-business-network-using-hyperledger-composer-c8e8f112da08) as a basis for a new Cucumber specific testing tutorial

- Describe the predefined Composer Cucumber steps in a reference document

- Mention testing in the developer tutorial

- Update the composer-cucumber-steps package [readme](https://github.com/hyperledger/composer/blob/master/packages/composer-cucumber-steps/README.md)!

**Comment by nklincoln** [comment]
whilst adding a *well needed* Composer testing section, we should add the 'how to connect VSCode debugger' too ... that would be awesome
