### ISSUE TITLE
Improve ability to test build scripts outside travis

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#3149]
## Context

Still have not had a successful release build since splitting to latest and next versions

## Expected Behavior

Builds should work reliably

## Actual Behavior

Not so much

## Possible Fix

Structure build scripts so that they are more amenable to testing outside travis against staging registries/environments

**Comment by mbwhite** [comment]
A testing framework for the scripts 
https://github.com/ampretia/mateo
