### ISSUE TITLE
Transaction not executing: JSON error

### ISSUE THREAD

**Issue by nachoku** [hyperledger/composer#3150]
## Context
Following the official IBM tutorial:
Needed to add a transaction after modifying the Model, permission, Contract files, and adding owners and corresponding accounts.
Error below:
`Error: Generated invalid JSON: {"$class":"org.acme.sample.Account","accountId":"account1","owner":"resource:org.acme.sample.Customer#AAA","balance":NaN}`

## Expected Behavior
The transaction should Submit.

## Your Environment
Hyperledger Composer playground -> simple business network
http://composer-playground.mybluemix.net/  

##Tutorial
https://www.coursera.org/learn/ibm-blockchain-essentials-for-developers

**Comment by lesleyannjordan** [comment]
Can you provide information on which version you are running against and which IBM tutorial with the step you got the error at please, thank you
