### ISSUE TITLE
Links in next docs/playground should be consistent

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#3159]
The next stream of Composer is still a bit mixed up with the latest/stable version.

For example, if I click on links to try the online playground in the next docs, I get the latest playground. And if I click on the doc link in the next playground, I get the latest docs.

**Comment by jt-nti** [comment]
For example, from #3174

> 1.go to this link: https://hyperledger.github.io/composer/next-unstable/tutorials/playground-tutorial
> 2.click Composer Playground and this links you to V0.16.3

**Comment by jt-nti** [comment]
The link data needs updating to fix this issue...

https://github.com/hyperledger/composer/blob/master/packages/composer-website/jekylldocs/_data/links.yml

**Comment by lesleyannjordan** [comment]
Correct link is : 
http://composer-playground-next.mybluemix.net/login
