### ISSUE TITLE
Documentation required for playground when interacting with a real fabric

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#3165]
The playground tutorial is meant only working with the online playground or can be used for a local playground when using the Web connector.

I am unable to find any tutorial, documentation or guidance about using playground to deploy to a real fabric and to explain the extra option presented with a real fabric of identity to bind to an initial participant.

Because there is no documentation about this, people think that the docs are out of date and also don't know what to do.

Also there is no explanation about the PeerAdmin card that exists there and what it means if it doesn't exist. There should also be detail about the fact that this card represents a channel admin and a peer admin  and in fact you could have 2 cards representing each

**Comment by jt-nti** [comment]
The single org tutorial does mention the default user, but that's the only place I've seen it described,  and the Playground info in https://hyperledger.github.io/composer/business-network/bnd-deploy doesn't seem up to date

**Comment by davidkel** [comment]
This applies to both 0.16.x branch and master.

**Comment by jt-nti** [comment]
The "Generating an Angular application from a Business Network Archive (.BNA)" section in packages/composer-website/jekylldocs/applications/web.md is a bit unclear here as well I think (in terms of the magic admin/adminpw incantation)

**Comment by davidkel** [comment]
@lesleyannjordan This is coming up a lot with users and I think is something that we would consider getting into the stable docs as soon as we can.

**Comment by acshea** [comment]
These issues need to be addressed as a matter of priority, as they have caused me and others all sorts of grief and wasted time.

Business networks seem to deploy fine, but have an authorisation error when connecting using the admin card if it was not created with a secret of "adminpw".

I can't see this feature referenced anywhere in the documentation that myself and a client had been using i.e. https://hyperledger.github.io/composer/installing/development-tools & https://hyperledger.github.io/composer/business-network/bnd-deploy
