### ISSUE TITLE
Orphan Link on Prerequisites Page

### ISSUE THREAD

**Issue by thegmarch** [hyperledger/composer#3167]
The "setting up the mac" hyperlink ( https://hyperledger.github.io/composer/installing/prereqs-mac.html ) no longer points to a valid page.

Sends you to a page that says "Oh no!…there’s no blockchain here :(
If you fancy telling us about this please raise an issue on our Github"

Hyperlink should point to https://hyperledger.github.io/composer/installing/installing-prereqs#macos

**Comment by davidkel** [comment]
@thegmarch could you say where this broken link is in our online docs ? I can't find it.

**Comment by thegmarch** [comment]
Sorry, here's the link to the page: https://www.coursera.org/learn/ibm-blockchain-essentials-for-developers/supplement/awJf3/prerequisites

**Comment by mostafa69d** [comment]
Same issue from here:
[IBM Blockchain foundation developer - Prerequisites ](https://developer.ibm.com/courses/all/ibm-blockchain-foundation-developer/?course=begin#11985)
click on 'Setting up the Mac' => Page Not Found

I think this link should reference to this [link](https://hyperledger.github.io/composer/installing/installing-prereqs.html#macos)
