### ISSUE TITLE
As a composer developer, I want to access third-party packages from my Transaction Processor functions

### ISSUE THREAD

**Issue by andrew-coleman** [hyperledger/composer#3169]
## Abstract
Modify the Composer API and Transaction Processor (TP) Function framework to support Javascript TP logic that is packaged as an ES6 module, and consumes the Composer API as an imported module rather than via global functions.

## Motivation
Currently the framework and API for Transaction Processor functions relies on global functions rather than the standard ES6 module import/expert mechanism.  One consequence of this is that third-party NPM modules cannot be accessed from  TP functions.

This issue is part of a larger initiative to align the APIs of Fabric and Composer to create a more consistent developer experience between these two components.  It also address the requirements of users who wish to access third-party node modules from within their TP logic.  This new format will also make it easier for the developer to unit test their TP code using frameworks such as Mocha.

## Specification
Transaction Processing functions will be written in Javascript files that conform to the ES6 module specification.  Functions that are to be invoked by Composer transactions must be exported by the module.  Any third party modules required by the TP functions can be imported using the node.js ‘require’ mechanism or the ES6 module ‘import’ statement.  The Composer TP API will also be packaged as a module so that API functions that are currently available as globals (e.g. `getAssetRegistry()`, etc) will need to be imported/required like any other module.

## Rationale
This capability has been requested by several users, and in some cases has been a blocker to using Composer services.  

## Backwards Compatibility
This is a breaking change and will require existing TP code to be upgraded to use the ES6 module syntax.

## Test Cases
The unit tests and integration tests that contain TP functions will need to be modified to the new format.  New tests will be written to test the ability to import external modules.

## Implementation
This implementation of this first of all requires https://github.com/hyperledger/composer/issues/3160 to be implemented.  Following this, the composer framework will be modified to import Transaction Processor functions packaged as an ES6 module.  The Composer API will also be packaged as a module.

## Copyright
This document is licensed under the Creative Commons Attribution 4.0 International Public License.

**Comment by mffrench** [comment]
Hi,

is there any plan to let us use third party library inside BNA ? 

Best,

**Comment by bolobox** [comment]
any progress on the issue?

Thanks

**Comment by nasht00** [comment]
This should not be closed....

**Comment by jt-nti** [comment]
It looks like this is still a popular improvement proposal. It seems like it would be a reasonably large contribution but would anyone be willing to take it on and work on an implementation?

**Comment by davidkel** [comment]
To actually make this work will require the following
- expose require as a global to the composer runtime (actually a small change)
- address the issue around finding node modules while running in a fabric chaincode container (again, a small change)
- address how this could be supported in playground. I can't see how it could work in Web Browser mode. Therefore online playground would not be able to use this. It probably could work with the runtime simulator with some work but the runtime simulator is also an undocumented and un-automated tested capability, so it would need to be decided on whether this adds value but I believe the simulator provides value for faster application development (albeit with limitations around queries due to pouchdb). It should work when playground is interacting with a real fabric
- It will need documentation
- It will need both functional and integration tests
- It will need to work with both pure javascript and native node.js modules so testing also required with different node modules

**Comment by iMacTia** [comment]
@andrew-coleman have you started any work on the above, or have you found any workaround? I'm also trying to find a way to make our code more modular and to use 3rd party libraries in our TP functions.

**Comment by iMacTia** [comment]
@davidkel @jt-nti I see the problem with the playground and backwards compatibility, so how do you see the following:

1. We could make this change configurable, so developers can choose between the old and new behaviour. From what I've seen, this should be possible with the `sourceType` option set to `module` on the `JavascriptParser` which is currently set as `script`.
2. If developers opt to use the new syntax, then they won't be able to use the Playground anymore. This should be fine though as we're talking about an opt-in feature that they'll probably use when they get serious, so unit tests will be preferred at that point.
3. We can explore the support for the Playground later on as a separate piece of work.

If you could give us a little direction on how to implement the "small changes" you mentioned above, I'd be happy to give this a try:

* expose require as a global to the composer runtime (actually a small change)
* address the issue around finding node modules while running in a fabric chaincode container (again, a small change)

Where is the best portion of code I should address to add this support?

**Comment by iMacTia** [comment]
Hi @davidkel thanks for the link, shame to read Composer is not getting the same attention as before.
Could you please articulate and give some direction on the new tools available in Fabric that won't make us miss Composer?

**Comment by davidkel** [comment]
@iMacTia We hope to provide some sort of guidance about migrating composer applications if we get a chance, but for now I suggest you take a look at
https://hyperledger-fabric.readthedocs.io/en/latest/developapps/developing_applications.html
to see how the new programming model in fabric may help.

**Comment by iMacTia** [comment]
Thanks @davidkel, this was really helpful.
I wasn't aware `1.4.0-rc1` was released literally hours ago and includes the new Contract classes.
I'll definitely give it a try and see how it compares to Composer's modelling language.
