### ISSUE TITLE
Mark npm modules as requiring specific node versions and OS

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#3173]
Currently the node modules can be installed on a wide version of node versions and platforms. 

For example, you can install on node 6.9... but then it just doesn't work later on.

We should use the `engine` and `os` settings of the package.json to enforce this. 

https://docs.npmjs.com/files/package.json

**Comment by jt-nti** [comment]
Looks like some do specify the node version at least, e.g. https://github.com/hyperledger/composer/blob/master/packages/composer-common/package.json

**Comment by jt-nti** [comment]
@varun-raj might be able to help with this one https://twitter.com/zathvarun/status/954662983849820160
