### ISSUE TITLE
Business network generator should generate permissions.acl file and queries.qry

### ISSUE THREAD

**Issue by samjsmith** [hyperledger/composer#3176]
In the [developer tutorial](https://hyperledger.github.io/composer/tutorials/developer-tutorial.html) users create a new business network using `yo hyperledger-composer:businessnetwork`

The tutorial then has the user update the generated `org.acme.biznet.cto` file and `logic.js` file and then they have to separately create the `permissions.acl` file and add some specified content to it. 

Given that the default permission is to deny access to everyone, I think it would be helpful if the generator automatically generated this file for the user, perhaps with the content specified in the tutorial (although ask the architects/designers what rules should be added as default).

I think it would also be helpful for the generator to auto-generate the queries.qry file as this minimises the risk of them getting the filename wrong and hence be unable to access their queries.

If there is agreement that this is to be done then the relevant `create the file...` steps would need to be removed from the developer tutorial too.

**Comment by sstone1** [comment]
Rolling into #3385.
