### ISSUE TITLE
CLI does not help get correct file extension for business network cards

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#3183]
Related to #2656

The CLI commands `composer card create` and `composer card export` output a business network card archive file with exactly the name specified as parameters to those commands. The user needs to know that `.card` is the appropriate extension. 

Would it be useful to have the `.card` extension automatically added if the supplied file name does not already end with this extension? Or is that just confusing for the user?

**Comment by winslet** [comment]
@bestbeforetoday this seems like the right thing to do. It seems it would likely be more confusing to end up with a file without an extension than with 👍
