### ISSUE TITLE
CLI command output not consistent with typical *nix commands

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#3184]
Output of CLI commands is unlike typical CLI commands, and is not suitable for use in scripting. For example, I might want to delete all cards by doing:
```bash
composer card list | while read cardName; do composer card delete --name "${cardName}"; done
```
The current output is too verbose / pretty to be used in this manner.

Possible options include:
1. Change the default command output to be more terse and scripting-friendly, and (optionally) add something like a `--verbose` option to provide pretty output we have today.
1. Retain the current pretty output as default and add something like a `--quiet` option to switch to terse (scripting-friendly) output.

**Comment by sstone1** [comment]
`composer card list` has a new `-q` option for exactly this purpose. If we want to roll it out across other commands, then great, but please open more specific issues for doing that work.
