### ISSUE TITLE
Prbl with link between rest-server and composer 

### ISSUE THREAD

**Issue by TBigjohn** [hyperledger/composer#3204]
Hello,
I followed the procedure described in this very good video (https://www.youtube.com/watch?v=fdFUsrsv5iw&t=2220s) to create a rest api for my test application. I have been able to generate the rest api and use the post method to create a new asset but my issue is that the web interface of the composer is not showing the new asset in the registry even if the rest api is saying that the creation is successful .... For what I understand I am connected at both places with the same admin user. Could somebody help ? It's at the end of the video around 42:00. Thanks

**Comment by mahoney1** [comment]
will answer this on Rocketchat thread https://chat.hyperledger.org/channel/composer?msg=n6QRPCoJ3tkmbpZsz - the problem is likely that the skeleton app (Angular) does not show the asset without manually refreshing the browser.
