### ISSUE TITLE
Attachement support 

### ISSUE THREAD

**Issue by TBigjohn** [hyperledger/composer#3206]
Is it possible to add a field in an asset to receive an attachment ( picture, pdf, ... ) ?
I would be interested be any information about all limitation/possibility concerning type of data, size of fields etc ...
What's the technology used for the "World State" db ?

Thanks 
Thierry

**Comment by davidkel** [comment]
Info about attachments
https://stackoverflow.com/questions/44137679/how-composer-can-handle-attachments-in-assets-and-or-transactions
you can also search stackoverflow for questions about pdfs.
However there is no specific support currently for handling attachments. There maybe something in future versions of composer.

World state DB is controlled by hyperledger fabric and currently supports 2 options. LevelDB and CouchDB.
