### ISSUE TITLE
Stable docs still refer to the 1-line installer

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#3207]
see https://hyperledger.github.io/composer/installing/installing-index.html

We should remove the section `Installing playground locally` to match what is done in the next/master documentation.

**Comment by lesleyannjordan** [comment]
@davidkel is this still an issue - can only see 'Installing playgrond only' etc

**Comment by davidkel** [comment]
@lesleyannjordan It's still there but not something I think we need to spend any time over, so closing
