### ISSUE TITLE
Error messages in Parser Exceptions are not consistent

### ISSUE THREAD

**Issue by m-g-k** [hyperledger/composer#321]
In an IllegalModelExceptions, the message contains the Line and Column info at the beginning of the string. In ParserExceptions the message contains the Line and Column info at the end. Firstly these should be consistent and I think having Line/Col info at the end of the message makes most sense. Secondly it would be nice to be able to get a message without any Line/Col info at all. This would be useful for editor usage such as the VSCode plugin where the Line/Col info is visually present in the editor itself anyway and so having it in the message duplicates this information.  The attached pic shows an example of an IllesageModelException with duplicated info.

![illegalmodelexception](https://cloud.githubusercontent.com/assets/11261488/23511707/f8a12c38-ff55-11e6-85bf-8a80c11f82ed.png)

**Comment by 14gracel** [comment]
@m-g-k Would it be enough to give you access to a `getShortMessage()` method on `IllegalModelException` that returns an error message without the location information?

**Comment by m-g-k** [comment]
Hi @14gracel no, that would be a hack :-). The point here is that there needs to be consistency between the exceptions thrown. I noticed this with the IllegalModelException but there may well be other exceptions that did the same - so all exceptions should put the Line/Column info in the same place (e.g. at the end which makes most sense to me). Having said that, if there was a "getShortMessage()" method on the base exception class that worked with all exception types that may well work, but does not remove the need for consistency between the exceptions themselves (so both would be the best solution ideally).

**Comment by 14gracel** [comment]
Solved in #1338
