### ISSUE TITLE
As a user of the Composer File System card store I can specify a configuration of the file system card store.

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#3212]
- Allow the FileSystem card store to be at a location of the users choice on disk
- Include both the Composer Card Store and the KeyVal store for the Fabric Client

WOW - features such as card store location should be outside code, and also for tools such as the Rest Server, etc.
WOW - makes cloud deployments simpler

Parent is #3121

**Comment by mataide** [comment]
it already is possible?
