### ISSUE TITLE
Missing link to external source in the docs and typo in the pre-requisites page

### ISSUE THREAD

**Issue by rohitadivi** [hyperledger/composer#3222]
On [Installing the development environment page](https://hyperledger.github.io/composer/next/installing/development-tools.html) in the docs the link to the landing page which mentions further details is missing in the note under controlling your dev environment section.

![details](https://user-images.githubusercontent.com/29281964/35350818-11d5ad8c-010d-11e8-8ee7-ca95a70df600.JPG)

I think this could be the missing link: https://ibm-blockchain.github.io/

-----------------------------------------------------------------------------------------------------------------  

The next issue I would like to bring to your notice is a typo in the [pre-requisites page](https://hyperledger.github.io/composer/next/installing/installing-prereqs.html): In the instructions for Mac OS under install Docker section it says "Install Docker for Max" it needs to be changed to Mac
![mac](https://user-images.githubusercontent.com/29281964/35351091-e32f0dc4-010d-11e8-9277-e0d61754d9da.JPG)

-----------------------------------------------------------------------------------------------------------------

On [Developer tutorial page](https://hyperledger.github.io/composer/next/tutorials/developer-tutorial.html) in step four of developer tutorial i.e. deploying business network it would be good if it is mentioned that the network should be up and running.

-----------------------------------------------------------------------------------------------------------------

Definition for runtime is missing in the developer tutorial so including a description of runtime would help first time users of composer understand how runtime environment works.

**Comment by rohitadivi** [comment]
I can't seem to add a label but I think the label should be Docs and tutorial

**Comment by davidkel** [comment]
Changes have been made. Thanks for highlighting the problems.
