### ISSUE TITLE
Providing a network card definition in the developer tutorial would be helpful

### ISSUE THREAD

**Issue by rohitadivi** [hyperledger/composer#3226]
On [Developer tutorial page](https://hyperledger.github.io/composer/next/tutorials/developer-tutorial.html) in step four of developer tutorial i.e. deploying business network it would be good to provide network card definition also it would be helpful to explain if it is only the admin who can use this card? or if a normal user can also create a network card?

**Comment by davidkel** [comment]
So I think what you want is a better description of the PeerAdmin card that is used for deploy and the resulting admin card file that get's created and then needs to be subsequently imported.
