### ISSUE TITLE
Defining ACL (Access Control Language) in the developer tutorial would be helpful for first time composer users

### ISSUE THREAD

**Issue by rohitadivi** [hyperledger/composer#3227]
1. As a new composer user it would be helpful if a definition for ACL is included as brief description or providing a link to ACL definition in the [developer tutorial page](https://hyperledger.github.io/composer/next/tutorials/developer-tutorial.html) rather than mentioning in a separate page under references. This will help the users understand the concept of ACL in a better way.

2. The tutorial asks us to create a permissions.acl file but doesn't define the concept of ACL here.

3. The rule mentioned in the ACL sample allows all participants to access all resources. This will not be the case as only the owner of the commodity will be able to sell or trade it.

**Comment by davidkel** [comment]
There is now a whole tutorial dedicated to ACL's at
https://hyperledger.github.io/composer/latest/tutorials/acl-trading
which hopefully addresses the issue here. If there is something missing from this tutorial please could you create a new issue.
