### ISSUE TITLE
Cucumber framework with native Fabric deployment

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#3253]
**As a** business network developer
**I want** to use Cucumber to write unit tests of my business application
**so that** I can write tests using natural language rather than code

Change business network step definitions for new deployment process. Should be just a change to `Composer.deploy()`.

**Comment by samjsmith** [comment]
So Andy and I think this could be about the composer integration tests (which all seem to fail at the moment) so we're going to look at fixing those under this issue

**Comment by bestbeforetoday** [comment]
@samjsmith This story is for the Cucumber framework (used by some sample business network unit tests) in _packages/composer-cucumber-steps_

**Comment by samjsmith** [comment]
This simple change seems to get all the unit tests passing so I'll do this tomorrow

![image](https://user-images.githubusercontent.com/16335033/37310148-f4011500-263a-11e8-9977-723f13ccb39e.png)
