### ISSUE TITLE
Update business network samples for native Fabric deployment

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#3254]
**As a** business network developer
**I want** to have sample business networks with accompanying unit tests using native Fabric deployment model
**so that** I can learn how to use the Composer API to develop my own business network unit tests

Changes needed to business network deployment step in all sample business network unit tests.

Can't be delivered until after Composer version with native Fabric deployment APIs is released.

**Comment by davidkel** [comment]
should also include updating the landregistry sample application at 
https://github.com/hyperledger/composer-sample-applications
