### ISSUE TITLE
Composer Rest Server - Non functional Endpoints

### ISSUE THREAD

**Issue by daveyMedvedev** [hyperledger/composer#3265]
When following the developer tutorial for composer solutions there is a step to generate REST API endpoints using composer-rest-server. When these endpoints are interrogated using POSTMAN or similar API tool, they do not actually do anything. From a tutorial standpoint, it would be nice to have functional endpoints that can be called rather than error out upon CRUD. 

Consider options like:
- Adding a sample endpoint walk through to the tutorial 
- Removing composer-rest-server entirely from tutorial
- Not generating fake endpoints using composer-rest-server

**Comment by davidkel** [comment]
Composer Rest Server doesn't generate Non Functional Endpoints. The end points provide both fixed capabilities of the rest server plus capabilities dependent on your business network you have deployed. It also provides a test. 
However, the tutorial at the point could be better in describing either the end points that are available or pointing you to try the explorer page which allows you to test the end points. 
So this issue should be about improving the tutorial for the rest server.
