### ISSUE TITLE
Using default values in model files results in top Enum being used in Playground

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3273]
If you have a model file that has an asset with a default value, which just so happens to be an Enum, rather than taking the specified default value, Playground will use the tip item in the Enum list as the default value.

## Context
Creating assets in playground that use default values that are from an Enum

## Expected Behavior
The default value is used, not the top one

## Actual Behavior
The top item in the Enum list is used

## Steps to Reproduce
1) Open basic sample network
2) Add to Asset an Enum field, with a default that is not the top enum
3) Open Playground test tab, create asset
4) Witness use of top enum in skeleton Asset

## Your Environment
Hosted 'next' playground, Chrome browser, Mac

**Comment by davidkel** [comment]
@nklincoln is this one fixed ?
