### ISSUE TITLE
Documentation errors and comments

### ISSUE THREAD

**Issue by awjh** [hyperledger/composer#3297]
# List of errors found in the documentation:
- **/managing/id-cards-playground** 
   - "Creating a business network card using from the Wallet" should possibly be Creating a business network card from the wallet? 
   - The section also states the user should select a connection profile. This could lead to confusion as if they may select the Hyperledger Fabric v1.1 option and be taken to a form which is not described within the document but rather in the playground section.
   -  Why are there two sections for creating business network cards? The section "Creating a business network card within a business network" is repeated in */playground/id-cards-playground*'s "Creating a Business Network Card" which contains more detail and an animation. Other areas are duplicated and others split between the two, shouldn't all information be located in the one doc?
      - "Creating a business network card within a business network" is covering the same problem as "Connecting using Credentials" in the playground section.
- **/reference/connectionprofile** - switches between American and English spellings of organisation. Maybe it would be best to stick with the Americanised form to match what is within the connection profile?
- **/playground/id-cards-playground**
   - "a Enrollment ID" -> "an Enrollment ID"
   - Creating a peer admin points you to the page on deploying to a fabric to understand a connection profile but doesn't particularly explain how the form works. May be only worth updating once #3050 goes in due to possible UI change. 
- **business-network/query** 
   - points to API Docs page which only mentions query once. Couldn't find much on the queryAPI from that page.
- **business-network/testing**
   - Link to bond network's testing points to master branch of composer-sample-networks rather than the 0.16.x branch.

**Comment by andrew-coleman** [comment]
- **/business-network/testing** - last link under 'References': `Istambul` should be spelled `Istanbul`

**Comment by samjsmith** [comment]
https://hyperledger.github.io/composer/next-unstable/applications/node "Submitting a transactions"

**Comment by erin-hughes** [comment]
- **/tutorials/deploy-to-fabric-single-org** - references to the Hyperledger Fabric docs throughout but without an actual link
