### ISSUE TITLE
README.md for Yo generated sample business network is overly terse

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#3300]
The entire content of the file is (as of Composer 0.17.3):
```
# org.example.biznet
```
As this is the first thing when you connect to the business network with Playground, just a few words here would improve the user perception.

**Comment by nklincoln** [comment]
@bestbeforetoday - any suggestion on what the words should be?

**Comment by sstone1** [comment]
Rolling into #3385.
