### ISSUE TITLE
Composer connection profile validation

### ISSUE THREAD

**Issue by samjsmith** [hyperledger/composer#3351]
As a composer user, it would be nice if the composer card import command validated my connection profile for me and reported errors that are in there.

**Comment by samjsmith** [comment]
Fixed by https://github.com/hyperledger/composer/pull/3358

**Comment by lesleyannjordan** [comment]
Re-opening to add integration test

**Comment by lesleyannjordan** [comment]
PR #3445 complete - closing this ticket
