### ISSUE TITLE
Several code fields in the multi org tutorial aren't highlighted

### ISSUE THREAD

**Issue by erin-hughes** [hyperledger/composer#3361]
## Context

In step one of the multi org tutorial, the terminal commands aren't highlighted like the commands in the rest of the tutorial.
https://hyperledger.github.io/composer/next-unstable/tutorials/deploy-to-fabric-multi-org

## Expected Behavior
Example of how they should look:
![screen shot 2018-02-08 at 11 24 34](https://user-images.githubusercontent.com/35696678/35970633-f83f970e-0cc2-11e8-93f0-7d0979c84dad.png)

## Actual Behavior

How they actually look:
![screen shot 2018-02-08 at 11 30 09](https://user-images.githubusercontent.com/35696678/35970768-7e908d9a-0cc3-11e8-892e-d9131a414c3a.png)

**Comment by nklincoln** [comment]
fixed by #3364
