### ISSUE TITLE
Playground tutorial test should use tutorial text

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3362]
The protractor tests for the playground tutorial is *nearly* perfect.

To make it two-thumbs-up, it should be using the information (text) from within the actual tutorial documentation to place information into the test itself.

Then we will actually be testing the tutorial, and not what the tutorial should be.

We can achieve this by:
 - Edit the tutorial documentation to indicate text blocks that are to be used in a tutorial
 - Inside the Protractor test for the tutorial, extract the required text block(s) and use where required

**Comment by awjh-ibm** [comment]
Covered again by issue #3784 and acted upon by PR #3859
