### ISSUE TITLE
Remove "composer identity request" and replace with fabric-ca-client CLI

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#3381]
Identity request is now used in the BYFN tutorial and is going to be a required tool when wanting to HSM manage identities. 
It was hoped that fabric would generate platform specific binaries of fabric-ca-client as identity request only exists because at the time this wasn't available and asking people to compile GO code to create it themselves isn't a good option.

Unfortunately fabric still haven't done this, so identity request has to live on.

**Comment by davidkel** [comment]
Looks like fabric-ca-client binary is going to be made available, so we don't have to document this command. Once available we should change where it has been referenced to use the fabric-ca-client instead. Changing the title to reflect this.

**Comment by sstone1** [comment]
This has now been provided via the Fabric v1.1 one line installer; and we should get rid of "composer identity request" as soon as possible.

**Comment by sstone1** [comment]
Updated title to reflect removal of CLI as well.

**Comment by davidkel** [comment]
So wanted to do this, but fabric-ca-client doesn't support either
- hostname override
- disabling tls cert verification
which means in the multi-org tutorial, fabric-ca-client will refuse to work because a request has to be made to localhost, but the cert CN is ca.org1.example.com
