### ISSUE TITLE
async function in logic.js --> Unknown token function error

### ISSUE THREAD

**Issue by rohit-gandhe** [hyperledger/composer#3382]
When I use async function in logic.js as per the example in tutorials, I get an "Unknown token function" error

## Context

I changed the `ecmaVersion` under `parserOptions` in .eslintrc.yml file, which fixed the warning in VSCode, but I still get the error through cli when I try to build the archive.

## Expected Behavior

Archive should build

## Actual Behavior

I get an error

## Steps to Reproduce

1. Go through the tutorial on website

## Your Environment

$ composer --version
v0.16.3
$ node --version
v8.9.4
$ npm --version
5.6.0
$ eslint -v
v3.7.1

**Comment by rohit-gandhe** [comment]
If I remove `async` from the function declaration, I get `The keyword 'let' is reserved` error

**Comment by davidkel** [comment]
In 0.16.3 async and ES6 keywords are not supported in TP functions. You can however use them in the next release currently 0.17.4 and that is documented on https://hyperledger.github.io/composer/next which provides information on this release which I guess you were on the tutorial for this version. You need to use the stable docs at https://hyperledger.github.io/composer to work with 0.16.3
