### ISSUE TITLE
composer card import appears to be broken on version 0.16.4

### ISSUE THREAD

**Issue by alicari** [hyperledger/composer#3407]
Running composer card import breaks with the following error in version 0.16.4.

Error: Failed to load connector module "composer-connector-hlfv1" for connection type "hlfv1". Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier

The expected behavior is for the card to be imported with a success message, and then the card be available in the composer card list.

This does work on 0.16.3 and I can get things working by downgrading my composer-cli npm package.

* Version used: 0.16.4
* Environment name and version: npm 3.10.10; node 6.11.2
* Operating System and version (desktop or mobile): Ubuntu 16.04.3 LTS

**Comment by davidkel** [comment]
Node 8 has been our minimum supported level for a while now, and changes put into 0.16.4 require node 8 now. Node 6 goes into maintenance mode in April and Node 8 is now the new LTS version.

**Comment by alicari** [comment]
ok, thanks. Fabric requires node 6.x and nothing higher is supported. I assumed composer had the same requirements. Is there a listing of perquisites specifically for composer?

http://hyperledger-fabric.readthedocs.io/en/release/prereqs.html#node-js-runtime-and-npm

**Comment by davidkel** [comment]
see
https://hyperledger.github.io/composer/installing/installing-prereqs for composer pre-reqs.
node 6.9 is also very old now even for the 6.x release stream. We have found node 8.9 to be solid and have never encountered any problems with the node-sdk running on this version.
