### ISSUE TITLE
Composer card create should use same validator as composer card import

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3410]
It would appear that there is different validation taking place for card creation and card import.

Both commands should use the same validator

## Context
Created a card, pointing to a known broken/bad connection profile .... no issues. Used the import command to import the generated card and an expected failure occurred. 

## Expected Behavior
I should not be able to create a business network card using a bad/invalid connection profile, especially if it is rejected at a later stage through the same version/level of coding during an import

## Actual Behavior
Can create card using bad profile, cannot use it.

## Possible Fix
Apply same validation mechanisms in create and import.

**Comment by davidkel** [comment]
Composer card create supports both JSON and YAML Connection Profile formats so extra work to perform YAML verification will be required in order for this to still be supported.
