### ISSUE TITLE
System tests for getNativeAPI should include error scenarios

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#3415]
Currently the system tests for the getNativeAPI don't test what happens if invoked chaincode throws an error (eg in a TP function).

**Comment by cammachusa** [comment]
Can I work on this issue?

**Comment by sstone1** [comment]
@cammachusa sure, welcome aboard!

**Comment by jt-nti** [comment]
@cammachusa I couldn't assign it to you (I guess you need to be on https://github.com/orgs/hyperledger/teams/composer-contributors/members for that) so I've assigned it to the build ID instead- hopefully that way it won't look like it's unassigned!

If this is your first contribution, you'll need to accept the Developer Certificate of Origin -> https://github.com/probot/dco#how-it-works

Let me know if you have any questions and thanks for helping!

**Comment by cammachusa** [comment]
Thanks for the response, gent. Yes, it's my first work on composer, it's a great tool so want to contribute.
@jt-nti , the link you provided above, doesn't work. I am contributor with Apache's projects, but still not sure how it works here? Please advise

**Comment by cammachusa** [comment]
@sstone1 & @jt-nti , need your helps. This link: https://github.com/orgs/hyperledger/teams/composer-contributors/members does not work. I just want to contribute something for this tool. Please advise. Thanks

**Comment by jt-nti** [comment]
Hi @cammachusa, I think I've caused a bit of confusion, sorry. You shouldn't need access to that link; I was just speculating why I couldn't assign the issue to you. Instead, I've assigned the issue to the build ID, fabric-composer-app, to show that it's been taken. As long as you've agreed to the DCO and added the appropriate sign offs to your commits, someone will be able to merge any pull requests you submit. The https://chat.hyperledger.org/channel/composer-contributors rocket channel is a good place to go if you have questions about contributing.
Sorry again for causing confusion!

**Comment by cammachusa** [comment]
Got it, and thank you. I am on it now.

**Comment by cammachusa** [comment]
Hi @davidkel , 
I am still new with the tool. So, can you give me more details on the issue? e.g. where can I find system tests? and what do you mean by TP function? Thanks

**Comment by davidkel** [comment]
Hi @cammachusa. The system tests I refer to are the functional tests which can be found in the `packages/composer-tests-functional` directory. TP Functions are Transaction Processor Functions which are part of your business network definition. You will find that the functional tests create business network definitions with TP functions to deploy to a real running fabric in order to test behaviour of the runtime inside a real fabric. 
The TP functions written to test the getNativeAPI can be found in `systest/data/common-network/transactions.js`
