### ISSUE TITLE
aggregating across two registries on the ledger

### ISSUE THREAD

**Issue by aparolini** [hyperledger/composer#3419]
The Query language dosen't work with two aggregated objects

Exemple
```
asset Country identified by name {
  o String name
  o String mainland
}

Participant Person identified by id {
  o String id
  --> Country country 
}
``` 

Don't work:
```
query selecPersonbyMainland {
  description: "Select all person by mainland"
  statement:
      SELECT Person
          WHERE (country.mainland == _$mainlandName)
}
```

**Comment by PhilipeLouchtch** [comment]
Would be a very useful feature, in our project we have worked around this limitation by either keeping the data model more flat with data duplication or doing this in two queries.

The latter case is achieved by doing a query on the Country registry. Then use the URI of the found country asset to query the Person registry.

**Comment by aparolini** [comment]
No answer from devs ?

**Comment by PhilipeLouchtch** [comment]
Seems they're a bit blind on externally supplied issues, and the bot closed it so they're not going to
