### ISSUE TITLE
createPeerAdminCard.sh fails silently when used with an invalid version

### ISSUE THREAD

**Issue by samjsmith** [hyperledger/composer#3426]
So I downloaded the latest fabric tools and started a new network with:
```
curl -O https://raw.githubusercontent.com/hyperledger/composer-tools/master/packages/fabric-dev-servers/fabric-dev-servers.tar.gz
tar -xvf fabric-dev-servers.tar.gz
cd ~/fabric-tools
export FABRIC_VERSION=hlfv11
./startFabric.sh
./createPeerAdminCard.sh
```
However, the createPeerAdminCard.sh script just fails silently and only displays this:
```
$ ./createPeerAdminCard.sh 
Development only script for Hyperledger Fabric control
Running 'createPeerAdminCard.sh'
FABRIC_VERSION is set to 'hlfv11'
FABRIC_START_TIMEOUT is set to '20'
```
The problem is that running `composer -v` showed that I was running v0.16.4 when I was trying to use an hlfv11.  
Note that this was due to my composer command being sym-linked for dev purposes like this 
```
/usr/local/lib/node_modules/composer-cli -> /Users/samsmith/Projects/BlockChain/Composer/fabric-composer/packages/composer-cli
```
And yesterday, I switched into a v.0.16.4 branch to run some tests - what a muppet!

An error message from the script would have been nice though!

**Comment by davidkel** [comment]
Done.
