### ISSUE TITLE
Unnecessary serialisation/deserialisation occurring in loopback connection

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3441]
At present the business network connection is (quite sensibly) geared at only returning objects via the API.

The loopback connector (businessnetworkconnector.js) is geared at only returning JSON structures.

The issue is that using loopback to (for instance) invoke a query, results in:
 - business network side `businessnetworkconnection.query()` performs the query and then creates a resource via `serialiser.fromJSON()`, which is then returned
- loopback side then then takes all the returned resources from the query result and serialises all resources back to JSON via `serializer.toJSON(resource)` which is then returned

Each of these batch serialisation processes take time, which is clearly impacted greatly by the number of objects being processed. 

It would be far more efficient if there was a non-default option (or alternative path) whereby the resources are returned to the loopback connector in a JSON format ready for immediate return and thereby avoiding an unnecessary deserialise->serialise process 

There is of course a potential issue here, with counter arguments too:
 - Removing the fromJSON() will remove an internal validation on the returned resource
 - It is arguable that since the resource has been pulled directly from the registry, then it *should* be in the correct format and so any validation is unnecessary.

Suggestion for the countering of the above, is to only enable the above path if a special 'new' flag is passed with the call to the server rather than it being a default option. This would mean that a user is explicitly requesting any validation checks to be skipped and therefore will have to deal with invalid return items within their application(s)

**Comment by jdockter** [comment]
We use the REST server for a number of entry points into our business network and it would be great if the performance was improved 👍

**Comment by dselman** [comment]
Please do not forget that the model can change... so there may be invalid instances in the registry if the user has made breaking changes to the model. Returning these is risky as they could not be subsequently processed. Server side validation could be optionally disabled however for customers that really knew what they were doing.
