### ISSUE TITLE
Include logs in composer-report archive

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#3442]
One of the issues related to #2096 will be updating composer tracing and logging to store log output in the **~/.composer/logs** directory. Once logs are being collected in a specific location, they should be bundled up in the composer-report archive to help problem determination.

This should be part of the basic diagnostics since it does not require any composer apis, e.g. a new `_collectLogs(tmpDirectory);` function as part of `collectBasicDiagnostics` in _packages/composer-report/lib/report.js_

**Comment by cammachusa** [comment]
Hi @jt-nti , i am also interested in working on this issue. Can you assign it to me?
