### ISSUE TITLE
Remove dependency on browserify

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#3461]
We use browserify which is a hangover from Hyperledger Fabric v1.0 where we had to use it to get the JavaScript code to run inside Duktape. This no longer happens with Hyperledger Fabric v1.1, and we use webpack instead for the playground, so we should get rid of browserify.

It also fails to handle async + await when combined with karma which is what triggered me to do this.

**Comment by mbwhite** [comment]
+1
This is giving me a number of problems getting the new cloud wallet modules integrated
