### ISSUE TITLE
v0.16 bump fabric-client and fabric-ca-client versions in hlf connector

### ISSUE THREAD

**Issue by samjsmith** [hyperledger/composer#3473]
As per the title really. Bump up to v1.0.4 in the composer-connector-hlfv1 package.json to release HSM support update.
Should work with any fabric v1.0

Tag @lesleyannjordan for information.

**Comment by jt-nti** [comment]
Fixed in #3480 (btw. are we expecting a similar fix in the v1.1 fabric SDK?)
