### ISSUE TITLE
Makefile:43: recipe for target 'integration-test' failed make: *** [integration-test] Error 1

### ISSUE THREAD

**Issue by anoopkvenu** [hyperledger/composer#3476]
## While executing make in fabric-sdk-go getting the integration-test failed error.
Running integration tests...
2018-02-24 22:15:42.957 IST [fabric_sdk_go] InitConfigWithCmdRoot -> INFO 001 Using config file: ../fixtures/config/config_test.yaml
2018-02-24 22:15:42.957 IST [fabric_sdk_go] InitConfigWithCmdRoot -> INFO 002 fabric_sdk_go Logging level: info
22:15:42.957 [bccsp_sw] DEBU :  KeyStore path [/tmp/msp/keystore] missing [true]: [<clean>]
22:15:42.957 [bccsp_sw] DEBU :  Creating KeyStore at [/tmp/msp/keystore]...
22:15:42.957 [bccsp_sw] DEBU :  KeyStore created at [/tmp/msp/keystore].
22:15:42.957 [bccsp_sw] DEBU :  KeyStore opened at [/tmp/msp/keystore]...done
22:15:42.957 [bccsp] DEBU :  Initialize BCCSP [SW]
22:15:42.957 [fabric_sdk_go] INFO :  KeyStore path [/tmp/enroll_user] missing [true]: [%!s(<nil>)]
22:15:42.957 [fabric_sdk_go] INFO :  Constructed fabricCAClient instance: &{0xc42026ca80}
22:15:42.958 [bccsp_sw] DEBU :  KeyStore path [/tmp/msp/keystore] missing [true]: [<clean>]
22:15:42.958 [bccsp_sw] DEBU :  Creating KeyStore at [/tmp/msp/keystore]...
22:15:42.958 [bccsp_sw] DEBU :  KeyStore created at [/tmp/msp/keystore].
22:15:42.958 [bccsp_sw] DEBU :  KeyStore opened at [/tmp/msp/keystore]...done
2018/02/24 22:15:42 [INFO] generating key: &{A:ecdsa S:256}
2018/02/24 22:15:42 [INFO] encoded CSR
2018/02/24 22:15:42 [INFO] TLS Enabled
--- FAIL: TestChannelQueries (0.07s)
	channel_queries_test.go:28: Create client failed: Enroll return error: Enroll failed: POST failure [Post https://localhost:7054/enroll: dial tcp 127.0.0.1:7054: connect: connection refused]; not sending
		POST https://localhost:7054/enroll
		Authorization: Basic YWRtaW46YWRtaW5wdw==
		{"hosts":null,"certificate_request":"-----BEGIN CERTIFICATE REQUEST-----\nMIHzMIGbAgEAMBAxDjAMBgNVBAMTBWFkbWluMFkwEwYHKoZIzj0CAQYIKoZIzj0D\nAQcDQgAER3/TXP407YHuQAl6rU2ltLAYPzYCGmOgiLtMJnruBfiMAPghVHdr0qyt\nTKbrXCwNRMjECy+cqKRytLWsdlOcdKApMCcGCSqGSIb3DQEJDjEaMBgwFgYDVR0R\nBA8wDYILYW5pLWRlc2t0b3AwCgYIKoZIzj0EAwIDRwAwRAIgGszMD6Hn31Rsa3++\nw/fOPGbiD7vTaP8ajSa4FBffB3ICICPobkKhr9MZZ9Qyor9dHQDgbFIL26ZjBoDp\nOnITQfan\n-----END CERTIFICATE REQUEST-----\n","profile":"","crl_override":"","label":"","CAName":"ca-org1"}
22:15:43.012 [fabric_sdk_go] INFO :  Using config file: ../fixtures/config/config_test.yaml
22:15:43.012 [fabric_sdk_go] INFO :  fabric_sdk_go Logging level: info
22:15:43.012 [fabric_sdk_go] INFO :  KeyStore path [/tmp/enroll_user] missing [true]: [%!s(<nil>)]
22:15:43.012 [fabric_sdk_go] INFO :  Constructed fabricCAClient instance: &{0xc42026cba0}
22:15:43.012 [bccsp_sw] DEBU :  KeyStore opened at [/tmp/msp/keystore]...done
2018/02/24 22:15:43 [INFO] generating key: &{A:ecdsa S:256}
2018/02/24 22:15:43 [INFO] encoded CSR
2018/02/24 22:15:43 [INFO] TLS Enabled
--- FAIL: TestChainCodeInvoke (0.01s)
	end_to_end_test.go:28: Create client failed: Enroll return error: Enroll failed: POST failure [Post https://localhost:7054/enroll: dial tcp 127.0.0.1:7054: connect: connection refused]; not sending
		POST https://localhost:7054/enroll
		Authorization: Basic YWRtaW46YWRtaW5wdw==
		{"hosts":null,"certificate_request":"-----BEGIN CERTIFICATE REQUEST-----\nMIH0MIGbAgEAMBAxDjAMBgNVBAMTBWFkbWluMFkwEwYHKoZIzj0CAQYIKoZIzj0D\nAQcDQgAEsn0rRUxOSnsLz9q2CGrDl0VngqB/kgsKlq7Dal+96Lro/MZk0o2xwBNb\n1K8R8DRLh4+nTrZRqrX8QVASucXXsqApMCcGCSqGSIb3DQEJDjEaMBgwFgYDVR0R\nBA8wDYILYW5pLWRlc2t0b3AwCgYIKoZIzj0EAwIDSAAwRQIhAJp4Cd4R1c0FiVqn\nNBE/7s46AkVDKRod1pXzWb59wvOSAiBLBLx/Jt1jYc79d1tE4XjXybNKTkkVSTCj\nK86E9ONwuw==\n-----END CERTIFICATE REQUEST-----\n","profile":"","crl_override":"","label":"","CAName":"ca-org1"}
22:15:43.022 [fabric_sdk_go] INFO :  Using config file: ../fixtures/config/config_test.yaml
22:15:43.022 [fabric_sdk_go] INFO :  fabric_sdk_go Logging level: info
22:15:43.022 [fabric_sdk_go] INFO :  KeyStore path [/tmp/enroll_user] missing [true]: [%!s(<nil>)]
22:15:43.022 [fabric_sdk_go] INFO :  Constructed fabricCAClient instance: &{0xc42026cb40}
22:15:43.022 [bccsp_sw] DEBU :  KeyStore opened at [/tmp/msp/keystore]...done
2018/02/24 22:15:43 [INFO] generating key: &{A:ecdsa S:256}
2018/02/24 22:15:43 [INFO] encoded CSR
2018/02/24 22:15:43 [INFO] TLS Enabled
--- FAIL: TestEvents (0.02s)
	events_test.go:45: Create client failed: Enroll return error: Enroll failed: POST failure [Post https://localhost:7054/enroll: dial tcp 127.0.0.1:7054: connect: connection refused]; not sending
		POST https://localhost:7054/enroll
		Authorization: Basic YWRtaW46YWRtaW5wdw==
		{"hosts":null,"certificate_request":"-----BEGIN CERTIFICATE REQUEST-----\nMIHzMIGbAgEAMBAxDjAMBgNVBAMTBWFkbWluMFkwEwYHKoZIzj0CAQYIKoZIzj0D\nAQcDQgAEcTHxaEB3LY5I+9i66oM5hJih7RlF6hfoSFIUvFXxM/jh9G03qGoXJkwh\nK90ujKswBvsuI80KRkM5lcCR6PWbq6ApMCcGCSqGSIb3DQEJDjEaMBgwFgYDVR0R\nBA8wDYILYW5pLWRlc2t0b3AwCgYIKoZIzj0EAwIDRwAwRAIgUQfv5BvolzzbELnw\nCYsno+ZVbIMPIhxfMAGkV1BAETwCICuEs+jidjZR1DbaI/Oc/L4zATUQY+V4O64l\nSoVdQSmb\n-----END CERTIFICATE REQUEST-----\n","profile":"","crl_override":"","label":"","CAName":"ca-org1"}
22:15:43.039 [fabric_sdk_go] INFO :  Using config file: ../fixtures/config/config_test.yaml
22:15:43.039 [fabric_sdk_go] INFO :  fabric_sdk_go Logging level: info
22:15:43.039 [fabric_sdk_go] INFO :  KeyStore path [/tmp/enroll_user] missing [true]: [%!s(<nil>)]
22:15:43.039 [fabric_sdk_go] INFO :  Constructed fabricCAClient instance: &{0xc42026cba0}
22:15:43.039 [bccsp_sw] DEBU :  KeyStore opened at [/tmp/msp/keystore]...done
2018/02/24 22:15:43 [INFO] generating key: &{A:ecdsa S:256}
2018/02/24 22:15:43 [INFO] encoded CSR
2018/02/24 22:15:43 [INFO] TLS Enabled
--- FAIL: TestRegisterEnrollRevoke (0.01s)
	fabric_ca_test.go:71: Enroll return error: Enroll failed: POST failure [Post https://localhost:7054/enroll: dial tcp 127.0.0.1:7054: connect: connection refused]; not sending
		POST https://localhost:7054/enroll
		Authorization: Basic YWRtaW46YWRtaW5wdw==
		{"hosts":null,"certificate_request":"-----BEGIN CERTIFICATE REQUEST-----\nMIH0MIGbAgEAMBAxDjAMBgNVBAMTBWFkbWluMFkwEwYHKoZIzj0CAQYIKoZIzj0D\nAQcDQgAET3nxqcsERFL45SMyIr85V5QKb2x/ksLQ/yU4X2iijPRJKjRiYY8zY1Lk\n2ojSezqonlvLiCvtcmQ79x/FMI1v5aApMCcGCSqGSIb3DQEJDjEaMBgwFgYDVR0R\nBA8wDYILYW5pLWRlc2t0b3AwCgYIKoZIzj0EAwIDSAAwRQIhAP54+PPS8QA/wWzF\nQ4nis6wU1vZo0EVA8CdKA0euXdqsAiA+q0caqK1ustrya8iL0UFKQlTne/4woZ7x\n454Scnaztw==\n-----END CERTIFICATE REQUEST-----\n","profile":"","crl_override":"","label":"","CAName":"ca-org1"}
22:15:43.050 [fabric_sdk_go] INFO :  Using config file: ../fixtures/config/config_test.yaml
22:15:43.050 [fabric_sdk_go] INFO :  fabric_sdk_go Logging level: info
22:15:43.050 [fabric_sdk_go] INFO :  KeyStore path [/tmp/enroll_user] missing [true]: [%!s(<nil>)]
22:15:43.050 [fabric_sdk_go] INFO :  Constructed fabricCAClient instance: &{0xc42026cb40}
22:15:43.050 [bccsp_sw] DEBU :  KeyStore opened at [/tmp/msp/keystore]...done
2018/02/24 22:15:43 [INFO] generating key: &{A:ecdsa S:256}
2018/02/24 22:15:43 [INFO] encoded CSR
2018/02/24 22:15:43 [INFO] TLS Enabled
--- FAIL: TestChaincodeInstal (0.01s)
	install_chaincode_test.go:36: Create client failed: Enroll return error: Enroll failed: POST failure [Post https://localhost:7054/enroll: dial tcp 127.0.0.1:7054: connect: connection refused]; not sending
		POST https://localhost:7054/enroll
		Authorization: Basic YWRtaW46YWRtaW5wdw==
		{"hosts":null,"certificate_request":"-----BEGIN CERTIFICATE REQUEST-----\nMIH0MIGbAgEAMBAxDjAMBgNVBAMTBWFkbWluMFkwEwYHKoZIzj0CAQYIKoZIzj0D\nAQcDQgAEi4aczkGEG82ZaWbxIhIF+XaNsrpviVOTqbiD6s559uY3y4ezxqtWfe3g\nJWPFDB1owdhpnDrtJj7usm7u/OsUkaApMCcGCSqGSIb3DQEJDjEaMBgwFgYDVR0R\nBA8wDYILYW5pLWRlc2t0b3AwCgYIKoZIzj0EAwIDSAAwRQIhALyPqXkgSk/vc2JS\nnzvpUQox9hp8kVZsyJ7JsnzUe07tAiBfD70/9XgigVCM3oqWc1HzMRv4lndDLIjU\nANBnCb/WRA==\n-----END CERTIFICATE REQUEST-----\n","profile":"","crl_override":"","label":"","CAName":"ca-org1"}
22:15:43.062 [fabric_sdk_go] INFO :  Using config file: ../fixtures/config/config_test.yaml
22:15:43.062 [fabric_sdk_go] INFO :  fabric_sdk_go Logging level: info
22:15:43.062 [fabric_sdk_go] INFO :  KeyStore path [/tmp/enroll_user] missing [true]: [%!s(<nil>)]
22:15:43.062 [fabric_sdk_go] INFO :  Constructed fabricCAClient instance: &{0xc42026cba0}
22:15:43.062 [bccsp_sw] DEBU :  KeyStore opened at [/tmp/msp/keystore]...done
2018/02/24 22:15:43 [INFO] generating key: &{A:ecdsa S:256}
2018/02/24 22:15:43 [INFO] encoded CSR
2018/02/24 22:15:43 [INFO] TLS Enabled
--- FAIL: TestTransient (0.01s)
	transient_data_test.go:27: Create client failed: Enroll return error: Enroll failed: POST failure [Post https://localhost:7054/enroll: dial tcp 127.0.0.1:7054: connect: connection refused]; not sending
		POST https://localhost:7054/enroll
		Authorization: Basic YWRtaW46YWRtaW5wdw==
		{"hosts":null,"certificate_request":"-----BEGIN CERTIFICATE REQUEST-----\nMIH0MIGbAgEAMBAxDjAMBgNVBAMTBWFkbWluMFkwEwYHKoZIzj0CAQYIKoZIzj0D\nAQcDQgAEEQf6q24jva331y+HNePopEWa0oY0NNt7nOlAS0J/g12aLzkyHxhlK+qm\nOzFjkhOzaHHFEARxVwhmeObAEGRsa6ApMCcGCSqGSIb3DQEJDjEaMBgwFgYDVR0R\nBA8wDYILYW5pLWRlc2t0b3AwCgYIKoZIzj0EAwIDSAAwRQIhAPDLViDFykL28xxw\n7WNuhE/XvewiBBy/pIBY2o4ubUXkAiBv21hW9Th3N2oT+FmPtn+uiRV4z2culQTx\nWdGOO7YGTA==\n-----END CERTIFICATE REQUEST-----\n","profile":"","crl_override":"","label":"","CAName":"ca-org1"}
FAIL
coverage: 8.1% of statements
FAIL	github.com/hyperledger/fabric-sdk-go/test/integration	0.145s
error: exit status 1
panic: EOF

goroutine 1 [running]:
main.main()
	/home/ani/go/src/github.com/AlekSi/gocov-xml/gocov-xml.go:60 +0x12c8
Integration tests failed. Cleaning up...
Stopping peer0.org2.example.com ... done
Stopping peer0.org1.example.com ... done
Removing peer0.org2.example.com ... done
Removing peer0.org1.example.com ... done
Removing orderer.example.com    ... done
Removing fixtures_builder_1     ... done
Removing ca_peerOrg2            ... done
Removing ca_peerOrg1            ... done
Removing network fixtures_default
Makefile:43: recipe for target 'integration-test' failed
make: *** [integration-test] Error 1

**Comment by anoopkvenu** [comment]
You should check the following golint suggestions:
test/integration/base_test_setup.go:129:2: redundant if ...; err != nil check, just return error instead.
end golint suggestions

**Comment by nklincoln** [comment]
@anoopkvenu 

I believe that you have raised this issue in the wrong repository - the above is a failure in the Hyperledger Fabric SDK code base tests - I believe that you will need to raise a jira in the fabric-sdk-go repository (https://github.com/hyperledger/fabric-sdk-go)
