### ISSUE TITLE
Error during ./createPeerAdminCard.sh command

### ISSUE THREAD

**Issue by BardoBravo** [hyperledger/composer#3477]
When executing the command informed in the title, I always get an error that the file /home/<userhname>/.nvm/versions/node/v8.9.4/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64/grpc_node.node could not be found.

## Context
I have followed all the instructions informed guide https://hyperledger.github.io/composer/installing/development-tools

## Your Environment

Virtual Machine for Linux

**Comment by cammachusa** [comment]
I can work on this issue, can someone assign it to me?

**Comment by BardoBravo** [comment]
Hello,
I just created a whole new VM and installed everything from scratch, then it worked.
Hugs
