### ISSUE TITLE
createPeerAdminCard.sh leads to syntaxError

### ISSUE THREAD

**Issue by CoverYourII** [hyperledger/composer#3479]
## Context

I was following this wiki: https://hyperledger.github.io/composer/installing/development-tools.html

When I ran "sudo ./createPeerAdminCard.sh", I got the following error message:

Development only script for Hyperledger Fabric control
Running 'createPeerAdminCard.sh'
FABRIC_VERSION is unset, assuming hlfv1
FABRIC_START_TIMEOUT is unset, assuming 15 (seconds)

Using composer-cli at v0.16.4
/usr/local/lib/node_modules/composer-cli/node_modules/composer-common/lib/modelmanager.js:418
    getAssetDeclarations(includeSystemType = true) {
                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/composer-cli/node_modules/composer-common/lib/businessnetworkdefinition.js:28:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
/usr/local/lib/node_modules/composer-cli/node_modules/composer-common/lib/modelmanager.js:418
    getAssetDeclarations(includeSystemType = true) {
                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/composer-cli/node_modules/composer-common/lib/businessnetworkdefinition.js:28:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

## Expected Behavior

After running "composer-playground" and bring up the local web app, I should be able to see PeerAdmin@hlfv1 card

## Actual Behavior

No card were there in my web app.

Following is from the above wiki:
You should see the PeerAdmin@hlfv1 Card you created with the createPeerAdminCard script on your "My Business Networks" screen in the web app: if you don't see this, you may not have correctly started up your runtime!

## Existing issues

- [GitHub Issues](https://github.com/hyperledger/composer/issues/3186)

## Your Environment

I'm using:

Ubuntu 16.04
Node v8.9.4
nodejs v4.2.6
composer-cli v0.16.4
npm 5.6.0

**Comment by CoverYourII** [comment]
I manually update the node version from 8.9.4 to 9.6.0, and now I got a different message:

Development only script for Hyperledger Fabric control
Running 'createPeerAdminCard.sh'
FABRIC_VERSION is unset, assuming hlfv1
FABRIC_START_TIMEOUT is unset, assuming 15 (seconds)

Using composer-cli at v0.16.4

Successfully created business network card file to 
	Output file: /tmp/PeerAdmin@hlfv1.card

Command succeeded

Error: Failed to load connector module "composer-connector-hlfv1" for connection type "hlfv1". Cannot find module '/usr/local/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node'-Cannot find module '/usr/local/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node'-Cannot find module '/usr/local/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node'-Cannot find module '/usr/local/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node'-Cannot find module '/usr/local/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node'-Cannot find module '/usr/local/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node'-Cannot find module '/usr/local/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node'-Cannot find module '/usr/local/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node'-Cannot find module '/usr/local/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node'-Cannot find module '/usr/local/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node'-Cannot find module '/usr/local/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node'
Command failed

**Comment by CoverYourII** [comment]
Quote from solution in this post: https://github.com/hyperledger/composer/issues/1531 by @abrinckm

Make sure you're root and navigate to wherever you have composer-cli installed (mine was /usr/lib/node_modules/composer-cli/) and run this command:

npm rebuild --unsafe-perm

For some reason, certain modules including pcsk11 and node-gyp needed rebuilt. The --unsafe-perm option was needed because I couldn't build as a root.

**Comment by jt-nti** [comment]
@CoverYourII I would strongly recommend not install Composer, or any node modules, as root or using sudo. If you are interested how things should look without using root, I have a Vagrant environment which has Composer installed the right way 👉 https://github.com/jt-nti/composer-devenv

**Comment by CoverYourII** [comment]
Thanks for the info jt-nti, I have two questions related to your reply.

1. I'm trying to follow the IBM hyperledger tutorial, if I switch to Vagrant, will things still work for me? Or is there any equivalent tutorial I can refer to use Vagrant set up my Hyperledger environment?

2. Do you care to elaborate why I shouldn't be using root / sudo to build composer?

**Comment by jt-nti** [comment]
@CoverYourII

> I'm trying to follow the IBM hyperledger tutorial, if I switch to Vagrant, will things still work for me? Or is there any equivalent tutorial I can refer to use Vagrant set up my Hyperledger environment?

You should be able to follow any of the Composer tutorials using a VM set up with Vagrant. The advantage is that you won't need to manually set up your environment by following the [Installing the development environment](https://hyperledger.github.io/composer/installing/development-tools) topic. Vagrant should make it easier to set up repeatable and disposable environments to try out Composer.

> Do you care to elaborate why I shouldn't be using root / sudo to build composer?

Installing node and node modules as root typically leads to permissions errors. The recommended approaches to solving these are documented on the npmjs site: [How to Prevent Permissions Errors](https://docs.npmjs.com/getting-started/fixing-npm-permissions)

The Composer [Installing pre-requisites](https://hyperledger.github.io/composer/installing/installing-prereqs.html) topic also advises not to install as root.
