### ISSUE TITLE
Customize Fabric components

### ISSUE THREAD

**Issue by PPCM** [hyperledger/composer#3485]
Actually, all my production goes with "example.com" lables in Fabric (CA, ledgers, ...).
It could be a real professionnal step, if all labels in Fabric could be replaced by customized labels without to rebuild new dockers
Perhaps with some variables? But you surely think about the best way to do that...

**Comment by sstone1** [comment]
@PPCM Composer includes a sample Fabric configuration for getting started and development purposes only; it is not meant to be customized for production usage. Please consult the Fabric documentation for building Fabric networks - Composer will deploy to any Fabric network.
