### ISSUE TITLE
Incorrect styling of code in the modelling language docs

### ISSUE THREAD

**Issue by erin-hughes** [hyperledger/composer#3491]
Found the issue here: https://hyperledger.github.io/composer//reference/cto_language

There's a section of example code in the docs for the modelling language that isn't contained in a code block and looks the same as the normal body text.

![screen shot 2018-02-27 at 11 31 48](https://user-images.githubusercontent.com/35696678/36741917-450ab710-1bde-11e8-8337-edc691f50e13.png)

**Comment by davidkel** [comment]
This appears to be fixed, so closing
