### ISSUE TITLE
Composer Network Deploy - Docs Inconsistent

### ISSUE THREAD

**Issue by rthatcher** [hyperledger/composer#3494]
The **Latest** and **Next** docs differ for the `composer network deploy` command under the CLI Reference.

In [Latest](https://hyperledger.github.io/composer/reference/commands) there is a nice warning about it.

In [Next](https://hyperledger.github.io/composer/next/reference/commands) it is not present.

The same warning should also be carried through to the actual docs for the command:
[Latest](https://hyperledger.github.io/composer/reference/composer.network.deploy.html)
[Next](https://hyperledger.github.io/composer/next/reference/composer.network.deploy.html)

**Comment by lesleyannjordan** [comment]
Changes applied to both latest (0.16.x branch) and next (0.17.x branch)
