### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by ikashif** [hyperledger/composer#3501]
While navigating to start lab from https://developer.ibm.com/courses/all/ibm-blockchain-foundation-developer/?course=begin#12006. It says "there is no blockchain here."

## Context
I was moving between lab1, lab2 and lab3. It wasn't a bookmark thing.

Missing resource:  
https://hyperledger.github.io/composer/tutorials/developer-tutorial.html
## Context

Trying to develop a use-case. I have some notes but it would be good if would have all resources which helped me while learning hyperledger fabric.

**Comment by jt-nti** [comment]
Looks like a wider problem than just the tutorial. There's more info in #3505 so I'll close this issue, but try https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial.html for the tutorial.

**Comment by ikashif** [comment]
Thank you for this new link.
