### ISSUE TITLE
Page Not Found: Deploying Business Networks

### ISSUE THREAD

**Issue by tom-jacobs** [hyperledger/composer#3504]
The link in the Hyperledger homepage for Deploying Business Networks is broken

## Context
From the Hyperledger Composer main menu on the left side of the screen, I try to go to Developing Business Networks -> Deploying Business Networks and the link does not work

## Expected Behavior
https://hyperledger.github.io/composer/business-network/bnd-deploy should lead to a page

## Actual Behavior
It leads to a Page Not Found

## Steps to Reproduce
1. Vist https://hyperledger.github.io/composer/latest/tutorials/tutorials.html
2. On the menu in the left hand side, click Developing Business Networks drop down menu
3. Select Deploying Business Networks

OR
1. Try to follow this link: https://hyperledger.github.io/composer/business-network/bnd-deploy

**Comment by mbwhite** [comment]
This page has moved to 
https://hyperledger.github.io/composer/latest/business-network/bnd-deploy

The latest had to be added to help distinguish the between v0.16 and v0.17 releases.

latest => v0.16.x
next => v0.17.x

**Comment by jt-nti** [comment]
Should be fixed now via #3505
