### ISSUE TITLE
Lots of broken documentation links?

### ISSUE THREAD

**Issue by benjy** [hyperledger/composer#3505]
There are lots of broken documentation links in Google, it looks like a recent change added the version after the composer part of the path.

Examples of broken paths.

* https://hyperledger.github.io/composer/business-network/query.html
* https://hyperledger.github.io/composer/integrating/getting-started-rest-api.html
* https://hyperledger.github.io/composer/reference/acl_language
* https://hyperledger.github.io/composer/business-network/programmatic-access-control
* https://hyperledger.github.io/composer/managing/participantsandidentities.html
* https://hyperledger.github.io/composer/reference/cto_language.html

If you change the above URL to /composer/latest/.... then it works as expected.

**Broken Search**

Search on the docs is also impacted, go to `https://hyperledger.github.io/composer/latest/introduction/introduction.html` and search for anything.

You'll land on a URL like: `https://hyperledger.github.io/composer/search/search.html?query=REST` which is a 404.

If you change it in the same way to `https://hyperledger.github.io/composer/latest/search/search.html?query=REST` it will work.

**Comment by benjy** [comment]
Here's the broken link - https://github.com/hyperledger/composer/blob/gh-pages/latest/search/search.html#L80

I can create a PR but i'm not sure if these files are generated somehow?

**Comment by jt-nti** [comment]
For anyone hitting this issue, you should be able to get to the original page by adding `latest/` after `composer/`, for example:

https://hyperledger.github.io/composer/tutorials/developer-tutorial.html

...is now...

https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial.html

(Using `next/` instead of `latest/` takes you to documentation for the very latest, not-quite-so-stable, release instead!)

**Comment by jt-nti** [comment]
@mbwhite given the huge number of potential broken links due to this change, I think it would be worth keeping latest at the top level somehow.

**Comment by benjy** [comment]
I can see that @mbwhite has restored all the pages, not sure if you want to do that long-term? We could setup some redirects for all the existing pages for a few months until Google etc has migrated everything to the new URLs? https://help.github.com/articles/redirects-on-github-pages/

**Comment by mbwhite** [comment]
@jt-nti I've restored the pages from latest to the root as well - leaving the 404 and index as they where.
Those pages have the latest `links` in them.

@benjy that is very useful article and could well be long term solution. Didn't know that was possible.
Thank you for assistance!
