### ISSUE TITLE
Cloud Wallet NitPicks

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#3509]
- [x] Redis wallet move to composer-tools  (awaiting travis and npm to play nice)
- [ ] IBM COS wallet move to IBM Blockchain repo  (awaiting repo creation)
- [x] Improve error messages for mis-configuration, eg missing }   #3518 
- [ ] Fix issue with regards to card delete (new issue needed - not the same as playground)
- [x] Fix playground issue re delete #3507 DONE

**Comment by mbwhite** [comment]
## Scenarios to cover with error messages

- Supplied module for the wallet can not be found
- Supplied module does not have the correct entry point
- Configuration that is supplied is not parseable

**Comment by samjsmith** [comment]
What is an S3 compatible API? Is that a good thing - do you have a link (in the doc pls) to something that explains it?

**Comment by jt-nti** [comment]
Typo in step 2 of https://github.com/hyperledger/composer-tools/blob/master/packages/composer-wallet-redis/README.md

```
npm install -g composer-waller-redis
```

Should be composer-wallet-redis

**Comment by samjsmith** [comment]
https://github.com/ampretia/composer-wallet-ibmcos
Not sure that this makes much sense `Would suggest to under the 'Select Service ID' automatically create a service`
Also I think you have to create a credential first so we should doc this step
I'm also wondering why I'd want to use AWS

**Comment by jt-nti** [comment]
References to `@ampretia/composer-wallet-redis` in https://hyperledger.github.io/composer/next-unstable//business-network/cloud-wallets and https://github.com/hyperledger/composer-tools/blob/master/packages/composer-wallet-redis/README.md

**Comment by jt-nti** [comment]
The default.json example on https://hyperledger.github.io/composer/next-unstable//business-network/cloud-wallets is broken (missing closing quote for desc):

```
{
  "composer": {
    "wallet": {
      "type": "@ampretia/composer-wallet-redis",
      "desc": "Uses a local redis instance,
      "options": {

      }
    }
  }
}
```

**Comment by jt-nti** [comment]
It might be nice to document using the `NODE_CONFIG_DIR` environment variable- I don't think the documentation really describes where the configuration files should go, and the composer-wallet-redis readme vaguely mentions the, "current working directory of the application" which could easily result in different wallets for the CLI, Playground, REST server etc.

It would be even nicer if Composer could default to picking up configuration from _~/.composer/config_ instead of the current working directory

**Comment by mbwhite** [comment]
@jt-nti @samjsmith   thanks for the comments and observations. Docs changes yes, and the config changes we should be able to sort out.

**Comment by Rmannn** [comment]
I wrote a module to work with AWS S3 for users that do not have ibm account
https://github.com/Pop-Code/composer-wallet-s3

**Comment by mbwhite** [comment]
Comments on the config have been moved into issue #3211 
otherwise closing this
