### ISSUE TITLE
generator-hyperledger-composer@0.17.6 has syntax error in namespace.cto

### ISSUE THREAD

**Issue by sebastianst** [hyperledger/composer#3514]
Running `composer archive create` returns the following `ParseException`:
```
$ composer archive create --sourceType dir --sourceName .
Creating Business Network Archive


Looking for package.json of Business Network Definition
	Input directory: /foo/network
ParseException: Expected comment, end of line, identifier or whitespace but "<" found. File /foo/network/node_modules/generator-hyperledger-composer/generators/businessnetwork/templates/models/namespace.cto line 5 column 11
Command failed
```
The error doesn't relate to the specific network definition, but rather to a syntax error in `generator-hyperledger-composer`. I'm using the `@next` composer packages, currently `@0.17.6`

## Your Environment
* Version used: 0.17.6
* Environment name and version: node v8.9.4
* Operating System and version (desktop or mobile): Arch Linux

**Comment by nklincoln** [comment]
Hi,

Just to get some more background on this - can you confirm that you were attempting to create an archive file using the CLI commands targeting the template files within a subdirectory of generator-hyperledger-composer?

If not performing the above, could you please give information/step so that we can perform a recreate?

Thanks

**Comment by sstone1** [comment]
@sebastianst works for me, is it possible that you provided an invalid namespace to the generator?

```
$ yo 
? 'Allo Simon! What would you like to do? Hyperledger Composer

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo hyperledger-composer

Welcome to the Hyperledger Composer project generator
? Please select the type of project: Business Network
You can run this generator using: 'yo hyperledger-composer:businessnetwork'
Welcome to the business network generator
? Business network name: my-template-busnet
? Description: My busnet description
? Author name:  MrConga
? Author email: conga@congazone.org
? License: For exclusive conga
? Namespace: test.template.namespace
   create package.json
   create README.md
   create models/test.template.namespace.cto
   create .eslintrc.yml
   create test/logic.js
   create lib/logic.js

     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y `

**Comment by Prskriti** [comment]
@sstone1 

I tried to same steps which you have mentioned but I am getting same parse exception
Can you please help me in resolving this issue?
I am stuck in this exception from past three days.
