### ISSUE TITLE
Throw error if unable to parse the JSON configuration

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#3518]
Failure to parse the JSON configuration by the config module needs to be caught and rethrown. 
Oddly JSON parse errors when this is set by environment variable can't be caught. 
Though in that case it does write to *stderr*.

This is not the perfect fix - I don't see another module that would be better - save for writing our own module!

**Comment by mbwhite** [comment]
Resolved by #3519

**Comment by sstone1** [comment]
PR merged, assuming now fixed 👍
