### ISSUE TITLE
No Angular Generator Tutorial

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3529]
There used to be an angular generator tutorial.

There is no longer an angular generator tutorial.

It would be really good if there was an angular generator tutorial, as it is one of the core components of Composer.

*angular generator tutorial*

**Comment by zachgoll** [comment]
@nklincoln I have been thinking about updating the generator to work with Angular 5 and other updated packages as well as add this to the developer tutorial.  Who should I talk to?

**Comment by winslet** [comment]
Question: We updated the main documentation for the angular tutorial a while ago (see https://hyperledger.github.io/composer/latest/applications/web) do we still feel this is necessary?

**Comment by winslet** [comment]
Answer: We feel the new documentation is sufficient and more scalable as the solution now. Yay!
