### ISSUE TITLE
Unable to import PeerAdmin card to Playground

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3536]
When using the npm spawned playground via `composer-playground` following an npm install, it i not possible to import the peer admin card.

It fails with the error `HLFConnectionManager    :importIdentity()         Failed to import identity. TypeError: this.wallet.put is not a function`

![screen shot 2018-03-06 at 13 30 12](https://user-images.githubusercontent.com/8394544/37034992-fa363560-2142-11e8-8e4c-b99abfd73d32.png)

Identified when trying to import the PeerAdmin card for a running Fabric instance.

**Comment by mbwhite** [comment]
The connector-server was missing the code to choose the correct wallet; thinking about additional tests - this is probably the domain of the playground-runtime fv tests...

**Comment by mbwhite** [comment]
Resolved by #3538
