### ISSUE TITLE
Provide ability to query historian events emitted by custom fields

### ISSUE THREAD

**Issue by DennisM330** [hyperledger/composer#3540]
## Context
Need the ability to query a custom field within the eventsEmitted array in the historian. Currently you can only query on predefined fields such as eventID.

## Expected Behavior
I should be able to query an event in the historian for partNo in the example below.
query selectPartHistory {
  description: "Select Asset based on Part"
  statement:
      SELECT org.hyperledger.composer.system.HistorianRecord
          WHERE (eventsEmitted CONTAINS ( partNo == '12345'))
}

The event definition for the above query is:
event componentAddPartEvent {
  o String eventMessage
   --> ComponentAssembly component
   --> ComponentPart partNo
}

## Actual Behavior
When trying to create a composer archive, you get an error due to it saying the partNo property does not exist.
InvalidQueryException: Invalid WHERE clause in query selectPartHistory: Property partNo does not exist on org.hyperledger.composer.system.Event File 'queries.qry': line 24 column 7, to line 26 column 1. 
Command failed

## Steps to Reproduce
1. Create an event with a custom field in VS Code Studio
2. Create a query that attempts to query on the custom field: SELECT org.hyperledger.composer.system.HistorianRecord
          WHERE (eventsEmitted CONTAINS ( partNo == '12345'))
3. Save the project
4.  composer archive create -t dir -n .

## Existing issues
https://stackoverflow.com/questions/49104387/how-to-access-the-eventemitted-field-in-transaction-history-of-hyperledger-fab
https://chat.hyperledger.org/channel/composer)

## Context
Need to be able to query events in the historian by any custom field to take advantage of composer REST APIs for the historin.

## Your Environment
* Version used: hyperledger composer 0.16.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): VS Code
* Operating System and version (desktop or mobile):Ubuntu 16.04.2 LTS

**Comment by DennisM330** [comment]
Do not mark as stale

**Comment by vilaleix** [comment]
Any news??
