### ISSUE TITLE
Unable to import PeerAdmin card

### ISSUE THREAD

**Issue by magicliang** [hyperledger/composer#3541]
## Context

I have run hyperledger-composer components(including all npm packages, rest-server, playground, etc) serveral months ago, which means there may be some legacy version configuration file existing. But I have purged my $user home directory by deleting everything having "composer" in their names. I uninstalled every npm package and reinstalled them globally. I started from a absolute new "fabric-tools" folder. If my pruning is complete, I hit a new bug of composer.

1.  Tried newest "Installing the development environment" , can't get a correct result of running  "createPeerAdminCard.sh".

2.  Using playground web page to import created Peeradmin card mannually also failed.

## Expected Behavior

It should create then import the Peeradmin card which can be seen in playground web page.

## Actual Behavior

 Console always print:

> Development only script for Hyperledger Fabric control
Running 'createPeerAdminCard.sh'
FABRIC_VERSION is unset, assuming hlfv1
FABRIC_START_TIMEOUT is unset, assuming 15 (seconds)

Using composer-cli at v0.16.5

Successfully created business network card file to
	Output file: /tmp/PeerAdmin@hlfv1.card

Command succeeded

**Error: Failed to load connector module "composer-connector-hlfv1" for connection type "hlfv1". Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier
Command failed**

## Possible Fix

This may relate to this [issue](https://github.com/hyperledger/composer/pull/3538). It keeps complaining about composer-connector issue. I try some debug but no valuable error is print inside catch block of composer-cli script, it is just plain "Unexpected identifier", there must be somewhere a NPE.

## Steps to Reproduce

1. prune the environment.
2. install dependencies.
3. inside the fabric-tools folder:   
    ./startFabric.sh
    ./createPeerAdminCard.sh

## Existing issues

- [ ] [card import using the wrong wallet #3538
](https://github.com/hyperledger/composer/pull/3538)

## Context
I can go through new tutorial.

## Your Environment

* Version used: composer-cli at v0.16.5
* Environment name and version (e.g. Chrome 39, node.js 5.4): node v6.11.3
* Operating System and version (desktop or mobile): MacOS X High Sierra 10.13.3

**Comment by sstone1** [comment]
@magicliang Hyperledger Composer requires Node.js v8.x, you have Node.js v6.x:
https://hyperledger.github.io/composer/latest/installing/installing-prereqs

**Comment by magicliang** [comment]
I think that's the problem. Thanks @sstone1.
