### ISSUE TITLE
New BusCard round trip scenarios required

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3557]
With the inbound changes relating to business network deployment, it will be necessary to modify the existing e2e test that tests the integration with the runtime/fabric/playground.

This is because is will not be possible to use the existing inclusion of an npmrc file in the runtime package

## Required Scenarios

- [ ] Import of card with secret (from CLI to Playground)
- [ ] Import of card with certificates (from CLI to Playground)
- [ ] Export of card with secret (from Playground to CLI)
- [ ] Export of card with certificates (from Playground to CLI)
- [ ] Use non-local card store (redis container?)

## Suggested Test Path

1. Import of card with secret
 - Existing test. Import a created PeerAdmin card for use within Playground

2. Import of card with certificates
 - Pre req for subsequent tests
 - Deploy busnet and create busnet admin card. 
 - Ping BusNet with card to enrol
 - Import card within Playground and log into BusNet with card

3. Export of card with secret
 - Log into busnet with card (as above)
 - Create Participant
 - Bind to identity
 - Export card (do not use!)
 - Import with CLI
 - Ping network with card

4. Export of card with certificates
 - As above but ensure card has been used within Playground prior to export.

**Comment by davidkel** [comment]
@nklincoln I'm going to look at providing a way to npmrc to be set for playground which can then be utilised by the e2e scenario. So hopefully this change will not be required.

**Comment by nklincoln** [comment]
Thanks for the above, the resulting scenarios above are still valid and should be covered within testing ... so would like to keep this issue open so that we can retain confidence in the ways cards can be shared between Playground and Runtime 👍

**Comment by davidkel** [comment]
ok, the point being as that you don't have to extract out the deploying of the business network and set that up using CLI calls. The E2E tests should still be able to do that part.

**Comment by davidkel** [comment]
Closing as I assume we don't need this anymore
