### ISSUE TITLE
Need external libraries in chaincode

### ISSUE THREAD

**Issue by PPCM** [hyperledger/composer#3565]
For my developments, it is easier to import libraries in chaincode instead of writing them into the logic file.

Currently, when I have a complex processing using external libraries, I am not able to use the command `require`, so, I have 2 solutions
* Write a REST server and make a 'External REST Service' call from the chaincode
* Use events with daemon wich catch them
For both solutions, after the processing, I have to make a new transaction with the result
This solutions have a big issue : man in the middle

If it would be possible to import libraries with the command `require` or in an other way, everything will be done in the chaincode without external call.

## Your Environment
* Version used: Composer 0.18.0

**Comment by davidkel** [comment]
There is an Improvement Proposal
https://github.com/hyperledger/composer/issues/3169
for this capability, so closing as this is a duplicate.
