### ISSUE TITLE
Set autocommit to true for EmbeddedDataService

### ISSUE THREAD

**Issue by uluhonolulu** [hyperledger/composer#3567]
The autocommit property of `EmbeddedDataService` should be set by true in the `EmbeddedContext`'s  constructor

## Context
If I test a transaction which causes an asset to be added to a registry, the addition is not done right away, it is scheduled instead. As a result, even after the `add` promise is resolved, the asset is still not in the registry, and some tests fail, despite the code being correct.

## Expected Behavior
If I have this code in my transaction:
```
    voteRegistry.add(vote).then(function() {
      voteRegistry.getAll().then(function(all){ console.log(all); });
    });
```
I expect the console output to display an array with the asset I've just added.

## Actual Behavior
Console output displays an empty array. 

## Possible Fix
composer-runtime-embedded/lib/embeddedcontext.js, line 38 should read:
```
this.dataService = new EmbeddedDataService(engine.getContainer().getUUID(), true);
```

## Context
Although the asset is added to the registry eventually, by the time my test checks its presentce it's not there, so the test fails. 

On the other hand, if the asset is added from the test, it is perfectly visible from the test. This is because in the `EmbeddedConnectionManager`'s constructor, the corresponding line reads:
```
this.dataService = new EmbeddedDataService(null, true);
```

## Your Environment
Composer v0.16.4 on Windows 7.

**Comment by uluhonolulu** [comment]
Correction: turned out my test was failing because of a different problem. Yet I believe it is natural to expect that if you add an asset to a registry, this asset should be there right after the `add` promise resolves.

**Comment by sstone1** [comment]
@uluhonolulu this is working as intended and is matching the behaviour of Hyperledger Fabric; this means that transaction processor functions running in the embedded runtime for unit tests behave the same way that they will when deployed to a real Hyperledger Fabric.

Here's some more information I provided via recent issue #3425:

> ... the behaviour in Composer is exactly the same behaviour that you get in Fabric; a GetState will only read committed state changes, not data written by a previous PutState in the same transaction.

> This was a change that Fabric made in-between v0.6 and v1.0, which we discussed with the Fabric team extensively before Fabric v1.0 was released. We were strongly in favour of being able to "read your own writes" because it makes the programming model much easier to understand, but the Fabric team went with the current behaviour.

> We would not look to introduce this change just into Composer. Composer should reflect the transaction characteristics of the underlying blockchain platform (Fabric). If you want to see this functionality, please raise this as a requirement against Fabric.
