### ISSUE TITLE
Foundation's Developer Course Pre-Req Broken links

### ISSUE THREAD

**Issue by bradleycherrin** [hyperledger/composer#3581]
On module page 4 **Pre-requisites** the **Setting up the Mac** link reference is broken
## Context
On module page 4 of the IBM Blockchain foundation developer Course on DeveloperWorks titled **Pre-requisites** the **Setting up the Mac** link is broken.

Current link is https://hyperledger.github.io/composer/installing/prereqs-mac.html
Active link on the hyperledger site is: https://hyperledger.github.io/composer/installing/installing-prereqs.html#macos

## Expected Behavior
User should be redirected to https://hyperledger.github.io/composer/installing/installing-prereqs.html#macos

## Actual Behavior
User is taken to https://hyperledger.github.io/composer/installing/prereqs-mac.html which is broken

## Possible Fix
update GitHub Pages site reference in the DeveloperWork course

## Steps to Reproduce
1. Go to module 4 of the course: https://developer.ibm.com/courses/all/ibm-blockchain-foundation-developer/?course=begin#11985 for the **Pre-requisites** page to get started.
![image](https://user-images.githubusercontent.com/5648785/37312279-ce07a63a-2620-11e8-8137-df9d20b5a7fe.png)
2. Click the **Setting up the Mac** link resulting in the following:
![image](https://user-images.githubusercontent.com/5648785/37312308-e301abc6-2620-11e8-8871-51b8b4bb83bf.png)

## Existing issues
https://github.com/hyperledger/composer/issues/3167 is the same issue but is closed.  Not sure why they thought it shouldn't be opened here instead they said they were going to open it to Coursera.  The broken link says to open issues in the composer GitHub project.

## Context
Just annoyance to go find the right links to setting up the playground for my machine.

## Your Environment
* Mac OSX

**Comment by davidkel** [comment]
The link isn't broken, it has moved. Whoever references the link will need to update the link and point to the new location. Currently the link is
https://hyperledger.github.io/composer/installing/installing-prereqs#macos
please report this problem to the site where they have the old link to update it to the new one
