### ISSUE TITLE
Failed to register: Error: Calling register endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054]

### ISSUE THREAD

**Issue by vishalgoyal18** [hyperledger/composer#3586]
I am getting below error when running node registerAdmin.js. Please advise.

PatilCh@FC-PUN-UBUN01-BAS:~/blockchain/landreg$ node registerAdmin.js
 Store path:/home/PatilCh/.hfc-key-landreg-store
Successfully loaded admin from persistence
Assigned the admin user to the fabric client ::{"name":"admin","mspid":"Org1MSP","roles":null,"affiliation":"","enrollmentSecret":"","enrollment":{"signingIdentity":"cc93f1876d51ed6d179cf6320baf97517cfdc40c4a543352bcc24fd9f3aa3014","identity":{"certificate":"-----BEGIN CERTIFICATE-----\nMIICATCCAaigAwIBAgIUMC7k0Fj8bOt3abnOOr/YyNfH9XswCgYIKoZIzj0EAwIw\nczELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNh\nbiBGcmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMT\nE2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMTgwMzEyMDg1NTAwWhcNMTkwMzEyMDkw\nMDAwWjAhMQ8wDQYDVQQLEwZjbGllbnQxDjAMBgNVBAMTBWFkbWluMFkwEwYHKoZI\nzj0CAQYIKoZIzj0DAQcDQgAEaIdQeV+/8lSZsRC1GlrsH/0Pgk4AGStsryPc3Wkk\noe8ORA8fmeZ3kTKrTxwZgqUYGMRxWhnRpfZEw+i90nL8DKNsMGowDgYDVR0PAQH/\nBAQDAgeAMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFGGFzjVNq3iVYO3Gqs+XVGrf\nOpWwMCsGA1UdIwQkMCKAIEI5qg3NdtruuLoM2nAYUdFFBNMarRst3dusalc2Xkl8\nMAoGCCqGSM49BAMCA0cAMEQCIHPKa4XGb1Mk527b9utUuFFZHU4lYUHOyHU1Y4pV\nlBVEAiBl6siE4/lJ0TMHjWTAcoKki6ol5ryIs+Up7ku6EPAptQ==\n-----END CERTIFICATE-----\n"}}}
PatilCh@FC-PUN-UBUN01-BAS:~/blockchain/landreg$ node registerUser.js
 Store path:/home/PatilCh/.hfc-key-landreg-store
Successfully loaded admin from persistence
Failed to register: Error: Calling register endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054]
PatilCh@FC-PUN-UBUN01-BAS:~/blockchain/landreg$

**Comment by sstone1** [comment]
@vishalgoyal18 what sample is this? Where did you get `registerAdmin.js` and the rest of this code from?
