### ISSUE TITLE
ERROR: pull access denied for hyperledger/hyperledger-fabric-orderer, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by vishalgoyal18** [hyperledger/composer#3587]
I am running startFabric.sh file and getting error as below. Ubuntu 16.04 is my OS version. Please advise what could be the reason.

Creating network "net_basic" with the default driver
Pulling orderer.example.com (hyperledger/hyperledger-fabric-orderer:latest)...
ERROR: pull access denied for hyperledger/hyperledger-fabric-orderer, repository does not exist or may require 'docker login'

**Comment by davidkel** [comment]
This doesn't look like anything provided by Hyperledger Composer. If you need help with setting up a Hyperledger fabric network then you should follow the Hyperledger Fabric documentation
http://hyperledger-fabric.readthedocs.io/en/latest/
