### ISSUE TITLE
Unable to import card generated from REST server

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3588]
Following the below steps:
 - Start REST server in Multi-User mode 
 - Log in via GitHub
 - POST /wallet/import the netadmin card
 - POST /system Issue Identity to Participant
 - Download card file
 - Use CLI command `composer card import -f mark@trade-network.card`

Produces the error `Type Error: connectionOptions.wallet.contains is not a function`

The actual output should be `command succeeded` with the ability to use the card after import.

Requirements:

- [x] Fix issue
- [x] Add integration test to cover this scenario and prevent future regressions

**Comment by mbwhite** [comment]
Tactical solution to remove the 'wallet' elements from the connection profile. 
Looking at additional tests in the intergation section.
