### ISSUE TITLE
composer 0.18.1  error

### ISSUE THREAD

**Issue by tanhuiya** [hyperledger/composer#3591]
composer 0.18.1

command `composer network start -c PeerAdmin@hlfv1 -a basic-sample.bna -A admin -S adminpw` get error like this.

```
2018-03-13T14:55:39.042Z ERROR   HLFConnection           :start()                  {"message":"Error trying to instantiate composer runtime. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: REQUEST_TIMEOUT\n","stack":"Error: Error trying to instantiate composer runtime. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: REQUEST_TIMEOUT\n\n    at _initializeChannel.then.then.then.then.catch (/Users/tanhui/.nvm/versions/node/v8.9.4/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:499:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
✖ Starting business network definition. This may take a minute...
✖ Installing runtime for business network undefined. This may take a minute...
Error: Error trying to instantiate composer runtime. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT
```

**Comment by mbwhite** [comment]
` Installing runtime for business network undefined`

Undefined... what did you do to install the composer runtime?

**Comment by tanhuiya** [comment]
I export a bna file from Web Browser.
export FABRIC_VERSION=hlfv11
./startFabric.js
then run composer runtime install command,
followed by composer network start ...

It works well on 0.16.x

**Comment by tanhuiya** [comment]
here my steps

```
./stopFabric.sh
./teardownFabric.sh
export FABRIC_VERSION=hlfv11
./startFabric.sh
./createPeerAdminCard.sh
composer runtime install -c PeerAdmin@hlfv1 -n basic-sample
composer network start -c PeerAdmin@hlfv1 -a basic-sample.bna -A admin -S adminpw
```
wait many minutes ,then get error
```
✖ Starting business network definition. This may take a minute...
Error: Error trying to instantiate composer runtime. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT

Command failed
```

**Comment by bh4rtp** [comment]
you can check the peer container status by `docker ps -a`. it should exit unexpectedly. and then use `docker logs $PEER_CONTAINER` to see the error log.

**Comment by tanhuiya** [comment]
I change the createPeerAdmin.sh 
fix to below
```
"peer0.org1.example.com": {
                    "endorsingPeer": true,
                    "chaincodeQuery": true,
                    "eventSource": true
                },
```
and  now works

**Comment by tanhuiya** [comment]
The problem occurs again...

**Comment by tanhuiya** [comment]
@bh4rtp  
I have another question , do you known this.
https://stackoverflow.com/questions/49292170/endorsement-policy-doesnt-work

**Comment by bh4rtp** [comment]
@tanhuiya you can switch to another internet access point. to create the chaincode image, 0.18.1 will pull the npm modules from remote repository. i have succeeded running `composer network start ... `.
btw, 0.18.1 sounds unreasonable to pull the npm modules from internet.

**Comment by davidkel** [comment]
@bh4rtp @tanhuiya be aware you can specify an npmrc file to change the npm repository. If organisations want to manage their own internal npm repository (and a lot do) you can specify the npmrc on install to point to a different repo, such as an internal one hosted by your organisation.

**Comment by davidkel** [comment]
closing as this is not a composer problem but an environment issue as discussed #3596

**Comment by tanhuiya** [comment]
@bh4rtp 
what's the mean of `switch to another internet access point`

**Comment by tanhuiya** [comment]
@bh4rtp  just switch a network ?

**Comment by tanhuiya** [comment]
0.18.1 will pull the npm modules from remote repository
the operation is in the container which build by hyperledger/fabric-ccenv:x86_64-1.1.0-rc1 image ?

@davidkel  @bh4rtp

**Comment by hi2rashid** [comment]
The issue is silly.

open `docker logs peer0.org1.example.com`

It will show the following

<img width="1275" alt="screen shot 2018-05-04 at 11 02 44 pm" src="https://user-images.githubusercontent.com/10250923/39650086-827b00c4-4fef-11e8-86f2-6e2f694863b7.png">

There is a Extra character when you copy the string from hyperledger composer website.

Try copy pasting the following line to a notepad and paste in command line. it will work.

`composer network start --networkName tutorial-network --networkVersion 0.0.1 --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv1 --file networkadmin.card
`

**Comment by silvogo** [comment]
@hi2rashid I have done exactly the same you said (Copy pasting the line to a notepad and paste in command line) but still doesn't work. I got the same error (still have the extra character). What is the extra character ? Do you know how to fix this ? 
![screenshot_6](https://user-images.githubusercontent.com/17312055/39726010-8c83b978-5245-11e8-9f1c-ea4719905166.png)

**Comment by silvogo** [comment]
I have tried with the basic-sample-network from playground and when I issue the command:

> composer network start --networkName my-basic-sample --networkVersion 0.0.1 --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv1 --file networkadmin.card

I got the error :

> Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: chaincode error (status: 500, message: cannot get package for chaincode (my-basic-sample:0.0.1))

I have posted the question with more detail in https://stackoverflow.com/questions/50232772/v0-19-2-hyperledger-composer-network-start-failed

Anybody know how to fix this ?

**Comment by varunajmera0** [comment]
> composer network start --networkName tutorial-network --networkVersion 0.0.1 --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv1 --file networkadmin.card

it worked finally @hi2rashid thanks

![screen shot 2018-10-19 at 11 57 41 pm](https://user-images.githubusercontent.com/22893376/47236850-f4f85400-d3fa-11e8-8691-cfe6ba1011f3.png)
