### ISSUE TITLE
Model extend from an other namespace

### ISSUE THREAD

**Issue by PPCM** [hyperledger/composer#3598]
## Context
Currently it is possible to extend a model, but only in the same namespace.

## Expected Behavior
It will be great if the inheritance will be able between different namesape

For example

In `model1.cto` file
```
namespace com.example.model1

asset Element identified by elementId {
  o String elementId
}
```

In `model2.cto` file
```
namespace com.example.model2

asset Leaf extends com.example.model1.Element {
  o String newField
}
```

**Comment by sstone1** [comment]
@PPCM you need to use `import`

```namespace com.example.model2

import com.example.model1.Element

asset Leaf extends Element {
  o String newField
}```
