### ISSUE TITLE
Composer installation prerequisites instructions for Ubuntu misleading

### ISSUE THREAD

**Issue by rskokan** [hyperledger/composer#3617]
The installation prereqs. at https://hyperledger.github.io/composer/installing/installing-prereqs.html do not work on Ubuntu 16.04.

The standard distro nodejs and npm versions are too old. installation of composer-cli will then fail with ELIFYCYCLE or similar.

When installing node & npm from the nodesource PPA, composer can then be installed.

Also, installing build-essentials is probably needed.

**Comment by davidkel** [comment]
That page doesn't tell you to install the distro versions of node.js and npm. It just says you need to install specific versions. The page also has a script specifically for ubuntu which you can download and execute which will install the pre-reqs for you. It installs nvm to manage node installations.
However I do note that we should also be mentioning that you need the basic compiler tools, however I have not come across an ubuntu 16.04 installation that didn't include the required C compilers and tools by default.

**Comment by davidkel** [comment]
#3620 with the suggestion to move the pre-reqs further up the page is worth considering, plus the important section isn't in bold just has ** around it.

**Comment by davidkel** [comment]
see also #3714
