### ISSUE TITLE
Missing or incorrect code samples in the page "Issuing a new identity to a participant"

### ISSUE THREAD

**Issue by aosti** [hyperledger/composer#3621]
The documentation presented in the page https://hyperledger.github.io/composer/managing/identity-issue uses the admin card in the javascript test that was supposed to return the participant name which had its identity previously created.

It also does not show the creation of the card after using the javascript api, which seems to be necessary for the ping test.

**Comment by davidkel** [comment]
There are some other issues with this page, such as a business network digitalpropertyNetwork which is not a valid network name.

**Comment by aosti** [comment]
The page https://hyperledger.github.io/composer/reference/composer.transaction.submit.html also has an old example.
