### ISSUE TITLE
Provide set of images for use

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3624]
We do not (yet) support windows, and suggest/recommend that people use VMWare to create a Ubuntu VM within which they install all the required items.

Wouldn't it be magical if there were images that they could download that could be used with their VMWare ... preinstalled with the required items at a known/given level.

Whilst this would mean that someone would not automatically get 'the latest and greatest' release (ie fixed versions ... they could be updated if required ... and they would be getting updated from a known image.

The reasoning behind this is that:
 - we should be making access to the tooling as easy as possible
 - there have been many configuration errors experienced and reported within RocketChat that could be avoided though 'using an image'

Something along the lines of:
http://www.sysprobs.com/create-virtualbox-image-share-upload

**Comment by mbwhite** [comment]
You mention VMWare; Virtual Box as well?

**Comment by jt-nti** [comment]
Pst. https://github.com/jt-nti/composer-devenv :)

If you really want people to download a complete VM image, make sure they get built automatically otherwise they're going to be out of date faster than a node dependency!

**Comment by nklincoln** [comment]
True - though the idea is to have known good images at known levels that people can use, without any worry about a dependancy changing.

So all they need to do if they want to 'play' with all the tooling at a set level is to grab the image and start it up (as a VirtualBox OVA file for instance) ... if they want the latest and greatest, then they can go through one of the installation routes at their peril!

**Comment by nklincoln** [comment]
Continuing this thread:
 - An OVA file (VirtualBox image) for Ubuntu with all Composer 0.16 tooling, Fabric images and pre-reqs, is circa 3GB
