### ISSUE TITLE
npm can't install composer-admin of version 0.18.x

### ISSUE THREAD

**Issue by tanhuiya** [hyperledger/composer#3634]
I use the latest version (0.18.1) of composer .but npm can't install composer-admin of version 0.18.x.

**Comment by nklincoln** [comment]
Do you have any error logs that might help diagnose this?

**Comment by tanhuiya** [comment]
npm install composer-admin, the latest is 0.16.6, no v0.18.1
@nklincoln

**Comment by nklincoln** [comment]
The command you want is `npm install -g composer-admin@0.18.1`

**Comment by tanhuiya** [comment]
When I user the lastest 0.16.6 
got the following error

```
error Error: Failed to load connector module "composer-connector-undefined" for connection type "undefined".
```
