### ISSUE TITLE
As an end user I can resolve relationships inside TP functions

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#364]
## Context
A user has requested the ability to resolve relationships using the runtime module.

## Expected Behavior
Get an asset or participant from a registry with its relationships resolved.

## Actual Behavior
Relationships are not resolved.

## Steps to Reproduce
1. Get an asset from a registry in a TP function
2. Note that relationships within the asset are not resolved

## Existing issues
http://stackoverflow.com/questions/42625977/resolving-relations-inside-a-chain-transaction

## Context
Relationships must be resolved manually.

## Your Environment
* Version used: 0.4.5

**Comment by shachisharma** [comment]
When an asset or participant is pulled from the AssetRegistry inside TP functions, the relationships are to be resolved manually by the developer using runtime APIs
