### ISSUE TITLE
Dev tutorial updates needed

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#3658]
Fixes required
- [x] Step Four describes how the network is deployed this needs updating
- [x] Step 4.3 the file used on the import command should be networkA.card

**Comment by samjsmith** [comment]
- [ ] Step 11 `composer runtime install` becomes `composer network install`

**Comment by jt-nti** [comment]
The dev tutorial ends a bit abruptly. It would be nice if the dev tutorial continued with creating the same participants and assets, and submitting the same transaction, as the playground tutorial but via the REST server.
