### ISSUE TITLE
Playground API gets odd versions of the samples

### ISSUE THREAD

**Issue by samjsmith** [hyperledger/composer#3661]
The multi-org tutorial requires a .bna file and says

_You will need a file trade-network.bna (business network archive, from our sample networks) to do the test. If you don't have this, just go to https://composer-playground.mybluemix.net/ and deploy the trade-network sample in the online Playground, then 'connect' to the business network as 'admin', and finally export it to the current directory as trade-network.bna_ 

I did this and now we need the version number of the network as contained in the package.json file.
At the moment, the playground seems to be picking up an odd version of this sample.  The UI and the package.json both show version `0.2.0-20180102082548`
However `npm view trade-network` shows `'dist-tags': { unstable: '0.2.3-20180314171154', latest: '0.2.2' },` which corresponds to the code view here https://github.com/hyperledger/composer-sample-networks/blob/master/packages/trade-network/package.json

I think this needs some investigation and sorting out,

**Comment by jt-nti** [comment]
It looks like the playground updates the version when it deploys for the first time. It seems to keep the right version on export anyway. There are some changes coming here for #3241 where automated version numbers will look like 0.2.0-deploy.0 and the version can easily be edited in the UI.

**Comment by caroline-church** [comment]
Fixed by releasing composer-sample-models and composer-sample-networks
