### ISSUE TITLE
Can not listen to events if a transaction has not been submitted before

### ISSUE THREAD

**Issue by Rmannn** [hyperledger/composer#3669]
The new implementation of the events channel basis for 1.1 is starting to listen to events only when chaincode is invoked/started/upgraded
If we connect to the network, there is no way to listen to events if this instance has not invoked the chaincode before.

## Context
I am using a businessNetworkConnection to listen to events only.
This connection will not submit any transaction, until it receives an event and then do some work.

## Expected Behavior
Connecting to the network should register a listener

## Actual Behavior
Connecting is not enough to start listening when we are not submitting an initial tx.

## Possible Fix
The composer-connector-hlfv1@0.18.2 package should start listener when connecting or provide a way to start listener form the BusinessNetworkConnection

## Actual Workaround 
Create simple transaction e.g StartListener
Submit the transaction from a connection that need to listen to events
Start listening as usual

## Steps to Reproduce
1. Upgrade to fabric 1.1
2. Install the composer version 0.18.2

## Your Environment

* Version used: 0.18.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): nodejs v8.9.1
* Operating System and version (desktop or mobile): desktop

**Comment by davidoevans** [comment]
Using v0.18.4.  Even with approach described above, can only seem to access events from the same businessNetworkConnection instance that submitted the transaction.

I assume that's not expected behaviour...correct?

**Comment by davidkel** [comment]
As event hub connect is asynchronous, it's not possible to check that connection has been made straight away, so a couple of thoughts on how to solve this
- call _checkCCListener on a ping request as business network connections I believe call ping
- call _registerCCEventHandler on _connectToEventHubs and rely on the error handler to switch to a new event hub if connection is not possible. 
The 2nd has the potential to miss events depending on timing.

**Comment by davidkel** [comment]
As a further thought, it is possible to listen for new event listeners so it could be set up when the first event listener is registered.
