### ISSUE TITLE
No matching version found for composer-common@0.19.0

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#3672]
## Context

While developing Composer with an unreleased version (i.e. not published to npm)

## Expected Behavior

I used to be able to deploy/update business networks

## Actual Behavior

Not so much after the native fabric deploy merge

```
Error: Error trying to start business network. Error: No valid responses from any peers. Response from attempted peer comms was an error: Error: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code ETARGET npm ERR! notarget No matching version found for composer-common@0.19.0 npm ERR! notarget In most cases you or one of your dependencies are requesting npm ERR! notarget a package version that doesn't exist. npm ERR! notarget npm ERR! notarget It was specified as a dependency of 'bother' npm ERR! notarget npm ERR! A complete log of this run can be found in: npm ERR! /root/.npm/_logs/2018-03-22T20_41_34_395Z-debug.log "
```

## Possible Fix

Some documentation would be awesome. Something in the contributing guide?

**Comment by mbwhite** [comment]
*This is SRTICTLY for contributor use only*

To execute local tests and applications using your locally cloned git workspace use these instructions
(this one route, there is an alternative - but this permits a more natural way of working)

Outline of the approach
- Install Verdaccio - as a local npm proxy server, and start that up and running.
- Publish your local workspace to Verdaccio
- Setup you local environment to find the `cli.js` of the `composer-cli` package
- Ensure that when you `composer network install` the `-o npmrcFile` option is passed with a a npmrc file that points to the local verdaccio server

Have tried to encapsulate the above in this script...
https://github.com/ampretia/composer-developer-cookbook/tree/master/scripts/local-npm

grab that dir, npm install, and npm start

**Comment by adnanjee** [comment]
![screenshot from 2018-10-04 21-06-25](https://user-images.githubusercontent.com/16976969/46484210-e2432400-c82b-11e8-93cf-3bd355f65a84.png)
