### ISSUE TITLE
graphql server

### ISSUE THREAD

**Issue by jas99** [hyperledger/composer#3682]
It will be awesome if u plan to add graphql server along with rest server and maybe even use graphql (which is quickly getting popular) as modeling language for composer.

Thx

**Comment by mbwhite** [comment]
It's something that I experimented with a few months back; it would be interesting.
If any member of the community would like to help here... I'm happy to act as a mentor.

**Comment by jas99** [comment]
This might be interesting solution to try. 
https://github.com/tallyb/loopback-graphql and also https://dgraph.io use of graphql+ language very interesting approach.
@mbwhite I will start email thread with u.

Thx

**Comment by jt-nti** [comment]
This sounds interesting. It would be a shame to hide any progress in an email thread- would it be possible to use Rocket Chat instead? It might be something worth discussing on a future community call as well to see how much interest is out there.

**Comment by jas99** [comment]
@jt-nti Rocketchat works for me and just joined; anyways was planing to keep any issue related talk over here.

**Comment by tbrooke** [comment]
I am just starting a project with GraphQL and Composer -- keep me posted
