### ISSUE TITLE
Unexpected identifier in composer-common/lib/cardstore/businessnetworkcardstore.js:54

### ISSUE THREAD

**Issue by Thomas55777** [hyperledger/composer#3685]
I have installed the composer-cli version 0.18.2 using the below command:
sudo npm install -g composer-cli@next

when I run anything from composer such as "composer --version" I get the following:
/usr/lib/node_modules/composer-cli/node_modules/composer-common/lib/cardstore/businessnetworkcardstore.js:54
    async get(cardName) {
          ^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/composer-cli/node_modules/composer-common/index.js:56:43)

Its very possible that I am doing something wrong on my end.  Any help or direction would be appreciated.  Thank you

**Comment by sstone1** [comment]
@Thomas55777 you do not have Node.js 8 installed; Composer has required Node.js 8 since before v0.16.x. Please upgrade your version of Node.js to 8.x.

**Comment by Thomas55777** [comment]
Thank you very much for the prompt response.  
I updated my nodejs version but now I receive:

Error: Cannot find module './api'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/composer-cli/node_modules/node-report/index.js:3:13)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

**Comment by Thomas55777** [comment]
In case anyone else runs into this it was happening because the npm packages were not installing fully.  I resolved my issue by flagging it with --usafe-perm based on this post from StackOverflow:
https://stackoverflow.com/questions/29468404/gyp-warn-eacces-user-root-does-not-have-permission-to-access-the-dev-dir

My working npm command was:
$ npm i -g composer-cli@next --unsafe-perm

Thank you for your help. It pointed me in the right direction!

**Comment by jt-nti** [comment]
@Thomas55777 the real problem here is using `sudo` in the command `sudo npm install -g composer-cli@next`

Using the `--unsafe-perm` is not the recommended solution. Instead, node should not be installed globally as root and Composer should not be installed using `sudo`. This is documented in the Composer prereq install guide if that helps https://hyperledger.github.io/composer/installing/installing-prereqs.html

A better solution from the StackOverflow post you linked to is the accepted answer, i.e. follow the recommended approach to fixing permissions problems in the npm documentation https://docs.npmjs.com/getting-started/fixing-npm-permissions

For a VM based development environment set up the correct way, have a look at https://github.com/jt-nti/composer-devenv

**Comment by Thomas55777** [comment]
Yes, I am using VirtualBox and didn't realize that project existed.  Thank you for pointing me in that direction, however I did get the follow error when running "vagrant up" seem it is unable to import the key needed to install docker:

    default: Executing: /tmp/tmp.b1Qdeyr45T/gpg.1.sh --keyserver
    default: hkp://p80.pool.sks-keyservers.net:80
    default: --recv-keys
    default: 58118E89F3A912897C070ADBF76221572C52609D
    default: gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
    default: gpgkeys: key 58118E89F3A912897C070ADBF76221572C52609D can't be retrieved
    default: gpg: no valid OpenPGP data found.
    default: gpg: Total number processed: 0
    default: gpg: keyserver communications error: keyserver helper general error
    default: gpg: keyserver communications error: unknown pubkey algorithm
    default: gpg: keyserver receive failed: unknown pubkey algorithm

I checked http://p80.pool.sks-keyservers.net/ and few other key servers and that key doesn't appear to be in there.  I fixed by editing the provision-root.sh file and replaced:

    apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

with:

    curl -fsSL https://apt.dockerproject.org/gpg | sudo apt-key add -

I got that from this blog: https://www.unixmen.com/how-to-install-wordpress-with-docker-on-ubuntu-16-04/

After that I reran "vargrant up --provision" and everything seemed to install correctly.  Thank you very much for your help. It is greatly appreciated.  I am glad to now be using Hyperledger with the proper setup even if it is only for dev.

**Comment by siddjain** [comment]
> @Thomas55777 the real problem here is using `sudo` in the command `sudo npm install -g composer-cli@next`
> 
> Using the `--unsafe-perm` is not the recommended solution. Instead, node should not be installed globally as root and Composer should not be installed using `sudo`. This is documented in the Composer prereq install guide if that helps https://hyperledger.github.io/composer/installing/installing-prereqs.html

hello, i would like to understand what is the reason behind Composer should not be installed using `sudo`?
nothing like this is documented on https://hyperledger.github.io/composer/latest/installing/development-tools.html

Also I have node 10.12.0 and when I try to npm install composer tools it fails. Do I need to use v8 of node - nothing more and nothing less?
