### ISSUE TITLE
can't run the pre-requisites steps for composer

### ISSUE THREAD

**Issue by aviroops** [hyperledger/composer#3712]
can't run the pre-requisites steps for composer

## Context
Trying to run the pre-requisites steps for hyper edger composer

## Expected Behavior
curl -O https://hyperledger.github.io/composer/prereqs-ubuntu.sh should extract prereqs-ubuntu.sh and after granting proper permission, the prereqs-ubuntu.sh should execute and install all the pre-requisites in Ubuntu for composer

## Actual Behavior
curl -O https://hyperledger.github.io/composer/prereqs-ubuntu.sh is extracting the wrong file and as a result when trying to execute prereqs-ubuntu.sh, its showing the below error -
./prereqs-ubuntu.sh: line 1: syntax error near unexpected token `newline'
./prereqs-ubuntu.sh: line 1: `<!doctype html>'

## Steps to Reproduce
1. run - curl -O https://hyperledger.github.io/composer/prereqs-ubuntu.sh
2. run - chmod u+x prereqs-ubuntu.sh
3. run - ./prereqs-ubuntu.sh
4.

**Comment by sstone1** [comment]
@aviroops please see the updated documentation; the URL to the `prereqs-ubuntu.sh` script has been fixed on this page: https://hyperledger.github.io/composer/latest/installing/installing-prereqs
