### ISSUE TITLE
ubuntu 16.04 pre-req install errors

### ISSUE THREAD

**Issue by sandeep20162017** [hyperledger/composer#3717]
precondition :
Ubuntu 16.04 clean install (VPS)
logged in as user with sudo access
---------------------
cmd :
npm install -g composer-cli

output :
25207 verbose stack Error: EACCES: permission denied, access '/usr/local/lib'
25207 verbose stack     at Error (native)
25208 verbose cwd /home/dev
25209 error Linux 4.4.0-21-generic
25210 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "composer-cli"
25211 error node v4.2.6
25212 error npm  v3.5.2
25213 error path /usr/local/lib
25214 error code EACCES
25215 error errno -13
25216 error syscall access
25217 error Error: EACCES: permission denied, access '/usr/local/lib'
===============================================================================================
2/ logged in as root -
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-21-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/composer-cli/node_modules/node-report
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

**Comment by sstone1** [comment]
@sandeep20162017 please read the documentation:
https://hyperledger.github.io/composer/latest/installing/installing-prereqs

Note this section:
```**If installing Hyperledger Composer using Linux, be aware of the following advice:

Login as a normal user, rather than root.
Do not su to root.
When installing prerequisites, use curl, then unzip using sudo.
Run prereqs-ubuntu.sh as a normal user. It may prompt for root password as some of it's actions are required to be run as root.
Do not use npm with sudo or su to root to use it.
Avoid installing node globally as root.**```

You have installed node/npm globally as root. Please reinstall node/npm using nvm (node version manager), available from: https://github.com/creationix/nvm#installation
