### ISSUE TITLE
weblink with instructions to install developing environment for hyperledge not working

### ISSUE THREAD

**Issue by jmat101** [hyperledger/composer#3718]
The weblink with instructions to install developing tools and hyperledge composer is not working. I cleared the browser cache but its still not loading.

**Comment by sstone1** [comment]
Without the URL, I can't tell you what link is broken, but you need to put `/latest/` into the URLs:
https://hyperledger.github.io/composer/latest/

**Comment by Jmat201** [comment]
@sstone1 sorry I forgot to add the link

https://hyperledger.github.io/composer/installing/development-tools.html
