### ISSUE TITLE
0.16.x documentation requires updating away from 'latest' tag

### ISSUE THREAD

**Issue by lesleyannjordan** [hyperledger/composer#3720]
With 0.19.x taking on the 'latest' tag, the -0.16.x branch is required to be referenced through 0.16.<latest patch release no>

Various changes required:

- build out a specific documentation url e.g. https://hyperledger.github.io/composer/v0.16/   (This is complete already)
- update documentation

Documentation updates:

- references to 'latest' or no tag need to change to '@0.16.x' where x is the latest patch release
- addition of 'export FABRIC_VERSION=hlfv1' command before downloading or starting fabric commands

Known pages with issues:
https://hyperledger.github.io/composer/v0.16/installing/development-tools

Suggest a new build of 0.16.x branch to push through the doc changes and provide a feature release to include references to the new documentation URL etc

**Comment by samjsmith** [comment]
So the [Playground Tutorial in the v0.16 docs](https://hyperledger.github.io/composer/v0.16/tutorials/playground-tutorial) currently tells users to open the IBM cloud hosted Playground which is now v0.19.

@lesleyannjordan @sstone1 
Should we remove the tutorial or make changes to publish another version based on the 16 branch to IBM cloud?

**Comment by lesleyannjordan** [comment]
@samjsmith correct IBM hosted playground is now v0.19.  Agree, to that end I would recommend removing the playground tutorial (and other doc) that refers to the hosted playground.  References to playground which is downloaded and hosted locally can remain.

**Comment by samjsmith** [comment]
I think that this issue will also need changes to the docs deployment script so that it can push the doc to the /v0.16 site.

**Comment by samjsmith** [comment]
I can't really test these scripts without doing a PR which will trigger a tagged build and then debugging any problems by examining the logs so that's what I'll do next.
If by some remote chance, the build passes and the unstable versions of v0.16 are pushed to npm then that's a good indication that things are happy for when we want to release.
Obviously PR reviews will probably find issues with my changes before that!

**Comment by bestbeforetoday** [comment]
Repurpose this issue to address the issues mentioned above in the 0.19 rather than 0.16 docs.
