### ISSUE TITLE
Error installing components of Developing environment and playground

### ISSUE THREAD

**Issue by Jmat201** [hyperledger/composer#3730]
I am trying to install the components and playground of the development environment by following the instructions on the install page and I am getting a large number of errors. 

I had installed xcode and the command line for os 10.12 xcode version 9.2 from the app store.

## Context

The following the result of running the command 'npm install -g composer-cli'

Jeffs-macbook:~ Jeff$ npm install -g composer-cli
npm WARN deprecated fs-promise@1.0.0: Use mz or fs-extra^3.0 with Promise Support
/Users/Jeff/.nvm/versions/node/v8.11.1/bin/composer -> /Users/Jeff/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/cli.js

> dtrace-provider@0.8.6 install /Users/Jeff/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/Jeff/anaconda/bin/python" is v3.6.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Users/Jeff/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/Jeff/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:567:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/Jeff/.nvm/versions/node/v8.11.1/bin/node" "/Users/Jeff/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Jeff/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/dtrace-provider
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

> fsevents@1.1.3 install /Users/Jeff/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/fsevents
> node install

[fsevents] Success: "/Users/Jeff/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-report@2.2.1 install /Users/Jeff/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/node-report
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/Jeff/anaconda/bin/python" is v3.6.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Users/Jeff/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/Jeff/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/Jeff/.nvm/versions/node/v8.11.1/bin/node" "/Users/Jeff/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Jeff/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/node-report
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-report@2.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-report@2.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Jeff/.npm/_logs/2018-03-30T05_24_13_344Z-debug.log

## Expected Behavior

Intall:

1.  Essential CLI tools:
2. Utility for running a REST Server on your machine to expose your business networks as RESTful APIs:
3. Useful utility for generating application assets:
4. Yeoman is a tool for generating applications, which utilises generator-hyperledger-composer:
5. Playground 

## Steps to Reproduce
https://hyperledger.github.io/composer/latest/installing/development-tools.html

## Context
Installing the developing environment 

## Your Environment
- node v8.11.1 (npm v5.6.0)
- installed Xcode and C from app store 
- Mac OS Sierra 10.12.6

**Comment by sstone1** [comment]
@Jmat201 please read the error message - it indicates that your version of Python is not compatible with `node-gyp`, which is a part of Node.js that builds native modules:

```gyp ERR! stack Error: Python executable "/Users/Jeff/anaconda/bin/python" is v3.6.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.```
