### ISSUE TITLE
Error while start fabric for first-network - Git/etc/Hyperledger files missing

### ISSUE THREAD

**Issue by Givench** [hyperledger/composer#3735]
I'm trying to start fabric on windows 10 for my first-network from the tutorial, and the Git/etc/Hyperledger files are missing.

## Context
When I run ./startFabric.sh I got this error:
Error: channel create configuration tx file not found open C:/Program Files/Git/etc/hyperledger/configtx/composer-channel.tx: no such file or directory

Looked for the files on the path but I don't have the Hyperledger folder on etc.
I'm searching the folder to put it on c:/ProgramFiles/Git/etc but I can´t find it on GitHub.

Where or how I can download the Hyperledger folder?

## Expected Behavior
The folder should be on the path and the /startFabric.sh execute correctly

## Actual Behavior
The folder isn´t on the path and the /startFabric.sh can't execute correctly

## Possible Fix
Put the folder on the path

## Steps to Reproduce
I don't know why I  don´t have the Hyperledger folder on Git/etc

**Comment by lesleyannjordan** [comment]
Please see link https://hyperledger.github.io/composer/latest/installing/installing-prereqs.html for pre-reqs and supported platforms

**Comment by lesleyannjordan** [comment]
Check for help on this area in https://github.com/hyperledger/composer-knowledge-wiki/blob/latest/knowledge.md
and
https://stackoverflow.com/search?q=%5Bhyperledger-composer%5D+windows

A ticket exists for extending support to running on windows: https://github.com/hyperledger/composer/issues/65

**Comment by flibustier** [comment]
Hi! I've got the same problem, resolved with @knagaev comment on #65 : 

> I inserted in `fabric-tools\hlfv11\startFabric.sh`

`export MSYS_NO_PATHCONV=1`

> before
```
# Create the channel
docker exec peer0.org1.example.com peer channel create -o orderer.example.com:7050 -c composerchannel -f /etc/hyperledger/configtx/composer-channel.tx
```
> and the `fabric-tools\startScript.sh` runs ok

So after that I was able to run `composer network install` and `composer network start` without any problem!

**Comment by kavithas-orbital** [comment]
Thanks @flibustier and @knagaev !  Was having an issue not being able to run the DeveloperTutorial on Windows - and this turned out to be the fix.  Spent 2 days on this issue.  Thanks!!

**Comment by kavitha-sant** [comment]
Thanks @flibustier and @knagaev - I had the same issue with not being able to run the Developer Tutorial on Windows.  This turned out to be the fix.

**Comment by mohindergupta** [comment]
I am using ubuntu 16.0.4, hyper ledger fabric 1.1. I had the same problem while starting the network. I tried the solution as suggested before. Unfortunately that didn't help. I further noticed that probably my Fabric wasn't starting completely as FABRIC_START_TIMEOUT parameter wasn't set. Therefore I used the command "export  FABRIC_START_TIMEOUT=45" and then ran startFabric.sh. It solved my problem.

**Comment by Hotchongas** [comment]
can i ask where did you put the script "export FABRIC_START_TIMEOUT=45"?
 is it before the? 
`      # Create the channel
docker exec peer0.org1.example.com peer channel create -o orderer.example.com:7050 -c composerchannel -f /etc/hyperledger/configtx/composer-channel.tx`

**Comment by Niklaskkkk** [comment]
Hi, When I try to go through a pre-build vagrant-project I receive an error when running the following command.

I have the following systems.
Ubuntu 18.04
Oracle VirtualBox 5.2
 Please help!

cd ~/fabric-fundamentals
configtxgen -profile FourOrgsOrdererGenesis -outputBlock channel-artifacts/genesis.block
configtxgen -profile FourOrgsChannel -outputCreateChannelTx channel-
artifacts/colleagues/channel.tx -channelID colleagues
configtxgen -profile ThreeOrgsChannel -outputCreateChannelTx channel-
artifacts/partypresent/channel.tx -channelID partypresent

ERROR Message in command line//

vagrant@ubuntu-xenial:~/fabric-fundamentals$ cd ~/fabric-fundamentals
vagrant@ubuntu-xenial:~/fabric-fundamentals$ configtxgen -profile FourOrgsOrdererGenesis -outputBlock channel-artifacts/genesis.block
2019-04-21 18:02:47.311 UTC [common/tools/configtxgen] main -> INFO 001 Loading configuration
2019-04-21 18:02:47.321 UTC [common/tools/configtxgen] doOutputBlock -> INFO 002 Generating genesis block
2019-04-21 18:02:47.322 UTC [common/tools/configtxgen] doOutputBlock -> INFO 003 Writing genesis block
vagrant@ubuntu-xenial:~/fabric-fundamentals$ configtxgen -profile FourOrgsChannel -outputCreateChannelTx channel-
2019-04-21 18:02:47.384 UTC [common/tools/configtxgen] main -> INFO 001 Loading configuration
2019-04-21 18:02:47.393 UTC [common/tools/configtxgen] doOutputChannelCreateTx -> INFO 002 Generating new channel configtx
2019-04-21 18:02:47.419 UTC [common/tools/configtxgen] doOutputChannelCreateTx -> INFO 003 Writing new channel tx
vagrant@ubuntu-xenial:~/fabric-fundamentals$ artifacts/colleagues/channel.tx -channelID colleagues
-bash: artifacts/colleagues/channel.tx: No such file or directory
vagrant@ubuntu-xenial:~/fabric-fundamentals$ configtxgen -profile ThreeOrgsChannel -outputCreateChannelTx channel-
2019-04-21 18:02:47.482 UTC [common/tools/configtxgen] main -> INFO 001 Loading configuration
2019-04-21 18:02:47.491 UTC [common/tools/configtxgen] doOutputChannelCreateTx -> INFO 002 Generating new channel configtx
2019-04-21 18:02:47.516 UTC [common/tools/configtxgen] doOutputChannelCreateTx -> INFO 003 Writing new channel tx
vagrant@ubuntu-xenial:~/fabric-fundamentals$ artifacts/partypresent/channel.tx -channelID partypresent
-bash: artifacts/partypresent/channel.tx: No such file or directory
