### ISSUE TITLE
Error installing v0.19 on Windows

### ISSUE THREAD

**Issue by uluhonolulu** [hyperledger/composer#3737]
## Context
Running `npm install -g composer-cli@next` produced the following error:

```
LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay
32.lib' [C:\scripts\node_modules\composer-cli\node_modules\x509\build\x509.vcxp
roj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\scripts\node_modules\composer-cli\node_modules\x509
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
```

The folder `C:\OpenSSL-Win64` doesn't exist on my machine.

I'm on Windows 7, node v8.9.1, npm v5.5.1.

**Comment by uluhonolulu** [comment]
Looks like it's related to https://github.com/Southern/node-x509/issues/49

**Comment by uluhonolulu** [comment]
Installing OpenSSL from http://slproweb.com/products/Win32OpenSSL.html to the default directory fixed it.

**Comment by davidkel** [comment]
@uluhonolulu A couple of things you should be aware of
1. you have installed 0.18.x, not 0.19 as there is no dependency now on x509 in 0.19
2. We don't support windows officially, but are tracking issues here #65

**Comment by uluhonolulu** [comment]
@davidkel yes, realized my mistake. I was using the @next tag, should have used @latest

**Comment by Ehoussoud** [comment]
Hi @uluhonolulu,

Could you please let me know all the steps to install Hyperledger Composer on Windows 10 Home?

Cheers
Ehoussoud

**Comment by uluhonolulu** [comment]
@Ehoussoud I don't know, I'm on 7. But the main idea is that you do it as in the docs, but you have to install Cygwin and use the shell scripts from https://github.com/acloudfan/HLF-Windows-Fabric-Tool to install Fabric etc

**Comment by uluhonolulu** [comment]
@Ehoussoud important is to put this in your .bash_profile:
```
export  COMPOSE_CONVERT_WINDOWS_PATHS=1
export  MSYS_NO_PATHCONV=1
```
