### ISSUE TITLE
Ubuntu Prereqs shell script link broken

### ISSUE THREAD

**Issue by svajiraya** [hyperledger/composer#3762]
The URL(https://hyperledger.github.io/composer/prereqs-ubuntu.sh) for Ubuntu script to install Composer PreReqs is broken: 

![image](https://user-images.githubusercontent.com/14901456/38373372-7c7b2de2-3934-11e8-9442-2ec3d1e97ce3.png)

## Context
Tried installing Ubuntu pre-reqs using the link in docs and looks like the script doesn't exist anymore

## Expected Behavior
Link should point to valid shell script

## Actual Behavior
404 Error is being displayed 

## Steps to Reproduce
1. use CURL command on https://hyperledger.github.io/composer/next/installing/installing-prereqs.html#ubuntu

## Your Environment
* Operating System and version (desktop or mobile): AWS Ubuntu AMI

**Comment by ronaldlong46** [comment]
https://hyperledger.github.io/composer/latest/prereqs-ubuntu.sh 

Had the same issue earlier. That's the link you're looking for.

**Comment by lesleyannjordan** [comment]
Please see release notes for changes in documentation URLs (inclusion of release tags)  https://github.com/hyperledger/composer/releases/tag/v0.19.0
