### ISSUE TITLE
As a User, having an APIKEY would provide a first level of security while focusing on the development of the business network

### ISSUE THREAD

**Issue by nicolapaoli** [hyperledger/composer#3763]
Using an ApiKey to get access to the REST API would help to establish a first layer of security for a development environment. Thus, this won't substitute the actual Authentication process. Rather it can be an optional support for both early-project development and authentication process.

## Context
As a User, using an APIKEY allow to adopt a easy-to-setup first layer of security to the development of early-stage projects. 
Threads on Rocketchat discussed about passport-local solutions where users are pre-loaded on db to provide a simple security layer over the project.  e.g. [Rocket Chat Thread](https://chat.hyperledger.org/channel/composer?msg=MaXLCfWrPXNgZAj7d)

## Expected Behavior
The idea is to provide an APIKEY as simple layer of security between client and rest server.
It should be optional and it can be used either:
- In early-stage development of projects which don't need a complete Auth process.
- As an extra layer of security to support Auth and TLS security.

## Actual Behavior
In the current version of the Rest Server it's possible to implement the Auth process using different passport strategies, but more effort is required to preload users locally or registering account online.

## Possible Fix
An APIKEY can be a feature to control the communication between multiple APIs in the same network. 
To enable an APIKEY on the Composer Rest API we can either:
- Setup an environmental variable `COMPOSER_APIKEY` 
- Add a param `-y APIKEY` via the command line when starting the composer-rest-server.

We already extended the rest-server implementing this for one of our projects, as we did not find anything elsewhere. 

## Existing similar issues
- [Rocket Chat Thread](https://chat.hyperledger.org/channel/composer?msg=MaXLCfWrPXNgZAj7d)
- [Rocket Chat Thread](https://chat.hyperledger.org/channel/composer?msg=eT8eDYrv3qr2KsoyS)

## Your Environment
Version used:
* Hyperledger Fabric 1.1
* Hyperledger Composer 0.19.0

**Comment by jt-nti** [comment]
Looks like this was delivered in #3764
