### ISSUE TITLE
Cannot connect to REST Server through public IP after upgrade v0.19.0

### ISSUE THREAD

**Issue by skarlekar** [hyperledger/composer#3767]
I have Hyperledger Fabric running on an AWS EC2 instance.  After upgrading the Composer to v0.19.0 from v0.16,  I am unable to connect to the Composer REST server through the public IP of the EC2 instance. 

## Context
I have Hyperledger Fabric running on an AWS EC2 instance.  After upgrading the Composer to v0.19.0 from v0.16,  I am unable to connect to the **Composer REST server** through the public IP of the EC2 instance. 

I have reinstalled **composer-rest-server** and it now states it is running v0.19.0

Interestingly, I am able to connect to the server using CURL in a terminal window but I am not able to reach the server using the public IP from a browser. 

This was working normally with version 0.16 before the update.

FYI: I have the port 3000 open on my security group.

## Expected Behavior
Should be able to connect to the REST server.

## Actual Behavior
The site cannot be reached.

## Steps to Reproduce
1. Start EC2 instance.
2. Start the HLF using fabric-tools/startFabric.sh
3. Create an archive for the business network.
    `composer archive create -t dir -n ../`
4. Install the business network.
    `composer network install -a hello-bna@0.0.5.bna -c PeerAdmin@hlfv1`
5. Start the network
   ` composer network start -A admin -S adminpw -c PeerAdmin@hlfv1 -n hello-bna -V 0.0.6`
6. Start the composer REST server
    `composer-rest-server -n always -c admin@hello-bna`
7. Test with CURL - works
    `curl http://localhost:3000/explorer`
8. Test with public ip on a browser - does not work
    

## Your Environment

* Version used:
**composer: v0.19.0
composer-rest-server: v0.19.0**

* Operating System and version (desktop or mobile):
**Linux ip-171-31-86-167 4.4.0-1054-aws #63-Ubuntu SMP Wed Mar 28 19:42:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux**

**Comment by rajatwasan** [comment]
I am also facing the same issue.

**Comment by lesleyannjordan** [comment]
@skarlekar When you upgraded from composer 0.16.x to 0.19.0 I assume you also upgraded from fabric 1.0.5 to 1.1.0 GA?

**Comment by skarlekar** [comment]
@lesleyannjordan This problem was resolved after deleting the Local Storage on my browser. Now, I am able to connect. Thank you for responding. Much appreciated.

**Comment by vanishtachangea** [comment]
Hi @skarlekar, 
How did you solve this problem?
I have similar issue. I have run all the necessary commands for hyperledger as I did on my local, on an ec2 instance. I am supposed to get the rest server api : http://localhost:3000/explorer
However when I use the IP of the ec2 instance : http://<ip>3000/explorer, I get blank page. There is no error in console/debug mode.  

Thanks. 
Kind Regards, 
Vanishta
