### ISSUE TITLE
Error trying to enroll user or load channel configuration. Code: 20, Authorization Failure

### ISSUE THREAD

**Issue by ronaldlong46** [hyperledger/composer#3781]
## Context

In the Hyperledger Fabric Composer Playground, I have created a new business network under the sample network. When clicking "Connect now" after building said network, I am met with Error Code 20. (See below for full error.)

## Expected Behavior
I should be connected with the network.

## Actual Behavior
Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{"code":20,"message":"Authorization failure"}]]

## Your Environment

* Version used: v0.19.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node.js v8.11.1
* Operating System and version: Ubuntu 16.04

**Comment by kv5214** [comment]
+1
I got the same error as @ronaldlong46 . I think this error has something to do with the **Enrollment ID and Secret** configuration while creating a business network.

I gave 

**- Enrollment ID        : test-enrollment_id
- Enrollment Secret  : <a string value>**


Please find the terminal log below

Administrator@ubuntu:~/fabric-tools$ composer-playground --port 8081
info: [Hyperledger-Composer] undefined:LoadModule               :loadModule()              Loading composer-wallet-filesystem from /home/Administrator/.nvm/versions/node/v8.11.1/lib/node_modules/composer-playground/node_modules/composer-wallet-filesystem
info: [Hyperledger-Composer] undefined:PlaygroundAPI            :createServer()            Playground API started on port 8081
info: [Hyperledger-Composer] undefined:PlaygroundAPI            :createServer()            Client with ID 'nks4BGVI7lr0e0WiAAAA' on host '::ffff:127.0.0.1' connected
info: [Hyperledger-Composer] undefined:PlaygroundAPI            :createServer()            Client with ID 'GU84uv9_Va9K_XzHAAAB' on host '::ffff:127.0.0.1' connected
info: [Hyperledger-Composer] undefined:ConnectionProfileManager :connect()                 Connecting using hlfv1 0=tutorial-network
info: [Hyperledger-Composer] undefined:ConnectionProfileManager :getConnectionManagerByTyp Looking up a connection manager for type 0=hlfv1
info: [Hyperledger-Composer] undefined:ConnectionProfileManager :getConnectionManagerByTyp Using this connection manager
error: [Hyperledger-Composer] undefined:HLFConnection            :enroll()                  Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{"code":20,"message":"Authorization failure"}]]
    at caClient.enroll.then.then.then.then.catch (/home/Administrator/.nvm/versions/node/v8.11.1/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:218:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error: [Hyperledger-Composer] undefined:HLFConnection            :login()                   Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{"code":20,"message":"Authorization failure"}]]
    at caClient.enroll.then.then.then.then.catch (/home/Administrator/.nvm/versions/node/v8.11.1/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:218:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error: [Hyperledger-Composer] undefined:ConnectorServer          :Error: Error trying login
info: [Hyperledger-Composer] undefined:ConnectionProfileManager :connect()                 Connecting using hlfv1 0=tutorial-network
info: [Hyperledger-Composer] undefined:ConnectionProfileManager :getConnectionManagerByTyp Looking up a connection manager for type 0=hlfv1
error: [Hyperledger-Composer] undefined:HLFConnection            :enroll()                  Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{"code":20,"message":"Authorization failure"}]]
    at caClient.enroll.then.then.then.then.catch (/home/Administrator/.nvm/versions/node/v8.11.1/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:218:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error: [Hyperledger-Composer] undefined:HLFConnection            :login()                   Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{"code":20,"message":"Authorization failure"}]]
    at caClient.enroll.then.then.then.then.catch (/home/Administrator/.nvm/versions/node/v8.11.1/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:218:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error: [Hyperledger-Composer] undefined:ConnectorServer          :Error: Error trying login

**Comment by kv5214** [comment]
Came across this.. Posting here as it might resolve the issue

https://stackoverflow.com/questions/49453672/hyperledger-playground-credentials-for-network-administrator

**Comment by DipeekaPatil** [comment]
I am trying to connect network using composer SDK. I am getting same error when I try to create business network connection using custom store path. https://hyperledger.github.io/composer/latest/business-network/cloud-wallets

**Comment by gologo13** [comment]
I faced the same issue.

mac OS: High Sierra 10.13.4
composer: v0.19.9
node: v9.4.0

**Comment by utkarsh17ife** [comment]
I faced the same issue, i think it has something to do with the password we give in below command

composer network start --networkName someBusiness --networkVersion 0.2.6-deploy.14 --card PeerAdmin@hlfv1 --networkAdmin admin --**networkAdminEnrollSecret password**

here i gave the password for network admin as "password" which showed up in the network admin card metadata.json
{
    "version": 1,
    "userName": "admin",
    "businessNetwork": "someBusiness",
    "enrollmentSecret": "password"
}

But this gave "Authorization failure" when i tried connecting. So tried by changing the password to default, as shown below:
{
    "version": 1,
    "userName": "admin",
    "businessNetwork": "someBusiness",
    "enrollmentSecret": "adminpw"
}

and it got connected.

**Comment by TBigjohn** [comment]
Hello,
Same error on my side ... 
Composer network install -> ok
Composer network start -> ok
But impossible to connect composer using the generated card.

On my side metadata.json is ok,

**Comment by fcobello** [comment]
Hi

I was having the same error, during the debug I exported the problem card and compared to another card I had generated before, and I verified that the credentials disappeared from the problem card after removing and reimporting the card with the credentials and everything went back to to function

**Comment by kkrgithub** [comment]
Looks like Username: admin && enrolmentSecret  : adminpw are used to generate default passwords and keys so providing a different username and enrolmentSecret might not work.
And manually editing may not work since those may not be compiled so you have to execute the command
composer network start  --networkName [networkname]  --networkVersion [version]  --card PeerAdmin@hlfv1  --networkAdmin admin  --networkAdminEnrollSecret adminpw  --file networkadmin.card
Then remaining steps.
This worked for me.

**Comment by TBigjohn** [comment]
I found the following error on the log my ca container /

"Failed to get user: : scode: 404, code: 63, msg: Failed to get User: sql: no rows in result set"

**Comment by TBigjohn** [comment]
Hi,
I exported a bna file then 
Composer network install -> ok
Composer network start -> ok
But impossible to connect ( by clicking on the connect button of the corresponding card )
Apparently my certif authority doesn't know the user corresponding to the card created during th "network start command", which sounds logical 
Question is : How can I define this user within the certif authority container ??

Thanks

**Comment by jawahar273** [comment]
mee to.  even also if i try to add participants in the netowrk

**Comment by mallapurbharat** [comment]
There is a default NetworkAdmin pre-configured in the Hyperledger Composer installation with credentials 'admin' and 'adminpw' as secret.

Refer https://hyperledger.github.io/composer/v0.19/business-network/bnd-deploy.html where it specifies this... 

> A built-in participant type, org.hyperledger.composer.system.NetworkAdmin, representing a business network administrator is provided by Hyperledger Composer.This built-in participant type does not have any special permissions; they are still subject to the access control rules specified in the business network definition

If we try to use any other secret or change the name of the admin to say, 'Admin' , then we'll be unable to connect to the network and this gives the errors about 
`Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{"code":20,"message":"Authorization failure"}]]`

So when starting the network, use only credentials 'admin' and 'adminpw' as secret. Then there'll be no issues.

**Comment by davidkel** [comment]
Closing as no further activity and this is a usability issue rather than a bug in composer

**Comment by RameshThangamuthu** [comment]
I used the network admin card user and password as "admin" and adminpw and it worked. If I give as netadmin I am getting Authorization failure as stated in the thread

composer network start -c <peer admin card> -n myapp-bna -V 0.0.1 -A admin -S adminpw
