### ISSUE TITLE
Instructions on installing development tools lead to installation of v0.18

### ISSUE THREAD

**Issue by lsheks** [hyperledger/composer#3782]
## Context
I tried to reinstall composer following the directions in the 'Installing components' section of the tutorial.
I noticed that there was a revision such that the '@next' was added to many of the installations, e.g. 'npm install -g composer-cli@next'.  When I followed the directions using '@next' it led to installing v0.18 and I have already updated my code for v0.19. I reinstalled without '@next' and it worked.

It specifically states that the '@next' addition is to make sure the latest version is installed, but this isn't true.

## Expected Behavior
I would think it should install v0.19.

## Actual Behavior
It installs v0.18

##Environment
Ubuntu 16.04

**Comment by sstone1** [comment]
@lsheks please use the correct version of the documentation:
https://hyperledger.github.io/composer/latest/installing/development-tools
