### ISSUE TITLE
Tutorials should be tested automatically

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3784]
The tutorials are the first port of call for a new user. If a tutorial is broken, then a user will walk away ... we really don't want this.

We should automate the tutorial testing to ensure that they are always functional, based on the perspective of a user going through the documentation.

We need to:
 - Add tags into the docs for tutorials so that we can parse out required commands
 - Automate the extraction of the commands and run these in an environment to perform the intended action of the tutorial being targetted

The above is possible to achieve within CLI based integration tests (since we enable the ability to run command line commands) and Protractor.

We should concentrate initial efforts on:

- [ ] Developer tutorial
- [ ] Playground tutorial

**Comment by awjh-ibm** [comment]
PR #3859 implements this
