### ISSUE TITLE
CLI Report Integration Tests require extending

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3787]
Current CLI-Report integration test ensures that the command succeeds and produces a file. We could do with being a little more rigorous here:

- [ ] Run report, check for expected output in tar file not just that it exists
- [x] Run report with bad commands, check error message is sensible
- [ ] Repeat using dedicated npm module only (uninstall cli item)

**Comment by jt-nti** [comment]
Also need to revert @nklincoln's change in #3613 to skip composer-report tests

**Comment by davidkel** [comment]
Closing as no further tests are going to be written for node-report.
