### ISSUE TITLE
Get rid of "hlfv1" and "PeerAdmin" as a name from all samples, tutorials, and documentation

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#3801]
The blockchain network created by `fabric-dev-servers` is referred to using the name of `hlfv1`. 
This name is used all over the place, e.g. in the business network card `PeerAdmin@hlfv1`.
It appears as the connection profile name in the Composer Playground.
This name has been with us for a long time, and is internally the type of the connector used to connect to a Hyperledger Fabric v1.1+ blockchain network. 

We should rename this to something a bit more friendly. I would prefer `blockchain-network`, so that you get a business network card `PeerAdmin@blockchain-network`, but could also be convinced by `fabric-network`. 

The name `PeerAdmin` is also suspect, because that's something we made up - the name of this identity is actually `Admin@org1.example.com` (IIRC). This causes a lot of confusion - who is PeerAdmin, and do they have magical powers over the whole of the blockchain network? 

We should scrap `PeerAdmin` and call it something like `admin-org1` instead, so that you get a business network card `admin-org1@blockchain-network`. This demonstrates clearly that this is an administrator for a single organisation, and can easily be extended to `admin-org2@blockchain-network` for our multi-org tutorial.

**Comment by bestbeforetoday** [comment]
Only risk with _admin-org1@blockchain-network_ is that it's much less distinct from the network admin ID that usually gets created called something like _admin@trade-network_. Would it make sense to just be _admin-org1_?

I think I prefer just _fabric_ as as a suffix; the _-network_ on the end always seems a bit redundant. Failing that, I prefer _fabric-network_ to the generic _blockchain-network_.

 In general all sounds like a good idea. Certainly the current _hlfv1_ is not great.

**Comment by Weavor74** [comment]
Maybe using network-admin@fabric-network. That seems very authoritative to me. The person who runs this card is in control.

**Comment by asker2410** [comment]
yeah I agree,name it to something else.. when I installed fabric version hlfv12, the created card still has name hlfv1.  Thats confusing.
