### ISSUE TITLE
System namespace docs only talks about assets, participants and transactions, but there are event and enum sections 

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#3816]
on this page
https://hyperledger.github.io/composer/unstable/systemns/systemns-index
there is no coverage of enums or events.

**Comment by mbwhite** [comment]
These additional lines are needed at the bottom of 
`composer-documentation/_template/phase2a-jekyll/systemns-index.njk`


```
## Events

The system namespace events are:

- Event

## Enumerations

The system namespace enumerations are:

- IdentityState
```

**Comment by davidkel** [comment]
thanks @mbwhite. Fixed now.
