### ISSUE TITLE
Enable docker deploy of angular generated application integration test

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3818]
There was a recent modification to the angular generator to facilitate easier deployment of generated applications to Docker. 

With new functionality comes great test responsibility, and here it would be really neat to generate an application and actually perform the deploy to a docker container.

**Comment by davidkel** [comment]
As it has never been documented and given the poor state of the angular generator in general. I would say this feature doesn't exist and the Angular Generator does not provide a good example on how to write an angular application to communicate with the rest server and should not be used.
