### ISSUE TITLE
As a user, I need informative ACL syntax and semantic errors, so that I can accurately fix problems

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#382]
Need better exception messages (with location information) for syntactic and semantic errors in permissions.acl.

**Comment by m-g-k** [comment]
This also affects VSCode as most ACL errors currently end up highlighting the whole file as there is so little specific line/column info returned. There is a "composer-vscode-plugin" issue open that is blocked on this as well (#37)

**Comment by m-g-k** [comment]
This is not stale, it's just overlooked :-) It is still a problem and would like a fix!

**Comment by davidkel** [comment]
![image](https://user-images.githubusercontent.com/25582377/38933397-b5086b94-4310-11e8-8a57-ff833435b52f.png)

Specified Participant as "Any", rather than "ANY" and you get Failed to find namespace

**Comment by jt-nti** [comment]
Taking a look at this in https://github.com/jt-nti/hyperledger-composer/tree/382-acl-validation

Suggestions on what would be good to improve very welcome

**Comment by m-g-k** [comment]
Have a look at [](https://github.com/hyperledger/composer-vscode-plugin/issues/37) for a starter
