### ISSUE TITLE
Minor niggles in Angular Generator

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3826]
Usability issue:
- When I create an angular application, selecting to also create a REST server to connect to, when specifying the answer to 'use namespaces or not', the same question is displayed (but skipped over) in the console output.

**Comment by zachgoll** [comment]
@nklincoln I'm not able to reproduce this.  Has it been fixed in `v0.19.5`?

**Comment by KaiUsher** [comment]
Both @EllisHenderson and I cannot recreate this either so closing the issue.
