### ISSUE TITLE
As an end user I want to benefit from VSCode features when editing ACL files

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#383]
## Context
Extend the VSCode extension for Composer to also support the ACL grammar, providing syntax highlighting, code folding, snippets, validation etc.

## Expected Behavior
Open `permissions.acl` file in VSCode and get the features above.

## Actual Behavior
ACL files are not supported by the Composer plugin.

## Suggested Fix
The code to parse and validate an ACL is illustrated in the unit test:
`/fabric-composer/packages/composer-common/test/acl/aclfile.js`

```
const aclFile = new AclFile('test.acl', modelManager, testAcl);
```

**Comment by dselman** [comment]
To get good error message back we need to improve #382

**Comment by xufengli** [comment]
@caroline-church I have finished my other story now, so I assign this back to me so that I can work on.  Let me know if you need me to look at other items before this.

**Comment by caroline-church** [comment]
@xufengli I spoke to Dan on fri and the plan was to get you work with him on v1 items.

**Comment by m-g-k** [comment]
Hi @dselman . I'm happy to have a look at this one if you want to assign it to me...

**Comment by m-g-k** [comment]
FYI, I can't seem to assign this to myself, but as no one seems to be working on this, I've made a good start. All basics working OK, hopefully ready to commit next week

**Comment by sstone1** [comment]
@m-g-k can we close this?

**Comment by m-g-k** [comment]
Yes :-)
