### ISSUE TITLE
Expose underlying Fabric client API

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#3838]
## Abstract
Extend the Composer client APIs (admin connection and business network connection) to offer access to the underlying Fabric client API, or the client API for other underlying blockchain platforms.

## Motivation
Common questions from the community are:
- How do I see the blocks?!
- I really want to see the blocks! Tell me how can I see the blocks?
- What's the current block height?

Blocks are a technical thing and have nothing to do with business networks, which is why we have never done anything about wrapping the block information APIs.

However, the current recommendation to go and use the Fabric client APIs (including setting up your own connections) is painful for users, especially when they are using Composer and Fabric client APIs in the same application.

Exposing the underlying Fabric client API would be easy to add, and a quick win for our users.

## Specification
`AdminConnection` will be extended with the following method:

```javascript
    /**
     * Get the native API for this connection. The native API returned is specific
     * to the underlying blockchain platform, and may throw an error if there is no
     * native API available.
     * @return {*} The native API for this connection.
     */
    getNativeAPI() { ... }
```
`BusinessNetworkConnection` will be extended with the following method:

```javascript
    /**
     * Get the native API for this connection. The native API returned is specific
     * to the underlying blockchain platform, and may throw an error if there is no
     * native API available.
     * @return {*} The native API for this connection.
     */
    getNativeAPI() { ... }
```

The `getNativeAPI` method will return a fully configured instance of `Client` from the `fabric-client` npm module, which allows users to do something like the following:

```javascript
const bnc = new BusinessNetworkConnection();
await bnc.connect('admin@simons-network');
const fc = bnc.getNativeAPI();
const channel = fc.getChannel('defaultchannel');
const info = await channel.queryInfo();
console.log('block height', info.height);
```

## Rationale
Have reused the method name `getNativeAPI` as this is the same method name used in the transaction processor API to get access to the Fabric shim API. The name is generic and does not tie the Composer APIs to Fabric, and can be implemented for any underlying blockchain platform.

The `getNativeAPI` method will only return the Fabric client API, not the Fabric CA client API. All of the requirements that I have seen focus on stuff offered by the client API, and the Fabric CA client API is trivial to set up in comparison.

In future, if access to the Fabric CA client API is desired, we could add an optional `type` parameter to the method to say which one should be returned. 

## Backwards Compatibility
No backwards compatibility implications, and no major version bump required - new API can be safely added in the next possible patch release.

Using this new method will tie the client application to the underlying blockchain platform, and the client application may be subject to changes in the underlying client API. These risks will be documented.

## Test Requirements
Unit tests will be added for these new methods, along with functional tests that ensure they work within a client application.

## Implementation
New methods will be added as described above. The `getNativeAPI` method will be added to the internal connector API as part of the `Connection` class, and then implemented in all of our connector implementations.

## Copyright
This document is licensed under the Creative Commons Attribution 4.0 International Public License.

**Comment by sstone1** [comment]
Today you can do this to figure out the type of connection:

```javascript
const bnc = new BusinessNetworkConnection();
await bnc.connect('admin@my-network');
const card = bnc.getCard();
const runtimeType = card.getConnectionProfile()['x-type'];
```

It's a bit messy but is doable.

There's some documentation to do for this feature, but as part of that (so it fits in nicely) I think that the whole "developing applications" section needs an overhaul first. I'll tackle that.

**Comment by rodchen-king** [comment]
**### I add the following code to get block information.**

`await getNativeAPI().invokeChaincode(
    'qscc', 
    ['getBlockByTxID', "composerchannel", QueryTransaction.transactionId], 
    'composerchannel');`

**### but the response is wrong.**

`"{\"status\":500,\"message\":\"access denied for [getBlockByTxID][composerchannel]: [Unmapped policy for qscc/getBlockByTxID]\",\"payload\":{\"buffer\":{\"type\":\"Buffer\",\"data\":[]},\"offset\":0,\"markedOffset\":-1,\"limit\":0,\"littleEndian\":false,\"noAssert\":false}}"`

**### who can help us to find the root cause?**
