### ISSUE TITLE
Fabric transaction ID and Composer historian/transaction IDs not always equal

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#3839]
The Fabric transaction ID and Composer historian/transaction IDs are not always equal.
The `createTransactionId` magic is not specified in the following methods:

`AdminConnection.start`
`AdminConnection.reset`
`AdminConnection.activate`

May be limited to these three methods, or may affect other methods (in both admin and client APIs).

**Comment by sstone1** [comment]
@mbwhite can you look at this please?

**Comment by mbwhite** [comment]
This was resolved by https://github.com/hyperledger/composer/pull/3847
