### ISSUE TITLE
ACL Validation gives useless error and no line number

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#3843]
Specified Participant as "Any", rather than "ANY" and you get `Failed to find namespace`

![image](https://user-images.githubusercontent.com/25582377/38730883-32861486-3f10-11e8-903c-204ae87e0baf.png)

**Comment by jt-nti** [comment]
Looks like a duplicate of #382

**Comment by davidkel** [comment]
@jt-nti it looks like it, thanks. Will close this one.
