### ISSUE TITLE
Activate stale bot on composer repository

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#3855]
## Context

Lots of issues have been manually closed due to inactivity

## Expected Behavior

Composer issues should be a good reflection of what the community is interested in working on

## Actual Behavior

Some issues do get manually closed due to inactivity, but not all. Manually reviewing old issues is time consuming and only done on an ad hoc basis

## Possible Fix

Automate using https://github.com/apps/stale

**Comment by ryjones** [comment]
Stalebot is installed on composer* repos
