### ISSUE TITLE
As an end user I can delete model and script files

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#386]
We need to allow users to delete both model and script files from a business network definition, and redeploy the business network. We need to pay special attention to the validation of the business network during/after file deletion, to ensure we revalidate the whole lot.

**Comment by winslet** [comment]
Design for the placement of the delete icons here: https://xd.adobe.com/view/4ec4a582-6a0e-416a-ba88-ce2dbd7a4a80/screen/c6040686-509d-4c6c-a6c0-630694697157/Custom-Size-7

image of the above: 

![image](https://cloud.githubusercontent.com/assets/13980028/23707014/8b676404-0408-11e7-93e5-cf29aa22ec3a.png)

- Bin icon placed top left above codemirror. Hover state changes fill colour to $primary-text 

We should provide some kind of confirmation modal to ask whether that person *really* wants to delete said file. This should match the current "alert" modals we already have 👍

**Comment by EdMoffatt** [comment]
Assign to @Tobias-Hunter to provide the deletion modal mockup.

Note that in Sam's hifi screenshot, the name and path of the model file is displaying at the top of the screen.  This is not the current UI behaviour, where the Business Network name and version are shown on all screens.  That change is being tracked in #387

**Comment by Tobias-Hunter** [comment]
Deletion modal mockup Lo-Fi!

Click-through:
https://xd.adobe.com/view/db4b4d11-44b8-457a-af59-c1274eb5aba0/
.XD file:
https://ibm.box.com/s/duow1t2i7dnqts5qf9zpv2heipsmomf6

ONLY deletion modal mockup, action on deleting a file be it a model, script or access control!

Assigning @winslet for Hi-Fi's!

**Comment by winslet** [comment]
Simple flow of 3 screens:

### User selects delete icon in top right hand corner:

![fabric composer playground define 2 copy 60](https://cloud.githubusercontent.com/assets/13980028/24415733/5a1d3068-13da-11e7-956f-5749b0a2bc85.png)

### Error modal appears with information about the file they are looking to delete:

![fabric composer playground define 2 copy 61](https://cloud.githubusercontent.com/assets/13980028/24415755/70482596-13da-11e7-8fa0-0f679cb8d14a.png)

### When selecting delete they are returned to composer with a notification in the top right letting them know it has been done successfully:

![fabric composer playground define 2 copy 85](https://cloud.githubusercontent.com/assets/13980028/24415790/8db83c1a-13da-11e7-8901-2850b13ce6da.png)

#### New assets:

I believe the only new assets are that of the red delete button:

![image](https://cloud.githubusercontent.com/assets/13980028/24415824/a9f038b0-13da-11e7-9bf1-c152c229bc9e.png)

Colour on active: #E62325
Colour on hover: #AA231F 

**Marketch:** 
[Model_File_Script_Deletion_FC_SW_1.zip](https://github.com/fabric-composer/fabric-composer/files/876336/Model_File_Script_Deletion_FC_SW_1.zip)

**Comment by winslet** [comment]
@sstone1 is this something we can assign out?

**Comment by sstone1** [comment]
@caroline-church @bestbeforetoday please assign this out 😉

**Comment by nklincoln** [comment]
Picked up and working on this item now:
 
- Deletion modal complete

Now working on processing delete action and alert notification

**Comment by nklincoln** [comment]
Processing delete action and alert notification complete, working on adding tests

**Comment by nklincoln** [comment]
Following conversation with @EdMoffatt, we will permit the deletion of files that will invalidate the business network, however it will not be possible to deploy the resulting network.

Future tasks to be raised relating to:
 - Highlighting files that are in error state, to help provide guidance to users where any fixes are required. 
 - Enabling a roll-back to a previous version of the business network (ie a global 'undo')
