### ISSUE TITLE
Broken hyperlink in local setup

### ISSUE THREAD

**Issue by pranav-ranjan** [hyperledger/composer#3869]
Installed Hyperledger Composer Playground on mac. When I open it in the browser the links for Tutorial, Docs and Community is broken
Tutorial points to an inaccessible URL https://hyperledger.github.io/composer/next/tutorials/playground-tutorial.html

**Comment by lesleyannjordan** [comment]
With release 0.19.x there the link is https://hyperledger.github.io/composer/latest/tutorials/playground-tutorial.html
