### ISSUE TITLE
Integrate new logo into website and documentation

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#3871]
We have a new logo:

![hyperledger_composer_logo_color](https://user-images.githubusercontent.com/7118158/38983421-332eeff6-43bc-11e8-848f-3c11962da9fa.png)

We should put the new logo into the website and documentation as appropriate.

Assigning to @EdMoffatt + @winslet + @EdProsser initially.

**Comment by winslet** [comment]
@sstone1 have we got any more files? eg svgs etc..

**Comment by sstone1** [comment]
@winslet have sent an email to Greg Wallace from Hyperledger and CC'ed you.

**Comment by sstone1** [comment]
All logo files are in this ZIP file: [Composer_Logo.zip](https://github.com/hyperledger/composer/files/1928616/Composer_Logo.zip)
