### ISSUE TITLE
Cannot get started!

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#3873]
## Context

Using the hosted/online/bluemix playground in a browser that has previously deployed the 'Get Started' basic sample network successfully with a previous version of the playground.

## Expected Behavior

I expect (but don't like) the online playground complaining about old data and forcing me to confirm that I want to clear local storage. I should then be back to a clean state where I can play again.

## Actual Behavior

The 'Get Started' button does nothing, and no errors are shown in the UI.

The following error does appear in the console:

```
Error: Chaincode already installed: my-basic-sample@0.2.4-20180407084500
```

There are Composer, Concerto(!), and _pouch_Composer listed under the application's storage which I'm guessing do not get cleared out when the version check destroys the ID cards required to access the previously deployed basic sample network.

Clearing all the IndexedDB data and reloading the page fixes the problem.

## Possible Fix

Need to clear more than just the local storage

**Comment by sstone1** [comment]
Marking this as a P2 as leftover databases is a frequent pain to those running regular hands on labs and there's no way to resolve it without having to get intimate with your browser (dev console or rm -rf on disk databases). Clearing them out properly would be preferred, but maybe we could just ignore existing databases on deployment if we think they shouldn't be there.

**Comment by jt-nti** [comment]
Could prefix names of the databases with the playground version perhaps? Although that's going to result in a fair few databases getting left orphaned- mind you, they already build up pretty quickly with frequent updates and, as far as I know, never get cleaned up.

**Comment by jt-nti** [comment]
Plan B is to move all the business network data out of the separate pouch db into the existing 'Composer' database, enabling it to be more easily deleted. No more orphaned data cluttering up the browser, or causing issues with the 'Get Started' link.

**Comment by jt-nti** [comment]
@EdMoffatt the same problem can potentially happen for any business network. If it has been deployed before, it can get left behind when things are meant to get cleared up. I'm not 100% how it gets into the half-gone state though since I don't think it always happens.

Moving all the business network data into the same database, with a fixed name, should make the clean up much more reliable and fix all these sort of issues.

**Comment by caroline-church** [comment]
done so closing
