### ISSUE TITLE
Command to update .bna in composer v0.19.0

### ISSUE THREAD

**Issue by tejakiranrayudu** [hyperledger/composer#3876]
In Composer version 0.16.6 we have a command "composer network update -a xxx.bna --card xxx" 
 to update the existing .bna

What the same like command or any other way to update the existing .bna file to network in composer v0.19.0

**Comment by sstone1** [comment]
@tejakiranrayudu https://hyperledger.github.io/composer/latest/business-network/upgrading-bna

**Comment by mundipf** [comment]
This is very cumbersome during development. Are there any other more convenient ways, e.g. via restarting and without bumping up the version number?
