### ISSUE TITLE
Testing primitive Boolean with cucumber-js resolves "false" to true.

### ISSUE THREAD

**Issue by alanblyth** [hyperledger/composer#3878]
## Context
When creating some cucumber tests, I could not test a primitive on an asset for a false value, providing "false" in my test always expected a true.

## Expected Behavior
If "false" is provided in an asset value assertion, the expected value should be a false boolean.

## Actual Behavior
"false" is resolved true, and a true value is expected.

## Steps to Reproduce
1. Create a cucumber test that checks the value of a Boolean.
2. Set the Boolean to false, then check this value using "false".
3. Cucumber expects true.

## Existing issues
Related to:
- https://github.com/hyperledger/composer/issues/1693

## Context
Found that by providing empty spaces will resolve false, thereby working around the issue, eg:

```
    Scenario: Bob can submit a transaction for his assets
        When I use the identity bob1
        And I submit the following transaction of type org.acme.mynetwork.Transfuse
            | donation | receiver              |
            | 2        | alice@email.com       |
        Then I should have the following assets of type org.acme.mynetwork.Donation
            | donationId | owner           | available | quantityMl |
            | 2          | bob@email.com   |           | 20         |
        And I should have received the following event of type org.acme.mynetwork.SampleEvent
            | donation | receiver            |
            | 2        | alice@email.com     |
```

(available) is Boolean.

**Comment by sstone1** [comment]
Confirmed as a bug - this is not how you parse boolean strings:

`return new Boolean(value).valueOf();`
