### ISSUE TITLE
As an end user I can change the namespace in a model file

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#389]
We need to allow users to rename the namespace at the top of a model file. We need to pay special attention to the validation of the business network during/after namespace modifications, to ensure we revalidate the whole lot and highlight any errors - for example, if I change the namespace of a model file and don't change the references in a script or ACL file.

**Comment by sstone1** [comment]
@caroline-church @bestbeforetoday please could you find somebody to pick this up?

**Comment by nklincoln** [comment]
@EdMoffatt - my interpretation here is that if any files in the editor are placed into an error state, they will be decorated in some fashion to indicate that they are in error. Can you confirm, and if so, suggest any icons for use (or alternative highlighting method, such as the file name in red etc)?

**Comment by nklincoln** [comment]
Picking up this item now, the re-validation of all items in the business network definition was delivered as part of #386.

This could extend that aspect by an indicator of some sort should that be a design request.

**Comment by winslet** [comment]
Error notification on an access control list should look like this:

![image](https://cloud.githubusercontent.com/assets/13980028/26202323/e77d77c6-3bce-11e7-901f-fd14d2ea0176.png)

Hex code for the colour dot and text: #E62325

Circle is a 7x7px size, if easier as an SVG please see here:
```
<svg width="7px" height="7px" viewBox="0 0 7 7" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs></defs>
    <g id="v4.1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Error-dot" transform="translate(-224.000000, -358.000000)" fill="#E62325">
            <circle id="Oval-5" cx="227.5" cy="361.5" r="3.5"></circle>
        </g>
    </g>
</svg>
```
