### ISSUE TITLE
Provide tooling to help identify model migration 'hot-spots'

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#3910]
With a defined model in a CTO file, there are well defined rules that determine the impacts of changes. When a business network is updated, there is a chance that data could become inaccessible etc. 

These rules are defined in https://hyperledger.github.io/composer/latest//reference/model-compatibility

In terms of tool support I've drafted a prototype - available in a branch in my repo. 

This would be a great topic to get somebody from the community to help with.

**Comment by zachgoll** [comment]
@mbwhite What is the branch you have drafted this on called?
