### ISSUE TITLE
Queries with ORDER BY returns CouchDB Index error in Unit Test

### ISSUE THREAD

**Issue by nicolapaoli** [hyperledger/composer#3923]
## Context
I am receiving errors running the Unit Test of a query with the ORDER BY clause.

## Expected Behavior
Test should pass for both using or not the ORDER BY clause.

## Actual Behavior
The unit test returns the followiing error:
```
1) Commodity Trading #tradeCommodity should be able to trade a commodity:
     Error: Cannot sort on field(s) "\$class,\$registryType,\$registryId,quantity" when using the default index
```

## Steps to Reproduce
1. Clone `trade-network` from [Composer Sample Networks](https://github.com/hyperledger/composer-sample-networks)
2. Add clause `ORDER BY quantity` in the query `selectCommoditiesByExchange`.
It will look like this:
```
    query selectCommoditiesByExchange {
    description: "Select all commodities based on their main exchange"
        statement:
            SELECT org.example.trading.Commodity
                WHERE (mainExchange==_$exchange)
                    ORDER BY quantity
}
```
3. Run `npm test`

## Possible Fix
Queries with ORDER BY threw similar errors from the rest server, and now it is fixed. That issue [#3766](https://github.com/hyperledger/composer/issues/3766) has ben solved changing the order of the generated CouchDB Indexes. 

## Your Environment
* Version used: Composer v0.19.2

**Comment by nicolapaoli** [comment]
I am still receiving errors on the unit test. @andrew-coleman do you think this issue might have a similar solution to the [#3766](https://github.com/hyperledger/composer/issues/3766), which is the one solved sorting the generated Couch DB index?

**Comment by nicolapaoli** [comment]
Hi @andrew-coleman did you have any chance to look at this issue or do you have any suggestions on how to solve it?

**Comment by alexvicegrab** [comment]
Any progress on this @andrew-coleman

**Comment by davidkel** [comment]
Unfortunately PouchDB which is used to emulate CouchDB doesn't do a good job when it comes to handling indexes so it looks like at the moment the is no solution to this problem.

**Comment by alexvicegrab** [comment]
I guess a workaround will be to set up the tests to automatically ignore the ORDER BY clause, although this is not ideal.

**Comment by alexvicegrab** [comment]
For the time being, I have solved this by using sed on the query file before and after tests. Not ultra-elegant (suggestions welcome), but does the job:

https://github.com/PacktPublishing/Hyperledger-for-Blockchain-Applications/blob/master/section_6/landreg/package.json#L12
