### ISSUE TITLE
Add complex asset/participant functionality to Angular Generator

### ISSUE THREAD

**Issue by EllisHenderson** [hyperledger/composer#3927]
Please see issue #3136 for existing functionality and features within the angular generator.

As part of #3196 it was necessary to add some code to handle concepts, as if they were contained within your business network the angular generator failed to compile. 

This change was added as part of the improvement proposal mentioned above, however handling for assets/participants containing concepts was not.  

As a result of this you are able to generate an angular app with a business network containing concepts but not able to create an asset or participant containing a concept. The expected result when trying to do this is `internal server error 500` however there are some known cases where the asset or participant will be created, with the fields showing `[object Object]` The most noticeable case of this is when creating an asset or participant directly through the REST server. 

Before the above is possible, handling of relationships will have to be implemented along with a way of detecting whether or not an asset/participant contains a concept. If a concept is detected, the current angular input form should be replaced with a JSON box to account for the multiple fields that would potentially have to be entered within the field containing the concept.

**Comment by EllisHenderson** [comment]
Reopening as still relevant.

**Comment by davidkel** [comment]
closing as not relevant for the generator sample
