### ISSUE TITLE
Response from attempted peer comms was an error: Error: 2 UNKNOWN: Unknown chaincodeType: NODE

### ISSUE THREAD

**Issue by sauravrana1983** [hyperledger/composer#3941]
Unable to install .BNA using composer CLI version 0.19.3.
Trying to install this on Azure Hyper ledge set up with one membership node, one ordered node and 2 peer node in the same subnet. Added a Ubuntu VM in same subnet hosting the composer runtime.

composer network install -c PeerAdmin@azure-demo -a test@0.0.1.bna

Error: Response from attempted peer comms was an error: Error: 2 UNKNOWN: Unknown chaincodeType: NODE

**Comment by davidkel** [comment]
Composer 0.19 only works with Hyperledger Fabric 1.1. The error you are getting says you are trying to use Hyperledger Fabric 1.0 (HLF 1.0 doesn't support node.js chaincode) which won't work
