### ISSUE TITLE
yo hyperledger-composer doesn't work. 

### ISSUE THREAD

**Issue by pathfinder2104** [hyperledger/composer#3943]
While trying to generate an Angular2 application the *`yo hyperledger-composer`* doesn't work at all. I have tried *`yo hyperledger-composer:angular`* as well. It fails with following error. 

seems like some internal problem with code. Pardon me I am very new to NodeJS programming. 

## Expected Behavior
It should generate a scaffolding for the angular2 application.

## Actual Behavior
It fails as shown below
```JAVASCRIPT
ayush@ayush-VirtualBox:~/DemoApp$ sudo yo hyperledger-composer
/usr/lib/node_modules/generator-hyperledger-composer/node_modules/composer-common/lib/cardstore/businessnetworkcardstore.js:54
    async get(cardName) {
          ^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/generator-hyperledger-composer/node_modules/composer-common/index.js:56:43)
```

## Steps to Reproduce
Go to this page https://www.npmjs.com/package/generator-hyperledger-composer
1.Install all the dependencies required. 
2. then run "yo hyperledge-generator" and notice the output as mentioned above.

## Context
I am unable to generate a scaffolding for the application which will interact with the Hyperledger Fabric blockchain. 

## Environment
Ubuntu - 16.04LTS

**Update**
Is this an older version that I am referring to? Is it possible to use & generate angular4/5 based application using composer? Because as per the composer website it seems to have different information. I am bit confused.

**Comment by sstone1** [comment]
@pathfinder2104 you do not have Node.js 8 installed; please see the pre-req information here:
https://hyperledger.github.io/composer/latest/installing/installing-prereqs

Please ensure you do not use root/sudo to install Node.js or any npm modules. We strongly suggest that you use nvm (the Node Version Manager) to install Node.js.

**Comment by pathfinder2104** [comment]
Thanks for quick feedback +1
