### ISSUE TITLE
Winston logger causes error

### ISSUE THREAD

**Issue by kOstovic** [hyperledger/composer#3952]
Alright so I used browserify to bundle up "composer-client" so I can use it in frontend(as there are no documentation this is the best I could figure out). 
Everything is in file 

/composer-common/lib/log/logger.js

However browserify cant "Cannot find module './winstonInjector.js'" altho there is some trick used in a code for it to find as far a I see
in function
static processLoggerConfig(localConfig,replace=false){
...
            // This weird code is needed to trick browserify.
            process.env.SUPPRESS_NO_CONFIG_WARNING = 'y';
            const mod = 'config';
            const req = require;
            const config = req(mod);

however 
it doesnt work in function static _loadLogger(localConfig)

## Expected Behavior
bundle should work without any problems

## Actual Behavior
bundleComposer.js:87514 Failed to load logger module ./winstonInjector.js: Cannot find module './winstonInjector.js'

atho in bundle there is winstonInjector bundled up

## Steps to Reproduce
make browserify bundle of script which include 
const BusinessNetworkConnection = require('composer-client').BusinessNetworkConnection;
so you can call transactions through composer-client module directly in browser

## Existing issues
Seems this is a bug for some time now, unreported here
https://stackoverflow.com/questions/46666884/unable-to-dynamically-load-npm-modules-in-ionic

## Context
I want to check few input parameters from webpage form and based on that call transaction of my choice without mending with angular app
https://raw.githubusercontent.com/kOstovic/diplomskiHyperledger/master/angular-app-wons/src/bundleComposer.js

my current bundle

## Your Environment
node 8.9.11 
browserify latest 
composer 0.19.4

**Comment by jt-nti** [comment]
This error shows up in the console log when running the playground as well

**Comment by hammadsaeed** [comment]
Any updates on this error I am still getting it

**Comment by jeydi243** [comment]
Please someone find solution?
