### ISSUE TITLE
REST API query double parametar problem

### ISSUE THREAD

**Issue by kOstovic** [hyperledger/composer#3961]
I have wrote a query like this

query selectIsOpened {
  description: "Query is particular collage in working time"
  statement:
      SELECT org.szg.UniversityComponent
        WHERE (_$universityKeyparam == universityKey AND _$timeparam >= opening AND _$timeparam <= closing)       
}

Hyperledger Composer REST server module on frontend expect timeparam to be written twice although its same parameter and ofc. when you put 2 times, it results in user side(400) error, more info in SS
## Expected Behavior

There should be only 1 box for parameter if it is used twice
## Actual Behavior

You have to put same parameter twice which results in 400 error
## Possible Fix
change RESTwebpage frontend so it figures out when 2 parameters in query are same

## Steps to Reproduce
try to make query that uses same parameter 2 times

https://ibb.co/dR10w7
https://ibb.co/efuLw7
https://ibb.co/jVJxb7

## Your Environment
composer 0.19.4 
node 8.9.11

**Comment by sstone1** [comment]
QueryAnalyzer needs fixing to avoid returning duplicate parameters of the same name, and _somewhere_ we need to validate that if we have multiple parameters of the same name they all are the same type (e.g. can't have `doubleValue == _$param && stringValue == _$param`).

**Comment by alexvicegrab** [comment]
Seeing the same behaviour. Current dirty fix is using multiple parameter names for the same parameter, but would be good to get it fixed.

**Comment by alexvicegrab** [comment]
In fact, the issue is more on the explorer side, not on the actual REST API. From the images and my experience it's the call that is wrong, since we see:

```timeparam=0&timeparam=0```

at the end of the `curl` string.

**Comment by alexvicegrab** [comment]
Latest pull request should solve this problem, so this issue can be closed.
