### ISSUE TITLE
Issue Identifier without cli

### ISSUE THREAD

**Issue by mataide** [hyperledger/composer#3967]
## Feature
How do I set an identifier without cli?

## Expected Behavior
I would do like to programatically issue an identifier without cli.

## Actual Behavior
At moment, every time that I try to make a transaction, I got this error:

`"Error trying to ping. Error: Error trying to query business network. Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier '29ab231d7527bdad3784fc6ea332f401e4fa493f1721d7b96621cacde5e34149', has not been registered"`

The identifier number changes on every request.

## Context
I am building my on API, not using Composer REST API.

## Your Environment
* Link to your project: https://github.com/mataide/serverless-hyperledger

**Comment by zachgoll** [comment]
By the looks of it, you are not providing the correct params for a few of the API functions.  In your `match.js` file, you have the following code: 

```
const idCardData = new IdCard("metadata", "connection");

    const idCardName = BusinessNetworkCardStore.getDefaultCardName(idCardData);
    try{
      const imported = await this.adminConnection.importCard(idCardName, idCardData);
      if (imported) {
        this.businessNetworkDefinition = await this.bizNetworkConnection.connect(idCardName);
```

First off, I don't think you can create a new IdCard how you have done it.  Here is one way to do it: 

```
    const connectionProfile = {
        name: 'embedded',
        'x-type': 'embedded'
    };

    const deployerMetadata = {
        version: 1,
        userName: 'PeerAdmin',
        roles: ['PeerAdmin', 'ChannelAdmin']
    };

const idCardData = new IdCard(deployerMetadata, connectionProfile);
```

Secondly, you are providing the arguments in the wrong order for the connection profile.  It should be:

```
const imported = await this.adminConnection.importCard(idCardName, idCardData);
```

**Comment by mataide** [comment]
@zachgoll , 

I am using this structure for the metadata:

```
const metadata = {
   userName: userID,
   version: hlfVersion,
   enrollmentSecret: enrollSecret,
   businessNetwork: networkName
};
```
I got this error when I tried yours:

`[200] {"statusCode":200,"body":"{\"status\":false,\"data\":{},\"error\":{\"status\":200,\"title\":\"Request Done\",\"detail\":{\"5\":\"Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{\\\"code\\\":20,\\\"message\\\":\\\"Authorization failure\\\"}]]\"}}}"}`

And for the connection profile I use the fully JSON with all the channels and certification and the `"x-type": "hlfv1"`

The order, you put the same. Didn't understand.

**Comment by zachgoll** [comment]
@mataide My example should not work for your particular case.  I was just giving an example since you had used two strings as the parameters for the newly created card.  If you want to see an example of how to generate a card which connects to a given instance of HL Fabric, I would checkout the  [createPeerAdminCard.sh script for hlfv11](https://github.com/hyperledger/composer-tools/blob/master/packages/fabric-dev-servers/fabric-scripts/hlfv11/createPeerAdminCard.sh) 

In regard to the importCard option, I must have just been tired looking at or seeing this error in my own files because I'm looking at it now wondering why I had mentioned :)

**Comment by marckaraujo** [comment]
@zachgoll , of course that I am not using that strings, I wont upload my own credentials to github.

I know how to create the connection profile from Fabric, and this works pretty well with REST SERVER API.

But back to the original question, all that you said at moment dont solve the problem.

**Comment by davidkel** [comment]
Please could you raise this on stackoverflow as github issues are for bug reports and enhancement requests and unfortunately this isn't either of them, but an issue with your code.
