### ISSUE TITLE
problem with async function

### ISSUE THREAD

**Issue by VarunLashkari** [hyperledger/composer#3968]
problem with async function
## Context

problem with async function while i am running the new-patient-network.bna that is having a async function in lib folder in the logic.js file on line 24 
## Expected Behavior
the composer network should get deployed

## Actual Behavior
dist/new-patient-network.bna
SyntaxError: Failed to parse lib/logic.js: Unexpected token (24:6)

## Steps to Reproduce

1.try to deploy pii-network example locally using composer network deploy.
2.or [new-patient-network.zip](https://github.com/hyperledger/composer/files/1973381/new-patient-network.zip)
3.
4.

## Existing issues

https://github.com/hyperledger/composer/issues/3301 this was closed using an older version but it rises again in newer version.

https://github.com/hyperledger/composer/issues/1680

## Your Environment

* Version used:hlfv1
* Environment name and version (e.g. Chrome 39, node.js 5.4):node -v
v8.11.1

* Operating System and version (desktop or mobile):UBUNTU 16.04
* Link to your project:

**Comment by davidkel** [comment]
@VarunLashkari Can you confirm you are using composer 0.16.x and HLF 1.0 ? I am guessing you are which means `async` is not supported. All our samples (master branch) and documentation (latest) refer to our must recent release which supports async. If you plan on continuing to use 0.16.x and HLF 1.0 then you will need to use promise chains, not async.

**Comment by davidkel** [comment]
Closing as almost certain this is using 0.16.x release of composer.
