### ISSUE TITLE
Ubuntu startFabric Error 0.19.1

### ISSUE THREAD

**Issue by tanhuiya** [hyperledger/composer#3971]
Env:

 - Ubuntu 16.04.3 LTS
 - Hyperledger Composer 0.19.1

When I use `./startFabric.sh` command to start a network.
The peer0.org1.example.com container cann't startUp. Show warnning below:

`2018-05-06 01:32:11.118 UTC [couchdb] handleRequest -> WARN 016 Retrying couchdb request in 125ms. Attempt:1  Error:Get http://couchdb:5984/: dial tcp 172.18.0.4:5984: getsockopt: connection refused`

I have try adding `dns_search:.` option in composer file, but it not works.

**Comment by kOstovic** [comment]
post output from this command, if you get "there are no containers named like that" try something i wrote in second paragrapgh
docker logs couchdb

couchdb docker image isnt online, try to get only docker image up for couchdb by copying that part in new docker-compose-couch.yaml and running: 
docker-compose -f docker-compose-couch.yaml up -d

there should be logs why couch isnt running
ps try to update to composer version 0.19.4 first plz



version: '2'

services:
  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb:$ARCH-0.4.6
    ports:
      - 5984:5984
    environment:
      DB_URL: http://localhost:5984/member_db

**Comment by tanhuiya** [comment]
It's a problem of Aliyun

**Comment by shniu** [comment]
@tanhuiya I have encountered a similar problem. Is it really a problem with Aliyun? How did you solve it?

as bellow:

```
2018-11-12 09:18:50.998 UTC [couchdb] handleRequest -> WARN 007 Retrying couchdb request in 1s. Attempt:4  Error:Get http://couchdb:5984/: dial tcp 172.19.0.3:5984: connect: connection refused
```

I have this problem when I deployed Fabric on Alibaba Cloud, which is good in my local environment.

**Comment by shniu** [comment]
I found an answer, and it works for me, see https://yq.aliyun.com/articles/238940
