### ISSUE TITLE
Error using composer card import 

### ISSUE THREAD

**Issue by bsanil68** [hyperledger/composer#3972]
Hi ,

I  am trying to integrate  composer  on to  a  Fabric topology  on Google  cloud  VPC , i have  a orderer vm, two pears and  one vm for each  and  a  vm for  composer  and  CA  ..     The  orderer and  peers  as well as  CA  have started  without issues  and i   am using  configtx.yaml, core.yaml for peers and ordrerer.yaml with  configtx to generate channels and  genesis  pb  block .  I am  able to  generate a  card  with  cryptogen generated  certificates  . But while  trying to import  card   i am getting  a  error  .

Here  is the  error  
 composer card import --file /home/asrikantiah/PeerAdmin
@decimus-network.card  --card PeerAdmin@decimus-network                         
Failed to import identity. Error: Client.createUser parameter 'opts mspid' is required.
Command failed
I  have  the  ORG MSP   defined  in all VM  to  reflect the  Org user msp and id  ....  I know this is related to identity  but not able   figure  out what  triggers  this  . Anybody has a  hint  , please  help . should i issue   a  new  identity , bind the  identity and then  do a  install  .......

**Comment by sstone1** [comment]
@bsanil68 please provide the connection profile, and `composer card create` command line used to create the file `PeerAdmin@decimus-network.card`.
