### ISSUE TITLE
 Have been successfully solved ：composer network start 0.19  Error: REQUEST_TIMEOUT 

### ISSUE THREAD

**Issue by wfcz10086** [hyperledger/composer#3974]
I set it as follows and I can't succeed

CORE_CHAINCODE_STARTUPTIMEOUT=2400s
CORE_CHAINCODE_EXECUTETIMEOUT=2400s

https://github.com/hyperledger/composer/issues/3731
https://developer.ibm.com/answers/questions/441724/unable-to-add-new-participants-to-a-deployed-busin.html?childToView=442489#answer-442489

I've looked at the two URL links above

================================================================================
==== Node Report ===============================================================

Event: exception, location: "OnUncaughtException"
Filename: node-report.20180507.204412.20184.001.txt
Dump event time:  2018/05/07 20:44:12
Module load time: 2018/05/07 20:42:32
Process ID: 20184
Command line: node /home/.nvm/versions/node/v8.11.1/bin/composer network start -c PeerAdmin@byfn-network-org1 -n trctoken -V 1.0.1 -o endorsementPolicyFile=/tmp/composer/endorsement-policy.json -A org1 -C org1/admin-pub.pem -A org2 -C org2/admin-pub.pem -A org3 -C org3/admin-pub.pem -o npmrcFile=npmConfig.txt 

Node.js version: v8.11.1
(http_parser: 2.8.0, v8: 6.2.414.50, uv: 1.19.1, zlib: 1.2.11, ares: 1.10.1-DEV,
 modules: 57, nghttp2: 1.25.0, openssl: 1.0.2o, icu: 60.1, unicode: 10.0,
 cldr: 32.0, tz: 2017c)

node-report version: 2.2.1 (built against Node.js v8.11.1, glibc 2.17, 64 bit)

OS version: Linux 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017
(glibc: 2.17)

Machine: izbp1hmnfysx1cdkogh4xnz x86_64

================================================================================
==== JavaScript Stack Trace ====================================================

WriteStream.emit (events.js:1:1)
onwriteError (_stream_writable.js:1:1)
onwrite (_stream_writable.js:1:1)
_destroy (internal/streams/destroy.js:1:1)
WriteStream.stderr._destroy (internal/process/stdio.js:1:1)
WriteStream.destroy (internal/streams/destroy.js:1:1)
WriteWrap.afterWrite [as oncomplete] (net.js:1:1)

================================================================================
==== Native Stack Trace ========================================================

 0: [pc=0x7f694a7bf1a3] nodereport::OnUncaughtException(v8::Isolate*) [/home/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/node-report/api.node]
 1: [pc=0xf1c332] v8::internal::Isolate::Throw(v8::internal::Object*, v8::internal::MessageLocation*) [node]
 2: [pc=0x1094a5d] v8::internal::Runtime_Throw(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 3: [pc=0x1dc4c76842fd] 

================================================================================
==== JavaScript Heap and Garbage Collector =====================================

Heap space name: new_space
    Memory size: 1,048,576 bytes, committed memory: 555,152 bytes
    Capacity: 1,031,168 bytes, used: 550,776 bytes, available: 480,392 bytes
Heap space name: old_space
    Memory size: 32,829,440 bytes, committed memory: 31,466,488 bytes
    Capacity: 32,058,000 bytes, used: 29,259,320 bytes, available: 2,798,680 bytes
Heap space name: code_space
    Memory size: 2,097,152 bytes, committed memory: 1,669,664 bytes
    Capacity: 1,840,384 bytes, used: 1,516,640 bytes, available: 323,744 bytes
Heap space name: map_space
    Memory size: 4,214,784 bytes, committed memory: 4,047,312 bytes
    Capacity: 4,136,096 bytes, used: 1,383,976 bytes, available: 2,752,120 bytes
Heap space name: large_object_space
    Memory size: 2,834,432 bytes, committed memory: 2,834,432 bytes
    Capacity: 1,459,219,672 bytes, used: 2,789,080 bytes, available: 1,456,430,592 bytes

Total heap memory size: 43,024,384 bytes
Total heap committed memory: 40,573,048 bytes
Total used heap memory: 35,499,792 bytes
Total available heap memory: 1,462,785,528 bytes

Heap memory limit: 1,501,560,832

================================================================================
==== Resource Usage ============================================================

Process total resource usage:
  User mode CPU: 1.850934 secs
  Kernel mode CPU: 0.137555 secs
  Average CPU Consumption : 1.98849%
  Maximum resident set size: 115,822,592 bytes
  Page faults: 2 (I/O required) 48457 (no I/O required)
  Filesystem activity: 3904 reads 32 writes

Event loop thread resource usage:
  User mode CPU: 1.523905 secs
  Kernel mode CPU: 0.107905 secs
  Average CPU Consumption : 1.63181%
  Filesystem activity: 3904 reads 16 writes

================================================================================
==== Node.js libuv Handle Summary ==============================================

(Flags: R=Ref, A=Active)
Flags  Type      Address             Details
[-A]   async     0x0000000002ad72d0  
[--]   check     0x00007fffdbffd910  
[R-]   idle      0x00007fffdbffd988  
[--]   prepare   0x00007fffdbffda00  
[--]   check     0x00007fffdbffda78  
[-A]   async     0x00000000021846a0  
[R-]   timer     0x0000000002b5f2e0  repeat: 0, timeout expired: 25400306 ms ago
[R-]   tty       0x0000000002b5faa8  , stdout, write queue size: 0, writable
[-A]   signal    0x0000000002b48260  signum: 28 (SIGWINCH)
[R-]   tty       0x0000000002b48458  , stderr, write queue size: 0, writable
[-A]   async     0x00007f694a9c6ce0  
[-A]   signal    0x0000000002be04d0  signum: 6 (SIGABRT)
[-A]   signal    0x0000000002be6750  signum: 14 (SIGALRM)
[-A]   signal    0x0000000002be8a70  signum: 1 (SIGHUP)
[-A]   signal    0x0000000002b6db10  signum: 2 (SIGINT)
[-A]   signal    0x0000000002bd6ac0  signum: 15 (SIGTERM)
[-A]   signal    0x0000000002be5c40  signum: 26 (SIGVTALRM)
[-A]   signal    0x0000000002be5d30  signum: 24 (SIGXCPU)
[-A]   signal    0x0000000002c2cc80  signum: 25 (SIGXFSZ)
[-A]   signal    0x0000000002c2cd70  signum: 12 (SIGUSR2)
[-A]   signal    0x0000000002c20b40  signum: 5 (SIGTRAP)
[-A]   signal    0x0000000002c20c30  signum: 31 (SIGSYS)
[-A]   signal    0x0000000002b82480  signum: 3 (SIGQUIT)
[-A]   signal    0x0000000002b82570  signum: 6 (SIGABRT)
[-A]   signal    0x0000000002b82660  signum: 29 (SIGIO)
[-A]   signal    0x0000000002b82750  signum: 29 (SIGIO)
[-A]   signal    0x0000000002b91940  signum: 30 (SIGPWR)
[-A]   signal    0x0000000002b91a30  signum: 16 (SIGSTKFLT)
[-A]   signal    0x0000000002b81e70  signum: 31 (SIGSYS)
[RA]   timer     0x0000000002be4d30  repeat: 0, timeout in: 80 ms
[R-]   timer     0x0000000002bc97e0  repeat: 0, timeout expired: 98528 ms ago
[-A]   async     0x00007f69487ada58  
[R-]   timer     0x0000000002bd1940  repeat: 0, timeout expired: 25399218 ms ago
[RA]   prepare   0x00007f69487ad980  
[R-]   timer     0x0000000002c1cfb0  repeat: 0, timeout in: 26740556560362621 ms
[-A]   tcp       0x0000000002c260e0  zookeeper0:34634 connected to zookeeper0:7051, send buffer size: 87040, recv buffer size: 1061296, file descriptor: 10, write queue size: 0, readable, writable
[-A]   tcp       0x0000000002c27570  zookeeper0:57238 connected to zookeeper0:8051, send buffer size: 87040, recv buffer size: 1061296, file descriptor: 11, write queue size: 0, readable, writable
[-A]   tcp       0x0000000002bc0290  zookeeper0:50678 connected to zookeeper1:7051, send buffer size: 87040, recv buffer size: 367360, file descriptor: 12, write queue size: 0, readable, writable
[-A]   tcp       0x0000000002bbf550  zookeeper0:35892 connected to zookeeper1:8051, send buffer size: 87040, recv buffer size: 367360, file descriptor: 13, write queue size: 0, readable, writable
[-A]   tcp       0x0000000002bc3ca0  zookeeper0:51488 connected to zookeeper2:7051, send buffer size: 87040, recv buffer size: 367360, file descriptor: 14, write queue size: 0, readable, writable
[-A]   tcp       0x0000000002c0c790  zookeeper0:34950 connected to zookeeper2:8051, send buffer size: 87040, recv buffer size: 367360, file descriptor: 15, write queue size: 0, readable, writable
[-A]   tcp       0x0000000002c11550  zookeeper0:34646 connected to zookeeper0:7051, send buffer size: 87040, recv buffer size: 2226507, file descriptor: 16, write queue size: 0, readable, writable
[-A]   timer     0x0000000002d5b4f0  repeat: 0, timeout in: 261410 ms
[-A]   timer     0x0000000002c7b140  repeat: 0, timeout in: 261410 ms
[-A]   timer     0x0000000002c96c10  repeat: 0, timeout in: 261410 ms
[-A]   timer     0x0000000002d0abe0  repeat: 0, timeout in: 261410 ms
[-A]   timer     0x0000000002cb5500  repeat: 0, timeout in: 261410 ms
[-A]   timer     0x0000000002cf7c20  repeat: 0, timeout in: 261412 ms
[RA]   timer     0x0000000002caa3c0  repeat: 0, timeout in: 201442 ms
[-A]   tcp       0x0000000002bfcce0  zookeeper0:57250 connected to zookeeper0:8051, send buffer size: 87040, recv buffer size: 1061296, file descriptor: 17, write queue size: 0, readable, writable
[-A]   tcp       0x0000000002d2d340  zookeeper0:50690 connected to zookeeper1:7051, send buffer size: 87040, recv buffer size: 367360, file descriptor: 18, write queue size: 0, readable, writable
[-A]   tcp       0x0000000002db3090  zookeeper0:35904 connected to zookeeper1:8051, send buffer size: 87040, recv buffer size: 367360, file descriptor: 19, write queue size: 0, readable, writable
[-A]   tcp       0x0000000002db2210  zookeeper0:51500 connected to zookeeper2:7051, send buffer size: 87040, recv buffer size: 367360, file descriptor: 20, write queue size: 0, readable, writable
[-A]   tcp       0x0000000002e6f1b0  zookeeper0:34962 connected to zookeeper2:8051, send buffer size: 87040, recv buffer size: 367360, file descriptor: 21, write queue size: 0, readable, writable
[-A]   timer     0x0000000002b542f0  repeat: 0, timeout in: 694 ms

================================================================================
==== System Information ========================================================

Environment variables
  XDG_SESSION_ID=1
  HOSTNAME=izbp1hmnfysx1cdkogh4xnz
  NVM_CD_FLAGS=
  SHELL=/bin/bash
  TERM=xterm
  HISTSIZE=1000
  OLDPWD=/home
  NVM_DIR=/home/.nvm
  USER=hyper
  LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
  MAIL=/var/spool/mail/hyper
  PATH=/home/.nvm/versions/node/v8.11.1/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/.local/bin:/home/bin
  PWD=/home
  LANG=en_US.UTF-8
  HISTCONTROL=ignoredups
  SHLVL=1
  HOME=/home
  LOGNAME=hyper
  NVM_BIN=/home/.nvm/versions/node/v8.11.1/bin
  LESSOPEN=||/usr/bin/lesspipe.sh %s
  _=/home/.nvm/versions/node/v8.11.1/bin/composer
  SUPPRESS_NO_CONFIG_WARNING=y
  GRPC_SSL_CIPHER_SUITES=ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384

Resource limits                        soft limit      hard limit
  core file size (blocks)                       0       unlimited
  data seg size (kbytes)                unlimited       unlimited
  file size (blocks)                    unlimited       unlimited
  max locked memory (bytes)                 65536           65536
  max memory size (kbytes)              unlimited       unlimited
  open files                                65535           65535
  stack size (bytes)                      8388608       unlimited
  cpu time (seconds)                    unlimited       unlimited
  max user processes                         4096           31215
  virtual memory (kbytes)               unlimited       unlimited

Loaded libraries
  /lib64/libdl.so.2
  /lib64/librt.so.1
  /lib64/libstdc++.so.6
  /lib64/libm.so.6
  /lib64/libgcc_s.so.1
  /lib64/libpthread.so.0
  /lib64/libc.so.6
  /lib64/ld-linux-x86-64.so.2
  /home/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/node-report/api.node
  /home/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node
  /lib64/libnss_files.so.2

**Comment by josh-fodale** [comment]
It's still timing out after 2400s?  Or it times out prior to reaching 2400s?

**Comment by wfcz10086** [comment]
@josh-fodale after

**Comment by codefull** [comment]
For me it almost always fail before reaching 2400s

**Comment by wfcz10086** [comment]
Have been successfully solved：
step1：
Create a new file npm.yaml：
##############
version: '2'
services:
  npmregistry:
    container_name: npmregistry
    image: verdaccio/verdaccio
    volumes:
      - /home/repo:/verdaccio/storage/
    ports:
      - 4873:4873
##############
stp2： docker-compose -f npm.yaml up -d
stp3：Create a new file npmConfig.txt：
#########
registry=http://xxxxx:4873/
############

stp4：composer network install --card PeerAdmin@byfn-network-org1 --archiveFile trctoken\@1.0.1.bna -o npmrcFile=npmConfig.txt 
composer network start -o npmrcFile=npmConfig.txt -c PeerAdmin@byfn-network-org1 -n trctoken -V 1.0.1 -o endorsementPolicyFile=/tmp/composer/endorsement-policy.json -A org1 -C org1/admin-pub.pem -A org2 -C org2/admin-pub.pem -A org3 -C org3/admin-pub.pem
.........


Please refer to the above steps in detail！
The whole problem is caused by compiling the container "dev.dev-peerx.orgx.example.com"; downloading the NPM dependent packet is too long.

**Comment by rthatcher** [comment]
Good news this is solved.
The knowledge wiki covers `composer network start` problems too:
https://github.com/hyperledger/composer-knowledge-wiki/blob/latest/knowledge.md#startissues[https://github.com/hyperledger/composer-knowledge-wiki/blob/latest/knowledge.md#startissues](url)
