### ISSUE TITLE
DOCs build is failing :(

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3977]
Currently the docs build is failing in Travis at the deploy build stage

This is a bit problematic, since without that the CRON job will never pass 😿 

It does not appear to be a problem with PR builds, but we do need to investigate and solve this

**Comment by sstone1** [comment]
Caused by PR #3920, but legitimately. JSDoc used to stick timestamps in all the generated API documentation, which meant the docs changed on every build, so this was never a problem. Will add changes to check for changes and only try to push if there are some.
