### ISSUE TITLE
Remove Google Analytics from cloud playground

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#3978]
Brace yourselves, GDPR is coming.
Nobody wants to tell us what to do with regards to GDPR and Google Analytics.
So let's remove Google Analytics.

**Comment by jt-nti** [comment]
Looks like https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#anonymizeIp would be a useful option if we want to start using Google Analytics again at some point

**Comment by sstone1** [comment]
Just to expand on the above for prosperity.

The cloud playground is currently hosted in an IBM owned, IBM Cloud account - therefore any data collected by it is entirely IBMs responsibility. The IBM contributor team could not find any responsible adults (compliance officers) within IBM who wanted to tell us what we needed to do/not do. We decided that we were too cool to take on that responsibility ourselves, so we're disabling it altogether.
