### ISSUE TITLE
PeerDeps will not automatically update

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3988]
the `npm run pkgbump` command that we rely on in the release build will only update the peerDependancies if they are also a devDependancy. Which is a lerna thing it would seem. 

This is also true if a manual version bump is made.

The proposal here is to add these back into the devDeps to ensure that they are updated automatically.

**Comment by davidkel** [comment]
@nklincoln why do we have PeerDependency definitions ? Not sure I can see why we ever needed them, so maybe a solution is just to remove them and go back to what we had before.

**Comment by sstone1** [comment]
@mbwhite added them in https://github.com/hyperledger/composer/pull/3798.

**Comment by davidkel** [comment]
ok, thought I could see a reason for having them in a subset, ie the wallets, but see we explicitly pull the filesystem and inmemory wallets in anyway so still none the wiser.
