### ISSUE TITLE
Angular2 app generated by "yo fabric-composer" does not have UI for Participants or Transactions

### ISSUE THREAD

**Issue by sanjay-saxena** [hyperledger/composer#400]
When `yo fabric-composer` command is used to generate Angular2 Application using an business network archive file, it only generates artifacts for Assets.  Executing `npm start` from the command-line will automatically launch a browser tab with the app running on  `http://localhost:4200`. In the browser, you can see a drop-down for `Assets`. Selecting an asset from the drop-down will render the corresponding page with `Add Asset` button above an empty table. However, there is no similar mechanism to populate Participants. Since an Asset and a Participant usually have a PK-FK relationship and one **cannot** add/populate Participants using the current browser UI, it becomes impossible to even add/populate Assets using the browser UI.

## Context
See above.

## Expected Behavior

`yo fabric-composer` should generate artifacts for Participants and Transactions. The UI should show drop-downs for Participants and Transactions. Also, there should be ability to create/add new Participants from the browser. Furthermore, the field that links an Asset to a Participant should show a drop-down populated with corresponding Participant IDs.

## Actual Behavior

Incomplete support.

## Steps to Reproduce
Here are the [steps](https://fabric-composer.github.io/tasks/genapp.html) to reproduce using any business network archive.

## Existing issues
One of the limitations listed in [generator-fabric-composer](https://github.com/fabric-composer/fabric-composer/tree/master/packages/generator-fabric-composer) module is about the missing functionality for Participants and Transactions. Since Assets typically depend on Participants, it would have made more sense to add functionality for Participants before adding the functionality for Assets.

## Context
Generate an Angular2 app using the business network archive to accomplish everything from the browser UI.

## Your Environment
* Version used: Composer v0.4.5
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node.js v6.10.0
* Operating System and version (desktop or mobile): macOS 10.12.1
* Link to your project:

**Comment by Jakeeyturner** [comment]
Hi @sanjay-saxena, we will definitely be adding the ability to create new participants and submit transactions in the future. Similarly to each asset component, the participant and transaction components will be generated with respect to the business network definition model files.

Thank you for creating this issue.

**Comment by winslet** [comment]
This also pulls in the work from #527 which is to redesign the UI for the whole angular generator, this work should be done at the same time. #527 is currently on the backlog for design as an FYI. 👍

**Comment by sstone1** [comment]
See additional feature requests for generator in #2870:

> So many features such as wallet and authorization are added in the composer rest server. but the generator is not accomadating all features.

**Comment by sstone1** [comment]
Replaced by CIP #3136.

**Comment by lokeshgene** [comment]
Could someone please comment, how to fix this issue?, I am still facing this. My Angular App, doesn't show up transaction UI.

thanks,
lokesh

**Comment by ghazanfarperdakh** [comment]
. Please visit : “Fixing Transaction issue in Angular for Hyperledger fabric blockchain application” https://medium.com/coinmonks/fixing-transaction-issue-in-angular-for-hyperledger-fabric-blockchain-application-fe7e28a7bb6e
