### ISSUE TITLE
Push images to docker hub as part of release process

### ISSUE THREAD

**Issue by sanjay-saxena** [hyperledger/composer#4011]
Developers are installing the latest Composer Runtime `0.19.5` to the cloud(i.e. Starter Plan instance). Then, in order to expose REST APIs directly from cloud, developers are using a cloud-based wallet with cards and pushing the image for `composer-rest-server` from docker hub as shown below:

```
$ cf push car-auction --docker-image sstone1/composer-rest-server \
    -c "composer-rest-server -c admin@carauction-network -n never -w true"  \
    -i 1 -m 256M --no-start --no-manifest
$ cf set-env car-auction NODE_CONFIG "${NODE_CONFIG}"
$ cf start car-auction
```
However, the `composer-rest-server` on docker hub under `sstone1/` is based on `0.19.4`. And, the latest Composer Runtime `0.19.5` is not compatible with `composer-rest-server 0.19.4`. This results in the following errors when developer tries to start `composer-rest-server` on the cloud(i.e. Starter Plan instance):

```
2018-05-11T14:49:44.92-0700 [APP/PROC/WEB/0]ERR Connection fails: 
Error: Error trying to ping. Error: Composer runtime (0.19.5) is not compatible 
with client (0.19.4)
```
## Expected Behavior
Ideally, Composer Runtime should be backward compatible with composer-rest-server. But, if that is not the case at this point, all the Hyperledger Composer pieces -- `composer-cli`, `composer-rest-server`, `generator-hyperledger-composer`, `composer-playground`, etc. -- should be simultaneously released to npm as well docker hub under `sstone1`.

## Actual Behavior
See above.

## Steps to Reproduce
1. Install and start a business network using Hyperledger Composer 0.19.5 to the Starter Plan instance.
2. Create cloud-based wallet using Cloudant NoSQL DB and populate it with the ca, peer-admin, and network-admin cards.
3. Execute the steps outlined above.

## Context
See above.

## Your Environment
* Version used: Hyperledger Composer v0.19.5 and composer-rest-server 0.19.4

**Comment by sstone1** [comment]
This is not a Hyperledger issue; should have been raised against an IBM repository.

**Comment by petercrippsIBM** [comment]
Hi Sanjay, I'm getting similar problems as this. First time through your tutorial (https://www.ibm.com/developerworks/cloud/library/cl-deploy-blockchain-starter-plan-network/) all worked but now, when I try to build my Angular app I get this error: 

**Error: Error trying to ping. Error: Composer runtime (0.19.5) is not compatible with client (0.19.0)**

I have checked my versions and I have 0.19.5 of both composer-cli and composer-rest-server so I don't understand where 0.19.0 is coming from? Any guidance you can give would be much appreciated, thx.

**Comment by sanjay-saxena** [comment]
@petercrippsIBM -- I think you are using an older-version of `composer-rest-server` on the cloud. If your using 0.19.5 runtime, then make sure that you are using `ibmblockchain/composer-rest-server:0.19.5` docker image.

Here is a [tutorial](https://www.ibm.com/developerworks/cloud/library/cl-deploy-blockchain-starter-plan-network/index.html) with detailed steps. I suggest you start from scratch by deleting your Blockchain instance and related apps. 

Also, this repo is for Hyperledger Composer which is an open-source project. Since you are running into an issue that is related to IBM Blockchain Platform, it is probably a good idea to file issues/tickets against it.

**Comment by petercrippsIBM** [comment]
Sanjay, I have been following your tutorial and specified `ibmblockchain/composer-rest-server:0.19.5` docker image on IBM Cloud but for some reason the runtime (I assume that means the composer-rest-server) is coming up as 0.19.0. Strange thing is this worked a few days ago and now is not. As you suggest I will go through again and see if I get the same error.

**Comment by valdergallo** [comment]
@sanjay-saxena , I have been following your tutorial (https://www.ibm.com/developerworks/cloud/library/cl-deploy-blockchain-starter-plan-network/). But now I just can push one network using version 0.19.12. 

When I try update one network using composer 0.19.5 ... I got this message:

```
✖ Upgrading business network definition. This may take a minute...
Error: Error trying to upgrade business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: transaction returned with failure: Error: Cannot upgrade business network. New composer runtime version of (0.19.5) is not compatible with (0.19.12). Composer runtime has changed major or minor version and cannot be upgraded.
Command failed
```

And no have image for version 0.19.12 in (https://hub.docker.com/r/ibmblockchain/composer-rest-server/tags/)
