### ISSUE TITLE
Cannot deploy network using certificate credentials for network admin in playground

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#4025]
## Context

Attempting to deploy a new business network to starter plan using playground. I was using the certificate and private key obtained at the end of step two in the starter plan [Deploying a business network on Starter Plan](https://console.bluemix.net/docs/services/blockchain/develop_starter.html#deploying-a-business-network) instructions

## Expected Behavior

It should be possible to specify certificate and private key credentials for the network admin when deploying a business network in the playground (it's even the default option!!!)

## Actual Behavior

It does not work: it sounds like the private key is not actually getting through to the api

> Error: Failed to import identity. Error: privateKey not specified or not a string

## Possible Fix

A few options...

1. Make it work
2. Remove the **Certificates** option (luckily the starter plan unexpectedly allows multiple enrollments so **ID and Secret** does actually work!)
3. Remove ability for Playground to connect to real Fabric

**Comment by davidkel** [comment]
For option 1 I suspect the problem is that the call to adminConnection.start which returns a card with only a certificate in which is not much use. We could fix adminConnection.start (as well as the start cli to either also accept the private key or a card) so it can generate a valid card, and may not require a change to playground

**Comment by davidkel** [comment]
Unfortunately there is a further problem which the above won't fix. What if you want to, at start time, bind identities from different organisations ? The card files created will have the connection profile from the identity used to start the network and will only be of 1 the organisations (or could even be non of them). So some or all cards are still not usable. Maybe the solution would be to take imported cards and maybe also card files is the input for the credential information and update them with the business network they are being associated with.
