### ISSUE TITLE
TypeError: Cannot read property 'port' of null

### ISSUE THREAD

**Issue by cloudhuang** [hyperledger/composer#4029]
## Context
Following the [Developer tutorial for creating a Hyperledger Composer solution](https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial) - [Start the web app ("Playground")](https://hyperledger.github.io/composer/latest/installing/development-tools.html) section

## Expected Behavior
execute the `composer-playground` command in console, but
encountered the error `TypeError: Cannot read property 'port' of null`

## Actual Behavior
it should start the web server correctly.

## Steps to Reproduce
1. Set up your development environment
2. start the `composer-playground`

## Env
1. All the software & docker images are download automatically via the download sh file
2. OS: MACOS 10.13.4

**Comment by smanetto** [comment]
I have the same issue (if this is an issue).

Passing --port=8080 will temporary fix this problem as a workaround.

.../lib/node_modules/composer-playground/cli.js
I agree it should take by default port.

**Comment by davidkel** [comment]
I can't recreate this, can you provide some more detail for example what version of composer-playground, how have you installed it, what version of node, npm, nvm have you installed ?

**Comment by smanetto** [comment]
I am a newbie with composer.
This is my environment:

OS: GNU/Linux Ubuntu 16.04.4 

I installed nodejs manually (so in my system I may have mixed libraries with nodejs Ubuntu package):
node-v8.11.2-linux-x64/

~/opt/nodejs/node-v8.11.2-linux-x64/bin/composer-playground --version
0.19.5

and ran as by tutorial the following commands (inside ~/opt/nodejs/node-v8.11.2-linux-x64/bin/):
npm install -g composer-cli
npm install -g composer-playground
and so forth ...

I thereafter modified PATH variable to include nodejs v8.11.2 path.

$ npm --version
5.6.0
(I have not nvm installed on my system)

$ ~/opt/nodejs/node-v8.11.2-linux-x64/bin$ ./composer-playground 
info: [Hyperledger-Composer] :LoadModule               :loadModule()              Loading composer-wallet-filesystem from /home/smanetto/opt/nodejs/node-v8.11.2-linux-x64/lib/node_modules/composer-playground/node_modules/composer-wallet-filesystem
/home/smanetto/opt/nodejs/node-v8.11.2-linux-x64/lib/node_modules/composer-playground/node_modules/composer-playground-api/index.js:61
    port = server.address().port;
                           ^ (<== caret is just under ".")

TypeError: Cannot read property 'port' of null
    at createServer (/home/smanetto/opt/nodejs/node-v8.11.2-linux-x64/lib/node_modules/composer-playground/node_modules/composer-playground-api/index.js:61:28)
    at createServer (/home/smanetto/opt/nodejs/node-v8.11.2-linux-x64/lib/node_modules/composer-playground/index.js:34:17)
    at Object.<anonymous> (/home/smanetto/opt/nodejs/node-v8.11.2-linux-x64/lib/node_modules/composer-playground/cli.js:50:13)
    at Module._compile (module.js:652:30)

**Comment by smanetto** [comment]
Despite the error message, this issue, at least for me, was caused by another application listening to port 8080. 
I modified the default port in the code (s/8080/9999/) and started it again. It worked fine.

**Comment by davidkel** [comment]
Confirmed that you get this error if something else is listening on the port that playground is trying to use, so by default playground uses port 8080 and if you have anything else listening on this port then you get this error.

**Comment by cloudhuang** [comment]
@smanetto Cool, you really made me a big favor, yes, I get this error due to the 8080 port already used, thanks.

**Comment by sstone1** [comment]
This is a bug; we should fix it!
