### ISSUE TITLE
Will composer be supported on Centos?

### ISSUE THREAD

**Issue by Dearkano** [hyperledger/composer#4030]

**Comment by mbwhite** [comment]
I do know that some community members are using the developer subscription to RHEL; CentOs should be similar.  Especially if Docker is used for running apps, then there should be no issue. 

The challenge is that we don't (using Travis-CI) have any sort of regression capability for Linux platforms other than Ubuntu.  So it's hard to say formally that it works and is supported as we can't test it.

**Comment by Dearkano** [comment]
will have a simple test＆thanks

**Comment by sstone1** [comment]
We have no plans to formally support CentOS or RHEL, as @mbwhite mentioned we have no capability to offer formal testing for these platforms. Please try it, if it works great, if it doesn't then we'll gladly accept code or documentation fixes that get it working on CentOS or RHEL (or any other platform!).
