### ISSUE TITLE
Business network generator does not gitignore dist folder

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#4041]
The business network generator needs to generate two ignore files:

- `.gitignore` that ignores the `dist` folder (this folder contains BNAs, which should not appear as pending changes and get committed into Git)
- `.npmignore` that is empty and does not ignore the `dist` folder (this folder contains BNAs, which should be included in the package that is published to npm)

**Comment by jt-nti** [comment]
I think it would probably be better to ignore *.bna and *.card files rather than the dist folder explicitly. By coincidence I've created a related pull request to create a Hyperledger Composer github gitignore template github/gitignore#2709
