### ISSUE TITLE
composer network start command failed((status: 500, message: cannot get package for chaincode)

### ISSUE THREAD

**Issue by divyamsingh13** [hyperledger/composer#4043]
command: composer network install --card PeerAdmin@hlfv1 --archiveFile land-agreement@0.0.1.bna✔ Installing business network. This may take a minute...
Successfully installed business network land-agreement, version 0.0.1

Command succeeded

command : composer archive list -a land-agreement@0.0.1.bna
Listing Business Network Archive from land-agreement@0.0.1.bna
Identifier:land-agreement@0.0.1
Name:land-agreement
Version:0.0.1

Command succeeded

command:  composer network start --networkName land-agreement --networkVersion 0.0.1 --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv1 --file networkadmin.card
Starting business network land-agreement at version 0.0.1

Processing these Network Admins: 
	userName: admin

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: chaincode error (status: 500, message: cannot get package for chaincode (land-agreement:0.0.1))
Command failed

The same error occurs with the two of my projects.
The same error is being raised when running the IBM tutorial for tutorial-network even on using the same commands .

**Comment by valdergallo** [comment]
I'm with same error here

**Comment by nitishbhushan2013** [comment]
seems its very basic common error.. 

I am also facing the same issue and looking around for some clues. I will update the solution soon... 

command issued - 
composer network start -c PeerAdmin@hlfv1 -n nitish-bna -V 0.0.1 -A admin -S adminpw

response - 
Starting business network nitish-bna at version 0.0.1

Processing these Network Admins: 
	userName: admin

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: chaincode error (status: 500, message: cannot get package for chaincode (nitish-bna:0.0.1))
Command failed

**Comment by girishkumara** [comment]
Hi, 

I am all facing same issue. Any resolution on the same?

Thanks
Girish

**Comment by davidkel** [comment]
Before you can start a business network, you need to ensure that it is installed on at least 1 peer in your network (depending on your requirements, number of peers etc). The error you get `cannot get package for chaincode (<Name of business network>:<version of business network>)` is telling you that you have either not installed the business network onto the peer or you have tried to start a business network with the wrong name and/or version to the package you have installed on the peer(s).

When you perform `composer network install` you will be told the name of the business network and the version that has been installed. You can also use `composer archive list` to determine the business network name and version of the bna. This information is also defined in the package.json on the business network you are creating, so there are multiple ways to determine what the correct business network name and version you should use when performing the network start command.

However I do note that the initial reporter followed the steps defined and still there was a problem. So what you can do is look on the peer container itself to see what package has been installed into the peer.
- docker exec -it <id_of_peer_container> /bin/bash
- cd /var/hyperledger/production/chaincodes
- ls
should show the installed chaincode packages and will contain a file with the name <businessnetwork name>.<businessnetwork version>
if it isn't there then this is why you get the error message and the install has not completed successfully on that peer.
eg
```
docker exec -it peer0.org1.example.com /bin/bash
root@fde1db8b9361:/opt/gopath/src/github.com/hyperledger/fabric# cd /var/hyperledger/production/chaincodes
root@fde1db8b9361:/var/hyperledger/production/chaincodes# ls
basic-sample-network.0.2.4
```

**Comment by Bolee95** [comment]
If you are trying to deploy network in IBM Cloud Blockchain and you already installed bna file, you should enter as name option as it is stated in My Code -> Install Code -> inside table with deployed chaincode take a look at code id column, and version option as it is stated in version column. My version for example wasn't like "0.0.1" , more like "0.0.2-deploy.70". 

![screen shot 2018-08-04 at 3 28 55 pm](https://user-images.githubusercontent.com/20232629/43677005-639f2e56-97fb-11e8-87ca-e1c9c5a89e0c.png)

**Comment by ibexdata** [comment]
This was pretty frustrating for me as well, and I encountered it in the Queries Tutorial of the IBM tutorial-network in the Developer Tutorials.

I had made the modifications in steps 1 though 3. Then, in step 4, I was able to install the network card at the new version (0.0.2). Then attempting to upgrade the network to the new version failed with the same error above. 

I was able to determine that the network had not been running correctly at the time and needed a healthy restart across the board.
A couple to troubleshooting tips:
- Reminder: start in your project's root folder.
- Is the card associated with a network? Try `composer network list --card PeerAdmin@hlfv1`
- is the docker container running? Try `docker ps` to confirm that the hyperledger/fabric* containers are running. At this point I stopped all of the containers in hopes of restarting what I needed. 
- is the business network running? Try `composer network ping --card admin@tutorial-network`

I next used the scripts that came with /fabric-dev-servers (should be in your home folder) to:
- Stop any running fabric runtimes with `.stopFabric.sh`
- Tear down with `teardownFabric.sh`
- Start the fabric runtime with `startFabric.sh`
- Repackage the business network archive (.BNA) file, from the project directory with `composer archive create -t dir -n . `
- Install the network from the repackaged .BNA file with `composer network install --card PeerAdmin@hlfv1 --archiveFile tutorial-network@0.0.2.bna` 
- Start the business network with `composer network start --networkName tutorial-network --networkVersion 0.0.2 --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv1 --file networkadmin.card`
- Re-installed the admin card with `composer card import --file networkadmin.card`
- Ping the network to confirm it is running and the correct version with `composer network ping --card admin@tutorial-network`. Make note of the Business Network Version.

At this point you should have running docker containers as well as a running business network. Your admin card should be associated with the business network.
 
Be sure to start the REST server (`composer-rest-server`) for this particular tutorial project.

**Comment by LoboSolitario** [comment]
@ibexdata  
Had run into the same issue. Your solution worked fantastically. Thanks a lot

**Comment by Keyglance** [comment]
Great! Thanks a lot!

**Comment by skia92** [comment]
I was struggling with this issue when I tried to upgrade version from 0.0.1 to 0.0.2 described in the officail query tutorial.

I realised that I didn't update version in the file `package.json` so if there are those who may face with it, check the __step three__ again

**Comment by bhemeswararao** [comment]
please give the solution i have facing this error


bc@bc-HP-Pro-3090-Microtower-PC:~/product-network$ composer network start --networkName product-network --networkVersion 0.0.1 --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv1 --file networkadmin.card
Starting business network product-network at version 0.0.1

Processing these Network Admins: 
	userName: admin

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: Failed to connect to any peer event hubs. It is required that at least 1 event hub has been connected to receive the commit event
Command failed

**Comment by brunus0475** [comment]
@bhemeswararao  Have you found the solution? I have facing same error!!!!

**Comment by bhemeswararao** [comment]
no

**Comment by bhemeswararao** [comment]
Hello there,

I just signed the petition "Prime Minister of India: Need Justification
Reg. National Cricketer "Ambati Rayudu" from unethical motion of BCCI" and
wanted to see if you could help by adding your name.

Our goal is to reach 200 signatures and we need more support. You can read
more and sign the petition here:

http://chng.it/wp2HKsBpSb

Thanks!
Bhemeswararao

**Comment by Mithun1284** [comment]
> This was pretty frustrating for me as well, and I encountered it in the Queries Tutorial of the IBM tutorial-network in the Developer Tutorials.
> 
> I had made the modifications in steps 1 though 3. Then, in step 4, I was able to install the network card at the new version (0.0.2). Then attempting to upgrade the network to the new version failed with the same error above.
> 
> I was able to determine that the network had not been running correctly at the time and needed a healthy restart across the board.
> A couple to troubleshooting tips:
> 
>     * Reminder: start in your project's root folder.
> 
>     * Is the card associated with a network? Try `composer network list --card PeerAdmin@hlfv1`
> 
>     * is the docker container running? Try `docker ps` to confirm that the hyperledger/fabric* containers are running. At this point I stopped all of the containers in hopes of restarting what I needed.
> 
>     * is the business network running? Try `composer network ping --card admin@tutorial-network`
> 
> 
> I next used the scripts that came with /fabric-dev-servers (should be in your home folder) to:
> 
>     * Stop any running fabric runtimes with `.stopFabric.sh`
> 
>     * Tear down with `teardownFabric.sh`
> 
>     * Start the fabric runtime with `startFabric.sh`
> 
>     * Repackage the business network archive (.BNA) file, from the project directory with `composer archive create -t dir -n . `
> 
>     * Install the network from the repackaged .BNA file with `composer network install --card PeerAdmin@hlfv1 --archiveFile tutorial-network@0.0.2.bna`
> 
>     * Start the business network with `composer network start --networkName tutorial-network --networkVersion 0.0.2 --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv1 --file networkadmin.card`
> 
>     * Re-installed the admin card with `composer card import --file networkadmin.card`
> 
>     * Ping the network to confirm it is running and the correct version with `composer network ping --card admin@tutorial-network`. Make note of the Business Network Version.
> 
> 
> At this point you should have running docker containers as well as a running business network. Your admin card should be associated with the business network.
> 
> Be sure to start the REST server (`composer-rest-server`) for this particular tutorial project.

It worked for me Thanks a lot !!
