### ISSUE TITLE
No matching version found for composer-wallet-inmemory@0.19.6

### ISSUE THREAD

**Issue by LeeJCherry** [hyperledger/composer#4052]
## Context
Building a New Hyperledger Environment using a clean Ubuntu 16.04 AWS EC2 image and following this article https://hyperledger.github.io/composer/latest/installing/development-tools.html

Completed the pre-req installation described here with no issues https://hyperledger.github.io/composer/latest/installing/installing-prereqs.html

I have installed the composer before, a few days ago on a different machine and didn't encounter this issue, seems to be a new issue.

## Expected Behavior
npm install should complete successfully

## Actual Behavior
npm install failed with the following error
![image](https://user-images.githubusercontent.com/29426298/40482107-852bdbd4-5f4b-11e8-9b66-913f83dcf773.png)

## Possible Fix
Possible version referencing issue.

## Steps to Reproduce

1. Fresh Ubuntu 16.04 EC2 instance from AWS 
Then run the following commands within the image
1. sudo apt update
2. curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
3. sudo apt-get install -y nodejs
4. curl -O https://hyperledger.github.io/composer/latest/prereqs-ubuntu.sh
5. chmod u+x prereqs-ubuntu.sh
6. sudo ./prereqs-ubuntu.sh
7. npm install -g composer-cli

**Comment by jt-nti** [comment]
@LeeJCherry hi, sorry, today is the weekly release day and it seems that something went wrong publishing node modules. For now it's probably best to explicitly install the 0.19.5 version while we work out what happened. Sorry.

**Comment by LeeJCherry** [comment]
No problem, at least I know now. Thanks for responding

**Comment by jt-nti** [comment]
Seems like this could be related to npm/registry#327

**Comment by LeeJCherry** [comment]
I have another issue which may be related to the original?

![image](https://user-images.githubusercontent.com/29426298/40486523-710fcda0-5f59-11e8-9474-8d815915c61b.png)

**Comment by jt-nti** [comment]
@LeeJCherry that's not related to the publish problems- you shouldn't be using `sudo` to run those scripts (or install the node modules)

**Comment by LeeJCherry** [comment]
If I don't, I get permissions / access denied errors (Linux newb)

**Comment by jt-nti** [comment]
@LeeJCherry there is a knowledge wiki and some Composer 'books' which might have some useful tips in. Failing that it's probably worth heading over to Rocket.Chat to ask about permissions issues:

 - https://github.com/hyperledger/composer-knowledge-wiki/blob/latest/knowledge.md
 - https://davidkel.github.io/
 - https://hyperledger.github.io/composer/latest/support/support-index.html

**Comment by jt-nti** [comment]
Closing this issue now that it's possible to install 0.19.6/latest modules again
