### ISSUE TITLE
Multiple conditions query regression from 0.16

### ISSUE THREAD

**Issue by TinoSM** [hyperledger/composer#4058]
I have a query which was working fine in 0.16, it filters by multiple parameters 
## Context

> query selectPending {
  description: "Select pending"
  statement:
      SELECT com.hi.hi.Asset  
  		WHERE ( flowStatus !=0 AND flowStatus != 7 )
}

## Expected Behavior

I would get only Assets with status NOT 0 and NOT 7. 

## Actual Behavior

I'm getting Assets with status NOT 0, but I'm getting Assets with Status 7. If i change the order, (i.e. WHERE ( flowStatus !=7 AND flowStatus !=0 ).  I will get Assets with status 7 and not 0. So I think it's not applying the second part of the AND
## Steps to Reproduce

1. Make a query like the one I did (multiple AND together)
2. Test

## Existing issues

Couldn't create find any

## Context

Not such a big problem, I'm filtering them in NodeJS after getting the result, but of course not desirable. I'm "just" developing a project

## Your Environment

* Version used: 0.19.5
* Environment name and version (e.g. Chrome 39, node.js 5.4): v9.4.0
* Operating System and version (desktop or mobile): Fedora (Amazon AMI)
* Link to your project: Can't make it public :/

**Comment by TinoSM** [comment]
I've trying it again and some of the conditions didn't apply even if they were the first one in the query :/ (many compilations ran between ticket and today tests, maybe the condition which is applied its just random).

**Comment by diegoduncan21** [comment]
+1 
https://stackoverflow.com/questions/50752323/query-filter-in-composer-rest-server/50758719#50758719
