### ISSUE TITLE
Docker images for Hyperledger Composer for s390 architecture for zLinux

### ISSUE THREAD

**Issue by DennisM330** [hyperledger/composer#4086]
Provide Docker images for Hyperledger Composer for s390 architecture for zLinux.
## Context

Docker images are available for Hyperledger Fabric on the s390 architecture for zLinux. There are no Hyperledger Composer Docker images for the s390 architecture for zLinux. 
## Expected Behavior

 For consistency and a simplified architecture, docker images should be provided for Hyperledger Composer.

## Actual Behavior
Hyperledger Composer is not an option.

**Comment by jt-nti** [comment]
See https://github.com/titogarrido/composer-playground-s390x for a composer-playground docker image ported to s390x - Mainframe/LinuxOne
