### ISSUE TITLE
Cannot get composer rest api to work with Auth0

### ISSUE THREAD

**Issue by sakopov** [hyperledger/composer#4093]
## Context
I'm attempting to get Composer REST API to talk to Auth0. It appears that the authentication request goes through successfully as I see no issues in Auth0 console logs. However, I don't see any access tokens in Composer REST API Explorer. I tried tracking the entire auth exchange in the network tab in dev tools and was able to see that the token is written to a cookie. But when I try to use it (via access_token query string parameter) I still get `Authorization Required` error from the API.

## Expected Behavior
I should be able to use the token and make an authorized API request.

## Actual Behavior
The request is denied. When I follow the requests, I can actually see the access_token being set when the callback gets hit. But the only cookie i see has name `connect.sid` and a value in it that doesn't correspond to the value being set in the cookie. Either way, neither value yield a successful response from the API. Moreover, the value appears to be url-encoded and decoding them didn't seem to make any difference.

## Your Environment

Both the application and the API in Auth0 use RS256 signing algorithm. The application type on the Auth0 application is set to Machine to Machine.

 ```
export COMPOSER_PROVIDERS='{
    "auth0": {
        "provider": "auth0",
        "domain": "redacted.auth0.com",
        "module": "passport-auth0",
        "clientID": "**redacted**",
        "clientSecret": "**redacted**",
        "authPath": "/auth/auth0",
        "callbackURL": "/auth/auth0/callback",
        "successRedirect": "/",
        "failureRedirect": "/",
        "audience": "urn:hyperledger"
    }
}'
```
node version 8.10.0
mac OSX 10.13.4
composer & composer-rest-server v0.16.6

**Comment by jordykrul** [comment]
Got the same problem over here.

**Comment by imdreamrunner** [comment]
After some research, i found that the access token is set to the wrong domain in the callback URL.

```
Set-Cookie: access_token=s%3A21YJ6CLLYNCr6YqzOcZUwEiCRkNv2c0T0JaNnfOqf6SFmpKLcHpAJnxBeDXYcpBz.2DzoEvShYA83FV6OoVC4S0BJMsVYqQqblTs47pR%2B9RQ; Max-Age=1209600; Domain=composer-demo.auth0.com; Path=/; Expires=Fri, 27 Jul 2018 08:02:43 GMT
Set-Cookie: userId=s%3A1.cJt90VPvLRb6wgFdnj86fADkYfCuYUekaSPp%2BMgYdzo; Max-Age=1209600; Domain=composer-demo.auth0.com; Path=/; Expires=Fri, 27 Jul 2018 08:02:43 GMT
```

**Comment by sakopov** [comment]
Indeed. I tracked the authorization exchange between Auth0 and Rest API and the cookie is set for the Auth0 tenant domain instead of the Rest API domain in the callback phase. I don't think this is Auth0 passport implementation issue. Perhaps Composer is doing something screwy here?

**Comment by imdreamrunner** [comment]
I forked the `passport-auth0` package and make some changes so that it can work with the loopback module `composer-rest-server` is using. This could be a temporary solution.

https://github.com/imdreamrunner/passport-auth0

**Comment by sakopov** [comment]
I'm not entirely sure I understand how to use this. I tried installing loopback update and changing the module property in the COMPOSER_PROVIDERS to "passport-auth0-loopback" but ended up getting "Cant'd find module" error.

I also tried simply making the same change directly in node_modules/passport-auth0/index.js which broke on `usernameOrId` being null even though the user in Auth0 has username.

But thanks for sharing your fix. Glad something works for some folks.

**Comment by sakopov** [comment]
Unfortunately, this still does not work. It looks like Composer doesn't find username claim in the token during in the callback.

```
/Users/sakopov/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/lib/util.js:151
        if (usernameOrId.match(/[^A-Za-z0-9\.\-_]/)) {
```

**Comment by ankuragrwl** [comment]
This worked for me

**Comment by haihoang20** [comment]
You can add the username or ID as a custom claim: https://auth0.com/docs/tokens/id-token#add-custom-claims
