### ISSUE TITLE
composer development pre-requisities to be installed automatically using a script on to Redhat Linux platform

### ISSUE THREAD

**Issue by pvrbharg** [hyperledger/composer#4099]
# Abstract

Getting composer development pre-requisities to be installed automatically using a script on to Redhat Linux platform - in addition to Ubuntu and Mac platforms

# Motivation

Most production deployments of Hyperledger Fabric that I came across use Redhat platform [for production workloads and for reasons of support and enterprise qualities of platform].
  It would help to have Redhat platform supported for composer development as well - again so we can keep development and production environments consistent - for CI/CD, automation, for surfacing issues sooner and as best practice methodology [12-factor and micro-services principles]

# Specification
Enable composer development for Redhat Linux platform in additon to Mac and Ubuntu platforms.

# Rationale
 See motivation section.
Most enterprise production workloads run on Redhat Linux platforms. Hyperledger Fabric works and runs on Redhat platforms. We want Hyperledger Composer development also to be enabled on Redhat platforms so we can have a cohesive and unified development to deployment environment support.

# Backwards Compatibility
We can choose to keep backward compatibility or choose to break it for a start, provide enablement to RHEL platform and going forward keep compatibility

We can choose to bump up or not bump up version numbering - perhaps good to bump up since this is a new platform enablement capability  

# Test Requirements
  Extend testing harness to cover Redhat platform in addition to Ubuntu and Mac platforms
  
# Test Deliverables
   - Features under test
  	All
   - Unit test requirements (This is more a statement of fact that we know all new code must be covered by unit tests, and that there will be 100% coverage ... with meaningful tests)
  	All
   - Functional test requirements
     -- Can you extend the extend existing frameworks? (ie, the cucumber steps etc)
  		Yes
     -- What user scenarios are to be covered?
  		All
   - Integration test requirements
     -- Can the deliverable be included within an integration test?
  		Yes if yes currently
     -- What integration scenarios are to be considered?
  		All currently used
     -- Are we considering golden path only, or also error paths?
  		All paths if we cover all parts today on Ubuntu and Mac platforms
   - Performance test requirements
     -- Should we be adding a performance test for the deliverable?
  		As done currently on Ubuntu and Mac platforms
     -- Are there expected performance improvements from the delivery of the CIP?
  		Yes - we as IBM would be more responsive to customer needs and also reduce support costs by surfacing issues sooner than later
   - Manual test requirements (shame on you! It is highly unlikely that any contributions that require manual testing will be accepted)
  		No shame on me - shame on all of us if we are doing things manually today! Follow what we do today on Ubuntu and Mac platforms - extend to RHEL platform
   - Test considerations
     -- Platform coverage: Are there any considerations such as specific OS requirements for the tests to be run on?
  		Very to somewhat likely - such as GRPC or Crypto libraries - even though we may get lucky with Ubuntu being covered
     -- Browser coverage	
  		N/A

# Implementation
Start with the existing pre-req checking script and adjust it to work with RHEL platforms.
I installed all pre-requisites manually and got the composer to work correctly - Composer samples and Marbles reference sample - using RHEL v7.5 on X86_64 bit amd64 platform

# Copyright
    This document is licensed under the Creative Commons Attribution 4.0 International Public License.

**Comment by jt-nti** [comment]
A couple of related issues for background info:
- Will composer be supported on Centos? #4030
- A Process for Installing Composer on Red Hat Enterprise Linux #2028

**Comment by pvrbharg** [comment]
Hi, 

Thank you for your pointers, James - very helpful.

I am coming from point of view of my customers - who are deploying production grade and enterprise apps on RHEL platform - for enterprise class workloads and for purposes of support and stability. As you know they typically use Docker EE versus Docker CE.

So getting Composer work on RHEL platform automatically aligns Composer, Fabric as well as operational deployment aspects - all lined up - especially given Composer already works on RHEL 7,5 (Maipo) shown below in my attachment. Hence my request.

Your pointers validate my request independently - even though I did not realize such previous requests.

For reasons explained - CentOS - even though works - would not address my request (for support reasons and for enterprise operational workloads - RHEL would likely be used than CentOS). 

With programming model between Composer and Fabric alignment over a period and with RHEL+ICP+OpenShift platform realities - I believe this request makes sense doubly (yes I said it like someone says Bigly)!

[ComposerOnRHEL_Marbles.zip](https://github.com/hyperledger/composer/files/2070650/ComposerOnRHEL_Marbles.zip)

Thanks.

**Comment by dselman** [comment]
Sounds like a great initiative. More platform choice can only be a good thing.

**Comment by sstone1** [comment]
@pvrbharg I assume that you are planning on implementing this CIP? I will get you added to the GitHub organisation so that we can assign ownership of the CIP to you for implementation.

**Comment by adrianblakey** [comment]
RHEL 7.5 only? No older releases? How about 7.4 and >? Enterprises are often very slow and conservative in deploying updates :-(

Running on the RH supported docker fork? or Docker CE?
