### ISSUE TITLE
Emitted events are not logged (or shown) in historian

### ISSUE THREAD

**Issue by aharita** [hyperledger/composer#4113]
When emitting an event in a transaction, it's not being logged or shown in Historian via API or Composer Playground

## Context
Emitted events do show in version 0.19.6, but not 0.19.7

Trying to get all the grab all the transactions that have happened to a particular asset using historian, but emittedEvents array is empty on version 0.19.7

## Expected Behavior
Log and show the emitted events in the emittedEvents array in the historian API

## Actual Behavior
Does not show or log the emitted events in the emittedEvents array, and it's empty

## Steps to Reproduce
1. Deploy the example for basic-sample-network
2. Create a new SampleParticipant
3. Create a new SampleAsset
4. Submit a SampleTransaction
5. Click on All Transaction
6. View Record for SampleTransaction, you'll see the Events (0) tab, should be Events (1)

## Environment
Node v8.11.2
Composer and tools v0.19.7
Fabric 1.1.0 images
macOS High Sierra

**Comment by mbwhite** [comment]
Doing an initial test run locally...

**Comment by skarlekar** [comment]
I noticed this issue in version 0.19.8 as well today.

**Comment by mbwhite** [comment]
FYI I've identified the problem here; the creation of the historian record was moved earlier when handling a transaction function. ACLs need to checked to ensure that the historian record can be created - and moving reduced the number of times it was checked,. 

But this meant that it missed getting the events added.

**Comment by mbwhite** [comment]
Resolved by #4123

**Comment by silvogo** [comment]
I am having the exact same issue. When using the Hyperledger Composer playground, version 0.19.7 the events do not appear after the submission of a transaction . I didn't understand what do I have to do to fix this. Can you help me ?

**Comment by mbwhite** [comment]
@silvogo you'll need the latest version to get the fix 0.19.8

**Comment by kafcioo** [comment]
I tried this with version 20.6 and its not working, same problem as described above
