### ISSUE TITLE
Get assets via the rest-server using loopback filters order, skip and limit is not supported.

### ISSUE THREAD

**Issue by Rmannn** [hyperledger/composer#4118]
Using the rest server, filters order, skip and limit are not supported.
We could use a Query to get ordered results, but limit and skip is also not yet supported. 
I add that filter is not supported in historian.
And finally what is the default results limit ?

## Expected Behavior

We should be able to order, limit and skip results when calling the rest server.
We can't go to production because we can't provide a solid way to paginate results.

## Actual Behavior

It's not possible to order, limit or skip results, and it's blocking.

Composer version: 0.19.7

**Comment by sstone1** [comment]
@Rmannn pagination of results is not possible with Hyperledger Fabric today, please see the following JIRA for details: https://jira.hyperledger.org/browse/FAB-2809

Once Hyperledger Fabric supports pagination, we can enable pagination in Hyperledger Composer.
