### ISSUE TITLE
 composer network install command failed

### ISSUE THREAD

**Issue by hainguyen291** [hyperledger/composer#4122]
I tried to install a network by following command:

`composer network install --card PeerAdmin@hlfv1 --archiveFile tutorial-network@0.0.1.bna`

tutorial-network@0.0.1.bna is created before. However, I got the following error:

> ✖ Installing business network. This may take a minute...
> Error: Error trying install business network. Error: No valid responses from any peers.
> Response from attempted peer comms was an error: Error: 14 UNAVAILABLE: EOF
> Command failed

My composer version is: v0.19.7

**Comment by TBigjohn** [comment]
Hi, could you have a look at the issue 4129 I registered, same thing ? Do you have also this container created automaticaly by the system ? Thanks

**Comment by ravijaviya** [comment]
if you have set export CORE_PEER_TLS_ENABLED=false during fabric setup, you should use http and grpc instead of https and grpcs.

**Comment by hainguyen291** [comment]
Hi all,

I decided to reinstall the dev environment to redeploy. Everything is ok now.

Thanks.
