### ISSUE TITLE
Peers and Participants

### ISSUE THREAD

**Issue by karankk1991** [hyperledger/composer#4124]
I had a doubt regarding Peers and Participants.
If i create 5 participants  does 5 different nodes get created in fabric network.If not how does the fabric decide that how many Nodes it needs to create???

**Comment by rjsadaye** [comment]
You have to configure that when you are creating Peer Admin card.
In the file fabric-dev-servers/fabric-scripts/hlfv11/CreatePeerAdminCard.sh 
find this line : cat << EOF > DevServer_connection.json
Below this will be the configuration of your network
You can add multiple peers, channels orderers by adding their details in JSON format.
Just take care you give different ports for every node. Additional port numbers can be 8051, 8053, 9051, 9053 ...
Then stop the fabric and create the PeerAdmin card again using : 
`./teardownFabric.sh && ./startFabric.sh && ./createPeerAdminCard.sh
`
If it throws some error first delete the PeerAdmin card using:
`composer card delete -n PeerAdmin@hlfv1`

then again run:
`./teardownFabric.sh && ./startFabric.sh && ./createPeerAdminCard.sh
`
Then you fabric will start with the new config.
Hope this helps.

**Comment by rjsadaye** [comment]
Participants are not same as nodes. Think of participants as clients and nodes as servers. Participants submit transactions to nodes(peers and orderers). The nodes then commit the transaction to the ledger after validation.

**Comment by karankk1991** [comment]
that means even if a new participants joins in time a new node won't be created... it will be connected to the same node only.
Number of nodes will remain fixed is that correct???

**Comment by rjsadaye** [comment]
You can add more nodes in future using certification authority.
But if you're just adding a participant, there's no need of spawning another node.

**Comment by davidkel** [comment]
Questions should be asked on stackoverflow. Github issues are for bugs and enhancement requests. Closing
