### ISSUE TITLE
Named Participant does not exist in Participant Registry.

### ISSUE THREAD

**Issue by lvndry** [hyperledger/composer#4127]
In http://composer-playground.mybluemix.net: When trying to add a new identity in Composer playrground it is impossible due to the error: Named Participant does not exist in Participant Registry. even if it is implemented in the .cto file.

## Step to reproduce

1. Deploy a business network on Composer playground
2. Try to add a new ID

## Expected Behavior

Creation of a new ID

## Actual Behavior

Can't create new iD

## Your Environment

* Version used: Web playground 0.19.8 
* Environment name and version: Chromium:
* Operating System and version:Manjaro 4.15.18-2-MANJARO

**Comment by rjsadaye** [comment]
Create a participant first in the test pane and then attach identity to it.
