### ISSUE TITLE
Error: Error trying invoke business network. Error: No valid responses from any peers. Response from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: ReferenceError: DentalDemo is not defined

### ISSUE THREAD

**Issue by RainbowArea** [hyperledger/composer#4135]
I have defined a Dental Clinic logic containing DentalDemo and another function of transaction , which function DentalDemo that can create new Participants ,Assets
but when I submit this transaction it is show this 

## Context
![image](https://user-images.githubusercontent.com/19144969/41228734-f56ecc62-6dab-11e8-8427-a85b379bba7f.png)

Error: Error trying invoke business network. Error: No valid responses from any peers. Response from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: ReferenceError: DentalDemo is not defined## Expected Behavior 

 It should be submitted a DentalDemo which it will create participant  

## Actual Behavior
 it said DentalDemo is not defined but I was actually defined it in .cto already

## Possible Fix
I have no idea

## Your Environment

Ubuntu 16.04.3 LTS
Composer-playground  v0.19.1
git version 2.7.4
node version 8.11.1
npm version 5.6.0
nvm version 0.33.9
docker-compose version 1.20.1, build 5d8c71b
Mozilla Firefox 60.0.1
I run this code on my locally notebook I don't use cloud because I 'm in China it cant use cloud I don't know why so I run on my locally computer.

## This is my logic.js code
/**
 * Sample transaction
 * @param {org.dentalclinic15.net.DentalDemo } dentaldemo
 * @transaction
 */

function dentalDemo(dentaldemo){
    var factory = getFactory();
    var NS = 'org.dentalclinic15.net'; 

    // create the clinic
    var clinic = factory.newResource(NS,'Clinic','lovecleansmile@mail.com');
    var clinicAddress= factory.newConcept(NS,'Address');
    clinicAddress.country='Brazil';
    clinic.address = clinicAddress;
    clinic.accountBalance = 1000000;

    //create the dentist
    var dentist = factory.newResource(NS,'Dentist','pete123@mail.com');
    var dentistAddress= factory.newConcept(NS,'Address');
    dentistAddress.country='USA';
    dentistAddress.province='NewYork';
    dentist.address = dentistAddress;
    dentist.accountBalance = 500000;

    //create the patient
    var patient = factory.newResource(NS,'Patient','rachael_weith@mail.com');
    var patientAddress= factory.newConcept(NS,'Address');
    patientAddress.country='USA';
    dentistAddress.province='Idaho';
    patient.address = patientAddress;
    patient.accountBalance = 20000;

    //create contract
    var contract = factory.newResource(NS,'Contract','contract005');
    contract.patient=factory.newRelationship(NS,'Patient','rachael_weith@mail.com');
    contract.dentist=factory.newRelationship(NS,'Dentist','pete123@mail.com');
    contract.clinic=factory.newRelationship(NS,'Clinic','lovecleansmile@mail.com');
    var tomorrow = DentalDemo.timestamp;
    tomorrow.setDate(tomorrow.getDate()+1);
    contract.arrivalDateTime = tomorrow;
    contract.unitPrice = 10;
    contract.TootTreatmentType = 'PROPHYLAXIS';
       
    //create prescription
    var prescription = factory.newResource(NS,'Prescription','treatment005');
    prescription.dentstatus ='ACTIVE';
    prescription.clinicstatus ='ACTIVE';
    prescription.tttype='PROPHYLAXIS';
    prescription.unitCount=1;
    prescription.contract = factory.newRelationship(NS,'Contract','contract005');

    // A bunch of Javascript Promises
   
    return getParticipantRegistry(NS +'Patient')
       .then(function(patientRegistry){
          return patientRegistry.addAll([patient]);
       })
       .then(function(){
          return getParticipantRegistry(NS + '.Dentist') ;
       })
       .then(function(dentistRegistry){
          return dentistRegistry.addAll([dentist]);
       })
       .then(function(){
           return getParticipantRegistry(NS + '.Clinic') ;
        })
        .then(function(clinicRegistry){
           return clinicRegistry.addAll([clinic]);
        })
        .then(function(){
           return getParticipantRegistry(NS + '.Contract') ;
        })
        .then(function(contractRegistry){
           return contractRegistry.addAll([contract]);
        })
        .then(function(){
           return getParticipantRegistry(NS + '.Prescription') ;
        })
        .then(function(prescriptionRegistry){
           return prescriptionRegistry.addAll([prescription]);
        })
        .then(function(){
           return getAssetRegistry(NS + '.Contract') ;
        })
        .then(function(contractRegistry){
           return contractRegistry.addAll([contract]);
        })
        .then(function(){
           return getAssetRegistry(NS + '.Prescription') ;
        })
        .then(function(prescriptionRegistry){
           return prescriptionRegistry.addAll([prescription]);
        });
       }

**Comment by davidkel** [comment]
closing as this is an issue with your transaction code rather than composer. The likely culprit is here
```
var tomorrow = DentalDemo.timestamp;
```
`DentalDemo` is not defined, maybe you meant
```
var tomorrow = dentaldemo.timestamp;
```

**Comment by RainbowArea** [comment]
oh yep  Thank you so much it is solved !!!
