### ISSUE TITLE
Access asset by using information received from another asset

### ISSUE THREAD

**Issue by Laora179** [hyperledger/composer#4160]
Hi,
I just started trying out the Hyperledger Platform and have the following problem: 

My platform consists of the following assets: 
- Historian
- Product
- Maschine

The assets "Product" are moving from one machine to another.
Therefore, I am using two transactions: "Begin_Productionprocess" and "updateHistorian". 

The first transaction "Begin_Productionprocess" changes some of the parameters of the asset "Product", adds the current transactionID as an information to the product and creates a new asset "Historian". The name of the newly created Historian is identical to the current transactionID.

The second transaction "updateHistorian" is then supposed to update the information store on the Historian entry. 

It therefore receives the following information: 

 > transaction UpdateHistorian {
 > --> Product Product
 > }

It is now supposed to get transactionID of the first transaction "Begin_Productionprocess" which is stored on the asset "Product" and use this information to update the entry "Historian". Yet, I am not sure how to transfer the information from the asset "Product" in order to access the right "Historian" entry.  

> function updateHistorian(updateHistorianRequest) {
> console.log('updateHistorian'); 
>  
> var factory = getFactory();
> var namespace = 'res';
>
> return getAssetRegistry(namespace + '.Product')
> 
> .then(function(ProductRegistry) {
> var Product = updateHistorianRequest.Product
> var id = Product.Id; 
>  
>  return (ProductRegistry.update(Product), id);  
> })
>   
> return getAssetRegistry(namespace + '.Historian')
>  
> .then(function(historianRegistry) {
> var Historian = id; 
> Historian.TransactionType = 'End';
> 
> return historianRegistry.update(Historian);  
> }) 
>}

Any help woud be highly appreciated!

**Comment by mbwhite** [comment]
@Laora179 When you say Historian - are you referring to your own asset called Historian or the one already in the system namespace of composer.  (if it is your own can I suggest chaning it's name so it doesn't cause confusion :-) )

Also I'd suggest if you use async/await instead of promise chains it will be easier to see your codes flow.

**Comment by Laora179** [comment]
@mbwhite, I am referring to my own asset which is called Historian. You are right, it might not have been the smartest choice of name for the asset - I will change this :)

What to you mean by using async/await instead of promise chains? I am sorry, but this is not clear to me.

**Comment by mbwhite** [comment]
I think you're almost there.
```
async function updateHistorian(updateHistorianRequest) {
  console.log('updateHistorian');

var factory = getFactory();
var namespace = 'res';

productRegistry = await getAssetRegistry(namespace + '.Product')

var Product = updateHistorianRequest.Product
var id = Product.Id;

await ProductRegistry.update(Product)

var historianRegistry = await getAssetRegistry(namespace + '.Historian')

// need to use the factory to create a new resource
var Historian = getFactory().newResource(namespace,'Historian',id);
Historian.TransactionType = 'End';

await historianRegistry.update(Historian);

}
```

**Comment by Laora179** [comment]
Thank you for your help, @mbwhite. I think that I am already close to what I want the transaction to perform, but not quite there yet.

At the moment, the following part creates a new entry in the asset registry 'Historian': 
> var Historian = getFactory().newResource(namespace,'Historian',id);
> Historian.TransactionType = 'End';
>
> await historianRegistry.update(Historian);

Yet, I want it to  **update** the existing entry, which means that there is already an existing entry whose name is identical to the 'id' which is stored within my variable. 

The only thing that I want to change within the existing entry is its 'status' (TransactionType), which is supposed to change from 'Begin' to 'End'. 

It would be great if you could take a look at the issue one more time and help me figure out the right solution. Thank you once again, @mbwhite :)
