### ISSUE TITLE
Issue with "composer network start"

### ISSUE THREAD

**Issue by TBigjohn** [hyperledger/composer#4161]
Hello,

Can somebody give me more info on what's happening when "composer network start" is launched ?
This command is creating a temporary docker container, how is it possible to configure the creation of this container ? Can this be achieve with an npmrc file ? 
Does anybody have a example of such an option file ?

https://github.com/hyperledger/composer/issues/4129

Thanks

**Comment by davidkel** [comment]
composer network start issues an instantiate on the fabric network. The fabric then starts the process of building chaincode container images based on the installed chaincode by creating a container of a defined fabric container image specifically designed to build chaincode container images. It performs an npm install --production on the chaincode. If a `.npmrc` file is present then npm will read this file and it influences how npm will work. For details of what can go into a .npmrc file you should look up this information where npm is documented. Once the chaincode container image is build, a container is created from that image and that is the container that run runs the chaincode in the network.

It probably is possible to configure your fabric network to influence how it builds chaincode containers, but that is something that is set up at the fabric network deployment and not something that composer can control. It will also require advanced knowledge of hyperledger fabric itself.
