### ISSUE TITLE
Enable transaction processor functions to return data to client applications

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#4165]
# Abstract
Enable transaction processor functions to return data to client applications.

# Motivation
Today, transaction processor functions cannot return data to the client application that submitted the transaction.

First, a bit of history:

Once upon a time...

Composer was originally built around Fabric v0.6, and a lot of Composer behaviour is still there because of the way that Fabric v0.6 worked. Fabric v0.6 used order-execute-commit transaction processing, which meant that transactions were a bit "fire and forget" - you submitted them to the network, and then if they succeeded you got a commit notification, otherwise if they failed (for any reason) you just got a timeout.

Chaincode queries in Fabric v0.6 worked slightly differently to chaincode invokes in that a query was sent to a single peer and was able to return data to the client application, but the query "transaction" could not be committed to the blockchain.

However, now, Fabric v1.0 uses execute-order-commit. The execute stage is much more synchronous than before, similar to an RPC call where chaincode is invoked and a signed proposal response is returned. The order-commit stage is still asynchronous, with the signed proposal responses being submitted to the ordering service, and eventually you get a commit notification (even if it failed due to MVCC errors). 

As a result of the transaction processing changes in Fabric v1.0, chaincode queries where removed. A chaincode "query" is now a chaincode invoke, except you just don't submit the signed proposal responses to the ordering service, and you probably only submit it to a single peer node.

Now, why do people want to do this?

A lot of client use cases we see involve an application wanting to submit a transaction to a business network that changes an asset, and then wanting to get the modified state of that asset back from the business network. Today, in Composer, this requires two calls:

- One to submit the transaction
- One to read the modified state of the asset

In Fabric, this could be done in a single call, with the modified asset being returned by the transaction. Performance testing has shown that the Composer way introduces a significant cost when compared to the cost of doing it in base Fabric.

What else could we enable?

The other thing that we do not have in Composer today is a way to write a query as code, rather than using the Composer query language. A good use case for this is being able to execute cross channel queries to collect a set of data, and then return that in one shot. That has been proven to be much faster than submitting queries to all of the individual channels, and aggregating the results on the client side.

We could introduce a "read-only" transaction processor function to enable this, once data can be returned from a transaction processor function. I think for now I'll leave that for another CIP however.

# Specification
First of all, the easy and non-controversial bit - modify transaction processor functions so that they can return a value, and that value will be serialized and sent to the client application when they use the `BusinessNetworkConnection.submitTransaction()` function, or they use the generated REST APIs for submitting a transaction.

The controversial bit as per Rocket.Chat discussion is to model the return types, and extend the transaction model so that a return type can be specified on a per transaction basis:

```
namespace org.acme

concept C {
    o String bar
}

transaction T {
    o String foo
} returns C
```

This was deemed too controversial as it was adding RPC stuff to what should be a pure type definition, so we (myself, @dselman, and @mttrbrts) discussed moving the returns information into a decorator. This is what we came up with:

```
@returns(C)
transaction T {
    o String foo
}
```

This made everyone as happy as they're going to get 😉 
It also enables "read-only" query processor functions via a similar mechanism:

```
@commit(never)
@returns(C)
transaction T {
    o String foo
}
```

I like `@commit` instead of `@readonly` because it allows for `never`, `default` (commit on success, the default behaviour), `always` (always commit, even if transaction fails).

A transaction processor function could then be implemented as:

```
/**
 * @param {org.acme.T} t the transaction
 * @returns {org.acme.C} the return data
 * @transaction
 */
async handleT(t) {
    // do some stuff 
    const c = getFactory().newConcept('org.acme', 'C');
    c.bar = t.foo;
    return c;
}
```

The `BusinessNetworkConnection.submitTransaction()` function would be extended to return the return data, if and only if the transaction had been modelled to return data:

```
const bnc = new BusinessNetworkConnection();
// do some stuff 
const t = bnc.getFactory().newTransaction('org.acme', 'T');
t.foo = 'hello';
const c = await bnc.submitTransaction(t);
assert(c.bar === 'hello');
```

The REST APIs would be extended so that the generated Swagger document shows that the REST API for `POST /api/org.acme.T` returns an instance of `org.acme.C`.

The input data would be the same:

```
{
    "$class": "org.acme.T",
    "foo": "hello"
}
```

The output data would change:

```
{
    "$class": "org.acme.C",
    "bar": "hello"
}
```

In future we could generate a Typescript API that allows code to be written like:

```
const myClient = new MyClient();
let t = myClient.newT();
t.foo = "hello";
let c = await t.submit();
assert(c.bar === 'hello');
```

# Rationale
There's plenty of discussion on Rocket.Chat about extending the modelling language to support a returns specification.

Read the discussion here: https://chat.hyperledger.org/channel/composer-contributors?msg=epmCbfqHbHm5fLM7T

# Backwards Compatibility
No backwards compatibility implications with the specification above; returns specification would be optional for transactions, and users could choose whether they wanted to use it or not.

# Test Requirements
Full unit testing, along with integration tests that cover passing data back from a transaction processor function to client applications via both the JavaScript APIs and the RESTful APIs.

# Implementation
Implemented by me!

# Copyright
This document is licensed under the Creative Commons Attribution 4.0 International Public License.

**Comment by alexvicegrab** [comment]
Fantastic, this will be rather helpful. And creating transactions that perform complex queries would also be very welcome!

**Comment by sstone1** [comment]
@dselman the problem with that is that everything about transactions in Composer today makes them look and smell a lot like RPC calls - I'm not sure anyone gets the impression that they're "async" in nature. 

- We have synchronous JavaScript and REST APIs that only return when the transaction has been committed to the blockchain network, or it has failed.
- The synchronous JavaScript and REST APIs wait for *all* of the transaction processor functions to execute, if any fail then the transaction is rejected.
- The synchronous JavaScript and REST APIs can already be abused to return data to the caller by adding the data to an error and throwing that from a transaction processor function (disgusting I know!).

> What happens if the network returns something other than a C? Serialization validation error at runtime?
Yep.

> Why not go the whole hog and model the RPC call itself, if that is what people want? E.g.
Wouldn't this just confuse the programming model? When would I use a `transaction` vs a `method`, when they both result under the covers in blockchain transactions? I'd be tempted to tell everyone just to use `method` because I don't understand what a `transaction` would buy me?

> This would be clearer IMO and cleanly separate the async/sync use cases. For example, there may be blockchains in the future that can only support one or the other, but not both.
We could just reject this at deployment time - e.g. if the blockchain network doesn't support returning data, then reject the deployment request. I had a quick sniff around and Ethereum, Fabric, and Sawtooth all support return data.

**Comment by dselman** [comment]
This is my central concern:
"Conflating a type definition with a method call signature feels wrong to me."

This means that those transaction definitions are now no longer reusable across networks, and can't really be used outside of the context of Composer.

For example, how could we create a standard library of IoT sensor transaction models? Why would we "pollute" the definition of a transaction type with this notion of a "return value" which is inherently nothing to do with the definition of a data model?

**Comment by sstone1** [comment]
> This means that those transaction definitions are now no longer reusable across networks

I'm not sure what "networks" means in this case - are you talking about Composer business networks, blockchain networks? What exactly isn't reusable?

> can't really be used outside of the context of Composer

It's still the *Composer* modelling language, you haven't pulled it out yet 😉 

> For example, how could we create a standard library of IoT sensor transaction models?

Don't specify the optional returns specification for a transaction? 😉 

> Conflating a type definition with a method call signature feels wrong to me

I think for Composer users, as opposed to Composer modelling language users, it's too late, we're already conflating things. The modelling language for a transaction defines the function name and the function input - just not the function output (which can't be defined anywhere). The transaction processor function provides the function implementation.

I can see several alternative solutions, so maybe we should discuss them - did I miss any?

1. Model functions instead of transactions:
  - Might introduce a new artefact type to the programming model.
  - IMHO, significant rework to avoid confusion of why transaction vs why function (similar to stored procedures vs functions in SQL).
  - Expensive follow on implications for ACLs, historian, playground, etc.
2. Determine return type by inspecting transaction processor functions.
  - This just feels weird to me; why do I have to inspect one thing for the function name and function inputs, and something else for the function outputs?
3. Don't model/determine return types at all, just pass through the return values from transaction processor functions (if any).
 - This could work, but at the expense of being unable to generate domain specific APIs and applications that handle the return values.
4. Do nothing.
 - This just gives users yet another reason not to use Composer, and instead use Fabric (our only supported blockchain platform at present).

**Comment by dselman** [comment]
I'm talking about Composer business networks. If I model an IoT sensor transaction for example and want to use that model across multiple networks. The return values from TP functions have nothing to do with the schema for the IoT sensor event.

Let's jump on a call and discuss.

**Comment by sstone1** [comment]
@dselman have updated the above with the `@returns` decorator as per our discussion.

**Comment by dselman** [comment]
We talked, we came to a mutual understanding, we move forward! 🤙
