### ISSUE TITLE
Access Denied When trying to start the network.

### ISSUE THREAD

**Issue by divyamsingh13** [hyperledger/composer#4167]
## Context

 composer network start --networkName landagreement --networkVersion 0.0.1 --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv1 --file networkadmin.card
Starting business network landagreement at version 0.0.1

Processing these Network Admins: 
	userName: admin

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: Unable to initalize channel. Attempted to contact 1 Peers. Last error was Error: Error: 2 UNKNOWN: access denied: channel [composerchannel] creator org [Org1MSP]
Command failed

## Your Environment

* Version used: 0.19.8

* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

**Comment by rjsadaye** [comment]
Is the fabric running? Make sure you're running v1.1 of hyperledger fabric.
You can run this command from the fabric directory to start fabric : 
`/teardownFabric.sh && ./startFabric.sh && ./createPeerAdminCard.sh`

**Comment by divyamsingh13** [comment]
@rjsadaye still the same error persists after running these commands .

**Comment by mandar-thoughti** [comment]
I also got same error.

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: Unable to initalize channel. Attempted to contact 1 Peers. Last error was Error: Error: 2 UNKNOWN: access denied: channel [composerchannel] creator org [Org1MSP]
Command failed

**Comment by sidladdha** [comment]
Same Error

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: Unable to initalize channel. Attempted to contact 1 Peers. Last error was Error: Error: 2 UNKNOWN: access denied: channel [composerchannel] creator org [Org1MSP]
Command failed

**Comment by kodepareek** [comment]
Am facing the same error when using the composer docker container

**Comment by LivioPompianu** [comment]
Same problem, I am following the [developer tutorial](https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial.html) (with Ubuntu 16.04 LTS) and the error persists after running the suggested commands.

**Comment by hossamabdullah** [comment]
I got this one also

**Comment by anallr** [comment]
me too!

**Comment by MonarthS** [comment]
Here you can find same issue, which should be helpful.

[link](https://github.com/hyperledger/composer-tools/issues/127)

**Comment by LivioPompianu** [comment]
Thank you @MonarthS, unfortunately the solutions suggested in the link did not work in my case.

**Comment by atul9911** [comment]
Facing the same issue

**Comment by soumendhar1310** [comment]
Same issue while invoking following command on my macbook,

composer network start --networkName tutorial-network1 --networkVersion 0.0.1 --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv1 --file networkadmin.card
Starting business network tutorial-network1 at version 0.0.1

Processing these Network Admins: 
	userName: admin

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: Unable to initalize channel. Attempted to contact 1 Peers. Last error was Error: Error: 2 UNKNOWN: Failed to deserialize creator identity, err MSP Org1MSP is unknown
Command failed

Composer Version is v0.19.12
Docker Version is 18.03.1-ce-mac65

Followed the steps mentioned in the other link, but did not work. Has anyone figured out the solution?

Regards

**Comment by soumendhar1310** [comment]
Found the solution...
Need to install new Fabric Version along with new Composer CLI and other associated components. Found following link, which works like a charm.

https://medium.freecodecamp.org/how-to-build-a-blockchain-network-using-hyperledger-fabric-and-composer-e06644ff801d

Regards

**Comment by davidkel** [comment]
This problem is usually down to the peer not joining the channel. If you are using composer fabric-dev-servers (A simple for development use only fabric) make sure you have the latest version and remove all docker containers and images first. Check the output when you run startFabric.sh to ensure the peer correctly joins the channel.

**Comment by rantoinne** [comment]
Please upgrade your composer-cli version to atleast 0.20.X

**Comment by adarshaJha** [comment]
upgraded but still facing the same error.

**Comment by ItsFunny** [comment]
the peer joined the channel  but still the same error
