### ISSUE TITLE
Write query in Playground

### ISSUE THREAD

**Issue by ArunNakkeeran** [hyperledger/composer#4177]
The Playground allows me to add queries in the Define tab, however the Test tab has no option to run these queries.

**Comment by rjsadaye** [comment]
You can't, they can be used in transactions or you can run them by generating a rest server using the command `composer-rest-server`

**Comment by ArunNakkeeran** [comment]
Thanks Raj. Have you done this? Can you give me the steps on how to run queries using REST server? I dont have much idea about the REST API.

**Comment by rjsadaye** [comment]
Refer to this, ,it's explained pretty well with examples:
[https://hyperledger.github.io/composer/latest/tutorials/queries](url)

**Comment by ArunNakkeeran** [comment]
Thanks Raj. I will try this out.
