### ISSUE TITLE
events.js:183       throw er; // Unhandled 'error' event       ^  Error: Card not found:

### ISSUE THREAD

**Issue by ghazanfarperdakh** [hyperledger/composer#4185]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Card not found: admin@my-basic-sample3.card
    at store.get.then.catch (/usr/local/lib/node_modules/generator-hyperledger-composer/node_modules/composer-common/lib/cardstore/walletbackedcardstore.js:74:27)
    at <anonymous>
this is coming from trying to generate an angular application through yo hyperledger-composer:angular even tho the card is there on the wallet list when i run playground locally or when i see composer card list its there

**Comment by sstone1** [comment]
@ghazanfarperdakh you have specified the file extension `.card` in the card name. The card name should not include the `.card` file extension.

**Comment by ghazanfarperdakh** [comment]
@sstone1  it doesn't work even without the .card extension ..it gives the same error

**Comment by sstone1** [comment]
@ghazanfarperdakh please post the output of `composer card list`. Did you re-run the generator specifying the card name without the `.card` file extension?

**Comment by ghazanfarperdakh** [comment]
yes I did ...still the same error...
![screenshot from 2018-06-28 14-58-24](https://user-images.githubusercontent.com/39822161/42027723-d02158ea-7ae3-11e8-9aa9-795c93bda2ae.png)

**Comment by prabhpahul** [comment]
Hello @sstone1 
I went through your video on hyperledger composer. However I am trying to run the same but getting the following error.
What else should I install to remove this error.?
<img width="948" alt="screen shot 2018-07-04 at 4 00 58 am" src="https://user-images.githubusercontent.com/18481051/42264588-18179c90-7f3f-11e8-8459-b0b975f8cba6.png">

**Comment by AnthonyCov** [comment]
Im getting the same error when tying to *yo hyperledger composer.

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Card not found: global-citizens-network
    at store.get.then.catch (C:\Users\\AppData\Roaming\npm\node_modules\generator-hyperledger-composer\node_modules\composer-common\lib\cardstore\walletbackedcardstore.js:74:27)
    at <anonymous>

**Comment by 5idu** [comment]
In Mac: try delete ~/.composer dict
it work for me.
