### ISSUE TITLE
Invalid JSON data. Found a value that is not a string

### ISSUE THREAD

**Issue by PureAngel** [hyperledger/composer#4186]
When I try to create a commodity using POST method, it keep returning Internet Server Error 500, saying "Invalid JSON data. Found a value that is not a string". Tried using JSON.stringify but it does not work. Is there any suggestion?

**Comment by vnextcoder** [comment]
Use this format to specify a Foreign Key  

Using the BNA mentioned in this Tutorial https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial  ,  the Commodity could be created using below JSON 

````
{
  "$class": "org.example.mynetwork.Commodity",
  "tradingSymbol": "MSFT",
  "description": "Microsoft",
  "mainExchange": "NASDAZ",
  "quantity": 4000,
  "owner":   "resource:org.example.mynetwork.Trader#456"
}
````

where as, Trader was created using below JSON 
````
{
  "$class": "org.example.mynetwork.Trader",
  "tradeId": "456",
  "firstName": "Bill",
  "lastName": "Gates"
}
````

Hope that helps you resolve the issue

**Comment by PureAngel** [comment]
Thanks! It works now.
