### ISSUE TITLE
Error while executing startfabric shell in azure (hyperledger-consortium)

### ISSUE THREAD

**Issue by hariharan1993** [hyperledger/composer#4187]
ERROR: for ca.org1.example.com  Cannot start service ca.org1.example.com: driver failed programming external connectivity on endpoint ca.org1.example.com (990bb8855ab011af785fceb16b46d93ef1ecdc9c9173f5e05ed0f715c7ec65d0): Bind for 0.0.0.0:7054 failed: port is already allocated

**Comment by davidkel** [comment]
This doesn't sound like it is anything to do with hyperledger composer. If it is azure, suggest you try contacting azure themselves
