### ISSUE TITLE
Got this error while executing the StartFabric shell

### ISSUE THREAD

**Issue by hariharan1993** [hyperledger/composer#4188]
ERROR: for ca.org1.example.com  Cannot start service ca.org1.example.com: driver failed programming external connectivity on endpoint ca.org1.example.com (af766ff039156900f87043cb84e712a8441d19a17b64af24162aac9798a35aab): Bind for 0.0.0.0:7054 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

**Comment by davidkel** [comment]
You already had something listening on port 7054 so the ca server can't start because it cannot use that port.
