### ISSUE TITLE
Upload of cards with certs in multiuser REST server leads to unexpected cert/private key removal in local card store

### ISSUE THREAD

**Issue by xuanyue202** [hyperledger/composer#4191]
Steps to reproduce:
- Use composer-cli to import a `admin_card` with certificate and privateKey
  - as a result, a folder `.composer/client-data/admin_card` is created. 
-  Launch rest server by `composer-rest-server -c admin_card -a true -m true`
- Login in Rest, and import the `admin_card` again via Rest POST /wallet/import
  - `.composer/client-data/admin_card`  will be deleted unexpectedly.
- As a result, if you want to restart the rest server, you will get en error since the card store has been damaged.

I think the problem is caused by the following line:

https://github.com/hyperledger/composer/blob/c46caa9fa4e519849f8e00517b9834280b5ec95f/packages/composer-admin/lib/adminconnection.js#L87

When I move it to Line 80, the problem fixed.

**Comment by davidkel** [comment]
I believe this issue was fixed in 0.19.13 and above.
