### ISSUE TITLE
install composer-cli at v0.19 or higher

### ISSUE THREAD

**Issue by hariharan1993** [hyperledger/composer#4192]
When i tried to execute createPeerAdminCard shell i encountered below error.

"No version of composer-cli has been detected, you need to install composer-cli at v0.19 or higher"

I have composer-cli installed
+ composer-cli@0.19.10 version
nvm version 0.33.8
npm version 6.1.0
node version v10.5.0

**Comment by rjsadaye** [comment]
Check your hyperledger version it should be 1.1. 
Version 1.1 works with composer v0.19. 
Also install node version 8.9. 
Composer is not compatible with node version higher than 8.9.

**Comment by hariharan1993** [comment]
Even after installing node 8.9 same error exits. 
node - 8.9.4
npm - 5.9.6
nvm -0.33.8
Please help

**Comment by davidkel** [comment]
either composer cli cannot be found on your path or composer-cli didn't install correctly. For example if you tried to install composer-cli using sudo.
Also noted that you are using a version of node v10 which isn't a supported version of node and is most likely the cause of your problem.

**Comment by MubasharIqbalBajwa** [comment]
I have the same issue. my node is 8.12.0 and composer 0.20 but I am getting this error when running ./createPeerAdminCard.sh

**Comment by riponbanik** [comment]
I am getting error for ubuntu 16.04. I am running it as vagrant user.  

npm install -g composer-cli@0.20

OS:

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

node-pre-gyp ERR! cwd /home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/composer-cli/node_modules/grpc
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.7.0
node-pre-gyp ERR! not ok
Failed to execute '/home/vagrant/.nvm/versions/node/v10.13.0/bin/node /home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/is_epollexclusive_available.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/load_file.oexec install script
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/lockfree_event.oinstall script
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/network_status_tracker.oscript
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/polling_entity.oinstall script
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_set_uv.oinstall script
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_set_windows.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_uv.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_windows.onstall script
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resolve_address_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resolve_address_uv.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resolve_address_windows.ocript
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resource_quota.oinstall script
In file included from ../deps/grpc/src/core/lib/iomgr/resource_quota.cc:19:0:
../deps/grpc/src/core/lib/iomgr/resource_quota.h:22:23: fatal error: grpc/grpc.h: No such file or directory
compilation terminated.
grpc.target.mk:394: recipe for target 'Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resource_quota.o' failed
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resource_quota.o] Error 1
make: Leaving directory '/home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/composer-cli/node_modules/grpc/build'
 ERR! build error ....] \ install: info lifecycle grpc@1.10.1~install: Failed to exec install script
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/home/vagrant/.nvm/versions/node/v10.13.0/bin/node" "/home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
gyp ERR! cwd /home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/composer-cli/node_modules/grpc
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/composer-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.10.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-11-02T00_59_26_499Z-debug.log

**Comment by oliverwhk** [comment]
> Check your hyperledger version it should be 1.1.
> Version 1.1 works with composer v0.19.
> Also install node version 8.9.
> Composer is not compatible with node version higher than 8.9.

@rjsadaye Is composer now supporting higher node version than 8.9?
