### ISSUE TITLE
The requested URL could not be retrieved

### ISSUE THREAD

**Issue by hariharan1993** [hyperledger/composer#4196]
I executed createPeerAdminCard succesfully  but i couldn't get any response in browser.

**The following error was encountered while trying to retrieve the URL: http://XXXXXXXXXXXXXXX.southindia.cloudapp.azure.com:8080/login**

Trust me i have added inbound ports for composer and api endpoints.

Please help me

**Comment by davidkel** [comment]
Please use Rocketchat or Stackoverflow for questions as hopefully people with experience with azure may be able to help. Github is for bugs and enhancement requests.
