### ISSUE TITLE
Not able to deploy a bna in local fabric server

### ISSUE THREAD

**Issue by prtk418** [hyperledger/composer#4198]
When trying to generate the rest api for the network using `composer-rest-server` and providing the card name ( `PeerAdmin@hlfv1` ), the following error is encountered:

`Discovering types from business network definition ...
Connection fails: Error: Error trying to ping. Error: No business network has been specified for this connection
It will be retried for the next request.
Exception: Error: Error trying to ping. Error: No business network has been specified for this connection
Error: Error trying to ping. Error: No business network has been specified for this connection
    at _checkRuntimeVersions.then.catch (/{$HOME}/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:813:34)
    at <anonymous>
`

### Steps to reproduce the error:

**Ran the following commands in order --**
1. `./stopFabric.sh`
2. `./tearDownFabric.sh`
3. `./teardownAllDocker.sh`
4. `./startFabric.sh`
5. `./createPeerAdminCard.sh`
6. `composer network install -a dist/iot-perishable-network.bna -c PeerAdmin@hlfv1`
7. `composer network start --networkName iot-perishable-network -v 0.1.12 -A admin -S adminpw -c PeerAdmin@hlfv1 --file networkadmin.card`
**Till now not found any errors**
8. `composer-rest-server`

`composer card list -c PeerAdmin@hlfv1` command results in --
![screenshot from 2018-06-28 17-22-28](https://user-images.githubusercontent.com/20238371/42032650-e3e49f72-7af7-11e8-946b-5ca502afe97a.png)

And my playground in localhost looks like below:
![screenshot from 2018-06-28 17-53-26](https://user-images.githubusercontent.com/20238371/42033987-3832ac14-7afc-11e8-8bf3-67b2907915eb.png)

**Comment by vishal3152** [comment]
card import ...  command failed because you are in a wrong directory. You are again trying to import card for hlfv1 network. All commands should be executed from /dist directory. Use a unique card name file instead of networkadmin.carf while running composer network start.. command

**Comment by davidkel** [comment]
The card PeerAdmin@hlfv1 is a special card which is used for fabric level interaction, ie installing a business network, starting a business network and upgrading a business network. To interact with the business network itself you need a card with an identity that has been registered with the business network and the card has a reference to the business network. 
From your information I see that you created a card file called `networkadmin.card` you need to import this card into the card store using `composer card import`. Now you will have a card that is capable of interacting with the business network you have started.

**Comment by prtk418** [comment]
@davidkel the `networkadmin.card` is exported from `PeerAdmin@hlfv1` card , so according to you i need to create a new card and use it for `composer install` and `composer start` , but `composer card create` requires a `connection.json` file, which is am not able to find.

**Comment by davidkel** [comment]
@prtk418 I don't know what you mean when you say networkadmin.card is exported from PeerAdmin@hlfv1. networkadmin.card is not exported, it is a new card file that needs to be imported into the card store. networkadmin.card represents the identity you specified using the -A/-S parameters when you performed the start

**Comment by prtk418** [comment]
@davidkel ok tell me when is networkadmin.card created, and where to locate this file

**Comment by davidkel** [comment]
It's created in your current working directory if the start request completes successfully. You might want to try out the tutorials for example https://hyperledger.github.io/composer/latest/tutorials/deploy-to-fabric-single-org which provide more insight into the whole environment

**Comment by prtk418** [comment]
@davidkel Thanks for the reference, but i understood the problem now, as per the doc after running the `composer network start` the `user@network-name.card` is generated right? 
But when i ran the start command the card file was generated.

**Comment by davidkel** [comment]
You aren't invoking `composer network start` correctly. the short version of `--networkVersion` is `-V` not '-v`

**Comment by saranya-satyavolu** [comment]
> When trying to generate the rest api for the network using `composer-rest-server` and providing the card name ( `PeerAdmin@hlfv1` ), the following error is encountered:
> 
> `Discovering types from business network definition ... Connection fails: Error: Error trying to ping. Error: No business network has been specified for this connection It will be retried for the next request. Exception: Error: Error trying to ping. Error: No business network has been specified for this connection Error: Error trying to ping. Error: No business network has been specified for this connection at _checkRuntimeVersions.then.catch (/{$HOME}/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:813:34) at <anonymous> `
> ### Steps to reproduce the error:
> 
> **Ran the following commands in order --**
> 
>     1. `./stopFabric.sh`
> 
>     2. `./tearDownFabric.sh`
> 
>     3. `./teardownAllDocker.sh`
> 
>     4. `./startFabric.sh`
> 
>     5. `./createPeerAdminCard.sh`
> 
>     6. `composer network install -a dist/iot-perishable-network.bna -c PeerAdmin@hlfv1`
> 
>     7. `composer network start --networkName iot-perishable-network -v 0.1.12 -A admin -S adminpw -c PeerAdmin@hlfv1 --file networkadmin.card`
>        **Till now not found any errors**
> 
>     8. `composer-rest-server`
> 
> 
> `composer card list -c PeerAdmin@hlfv1` command results in --
> ![screenshot from 2018-06-28 17-22-28](https://user-images.githubusercontent.com/20238371/42032650-e3e49f72-7af7-11e8-946b-5ca502afe97a.png)
> 
> And my playground in localhost looks like below:
> ![screenshot from 2018-06-28 17-53-26](https://user-images.githubusercontent.com/20238371/42033987-3832ac14-7afc-11e8-8bf3-67b2907915eb.png)

I am getting the same error, how did you happen to solve it
