### ISSUE TITLE
node-plantuml should be a dev-dependency in composer-common

### ISSUE THREAD

**Issue by mttrbrts** [hyperledger/composer#4199]
`node-plantuml` is only used for the Composer doc generation but is listed as dependency. This 
bloats all dependent packages. The `cost-of-modules` tool calculates that node-plantuml accounts around 75% of the total dependency size at 16MB!

![image](https://user-images.githubusercontent.com/7544022/42036977-fd896714-7ade-11e8-83ab-5f306a949308.png)

## Possible Fix
Change `node-plantuml` to a dev-dependency in composer-common

* Version used: 0.19.8

**Comment by jt-nti** [comment]
@mbwhite does this get used in the `composer generator docs` command?

**Comment by davidkel** [comment]
node-plantuml as far as I can see is only used for a tool inside common called plantumltoimage.js which I doubt we document externally. It then is referenced in a script only for doc generation for the website but as far as I can see whatever image it creates (if indeed it is ever run) aren't referenced anywhere. If it is I can't find them.
So we could either just remove all this completely, or move it to the website package and take it out of common.

**Comment by mttrbrts** [comment]
Thanks @mbwhite, @davidkel & @jt-nti, what do you suggest we do to close this out? 

1. Make this a dev-dependency in composer-common (As in #4200 )
2. Move the dependency and the script to the website package
3. Remove the dependency, script and script references?

I'm happy to update the PR.

**Comment by nklincoln** [comment]
... Is this not used by the VSCode plugin?

**Comment by m-g-k** [comment]
Yes, the VSCode plugin does use this currently to generate inline UML diagrams

**Comment by m-g-k** [comment]
As long as the interfaces were unchanged I should be able to make it a dependency of the plugin itself and carry on as before.

**Comment by m-g-k** [comment]
Just tested the plugin and it works fine!

**Comment by mttrbrts** [comment]
Many thanks @m-g-k and @nklincoln Cicero has now gone on a diet! https://github.com/accordproject/cicero/pull/156

As #4200 has been merged and VSCode plugin works, I'll close this issue
