### ISSUE TITLE
Invalid status code returned by the REST server

### ISSUE THREAD

**Issue by uluhonolulu** [hyperledger/composer#4201]
## Context
If I issue a `GET` request to a nonexistent entity (something not defined in my model), the server returns a 404 response, which is easy to confuse with a correct request for a missing object. For example, if my model has `SampleAsset`, and I `GET /SampleShmasset/1`, the response is 404, which is the same as if I had `SampleShmasset` defined in my model, but there wasn't an instance with id=1.

Another example is when the Fabric hasn't been started. It returns 404 for every request.

I realize that the response body has an explanation of what happened really, but having to parse the error message is not cool. In addition, the message is a bit misleading, it says, `There is no method to handle GET ...`. Looks like it's a message from Loopback.

## Expected Behavior
The REST Server should return `400 Bad Request`, or `405 Method Not Allowed`.

## Actual Behavior
The REST server returns 404 Not Found

## Possible Fix
I can work on a PR, or try and fix it with Loopback if they agree it's a bug.

## Your Environment

* Version used: 0.19.5

**Comment by jt-nti** [comment]
404 does seem more appropriate since the request was fine and GET is allowed, but the resource really doesn't exist.

Having said that, it might be nice to add something to the json error object you get back to provide additional information instead of the stack.
