### ISSUE TITLE
No way to disconnect the wallet

### ISSUE THREAD

**Issue by PPCM** [hyperledger/composer#4213]
## Context
I made a new wallet for MongoDB (based on composer-wallet-redis), but there is no way to say to the wallet to disconnect.
So especially for my wallet, I have 2 solutions:
- Connect/diconnect on each action -> poor performance
- Connect on first action/Never disconnect -> an application never end

The objectif is to stay in the spirit of the wallet, I would not to do something specific to my wallet

Is there something in plan for that or a discussion?

## composer-wallet-mongodb
The new wallet can be found here: https://github.com/PPCM/composer-wallet-mongodb

**Comment by mbwhite** [comment]
Thank you for creating a Wallet for mongodb..
I see your point regarding the disconnect; our current implementations have so far not needed this AFAIK.

When either the network connection or admin connection is disconnected, they could pass that onto the cardstore - which could disconnect if needed. 

Would you like to tackle this extra feature @PPCM  :-)
