### ISSUE TITLE
Accessing a fabric network from a different machine 

### ISSUE THREAD

**Issue by ghazanfarperdakh** [hyperledger/composer#4217]
"I implemented hyperledger composer tutorial and create a simple business network definition and deploy it on through composer and implement it's rest API's through composer-rest-server. Now I want to add one more peer to it on a different local machine which can access blockchain I created previously, so my question is How can I achieve that a different peer node (another local machine) connected to blockchain I created in the composer tutorial?""I implemented hyperledger composer tutorial and create a simple business network definition and deploy it on through composer and implement it's rest API's through composer-rest-server. Now I want to add one more peer to it on a different local machine which can access blockchain I created previously, so my question is How can I achieve that a different peer node (another local machine) connected to blockchain I created in the composer tutorial?"

**Comment by ghazanfarperdakh** [comment]
@sstone1  @davidkel ...Need your help sir

**Comment by mbwhite** [comment]
Can I suggest you check on the RocketChat Channel https://chat.hyperledger.org/channel/composer please.  There are resources and folks that will help

**Comment by ghazanfarperdakh** [comment]
Appreciate it
