### ISSUE TITLE
Support Fabric 1.2

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#4238]
_As a_ business network developer
_I want_ to deploy to Fabric 1.2
_so that_ I can take advantage of new Fabric features

A few tasks off the top of my head; probably lots more that should be added:

- [x] Update fabric-tools to install Fabric 1.2
- [x] Update dependencies to fabric-shim@1.2 and re-test + fix
- [x] Doc updates for Fabric version
- [x] Build changes to maintain Composer 0.19.x (Fabric 1.1) and Composer 0.20.x (Fabric 1.2) streams in parallel, including docs
- [x] Update [composer-sample-networks](https://github.com/hyperledger/composer-sample-networks) for Composer 0.20

**Comment by bhayward93** [comment]
I would love to see this. I'm a bit pigeonholed into using v1.2 of Fabric, but really enjoy working on it with Composer.

**Comment by bestbeforetoday** [comment]
@jim-mason-dmxio I've just started looking at it. It depends very much on how many bumps in the road and distractions I hit. No promises but I'd hope to get into a release within the next couple of weeks.

**Comment by MarcusHong** [comment]
"fabric-client@1.3.0-snapshot.7" has many bugs. For example, it doesn't have "getEventHubsForOrg" method. Why don't you test on 1.2.0?

**Comment by handaanmol** [comment]
@bestbeforetoday - Can I go ahead and run the composer from your repository, Is it reliable to run at the moment with no major bugs?

**Comment by bestbeforetoday** [comment]
I've just merged the changes to _hyperledger/composer_ for Fabric 1.2 support. Once that shakes out, you should see _unstable_ versions at _0.20.x_ that run with Fabric 1.2. There is an update to the _fabric-dev-servers_ scripts for standing up a Fabric 1.2 development environment sitting in a [pull request](https://github.com/hyperledger/composer-tools/pull/139) but not yet merged since this changes the default Fabric version to 1.2 and could cause problems for people using the _latest_ (0.19.x) release of composer, which needs Fabric 1.1.
