### ISSUE TITLE
Sever returns status code 500 when using PUT API

### ISSUE THREAD

**Issue by AiDirex** [hyperledger/composer#4241]
## Context
When I try to edit an entity using the composer-rest-server PUT API, the server returns status code 500. but when I try to fetch the resource using GET the edited entity is returned. so the server should return 200.

I have just followed steps from [here](https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial) and [here](https://hyperledger.github.io/composer/latest/tutorials/queries). my models and logics and acl looks same as the examples.

Response body:
```
{
  "error": {
    "statusCode": 500,
    "name": "TypeError",
    "message": "Cannot read property 'tradeId' of undefined",
    "stack": "TypeError: Cannot read property 'tradeId' of undefined\n    at /home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/dao.js:3106:25\n    at doNotify (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)\n    at doNotify (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)\n    at doNotify (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)\n    at doNotify (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)\n    at Function.ObserverMixin._notifyBaseObservers (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:178:5)\n    at Function.ObserverMixin.notifyObserversOf (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)\n    at Function.ObserverMixin._notifyBaseObservers (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)\n    at Function.ObserverMixin.notifyObserversOf (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)\n    at Function.ObserverMixin._notifyBaseObservers (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)\n    at Function.ObserverMixin.notifyObserversOf (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)\n    at Function.ObserverMixin._notifyBaseObservers (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)\n    at Function.ObserverMixin.notifyObserversOf (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)\n    at replaceCallback (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/dao.js:3103:17)\n    at ensureConnected.then.then.then (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/loopback-connector-composer/lib/businessnetworkconnector.js:596:17)\n    at <anonymous>"
  }
}
```
## Expected Behavior
The server should return staus code 200.
## Actual Behavior
The server returns status code 500 but the entity is edited
## Possible Fix
The stack trace points to the line 3106 of dao.js file. I looked at it and it seems something for observers (Model.notifyObserversOf('loaded', ctx, ...)). ctx.data is undefined so the server throws an error. Edit operation is sucessfull but the observer fails.
## Steps to Reproduce
I have just followed steps from [here](https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial) and [here](https://hyperledger.github.io/composer/latest/tutorials/queries). my models and logics and acl looks same as the examples.
## Your Environment
composer: 0.9.12
node: 8.11.3
OS: Ubuntu Xenial 64bit

**Comment by labcoinpoc** [comment]
Same Error
```
"error": {
    "statusCode": 500,
    "name": "TypeError",
    "message": "Cannot read property 'userId' of undefined",
    "stack": "TypeError: Cannot read property 'userId' of undefined\n    at ........
  }
```

**Comment by AiDirex** [comment]
I figured out that the error occurs only when using composer-rest-server CLI, but it doesn't happen with the generated loopback codes.

**Comment by sergey-koba-mobidev** [comment]
I can confirm this error is still reproducible

**Comment by rthatcher** [comment]
I have not been able to reproduce this error with v0.19.15, or v0.20.1

Are you using v0.19.12?  (Your description says 0.9.12 - is that a typo ? :-) )

I have seen it [reported here](https://stackoverflow.com/questions/52058371/in-composer-rest-server-put-request-is-throwing-cannot-read-property-productid) before with v0.19.12 of Composer.  It was apparently cleared by upgrading to a newer version of Composer.

I wondered if it was also a problem with lots of old test data with a modified model file that changed a few times - but I didn't have any real evidence for that.

**Comment by AiDirex** [comment]
@rthatcher Yes, I used v0.9.12.
I haven't had time to test newer versions.

**Comment by davidkel** [comment]
closing as no further updates and unable to be recreated.
