### ISSUE TITLE
Modeling language: Primitive datatype uint 256

### ISSUE THREAD

**Issue by b509** [hyperledger/composer#4243]
In the language coverage of the modeling language it would be nice to have an additional primitive - similar to uint 256 in Ethereum - for hashes. Yes, the scenario can be approximated with a string, but for a string there are less clear rules for comparison. E.g. when the hash gets padded or uses small/big letters.

**Comment by dselman** [comment]
I think it mostly depends on what operations you want to support. If it is purely a 256-bit data structure then the existing `String` data type may work for you. You could even use a `regex` validator to impose constraints on the length and format of the string. If you want to perform mathematical operations on those 256-bit unsigned ints then we likely need some sort of integration with BigNumber (see below).

Notes:
web3 uses BigNumber: https://github.com/MikeMcl/bignumber.js/
https://ethereum.stackexchange.com/questions/33832/negative-number-passed-to-function-with-uint-parameter
