### ISSUE TITLE
Syntax Error "Unexpected token" in logic.js while creating .bna file

### ISSUE THREAD

**Issue by Jonbi2** [hyperledger/composer#4244]
## Context
I'm trying to generate a .bna file following this -> https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial.html tutorial. 
But when I'm running the command 'composer archive create -t dir -n .'  Instead of generating a new .bna file I get the following error: 
code in logic.js : 
`/**
 * Track the trade of a commodity from one trader to another
 * @param {org.example.biznet.Trade} trade - the trade to be processed
 * @transaction
 */
async function tradeCommodity(trade) {
    trade.commodity.owner = trade.newOwner;
    let assetRegistry = await getAssetRegistry('org.example.biznet.Commodity');
    await assetRegistry.update(trade.commodity);
}

console.log("Node?");
`
`SyntaxError: Failed to parse /Users/marcello/tutorial-network/lib/logic.js: Unexpected token (6:6)
`
It looks like composer doesn't recognise the async syntax. 
When I run this code using node everything is ok. 

## Expected Behavior
Creation of tutorial-network.bna
## Actual Behavior
I get this error 
`SyntaxError: Failed to parse /Users/marcello/tutorial-network/lib/logic.js: Unexpected token (6:6)
`## Possible Fix

## Steps to Reproduce
First three steps of this tutorial
 https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial.html

## Your Environment

* Version used:
node : v8.11.3
npm : 5.6.0
composer : v0.16.6
Docker version 18.03.1-ce, build 9ee9f40
* Operating System and version (desktop or mobile):
Mac OS 10.13.4
https://github.com/Jonbi2/marcellos-hyperledger-composer-repo

**Comment by jt-nti** [comment]
Hi @Jonbi2, `async` was not supported in version 0.16.6 (I think it was added in 0.17.0)

The developer tutorial for the 0.16.6 version of Composer is here -> https://github.com/hyperledger/composer/blob/efecda254343af66f24b89ba6b7895eec3e75c77/packages/composer-website/jekylldocs/tutorials/developer-tutorial.md
