### ISSUE TITLE
Proposal: JSON Primitive support in CML

### ISSUE THREAD

**Issue by mttrbrts** [hyperledger/composer#4249]
Occassionally, there are scenarios where it would be convenient to model an arbitrary JSON object as a property of a CML class.

Currently, the alternative is to model JSON as a `String` an then assign a string serializations of the object, e.g.
```
concept MyConcept {
 o String json
}
```
```js
myConcept.json = JSON.stringify(object);
```

I propose adding a JSON primitive to the Composer Modelling Language. For example:
```
concept MyConcept {
 o JSON json
}
```
or
```
concept MyConcept {
 o Object json
 o Object[] array
}
```
To allow direct assignment as follows:
```js
myConcept.json = {
    foo: 'bar',
    baz: Symbol('composer'),
    f: () => {},
}
```
This would give TPFs or other client applications using CML greater flexibility to assign more complex types (such as `Symbol`s and `function`s)  to objects. This could be useful to capture arbitrary data in CML whose structure is not known at design time, e.g. errors produced by third-party libraries.

**Comment by dselman** [comment]
I like this, however, we do have to implement the serialization/validation/persistence, so I think the JSON data type would have to be purely data (not functions).
