### ISSUE TITLE
ERR Connection fails: Error: Error trying to ping. Error: Composer runtime (0.19.12) is not compatible with client (0.19.5)

### ISSUE THREAD

**Issue by petercrippsIBM** [hyperledger/composer#4250]
## Context
Attempting to deploy a composer REST Server to use my Hyperledger network deployed onto the IBM Blockchain Starter Plan on IBM Cloud but get the above error from the CF 'start' command.

## Expected Behavior
Composer REST server should start.

## Actual Behavior
I've deployed a network, which is running okay, and the REST server using the command:

`bx cf push art-ledger --docker-image ibmblockchain/composer-rest-server -c "composer-rest-server -c admin@art-ledger -n never -w true" -i 1 -m 256M --no-start --no-manifest`

I get a message back saying "there are no running instances of this app" which I think is as it should be. When I then run the start command:

`bx cf start art-ledger`

After a minute or so I get a FAILED message with a line in the log output as follows:

*ERR Connection fails: Error: Error trying to ping. Error: Composer runtime (0.19.12) is not compatible with client (0.19.5)*

If I ping the network with the command:

`composer network ping --card admin@art-ledger`

It does indeed indicate the composer runtime is 0.19.12.

I don't specify a version number in the `push` command and I assume I just get the latest (i.e. 0.19.5). I did try specifying 0.19.12 but that did not exist.

## Possible Fix
Incompatible version numbers between Composer and Composer REST Server.

## Steps to Reproduce
Description as above.

## Existing issues
Some similar issues exist but mainly to do with deploying locally in Containers not on Starter Plan.

## Context
Cannot start REST server.

## Your Environment
* IBM Cloud Blockchain Starter Plan
* Fabric v1.1
* Composer Runtime v 0.19.12
* Composer REST Server v0.19.5

**Comment by andystanley** [comment]
Change this <code>ibmblockchain/composer-rest-server</code> to <code>ibmblockchain/composer-rest-server:0.19.5</code>.  If you go to the [IBM Blockchain Docker repo](https://hub.docker.com/r/ibmblockchain/composer-rest-server/tags/) you'll be able to see the different versions you can specify.

**Comment by petercrippsIBM** [comment]
Thanks Andy, I reverted to 0.19.5 of everything and this now work.

**Comment by BinduMaharudrappa** [comment]
When i use ibmblockchain/composer-rest-server:0.19.5 docker issue will not be there, but I get this error 

   2019-03-04T13:14:09.08+0100 [APP/PROC/WEB/0] ERR Connection fails: Error: Error trying to ping. SyntaxError: Unexpected end of JSON input
   2019-03-04T13:14:09.08+0100 [APP/PROC/WEB/0] ERR It will be retried for the next request.

Please help out.
thank you
