### ISSUE TITLE
No way to update connection.json when a new peer is added while composer is already running

### ISSUE THREAD

**Issue by ktiwary2** [hyperledger/composer#4260]
No way to update connection.json when a new peer is added while composer is already running

I think there should be a function that updates the connection.json file if a new peer is added to network after the hyperledger composer is already running. Say the composer is running and I use cryptogen extend command to make certs for the new peer and then add it to the channel. 

Now I want to add that peer's information onto the connection.json file so that the composer can talk to that peer as well. Currently there are no way to do that and the running the commands` composer card delete `and `composer card create` with the new connection.json file with specs from the newly created peer doesn't really update the network that is currently being run? Is there any way to do this?

**Comment by vitorduarte** [comment]
This is an important feature. When I need to add a new peer to a running network, I open the bna file and change by hand my connection.json. This doesn't sound well, but works. I hope that this could be implemented in composer

**Comment by vitorduarte** [comment]
This feature could be extended to add a new org too

**Comment by ktiwary2** [comment]
I agree with you, and it annoying to write long scripts which just perform this one thing when it'd be easier for composer to provide this functionality.

**Comment by ktiwary2** [comment]
just an FYI there's a very `hacky` way to do this if any one's still interested.
