### ISSUE TITLE
Hyperledger Composer Yeoman generator fails to generate app

### ISSUE THREAD

**Issue by mbnsrwr** [hyperledger/composer#4270]
![screenshot from 2018-07-24 18-21-24](https://user-images.githubusercontent.com/33069230/43141120-96eee552-8f6e-11e8-8807-581fe4d5fcd0.png)

**Comment by davidkel** [comment]
Unfortunately there is no information provided as to what caused your error. You need to provide as simple recreate or your bna file so that it can be recreated. Also you need to provide which version of the composer generator you are using.

**Comment by davidkel** [comment]
Closing as no further information provided
