### ISSUE TITLE
When using google OAuth 2.0 authorization, docker container mongo is in conflict with fabric

### ISSUE THREAD

**Issue by Dearkano** [hyperledger/composer#4272]
Trying to use google OAuth 2.0 service as introduced in docs and do so step by step as the tutorial requires, but have some trouble with trouble.

If I start Fabric-dev-server network in the previous step, starting mongo docker image as the command ```docker run -d --name mongo --network composer_default -p 27017:27017 mongo```,

Error message like 
```
Error response from daemon: Conflict. The container name "/mongo" is already in use by container "02218fdb91c5a6af9103b3b6a42969c17b1e6f41fa25d756f2f7bf33b59c8d48". You have to remove (or rename) that container to be able to reuse that name.
```
Then I tried to restart docker service and start mongodb docker container, and install the trade.bna, error TIMEOUT would happen. Error message is 
```
✖ Installing business network. This may take a minute...
Error: Error trying install business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT
Command failed
```

At last, I tried to start Fabric network first and then install the trade.bna, it will success but running mongo docker container will fail, if not, how can I install the trade.bna without timeout error?

My question is, should both fabric network and mongo container start at the same time? If so, how to deal with the conflict problem?

Thanks

**Comment by davidkel** [comment]
Please ask questions on RocketChat or Stackoverflow. Github is for bugs and enhancement requests.
