### ISSUE TITLE
Assets and Participants can't be identified by an integer

### ISSUE THREAD

**Issue by mhamzawey** [hyperledger/composer#4274]
When we create any Participant or Asset we can't identify it by an Integer field.  Is there a possibility to do so? And is there a way to make it auto-incremental?
![image](https://user-images.githubusercontent.com/5594052/43204557-841c9c4a-9021-11e8-93d9-544d9c120bcb.png)

## Context

Participants and Assets can be identified by auto-increments or extended to do so.
## Expected Behavior

Making it possible to create Assets/Participants identified by an integer ID

**Comment by ronaldlong46** [comment]
I think (someone correct me if I'm wrong) but if IDs were auto-incremental wouldn't that cause mismatches among other peers in the network that were also doing auto-incremental IDs?

**Comment by dselman** [comment]
You are correct. Auto increment assumes a global lock which is anathema to distributed systems.

**Comment by mhamzawey** [comment]
Thank you guys.

**Comment by medoamanquer** [comment]
change the name to other than "id" and see if it fixed your problem
the field which is used in "identified by" should be a string

**Comment by davidkel** [comment]
Sorry, but there is no intention to allow identified fields to be anything other than a string. 
closing
