### ISSUE TITLE
Hyperledger Composer Version 1.1.0

### ISSUE THREAD

**Issue by pallavrj** [hyperledger/composer#4293]
@hyperledger-github 
Issue: Get below error message while running network install command. 

Error Log:
$ composer network install --card PeerAdmin@hlfv1 --archiveFile land-registry@0.0.1.bna
x Installing business network. This may take a minute...
Error: Error trying install business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 14 UNAVAILABLE: Connect Failed
Command failed

Steps Taken: 
1. Reinstalled Dev Environment

Version Details:
1. Fabric_Version=hlfv11
2. PeerAdmin Card= hlfv1
3. Docker Toolbox Version: 18.03.0-ce

Container Details: 

CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS              PORTS                                            NAMES
a3a024472fb4        hyperledger/fabric-peer:x86_64-1.1.0      "peer node start"        About an hour ago   Up 17 minutes       0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp   peer0.org1.examp
400016fb1823        hyperledger/fabric-couchdb:x86_64-0.4.6   "tini -- /docker-ent"   About an hour ago   Up 17 minutes       4369/tcp, 9100/tcp, 0.0.0.0:5984->5984/tcp       couchdb
2b1ff5a52cf3        hyperledger/fabric-ca:x86_64-1.1.0        "sh -c 'fabric-ca-se"   About an hour ago   Up 17 minutes       0.0.0.0:7054->7054/tcp                           ca.org1.example.c
3920ce2f4321        hyperledger/fabric-orderer:x86_64-1.1.0   "orderer"                About an hour ago   Up 17 minutes       0.0.0.0:7050->7050/tcp                           orderer.example.

Image Details: 

REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
hyperledger/fabric-ca        x86_64-1.1.0        72617b4fa9b4        4 months ago        299MB
hyperledger/fabric-orderer   x86_64-1.1.0        ce0c810df36a        4 months ago        180MB
hyperledger/fabric-peer      x86_64-1.1.0        b023f9be0771        4 months ago        187MB
hyperledger/fabric-ccenv     x86_64-1.1.0        c8b4909d8d46        4 months ago        1.39GB
hyperledger/fabric-couchdb   x86_64-0.4.6        7e73c828fc5b        5 months ago        1.56GB

Please guide me to solve this issue. Really appreciate any help.

**Comment by medoamanquer** [comment]
send to me your .bna file to check if the error is reproducible
a.abdelazizcsds[at]gmail[dot]com

**Comment by davidkel** [comment]
More information about this type of setup issue can be found at
https://github.com/hyperledger/composer-knowledge-wiki/blob/latest/knowledge.md
also search on stackoverflow and rocketchat

github is only for bugs and enhancement requests, so closing.
