### ISSUE TITLE
As a composer developer, Can i use third-party javascript libraries like require ('fs') in my transactions

### ISSUE THREAD

**Issue by ghazanfarperdakh** [hyperledger/composer#4294]
This is more of a feature request than a bug :
When developing composer transactions, I wish to use third-party javascript libraries for example require('fs')

**Comment by ghazanfarperdakh** [comment]
@davidkel help needed!!

**Comment by ghazanfarperdakh** [comment]
If we write an external node js app integrated with composer can then we use these javascript libraries and use them in transactions processes

**Comment by davidkel** [comment]
There are no restrictions for client side applications. For TP functions in your business network (ie what you install and instantiate into a fabric network) you cannot use require().

**Comment by ghazanfarperdakh** [comment]
can u kindly recommend any article or reference any source code on github or else where for establishing connection in client side app with composer .. i tried to follow the official doc https://hyperledger.github.io/composer/latest/applications/node.html
I  understood the api's but could not put them into practice . Apologies for such a long post but I'm in dire need of saving here

**Comment by davidkel** [comment]
being able to use require in TP functions is a duplicate of #3169 so closing.
