### ISSUE TITLE
npm install composer-cli fails to download files (HTTP 403)

### ISSUE THREAD

**Issue by esophagus-now** [hyperledger/composer#4295]
I am unable to install composer-cli using npm. I think this is because the install script tries to download a file but gets an HTTP 403 message

## Context

The exact error I get is the following:
```
node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.1/node-v64-linux-x64-glibc.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.1 and node@10.5.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Pre-built binaries not installable for grpc@1.10.1 and node@10.5.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Hit error Connection closed while downloading tarball file
```

## Expected Behavior

The npm installation should have finished with no errors

## Actual Behavior

The installation did not complete due to some kind of error.

## Possible Fix

Possibly the installation scripts contain broken links, which would need to be fixed.

## Steps to Reproduce

1. I simply ran `npm i composer-cli` in my project directory.
2. You can see the entire output of the install command [here](https://pastebin.com/HJZJQ41v).

## Existing issues

- [ ] [Tried this solution, but didn't work (the build from source ended up failing)](https://stackoverflow.com/questions/48866375/errorunable-to-install-composer-cli)

## Your Environment

* Environment name and version (e.g. Chrome 39, node.js 5.4): npm version 6.2.0, node.js v10.5.0
* Operating System and version (desktop or mobile): Manjaro Linux

**Comment by esophagus-now** [comment]
Using nvm, I downgraded to node 9.0.0. I was able to install all the tools into my local project directory. I was even able to ask nvm to go back to using the latest version of node and things still appeared to be working.

**Comment by guanbo** [comment]
For now, v1.1 is work well with node long term support(v8.11). You should follow official guid of [install perequest](https://hyperledger.github.io/composer/latest/installing/installing-prereqs.html)

**Comment by rthatcher** [comment]
Not a Composer problem, and @esophagus-now is up and running.

**Comment by RishiRomeo** [comment]
i'm getting this odd error on mine: 

Error: Command failed: C:\Users\USER\AppData\Local\Continuum\anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3]

I'm guessing this means my version of py is an issue? i have 3

**Comment by rthatcher** [comment]
Composer is not supported on Windows.  Support is for Linux and Mac as per the install docs.

**Comment by MeganEden** [comment]
I am getting the exact same error as the originator of this Issue.

The environment details are as follows:

Node:           v10.13.0
npm:            6.4.1
Docker:         Docker version 18.06.1-ce, build e68fc7a
Docker Compose: docker-compose version 1.13.0, build 1719ceb
Python:         Python 2.7.12

The operating system and version is
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

This is running virtually in VMware Workstation 15 Player

And here's the log file
[2018-11-01T03_59_18_920Z-debug.log](https://github.com/hyperledger/composer/files/2537168/2018-11-01T03_59_18_920Z-debug.lo

Any assistance you can provide would be greatly appreciated. I'm trying to the complete the edX course LFSx - Blockchain for Business and can't get past this point. I'm more business than technical so I'm sure it's an easy problem for someone who knows what they're doing.

**Comment by rthatcher** [comment]
I haven't looked at the log, but I would think the problem is likely to be:
`Node: v10.13.0`
Composer supports Node 8.  These 2 commands should help before installing composer ...
`nvm install 8` followed by `nvm use 8`

**Comment by MeganEden** [comment]
Hi Rob,
I did use the pre-reqs. 
Thank you so much. That's worked! :)

**Comment by y0unghe** [comment]
> I haven't looked at the log, but I would think the problem is likely to be:
> `Node: v10.13.0`
> Composer supports Node 8. These 2 commands should help before installing composer ...
> `nvm install 8` followed by `nvm use 8`
> 
> (I don't know if you used the pre-reqs script - but that was corrected yesterday or today to explicitly specify node 8.)

Fixed a lot of npm install errors. The doc should indicates composer only works with node 8.
