### ISSUE TITLE
passport-local

### ISSUE THREAD

**Issue by aparolini** [hyperledger/composer#4297]
Unable to use the passport-local strategy

## Context

I am trying to secure the REST server using Passport Local strategy using the en variable `COMPOSER_PROVIDERS` like this:
```
 export COMPOSER_PROVIDERS='{
"local": { 
    "provider": "local", 
    "module": "passport-local", 
    "usernameField": "username", 
    "passwordField": "password", 
    "authPath": "/auth/local", 
    "callbackURL":"/auth/local/callback",
    "successRedirect": "/", 
    "failureRedirect": "/", 
    "setAccessToken": true, 
    "callbackHTTPMethod": "post" 
   }
}
```
Then run my REST Server with `composer-rest-server -n never -c admin@rinku -m true -a true`, but when I go to `http://localhost:3000/auth/local/` I get a 

"Cannot GET /auth/local/","status":404".

Do you know what do I miss ?

Thank you.

Antonio
## Expected Behavior
`http://localhost:3000/auth/local/` should show you a login form

## Actual Behavior
"Cannot GET /auth/local/","status":404".

## Your Environment
node 8.11
Composer v0.19.12

**Comment by hingjlee** [comment]
https://hyperledger.github.io/composer/latest/integrating/enabling-rest-authentication

**Comment by davidkel** [comment]
passport-local doesn't work out of the box. A lot don't as they are designed to be driven by user code, but it's possible to wrap one with your own code and make it look like a customised passport plugin which can work with the rest server (an example of jwt can be found using google). Here are some references around passport-local

https://stackoverflow.com/questions/50349925/composer-rest-server-with-passport-local-strategy 

https://stackoverflow.com/questions/49409675/hyperledger-composer-rest-server-local-passport-strategy

https://gist.github.com/michaelfreund/edc147f1abefb39753496856306aa076

**Comment by davidkel** [comment]
As this isn't a bug or enhancement, closing.
