### ISSUE TITLE
As a user I can download a deployed business network archive from a fabric

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#43]
Some sort of `composer network download` command would be useful. It would allow the code generators to always work against a local archive, while providing a command to download the archive.

**Comment by mbwhite** [comment]
Most of this in the composer-rest-server; I can pull this out into a command quite easily

**Comment by EdMoffatt** [comment]
Moving this over to Playback 4 so that I can close out the Playback 3 milestone.

**Comment by sstone1** [comment]
@mbwhite what's the status of this one? I thought you did make a start on it - I didn't think it was that big... 😉

**Comment by mbwhite** [comment]
The devil is in the details @sstone1, can't rush perfection  😃 

Just tried this - and yes it's all done!
