### ISSUE TITLE
Docker container not staring on Ubuntu running on windows. 

### ISSUE THREAD

**Issue by tovijayy** [hyperledger/composer#4331]
After installing prerequisites. When it's tried to start composer using startFabric.sh script Its gives following error. 

Development only script for Hyperledger Fabric control
Running 'startFabric.sh'
FABRIC_VERSION is set to 'hlfv12'
FABRIC_START_TIMEOUT is unset, assuming 15 (seconds)
Stopping couchdb ... done
Removing peer0.org1.example.com ... done
Removing orderer.example.com ... done
Removing couchdb ... done
Removing ca.org1.example.com ... done
Removing network composer_default
Creating network "composer_default" with the default driver
Creating ca.org1.example.com ...
Creating orderer.example.com ...
Creating couchdb ...
Creating ca.org1.example.com
Creating orderer.example.com
Creating couchdb ... done
Creating peer0.org1.example.com ...
Creating peer0.org1.example.com ... done
sleeping for 15 seconds to wait for fabric to complete start up
**Error response from daemon: Container c1d55824cbb33eb050a2df70538499fdb449539cc96dc3e0d2e4aac9e90e48b8 is not running**

# Expected Behavior
The development composer should start. 

## Actual Behavior
the development composer is not starting. 

## Steps to Reproduce
1. Install pre-requisites
2. Run the startFabric.sh 

## Your Environment
* Version used: 1.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version (desktop or mobile): desktop ubuntu on windows

**Comment by davidkel** [comment]
I'm guessing you are trying to use the Windows Subsystem for Linux (ie you have downloaded Ubuntu from the windows store). This isn't supported and is not a true linux system as it is a very clever microsoft technology that dynamically converts linux system calls to windows api's and so there is no linux kernel which is a requirement for docker. 
Windows itself is not a supported platform and the supported method is to use a hypervisor such as virtualbox, vmware, hyperv to run a full linux virtual machine. 
If you still want a more windows native approach then you could take a look at https://davidkel.github.io/docs/Windows/Intro.html 
Although this describes different approaches to using windows natively the disclaimer still states this is not a supported environment.
