### ISSUE TITLE
Error starting Business network application in Hyperledger fabric composer— Multi host peer environment

### ISSUE THREAD

**Issue by rprasanakumar** [hyperledger/composer#4334]
I'm creating a fabric network with 5 peers.

2 peers, CA and orderer running on machine 1, 1 peer and couch instance on machine 2, 1 peer and couch instance on machine 3, 1 peer and couch instance on machine 4.

They all are on the same channel. I was able to install the .bna into the network. But when I tried starting the application using composer tool, using the below command

"composer network start -c PeerAdmin@hlfv1 -n blockv6 -V 0.0.1 -A admin -S adminpw"

I'm getting no valid response error

✖ Starting business network definition. This may take a minute... Error: Error trying to start business network. Error: No valid responses from any peers. Response from attempted peer comms was an error: Error: 2 UNKNOWN: chaincode error (status: 500, message: is not a valid endorsement system chaincode) Response from attempted peer comms was an error: Error: 2 UNKNOWN: chaincode error (status: 500, message: Unknown chaincodeType: NODE) Response from attempted peer comms was an error: Error: 2 UNKNOWN: chaincode error (status: 500, message: Unknown chaincodeType: NODE) Command failed

Below is my createPeerAdmin script's connection profile

 {

            "name": "hlfv1",
            "x-type": "hlfv1",
            "x-commitTimeout": 300,
           "version": "1.0.0",
         "client": {
    "organization": "Org1",
    "connection": {
        "timeout": {
            "peer": {
                "endorser": "300",
                "eventHub": "300",
                "eventReg": "300"
            },
            "orderer": "300"
        }
    }
},
"channels": {
    "composerchannel": {
        "orderers": [
            "orderer.example.com"
        ],
        "peers": {
            "peer0.org1.example.com": {},
             "peer1.org1.example.com": {},
              "peer2.org1.example.com": {},
              "peer3.org1.example.com": {},
              "peer4.org1.example.com": {}
        }
    }
},
"organizations": {
    "Org1": {
        "mspid": "Org1MSP",
        "peers": [
            "peer0.org1.example.com",
            "peer1.org1.example.com",
            "peer2.org1.example.com",
            "peer3.org1.example.com",
            "peer4.org1.example.com"

        ],
        "certificateAuthorities": [
            "ca.org1.example.com"
        ]
    }
},
"orderers": {
    "orderer.example.com": {
        "url": "grpc://${HOST}:7050"
    }
},
"peers": {
    "peer0.org1.example.com": {
        "url": "grpc://${HOST}:7051",
        "eventUrl": "grpc://${HOST}:7053"
    },
     "peer1.org1.example.com": {
        "url": "grpc://${HOST}:8051",
        "eventUrl": "grpc://${HOST}:8053"
    },
     "peer2.org1.example.com": {
        "url": "grpc://<machineIP>:9051"
    },
     "peer3.org1.example.com": {
        "url": "grpc://<machineIP>:9051"
    },
     "peer4.org1.example.com": {
        "url": "grpc://<machineIP>:9051"
    }
},
"certificateAuthorities": {
    "ca.org1.example.com": {
        "url": "http://${HOST}:7054",
        "caName": "ca.org1.example.com"
    }
}

**Comment by mahoney1** [comment]
hello,

I would imagine the reason you're getting this error is because you are not using Fabric 1.1 (ie you're using a pre-Fabric environment, like 1.0.5) - see the output in this Fabric JIRA (from where the error is generated) -> https://jira.hyperledger.org/browse/FAB-7645 - ie it is not a Hyperledger Composer error.  

If you have any more issues please post on https://stackoverflow.com/questions/tagged/hyperledger-fabric
