### ISSUE TITLE
I do not list the business network that installs

### ISSUE THREAD

**Issue by arsevys** [hyperledger/composer#4338]
help me please, I do not know because my created network is not shown, but it says that it is already installed, it seems that it is saved in a temporary folder or something :(

![image](https://user-images.githubusercontent.com/22304618/44148617-af7e8dc4-a05e-11e8-9fb8-7a8d979d2430.png)

**Comment by davidkel** [comment]
Please could you ask questions on RocketChat or create a stackoverflow entry. Github is for bugs or enhancements.
