### ISSUE TITLE
Composer 0.19.10 Failed to import the business network card for PeerAdmin

### ISSUE THREAD

**Issue by mtaram** [hyperledger/composer#4340]
## Context
Setting up the development environment on a new vm, followed the prerequisites and the setup guide from https://hyperledger.github.io/composer/v0.19/installing/development-tools
All goes well till ./startFabric.sh.
On executing ./createPeerAdminCard.sh
The card is created but the import fails saying error in connection profile. The same thing had worked well before.

./createPeerAdminCard.sh
Development only script for Hyperledger Fabric control
Running 'createPeerAdminCard.sh'
FABRIC_VERSION is set to 'hlfv11'
FABRIC_START_TIMEOUT is unset, assuming 15 (seconds)

Using composer-cli at v0.19.10

Successfully created business network card file to
	Output file: /tmp/PeerAdmin@hlfv1.card

Command succeeded

Failed to import the business network card
keyword:    required
dataPath:   .peers['peer0.org1.example.com']
schemaPath: #/required
params:
  missingProperty: eventUrl
message:    should have required property 'eventUrl'

Error: Errors found in the connection profile in the card
Command failed

## Expected Behavior
Should create the peeradmin card and import successfully.

## Actual Behavior
Card is created but

Import fails
Failed to import the business network card
keyword:    required
dataPath:   .peers['peer0.org1.example.com']
schemaPath: #/required
params:
  missingProperty: eventUrl
message:    should have required property 'eventUrl'

Error: Errors found in the connection profile in the card
Command failed

## Steps to Reproduce
Followed the prerequisites and the setup guide from https://hyperledger.github.io/composer/v0.19/installing/development-tools
./createPeerAdminCard.sh creates card but fails to import

## Environment

*https://raw.githubusercontent.com/hyperledger/composer-tools/master/packages/fabric-dev-servers/fabric-dev-servers.tar.gz
*hyperledger fabric v 1.1
* composer version 0.19.10
* Ubuntu 16.04

**Comment by davidkel** [comment]
You need to upgrade to composer 0.19.14. eventURL was removed from the latest fabric-dev-servers as it isn't required and composer was updated to not mandate it's presence in a connection profile
