### ISSUE TITLE
How to update an asset from other composer network?

### ISSUE THREAD

**Issue by parvizi** [hyperledger/composer#4341]
I have followed hyperledger composer tutorial [1](https://hyperledger.github.io/composer/latest/tutorials/invoke-composer-network), and it works properly. I will change the networkA's script in order to update networkB's asset.  I have tested other Interface Engine APIs [2](https://appdoc.app/artifact/com.github.xuanyue202/composer-sdk-java-common/0.16.2/org/hyperledger/composer/Engine.html#submitTransaction-java.lang.String-) but A could not update the asset. I really do not know how to update the B's asset from network A. I will be glad if somebody help me.

**Comment by davidkel** [comment]
Github is for bugs and enhancement requests. For these types of questions please create a stackoverflow entry, however you are going to have to provide a lot more detail than above as it's not possible to understand what you are trying to achieve.
