### ISSUE TITLE
REST server: order filter not working

### ISSUE THREAD

**Issue by majkowski-KompiTech** [hyperledger/composer#4348]
As a developer, I would like to get assets ordered by some attribute value.

## Context
When using order filter according to [documentation](https://loopback.io/doc/en/lb2/Order-filter.html), the assets should be returned sorted according to the filter setting. Assume that I have an asset with DateTime attribute **when** and I want to have these returned in sorted order.

## Expected Behavior
GET /api/Comment?filter=%7B%22order%22%3A%20%22when%20DESC%22%7D should return assets sorted in descending order by value of **when** field 

## Actual Behavior
GET /api/Comment?filter=%7B%22order%22%3A%20%22when%20DESC%22%7D returns assets in arbitrary order, not sorted. When i change order to ASC, nothing changes. However, if I make deliberate typo in order, then error message is produced:
```
{"error":{"statusCode":400,"name":"Error","message":"The order \"when DES\" has invalid direction"...
```

## Steps to Reproduce
1. Create a network with some assets
2. Try to get some assets using REST server with order LoopBack filter

## Context
Current workaround is to use named query, which sorts correctly, but this has the drawback of unability to use {"include": "resolve"} to get references immediately resolved.

## Your Environment
Composer v0.20.0
Fabric 1.2

**Comment by davidkel** [comment]
Unfortunately Composer only supports the `Where` filter.

**Comment by olesyakorovina** [comment]
Then why on the explorer it's written:

> Filter defining fields, where, include, order, offset, and limit - must be a JSON-encoded string ({"something":"value"})

if it only supports `where` ?

**Comment by davidkel** [comment]
Because the explorer is a loopback capability (which is the technology that powers the composer rest server) which we include in the rest server as a convenience to facilitate testing in development. It provides the UI and information on the explorer page and it isn't something that composer has created.
We also document here that only `where` is supported
https://hyperledger.github.io/composer/latest/business-network/query
