### ISSUE TITLE
Google OAUTH2.0 with a REST server failed to connect

### ISSUE THREAD

**Issue by hingjlee** [hyperledger/composer#4349]
I followed [google_outh2_tutorial](https://hyperledger.github.io/composer/latest/tutorials/google_oauth2_rest) to set up REST service in docker. I can successfully authenticate through Google and can import different wallets. Except Wallet API, all API calls failed with following error in using different cards.

500 Error: Error trying to ping. 

The cards work perfectly in composer-playground and I downloaded them from the composer-playground and uploaded via the REST server. 

## Context

I have tried over 3 weeks in all different settings. There are 3 tutorials in composer documentation to enable authentication for REST server.

a) https://hyperledger.github.io/composer/latest/integrating/enabling-rest-authentication
It works perfectly. The rest-server runs on bash directly (no docker) and no 'loopback' is required and therefore you cannot create persistent service. I used below command to keep it up and running.

`nohup composer-rest-server -c admin@bank-network -m true -a true & disown
`

b) https://hyperledger.github.io/composer/latest/integrating/deploying-the-rest-server 
As pointed out in https://github.com/hyperledger/composer/issues/4126, the documentation has not explained replacing the connection from "localhost" to respective docker container names and thus it does not work. 

c) https://hyperledger.github.io/composer/latest/tutorials/google_oauth2_rest
I can successfully authenticate through Google and can import any card.  But whenever I perform any transaction, below error occurs. Importing wallet is interacting with mongo db and it seems loopback setting is correct. The reason of the error is the 'rest' docker cannot communicate with the 'frabic' docker.

```
{
  "error": {
    "statusCode": 500,
    "name": "Error",
    "message": "Error trying to ping. Error: Failed to connect before the deadline",
    "stack": "Error: Error trying to ping. Error: Failed to connect before the deadline\n    at _checkRuntimeVersions.then.catch (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:806:34)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"
  }
}
```

As point out in Step 6, the key issue is let rest-server in docker talking to fabric in docker by replacing "localhost" into the name of the the containers. I successfully replaced the 'connection.json' under '.composer/cards/restadmin@biz-network' that as follows. 

`{"name":"hlfv1","x-type":"hlfv1","x-commitTimeout":300,"version":"1.0.0","client":{"organization":"Org1","connection":{"timeout":{"peer":{"endorser":"300","eventHub":"300","eventReg":"300"},"orderer":"300"}}},"channels":{"composerchannel":{"orderers":["orderer.example.com"],"peers":{"peer0.org1.example.com":{}}}},"organizations":{"Org1":{"mspid":"Org1MSP","peers":["peer0.org1.example.com"],"certificateAuthorities":["ca.org1.example.com"]}},"orderers":{"orderer.example.com":{"url":"grpc://orderer.example.com:7050"}},"peers":{"peer0.org1.example.com":{"url":"grpc://peer0.org1.example.com:7051"}},"certificateAuthorities":{"ca.org1.example.com":{"url":"http://ca.org1.example.com:7054","caName":"ca.org1.example.com"}}}`

The replaced names match what is currently running in the docker as follows. 
```
CONTAINER ID        IMAGE                                                                                                            COMMAND                  CREATED             STATUS              PORTS                                            NAMES
36261f20a664        myorg/composer-rest-server                                                                                       "pm2-docker composer…"   3 seconds ago       Up 2 seconds        0.0.0.0:3000->3000/tcp                           rest
0f02187635e5        dev-peer0.org1.example.com-bank-network-0.0.6-1d0c655050ce9c031a839d775544403a251a9ca629f7791930e8cef94c12bf53   "/bin/sh -c 'cd /usr…"   4 hours ago         Up 4 hours                                                           dev-peer0.org1.example.com-bank-network-0.0.6
8094a7d99e22        mongo                                                                                                            "docker-entrypoint.s…"   4 hours ago         Up 4 hours          0.0.0.0:27017->27017/tcp                         mongo
7653ec19e081        hyperledger/fabric-peer:1.2.0                                                                                    "peer node start"        6 hours ago         Up 6 hours          0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp   peer0.org1.example.com
639ce576be5f        hyperledger/fabric-orderer:1.2.0                                                                                 "orderer"                6 hours ago         Up 6 hours          0.0.0.0:7050->7050/tcp                           orderer.example.com
03ba2953febd        hyperledger/fabric-ca:1.2.0                                                                                      "sh -c 'fabric-ca-se…"   6 hours ago         Up 6 hours          0.0.0.0:7054->7054/tcp                           ca.org1.example.com
11fd96c90dca        hyperledger/fabric-couchdb:0.4.10                                                                                "tini -- /docker-ent…"   6 hours ago         Up 6 hours          4369/tcp, 9100/tcp, 0.0.0.0:5984->5984/tcp       couchdb
```
To further validate the communication issue, I installed "google-oauth2" not in docker and run it directly in the shell to avoid the docker communication issue. 

`npm install -g passport-google-oauth2
`
`nohup composer-rest-server -c admin@bank-network -m true -a true & disown
`

In this trial, I used the ordinary business card instead of the restadmin and it just run perfectly like in section a). 

**I therefore concluded that the "cannot ping" error is due to communication issue between docker containers**

## Expected Behavior

Different wallet can access only authorized API calls.

## Actual Behavior

Failed to connect

## Possible Fix

Calling rest-server in shell is a workaround but it is not recommended as mentioned in various articles in composer documentation.

## Steps to Reproduce

1. [google_outh2_tutorial](https://hyperledger.github.io/composer/latest/tutorials/google_oauth2_rest) 
2. test business network in playground
3. download business cards with different access right
4. import the business cards to wallet using Google OAuth2 in REST server
5. test API calls

## Existing issues

- https://github.com/hyperledger/composer/issues/4126

## Your Environment

* Version used: composer v0.20.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 68
* Operating System and version (desktop or mobile): Ubuntu

**Comment by rthatcher** [comment]
This is strange - in order for you to be able to import a card and attempt a transaction, the REST server must have started OK, and the 'admin' card you started it with must have connected to the Fabric to complete the 'Discovery' and build the endpoints.  Is there something different in the connection.json for the card that you import?  Have you tried importing and using the 'admin' card itself?

You could also try a different test (if you haven't done this already) - Run the REST server in a Container, in single-user mode without authentication - are you able to submit transactions this way?

You are obviously building/starting/stopping lots of containers - are you housekeeping to delete old versions? and do you have plenty of system resource to run all the containers?

**Comment by hingjlee** [comment]
Hi Rob, as I have written, I've exhausted all the documentations in the composer library. I ./teardownAllDocker.sh including all the images in each retry. The environment is completely clean. As described in the context, I tried using composer-rest-server with all options and all of them worked. I used auth/github/callback as described in a). It worked. Even when I changed auth/google/callback directly, it worked perfectly.

```
npm install -g passport-google-oauth2
nohup composer-rest-server -c admin@bank-network -m true -a true & disown
```

Only when I used docker as described in the google OAuth tutorial, it failed. I didn't create my own connection.json file but using the "sed" command as described in Step 6 in the tutorial to update the connection profile. 

I tried to run the test single user mode according to your recommendation but after many attempts, I failed to produce the restadmin card and a new issue has been raised in other thread. Thank you very much.

**Comment by hingjlee** [comment]
In https://hyperledger.github.io/composer/latest/tutorials/google_oauth2_rest, I believe there is an update and especially step 9 is added, correct me if I'm wrong. The step requires all cards changing the connection profile. I'll try to follow the step and try again.

**Comment by hingjlee** [comment]
I successfully created additional ID cards and replaced all "localhost" to corresponding container names. It finally works. 

**However, from a governance perspective and day-to-day security management perspective, it is not ideal as administrator has to go into low level command line to edit the connection profile in the ".composer/cards" directory whenever a new card is issued.**

**Comment by rthatcher** [comment]
The connection.json of a new card created by identity issue is based on the connection.json of the card issuing the identity.  So the "original" cards have localhost in them, but you can issue identities from the REST server, and these will be based on the "new" connection.json.

**Comment by hingjlee** [comment]
Thank you Rob but I don't see any card "Issuing" function in REST server. Could you pls provide guidance? Thanks.
