### ISSUE TITLE
Composer Identity Issue failed to register user

### ISSUE THREAD

**Issue by hingjlee** [hyperledger/composer#4350]
Composer Identity Issue failed to register user. 

## Context

Composer Identify Issue failed to registered user.  Using rest-server, localhost/api/system/identities found outs that such identity not registered.

## Expected Behavior

Identity properly issued and card is used for connection.

## Actual Behavior

```
#composer identity issue -c admin@bank-network -f OWL2.card -u OWL2 -a "bank.Customer#OWL"

Issue identity and create Network Card for: OWL2

✔ Issuing identity. This may take a few seconds...

Successfully created business network card file to
        Output file: OWL2.card

Command succeeded
```
Pinging the card
```
Error: Error trying to ping. Error: transaction returned with failure: Error: The current identity, with the name 'OWL2' and the identifier '1db349cfbe4db1700286400be4cb94f2a6429f84b43af78d4392044a59a0048f', has not been registered
Command failed
```
## Steps to Reproduce

1. composer identity issue
2. composer card import
3. composer network ping

## Your Environment

```
/home/300jrdadmin/.nvm/versions/node/v8.11.3/lib
├── composer-cli@0.20.0
├── composer-playground@0.20.0
├── composer-rest-server@0.20.0
├── generator-hyperledger-composer@0.20.0
├── npm@6.1.0
├── passport-github@1.1.0
├── passport-google-oauth2@0.1.6
├── wscat@2.2.1
└── yo@2.0.5

```

**Comment by michaelwangbh** [comment]
I had a similar issue when I tried to do ```composer identity issue``` or ```composer network ping``` , and I would get the same error message as yours. I solved it by following the instructions under this post: https://github.com/hyperledger/composer/issues/4303#issuecomment-411304780 .

So in short, right after running ```composer network list -c admin@your-network``` successfully, run:
### **```$ composer identity list -c admin@basic-sample-network```**
to make sure the state of your identity is activated.

**Comment by mahoney1** [comment]
After issuing with the CLI (as you've done), you would import the card (OWL2.card) using composer card import if OWL2.card.  Then you do the network ping ('connect' to the network), and then check using `composer identity list` as @michaelwangbh suggests. It should show as activated.
