### ISSUE TITLE
Business Card became unauthorized after few hours

### ISSUE THREAD

**Issue by hingjlee** [hyperledger/composer#4351]
Business Card became unauthorized after few hours. 

## Context

I issued Business Card via Playground. Downloaded it and uploaded it into multi-user Rest-server. It worked in both Playground and Rest-server upon right after. But after few hours with no transaction done in the system/blockchain, the card get unauthorized. I issued 5 cards and only 1 still working. In producing the card, I did the same and those working is using "**credentials:         Credentials set**" while those not working is "**credentials:         One time use only secret set**"

## Expected Behavior

Card should work unless credential changed. 

## Actual Behavior

Card malfunctioned after few hours.

`Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{"code":20,"message":"Authorization failure"}]]
`
## Possible Fix

The card still working.
**credentials:         Credentials set**
```
$ composer card list -c alice@bank-network
userName:            alice
description:
businessNetworkName: bank-network
identityId:          d136747809f0b8684aedade599f60766a0819a7c5a31dc072c47ad6c8be585a5
roles:               none
connectionProfile:
  name:   hlfv1
  x-type: hlfv1
credentials:         Credentials set
```
The card not working:
**credentials:         One time use only secret set**
```
$ composer card list -c bob@bank-network
userName:            bob
description:
businessNetworkName: bank-network
identityId:
roles:               none
connectionProfile:
  name:   hlfv1
  x-type: hlfv1
credentials:         One time use only secret set
```
## Steps to Reproduce

1. composer identity issue (or playground ID Registry page)
2. composer card import (or playground save to wallet)

## Existing issues

Nothing related found.

## Your Environment

/home/300jrdadmin/.nvm/versions/node/v8.11.3/lib
├── composer-cli@0.20.0
├── composer-playground@0.20.0
├── composer-rest-server@0.20.0
├── generator-hyperledger-composer@0.20.0
├── npm@6.1.0
├── passport-github@1.1.0
├── passport-google-oauth2@0.1.6
├── wscat@2.2.1
└── yo@2.0.5

**Comment by rthatcher** [comment]
When you Issue an Identity (and create a card) it gets created with a 'one-time' secret.  When the card is first used to connect to the network, Credentials (certificate/key) are downloaded AND the one-time secret becomes invalid.  You have seen the change in status with `composer card list`.

After the secret has been used, you CANNOT re-import the .card file.  (If you export a working card that has credentials set, you will see that the .card file is larger as it now contains the credentials.)

There is additional information about cards in the Knowledge Wiki:
https://github.com/hyperledger/composer-knowledge-wiki/blob/latest/knowledge.md#bizcards

**Comment by hingjlee** [comment]
Hi Rob,
Thank you very much for the wiki. It explained. 
cheers

**Comment by jfobrien29** [comment]
This is great advice thank you!
