### ISSUE TITLE
Failed to import the business network card

### ISSUE THREAD

**Issue by VarunVerma3** [hyperledger/composer#4354]
Deploying business network card giving error 

## Context

$ composer card import -f PeerAdmin@fabric-network.card 

Failed to import the business network card
keyword:    required
dataPath:   .peers['peer0.org1.example.com']
schemaPath: #/required
params: 
  missingProperty: eventUrl
message:    should have required property 'eventUrl'

Error: Errors found in the connection profile in the card
Command failed

**Comment by davidkel** [comment]
See https://stackoverflow.com/questions/51693339/unable-to-import-card-in-hyperledger-composer
you need to upgrade to composer 0.19.13 or 0.19.14
