### ISSUE TITLE
Connection fails: Error: Error trying to ping. Error: Composer runtime (0.19.4) is not compatible with client (0.20.0)

### ISSUE THREAD

**Issue by parismollo** [hyperledger/composer#4355]
Fail to deploy rest server for a business network: 

## Context
I'm following this tutorial : https://hyperledger.github.io/composer/latest/integrating/deploying-the-rest-server
Once I run : `docker run \
    -d \
    -e COMPOSER_CARD=${COMPOSER_CARD} \
    -e COMPOSER_NAMESPACES=${COMPOSER_NAMESPACES} \
    -e COMPOSER_AUTHENTICATION=${COMPOSER_AUTHENTICATION} \
    -e COMPOSER_MULTIUSER=${COMPOSER_MULTIUSER} \
    -e COMPOSER_PROVIDERS="${COMPOSER_PROVIDERS}" \
    -e COMPOSER_DATASOURCES="${COMPOSER_DATASOURCES}" \
    -v ~/.composer:/home/composer/.composer \
    --name rest \
    --network composer_default \
    -p 3000:3000 \
    myorg/my-composer-rest-server`
The error appears if you check the logs in `docker logs -f rest`
Import : I'm using another business network  
## Expected Behavior
Once we run the `docker run` command and we verify `docker logs -f rest` the expected behavior it should be something like this : `Browse your REST API at http://localhost:3000/explorer`

## Actual Behavior
My error : 
`Connection fails: Error: Error trying to ping. Error: Composer runtime (0.19.4) is not compatible with client (0.20.0)
It will be retried for the next request.
Exception: Error: Error trying to ping. Error: Composer runtime (0.19.4) is not compatible with client (0.20.0)
Error: Error trying to ping. Error: Composer runtime (0.19.4) is not compatible with client (0.20.0)
    at _checkRuntimeVersions.then.catch (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:806:34)
    at <anonymous>
`

## Possible Fix
Because my composer-versions are normal and they respect the compability I don't know what action to take from here...

## Steps to Reproduce
On tutorial : 
https://hyperledger.github.io/composer/latest/integrating/deploying-the-rest-server

## Your Environment

/home/paris/.nvm/versions/node/v8.11.3/lib
├── @ampretia/composer-wallet-cloudant@0.2.1
├── composer-cli@0.19.14
├── composer-rest-server@0.19.14
├── composer-runtime@0.19.14
├── generator-hyperledger-composer@0.19.5
├── loopback-connector-mongodb@3.6.0
├── npm@5.6.0
├── passport-github@1.1.0
└── yo@2.0.5
I can't undestand the reason why he consideres my runtime version as 0.19.4 and the client as 0.20.0 if before deploymeny my environnement looks just like that.

For curiosity when I try to run composer-rest-server for leverage a local rest api, it works perfectly and there are not issues related to runtime version or client....

**Comment by davidkel** [comment]
See your stackoverflow question
https://stackoverflow.com/questions/52039298/error-error-trying-to-ping-error-composer-runtime-0-19-4-is-not-compatible
Note that you are probably downloading the latest docker image which will be version 0.20.0 of the rest server. You should explicitly state the version of the docker image as 0.19.14 for the rest server to get a compatible version.

**Comment by parismollo** [comment]
@davidkel  Thank you, David. 
I don't have much experience with such subject, could you tell me where I should specify that?
When I run docker build ? or inside the envvars.txt file?

**Comment by davidkel** [comment]
In your Dockerfile specify the version of composer rest server you want to base on, eg
```
FROM hyperledger/composer-rest-server:0.19.14
RUN npm install --production loopback-connector-mongodb passport-github && \
    npm cache clean --force && \
    ln -s node_modules .node_modules
```

**Comment by parismollo** [comment]
@davidkel  thank you, David ! I was going to try that exactly now!
