### ISSUE TITLE
GraphQL API to talk with Composer backend

### ISSUE THREAD

**Issue by ClementeSerrano** [hyperledger/composer#4356]
Hi everyone!

I’ll start a project for the supply chain of a private company and I decided to use Hyperledger Composer to make the app (which is web) descentralized and private.

I want to work in my clientside with React and communicate with the server (composer) via GraphQL. 

Composer allows to create a REST API, but I needed to be GraphQL

How can I do it?

**Comment by ClementeSerrano** [comment]
I also want to divide the Composer server logic into microservices. 

Any idea?

**Comment by ClementeSerrano** [comment]
Thanks @jt-nti, I’ll check it!

**Comment by davidkel** [comment]
Closing as not something composer will provide
