### ISSUE TITLE
Composer Playground Exports "To" version in bna file

### ISSUE THREAD

**Issue by hingjlee** [hyperledger/composer#4361]
When I pressed "Export" button in playground/editor, it generates a bna file with the version in the "To" field. 

## Context

As "To" is the version to be deployed and never deployed, generating this bna file will result in different version when I try to deploy in other peer.

## Expected Behavior

When pressing "Export" button in playground/editor, it should generate a bna file with the version in the "From" field (i.e., the current deployed version). 

## Actual Behavior

When I pressed "Export" button in playground/editor, it generates a bna file with the version in the "To" field. 

## Steps to Reproduce

1. playground
2. connect to any business card
3. Export a bna file
4. view the version of the bna file

## Context

As "To" is the version to be deployed and never deployed, generating this bna file will result in different version when I try to deploy in other peer.

## Your Environment

* Version used: v.0.20.0

**Comment by hingjlee** [comment]
Hi, there, is there anyone following this up please?

**Comment by davidkel** [comment]
The export is designed to export your current work, not what has been deployed as you could have newer code stored that you have not deployed to a fabric or web runtime but want to backup for example so it is working as designed.
