### ISSUE TITLE
CIP: Make ModelManager (CTO) an independent npm module

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#4365]
In light of https://lists.hyperledger.org/g/composer/message/125 (as well as other considerations) I would like to propose a new work item for discussion.

I would like to move the `ModelManager` and all related code outside of the `composer-common` npm module and into its own GitHub repo. I propose the name `Hyperledger Concerto` for this new module/rep. Old timers will see what I did there! 😉

We will maintain API compatibility during the move, the only change being the creation of a new npm module: `@hyperleger/concerto` ?

This has several advantages:
1. The model manager code is pretty stable now. It will allow us to semver the code as an independent module, releasing it on its own update cycle.
2. It allows projects that want to use CTO as a schema language, outside of the context of Composer, to do so much more easily, and with far fewer dependencies.
3. It will make it easier for us to evangelize the use of this code across other HL projects. For example, to use the models inside a HL Fabric application (as an npm dependency from Node.js chaincode), or potentially from Sawtooth, Burrow, Iroha etc. Shared models across projects will drive data-level interop and open up cross-chain integration scenarios. For example, the code that generates a REST server from a set of CTO models could be generally applicable across different backends.
4. It makes it easier for downstream projects to consume, such as Accord Project: https://docs.accordproject.org/docs/model-repository.html
5. Makes it easier to attract contribution to this code base. The code is much smaller and more focused than the whole of Composer. No Fabric knowledge is required. I would love to see  C/C++/Go/Java implementations of the parser, serialiser and validator.

Some refactoring of Composer will be required so that it uses the new npm module.

I have an experimental repo where I have separated the `ModelManager` code from Composer and updated all the tests. The browserified version of this repo is 350 KB vs. 3.5 MB for the whole of `composer-common`.

During this move we should separate the `codegen` code from the core `ModelManager` code. For example, they could go into a repo/npm module called `concerto-tools`.

**Comment by mbwhite** [comment]
Good idea @dselman,  myself and @EllisHenderson had also taken look at the feasibility of this with an experimental repo  (https://github.com/ampretia/copse-orm)

**Comment by szewong** [comment]
@dselman on point 3 above. Would using CTO on DLTs outside of HL projects be considered? Such as private ETH?

**Comment by dselman** [comment]
@szewong yes, that would become much easier once we move the model manager code outside of Composer.
