### ISSUE TITLE
Not issue, want knowledge! How to validate the asset by model language when i add the asset?

### ISSUE THREAD

**Issue by rodchen-king** [hyperledger/composer#4366]
I want to verify the Relationships "trader" when i add the assset "Test", but i don't get the way to do it in .cto file.
## Context

asset Test identified by TestId {
    o String TestId 
    --> Trader trader
}

## Point
Please help me to do it! Thanks.

**Comment by davidkel** [comment]
Sorry, github is for bugs or enhancement requests. You might want to create a question on stackoverflow.
