### ISSUE TITLE
Skip/Limit in queries returning all results, ignoring parameters

### ISSUE THREAD

**Issue by ronaldlong46** [hyperledger/composer#4374]
I am trying to make some sort of pagination functionality. It appears that the limit/skip is just querying like normal, ignoring the skip/limit parameters.
## Context
My query:
query propertiesByPosition {
    description: "Enables pagination for properties"
    statement:
        SELECT org.realestate.land.Properties
		LIMIT _$limit
                SKIP _$skip
}

## Existing issues
Have found this: https://github.com/hyperledger/composer/issues/1015
But was back from April. Was wondering if this bug was ever fixed with newer Fabric releases.

## Your Environment

* Version used: Composer v0.20.0
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by davidkel** [comment]
Unfortunately limit and skip are always reset by fabric so even though they can be set, effectively fabric ignores them. Fabric is not going to introduce support for limit and skip values and the limit and skip options of composer won't work without it.

**Comment by JairoHernandezFlores** [comment]
Hyperledger composer for develop, it is only available for the version v1.2

even if you migrate to version 1.3, it always fails.  with:

const { iterator, metadata } = await getNativeAPI().GetQueryResultWithPagination(queryString, pageSize, bookmark);

**Comment by ahmedemam** [comment]
Is there any update solution for this issue?! limit /skip not working until now.
