### ISSUE TITLE
Retrieve administrator certificates for organization error

### ISSUE THREAD

**Issue by htinshar** [hyperledger/composer#4377]
When I try to retrieve certificate for organization `composer identity request -c PeerAdmin\@mynetwork-agent -u admin -s adminpw -d agent`, I got this error `Error: failed to request identity. Error trying to enroll user and return certificates. Error: Calling enrollment endpoint failed with error [Error: write EPROTO 140736418640832:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:797:`, does anyone know how to solve that?

**Comment by chrim5** [comment]
+1
I've faced the same issue while following the deploy-to-fabric-multi-org tutorial (https://hyperledger.github.io/composer/latest/tutorials/deploy-to-fabric-multi-org)

**Comment by davidkel** [comment]
This looks like a configuration issue where you either have the fabric-ca-server running in tls mode but declared it as http only in the connection profile or you have the fabric-ca-server running in non-tls mode and declared the entry in the connection profile as https. Check your fabric setup and ensure that the connection profile matches the fabric configuration.
