### ISSUE TITLE
JSDoc for helper functions

### ISSUE THREAD

**Issue by nasht00** [hyperledger/composer#4385]
In my processor code, I added a helper function. 
Meaning a function that is not called as a standalone transaction, but rather a piece of reusable code that transactions can use.

If I don't put JSDoc comments, the linter complains.
If I put a jsdoc comment, then I can't compile it as I get an error:
`Cannot read property 'name' of null`

I am not doing anything named `name` but all I can say is as soon as I put a JSDoc it fails with this error...

My current workaround was to disable the jsdoc enforcement in eslint.yml, however is there a way to tell composer that a specific function is NOT a transaction?

**Comment by nasht00** [comment]
Yes I think I understood that.
However, it does not explain the `Cannot read property 'name' of null` error when putting a jsdoc on my non-transaction function...
The error only happens when I add a jsdoc to it, and it happens during `npm install` as it tries to compile the BNA.

**Comment by davidkel** [comment]
@nasht00 Some parsing of the comments is done to look for annotations. Can you add an example recreate of a jsdoc that causes the problem ?

**Comment by davidkel** [comment]
Closing as no further update from reporter.
