### ISSUE TITLE
Create a footer for the Define and Test content panels/tabs

### ISSUE THREAD

**Issue by samjsmith** [hyperledger/composer#440]
This needs to be a floating footer with the version, a link to GitHub, Legal etc as per the screenshot that @winslet will upload.

**Comment by caroline-church** [comment]
@EdMoffatt Are the designs finished for this?

**Comment by EdMoffatt** [comment]
Here's the design for the footer, with the amended contents @caroline-church :

![footer bar design](https://cloud.githubusercontent.com/assets/7454304/24094404/74af5a54-0d50-11e7-8f23-1c665272f2a2.png)

The "Feedback?" bit needs styling for a dropdown menu: behaviour will be that it opens out above that word, and has sub-options for StackOverflow, Rocket.Chat and Community (which will link to http://stackoverflow.com/questions/tagged/fabric-composer , https://chat.hyperledger.org/channel/fabric-composer and https://fabric-composer.github.io/support/index.html respectively).

I've gotta defer to @winslet for the styling of dropdowns, as we don't have any in the hi-fis yet.  There are a few issues that need it, so will give Sam a list to work through when he's back in tomorrow!

**Comment by EdMoffatt** [comment]
Just a note for Sam - my feeling is that the "Feedback?" drop-up should contain:

Ask on StackOverflow
Discuss on Rocket.Chat
Join the Community

That introduces the context in which you'd use each thing for those who don't recognise the names, but is still hopefully succinct enough to not look silly!

I don't think we should have a link to "Leave NPS": that's better handled through prompting the user at the appropriate point, so I don't think we need a link for them to click to leave it.

**Comment by winslet** [comment]
Feedback 'drop up' has a similar styling to the dropdown in identity management #533 

![fabric composer playground define 2 copy 61](https://cloud.githubusercontent.com/assets/13980028/24446970/525437ae-1467-11e7-8497-d595fc12ac58.png)

**Marketch:** [Feedback_Popover_FC_SW_1.zip](https://github.com/fabric-composer/fabric-composer/files/878439/Feedback_Popover_FC_SW_1.zip)
**Assets:** (please check if we have these already to avoid duplication) [Popover_Assets.zip](https://github.com/fabric-composer/fabric-composer/files/878444/Popover_Assets.zip)

**Comment by jthub** [comment]
> Feedback 'drop up' has a similar styling to the dropdown in identity management #533

See no. 4 on the playground component wishlist for these pop overs #649

**Comment by winslet** [comment]
@caroline-church is there any update as to who can work on this?

**Comment by mbwhite** [comment]
FYI - on builds from now - check out the JS Console in the browser - added a simple output of the version.  Might help in the interim.

**Comment by 14gracel** [comment]
Do we have a link to the legal stuff?

**Comment by winslet** [comment]
@markcastle3 what legal things (eg licenses) should we be listing/linking to on the playground?
