### ISSUE TITLE
Support for mutual authentication in tls

### ISSUE THREAD

**Issue by mplescano** [hyperledger/composer#4405]
Currently there is no documentation related to configure composer to provide the crt/key tls files for mutual authentication.
## Context
I've configured my orderer and peer servers with these flags:
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/data/org1-mplescano-com-ca-cert.pem]
      - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_GENERAL_TLS_CLIENTROOTCAS=[/data/org1-mplescano-com-ca-cert.pem]
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/data/org2-mplescano-com-ca-cert.pem
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/data/org2-mplescano-com-ca-cert.pem
      - CORE_PEER_TLS_CLIENTCERT_FILE=/data/tls/peer1-org2-mplescano-com-client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/data/tls/peer1-org2-mplescano-com-client.key

I've tried to configure my profile connection like the code below based on this link:
https://github.com/hyperledger/composer/blob/master/packages/composer-cli/test/card/data/connection.yaml

`

    "organizations": {
        "org2.mplescano.com": {
            "mspid": "peerorg2.mplescano.comMSP",
            "peers": [
             "peer1.org2.mplescano.com",
             "peer2.org2.mplescano.com"
             ],
            "certificateAuthorities": [
                "rca.org2.mplescano.com"
            ],
            "adminPrivateKey": {
              "path": "/home/user_composer/peercomposer/org2.mplescano.com/admin/msp/keystore/967eb6f9f9939ce0c0e094f7734000007ad60b8dadf014d"
            },
            "signedCert": {
              "path": "/home/user_composer/peercomposer/org2.mplescano.com/admin/msp/signcerts/cert.pem"
            }
         }
    },
    "orderers": {
       "orderer1.org1.mplescano.com": {
            "url": "grpcs://orderer1.org1.mplescano.com:7050",
            "tlsCACerts": {
                "path": "/home/user_composer/peercomposer/org2.mplescano.com/admin/msp/cacerts/rca-org1-mplescano-com-7054.pem",
                "client": {
                  "keyfile": "/home/user_composer/peercomposer/org2.mplescano.com/admin/tls/cli-client.key",
                  "certfile": "/home/user_composer/peercomposer/org2.mplescano.com/admin/tls/cli-client.crt"
                }
            }
        }
    },
    "peers": {
           "peer1.org2.mplescano.com": {
              "url": "grpcs://peer1.org2.mplescano.com:7051",
              "tlsCACerts": {
                "path": "/home/user_composer/peercomposer/org2.mplescano.com/admin/msp/cacerts/rca-org2-mplescano-com-7054.pem",
                "client": {
                  "keyfile": "/home/user_composer/peercomposer/org2.mplescano.com/admin/tls/cli-client.key",
                  "certfile": "/home/user_composer/peercomposer/org2.mplescano.com/admin/tls/cli-client.crt"
                }
              }
           },
           "peer2.org2.mplescano.com": {
              "url": "grpcs://peer2.org2.mplescano.com:7051",
              "tlsCACerts": {
                "path": "/home/user_composer/peercomposer/org2.mplescano.com/admin/msp/cacerts/rca-org2-mplescano-com-7054.pem",
                "client": {
                  "keyfile": "/home/user_composer/peercomposer/org2.mplescano.com/admin/tls/cli-client.key",
                  "certfile": "/home/user_composer/peercomposer/org2.mplescano.com/admin/tls/cli-client.crt"
                }
              }
           }
    },

`

## Expected Behavior
Composer should install the business network.

## Actual Behavior
it's complaining about of bad credentials
`
E0923 18:36:20.897620679     729 ssl_transport_security.cc:188] ssl_info_callback: error occured.

E0923 18:36:20.897668345     729 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL:
error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate.
E0923 18:36:20.897919361     729 ssl_transport_security.cc:188] ssl_info_callback: error occured.

E0923 18:36:20.897946538     729 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL:
error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate.
E0923 18:36:21.910181515     729 ssl_transport_security.cc:188] ssl_info_callback: error occured.

E0923 18:36:21.910302975     729 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL:
error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate.
E0923 18:36:21.910937672     729 ssl_transport_security.cc:188] ssl_info_callback: error occured.

E0923 18:36:21.911034199     729 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL:
error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate.
E0923 18:36:23.324335493     729 ssl_transport_security.cc:188] ssl_info_callback: error occured.

E0923 18:36:23.324454341     729 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL:
error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate.
E0923 18:36:23.494438199     729 ssl_transport_security.cc:188] ssl_info_callback: error occured.

E0923 18:36:23.494571571     729 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL:
error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate.
✖ Installing business network. This may take a minute...
Error: Error trying install business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: Failed to connect before the deadline
`
## Possible Fix
Deactivate the flags of mutual tls.

## Steps to Reproduce
1. Create and import the profile connection
2. Create bna file of tutorial network
3. install it using composer

## Existing issues
There are few or nothing about this.

## Context
Trying to do a demo with mutual auth tls.

## Your Environment
* Version used:
composer --version v0.20.1

node -v v8.12.0

npm --version 6.4.1

uname -a
Linux e237305583e1 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 x86_64 x86_64 GNU/Linux

Docker images of fabric version 1.2.0

**Comment by davidkel** [comment]
@mplescano unfortunately composer doesn't support fabrics that have mutual tls enabled.

**Comment by davidkel** [comment]
This issue is being closed, for reference please see
https://lists.hyperledger.org/g/composer/message/125
