### ISSUE TITLE
Conecction Refused in Tutorial

### ISSUE THREAD

**Issue by MatiasNovoa** [hyperledger/composer#4411]
In tutorial of fabcar the command  "node enrollAdmin.js" doesn't work

## Context
"docker log -f ca.example.com" , is listening in adress 0.0.0.0:7054 in another console, but when i try to use enrollAdmin.js the conection is refused, because this command search in 127.0.0.1:7054 and not match with the linstening adress

what can i do?

**Comment by davidkel** [comment]
This sounds like it's from hyperledger fabric samples and nothing to do with hyperledger composer, suggest you try either stackoverflow or you ask the question on one of the rocketchat fabric channels.
