### ISSUE TITLE
composer network start always take so much long time to download something from internet. 

### ISSUE THREAD

**Issue by adnanjee** [hyperledger/composer#4442]
When I start a network it always download something from the internet. I cannot start a network if my internet connection is closed. Why it always download very large data from internet before starting a network. I think it is npm install commands during container building. Is there any solution for this?
mostly it results like this

Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT
Command failed

## Expected Behavior

It should start the network within a minute.

**Comment by davidkel** [comment]
This is the way fabric creates and builds node.js chaincode. It isn't something composer can do anything about. You could consider setting up your own local npm registry to host npm packages for you and then use a .npmrc file to point to that registry. See here for more info about installing business networks with a .npmrc file
https://hyperledger.github.io/composer/latest/managing/connector-information

**Comment by davidkel** [comment]
There should be examples on the internet about setting up a local npm registry eg stackoverflow as I believe other composer users have done this.

**Comment by adnanjee** [comment]
I have started local npm server at localhost:5080. But i dont know how to use it with composer network start comman. Can you help me please. I could not understand it.

**Comment by Gyon-Ki** [comment]
> This is the way fabric creates and builds node.js chaincode. It isn't something composer can do anything about. You could consider setting up your own local npm registry to host npm packages for you and then use a .npmrc file to point to that registry. See here for more info about installing business networks with a .npmrc file
> https://hyperledger.github.io/composer/latest/managing/connector-information

what are the packages ?
