### ISSUE TITLE
composer network start is not using local-npm

### ISSUE THREAD

**Issue by adnanjee** [hyperledger/composer#4444]
I have installed local-npm in following procedure

$ npm install -g local-npm
$ local-npm
$ npm set registry http://127.0.0.1:5080

The I create a file npmConfig.txt and write following line inside it

registry=http://localhost:5080/

But composer network start is not using local-npm. I have start many networks and it still took very long time to start and as I get offline from internet and try to start a network it fails.

Below is a sample output:

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: failed to execute transaction 63ddae5b59bbd8ed818d1bf728e98693ecfd220a742b8752666e01802db33e71: error starting container: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/composer-common failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-04T07_20_05_373Z-debug.log
"
Command failed

Can somebody help me to use local-npm to start a network. Its take too much long to start a network and many times it fails with Request time out.
![screenshot from 2018-10-04 15-34-25](https://user-images.githubusercontent.com/16976969/46459282-00d4fb00-c7eb-11e8-9ae7-3b838fc04c95.png)

**Comment by davidkel** [comment]
you should pass the npmrc on the install and use lower case 'o'.
`composer network install -c PeerAdmin@hlfv1 -a bna.bna -o npmrcFile=/home/adman/npm/npmConfig.txt`

**Comment by adnanjee** [comment]
I checked all the options. did all things. but it failed. Anyway, thank you so much for the response.

**Comment by Gyon-Ki** [comment]
did you solve it Im facing same issue know

**Comment by Gyon-Ki** [comment]
> I checked all the options. did all things. but it failed. Anyway, thank you so much for the response.
 did you solve the issue

**Comment by BhargavKK** [comment]
I'm getting this error

 Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: failed to execute transaction 594d55d44b07b863826803d9bbfcd6baf3d3d95efd764b2b56ddf3ddfc4f606b: error starting container: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code ENETUNREACH
npm ERR! errno ENETUNREACH
npm ERR! request to https://registry.npmjs.org/cryptiles failed, reason: connect ENETUNREACH 104.16.16.35:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-03T03_51_32_492Z-debug.log


i restarted the network, added the registry file to the install command. Still did not work!
