### ISSUE TITLE
REST ERROR  500   the error said I dint registered the i dentity that it expect but actually I already registered in the wallet

### ISSUE THREAD

**Issue by RainbowArea** [hyperledger/composer#4445]
I follow this tutorial   [https://hyperledger.github.io/composer/latest/integrating/enabling-rest-authentication](url) to  authenticating to the REST server

> 
>   "error": {
>     "statusCode": 500,
>     "name": "Error",
>     "message": "Error trying to ping. Error: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier '40b4516088f83a63966698dc99ccb697f510424fbf64652079b3374ffbf751f2', has not been registered",
>     "stack": "Error: Error trying to ping. Error: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier '40b4516088f83a63966698dc99ccb697f510424fbf64652079b3374ffbf751f2', has not been registered\n    at _checkRuntimeVersions.then.catch (/home/chiangmaident/.nvm/versions/node/v8.12.0/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:798:34)\n    at <anonymous>"
>   }

After I run composer-rest-server 
and connect it with github oAuth
I got this secret id and client id  from oAuth when i create application

> Client ID
> f15e8abd8b5f20a68146
> Client Secret
> 5cc123729db6c79671efc650d973aecb072f46de

and then I run this 
```
export COMPOSER_PROVIDERS='{
  "github": {
    "provider": "github",
    "module": "passport-github",
    "clientID": "f15e8abd8b5f20a68146",
    "clientSecret": "5cc123729db6c79671efc650d973aecb072f46de",
    "authPath": "/auth/github",
    "callbackURL": "/auth/github/callback",
    "successRedirect": "/",
    "failureRedirect": "/"
  }
}' 
```
this is my command to run composer rest server 
`composer-rest-server -c admin@dentalclinic16-network -n never -a true -m true -u true -w true
`

when the application browser run up 
I go to wallet bar  and post wallet import the file from my folder  and then i try it out in GET / wallet and it show  fine  with  response with number 200  and user name admin is default
`[
  {
    "name": "admin",
    "default": true
  },
  {
    "name": "clinic1",
    "default": false
  },
  {
    "name": "dentist1",
    "default": false
  },
  {
    "name": "patient1",
    "default": false
  }
]`

but I really don't understand why when I go try to create the participant it show 
`The current identity, with the name 'admin' and the identifier '40b4516088f83a63966698dc99ccb697f510424fbf64652079b3374ffbf751f2', has not been registered"`

I  dont know what I had not setting yet that make it error  please help me .... 

version of composer-rest-server  v0.20.1
composer-playground V 0.20.1
Hyperledger Fabric V 1.2

**Comment by RainbowArea** [comment]
I can solve it now  the solution is  export the wallet user and import again on fest server  
or run this command in terminal 
 composer card export -c admin@yourbusinessnetwork -f admin001.card     and then  import this card again in wallet (you can browse the file from the directory that is just exported)

**Comment by davidkel** [comment]
Closing as reporter as solved the issue.
