### ISSUE TITLE
Ldap integration issue

### ISSUE THREAD

**Issue by volodyad** [hyperledger/composer#4454]
Cannot integrate fabric ca with ldap. 
Composer and fabric-ca-node sdk requires affiliation to be non empty.
But when fabric ca connected to ldap - it cannot issue identity.

Fabric ca do validation of affiliations by calling method
_func validateAffiliation(req *api.RegistrationRequest, ctx *serverRequestContextImpl)_

this method calls _ctx.ca.registry.GetAffiliation(affiliation)_ to check if affiliation exists.
When ldap connected - registry is a ldap client

if you check ldap client implementation, method is not implemented, it means validation always fails,
it only success if affiliation empty
_func (lc *Client) GetAffiliation(name string) (spi.Affiliation, error) {
	return nil, errNotSupported
}_

This means that composer cannot be integrated with fabric client at the moment

**Comment by davidkel** [comment]
@volodyad This is for identity issue ? you could get around it for now by doing the following
1. use fabric-ca-client to register the identity
2. use fabric-ca-client to enrol the identity
3. use composer network bind to bind that identity to the participant
4. use composer card create to create a card

**Comment by davidkel** [comment]
@volodyad Have you also raised a JIRA with fabric on this to get their view ?

**Comment by volodyad** [comment]
Seems I have used wrong api, I have tried to use composer identity issue - which invoke register request to fabric-ca. Fabric ca does not support user creation in ldap from fabric-ca. You can not do register request when ldap integrated. Instead you should use composer bind to connect identity to participant

**Comment by davidkel** [comment]
Closing as resolved and not an issue with composer.
