### ISSUE TITLE
Error: Failed to load connector module "composer-connector-embedded" for connection type "embedded". Must create ConnectionManager with a ConnectionProfileManager implementation.

### ISSUE THREAD

**Issue by 5idu** [hyperledger/composer#4463]
## Context
```sh
Error: Failed to load connector module "composer-connector-embedded" for connection type "embedded". Must create ConnectionManager with a ConnectionProfileManager implementation.
```

## Steps to Reproduce

1. [According to the tutorial](https://hyperledger.github.io/composer/latest/integrating/customizing-the-rest-server)
2. cd myProject && npm start
3. An error occurred: 
![image](https://user-images.githubusercontent.com/26264096/46861343-17133480-ce45-11e8-80bd-44445db90a86.png)

## Your Environment

* fabric version: `hlfv12`
* node.js version: `v10.3.0`
* loopback: `3.19.0`
* loopback-connector-composer: `0.20.2`,

**Comment by 5idu** [comment]
Can someone help me..

**Comment by davidkel** [comment]
You are using the wrong version of node. You need to be using node 8. Currently Node 8.12.0 is the latest version so please install nvm as per our installation guide (remove any previous installation of node you might have done via you linux repo package manager for example).
https://hyperledger.github.io/composer/latest/installing/installing-prereqs.html
