### ISSUE TITLE
Cannot install composer-cli

### ISSUE THREAD

**Issue by cristiano-c** [hyperledger/composer#4474]
I try to install `composer-cli` using following command:

`npm install -g composer-cli`

But I get a list of many errors, first of those is:

```
node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.1/node-v64-darwin-x64-unknown.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.1 and node@10.11.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Pre-built binaries not installable for grpc@1.10.1 and node@10.11.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Hit error Connection closed while downloading tarball file 
```

and many others, following.

Using macOS 10.14.

**Comment by davidkel** [comment]
You are using the wrong version of node. You need to be using node 8. Currently Node 8.12.0 is the latest version so please install nvm as per our installation guide (remove any previous installation of node you might have done via you linux repo package manager for example).
https://hyperledger.github.io/composer/latest/installing/installing-prereqs.html

**Comment by riponbanik** [comment]
@davidkel I am getting the following error for ubuntu 14.06. cannot intsall cli

node-pre-gyp ERR! cwd /home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/composer-cli/node_modules/grpc
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.7.0
node-pre-gyp ERR! not ok
Failed to execute '/home/vagrant/.nvm/versions/node/v10.13.0/bin/node /home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/is_epollexclusive_available.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/load_file.oexec install script
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/lockfree_event.oinstall script
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/network_status_tracker.oscript
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/polling_entity.oinstall script
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_set_uv.oinstall script
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_set_windows.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_uv.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_windows.onstall script
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resolve_address_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resolve_address_uv.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resolve_address_windows.ocript
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resource_quota.oinstall script
In file included from ../deps/grpc/src/core/lib/iomgr/resource_quota.cc:19:0:
../deps/grpc/src/core/lib/iomgr/resource_quota.h:22:23: fatal error: grpc/grpc.h: No such file or directory
compilation terminated.
grpc.target.mk:394: recipe for target 'Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resource_quota.o' failed
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resource_quota.o] Error 1
make: Leaving directory '/home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/composer-cli/node_modules/grpc/build'
 ERR! build error ....] \ install: info lifecycle grpc@1.10.1~install: Failed to exec install script
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/home/vagrant/.nvm/versions/node/v10.13.0/bin/node" "/home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
gyp ERR! cwd /home/vagrant/.nvm/versions/node/v10.13.0/lib/node_modules/composer-cli/node_modules/grpc
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/composer-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.10.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-11-02T00_59_26_499Z-debug.log

**Comment by PelotonBlockchain** [comment]
@riponbanik - guess you're having the same problem, even after following the instructions in the install guide, because you have a later version of Node already installed.

$ nvm install --lts
Installing latest LTS version.
v10.13.0 is already installed.
Now using node v10.13.0 (npm v6.4.1)

$ nvm use --lts
Now using node v10.13.0 (npm v6.4.1)

$ node --version
v10.13.0

@davidkel - perhaps worth adding an additional step to the doco to specify the precise version (8.12.0 per your note above) that should be installed?

**Comment by PelotonBlockchain** [comment]
@riponbanik - guess you're having the same problem, even after following the instructions in the install guide, because you have a later version of Node already installed.

$ nvm install --lts
Installing latest LTS version.
v10.13.0 is already installed.
Now using node v10.13.0 (npm v6.4.1)

$ nvm use --lts
Now using node v10.13.0 (npm v6.4.1)

$ node --version
v10.13.0

Instead, you can use a more specific instruction:

$ nvm use --lts=carbon
Now using node v8.12.0 (npm v6.4.1)

**Comment by riponbanik** [comment]
@PelotonBlockchain Thanks. I have figured that out.

**Comment by jonschlinkert** [comment]
> guess you're having the same problem, even after following the instructions in the install guide, because you have a later version of Node already installed.

Here is effectively why many users will have this same issue (and most won't mention it here):

![image](https://user-images.githubusercontent.com/383994/48798039-c4ddf280-ecd1-11e8-92f0-dae4f98dcc1c.png)

That's at the top of the page, which jumps you down to the installation section, where you see this:

![image](https://user-images.githubusercontent.com/383994/48798108-e4751b00-ecd1-11e8-889b-7f4449e42b5e.png)

Which says "latest version". 

It skips past the part of the docs that says the following:

> Node: 8.9 or higher (note version 9 is not supported)

**Comment by raj12892** [comment]
macOS High Sierra 
Version 10.13.6

raj-macbookpro:~ rajdeolekar$ node --version
v10.15.1
raj-macbookpro:~ rajdeolekar$ 
raj-macbookpro:~ rajdeolekar$ npm --version
6.8.0
raj-macbookpro:~ rajdeolekar$ 
raj-macbookpro:~ rajdeolekar$ nvm --version
0.34.0
raj-macbookpro:~ rajdeolekar$ 
raj-macbookpro:~ rajdeolekar$ npm install -g composer-cli@0.19
/Users/rajdeolekar/.nvm/versions/node/v10.15.1/bin/composer -> /Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/cli.js

> dtrace-provider@0.8.7 install /Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
gyp ERR! stack     at Socket.emit (events.js:189:13)
gyp ERR! stack     at Pipe._handle.close (net.js:600:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/rajdeolekar/.nvm/versions/node/v10.15.1/bin/node" "/Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/dtrace-provider
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> fsevents@1.2.7 install /Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> node-report@2.2.1 install /Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/node-report
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
gyp ERR! stack     at Socket.emit (events.js:189:13)
gyp ERR! stack     at Pipe._handle.close (net.js:600:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/rajdeolekar/.nvm/versions/node/v10.15.1/bin/node" "/Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/node-report
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-report@2.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-report@2.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rajdeolekar/.npm/_logs/2019-02-22T07_08_17_593Z-debug.log

Can anyone help me with this?

**Comment by CT99** [comment]
I am having the same issue, running on mac OS X Mojave 10.4.4 with latest x-code installed. 

NOTE: this users has root / admin privs; even so running with sudo or as root doesn't fix the issue; have tried the set global prefix "fix" as indicated here and then NVM complains:
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

PLEASE ADVISE -- we are unable to move forward with composer at this point.

Installed utils and Errors are:

McKinley:~ CT15$ node --version
v8.9.4
McKinley:~ CT15$ npm --version
5.10.0
McKinley:~ CT15$ nvm --version
0.33.0
McKinley:~ CT15$ npm install -g composer-cli
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/composer-cli
npm ERR! path /usr/local/lib/node_modules/composer-cli
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/composer-cli'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules/composer-cli'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules/composer-cli\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/composer-cli' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/CT15/.npm/_logs/2019-04-25T18_20_33_938Z-debug.log
McKinley:~ CT15$

**Comment by bhaskargupta98** [comment]
> macOS High Sierra
> Version 10.13.6
> 
> raj-macbookpro:~ rajdeolekar$ node --version
> v10.15.1
> raj-macbookpro:~ rajdeolekar$
> raj-macbookpro:~ rajdeolekar$ npm --version
> 6.8.0
> raj-macbookpro:~ rajdeolekar$
> raj-macbookpro:~ rajdeolekar$ nvm --version
> 0.34.0
> raj-macbookpro:~ rajdeolekar$
> raj-macbookpro:~ rajdeolekar$ npm install -g composer-cli@0.19
> /Users/rajdeolekar/.nvm/versions/node/v10.15.1/bin/composer -> /Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/cli.js
> 
> > dtrace-provider@0.8.7 install /Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/dtrace-provider
> > node-gyp rebuild || node suppress-error.js
> 
> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: /anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack File "", line 1
> gyp ERR! stack import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack ^
> gyp ERR! stack SyntaxError: invalid syntax
> gyp ERR! stack
> gyp ERR! stack at ChildProcess.exithandler (child_process.js:294:12)
> gyp ERR! stack at ChildProcess.emit (events.js:189:13)
> gyp ERR! stack at maybeClose (internal/child_process.js:970:16)
> gyp ERR! stack at Socket.stream.socket.on (internal/child_process.js:389:11)
> gyp ERR! stack at Socket.emit (events.js:189:13)
> gyp ERR! stack at Pipe._handle.close (net.js:600:12)
> gyp ERR! System Darwin 17.7.0
> gyp ERR! command "/Users/rajdeolekar/.nvm/versions/node/v10.15.1/bin/node" "/Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/dtrace-provider
> gyp ERR! node -v v10.15.1
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> 
> > fsevents@1.2.7 install /Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/fsevents
> > node install
> 
> node-pre-gyp WARN Using request for node-pre-gyp https download
> [fsevents] Success: "/Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote
> 
> > node-report@2.2.1 install /Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/node-report
> > node-gyp rebuild
> 
> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: /anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack File "", line 1
> gyp ERR! stack import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack ^
> gyp ERR! stack SyntaxError: invalid syntax
> gyp ERR! stack
> gyp ERR! stack at ChildProcess.exithandler (child_process.js:294:12)
> gyp ERR! stack at ChildProcess.emit (events.js:189:13)
> gyp ERR! stack at maybeClose (internal/child_process.js:970:16)
> gyp ERR! stack at Socket.stream.socket.on (internal/child_process.js:389:11)
> gyp ERR! stack at Socket.emit (events.js:189:13)
> gyp ERR! stack at Pipe._handle.close (net.js:600:12)
> gyp ERR! System Darwin 17.7.0
> gyp ERR! command "/Users/rajdeolekar/.nvm/versions/node/v10.15.1/bin/node" "/Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/rajdeolekar/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/node-report
> gyp ERR! node -v v10.15.1
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-report@2.2.1 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the node-report@2.2.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /Users/rajdeolekar/.npm/_logs/2019-02-22T07_08_17_593Z-debug.log
> 
> Can anyone help me with this?

Did you get the solution?
