### ISSUE TITLE
Composer: Framework or Tool ?

### ISSUE THREAD

**Issue by zainmustafa** [hyperledger/composer#4475]
## Framework or Tool 

Hi, 
I recently started my work on hyperledger projects. I was wondering if you guys can answer a small query. 
On the official website it defines HYPERLEGER COMPOSER as TOOL but on several online blogs and in Simon Stone presentation even on this repository description it defines composer as FRAMEWORK. 

It will be much help if anyone can clear this. 
 
Thanks.

**Comment by davidkel** [comment]
Please see the introduction on our official documentation page which explains what composer is. It is not correct to define composer as just a tool, but I guess hyperledger couldn't put composer into the framework category as it requires hyperledger fabric to provide the DLT technology. They probably define the term `tool` differently.
https://hyperledger.github.io/composer/latest/introduction/introduction

**Comment by zainmustafa** [comment]
@davidkel 
<img width="657" alt="screen shot 2018-10-21 at 8 01 40 pm" src="https://user-images.githubusercontent.com/9256587/47268586-3b20f500-d56c-11e8-942b-8d9e0777418d.png">
