### ISSUE TITLE
User can submit transaction when his fabric ca certificate is revoked

### ISSUE THREAD

**Issue by volodyad** [hyperledger/composer#4489]
1. I have setup test network via composer, and create test user and import his card. Successfully executed test transaction.
2. Connected to fabric-ca container and execcuted fabric-ca-client revoke -a xxx -s xxx -r keycompromise
3. in fabric ca certificates db identity certificate status changed to REVOKED
4. I have tried to execute transaction again  composer transaction submit -c identitycard -d data
Actual result - execution success
Expected result - authorization failure

I cannot understand why I still can execute transaction even if identity certificate revoked

**Comment by davidkel** [comment]
The Fabric Peers do not communicate with the fabric ca server to determine what certificates are revoked. All you have done is revoke the certificate at the CA. You need to tell the fabric network itself that the certificate is revoked if you want to stop that identity from being able to access fabric. It's probably a config update to tell the fabric that a certificate has been revoked and this isn't something composer provides any capabilities for. I suggest asking on a fabric channel in Rocket Chat for help on this if it isn't described in the fabric documentation.

You can revoke an identity from a business network (which will block that identity from accessing the business network, but it doesn't stop it accessing fabric itself, so for example that identity would still be able to query the ledger directly or listen for block events). The command is `composer identity revoke`. Composer keeps a list of all identities that are registered to the business network and it's marked as revoked after this command. But again I stress that it only revokes access to the business network and not access to the fabric itself.
