### ISSUE TITLE
Components of Hyperledger Composer that need improved testing

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#449]
# Testing Gaps
UT = unit testing ST = system testing end-end  ET = exploratory human testing 
X = required/update
S  = sufficient

Component        |  UT   | ST   | 
--------------   | ----- | ---- | 
Samples          | X     | X    | 
Getting Started  | X     | X    |   
Loopback         | S     | X    | 
CLI              | S     | X    | 
Playground REST  | S     | S    |
Composer UI      | X     | X    |
Client/Admin API | S     | S    | 
Runtime          | S     | S    |
Generators       | X     | X    |
Go runtime       | X     | S    |
HLConnector      | S     | S    |
WebRuntime       | S     | S    |
Connector Proxy  | X     | X    |
EmbeddedRuntime  | S     | S    |

**Comment by caroline-church** [comment]
Added issue #435 for unit testing composer playground

**Comment by nklincoln** [comment]
#292 is relevant here

**Comment by sstone1** [comment]
@nklincoln if this is just an ongoing uber issue to track the test debt, can we close this off and track them with the `qa` tag instead please?
