### ISSUE TITLE
prereqs-ubuntu.sh is now installing node 10

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#4501]
Prereqs-ubuntu script is now installing node 10 now that it has gone lts, however grpc at 1.10.1 will not work with node 10. we need to change the script to ensure it only installs node 8.

**Comment by dragontailys** [comment]
"nvm install --lts" is also install node v10.13. Is this compatible with compose?
If not, please modify the official doc at https://hyperledger.github.io/composer/latest/installing/installing-prereqs.html

**Comment by davidkel** [comment]
Now published new release with fix
