### ISSUE TITLE
Cannot find archive file

### ISSUE THREAD

**Issue by ferheenayaz** [hyperledger/composer#4507]
I have successfully created archive file but when I run the following command:
composer network install -a fabric-dev-servers@0.014.bna -c PeerAdmin@hlfv1
It gives the following error:
Error: Archive file fabric-dev-servers@0.014.bna does not exist.
Command failed

## Possible Fix
Where should archive file be placed?

**Comment by medoamanquer** [comment]
if you exported the bna file using the composer-playgroud
you'll find it in the downloads folder
just navigate there and open the terminal and try this command
composer network install --card PeerAdmin@hlfv1 --archiveFile ./fabric-dev-servers@0.014.bna

**Comment by mahoney1** [comment]
suggest to do a `composer archive list -a <filename>.bna` in the same directory. I'm guessing your version supplied in the param may not be the same. In fact -  you can resolve the name by simply doing `composer archive list -a $(ls fabric-dev-*.bna)`  in the directory where the file is - if it doesn't work, something is wrong with your PATH / env.

**Comment by davidkel** [comment]
Closing as it was user error and no response from reporter in a while
