### ISSUE TITLE
IBM Object Store as a Cloud Wallet

### ISSUE THREAD

**Issue by kamilkamili** [hyperledger/composer#4510]
From what I understood from [this](https://github.com/hyperledger-composer-samples/composer-wallet-ibmcos) github repo. If I create a NODE_CONFIG variable in the terminal instance the composer will use the cloud wallet. 

However, after going through the steps `composer card import` just imports the card in my `.composer` folder and does nothing to the cloud store. Since it's written in the readme of that repo`. The any application (or command line, eg composer card list) that is in this shell will use the cloud wallets.`

Am I missing something? I dont know if its the composer issue or that repo's issue so I am opening an issue on both.

Composer Version: 0.20.4

**Comment by rthatcher** [comment]
If you have the NODE_CONFIG environment variable correctly set (specifying a cloud wallet that exists and that you have access to) then it should work.  (Just tested on Composer v0.20.2)

I would suggest checking the exact format of the JSON for your cloud wallet, and then confirm it is set with `echo $NODE_CONFIG` prior to running a command such as `composer card list`.   

A site [such as this](https://jsonformatter.curiousconcept.com/) will help vaildate the syntax of JSON.

**Comment by kamilkamili** [comment]
Hey, I tried the above. Still, doesn't work. How exactly are you trying the bucket? Are you creating regional or cross-regional? Also if the JSON is not valid, it does say so in the terminal.

**Comment by rthatcher** [comment]
Mine is an EU Cross Region object store, and the Public endpoint I used was:
s3.eu-geo.objectstorage.softlayer.net

**Comment by kamilkamili** [comment]
I just created a new bucket in EU Cross Region. Sharing my details here since I will delete this service anyways. If you can check if this is right or working, I will be really grateful.


```
    "composer": {
        "cardstore": {
            "type": "composer-wallet-ibmcos",
            "desc": "Uses the IBM Cloud Object Store",
            "options": {
                "bucketName": "composer-wallet-v3",
                "endpoint": "s3.eu-geo.objectstorage.softlayer.net",
                "apikey": "EAi1tspTyRETlpdTfZ8iiMGRtzA15LdZ4-VmPULn8W5L",
                "serviceInstanceId": "crn:v1:bluemix:public:cloud-object-storage:global:a/45b86250e486b68dacbd74f9f4d9ac13:3539f3cd-47b5-4301-8e8f-f08636741acb::"
            }
        }
    }
}
```

**Comment by rthatcher** [comment]
Use `wallet` instead of cardstore - I just tested and imported a card to your cloud store.

**Comment by kamilkamili** [comment]
It worked. I can't believe I didn't read the documentation correctly. *facepalm*
