### ISSUE TITLE
error with REST server - not all options appear

### ISSUE THREAD

**Issue by lole2018** [hyperledger/composer#4514]
My REST server does not show me all options! 
![screenshot from 2018-11-19 11-42-50](https://user-images.githubusercontent.com/45192904/48756102-cfd05d00-eca8-11e8-8ca6-10e94e3ad83b.png)

this made me cant add any participant or transaction in Angular! 
![screenshot from 2018-11-19 14-49-18](https://user-images.githubusercontent.com/45192904/48756124-deb70f80-eca8-11e8-9eea-7822ebc34fd1.png)

**Comment by rthatcher** [comment]
There is very little information supplied!
What versions of Composer and Fabric are you running
Do you see any errors from the `composer-rest-server` command?

Are you using the 'Peer Admin' card to start the rest server?
Do you have ACLs in place that are preventing the card you are using from seeing the Business Network?
Try the `composer network list` command with the same card - does that show the Network and the data?

**Comment by lole2018** [comment]
thanks for your replay.. here is the answer

What versions of Composer and Fabric are you running
**compose v0.19.18 the fabric is  v1.1**
Do you see any errors from the composer-rest-server command? **No**
Are you using the 'Peer Admin' card to start the rest server? **No, I'm using the business network application (BNA) admin card **
Do you have ACLs in place that are preventing the card you are using from seeing the Business Network? **No ACL file is exist** 
Try the composer network list command with the same card - does that show the Network and the data?
**Yes**
![screenshot from 2018-11-20 13-10-32](https://user-images.githubusercontent.com/45192904/48766503-affb6200-ecc5-11e8-8fbb-a1b7caffcea7.png)

**Comment by rthatcher** [comment]
The `composer network list` command is showing the same behaviour as the REST server command, i.e. it is not showing the registries.  

Either there are no asset/participant definitions in the model or there are ACLs that are preventing the registries from being seen by the card.  The example below shows typical output when a network has been started, but no data has been added:
![image](https://user-images.githubusercontent.com/29195399/48775845-24ce9c00-ecc6-11e8-96e9-b6c8746ad084.png)

Closing the issue as there is no obvious bug here. 
 @lole2018 Please post a StackOverflow question [https://stackoverflow.com/questions/tagged/hyperledger-composer](url) or join the rocket chat forum [https://chat.hyperledger.org/channel/composer](url) if you have questions about the model or ACL.
