### ISSUE TITLE
Broken link to language and index

### ISSUE THREAD

**Issue by orang3raven** [hyperledger/composer#4526]
Part of the HL Composer online exercise on a car auction, Lab part 3, provides the following (broken) link to learn more about the HLC modelling language: https://hyperledger.github.io/composer/reference/cto_language.html

## Context
The link above is broken. This additional and related link on the forum is also broken: https://hyperledger.github.io/composer/jsdoc/index.html

## Expected Behavior
Send me to a working link

## Actual Behavior
Sends to a broken link page

## Possible Fix
Please provide alternative link where I can learn more about the HLC modelling language, or the general HL documentation

## Steps to Reproduce
https://hyperledger.github.io/composer/reference/cto_language.html
https://hyperledger.github.io/composer/jsdoc/index.html

## Existing issues
As mentioned above

## Context
Learn about HL Composer, as part of an online course

## Your Environment
MS Office, Chrome

**Comment by davidkel** [comment]
All latest documentation can be found at
https://hyperledger.github.io/composer/latest/ eg
https://hyperledger.github.io/composer/latest/reference/cto_language.html
please report the broken links to whoever is referencing them, they should fix them.
