### ISSUE TITLE
Endorsement policy for one organisation with 5 peers

### ISSUE THREAD

**Issue by dattajadhav44** [hyperledger/composer#4530]
Hi Team, I have developed the network for one organisation with 5 peers using nodejs application 
but i am bit confused with endorsement policy. I want atleast 3 peers to endorse the the transaction. how should i define if all peers have to endorse the transaction. 

This is how i am trying to do but its failing. while invoke. can someone please help me with it,

**'endorsement-policy': {
			        identities: [
					{ role: { name: 'peer', mspId: 'Org1MSP' }},
			        ],
			        policy: {
					'1-of':[{ 'signed-by': 0 } ]
			        }
		        }**
But the above approach doesnt really work for me. can someone please suggest over this.

**Comment by davidkel** [comment]
Endorsement policies are across multiple organisations, you can't have an endorsement policy governing peers in a single organisation. Composer doesn't handle endorsement policies. It just passes it the the node-sdk to handle. Further questions on endorsement policies should be directed at fabric themselves and not composer.

**Comment by dattajadhav44** [comment]
I was unable to raise under the fabric hence raied it here, can you please help with fabric link where I can raise it or please divert this to fabric group.
