### ISSUE TITLE
Regression: Main JS Bundle served as HTML in 0.20.6

### ISSUE THREAD

**Issue by hickscorp** [hyperledger/composer#4549]
We had a major head scratcher recently, until we realised that `composer-playground` might have a new bug.

When using `0.20.5` everything's fine. However if we upgrade to `0.20.6` the main JS bundle is served incorrectly, and essentially is serving `index.html` instead (See screenie).

I added a comment on a [*closed* issue](https://github.com/hyperledger/composer/issues/4524) and I really think it should not be closed.

![image](https://user-images.githubusercontent.com/822933/49866212-078d7900-fdff-11e8-89cb-f4544f75a162.png)

**Comment by davidkel** [comment]
Composer playground has not been changed in a long time so no composer code regression has been introduced. Also there is no 0.20.6 version of composer, the latest version of composer is 0.20.5. The online Composer playground is at 0.20.5 and doesn't exhibit this issue for me, nor does a locally npm installed version of composer-playground. I am unable to recreate the issue.

**Comment by dcasado** [comment]
That error also happens to me when I try to put a nginx proxy in front of composer. With the same docker container instance of composer-playground if I try to access it directly it works perfectly fine but if I try through the proxy it always fails.

![image](https://user-images.githubusercontent.com/10188511/50089079-1744fd00-0205-11e9-8e2c-d9cc8762cfaf.png)

**Comment by davidkel** [comment]
closing as this will be an environment issue rather than a bug in composer playground.
