### ISSUE TITLE
An error occurred when I executed the composer card list command

### ISSUE THREAD

**Issue by zcyzhu** [hyperledger/composer#4553]
I am executing the command on ubuntu and want to see my business network, execute the command composer card list but
```
Zcy@ubuntu:~/new project/IOT-foodSupplyChain$ composer card list
Error: Unable to read required file: metadata.json
Command failed
```

**Comment by rthatcher** [comment]
What version of Composer are you using?
How did you create the card(s) you have a problem with?
(I am able to recreate the error by using a "good" card, then removing the metadata.json file from the `~/.composer/cards/<myadmincard>`folder. )

**Comment by davidkel** [comment]
closing as resolved.
