### ISSUE TITLE
namespaces with REST and Angular

### ISSUE THREAD

**Issue by lole2018** [hyperledger/composer#4556]
Avoiding namespaces does not work

## Context
I'm using composer rest server with yo hyperledger composer to generate my angular web app. I avoid using namespaces with both (composer rest & angular) however namespaces are still activated

## Expected Behavior

something like this 
![image](https://user-images.githubusercontent.com/45192904/50206768-7e85bd00-037d-11e9-8d50-97dbb8f1bb6f.png)

## Actual Behavior
That is what i got. However that happens only with variables generated out of (relationship). All other variables are shown properly
![image](https://user-images.githubusercontent.com/45192904/50206792-952c1400-037d-11e9-8d16-ea1837533abd.png)

## Context
When I set a new transaction in my angular app, I’ve to type the full qualified object path. For example, instead of typing the customer email I’ve to write the following org.hyperledger_composer.scms.Customer#xyz@gmail.com . Otherwise I’ll get an error.

## Your Environment

Ubuntu 16.04
composer v0.20.4
node v8.12.0

**Comment by rthatcher** [comment]
Using the option "-n never" (never use namespaces) on the REST server specifies that namespace will not be used for the REST Endpoints.

The namespace will always remain in the data model and in the data itself stored in the ledger and state database - it is a fundamental part of Composer.
