### ISSUE TITLE
Composer Roadmap

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#4557]
This issue has been created to track Composer roadmap proposals and offers of help.

The context for this issue is this message about IBM's future contribution to Composer:
https://lists.hyperledger.org/g/composer/message/125

Please also refer to the Fabric v1.4 programming model enhancements, which have been influenced by similar features/APIs in Composer:
https://fabric-sdk-node.github.io/master/module-fabric-network.html
https://hyperledger-fabric.readthedocs.io/en/release-1.4/developapps/smartcontract.html

Note that the Composer `ModelManager` has already been modularised such that it can be used from Node.js chaincode:
https://www.hyperledger.org/blog/2018/11/28/conducting-data-with-concerto-and-hyperledger-fabric

Ideas:
- Subclass `Contract` to define `ComposerContract`. Add the runtime API methods to this class: `getAssetRegistry`, `getParticipantRegistry`, `getFactory`, `getNativeAPI`, `getSerializer`, `getCurrentParticipant`, `getCurrentIdentity`. These would be implemented as `StateList` instances on the `Contract`.
- Modularize the CQL language to make it a standalone module that people can use to compile CQL queries to MongoDB
- Modulatize the ACL language and runtime to make it a standalone module that people can use to enforce access control
- `ComposerContract` should run a system function before user code to validate the arguments to the function using the Concerto `ModelManager`
- Customize `State` to use the Concerto `Serializer` to generate JSON
- Create a CLI that connects to a Fabric, downloads the CTO models and generates a Loopback v4 model and app.
- Create a Concerto code generator that converts a Concerto model to a set of Typescript domain classes to be used with the new Fabric v1.4 programming model

Issues/questions
- Positions Composer as a set of libraries for Fabric *only*
- ACL modularisation needs deeper investigation
- How can the Historian records be updated automatically?
- Can we do anything to migrate the Playground?
- What happens to the BNA file? For example, a one-time migration facility could be provided that generated a new project structure.
- Do we need dedicated CLIs for deploy?

**Comment by sstone1** [comment]
> Subclass Contract to define ComposerContract

Some of these would be better placed in a subclass of Context, not Contract. 

> Add the runtime API methods to this class: getAssetRegistry, getParticipantRegistry

There really needs to be some thought about asset/participant registries and newer Fabric features such as private data collections; IMO private data collections is one of the biggest and most popular features in Fabric v1.x and Composer currently offers nothing to users in this regard.

> Modulatize the ACL language

ACLs, participants, and identities don't fit well with the Fabric identity model. Most Fabric chaincodes out there do ACLs based on Fabric organisations, and there's no linkage between the Composer participants and Fabric organisations today, which makes things a lot more complicated than they should be.

> ComposerContract should run a system function before user code to validate the arguments to the function using the Concerto ModelManager

The new programming model in Fabric introduces a way to plug in your own data serializers/validators/etc, @mbwhite can provide details.
