### ISSUE TITLE
Confusing description about env.COMPOSER_PROVIDERS, may cause bugs

### ISSUE THREAD

**Issue by Pingze-github** [hyperledger/composer#4558]
## Context
Accroding to [your document](https://hyperledger.github.io/composer/latest/integrating/enabling-rest-authentication), when using github's OAuth service, I should use "callbackURL" to declare the callback_uri.
In github case, it works fine. 

But when I try to make it connect my own OAuth2 provider, I write env like:
```
export COMPOSER_PROVIDERS='{
 "common-oauth2": {
 "provider": "common-oauth2",
 "module": "passport-common-oauth2",
 "clientID": "fabric-bikesharing-network",
 "clientSecret": "fabric-bikesharing-network-secret",
 "authPath": "/auth/common",
 "callbackURL": "/auth/common/callback",
 "successRedirect": "/",
 "failureRedirect": "/",
 "scope": "user_info:read"
 }
}'
```
(My passport named common-oauth2)

I hope it will callback to /auth/common/callback, but I got a 404 error.

I rewrite your source code to print "callbackPath" variable, and got that it is "/auth/common-oauth2/callback". So if I write env as:
```
 "callbackPath": "/auth/common/callback",
```
It works fine.

Summary: Should change the "callbackURL" to "callbackPath" in [your doc](https://hyperledger.github.io/composer/latest/integrating/enabling-rest-authentication)

## Possible Fix
Change the "callbackURL" to "callbackPath" in [your doc](https://hyperledger.github.io/composer/latest/integrating/enabling-rest-authentication)

## Your Environment
* Version used: v0.20.5
* Environment name and version (e.g. Chrome 39, node.js 5.4):nodejs 8.14.1
* Operating System and version (desktop or mobile): Ubuntu 16.04 desktop

**Comment by davidkel** [comment]
for COMPOSER_PROVIDERS you declare a passport module but the properties that follow are specific to the module provided. Our example is for github and as such the properties provided are ones that work for github. If a different provider is selected, be it yours or some other then the properties included are going to be specific to that module. There are examples on the internet showing `local` and JWT and their COMPOSER_PROVIDERS are going to be very different. When you choose to use a passport module you need to research the appropriate properties that are relevant to that module you are using so in your case `callbackPath` is appropriate.

**Comment by Pingze-github** [comment]
> 
> 
> for COMPOSER_PROVIDERS you declare a passport module but the properties that follow are specific to the module provided. Our example is for github and as such the properties provided are ones that work for github. If a different provider is selected, be it yours or some other then the properties included are going to be specific to that module. There are examples on the internet showing `local` and JWT and their COMPOSER_PROVIDERS are going to be very different. When you choose to use a passport module you need to research the appropriate properties that are relevant to that module you are using so in your case `callbackPath` is appropriate.

I still think `"callbackURL": "/auth/common/callback"` is a wrong use for the value is a PATH, but not URL.
