### ISSUE TITLE
Wildcards in Cucumber assertions are not supported

### ISSUE THREAD

**Issue by danionita** [hyperledger/composer#4559]
## Context
Some of the assets have attributes which are filled in by a smart contract (transaction processing function specified in .js), such as a timestamp. The attributes are not known beforehand since they are generated on execution.
When writing .feature test files, I am unable to specify wildcards for these attributes so my tests fail.

## Expected Behavior
I should be able to specify wildcards for some values specified in assertions of type "Then I should have the following assets of type ..." for which I do not know the value or do not care about the value.

## Actual Behavior
If I make the attribute optional in the .cto file and omit it in the assertions the test fails because the attribute was unexpected.
If I I use {} in the value of the attribute as described [here](https://docs.cucumber.io/cucumber/cucumber-expressions/#parameter-types) the test fails.
If I use wildcards as described [here](https://agileforall.com/just-enough-regular-expressions-for-cucumber/), the test fails.

## Possible Fix
Add support for some kind of wildcard or allow test to pass if attributes not specified in the assertion are returned (especially if these are optional attributes).

## Steps to Reproduce
Simplified example:
1. In nl.thevalueengineers.music.cto:
```
namespace nl.thevalueengineers.music
asset Claim identified by claimId {
  o String claimId
  --> Creation creation
  o DateTime submissionDate optional
  o ClaimStatus status
}
asset Creation identified by creationId {
  o String creationId
  o String title optional
  --> Actor[] approvers optional
}
participant Actor identified by actorId {
  o String actorId
  o String name
}
transaction SubmitClaim {
  o String claimId  
  --> Creation creation
}
```
2. In logic.js
```
/**
 * Creates a new Claim
 * @param {nl.thevalueengineers.music.SubmitClaim} claimSubmission - the SubmitClaim transaction to be processed
 * @transaction
 */
async function processSubmission(claimSubmission){

    // Create Claim asset
    let claimRegistry = await getAssetRegistry('nl.thevalueengineers.music.Claim');
    var factory = getFactory();
    var claim = factory.newResource('nl.thevalueengineers.music', 'Claim', claimSubmission.claimId);
    claim.submissionDate = new Date();

    // Approve if no approvers
    if (!Array.isArray(claimSubmission.creation.approvers) || !claimSubmission.creation.approvers.length){
        claim.status = 'APPROVED';
    }
    else{
        claim.status = 'SUBMITTED';
    }
    // Save new Claim on the blockchain
    await claimRegistry.add(claim);
}
```

3. In submitClaim.feature:
```
Feature: Sumbitting claims

    Background:
        Given I have deployed the business network definition ..
        And I have added the following participants of type nl.thevalueengineers.music.Actor
            | actorId |  name  |
            | Actor1  |  Alice  |
        And I have added the following assets of type nl.thevalueengineers.music.Creation
            """
            {
            "$class": "nl.thevalueengineers.music.Creation",
            "creationId": "Work1",
            "title": "RalphsFirstWork"
            }
            """
        And I have issued the participant nl.thevalueengineers.music.Actor#Actor1 with the identity alice1

    Scenario: Actor Alice can submit a Claim
        When I use the identity alice1
        And I submit the following transaction of type nl.thevalueengineers.music.SubmitClaim
            """
            {
            "$class": "nl.thevalueengineers.music.SubmitClaim",
            "claimId": "Claim2",
            "creation": "resource:nl.thevalueengineers.music.Work#Work1"
            }
            """
        Then I should have the following assets of type nl.thevalueengineers.music.Claim
            | claimId | creation   |   status   |
            | Claim2  | Work1      | ?             |
```

The test will fail on the last assertion because submissionDate was unexpected and because I did not pass a value for the status attribute.

## Context
I am unable to test chaincode, containing smart contracts which attach timestamps or generate unpredictable value for some asset attributes.

## Your Environment

* Version used:
```
 "composer-admin": "^0.19.18",
    "composer-cli": "^0.19.18",
    "composer-client": "^0.19.18",
    "composer-common": "^0.19.18",
    "composer-connector-embedded": "^0.19.18",
    "composer-cucumber-steps": "^0.19.18",
    "chai": "latest",
    "chai-as-promised": "latest",
    "cucumber": "^2.2.0",
    "eslint": "latest",
    "nyc": "latest",
    "mkdirp": "latest",
```
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node v8.13.0
* Operating System and version (desktop or mobile): Ubuntu

**Comment by davidkel** [comment]
Unfortunately there are no plans to provide any further enhancements to composer. See https://lists.hyperledger.org/g/composer/message/125
We are recommending that you get familiar with fabric 1.4 and release candidates are available now to get going with fabric and we highly recommend that you focus your efforts on the new programming models both client (fabric-sdk-node) and chaincode (fabric-chaincode-node) side in fabric 1.4.

**Comment by danionita** [comment]
I was hoping this was already implemented but I did not know what the wildcard string is. Is this maybe the case?

**Comment by davidkel** [comment]
I'm not familiar with the cucumber implementation unfortunately, but if it isn't documented then the likelyhood is that it isn't the case. However you can always inspect the code yourself to see if there are capabilities that haven't been documented.
