### ISSUE TITLE
while storing an asset Long Datatype is accepting String without throwing any error , but it is not shown while querying the same asset 

### ISSUE THREAD

**Issue by sushmee04** [hyperledger/composer#4562]
## Context
I have created an asset with some fields of datatype Long, Integer, String etc.,
If I create an asset with data as as string to the long field or Integer field
It was successful without throwing any kind of error.
And If I query the same asset, I got the asset details without these fields

## Expected Behavior
Throw an error and transaction should fail

## Actual Behavior
It was successful without throwing any kind of error.

## Steps to Reproduce
1. Create an asset in .cto file
asset tm identified by TID
{
o String TID
o String EN optional
o Integer TP optional
o Long MN optional 
}
2. Create an asset with following input:
{
  "$class": "tp.tm",
  "TID": "8048",
  "EN": "sampleEN",
  "TP": "abc",
  "MN": "anbvcxf"
}
3. Now check the asset, (see in the list of  assets in composer-playground OR use get by Id in rest-server)
4. Asset looks like following:
{
  "$class": "tp.tm",
  "TID": "8048",
  "EN": "sampleEN"
}
**Long , Integer Fields (MN,TP) are missing** 

* Version used:
Fabric version 1.2 
Composer version v0.20.2

**Comment by davidkel** [comment]
This is due to the serialiser interaction that will deserialise non numbers to `NaN`, which when converted to JSON through JSON.stringify actually then get converted to null. Because the fields are optional a null is considered to be no value provided so no value is actually stored for these fields. That's why it is successful and why when you query it the fields aren't set.

**Comment by sushmee04** [comment]
> This is due to the serialiser interaction that will deserialise non numbers to `NaN`, which when converted to JSON through JSON.stringify actually then get converted to null. Because the fields are optional a null is considered to be no value provided so no value is actually stored for these fields. That's why it is successful and why when you query it the fields aren't set.

**Current behavior**:  effectively, bad content sent for Long fields is silently ignored; rest of fields are saved; so calling program won’t be aware that only partial content of the payload is saved.

**Desired behavior**: exception is thrown when bad content is sent for Long fields; entire record is rejected and nothing is saved into blockchain; caller gets error and will fix the payload and resent.

Is there any setting we can change to get above mentioned desired behavior

**Comment by sstone1** [comment]
@sushmee04 no, there is no setting to get this behaviour.

Please note that the Composer project is seeking new maintainers and contributors, so feel free to get involved and contribute a solution for this issue:
https://github.com/hyperledger/composer/wiki
https://github.com/hyperledger/composer/blob/master/CONTRIBUTING.md

**Comment by dselman** [comment]
Please file an issue on the Composer-Concerto project for this and either submit a PR or I will fix it there.

**Comment by davidkel** [comment]
I would say that the best solution here is for model validation to detect if NaN is present and throw an error. But I also note that the current behaviour for booleans is to coerce to `false` if it isn't a boolean or a string value of 'true'. If coercion for booleans should remain as the correct behaviour than it should also consider replicating the javascript behaviour of coercion to boolean.

**Comment by davidkel** [comment]
a fix for this will be in the next release of composer

**Comment by sushmee04** [comment]
@davidkel In which composer version, can this issue be fixed?

**Comment by sushmee04** [comment]
@davidkel Can you please review this again, In composer v0.20.6 I have executed the same testcase 

And functionality is same;  bad content sent for Long fields is silently ignored; rest of fields are saved; so calling program won’t be aware that only partial content of the payload is saved.
