### ISSUE TITLE
How to upgrade composer 0.19 to 0.20 without losing the ledger data

### ISSUE THREAD

**Issue by CyranoChen** [hyperledger/composer#4564]
I've deployed a real environment with composer 0.19 and fabric 1.1 which run normally for 4 months.
Now I would like to upgrade the fabric from v1.1 to v1.2 which composer 0.20 is compatible with.
I start my work as follow steps.

1. backup my ledger data from real server. The data includes 3 parts as coudb, peer0, order. (I deploy a single org network)
2. Install composer 0.20.5, pull fabric 1.2.1 images on my local mac.
3. generate a network profile (bna) as same logic with the real environment and modify the package.json as 0.20
4. modify the docker-compose.yml adding volume configuration for persisting the data
5. run startFabric script to init containers, create PeerAdmin card, install 0.20 network, start network, import admin card. 
6. All the steps are successful. And I can use the new compose network with version 0.20, fabric 1.2.1 and persist the data.

However, how can I restore the ledger data from my real server (composer 0.19, fabric 1.1) to my local new environment.

I am trying to replace the blockfile files. But after I replace the files, the network excepts and fail to initiate the chaincode.

Would you kindly give me some suggestions on how to restore the old ledger data to a new version environment?

**Comment by davidkel** [comment]
Unfortunately there is no easy way to upgrade to fabric 1.2 from 1.1 with a deployed business network. If you do upgrade your fabric to 1.2 as described above, you still need to upgrade your composer environment from 0.19.x to 0.20.x and there is no official mechanism to achieve this and leave the data in place. 
If you are not interested in preserving the historian records (or the underlying history for a key) then you can write an application to extract all the assets and participants and reload them into a new 1.2 environment. If you are then you would need to find a way to replay all the transactions from the 1.1 environment again into a clean 1.2 environment. I can't say if that is possible as I have never looked into doing that, you may be able to get all the information from Historian for example.

**Comment by CyranoChen** [comment]
Thank you, David. I got it.

I would like to run an application to read all the transaction and run them to my new environment.

By the way, does composer v0.20.x support fabric v1.3 even 1.4?

**Comment by davidkel** [comment]
composer v0.20.x will tolerate fabric 1.3 and we are hoping that it will also tolerate 1.4 as well (it tolerates 1.4.0-rc1) but won't know for sure until 1.4 is finally released.

**Comment by CyranoChen** [comment]
gotcha. Though it is hard for me to upgrade composer 0.19 to composer 0.20.x because I would upgrade fabric 1.2 from 1.1 with a deployed business network, I suppose that it is possible to upgrade fabric 1.2 to 1.3 or 1.4.0-rc1 directly while keeping composer 0.20.x.

I think the only thing should do is to pull the new version of hyperledger fabric docker images and modify the docker-compose yaml file. Do you think it could be work absolutely?

**Comment by davidkel** [comment]
You would be able to upgrade fabric from 1.2 to 1.3 (not sure if there is a supported path from 1.2 to 1.4, but you should be able to do 1.2 to 1.3 to 1.4) and still keep the same level of composer. To understand about upgrading fabric itself you should refer to the fabric documentation for guidance.

**Comment by ivorobioff** [comment]
@rthatcher I have followed this instruction https://hyperledger-fabric.readthedocs.io/en/release-1.3/upgrading_your_network_tutorial.html to upgrade fabric from v1.2 to v1.3. After that, `composer-rest-server` throws this error `access denied: channel [composerchannel] creator org [Org1MSP]`. Do you have any idea what other steps should I do in order to adapt composer with updated fabric containers?

**Comment by davidkel** [comment]
@ivorobioff Sounds like you changed the crypto material of your fabric. It will mean that all you network cards now don't have access

**Comment by ivorobioff** [comment]
@davidkel Thanks for your response. Yes, I actually made a mistake and fixed it later. The problem was that peer/orderer containers created by composer did not store files outside of the containers and after stoping them the files were disappearing. So, I've added volumes to solve that issue.

**Comment by davidkel** [comment]
@CyranoChen @ivorobioff As we are now recommending that you should look to move off of Composer and onto a native fabric solution (with 1.4 being available now with new programming models). You might want to take a look at 
https://davidkel.github.io/docs/Porting/TOC.html
Which should allow you to move to a newer version of fabric and still retain your data.

**Comment by CyranoChen** [comment]
@davidkel thank you for your recommendation.

Is the Hyperledger Composer Porting a next generate product which will replace hyperledger composer?

The porting only works on fabric 1.4. Is it an official project of hyperledger?

**Comment by davidkel** [comment]
@CyranoChen New programming models have been introduced into hyperledger fabric 1.4. These programming models will be extended over time. Hyperledger fabric 1.4 is the TLS release of hyperledger fabric V1. The doc provides some guidance on how to take a composer application and look to re-engineer it using the capabilities available in fabric 1.4. This guide is not an official project but something I created which may be of value. As you know hyperledger composer was not a blockchain system in it's own right, but utilises hyperledger fabric to provide the blockchain technology

**Comment by davidkel** [comment]
Closing as the recommended upgrade path now is to native fabric api, with some guidance provided by https://davidkel.github.io/docs/Porting/TOC.html
