### ISSUE TITLE
Cannot deploy network after successful installation. 

### ISSUE THREAD

**Issue by abhik-99** [hyperledger/composer#4576]
## Context

I am following https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial.html Tutorial Docs. I did everything as written. It worked perfectly until I issued the start command using "composer network start" at which point it gave me an error.
Commands used up to this point:
./startFabric.sh
./createPeerAdminCard.sh
yo hyperledger-composer:businessnetwork
<The name of the network is "test">
composer archive create -t dir -n ../ (I am creating the .bna inside "dist" directory inside the business-network directory)
composer network install --card PeerAdmin@hlfv1 --archiveFile test@0.0.1.bna
Succeeded upto this point and then:
composer network start --networkName test --networkVersion 0.0.1 --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv1 --file networkadmin.card

## Expected Behavior
This should create a networkadmin.card.
## Actual Behavior

This gives me the  following Error:
✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: failed to execute transaction 489bca1152a783d8fa9b2f71001bde83ea5f04c9d72b825b0484d47a4f013228: error starting container: error starting container: Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:latest: API error (500): Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout
Command failed

## Your Environment

* Version used: Composer Version- 0.20.6
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Linux ubuntu 4.15.0-43-generic
* Link to your project:

**Comment by elizoller** [comment]
I am also experiencing this issue. Is there any update?

**Comment by xxLestadxx** [comment]
Instead of this 
```
composer archive create -t dir -n ../
```
execute this command 
```
composer archive create -t dir -n .
```
Then the bna would be in the same folder where you will have your business cards to install afterwards.

**Comment by abhik-99** [comment]
I tried it a second time in my way, there was a TIMEOUT error. So, I edited the docker-compose.yaml file inside 

> ~/fabric-dev-servers/fabric-scripts/hlfv12/composer

 and added the following line
`- CORE_CHAINCODE_STARTUPTIMEOUT=1200s`
to the peer0.org1.example.com container.
Then I did a Teardown and re-executed the same steps. This time, it worked
