### ISSUE TITLE
Cannot use v0.19.19 version of composer with fabric 1.2, v0.20 or higher is required

### ISSUE THREAD

**Issue by Prashasti9** [hyperledger/composer#4579]
Hi, on running following command

./createPeerAdminCard.sh

I received this error

./createPeerAdminCard.sh
Development only script for Hyperledger Fabric control
Running 'createPeerAdminCard.sh'
FABRIC_VERSION is set to 'hlfv12'
FABRIC_START_TIMEOUT is unset, assuming 15 (seconds)

Cannot use v0.19.19 version of composer with fabric 1.2, v0.20 or higher is required

how to fix the above issue?
[SupportingDocuments.txt](https://github.com/hyperledger/composer/files/2776819/SupportingDocuments.txt)

**Comment by pnshore4** [comment]
I'm having the same issue.  npm install -g composer-cli@latest does not fix the issue.

**Comment by joshyjoy999** [comment]
### ** [Step by Step Install Hyperledger](https://hyperledger.github.io/composer/latest/installing/installing-index)**

**### Step 1: Update the CLI tools**

**1. Uninstall the currently installed version of all the CLI tools:**

npm uninstall -g composer-cli composer-rest-server generator-hyperledger-composer

**2. Install the latest version of all of the CLI tools:**

npm install -g composer-cli@0.20 composer-rest-server@0.20 generator-hyperledger-composer@0.20


### **Step 2: Update Playground**

**1.Uninstall the currently installed version of the browser app:**

npm uninstall -g composer-playground

**1.Install the latest version of the browser app:**

npm install -g composer-playground@0.20
