### ISSUE TITLE
Composer runtime downgrade

### ISSUE THREAD

**Issue by mataide** [hyperledger/composer#4583]
## Context
I'd like to deploy a .bna file to downgrade a composer runtime version.

## Expected Behavior
It should allow.

## Actual Behavior
Error: 

```
✖ Upgrading business network definition. This may take a minute...
Error: Error trying to upgrade business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: transaction returned with failure: Error: Cannot upgrade business network. New composer runtime version of (0.19.18) is not compatible with (0.19.19). Composer runtime has changed major or minor version and cannot be upgraded.
Command failed
```

## Steps to Reproduce
1. Publish a .bna file with composer@0.19.19
2. Publish a .bna file with composer@0.19.18

**Comment by davidkel** [comment]
This is working as designed and is not going to change. The code to check is built into the version you are trying to downgrade to, so it's not possible to change even if you wanted to for older releases.
