### ISSUE TITLE
Participant does not have read access

### ISSUE THREAD

**Issue by SirisetyManeela** [hyperledger/composer#4588]
1st error : Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#admin' does not have 'READ' access to resource 'org.hyperledger.composer.system.Network#supply_chain@0.0.1'
Command failed

2nd error : Namespace is not defined for type "org.supply.AirConditioner" in "queries.qry" file (TYPE NOT FOUND EXCEPTION)

3rd error : Expected Namespace "org.supply.SellAirConditioner.*" to be defined (ILLEGAL ACL EXCEPTION)

code:
org.supply.cto:
namespace org.supply

abstract participant Individual identified by id {
    o String id
    o String name
    o Address address
    o Integer phoneNumber
}

concept Address {
    o String addressLine
    o String locality
    o String postCode regex=/\d{4}[ ]?[A-Z]{2}/
}

concept Product {
    o String exportingCompanyName
    o String importingCompanyName
    o String sellerName
    o String sellerId
    o String productId
    o String productName
    o DateTime importingDate 
    o DateTime exportingDate
    o Integer productPrice
    o Integer rating
    o Integer warranty
}

participant RawMaterialSeller extends Individual {
    o String licenseNumber
    o Product rawMaterialDetails
    o Integer RawMaterialSellerRating
/* o String exportingCompanyName
* o String importingCompanyName
* o String productId
* o String productName
* o DateTime importingDate 
* o DateTime exportingDate
* o Integer productPrice
*/
}

participant ProductSeller extends Individual {
    o String licenseNumber
    o Product productDetails
    o Integer ProductSellerRating
}

participant CompanyOwner extends Individual {
    o String companyName
    o Integer companyRating
}

participant Buyer extends Individual {
    o Product productDetails
    o Product rawMaterialDetails
    o Double amountPaid
    o String discount
}

participant Regulator identified by id {
    o String id
    o String name
}

asset AirConditioner identified by acId {
    o String acId
    o Integer efficiencyRating range = [1,5]
    o AirConditionerStatus status default = "AVAILABLE"
    o DateTime purchasedTime
    --> Individual owner
}

enum AirConditionerStatus {
    o MANUFACTURED
    o AVAILABLE
    o PURCHASED
    o SOLDOUT
}

transaction SellAirConditioner {
    --> AirConditioner ac
    --> CompanyOwner companyOwner
/* --> AirConditioner companyOwner */
    --> Buyer buyer
}

event AirConditionerSale {
    o String acId
    o String companyName
    o String BuyerName
}

logic.js:
'use strict';
/**
 * Defining the namespace for the business network
 */
const NS = 'org.supply';

/**
* Transfer AirConditioner from one owner to another
* @param {org.supply.SellAirConditioner} tx - The transferAirConditioner transaction
* @transaction
*/
async function SellAirConditioner(tx) {
     // Get asset registry for AirConditioner
    const acRegistry = await getAssetRegistry(NS + '.AirConditioner');
    
    // Get participant registry for Individuals
    const companyOwnerRegistry = await getParticipantRegistry(NS + '.CompanyOwner');
    const ac = await acRegistry.get(tx.ac.getIdentifier());
		// Make sure that AirConditioner exists
    if (!ac) {
    	throw new Error(`AirConditioner with id ${tx.ac.getIdentifier()} does not exist`);
        }
        // Make sure the ac status is MANUFACTURED and not PURCHASED OR SOLDOUT
	if (ac.status !== 'MANUFACTURED') {
        throw new Error(`AirConditioner with id ${tx.ac.getIdentifier()} is not in MANUFACTURED status`);
    }
    if (ac.status == 'SOLDOUT') {
        throw new Error(`AirConditioner with id ${tx.ac.getIdentifier()} is SOLDOUT`)
    }
    // Get companyOwner ID
    const companyOwnerId = tx.companyOwner.getIdentifier();
    // Make sure that companyOwner exists
    const companyOwner = await companyOwnerRegistry.get(companyOwnerId);
    if (!companyOwner) {
        throw new Error(`CompanyOwner with id ${companyOwnerId} does not exist`);
    }
    // Update ac with new owner
    tx.ac.owner = tx.companyOwner;
    tx.ac.status = 'AVAILABLE';
    // Update the asset in the asset registry.
    await acRegistry.update(tx.ac);
    // Create a Tuna Sale Event
    let acSaleEvent = getFactory().newEvent(NS, 'AirConditionerSale');
    acSaleEvent.acId = tx.ac.acId;
    acSaleEvent.companyName = tx.companyOwner.companyName;

    // buyer registry
    const buyerRegistry = await getParticipantRegistry(NS + '.Buyer');
    //Get Buyer ID
    const buyerId = tx.buyer.getIdentifier();
    // Make sure that buyer exists
    const buyer = await buyerRegistry.get(buyerId);
    if (!buyer) {
        throw new Error(`Buyer with id ${buyerId} does not exist`);
    }
    // Update ac with new owner
    tx.ac.owner = tx.buyer;
    tx.ac.status = 'PURCHASED';
    tx.ac.status = 'SOLDOUT';
    // Update the asset in the asset registry
    await acRegistry.update(tx.supply);
    // Emit the Event
    emit(acSaleEvent);
}

permissions.acl:
rule OnlyOwnerCanTransferAirConditioner {
    description: "Allow only AirConditioner owners to transfer the product"
    participant(p): "org.supply.*"
    operation: CREATE
    resource(r): "org.supply.SellAirConditioner.*"
    condition: (r.ac.owner.getIdentifier() != p.getIdentifier())
    action: DENY
}

rule ReadResources {
    description: "All participants can access the data"
    participant: "org.supply.*"
    operation: READ
    resource: "org.supply.SellAirConditioner"
    action: ALLOW
}

queries.qry:
query getAirConditionerByParticipant {
    description: "List AirConditioner owned by specific 'owner'"
    statement:
        SELECT org.supply.AirConditioner
            WHERE (owner == _$owner)
                ORDER BY [purchasedTime ASC]
}

Please give me the solution to this!!

**Comment by zahichemaly** [comment]
Struggled for 4 hours, but I finally found a fix:

Change the version in package.json to 1.0.0 instead of 0.x.x and restart everything. Make sure to stop Fabric and delete the business network cards using:

`composer card delete -c admin@my-network`
`card delete -c PeerAdmin@hlfv1`

Also, you can try adding those ACL rules just to be sure:

`rule Default {
  description:  "Grant all access by default"
  participant: "org.hyperledger.composer.system.Participant"
  operation: ALL
  resource: "**"
  action: ALLOW
}

rule NetworkAdminUser {
    description: "Grant business network administrators full access to user resources"
    participant: "org.hyperledger.composer.system.NetworkAdmin"
    operation: ALL
    resource: "**"
    action: ALLOW
}

rule NetworkAdminSystem {
    description: "Grant business network administrators full access to system resources"
    participant: "org.hyperledger.composer.system.NetworkAdmin"
    operation: ALL
    resource: "org.hyperledger.composer.system.**"
    action: ALLOW
}`

**Comment by xxLestadxx** [comment]
@zahichemaly The ACL you provide are giving full access of the resources to every participant, which is something you don't want to do in production based software.

**Comment by SirisetyManeela** [comment]
thanks for the response will give a try!!
