### ISSUE TITLE
Is composer project development is postponed or ended?

### ISSUE THREAD

**Issue by adnanjee** [hyperledger/composer#4591]
Hello!

I want to know if the development of hyprledger composer project is postponed or end. I have read at many forums that hyperledger composer is not going to developed any more.
Second the web page of next release is not available.
https://hyperledger.github.io/composer/next/

Thanking you in anticipaion

**Comment by davidkel** [comment]
Please see
https://lists.hyperledger.org/g/composer/message/125
Also see composer release notes
https://github.com/hyperledger/composer/releases/tag/v0.20.7
