### ISSUE TITLE
Google OAuth with Multiuser 

### ISSUE THREAD

**Issue by srikanthpdpl** [hyperledger/composer#4596]
## Context
I have done with Google Oauth sucessfully, but it is not working with multiple users. Seems there is problem with OAuth Module. Please someone put some light on this.

## Expected Behavior
It should allow multiple users to login

## Actual Behavior
Allowing the first user to login and invoke the transaction. When the second user login and try to invoke the transaction it is giving "Authorization Error"

## Possible Fix
Looking for Solution

## Steps to Reproduce
I have setup multi user with restserver with auth as Google OAuth
 Registered a card  (lets say card1) using cli
Logged in with user1 (lets say user1@gmail.com) 
I am able to access rest server successfully.
When I register a one more card (lets say card2 
Tried logging in with user2 (lets say user2@gmail.com)
When I try ti invoke transaction it says "Authorization failure)

## Context
Trying to log with multiple users with Google OAuth

## Your Environment
Fabric 1.0
composer rest server 0.19

**Comment by SJoshi7** [comment]
What steps are you following while registring the user ? I believe you will need to add,issue and export the card for making the user2 to be abel to perform transactions with its own identity.
