### ISSUE TITLE
Plans to migrate to fabric-shim 1.4 version

### ISSUE THREAD

**Issue by volodyad** [hyperledger/composer#4598]
Yesterday fabric-shim 1.4 was released (there is important update of grpc lib), do you have any plans to migrate to the new version (at the moment fabric-shim 1.2.4 used in composer)

**Comment by davidkel** [comment]
No sorry. At this time there is no plan to provide any further releases of composer. I assume you have seen this https://lists.hyperledger.org/g/composer/message/125
