### ISSUE TITLE
Styling of README.md needs more vertical space

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#460]
## Context
The rendering of README.md with lists and sub-headings seems sub-optimal when compared with the rendering of the same file on GitHub.com. In particular the vertical space after lists seems inadequate.

## Expected Behavior
README.md style should more closely resemble what the user sees on GitHub.com

## Actual Behavior
![screen shot 2017-03-14 at 13 53 43](https://cloud.githubusercontent.com/assets/623108/23903806/add04510-08bd-11e7-8802-b0c31b1c977f.png)

## Possible Fix
CSS changes?

## Steps to Reproduce
1. Import the org.acme.shipping.perishable.network sample
2. View the README
3. Compare with the README on GitHub: https://github.com/fabric-composer/sample-networks/tree/master/packages/Perishable-Network

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Context
Hurts my eyes.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4): Safari and FF
* Operating System and version (desktop or mobile): Mac
* Link to your project:

**Comment by winslet** [comment]
Potential fix: Make use of the SCSS styling for the Docs to apply to the Readme. Will look into getting this working next week.

**Comment by winslet** [comment]
Cannot make any changes as of yet due to #706

**Comment by caroline-church** [comment]
@winslet #706 is now closed so this isn't blocked anymore

**Comment by winslet** [comment]
Initial fixes should go in in PR #827
