### ISSUE TITLE
Error trying to ping. Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org2MSP]

### ISSUE THREAD

**Issue by Gyon-Ki** [hyperledger/composer#4609]
I've created a fabric network consist of 3 org ( in 3 VM) using docker swarm, I created the channel and created a card of each org, also start the network. Now I'm following this [tetorial](https://hyperledger.github.io/composer/v0.19/tutorials/deploy-to-fabric-multi-org) to deploy a bussiness network to my network. I got an error when I run --> composer network ping -c alice@trade-network

## Context
error I got: Error: Error trying to ping. Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org2MSP]
Command failed
(I got same error in 3 orgs) 
## Expected Behavior
the connection to the network was successfully tested: trade-network

## Actual Behavior
the connection to the network was successfully tested: trade-network

## Possible Fix
The error is strange because before when I try to invoke transaction I got the same error but then I start my network again, but this is not the solution! How many times should I shut down and start my network?

* Version used:
composer: 0.19.20
hyperleadger fabric: 1.1

**Comment by Gyon-Ki** [comment]
?

**Comment by franke92** [comment]
> I've created a fabric network consist of 3 org ( in 3 VM) using docker swarm, I created the channel and created a card of each org, also start the network. Now I'm following this [tetorial](https://hyperledger.github.io/composer/v0.19/tutorials/deploy-to-fabric-multi-org) to deploy a bussiness network to my network. I got an error when I run --> composer network ping -c alice@trade-network
> 
> ## Context
> error I got: Error: Error trying to ping. Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org2MSP]
> Command failed
> (I got same error in 3 orgs)
> 
> ## Expected Behavior
> the connection to the network was successfully tested: trade-network
> 
> ## Actual Behavior
> the connection to the network was successfully tested: trade-network
> 
> ## Possible Fix
> The error is strange because before when I try to invoke transaction I got the same error but then I start my network again, but this is not the solution! How many times should I shut down and start my network?
> 
> * Version used:
>   composer: 0.19.20
>   hyperleadger fabric: 1.1

Did you solve it?
