### ISSUE TITLE
chaincode error (status: 500)

### ISSUE THREAD

**Issue by nk-kamra** [hyperledger/composer#4615]
$ composer network start --networkName tutorial-network --networkVersion 0.0.1 -A admin -S adminpw -c PeerAdmin@fabric-network
Starting business network tutorial-network at version 0.0.1

Processing these Network Admins: 
	userName: admin

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: chaincode error (status: 500, message:  is not a valid endorsement system chaincode)
Command failed

**Comment by nk-kamra** [comment]
Following instructions given on - https://hyperledger.github.io/composer/v0.19/tutorials/deploy-to-fabric-single-org.html

Facing issue on Step-8

**Comment by xxLestadxx** [comment]
1st: Have you set the right environment ? For me ( using Fabric 1.2 ) I need to type 
``` export FABRIC_VERSION=hlfv12 ```

before I start Fabric 
``` ./startFabric ```

**Comment by nk-kamra** [comment]
Thanks a lot
----------
Thanks and Regards
Narinder Kamra (PMP, CSM, CSP)
*CEO and MD*
https://www.linkedin.com/in/nkamra/
+91-8800665460, +91-1244201749
*vDoIT Technologies Private Limited - "Simplifying the world"*
*www.vdoit.in <http://www.vdoit.in>*
*1024, Tower-A, Spaze-i-tech park, Sec-49, Sohna Road, Gurgaon, India*

*Disclaimer:*
*The content of this email is confidential and intended for the recipient
specified in message only. It is strictly forbidden to share any part of
this message with any third party, without a written consent of the sender.
If you received this message by mistake, please reply to this message and
follow with its deletion, so that we can ensure such a mistake does not
occur in the future.*
