### ISSUE TITLE
Restarting composer with causes error "connection fails: Error: Error trying to ping. Error: make sure the chaincode  has been successfully instantiated and try again"

### ISSUE THREAD

**Issue by tocm** [hyperledger/composer#4620]
After restarting the composer server (./stopFabric.sh and ./startFabric.sh) however, it fails to connect again. 

## Context
I installed the latest Composer locally on an Ubantu Linux and then started with the composer.sh. It works fine, I can do anything what I want. After restarting the composer, however, it fails to connect again.
I get the following error: 
Connection fails: Error: Error trying to ping. Error: make sure the chaincode xxxnetwork has been successfully instantiated and try again: getccdata composerchannel/xxxnetwork responded with error: could not find chaincode with name 'xxxnetwork'
It will be retried for the next request.

## Expected Behavior
can find the chaincode

## Actual Behavior
Could not find chaincode with name 'xxxnetwork'
and if reinstall the chaincode .bna, it will lose original data.

## Steps to Reproduce

1. ./startFabric.sh 
2. composer install chaincode.bna 
3. composer-rest-server....... it woks fine and can do anything.
4. ./stopFabric.sh
5. ./startFabric.sh
6. ./composer-rest-server 
7. happen error info. "can't found the chaincode"

## Your Environment
Version used: composer v0.20.7 ,  Fabric 1.2 , node v8.11.1 
Operating System and version (desktop or mobile): ubuntu 16.04 LTS

**Comment by xxLestadxx** [comment]
Are you setting the right environment ? When using Fabric 1.2 this is the following line 
```
export FABRIC_VERSION=hlfv12
```
Etc for v 1.3 and 1.4 . You cannot use 20.7 with Fabric 1.1

**Comment by tocm** [comment]
Dear Yordan, 
      yes, I do it.
      Here's a screenshot of my steps。




Br.
thanks.



At 2019-03-18 22:02:04, "Yordan Gospodinov" <notifications@github.com> wrote:


Are you setting the right environment ? When using Fabric 1.2 this is the following line

export FABRIC_VERSION=hlfv12


Etc for v 1.3 and 1.4 . You cannot use 20.7 with Fabric 1.1

**Comment by tocm** [comment]
Sorry, It's my misunderstanding that the restart of network services is performed in the docker container, not in the stopFabric command.
