### ISSUE TITLE
composer-rest-server count assets on filter not support

### ISSUE THREAD

**Issue by hxgqh** [hyperledger/composer#4621]
Does composer-rest-server api support count assets while using filter(or not)? Couldn't find any docs about it.

**Comment by westudiodev** [comment]
已经不更新了，建议直接用fabric自带的sdk（go或node）开发chaincode QQ：327011019 你到这里问问吧
![WechatIMG11](https://user-images.githubusercontent.com/33219803/54511706-b99f8880-498c-11e9-9cb8-ee470f13f0f1.png)

**Comment by hxgqh** [comment]
Thank you!
