### ISSUE TITLE
composer rest server localhsot:3000 refused to connect

### ISSUE THREAD

**Issue by realChainLife** [hyperledger/composer#4622]
## Context
I've created a business network on Hyperledger Composer and tested it out on Composer playground and it works great. I could add participants, add assets, perform transactions etc. I tried to generate a bespoke rest API for the business network using the guide available at https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial and it worked great as well.

The output for the command composer-rest-server --card admin@my-network is this:

> Discovering types from business network definition ...
Discovering the Returning Transactions..
Discovered types from business network definition
Generating schemas for all types in business network definition ...
Generated schemas for all types in business network definition
Adding schemas for all types to Loopback ...
Added schemas for all types to Loopback
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer

## Expected Behavior
The rest server should be hosted and connection to localhost 3000 must not be refused.

## Actual Behavior
This site can’t be reached localhost refused to connect.

## Steps to Reproduce
Follow the tutorial as given on this site :
 https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial

1. Navigate to the `my-network` directory and run the following command `composer-rest-server`
2. Fill out all the required information.
3. The generated API should be connected to the deployed blockchain and business network.

## Context

I want to use the Open API specification that would be available on `localhost:3000/explorer/swagger.json` to generate a Java client using swagger codegen in order to consume the REST API from a Java application. 

## Your Environment

* Version used: Composer v0.2 
* Operating System and version: Ubuntu 18.04 an Azure resource
* Link to your project:

**Comment by xxLestadxx** [comment]
Try to upgrade your composer-rest-server to newer version. I had problems when my rest was at 20.2.

**Comment by realChainLife** [comment]
Thanks @xxLestadxx I ended tearing down my entire build and starting again - it worked the second time around and I deployed the network without any further problems.
