### ISSUE TITLE
Online composer playground is not running

### ISSUE THREAD

**Issue by Prabhat-Sutar** [hyperledger/composer#4641]
I am not able to browse hyperledger composer playground online.
This link is not working: https://composer-playground.mybluemix.net/login

**Comment by FranciscoImanolSuarez** [comment]
Hello @Prabhat-Sutar , try the following link (https://composer-playground.mybluemix.net/), there you have to wait a little while, I hope I could help.
regards.
Francisco Imanol Suarez

**Comment by davidkel** [comment]
The online playground has been restarted so should be responding better now.
