### ISSUE TITLE
Start fabric issue 

### ISSUE THREAD

**Issue by Stewthebosshog** [hyperledger/composer#4643]
I'm trying to start fabric for my first network but something in my windows 10 environment is not right. It says it cannot find the docker-compose yml file, but it is in the computer like photo here:

## Context
![FabricProblem](https://user-images.githubusercontent.com/25162887/57166868-23e77d80-6dc1-11e9-9647-45ae0755ecbb.PNG)
So I have tried moving the folder to various places including of where the folder should be located, but it's not reading it at all. I think the issue is something environmental for the windows 10.

## Expected Behavior
Start the fabric

## Actual Behavior
Says the file cannot be found even though it's in the right place.
## Possible Fix

Something somewhere in the environment

## Your Environment
* Visual Code with Git as terminal
* Windows 10

**Comment by davidkel** [comment]
Composer and the composer development fabric server are not setup to work on windows. I would suggest using linux in a hypervisor such as vmware, virtualbox or hyperv
