### ISSUE TITLE
Access Control problem in hyperledger composer for non-admin participants

### ISSUE THREAD

**Issue by Mahdad-Baghani** [hyperledger/composer#4647]
I got a question regarding access control in hyperledger composer.
I have read and utilized the instructions in [Hyperledger Composer v0.19 Hiding Historian in ACL](https://stackoverflow.com/questions/50121737/hyperledger-composer-v0-19-hiding-historian-in-acl), but still, I have no success.

## Context

I want to have the following scenario:
1. have a participant defined as the exampleParticipant model

```
namespace org.example
import org.example.assets.*

// participants
participant exampleParticipant identified by Id {
  o String Id
  o String firstName
  o String lastName
}
```

2. have different types of asset models in a namespace called 'org.example.assets'; for simplicity, lets assume I have an asset modeled as myAsset which is derived from exampleAsset:

namespace org.example.assets

import org.example.*

    abstract asset exampleAsset identified by assetId 
    {
     o String assetId
     --> exampleParticipant owner
    }

    asset myAsset extends exampleAsset
    {
     o String title 
     o String description
     o String logoUrl
     --> exampleParticipant issuer
    }
    
every asset is publicly readable for every participant in the network.

3. I do not want every participant to watch the whole historian; he/she can only see the records of transactions made by him/herself
4. I want every participant to see all the issued assets, but only the owner can do administrative functions on that asset.
5. I want all the participants to be able to see other participants, but only admin can register/add new participants

Here is the permissions.acl file I have so far

 ```
    rule Participant_CanOnlyReadOwnHistorian {
       description: "each party should be able to read its own record"
       paricipant(p): "org.example.exampleParticipant"
       operation: READ
       resource(r): "org.hyperledger.composer.system.HistorianRecord"
       condition: (p.getIdentifier() == r.participantInvoking.getIdentifier())
       action: ALLOW
    }
  rule Participants_CanReadParticipantRegistry {
     description: "every participant in the network can bee seen by others"
     participant: "org.example.exampleParticipant"
     operation: READ
     resource: "org.hyperledger.composer.system.ParticipantRegistry"
     action: ALLOW
   }
  rule Participants_CanReadAssetRegistry {
     description: "assets are all owned and publicly read"
     participant: "org.example.exampleParticipant"
     operation: READ
     resource: "org.hyperledger.composer.system.AssetRegistry"
     action: ALLOW
  }

    rule Participant_CanReadNetwork {
       description: "participants can read (connect to) the business network"
       participant: "org.example.exampleParticipant"
       operation: READ
       resource: "org.hyperledger.composer.system.Network"
       action: ALLOW
    }

    rule NetworkAdminUser {
       description: "Grant business network administrators full access to user resources"
       participant: "org.hyperledger.composer.system.NetworkAdmin"
       operation: ALL
       resource: "**"
       action: ALLOW
    }

    rule NetworkAdminSystem {
       description: "Grant business network administrators full access to system resources"
       participant: "org.hyperledger.composer.system.NetworkAdmin"
       operation: ALL
       resource: "org.hyperledger.composer.system.**"
       action: ALLOW
     }
```

## Expected Behavior

I connect to composer playground using my admin card, then I create a new participant and issue and identity for that paricipant. Then I create an 'myAsset' and set the test participant as its owner. 
When I switch to test participant using his card to connect to network, I expect to be able to see the test participant in participant registry and the asset which was issued to test using admin@myexamplenetwork card participant in asset registry.

## Actual Behavior

When I use my test participant id card to connect to network, the asset registry and participants registry are empty.
I added the following lines in my permissions.acl, 
```
rule Participants_CanReadParticipantRegistry {
    description: "no one should hide in this network"
    participant: "org.example.exampleParticipant"
    operation: READ
    resource: "org.hyperledger.composer.system.ParticipantRegistry"
    action: ALLOW
  }
 rule Participants_CanReadAssetRegistry {
    description: "assets are all owned and publicly read"
    participant: "org.example.exampleParticipant"
    operation: READ
    resource: "org.hyperledger.composer.system.AssetRegistry"
    action: ALLOW
 }
```
because without them I would get the following error:
`Error: transaction returned with failure: AccessException: Participant 'org.pledger.PledgerParticipant#neo' does not have 'READ' access to resource 'org.hyperledger.composer.system.AssetRegistry#org.hyperledger.composer.system.HistorianRecord'`

## Steps to Reproduce

1. create model files based on the example I provided
2. do the same for permissions.acl
3. use the fabric-dev-servers repo or byfn at fabric tutorials and example and deploy the business network to fabric
4. start composer-playground
5. create test assets and a test participant. then assign an identity to participant
6. use the test participant id to connect to network
7. check if you can see the asset that you just created and assigend to the test participant

## Your Environment

* Version used: Composer 0.20.8 / fabric 1.4.1
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Linux Mint Tara
* Link to your project: 

what should I do to solve this problem? 

  [1]: https://stackoverflow.com/questions/50121737/hyperledger-composer-v0-19-hiding-historian-in-acl

**Comment by rockingeric** [comment]
@Mahdad-Baghani did you solve this? I got the same problem here.

**Comment by Mahdad-Baghani** [comment]
> @Mahdad-Baghani did you solve this? I got the same problem here.

I didn't get to know what was the actual problem. However, I found a new way of approaching the problem using the hint a helpful stackoverflow user gave me. Look [here](https://stackoverflow.com/a/56210359/6045793)
The thing is you have to stick to already working examples and try to expand them. What was suggested by that user was to look at the "leter-of-credit" example created by HL Composer community. I did end up removing some of the acl rules in letter of credit example, but my problem now longer exists.

**Comment by Mahdad-Baghani** [comment]
[](url)
