### ISSUE TITLE
Error: Card not found: PeerAdmin@hlfv1 Command failed

### ISSUE THREAD

**Issue by hafizzain** [hyperledger/composer#4648]
https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial

## Context
I am working on Hyperledger fabric tutorials. I mentioned the link above. When I run the command: "composer network install --card PeerAdmin@hlfv1 --archiveFile tutorial-network@0.0.1.bna" in 'Step Four: Deploying the business network', I am getting "Error: Card not found: PeerAdmin@hlfv1 Command failed"

Is there anyone who works on Hyperleder by using the above tutorial link? Please Help

## Your Environment
* Version used:
* Node: v8.9.4
* nvm: 0.33.0
* Mac

My Directory Structure: I have a main directory fabric-dev-servers in which I created tutorial-network skeleton business network using Yeoman.

![Screenshot 2019-05-15 at 09 01 48](https://user-images.githubusercontent.com/12877221/57749673-177ff080-76f0-11e9-9d8a-f1238509eb8e.png)

**Comment by Mahdad-Baghani** [comment]
It seems you are following the composer tutorial in which you have to start fabric using 'fabric-dev-servers' repo. In that case, just after you run the command 
`$ ./startFabric.sh`
run the following command so the PeerAdmin card would be created and imported
`$ ./createPeerAdminCard.sh`
then you can :
`composer network install --card PeerAdmin@hlfv1 --archiveFile tutorial-network@0.0.1.bna`

**Comment by official-akshayjadhav** [comment]
while doing this step `$ ./createPeerAdminCard.sh` I am getting following errors:

```
Error: Card already exists: PeerAdmin@hlfv1
Command failed

 Error: Unable to read required file: metadata.json
Command failed
```
how to fix it?
thanks for feedback

**Comment by Mahdad-Baghani** [comment]
> 
> 
> while doing this step `$ ./createPeerAdminCard.sh` I am getting following errors:
> 
> ```
> Error: Card already exists: PeerAdmin@hlfv1
> Command failed
> 
>  Error: Unable to read required file: metadata.json
> Command failed
> ```
> 
> how to fix it?
> thanks for feedback

You should probably remove the card first to be able to test this.
try using this:
`composer card delete --card name_of_the_card`

**Comment by nimit199** [comment]
First check the composer card list by
```composer card list```
then check if there are any other(other than PeerAdmin) existing cards. If not then use
```composer network install --card PeerAdmin@hlfv1 --archiveFile tutorial-network@0.0.1.bna```
if there are any other cards existing then remove the existing cards by
```composer card delete --card name_of_the_card```
as @Mahdad-Baghani said.
and then re-install your tutorial-network@0.0.1.bna
