### ISSUE TITLE
MAJOR Documentation Unavailable

### ISSUE THREAD

**Issue by hgrgic** [hyperledger/composer#4650]
Every latest documentation page is unavailable. 

## Context
I am not sure if this is because of some general update but entire documentation is throwing unavailable page.

## Expected Behavior
Documentation should be opened, but instead only what I see is Oh no!…there’s no blockchain here :(

## Steps to Reproduce
Open https://hyperledger.github.io/composer/latest/tutorials/playground-tutorial/

## Your Environment
* Safari:Version 12.1 (14607.1.40.1.4); Chrome:Version 74.0.3729.131 (Official Build) (64-bit) and every other browser
* MacBook Pro macOS Mojave

**Comment by ryjones** [comment]
thank you!

**Comment by davidkel** [comment]
no problem with docs, just remove the trailing slash, eg.
https://hyperledger.github.io/composer/latest/tutorials/playground-tutorial
