### ISSUE TITLE
No documentation for handling Composer certificate expirations

### ISSUE THREAD

**Issue by lesleyannjordan** [hyperledger/composer#4652]
Composer relies on the X509 certificate system for access first to the fabric network and then to the business network itself. X509 certificates have an expiration date therefore Composer applications including the Composer business network as well need to have a process in place to ensure that users, and this includes any defined administrator type users, are not locked out of the application/business network.

In fact, there is the potential that if all users’ certificates expire then you will be locked out of the business network completely with no way to recover.

Request to have some documentation on how to renew Composer network certificates

**Comment by lesleyannjordan** [comment]
Documentation added to the wiki Education section:

https://github.com/hyperledger/composer/wiki/HandlingCertificateRenewal

**Comment by davidkel** [comment]
added qa tag to stop this issue from going stale

**Comment by ryjones** [comment]
⚠️ ⚠️ ⚠️

As of the 29th August 2019, the Hyperledger Composer project is in deprecated status. None of the maintainers are actively developing new features. None of the maintainers are actively providing support via GitHub issues. However, if you wish to submit code changes via pull requests, these will be merged.

It is highly recommended that you use Hyperledger Fabric v1.4+ instead, which features significant improvements to the developer experience, including a new programming model.

More information available here: What's new in Hyperledger Fabric v1.4

⚠️ ⚠️ ⚠️
