### ISSUE TITLE
“Error: 14 UNAVAILABLE: TCP Write failed” with hyperledger blockchain application

### ISSUE THREAD

**Issue by Bagoos** [hyperledger/composer#4657]
I am actually working with this Hyperledger Fabric blockchain application on my computer (https://github.com/rastringer/medication-blockchain) and I can run the application on port 8000.

But I have a problem: when I want to create drug record or change drug holder with the application on port 8000, I have this message in my terminal:

"... Transaction proposal was good
Successfully sent Proposal and received ProposalResponse: Status - 200, message - ""
Failed to invoke successfully :: Error: There was a problem with the eventhub ::Error: 14 UNAVAILABLE: TCP Write failed"

And sometimes I have the same message but with:

..."TCP Read failed"

More, the green message with the success of the transaction and the transaction ID is not writing like the example in the picture, and this for the both (create drug record & change drug holder).

But when I refresh the page on the port 8000, the new transaction appears in the table, even if there is the message error.

And I checked the application in another computer, and there is not this problem (I have the last version of Linux Ubuntu 18.04.2)

Somebody told me it's probably a problem with the GRPC, or a problem with the person code who build this app (maybe he changed some code on hyperledger fabric pre existing code to adapt his app)

Thank you in advance for any help :)

**Comment by davidkel** [comment]
Sorry, closing this as it has nothing to do with Hyperledger Composer
