### ISSUE TITLE
Cannot use v0.16.2 version of composer with fabric 1.2, v0.20 or higher is required

### ISSUE THREAD

**Issue by hwaming0101** [hyperledger/composer#4671]
I'm trying to run the following setup `./createPeerAdminCard.sh`

but it throws the error below

> Development only script for Hyperledger Fabric control Running 'createPeerAdminCard.sh' FABRIC_VERSION is set to 'hlfv12' FABRIC_START_TIMEOUT is unset, assuming 15 (seconds) Cannot use v0.16.2 version of composer with fabric 1.2, v0.20 or higher is required

I've tried to uninstall and reinstall the composer but it still couldn't work.

**Comment by nimit199** [comment]
First Follow This
https://hyperledger.github.io/composer/latest/installing/uninstall-dev-env.html
Then Follow This
https://hyperledger.github.io/composer/latest/installing/installing-prereqs.html
and this
https://hyperledger.github.io/composer/latest/installing/development-tools.html

Make sure the prereqs are proper.

**Comment by ryjones** [comment]
⚠️ ⚠️ ⚠️

As of the 29th August 2019, the Hyperledger Composer project is in deprecated status. None of the maintainers are actively developing new features. None of the maintainers are actively providing support via GitHub issues. However, if you wish to submit code changes via pull requests, these will be merged.

It is highly recommended that you use Hyperledger Fabric v1.4+ instead, which features significant improvements to the developer experience, including a new programming model.

More information available here: What's new in Hyperledger Fabric v1.4

⚠️ ⚠️ ⚠️
