### ISSUE TITLE
Deploying a Hyperledger Composer blockchain business network to Hyperledger Fabric (multiple organizations) has a little issue for tmp directory creation command in  'latest' documentation

### ISSUE THREAD

**Issue by shadab14meb346** [hyperledger/composer#4674]
Within documention
https://hyperledger.github.io/composer/latest/tutorials/deploy-to-fabric-multi-org
The section in which the command for creating tmp folder is this incorrect

`mkdir -p /tmp/composer/org1`
`mkdir -p /tmp/composer/org2`

**It should be**

`mkdir -p tmp/composer/org1`
`mkdir -p tmp/composer/org2`

**Comment by davidkel** [comment]
Sorry, but it is correct it is referencing the tmp directory found on standard unix systems which is off of the root directory (ie /tmp). other parts of the tutorial explicitly reference these directories.
