### ISSUE TITLE
Possibility to include Convector as an alternative in the deprecation header

### ISSUE THREAD

**Issue by diestrin** [hyperledger/composer#4692]
## Context
Given the [recent commits](https://github.com/hyperledger/composer/commit/12800550440030d253a9e73be8650d331b14597f) of composer being deprecated, we (convector org) wanted to know if it's possible to include a link to Convector as one of the alternatives alongside with the native Fabric option.

Convector is [under the hyperledger-labs initiative](https://github.com/hyperledger-labs/convector) right now, with over +55k downloads, and a lot of our Discord community members are developers that discovered the framework while trying to find a migration path out of Composer, in fact we have articles describing [how to do so](https://hackernoon.com/migrating-from-hyperledger-composer-to-convector-framework-marbles-example-13a24a74faad).

If you think it's fine, I can send a PR updating the readme with a small reference to Convector as an alternative option.

Best regards.

**Comment by sstone1** [comment]
I would be worried that any such reference to Convector would come across as a form of endorsement for Convector by the Composer contributors and maintainers. There is no such endorsement, so it's a no from me.

The recommendation from from the Composer contributors and maintainers, excluding Dan Selman (who I cannot speak for!), is that Composer users migrate to building their smart contracts and applications using Fabric v1.4.

We would not recommend that users use any other framework similar to Composer, especially one that seems to be over reliant on [one developer](https://github.com/hyperledger-labs/convector/graphs/contributors), and is also liable to be "eaten from below" over time as we continue our efforts to extend the Fabric programming model.

Of course, we would very much welcome assistance with our efforts to improve Fabric. If you wanted to get involved there, then check this page out: https://hyperledger-fabric.readthedocs.io/en/release-1.4/CONTRIBUTING.html

BTW, using your bot `worldsibu-bot` to vote on GitHub issues is kind of bad form 😉

**Comment by diestrin** [comment]
It's a shame to hear that, but it's ok. Convector is nothing like Composer, and the framework is actually built on top of the Fabric libraries with no hard dependency. Any new update in the fabric libraries is supported by Convector on day 0, because of the patterns we have applied.

But anyways, thank you for your response, and I hope you guys continue to improve the Fabric libraries, as this will only make Convector better.

BTW, using the bot was definitely a mistake, not intended to do so.
