### ISSUE TITLE
IIB loopback-connector Update operation

### ISSUE THREAD

**Issue by kylelorenz** [hyperledger/composer#477]
## Context
I'm using IIB as the integration tool leveraging loopback-connector. With the operation of 'Create' I can successfully submit a json object for a new Asset and see the payload on the blockchain. However, the transaction seems to fail if sending in an updated json for that same Asset (using same identified by field). [fyi... this works currently via the rest server using Put-by-ID transaction.] So I tried a similar IIB message flow with operation of 'Update' however that does not seem to get submitted either (not seeing any transaction on the blockchain). Any suggestion on how loopback-connector is intended to work for submitting updated Assets... or if I'm doing something incorrect with my test/setup? 

## Expected Behavior
'Update' operation will process transaction.

## Actual Behavior

'Update' operation appears to hang... transaction not sent to blockchain.

## Steps to Reproduce

1. Setup message flow in IIB leveraging 'Create' operation... and submit json.  Transaction processed to blockchain successfully.
2.  Setup message flow in IIB leveraging 'Create' operation... and submit json with same key/identified-by but with some other updated values.  Issue is that transaction is not processed.
3.
4.

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by mbwhite** [comment]
I've been looking into this and believe that I may have reproduced the issue. What I've done is create two IIB flows that read from a CSV file, and convert to JSON, that is then passed to a REST Request node. 

One flow is for creating assets (POST) the other is for updating the assets (PUT).  I've been able to create as many assets as I like, but errors do occur on the PUT for the update - so the asset is not updated. Currently looking into that. 

This isn't using the loopback node though in IIB

**Comment by kylelorenz** [comment]
Per our Slack conversation, the issue I was seeing was leveraging the loopback node within IIB.  Thanks,

**Comment by mbwhite** [comment]
@kylelorenz could you detail which version of IIB and what platform?  Is this Windows or Linux.  
Where abouts is the IIB Integration node run and where is the HyperLedger Fabric running.

**Comment by kylelorenz** [comment]
@mbwhite I have a Windows7 workstation so am running everything (IIB and Fabric) within Ubuntu 14.04 via VMWare.  The IIB version is 10.0.0.7.  Thanks,
