### ISSUE TITLE
As a user I should not have to specify which field a transaction is identified by

### ISSUE THREAD

**Issue by 14gracel** [hyperledger/composer#488]
When creating a a new transaction in a model, you need to define a field e.g. `transactionId` which the transaction is identified by. This seems unnecessary as all transactions will call the identifier `transactionId`

## Expected Behavior
When defining a transaction, rather than this
```
transaction MyTransaction identified by transactionId {
    o String transactionId
}
```
by default, it could be written as
```
transaction MyTransaction {
}
```
and the identifier field is automatically set to a field named `transactionId` (or something similar)

**Comment by sstone1** [comment]
Closing this off, it will be implemented in #920 by system core types.
