### ISSUE TITLE
UI Nitpicks - v2

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#496]
This issue is used to collect all minor "nitpicks" with the Composer Playground UI.  Use it for things that you don't think really merit a full issue to themselves e.g. typos, ordering issues, wrong icons etc.

## Using the list

- Add a checkbox for each new item, and number it
- As items are fixed, they can be ticked off
- If items are decided invalid (via discussion in comments), they can be ~~crossed through~~ (leave them there so we maintain the numbering and don't lose the fact we discussed it!)
- If we decide an item needs its own issue, we can again ~~cross through it~~, and also reference the new issue!
- If you claim an item, put your name next to it so that we don't duplicate fixes

## The list
- [x] (01) We need a favicon icon **SamS**
- [x] (02) Submit transaction drop down needs styling - **SamW** to provide design
- [x] (03) Import modal contents aren't full width of the modal - **Caroline**
<img width="747" alt="screen shot 2017-03-17 at 08 46 18" src="https://cloud.githubusercontent.com/assets/23044145/24035620/429bdd1c-0aee-11e7-931a-c7c5c86d75ec.png">

- [x] (04) On test page ID and DATA shouldn't be in capitals - **MarkL**
- [x] (05) When generate random data button is clicked json view shrinks it also expands again when typing - **SamS**
- [x] (06) Magic disappearing buttons and various other component issues in modals, on IBM ESR Firefox v45.8.0 (more info: resizing the browser window seems to remove white boxes)
![image](https://cloud.githubusercontent.com/assets/13980028/24039893/bfd6ca16-0afe-11e7-9f6a-409b5667f366.png) - **Caroline**

**SamS**: I had a look at this and can make the problem go away by deleting the `&.gradient` and `&.tiny-gradient` defs in the registry.scss but then we lose the graduated text for the 'Show All' button. 
I couldn't figure out how how to fix this (which affects buttons all over the place, in modals etc.) without just removing it :(
So I'll leave it in there for now until someone with a better understanding of FF support of obscure CSS properties can figure it out!
**Caroline**: Think i've got a solution for this so i'll take this 

- [x] (07) The transaction registry heading does not vertically align with the other registries headings, so if you switch between them the text moves around. **SamS**
- [ ] (08) Files on the _Define_ tab show validation errors as you type, however this feature is missing when you edit participants and assets on the _Test_ tab
@EdMoffatt so you get JSON validation status shown when editing assets and participants but you don't get model validation - is this what this nitpick is driving at because if so, I think that's bigger than a nitpick and more of an issue in its own right.

- [x] (09) Welcome panel update - new wording and illustration - **EdM**
- [x] (10) Replace globe icon with "Install local version" link **Caroline**
- [x] (11) When go to test panel the first registry is selected by default @EdMoffatt can you say what this should be? **SamS**
- [x] (12) When you hover your mouse over a registry it should change the pointer **SamS**
- [x] ~~(13) Cannot name new files~~
- [x] ~~(14) Cannot rename existing files~~ This one's been raised as a full issue: #387 
- [x] (15) Samples from GitHub should be shown in a set order: "basic-sample-network", then "carauction-network", then the remaining ones (perhaps in alphabetical order)?  This is to make it easier to find the ones that we use in tutorials and labs! **SamS**
- [x] (16) When adding a new member, the size of the 'grey' window changes size depending on how much text is typed. Think it should stay the same proportions as the overal dialog
- [ ] (17) Addin random data is great, but it's not consistent.  Hard to do possibly, but maybe worth warning?
- [x] (18) Not sure about the Submit Transaction button - whereas everything else is add something new top right.  Transactions are bit different but on first view, I'm wondering why there's a submit transaction and nothing else
- [ ] (19) When does my state get cleared? It's not clear when that happens or what I have to do to achieve that
**SamS** You can clear your state using the dev console in FF or chrome by typing `localStorage.clear()` but that's a bit of a techie way of doing it.  We could add a button somewhere to help people with this.
- [x] (19.a) The splash screen indicates that the simple hello world model will be loaded. However if you've got state it isn't... indicate this in the splash screen - with option to clear the state?
**SamS** Agreed, this isn't great.  The splash screen is wrong if you've ever changed the model for the simple hello world, or loaded a new one.  
I think that we could do with some design input here @winslet please :)

- [x] (20) Could we make the readme pop-out-able (or viewable in separate window) so I can refer to it whilst working on the network?  Currently I'd have to cut and paste it... to notepad. 

- [x] (21) Update button enabled if package name or version are selected, not changed, then navigated away from. Replicate via opening Composer, select file, select edit, click on name, then click on version without making changes. Update button becomes active, despite no changes. **Caroline**

**Comment by EdMoffatt** [comment]
Regarding (10), here's the desired behaviour...

In the local Playground UI (once we have ID implemented), the top-right will look like this:
![image](https://cloud.githubusercontent.com/assets/7454304/24143226/ebce572c-0e20-11e7-8b21-e99bad8480a2.png)

In the web version, it should instead look like this:
![image](https://cloud.githubusercontent.com/assets/7454304/24143271/15e7dda8-0e21-11e7-82d4-af4fa1b47797.png)

Clicking that link will take the user to the "how to install and run Fabric Composer locally" instructions page on the Documentation.

The full Docker icon is a little detailed for the size we'd be displaying it at (it's there to imply that the local install means running it in a Docker container by the by), so I've made a simplified version for us to use there: https://ibm.box.com/s/ir8f591fjm6ai929kcse4n2fiab3mhpk

I probably shouldn't go implementing this change as it involves awareness of creating a difference between the web and local builds...  So I'll untag myself from it now and leave it to somebody smarter to implement ;)

**Comment by EdMoffatt** [comment]
Regarding (13)...  In my opinion, once we fix (14), I think we're ok here.  The behaviour we have of just giving things a unique path automatically is pretty nice for just getting *something* to appear the UI and then start editing it in place.  I'm gonna strike-thru that one, let me know if any objections!

**Comment by EdMoffatt** [comment]
Hi-fis for (10):

On the local build, where it's possible to switch connection profiles, the top bar looks like this:
![image](https://cloud.githubusercontent.com/assets/7454304/24348741/aef3948a-12d4-11e7-8a23-73c1f0933cdf.png)

Then if they're using the bluemix-hosted version (where connection profiles are not available), they'll instead see this:
![image](https://cloud.githubusercontent.com/assets/7454304/24348905/3f8a0f38-12d5-11e7-90f6-d9b92b2e88af.png)

Hover is different because this is linking them off out of the UI (relevant docs page should open in a new tab i.e. the page that tells you how to get the Docker version of Playground):
![image](https://cloud.githubusercontent.com/assets/7454304/24349005/962df570-12d5-11e7-86d6-787e07769c0b.png)

And if we want to be good and responsive, we could cut off the text as we get down to smaller screen sizes:
![image](https://cloud.githubusercontent.com/assets/7454304/24349066/cdbd0404-12d5-11e7-873a-ee128f3811dd.png)

**Comment by EdMoffatt** [comment]
Oh, and the Docker icon looks good at 20px height for me ;)

**Comment by EdMoffatt** [comment]
(11) - This should be the first Participant registry on the list i.e. whichever one is at the top of the list of registries in the navigation on the LHS (not the first Asset registry as behaviour currently seems to be).  

If we want to be even smarter, we could store the registry that the user was previously in, such that if they flick over to another tab and then back here, they'll be in the same registry they were in before, and we just use the first Participant Registry as a default.

**Comment by samjsmith** [comment]
For nitpick 16 above, I'm marking this as done since I added horizontal scrollbars and made it a fixed width in the PR for nitpick 5.  Here's a screengrab of how it is now but feel free to unmark if I've missed the point here.

![image](https://cloud.githubusercontent.com/assets/16335033/24601916/a0d97f4e-1852-11e7-9a01-d8040078aa13.png)

**Comment by caroline-church** [comment]
Closing as this is really old now
