### ISSUE TITLE
fabric-composer.org nitpicks March 2017

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#504]
This issue is used to collect all minor "nitpicks" with the fabric-composer.org docs (i.e. not stuff in the Playground).  Use it for things that you don't think really merit a full issue to themselves e.g. typos, ordering issues, wrong icons etc.

Note that there's a separate issue for stuff in the PLayground UI: #496 

## Using the list

- Add a checkbox for each new item, and number it
- As items are fixed, they can be ticked off
- If items are decided invalid (via discussion in comments), they can be ~~crossed through~~ (leave them there so we maintain the numbering and don't lose the fact we discussed it!)
- If we decide an item needs its own issue, we can again ~~cross through it~~, and also reference the new issue!
- If you claim an item, put your name next to it so that we don't duplicate fixes

## The list

- [x] (01) Data integration text on main page isn't vertically aligned with the other text
- [x] (02) Loopback on the main page should be spelt LoopBack
- [x] (03) Github at the bottom of the main page should be spelt GitHub
- [x] (04) Homepage needs more graceful feedback for flexbox issues on ios.
- [ ] (05) Insert some useful images of what the users are getting into https://github.com/fabric-composer/fabric-composer/blob/master/README.md
- [x] (06) Overview page of docs should have a "this is Fabric Composer's role in this whole thang" diagram, showing the relationship to Fabric and where the boundaries lie
- [x] (07) https://fabric-composer.github.io/introduction/introduction.html has a typo:

> For an example of a business network in action; a realtor may have a business network containing houses and listings as assets. Participants could include buyers and homeowners. Transactions might include buying or selling houses, and creating and closing **lsitings**.”

- [x] (08) Main CTA to change to "Try It Out" (linked to some changes in the Playground - Ed to coordinate these!) - **EdM**

**Comment by dselman** [comment]
This has been open for too long. If these are going to linger they need to be broken out into their own issues for tracking.

**Comment by winslet** [comment]
Going to close this as it has become stagnant. The only remaining issue is the Readme file images which are not critical at this stage.
