### ISSUE TITLE
As an end user I can add a permissions.acl file in the Playground

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#505]
## Context
When creating a new business network definition (or editing an existing sample to add ACLs) it will be necessary to add permissions.acl to a business network definition.

## Expected Behavior
Allow a template permissions.acl file to be added

## Actual Behavior
Cannot add a new permissions.acl

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Context
Trying to add access control to a new or existing business network.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by winslet** [comment]
Will wait for confirmation from @EdMoffatt or @Tobias-Hunter but please find the ACL illustration attached ready to go:

[ACL_File_Illustration.zip](https://github.com/hyperledger/composer/files/1068110/ACL_File_Illustration.zip)

**Comment by Tobias-Hunter** [comment]
The same behaviour as the README.md files, we will not allow a user to create a new ACL file. If a user drag & drops or browses to a different ACL file we will replace the current ACL file in their model! 🎈
