### ISSUE TITLE
As an AppDev I want to use the Composer tools to generate code from the BNA

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#511]
## Context
It's advertised that the CTO files are good starting point for generating artifacts for helping me write
my own application. The codegen tools are not working correctly and are hard to locate in the composer-common module

## Expected Behavior
Expecting these to be more widely available.  There is a undefined variable when they are run. 

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by dselman** [comment]
This sounds like a mixture of bug and enhancement. Can you please split into 2 so we can make progress?

**Comment by mbwhite** [comment]
Will close this and re-open;
