### ISSUE TITLE
Redesign ui on composer generator

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#527]
The ui for the generator needs redesigning

**Comment by EdMoffatt** [comment]
Could we maybe add to this one with a description of what the Generator is, and screenshots of how it is at the moment + the reason for the re-design?  If we made it a more accessible issue for somebody new to pick up, it might be a good opportunity to encourage any would-be-committer Designers we have in the community to get involved in the project, since it's neatly separate from the Playground work??
Any ideas who would be best to add in that detail and info, @mbwhite ?  Could we assign out to someone to add that in?

**Comment by ilfrich** [comment]
Just to clarify - is this about:

(1) re-designing the Angular application that is generated OR 
(2) about re-designing how the generator picks up the data model and generates the app?

**Comment by sstone1** [comment]
@ilfrich the first - redesigning the generated Angular application so the UI sucks less, and also includes generated components for all Composer features where relevant (like transactions in #400).

**Comment by ilfrich** [comment]
Gotcha. I can take a look at this. But the plan is to stick with Bootstrap, right?

**Comment by ilfrich** [comment]
My suggestion would be to have a component structure (easier to reuse in a custom application). This is a first shot at it of a rough component structure / hierarchy.

- `AssetListView`
    - `AssetListing`
        - `AssetListHeader`
        - `AssetListItem`
    - `AssetModal` as wrapper container
        - `AssetForm` new and edit
- `AssetDetailView` 
    - `AssetDetails` detail view of an asset with `href` references to associated assets and transactions
    - `AssetModal` as wrapper container
         - `AssetForm` edit
- `AssetFormView`
    - `AssetForm` new and edit
- `TransactionListView`
    - `TransactionList`
    - `TransactionForm`
    - `TransactionModal` (maybe?)
- `TransactionDetailView`
    - `TransactionDetail`
- `TransactionFormView`
    - `TransactionForm`
- _Participant structure same as for assets_
- _Maybe some additional views for personalised participant management (e.g. edit my own profile)_

In general I see potentially a lot of reusable components here, where developers just create a new view and compose whatever they need and orchestrate the data in the view. This requires each of the components listed above to allow for some configuration parameters controlling the behaviour, but primarily just passing data in.

**Comment by ilfrich** [comment]
This is what it currently looks like:

**Landing Page**
![image](https://user-images.githubusercontent.com/4035411/30361683-b49d082e-989b-11e7-985a-0bfb865bcae2.png)

**Asset List**
![image](https://user-images.githubusercontent.com/4035411/30361673-a6697ea4-989b-11e7-8ba0-1ef7a37806f8.png)

**Asset New/Edit Modal**
![image](https://user-images.githubusercontent.com/4035411/30361694-c6910e9a-989b-11e7-99f9-3f00697975f8.png)
![image](https://user-images.githubusercontent.com/4035411/30361705-d70d7f92-989b-11e7-9e22-6af2112ba09b.png)

**Delete Asset**
![image](https://user-images.githubusercontent.com/4035411/30361734-f7cb7e32-989b-11e7-9076-8ad6bdd2f304.png)

**Comment by sstone1** [comment]
@ilfrich I can't provide much help here as I'm not a UI guy, so it's worth chatting with Sam (@winslet) our UI designer and James (@jt-nti) one of our UI devs.

**Comment by winslet** [comment]
@ilfrich very happy to move away from bootstrap, it includes an awful lot of unneeded classes etc which we can do without. I would prefer to start from scratch if possible on this. 

In terms of the component structure, happy to take your suggestion on this. @jt-nti might have more valid opinions 👍

**Comment by jt-nti** [comment]
@ilfrich also more than happy to move away from bootstrap. Wouldn't mind starting from a lighter weight css framework or from scratch- guess it really depends on what the designs look like. Also like the idea of components that can easily be reused in a custom application- is there any value in separating those out of the generator?

@winslet any thoughts on the design? Something based on http://carbondesignsystem.com/ crossed my mind but only if you don't have the time to cook up something better :)

**Comment by ilfrich** [comment]
Carbon Design looks just as heavyweight as Bootstrap with a bunch of complex elements supported. We could go with something very basic (native CSS only), which might make it easier for any dev generating an app template to customise and extend it.

Also it allows the dev to add any front-end framework s/he wants and it makes it more lightweight.

**Comment by experienceplay** [comment]
Hi Guys, From a design point of view carbon is good. It would be nice to use it as it links the IBM design framework. However, I wonder how heavy its in terms of performance, and also, the majority of users will use what is generated from composer (regardless of framework or light css) as an starting to point to customize (remove the framework of change it). So we probably need to weight these two views to come up with an approach?

**Comment by jt-nti** [comment]
@ilfrich @experienceplay @winslet could be worth getting everyone who's interested together on one of the upcoming community calls?

**Comment by winslet** [comment]
@jt-nti big fan of having a conversation on a community call. @experienceplay & James I would like to keep away from any IBM specific design language (we're open source - lets try and keep it that way) @ilfrich I completely agree with keeping it as basic as possible - as long as everything is properly commented and named it should be easy enough to swap out as you say. 

**My suggestion would be we use the community call on Thursday 28th (2 weeks today)** to discuss this. Information on joining it can be found here: https://github.com/hyperledger/composer/wiki

How would everyone feel about this? (too far away?)

**Comment by experienceplay** [comment]
I sense that we are inclining to keep the design open source, as @winslet mentioned (we're open source - lets try and keep it that way). May I propose we do a couple of designs and get people to vote?. I had mentioned to @ilfrich that designing for a complex table will be a good starting point, so we can then easily scale down. And maybe we could consider new features in the designs, such as bash actions on a list (select multiple list items to delete). 

If we are happy with this, we would need to agree on a complex table so we can design with that data in mind.

Alternatively, if we prefer the call, its ok too.

**Comment by ilfrich** [comment]
@winslet, @jt-nti, @experienceplay I think an important open question is about the look and feel. I think the trick is to find a good tradeoff between a simple design (means it's easier to adjust) and a good look (out-of-the-box should impress).

I think it would be good to come up with some mocks of what the UI should look like (basic style) or some examples of other products with simple, but good looking designs from where we can draw ideas.

My preference would be some metallic look with plenty of space in the overall design, but that means areas with high information density are problematic (e.g table view).

... oh and layout is another one...

**Comment by ilfrich** [comment]
This is a first proposal for a layout and look'n'feel. The width of the mocks is smaller than a usual screen, so items will be further distributed (more horizontal spacing).

![image](https://user-images.githubusercontent.com/4035411/30575443-2290ab54-9d44-11e7-84e6-c0fa6154e6f3.png)

![image](https://user-images.githubusercontent.com/4035411/30575283-0a83c6a0-9d43-11e7-9ba6-223d7733da50.png)

- The placeholders are meant to provide extension points (empty components).
- In case anyone wonders, the search functionality is supposed to just do a simple primary key search.
- I would suggest for the list view to only show the first `n` columns of the data model. This should allow users to shift properties/attributes of larger models up and down and make them visible in the list view. All attributes can be shown on the detail page or when editing the asset. I would also prefer to get rid of the new/edit modal, but rather use separate routes for this (keeps the CSS lightweight without using a UI kit such as Bootstrap).

Oh and important question: **Is responsiveness a priority?**

**Comment by ilfrich** [comment]
@winslet, @jt-nti, @sstone1 some other question just became relevant: **Angular or React** - the previously existing license issue appears to be resolved: https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html#mit-licensed

**Comment by sstone1** [comment]
@ilfrich both, I am hoping that now the license issue is resolved somebody will contribute a React generator which will sit alongside the Angular generator 😉 

Both would of course need the same look 'n feel.

**Comment by sstone1** [comment]
Replaced by CIP #3136.
