### ISSUE TITLE
Update the generator form generation

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#529]

**Comment by EdMoffatt** [comment]
Could we get some more description on this one please @caroline-church ?  Not sure where to start on it at the moment :)

**Comment by caroline-church** [comment]
I think this is to update how the forms are generated by the generator. I'm not sure this needs any design. I'm probably wrong though about what this. @sstone1 am i right about what this was?

**Comment by sstone1** [comment]
@caroline-church you raised it! 😛 
My only guess is that this covers using the same form generation code in the playground and the generator. Since we can't answer the why how about we just close it off and re-open when we remember 😄
