### ISSUE TITLE
Composer Playground should use one abstract modal component

### ISSUE THREAD

**Issue by Jakeeyturner** [hyperledger/composer#541]
## Context
The Composer Playground should use one modal component. At the moment we have a welcome and version-check component.

These components could be simplified and merged into one component.

## Expected Behavior
Should have one component which can be used to create, show and hide modals. We should be able to pass HTML into the modal header, body and footer.

## Actual Behavior
We have separate modal components all with the same purpose

## Possible Fix
Create one component for handling modals

## Your Environment

**Comment by sstone1** [comment]
@caroline-church can we either get this done and closed soon or just forget about it? No point dragging around tech debt for a long time.
