### ISSUE TITLE
As a user, I can perform complex queries against resources in a business network

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#543]
An end user should be able to define and execute content-based queries over the assets and participants and the Historian in a business network.

Examples
- find all red cars
- find all cars owned by `dan`
- find all vehicle owners that live in the `UK`

Queries also need to be exposed over REST using the `composer-rest-server`, so they can be easily used by application developers.

Technically this story is predicated on the HLF v1 support for storing the world-state in CouchDB, along with the CouchDB query language.

This epic will be delivered in several phases:

1. PHASE 1: Allow the end user to write native CouchDB queries and to associate them with logical names, and execute the queries using a logical name
2. PHASE 2: Define a query language expressed in terms of the Composer model, which compiles to CouchDB.

Only Phase 1 is in scope for this epic.

## Design Ideas

To model the queries they should be placed into a file `queries.txt` (or similar) in the business network. The file maps from a logical name for the query to a CouchDB query string.

Example:

```
findPersonByAndGroup = function(doc) { 
  if (doc.person_id && doc.group_id) { 
    emit([doc.person_id, doc.group_id], {"name":doc.name,"department":doc.department});
  }
} 
```

We then need to supply a runtime JS API to execute a query. The JS API will be mapped to underlying Go code to execute the query, passing through the query string to CouchDB.

```
/**
 * Sample transaction processor function.
 */
function onPostTransaction(postTransaction) {
    var results = query('findPersonByAndGroup', [postTransaction.person.id, postTransaction.person.groupId]);
   // do something with results
}
```

The result of running a query should be an array of JS Objects, where each JS Object can be passed to the Serializer for the business network to be rehydrated to a valid Resource.

## REST API

The `composer-rest-server` should discover the queries for a business network via a QueryManager API (defined in composer-common). Each query gets generated as a GET route.

## ACL

The results of executing a query need to be filtered using the Access Control Manager - to ensure that the current participant has READ access to the asset in question.

### Complete:
~~#820 As a user, I want to query a world-state in CouchDB with JS API via Composer~~
~~#994 As a user I want to perform a rich query with HyperLedger Fabric V1~~
~~#994 As a user I want to apply access control to my return results.~~
~~#1185 As a QA I want to skip some components for cucumber tests to pass the unit test 
coverage~~
~~#1199 As a user I want to scrap all vehicles by colours for the vehicle life cycle demo~~

Phase 2 Stories:
~~#1323 As a user, I can add and package query files into a business network definition~~
~~#921 As a user, I want to perform complex queries when using the REST APIs~~
~~#1010 As a user, I want to perform complex queries when using the embedded runtime~~
~~#1328 As a user, I want to perform complex queries when using the web runtime~~
~~#1331 As a user, I can perform complex queries when using the runtime APIs~~
~~#1234 As a user, I can define queries using a domain specific language~~
~~#1235 As a contributor, I can compile Composer queries to the CouchDB Mango query language~~
~~#1330 As a user, I can perform complex queries when using the Node.js client APIs~~
~~#1323 As a user, I can add and package query files into a business network definition~~
~~#1332 As a user, I can work on query files in the playground~~
~~#1329 As a user, I want my access control rules applied to complex queries~~

### Pending:
#1015 As a user, I can work with large numbers of resources in the playground using pagination  -- playground story but is blocked by Fabric LIMIT/SKIP support.
#1011 As a user, I can run queries on resources in the playground using search/filtering tools -- Playground story
#1031 As a contributor, I want automated scenario testing to ensure the reliability of complex queries  -- also blocked by Fabric LIMIT/SKIP support. 

## References

http://guide.couchdb.org/draft/cookbook.html
http://guide.couchdb.org/draft/views.html

**Comment by xufengli** [comment]
have had a discussion with David today, he will send me info on how to set up fabric V1 on linux. I will set up this on my VM.

**Comment by xufengli** [comment]
Based on a discussion with Dan and Simon today, this story can be broken into below tasks:
1. Install and config hyper ledger V1 to enable CouchDB
2. Found out the types of query with Fabric team
3. Test some rich queries using CouchDB query language
4. How to expose queries through APIs/Models etc ...
    -- REST
    -- JS API for client
    -- JS API for Transaction Platform(TP)  functions
5. Security and ACL  -- this needs to be consistent with the business network's security and ACL's behavior, eg a participant should only query values from it's own asset.  
6. We need to set up system tests against both LevelDB and CouchDB in V1.

The output of this investigation is to be able to perform a simple rich query with CouchDB
eg. a farmer can query all animals in the fields belong to this farmer.

**Comment by caroline-church** [comment]
@fenglianxu can you create issues for the tasks you identified for this please?

**Comment by fenglianxu** [comment]
@caroline-church I have just started to look at this one due to a delay for getting started for V1 story. It will require couple of weeks to get this clear.

**Comment by fenglianxu** [comment]
@EdProsser We need to have a documentation on how to use rich query to resources from the world state data in couchDB.

**Comment by dselman** [comment]
I believe this is now complete (PHASE 2). @fenglianxu can you please update the status and close items as appropriate?

**Comment by fenglianxu** [comment]
As all the features in query phase 2 have been finished now, I close this epic.
