### ISSUE TITLE
As a user can view and download a UML diagram for a business network and model

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#56]
From within the Composer UI the end user can generate the UML diagram image from the business network, or from a model file.

**Comment by winslet** [comment]
Could we scope and work out where this should go in terms of priority? Thinking backlog?

**Comment by winslet** [comment]
@dselman thoughts on whether we would like an open issue on this? We agreed it is something we would like to do but this is dramatically out of date and we can certainly take a look in the future.

**Comment by sstone1** [comment]
Not an issue right now, closing until it resurfaces.
