### ISSUE TITLE
As a user I can easily test my ACL logic

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#57]
Support the enforcement of ACL logic when running in the embedded and web runtimes.

**Comment by bndzanan** [comment]
How can I easily test my ACL logic ?

**Comment by EdMoffatt** [comment]
Testing current build, this is now working.  Steps to test ACL:

e.g. to test that an EvilParticipant cannot update a sampleAsset...

1. Create the ACL rule, following the documentation on the Hyperledger Composer website.  In this case, it'd look something like:

rule preventEvil {
    description: "Stop evil participants from doing stuff"
    participant: "org.acme.sample.EvilParticipant"
    operation: UPDATE
    resource: "org.acme.sample"
    action: DENY
}

2. Create an instance of an EvilParticipant over on the Test tab

3. Issue that EvilParticipant an ID and add it to your wallet (click the "person icon top right to access the IDs screen)

4. Switch to that participant (at time of writing, a known defect means you must then refresh your browser to have it take effect

5. Try to update an asset e.g. by submitting a SampleTransaction, and see that an error is returned in the modal

**Comment by fvllam** [comment]
Is there anyway to test the ACL rules with unit tests?  Ie. without Fabric?

**Comment by Ambros94** [comment]
I think that it would be important to test ACL rules with the same runtime that we use during unit tests. It would speed up the development process and improve code quality.
