### ISSUE TITLE
As a business network developer would like to restrict direct CRUD access to an asset, instead asset manipulations can only take place through transactions

### ISSUE THREAD

**Issue by bonen** [hyperledger/composer#575]
For the problem I work on there is a lot of business logic that describes how assets can be manipulated (CRUD). I capture the business logic in transaction definitions. 

However that doesn't work though as participants can omit the business logic by directly manipulating assets. 

Whats 'problematic' is that it's not possible to capture the same business logic within ACL conditions (ACL expressions are too limited). 

## Context
In general, to me, it would make sense if (all) asset manipulations have to go through transactions (having a transaction ledger containing all historic manipulations fits the blockchain paradigm).

**Comment by sstone1** [comment]
I will fix this by extending the ACL language with an optional transaction specification:

```
rule R6 {
    description: "Drivers can do something in a org.acme.Transaction transaction"
    participant: "ANY"
    operation: ALL
    resource: "org.acme.Car"
    transaction: "org.acme.Transaction"
    action: ALLOW
}
```

If a transaction type is specified, then the action must be running within a scope of a transaction.
That transaction must be an instance of the specified transaction type.
CRUD actions do not run within the scope of a transaction, so by specifying any transaction type, the access controls will not be applicable to CRUD actions.

The ACL language also allows you to bind the transaction to a JavaScript variable for use in complex JavaScript conditions:

```
rule R7 {
    description: "Regulators can do something in a org.acme.Transaction transaction"
    participant: "ANY"
    operation: ALL
    resource: "org.acme.Car"
    transaction(tx): "org.acme.Transaction"
    condition: (tx.asset.colour === 'blue')
    action: ALLOW
}
```

**Comment by dselman** [comment]
Implemented.
