### ISSUE TITLE
Auto update the community call dates on the homepage

### ISSUE THREAD

**Issue by winslet** [hyperledger/composer#582]
## Context

We have a date on the homepage which advertises the next community call - it would be great if this could auto update based on a calendar event or some other magical way. 

![image](https://cloud.githubusercontent.com/assets/13980028/24447348/8ab1c462-1468-11e7-9a08-4843072e3c09.png)

## Expected Behavior

The date on the homepage should always be update with the next call.

## Actual Behavior

It gets outdated until we make a pull request and a build cut.

@mbwhite would you be interested?

**Comment by mbwhite** [comment]
Certainly -  I have a plan here!

**Comment by mbwhite** [comment]
Going to close this as the home page is now a generic statement with details in the wiki. 

1) Google calendar is the most obvious choice for holding a shared calendar. There is a REST API for it, but it's a bit hidden away, and not too easy to use
2) The other calendar services are very integrated into their own bigger structures, eg, MS Office
3) Couldn't really find a truly open calendar service.

Tempted to create a Composer based calendar service... but not quite got enough free time in the day!
