### ISSUE TITLE
Unhelpful error from composer-rest-server when fabric network isn't running

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#593]
I accidentally ran `composer-rest-server` without a fabric network running and got an unhandled error event.

## Context

I was following the tutorials however I restarted my machine after the quickstart so the fabric network wasn't running when I reached [How Generate a REST API Server for a Business Network](https://fabric-composer.github.io/applications/rest-api-server.html). (It would be useful to have a reminder on that page to check everything is running before proceeding, perhaps using `docker ps`?)

## Expected Behavior

An error explaining why `composer-rest-server` failed.

## Actual Behavior

```
Discovering types from business network definition ...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error
    at ClientDuplexStream._emitStatusIfDone (/home/ubuntu/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:189:19)
    at ClientDuplexStream._readsDone (/home/ubuntu/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:158:8)
    at readCallback (/home/ubuntu/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:217:12)
```

## Possible Fix

- Add a note to the top of the _How Generate a REST API Server for a Business Network_ page. For example, from one of the other topics...

> Before you follow these instructions, make sure you've completed the Quickstart! After the end of the Quickstart there will be a local Hyperledger Fabric instance running and a deployed business network.

- Update `composer-rest-server` to handle error and show an appropriate message.

## Steps to Reproduce

1. Stop HLF if it is already running, `npm run stopHLF`
2. Attempt to start the rest server, `composer-rest-server`

## Context

Trying to gain familiarity with the composer project

## Your Environment

* Operating System and version (desktop or mobile): Ubuntu Linux 16.04 LTS

**Comment by 14gracel** [comment]
This error cannot be caught as the Fabric node sdk deals with the error

**Comment by caroline-church** [comment]
@sstone1 Can this issue be fixed or is it right that we can't catch the error. If we can't catch the error can we get fabric to fix it?

**Comment by sstone1** [comment]
We can't fix the error; the Fabric team are working on this already. Closing.

**Comment by jt-nti** [comment]
@sstone1 @EdProsser what about a doc fix?

**Comment by EdProsser** [comment]
I can add stuff to the relevant pre-reqs which might mitigate, but documentation can only steer people away from the problem, rather than solving it.
