### ISSUE TITLE
Ensure that all entry points to Composer link to the home page

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#599]
## Context

With the number of resources such as Github/multiple NPM modules/Docker Hub there are multiple entry points to Composer.  These need to be linked to the main source - to avoid any misunderstandings of the scope of product. 

## Expected Behavior

Ensure a simple link is included with some information about the environment and context Composer should run in .. eg node.js Ubuntu/MacOS for HyperLedger fabric. 

## Actual Behavior
Possibly confusion over OS support

## Possible Fix

**npmjs**:
There are 38 npm packages recorded.   A user could get to any of these first
https://www.npmjs.com/~fabric-composer-admin

**dockerhub**
https://hub.docker.com/u/fabriccomposer/
The 3 docker images have some good docs

**github**
Any of the repos linked from https://github.com/fabric-composer

**Comment by dselman** [comment]
Please list all the places to fix so we can make this actionable.

**Comment by mbwhite** [comment]
Having checked over this, I'm not seeing obvious omissions.  Closing this, if any more are seen can be sorted on case-by-case basis.
