### ISSUE TITLE
As a user I should get good error messages for issues in model files

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#60]
Areas to improve on:
- [ ] Globalization of error messages
- [x] Associate a file name with a ModelFile and report the file name associated with an error
- [x] Referential integrity errors should include source line information
- [ ] Detect more semantic errors such as transactions that extend participants etc (see TODOs in code)
- [ ] Add more unit tests for error detection

**Comment by pastadin** [comment]
When issued happen with the ACL file it doesn't say it's permissions.acl that is causing it.

**Comment by EdMoffatt** [comment]
Shifting this off of Playback 3 Milestone - will put it on Playback 4 for now

**Comment by sstone1** [comment]
Issue is not actionable, raise specific issues as incomprehensible errors are found.
