### ISSUE TITLE
As a user, I need to add non-optional fields to asset definitions for which existing assets already exist

### ISSUE THREAD

**Issue by samjsmith** [hyperledger/composer#601]
## Steps to Reproduce

1. Open a clean playground (with default model)
2. Switch to Test tab
3. Create a  new participant
4. Switch to Define tab
5. Add `o String email` to `Participant` definition
6. Click `Update` button to deploy BN. 
7. Switch to Test tab.

Observe error:
![image](https://cloud.githubusercontent.com/assets/16335033/24602739/162b234e-1856-11e7-8350-7f6f0403d684.png)

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Context

Just trying to update an existing model

## Your Environment

* Version used: 0.5.5
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome/FF
* Operating System and version (desktop or mobile): Mac desktop Sierra
* Link to your project:

**Comment by samjsmith** [comment]
Chatting to @sstone1 on this, it is desirable behaviour that the objects become invalid when the model is updated and the new property/ies have not been marked as `optional` in the model file.
However, if this happens then the UI will not let you view any invalid objects that you have.  So you can still create a new asset or participant but the Plyaground UI will not then allow you to view/edit those instances.

The UI is making a simple `getAll()` call on the appropriate registry in `composer-client` and it is this that is throwing the error.

So I'd propose adding an optional `options` object on the composer-client API for `getAll` which allows you to specify that invalid objects should be returned, marked as being invalid of the form:
```
{
    $class: 'org.acme.sample.SampleParticipant'
    id: '123456'
    status: 'invalid'
}
```

Using this option the UI could distinguish between instances that are valid/invalid wrt the model that's deployed.

**Comment by dselman** [comment]
Before embarking on this approach I think we should warm people when they are making schema incompatible changes to the model and have instances in the registry.

**Comment by samjsmith** [comment]
I agree, but this could be quite time consuming if the deploy process has to get all existing instances and validate them against the updated model couldn't it?  (It might be a lot of code too?!?)

My thoughts are that there are a couple of scenarios here:

1. you're in Development/Test and changing your model in the Playground and don't really care whether your changes make existing objects invalid. In this case, perhaps the 'invalid' solution proposed above would suffice for now?
2. you're in QA/Prod and definitely don't want to be making model changes that will break existing instances (or even transaction capabilities that rely on the model definitions).  That's a big feature though and worth validating with customers first so I'll mention @EdMoffatt and @winslet here to get their input on that. It's also something of an architectural decision as to whether twere best implemented in the fabric or the fabric-composer layers.

Ideally, if you've only added non-optional fields then we'd realise that and not have to perform the validation.  And, I'm sure there are other cases where the model change doesn't affect existing instances e.g. removing a required property or relationship might not necessarily invalidate existing objects on the blockchain.

**Comment by dselman** [comment]
In theory we don't need to look at instances to know whether they are incompatible -- we can just compare two models to determine whether they are binary compatible.

**Comment by EdMoffatt** [comment]
I think a summary of how this will affect the Playground UI is:

- Playground should warn the user if deploying the Business Network Definition they have in their editor will cause incompatibilities with historic assets
- This should be synced with work on #902 - which will introduce the ability to deploy multiple networks to the same connection profile.  As such, we may only want to warn on Deploy (because that's when we'll know where it's going and whether a clash will exist!) rather than, say, below the editor where code feedback is given.  I'm imagining a confirmation to say "this will have this effect - are you sure you want to do that?"
- Registries in Playground should also be able to cope with there being "invalid" objects in there, and we should decide how we will inform the user that some of their objects are invalid, and what they will see when they look in the Registry

**Comment by sstone1** [comment]
Closing; we're not tackling this any time soon and it's a massive piece of work.

**Comment by sstone1** [comment]
We have docs for model evolution that cover these scenarios.
