### ISSUE TITLE
composer generator create is in the cli but no documentation exists

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#608]
Came across composer generator command and it supports 2 options
- create
- tests

There isn't any documentation for the create option and the documentation for tests could do with a bit more detail.

**Comment by mbwhite** [comment]
FYI I'm added some docs for the create command. 

I've looked at the tests command and I'm of the view that this now doesn't add much value  - it did a while ago. @sstone1 did mention Cucumber related to testing business definitions.

**Comment by mbwhite** [comment]
I've pushed some updates to this
