### ISSUE TITLE
As a user I can run the getting started sample on HLF v1

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#611]
Port or clone the Getting Started sample to HL v1.

## Context

As we support both HL v0.6 and HL v1.0. The sample application scripts no longer work with HL v1.0.
This story includes:

1.  a new version of Sample application project with correct scripts and profile and create and join channel scripts etc
2. Instructions on how to set up environment to run sample applications on HL V1.0.

**Comment by EdMoffatt** [comment]
As part of "GitHub cleanup", adding the Playback 4 Milestone to this one.

Not sure whether it's one that should be converted into an Epic and then split out - what do you think, @fenglianxu ?  Is this a single issue worth of work, or would you be able to split it into smaller tasks and share around the team?

**Comment by markcastle3** [comment]
@EdMoffatt epic I think and then issues.

**Comment by EdMoffatt** [comment]
#666 and #667 raised as issues under this epic - this one can be closed once @14gracel and @mahoney1 close off those issues!

**Comment by markcastle3** [comment]
Speaking to @sstone1  this issue can be closed with a follow on story raised for phase 2 work.
