### ISSUE TITLE
As a user, I want to be able to import all types from another namespace in one line of code

### ISSUE THREAD

**Issue by rodders1991** [hyperledger/composer#612]
At the moment, there seems to be no shortcut of importing all types from a namespace. For example, if `namespace biz.a` wants all assets from `namespace biz.b` containing assets Car1 , Car2 and Car3 for example, you will need to provide the following lines in the model file for `namespace biz.a`:

`import biz.b.Car1`
`import biz.b.Car2`
`import biz.b.Car3`

To save the amount of code, as a user, I would like to be able to import all assets in a single line, for example:

`import biz.b.*`

Where * indicates all types.

**Comment by sstone1** [comment]
@rodders1991 this has been implemented and should be available in the next release. You will be able to use the syntax `import biz.b.*`.
