### ISSUE TITLE
Broken Links in Docs

### ISSUE THREAD

**Issue by sumanair** [hyperledger/composer#614]
minor observation. Thought to bring it to your notice. Some internal links in the docs are broken… These are the ones I noticed - In the page https://fabric-composer.github.io/tutorials/getting-started-cmd-line.html, the links at the bottom need to be updated.

https://fabric-composer.github.io/tutorials/getting-started-coding-bnd.html - > https://fabric-composer.github.io/business-network/businessnetwork.html

The following links can probably be replaced with a link to ‘Writing applications’ or corresponding REST and node.js links under the same.
https://fabric-composer.github.io/tutorials/getting-started-rest-api.html
https://fabric-composer.github.io/tutorials/getting-started-nodejs-app.html

**Comment by dselman** [comment]
@EdProsser can you please run a link checker over the docs and fix any broken links. The W3 link checker is here: https://validator.w3.org/checklink
