### ISSUE TITLE
As a user, I want to deploy Composer to Hyperledger Fabric v1.0

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#62]
This work includes:

- [x] Developing a new HLF v1.0 runtime container `composer-runtime-hlfv1` that ports the existing Go chain-code code from the HLF v0.6 APIs to the new v1.0 APIs.
- [x] Developing a new HLF v1.0 connector `composer-connector-hlfv1` that ports the existing JavaScript connector code from the `hfc` client SDK to the `fabric-client` & `fabric-ca-client` client SDKs.
- [x] Defining a new HLF v1.0 connection profile that can be used with the HLF v1.0 connector.
- [x] Modifying the common runtime code `composer-runtime` to cope with the dropping of Read Your Own Writes support in HLF v1.0.
- [x] Adding the new HLF v1.0 connector as a dependency for the `composer-admin`, `composer-client`, and `composer-connector-server` modules so it is automatically installed.
- [x] Porting the system tests so that they run on HLF v0.6 and v1.0 - once that is complete, we can discuss dropping HLF v0.6 support.
- [x] Updating Composer Playground to support the creation of HLF v1.0 connection profiles.

**Comment by davidkel** [comment]
Summary of what is left to do for the runtime

- [ ] Add TLS support
- [ ] define an automated system test environment for both the alpha release and daily drops (may not be possible to do both)
- [ ] Support the list option in the connector

**Comment by davidkel** [comment]
# Logging
Looks like we are going to have to manage our own logging inside our chaincode so need to detect an environment variable to control logging, plus would be good to have a request to dynamically change the logging levels in the chaincode

**Comment by davidkel** [comment]
I've split this epic out into several issues here
#677 
#676 
#675 
#674 
#673 
#672 
#671 
#670 
#669

**Comment by dselman** [comment]
Can this be closed and follow on issues created please.

**Comment by sstone1** [comment]
This work is done for the most part, all remaining work should be tracked by new issues.
