### ISSUE TITLE
As a contributor I manage code using Hyperledger infrastructure

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#620]
Code migration to go along with Fabric Composer's acceptance as a Hyperledger project!

**Comment by EdMoffatt** [comment]
This one needs lots more detail.  It feels like there are probably multiple tasks under it though, so I'm going to convert it to an epic, and then somebody with more knowledge of what's actually required than me should come create Issues to break it down so that people can start working on it, please ;)

**Comment by mbwhite** [comment]
Areas that need update based on name change *Fabric Composer* -> *Hyperledger Composer*

- Twitter id is fabric_composer
- StackOverflow tag - need to create synonym `hyperledger-composer`
  - simple to do I've a contact in Hursley who can do this
- NPM 
  - change the name of the administrator
  - change the name of the Yeoman module
- Vanity URL
  - hyperledger-composer.org to replace fabric-composer.org
- SEO - how to manage a product name change?

**Comment by markcastle3** [comment]
@sstone1 could you break this down into smaller issues

**Comment by markcastle3** [comment]
@sstone1 how is this progressing?

**Comment by sstone1** [comment]
We have been making great progress with this:
- GitHub repositories moved
- Documentation (GitHub Pages) moved
- Travis CI builds moved
- npm publishing moved
- Docker Hub publishing moved
- Rebranding complete

Work remaining:
- Need to clean up GitHub repository tags and descriptions
- CLA/DCO signing enforcement (CLAHub?)
- Playground hosting and publishing

**Comment by harrika1982** [comment]
Is there a separate issue for re-creating the IBM github that pulls from the open source for any of the IBM specific work?
