### ISSUE TITLE
As a user I no longer have access to Composer-UI

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#621]
Composer-UI is the old version of Composer-Playground, but is currently still used in the run-me-locally Docker container, because the new Playground UI does not support all of the same functionality yet.

This therefore requires both #139 and #533 to be completed so that Composer-Playground can do everything that Composer-UI currently does.

There will then be additional tasks to achieve this Epic, which should be broken out as issues.

**Comment by EdMoffatt** [comment]
Updated the description.  This one needs breaking into issues.  Once we have #139 and #533 closed, what else do we need to do to retire Composer-UI and replace it with Composer-Playground?

**Comment by EdMoffatt** [comment]
Oh, and I'm gonna un-assign @sstone1 again because he's on holiday and shouldn't be working ;)  Plus if someone comes in and sees it as un-assigned, they may pick it up and be able to help by splitting it into Issues!

**Comment by sstone1** [comment]
@EdMoffatt I assigned this one so I could have the pleasure of deleting all of the old UI code; I still want that pleasure 😉

**Comment by markcastle3** [comment]
@sstone1 this looks like its all done, can we close this ?

**Comment by sstone1** [comment]
:+1:
