### ISSUE TITLE
As an end user I can create assets, participants and transactions using a webform

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#623]
When the user clicks "Create Asset" or "Create Participant" or "Submit Transaction" in the Playground, we want to offer the user a generated form to fill out wherever possible.

The behaviour should be:

1) If it's possible to generate a form, show the user both a form and an editable text field, and allow them to either fill the form or the box of JSON.

1a) Handle the situation where one of the 2 sections (form or JSON) has been placed into a broken state e.g. if there is an error in the JSON, fade out and disable the form until the JSON errors are fixed.

2) In cases where the object is too complex to generate a form for, display a just-JSON version of the modal (more similar to the current behaviour)

**Comment by markcastle3** [comment]
@EdMoffatt do we need to review/add the design for this ?

**Comment by EdMoffatt** [comment]
Yup, we sure do @markcastle3 - I'll assign to myself to get that sorted

**Comment by winslet** [comment]
Hifi's from back in the day which we believe to still be relevant. There will be edge cases we will have to work around to fix for all use cases, but testing will be required to be sure of these.

### Example of participant view with text entry fields.

This view will be different depending on the form fields found in the model file. But as an example:

![fabric composer playground define 2 copy 64](https://cloud.githubusercontent.com/assets/13980028/25751679/bd76cd86-31ad-11e7-98f7-9c259d1b44b9.png)

### Example of when the content is too complex to split out the fields.

Not too sure at which point we say things are "too complex" but this can be discussed.

![fabric composer playground define 2 copy 66](https://cloud.githubusercontent.com/assets/13980028/25751728/ddad8c3e-31ad-11e7-8fa9-078a56ac3a90.png)

**Marketch:** 
[Playground_Simple_View_SW_2.zip](https://github.com/hyperledger/composer/files/979510/Playground_Simple_View_SW_2.zip)

Any questions please let me know - I think when implementing this we will need to have further discussion.

**Comment by EdMoffatt** [comment]
Part of this is "In cases where the object is too complex to generate a form for"...  @dselman I seem to remember that you had a good explanation of why something might be "too complex".  What should we be looking for to know that something is "too complex" to generate a form for?

**Comment by Jakeeyturner** [comment]
I've started the code and committed it here - https://github.com/Jakeeyturner/fabric-composer/tree/623-webform-creation
Speaking to @dselman a while ago, this code might want to be completely re-written and changed to use a visitor/pattern approach.

**Comment by EdMoffatt** [comment]
Popping this one back onto the Backlog, as it's not a P1, and nobody's actively working on it right now - oo, I'll add the P2 tag too.

**Comment by sstone1** [comment]
As far as I know, nobody is working on this at the moment or planning to work on it, so closing. 
If somebody wishes to work on this in the future, then please reopen this issue or open a new issue.
