### ISSUE TITLE
As a user I can use Playground to save a business network definition to GitHub

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#624]
## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by sstone1** [comment]
Closing as we're not going to do this anytime soon.
