### ISSUE TITLE
Missing API to manipulate Composer data structure from/to registries

### ISSUE THREAD

**Issue by stephane-mery** [hyperledger/composer#643]
## Context

Writing JavaScript transaction callback might require manipulating JavaScript objects that need to be hydrated from resources stored in Fabric Composer registries. 
Objects manipulated by Fabric Composer need to have Relationship objects to materialize relations whereas pure JS object might have direct references to other JS objects. 
One might need more APIs to transform JS objects to data structure that can be persisted in registries and vice versa.

## Expected Behavior

Fabric Composer API provides classes like Serializer with APIs like fromJSON / toJSON that are designed to do this data manipulation. However, there is no way to instantiate a serializer in the scripts interpreted by the chaincode.

## Possible Fix

Expose a getSerializer() API at the same level as getFactory() or getAssetRegistry() 

## Existing issues
- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Context

Writing complex smart contracts that require complex data structures

## Your Environment

* Version used: Playground 0.5.9
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome  56.0.2924.87
* Operating System and version (desktop or mobile): desktop Windows 7
* Link to your project:

**Comment by dselman** [comment]
This was added in 0.7.3.
