### ISSUE TITLE
Scrollbar fixes on Asset/Participant/Transaction modals

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#652]
When creating an Asset or a Participant, if you make the input box wide or tall enough to get scrollbars...

1. You get 2 vertical scrollbars:

![image](https://cloud.githubusercontent.com/assets/7454304/24872404/4451bb1a-1e15-11e7-9365-caf34c1c9020.png)

(Image captured in Chrome, can also confirm it happens in Firefox, but harder to screenshot as the second scrollbar only shows up when you are scrolling).

2. Whilst the horizontal scrollbar was added as part of the UI Nitpicks issue #496 (to address 5 and 16)...  I'm not a fan of it.  I think the solution on submitting a new transaction is much more elegant (i.e. split stuff over multiple lines like this...)

<img width="684" alt="image" src="https://cloud.githubusercontent.com/assets/7454304/24872647/f9e320fe-1e15-11e7-8e75-a654b567854f.png">

I think we need a solution that means that input box is always a fixed width, regardless of whether you've typed something or not, AND generating random data also leaves it at the fixed width AND instead of a horizontal scroll, it splits any content that is too wide to show in a single line out across multiple lines (with the line numbering still clearly showing that it's part of 1 line).

FWIW, I *think* that the "changes width when you start typing" nitpick that was originally raised might have a root cause linked to the "Something's wrong" feedback message, which is shown split over 2 lines in the attached screenshot, but I could *swear* was always on one line and pushing out the size of the modal before.

So, to clarify, the fixes are:

- [ ] Make it so there's a single vertical scrollbar on Asset, Participant and Transaction creation
- [ ] Get rid of the horizontal scroll behaviour on Asset and Participant creation, making the behaviour the same as in Transaction creation.  Also, ensure that it still addresses the nitpicks about the modal and/or the input area changing size as the user types or generates random data (both should stay fixed).

**Comment by samjsmith** [comment]
Yes, the scrollbars do need to be updated on the 'Submit Transaction' modal.  It must have inherited a CSS change from #496.

Personally, for these tasks I'd prefer to have a resizable dialog but scrollbars are better than overflowing onto the next line. 

I see less of a problem when submitting parameters for a transaction (even though they might take long parms like URIs and split them over several lines).  

It's more of an issue when you're creating an Asset/Participant that has a deeper object structure that can contain long name/value pairs (or lists). When you fix the width of the dialog then things can start to look messy you obscure the users' view of the shape of the object in the editor.

That's just my 2cents and I should probably put my indentation OCD away somewhere ;)
Some user testing might help?
Let me know if you just want me to make it fixed width anyway.

**Comment by caroline-church** [comment]
done so closing
