### ISSUE TITLE
Review ID and Connection Profile behaviours for consistency

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#655]
As part of #533 , @jthub pointed out that we have inconsistency between the way IDs and Connection Profiles behave as UI components, and we don't have a solid justification for why that's needed.

As part of an effort to make more re-usable Angular components for our UI, @Tobias-Hunter is going to take a look at whether we could re-design some of the way ID and Connection Profiles work to improve the consistency.  This is also linked to another issue that I know @Jakeeyturner was working on around Connection Profiles, but I don't see that on the to-do list for the current Milestone yet, so I'll go find that and pull it in!

**Comment by Tobias-Hunter** [comment]
Initial thoughts on this, explained on the first page of the .XD File Click-Through below! 😛
Shared with @jthub the other day! 

.XD File Click-Through: https://xd.adobe.com/view/e2ae2405-2d08-4b7f-b8e3-1469f9186fbf/
.XD File Box Link: https://ibm.box.com/s/k9df73ucdn35s0yv1kzab4f4rz5i7kov

Assigning @winslet for Hi-Fi's!

**Comment by winslet** [comment]
Updates following extensive discussion with @jthub @EdMoffatt @Tobias-Hunter 

Outcome:

1. Update the header to include the name of the connection profile

_hifi_
![image](https://cloud.githubusercontent.com/assets/13980028/25189898/8602b474-2522-11e7-97ba-a1a6603362f0.png)

2. In the "Identity Registry" page, include a way of showing the current _"In Use"_ Identity

_hifi_
![image](https://cloud.githubusercontent.com/assets/13980028/25190167/524a5136-2523-11e7-9091-91d7403506dc.png)

This "in use" class is attached to the profile in the status column.
