### ISSUE TITLE
As a user I am able to deploy to a different Connection Profile than the one currently activated.

### ISSUE THREAD

**Issue by Tobias-Hunter** [hyperledger/composer#656]
Allow users to deploy to a Connection Profile other than the one currently active!

**Comment by Tobias-Hunter** [comment]
Initial thoughts on this, explained on the first page of the .XD File Click-Through below! 😛

.XD File Click-Through: https://xd.adobe.com/view/d63ffb02-0e58-4dba-ab07-005584121ef1/
.XD File Box Link: https://ibm.box.com/s/4jv9ps0h2gn0ol43n59bz2boit716jph

Assigning @winslet for Hi-Fi's!

**Comment by winslet** [comment]
Hifi's incoming...

### New link beneath the "deploy" button (previously named "update").
![fabric composer playground define 2 copy 87](https://cloud.githubusercontent.com/assets/13980028/25809445/e8c3b234-3404-11e7-9f21-2089e6db7344.png)

_when selecting this a new modal pops up_

### Connection profile select modal 
![fabric composer playground define 2 copy 88](https://cloud.githubusercontent.com/assets/13980028/25809473/fc47ee56-3404-11e7-80cf-130bd8b73f81.png)

_user can select a connection profile to do a one-time deploy to_

### Notification saying that the deploy has been successful and to which profile

![fabric composer playground define 2 copy 89](https://cloud.githubusercontent.com/assets/13980028/25809510/1a6c2028-3405-11e7-8ab9-722bd0de5099.png)


**Marketch:** 
[Connection_Profiles_FC_SW_1.zip](https://github.com/hyperledger/composer/files/983836/Connection_Profiles_FC_SW_1.zip)

Shouldnt be any new assets needed for this. Any questions please let me know!

**Comment by EdMoffatt** [comment]
Just adding a note that, as is true of quite a few issues, this will definitely be influenced by #902

**Comment by EdMoffatt** [comment]
Current direction of thought on #902 might leave this one feeling a bit odd - just mentioning this as a flag here!  Probably not a good one for someone to pick up and start working on if they're worried about the potential of their work being thrown away later ;)

**Comment by sstone1** [comment]
Closing as this work will be replaced by the work on ID cards.
