### ISSUE TITLE
As a user I can decide which model I want to import into the Playground in the splash screen!

### ISSUE THREAD

**Issue by Tobias-Hunter** [hyperledger/composer#657]
Context: The current Splash page in the UI has a weird behaviour, it is like if you open Word a document & a document has already been loaded in!

Suggested: When entering the Playground, we display the models which are available to be Imported into the Playground, some may require authentication whereas others do not! Acting like a shop window for the models which are available! (When you open Word you have the ability to select the file you want or start a new document.)

Attached a mock-up to explain my suggestion 😛

.XD File Box Link: https://ibm.box.com/s/qlcgmwrh5jldmpatef9qw4vp6njav0a2
.XD Click-through: https://xd.adobe.com/view/10a8bbf1-6f7d-4047-b44c-6aa2e30376fe/

**Comment by dselman** [comment]
I like this, but I would also like to increase the visibility of the import overall. Can we have a link in the UI to Model Marketplace / Network Marketplace or something similar? We also need to add the ability to import a model into an existing network.

**Comment by winslet** [comment]
@dselman thanks, do you know if we are able to display the names of the sample networks we have in Github _before_ the user authenticates? (eg so we could grey them out etc until you authenticate).

**Comment by winslet** [comment]
Hifi's...

#### 1. Before user has authenticated with GitHub account

![fabric composer playground define 2 copy 89](https://cloud.githubusercontent.com/assets/13980028/25005686/c74ca280-2051-11e7-8b08-6ac4c3926033.png)

#### 2. Post GitHub authentication

![fabric composer playground define 2 copy 88](https://cloud.githubusercontent.com/assets/13980028/25005658/a9cfabbc-2051-11e7-9604-8df88232e409.png)

#### Please note:

The interactions on this are quite complex, and include 2 different types of SVG. One which as animation and should be used on the right hand panel: 

![kapture 2017-04-13 at 11 52 43](https://cloud.githubusercontent.com/assets/13980028/25005736/f4a9dfd6-2051-11e7-9a0e-1de3e74cd7b4.gif)

The single SVG (without animation) should be used on the tiles. 

Selecting a sample network should fade and slide the right hand panel content across. 

Marketch: 
[Splash_Screen_FC_SW_1.zip](https://github.com/fabric-composer/fabric-composer/files/919601/Splash_Screen_FC_SW_1.zip)

Assets: TBC, finalising 2 illustrations. Please contact me for any others needed immediately.

@EdMoffatt has a couple of copy changes, which will be posted below.

**Comment by EdMoffatt** [comment]
Quick thought on @dselman 's last comment...  It sounds like we might want to have another issue along the lines of "Extend the functionality of the "Import/Replace" action in the Playground"?

This one's specifically looking at when you first access the page and get the welcome page, and at the same time it's sounding like there are some things we could explore for when the user is in the UI and wanting to adjust the model they're using.

Just leaving this thought here for now, to remind me what I was thinking when I come back to this next week!

**Comment by Tobias-Hunter** [comment]
Current thinking on the Splash page, some of the other functionality will be reflected in other issues.
.XD Click-through: https://xd.adobe.com/view/10a8bbf1-6f7d-4047-b44c-6aa2e30376fe/
Any questions, shout up! 🤘🏻

**Comment by EdMoffatt** [comment]
For now, not dealing with the issue of importing a model into an existing network, OR including other models or things.  Here's a final low-fi of this screen for @winslet to take a look at and give us the final hi-fis!

https://xd.adobe.com/view/91d68ee4-5cf4-4e73-b073-ec82a17a32c0/

Will raise a separate issue to cover the new bits of function and leave this one to just be the improvements to the existing stuff!

**Comment by Tobias-Hunter** [comment]
Low-Fi's updated with a 3rd scenario! After talking to @caroline-church 
https://xd.adobe.com/view/1deb1a98-38ce-416d-9c9f-7dfa69ed1ba1/

**Comment by Tobias-Hunter** [comment]
Hi-Fis incoming:

1st time experience - on load Splash screen:
![fabric composer playground define 2 copy 91](https://cloud.githubusercontent.com/assets/25635381/25850059/cf86bc9e-34b8-11e7-8cd3-a9745dc5ef96.png)

A user drags & drops their .bna file:
![fabric composer playground define 2 copy 93](https://cloud.githubusercontent.com/assets/25635381/25850070/d6d6e5fa-34b8-11e7-950c-3d85a96b6b4d.png)

Once dropped we display the file as a tile & provide information about the business network definition:
![fabric composer playground define 2 copy 91](https://cloud.githubusercontent.com/assets/25635381/25850090/e6e39506-34b8-11e7-9e1c-87c1bb463d78.png)

If a user selects a different tile the key-line will change & the remove button will change:
![fabric composer playground define 2 copy 94](https://cloud.githubusercontent.com/assets/25635381/25850108/f60b89b2-34b8-11e7-8e53-22deeff909f0.png)

If they remove the file, the drag & drop tile will reappear:
![fabric composer playground define 2 copy 91](https://cloud.githubusercontent.com/assets/25635381/25850131/03a53f14-34b9-11e7-92a3-2ba2a877a4b2.png)

Once they authorise with GitHub, the button will be removed & the appearance of the tiles will change:
![fabric composer playground define 2 copy 91](https://cloud.githubusercontent.com/assets/25635381/25850178/2779038a-34b9-11e7-9bc5-c8507845d3e4.png)
![fabric composer playground define 2 copy 91](https://cloud.githubusercontent.com/assets/25635381/25850183/2d002c3e-34b9-11e7-9405-ec8a4c8077e4.png)

Scenario 2: Second time entering the playground
![fabric composer playground define 2 copy 95](https://cloud.githubusercontent.com/assets/25635381/25848030/7f874144-34b0-11e7-91d2-360c53368531.png)

Scenario 3: If they are connected to a HLF instance
![fabric composer playground define 2 copy 90](https://cloud.githubusercontent.com/assets/25635381/25850231/6366cb70-34b9-11e7-94e0-599f0e54c9a9.png)
![fabric composer playground define 2 copy 95](https://cloud.githubusercontent.com/assets/25635381/25850233/65cae284-34b9-11e7-86b6-1c16bede2320.png)

Then they will get the same screen as in scenario 2! 

Marketch file: 
[Splash Screen TMH v0.1sketch.zip](https://github.com/hyperledger/composer/files/986421/Splash.Screen.TMH.v0.1sketch.zip)

All assets should be in @winslet comment apart from the Drag & Drop tile illustration, which is here: (this doesn't require an animation as it will never appear in the right hand column)
[10.svg.zip](https://github.com/hyperledger/composer/files/986423/10.svg.zip)

**Comment by Tobias-Hunter** [comment]
Assigning @sstone1 find the most appropriate person for this 😛

**Comment by sstone1** [comment]
@caroline-church @bestbeforetoday please allocate this work 😄

**Comment by winslet** [comment]
are there any update on this? @markcastle3 do we have this work planned at all?

**Comment by sstone1** [comment]
Closing as this work will be contained as part of the work on ID cards.
