### ISSUE TITLE
Example data for transactions in rest server include   {"transactionId": "string"}

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#663]
In the rest server Web UI transactions show example values which include the property transactionId. But when you specify that property in the try it out box you get an error as follows

```
{
  "error": {
    "statusCode": 422,
    "name": "ValidationError",
    "message": "The `RegisterPropertyForSale` instance is not valid. Details: `transactionId` can't be set (value: \"string99\").",
    "details": {
      "context": "RegisterPropertyForSale",
      "codes": {
        "transactionId": [
          "absence"
        ]
      },
      "messages": {
        "transactionId": [
          "can't be set"
        ]
      }
    },
    "stack": "ValidationError: The `RegisterPropertyForSale` instance is not valid. Details: `transactionId` can't be set (value: \"string99\").\n    at /home/vagrant/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/dao.js:348:12\n    at ModelConstructor.<anonymous> (/home/vagrant/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/validations.js:502:11)\n    at ModelConstructor.next (/home/vagrant/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/hooks.js:83:12)\n    at ModelConstructor.<anonymous> (/home/vagrant/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/validations.js:499:23)\n    at ModelConstructor.trigger (/home/vagrant/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/hooks.js:73:12)\n    at ModelConstructor.Validatable.isValid (/home/vagrant/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/validations.js:465:8)\n    at /home/vagrant/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/dao.js:344:9\n    at doNotify (/home/vagrant/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)\n    at doNotify (/home/vagrant/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)\n    at doNotify (/home/vagrant/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)\n    at doNotify (/home/vagrant/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)\n    at Function.ObserverMixin._notifyBaseObservers (/home/vagrant/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:122:5)\n    at Function.ObserverMixin.notifyObserversOf (/home/vagrant/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)\n    at Function.ObserverMixin._notifyBaseObservers (/home/vagrant/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)\n    at Function.ObserverMixin.notifyObserversOf (/home/vagrant/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)\n    at Function.ObserverMixin._notifyBaseObservers (/home/vagrant/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)"
  }
}
```

**Comment by sstone1** [comment]
This is a LoopBack bug and should be raised against them.
We are setting `forceId: true`:

> forceId	Boolean	true	If true, prevents clients from setting the auto-generated ID value manually.

We are also setting `generated: true` and `required: false` on the ID property.

The ID should not appear in the Swagger example for the POST operations.

**Comment by sstone1** [comment]
Raised LoopBack defect:
https://github.com/strongloop/loopback/issues/3447

**Comment by technowar** [comment]
I used `Postman` to do POST instead of LoopBack.

**Comment by himanimukne** [comment]
@technowar could you please elaborate more on that?

please provide a solution for this, the problem still persists.
even after writing
"transactionId" : false,

this is the error

{
"error": {
"statusCode": 400,
"name": "SyntaxError",
"message": "Unexpected token t in JSON at position 110",
"body": "{\n "$class": "test.AccountTransfer",\n "from": "HimaniAccount",\n "to": "AstatineAccount",\n "amount": 20,\n transactionId: false,\n "timestamp": "2018-06-01T04:33:39.539Z"\n}",
"status": 400,
"stack": "SyntaxError: Unexpected token t in JSON at position 110\n at JSON.parse ()\n at parse (/home/himani/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/body-parser/lib/types/json.js:88:17)\n at /home/himani/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/body-parser/lib/read.js:116:18\n at invokeCallback (/home/himani/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/raw-body/index.js:262:16)\n at done (/home/himani/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/raw-body/index.js:251:7)\n at IncomingMessage.onEnd (/home/himani/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/raw-body/index.js:307:7)\n at emitNone (events.js:106:13)\n at IncomingMessage.emit (events.js:208:7)\n at endReadableNT (_stream_readable.js:1064:12)\n at _combinedTickCallback (internal/process/next_tick.js:138:11)\n at process._tickCallback (internal/process/next_tick.js:180:9)"
}
}


error 422 with true

**Comment by technowar** [comment]
Have you tried removing `transactionId` and `timestamp` when submitting?

**Comment by himanimukne** [comment]
@technowar 
yes, it gives error 500 then

{
  "error": {
    "statusCode": 500,
    "name": "Error",
    "message": "Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Insufficient funds",
    "stack": "Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Insufficient funds\n    at _initializeChannel.then.then.then.then.catch (/home/himani/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:980:34)\n    at <anonymous>"
  }
}

**Comment by technowar** [comment]
Gives `500` because you have `Insufficient funds`. Have you checked the funds before transferring?

**Comment by himanimukne** [comment]
yes. the two accounts have 100 and 50. i am transferring 20 @technowar

**Comment by technowar** [comment]
That, you have to check your logic, and is not related to this issue.

**Comment by himanimukne** [comment]
the logic is getting perfectly on hyperledger composer online

**Comment by himanimukne** [comment]
@technowar

**Comment by himanimukne** [comment]
Another user on stackoverflow had encountered a similar problem. They fixed it by making their npm and node.js non-root. In my case, it is already non-root. [non-root](https://i.stack.imgur.com/0DWCv.png)
Is it possible that npm and node.js are not installed properly? I had received a few errors during its installation npm errors during installation
[npm installation errors](https://i.stack.imgur.com/RzvKv.png)

**Comment by indolia143** [comment]
I am also getting same problem even i also have installed node.js and npm woth non root..
