### ISSUE TITLE
Getting Started update for V1

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#666]
Make the updates to Getting Started as part of epic #611

**Comment by 14gracel** [comment]
Added in PR (here)[https://github.com/fabric-composer/sample-applications/pull/22]

**Comment by caroline-church** [comment]
@EdMoffatt @14gracel can this issue now be closed or is there more to do, if so what else do we need to do?

**Comment by EdMoffatt** [comment]
I don't know - the issue is pretty light on what's actually being worked ;)  I think the plan was to move things to "Done" when we're done with them, and then close them at the end of an iteration.

On this one though, looking at the referenced PR, I see it getting reverted, so I'm not sure this is done.  I'm not able to add any detail on what needs doing here - @14gracel do we still need this issue, or is it better closed off and the work tracked elsewhere?
