### ISSUE TITLE
Implement controllable logging for chaincode and runtime

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#669]
chaincode and runtime logging used to work but on release of the v1.0.0-alpha logging stopped. Currently the code has hardcoded the logging level to debug in order to re-instate logging however this should be controllable.
Ideally we don't want to use environment variables because although that is ok for development and testing on local fabrics, when it comes to production fabrics it may not be so easy to set environment variables and restart chaincode containers.

**Comment by davidkel** [comment]
- Can you pass environment variables to a chaincode container ?
- Do we want to be storing the debug level in the world state or just a memory thing ? If we don't then how do we get debug running at initialisation time ?
- Assume comms will be through the invoke or query interfaces depending on whether we store in world state or memory.

**Comment by davidkel** [comment]
More thoughts
- Environment variables don't look like they come through except the ones the peer decides are appropriate. But one of those is the shim logging level, so we can make use of that "CORE_CHAINCODE_LOGLEVEL"
- If we have a chaincode invoke command to change logging levels dynamically how would we get logging for the init process ? Not much help for an already deployed fabric runtime and we want to debug deploying a business network (do we really want to bring the peer down and back up and change an environment variable ?). This really points to the best solution being that we pass a debug flag on init, invoke and in 0.6 query calls that execute with a debug level specified (with the default being the value in the CORE_CHAINCODE_LOGLEVEL.

**Comment by sstone1** [comment]
@davidkel any updates on what the plan is for this one?

**Comment by davidkel** [comment]
@sstone1 @EdMoffatt Do either of you think that we need this capability from within playground ? Note there are 2 separate methods to setting the log level, one is at deploy time and the other is whenever you want to change it to debug runtime invoke/query ?

**Comment by davidkel** [comment]
Documentation required for this story:
composer network deploy get's a new optional parameter:
```
Options:
  --help                       Show help  [boolean]
  -v, --version                Show version number  [boolean]
  --archiveFile, -a            The business network archive file name  [string] [required]
  --connectionProfileName, -p  The connection profile name  [string]
  --enrollId, -i               The enrollment ID of the user  [string] [required]
  --logLevel, -l               the initial loglevel to set (INFO|WARNING|ERROR|DEBUG)  [string]
  --enrollSecret, -s           The enrollment secret of the user  [string]
```
this is the logLevel parameter. This will define the log level of the composer runtime when you deploy the business network.

a new command is added
```
composer network loglevel [options]

Options:
  --help                       Show help  [boolean]
  -v, --version                Show version number  [boolean]
  --businessNetworkName, -n    The business network name  [string] [required]
  --connectionProfileName, -p  The connection profile name  [string] [required]
  --logLevel, -l               the new logging level (INFO/WARNING/ERROR/DEBUG)  [string]
  --enrollId, -i               The enrollment ID of the user  [string] [required]
  --enrollSecret, -s           The enrollment secret of the user  [string]
```
All the options are standard. The specific one to this command is --logLevel. It is optional. If it isn't specified then it returns the current log level of the composer runtime, if specified it will set the log level to the specified value.
