### ISSUE TITLE
As a user, I can define and expose a set of complex queries against resources in a business network

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#67]
This is blocked by:
[#543 As a user, I can perform complex queries against resources in a business network](https://github.com/hyperledger/composer/issues/543)

Query

    Assets
    Transactions (inputs as well as side effects)
    Participants

Need to run queries from JS Functions and remote via REST.
Need a model specific query language that compiles to the backing store. We want to abstract the query language away from the backing store, but must remain pragmatic.

Need to put access control on queries.

Need to be able to control the scope of what is returned/resolved.

Be able to add queries to a CTO file. Queries are exposed as JS Functions, so they can be called from transaction processor functions. The functions are annotated with type information and @query so that they are also automatically exposed as GET methods over REST.

Query syntax is a loosely based on JPQL object-oriented query syntax:
https://openjpa.apache.org/builds/1.2.3/apache-openjpa/docs/jpa_overview_query.html

    Define query functions in CTO model file
    Call query from transaction processor function
    Expose query function as a REST GET method

Examples (from Mozart).

/**
 * Get the Animals, but do not resolve contained relationships
 * @query
 * @param {String} farmerId - the email of the farmer
 * @returns {Animal[]} - the animals that belong to the farmer
*/
function findAnimalsByOwnerId(farmerId) {
  return query('select a from Animal a where a.owner == :farmerId');
}

/**
 * Get the Animals, and resolve the location and owner relationships only
 * @query
 * @param {String} farmerId - the email of the farmer
 * @returns {Animal[]} - the animals that belong to the farmer
*/
function findAnimalsByOwnerIdWithDetails(farmerId) {
  return query('select resolve(a, a.location, a.owner) from Animal a where a.owner == :farmerId');
}

/**
 * Get the incoming animals for a farmer and do not resolve relationships
 * @query
 * @param {String} farmerId - the email of the farmer
 * @returns {Animal[]} - the animals that belong to the farmer
*/
function findIncomingAnimalsByFarmerId(farmerId) {
  return query('select b.incomingAnimals from Business b where b.owner == :farmerId');
}

**Comment by ibmamnt** [comment]
Customer need this feature as soon as possible, since they are going to put large number of assets in the production system. Say 30,000 / year.

**Comment by fenglianxu** [comment]
should this be a duplication of the #543?

**Comment by sstone1** [comment]
Closing as duplicate.
