### ISSUE TITLE
As a network starter, I can bind an initial set of identities to participants at deployment time

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#670]
Composer runtime defines that if on request for an identity, that identity is null then whoever made the request as no restrictions on them.
In HLFV1 all users are identified through the common name of the request creator certificate. That included Admin and as such if we returned admin as the identity then admin was restricted from certain capabilities. In order to accelerate working with hlfv1, the code has hard coded admin as a superuser (ie if admin, return null). 
The way forward is to register the user who deployed the business network as the superuser and return null for that user rather than be hard coded. It should also be possible to register other users as having the same capability for a business network.

**Comment by sstone1** [comment]
Removed HLFv1 as this is not specific to the HLFv1 support.
We need to bind the deployment identity (or other identity) to a participant as part of deployment, and then enforce administrative access control based on that.
We don't have administrative access control yet so we need another story to implement that 😉 
Adding architecture tag as this requires design + discussion.

**Comment by davidkel** [comment]
shouldn't this be a P1 ?

**Comment by sstone1** [comment]
This is done.
