### ISSUE TITLE
Undeploy Support

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#673]
Need to define what this means on an HLFV1 context and implement it for the command
`composer network undeploy`

**Comment by davidkel** [comment]
## assumptions
An assumption about undeploy is that if a business network is undeployed, it should be possible to redeploy it again to any peer that it had been originally deployed to.

## info about fabric docker containers for chaincode
Docker containers are started with the name as follows
<network_id>-<peer_id>-<chaincode_id>
which is also the docker image name.
The chaincode id is made up of the business network name and composer runtime version.
We have only 1 business network per container.

## When it comes to undeploy what would we like to do ?
- stop all the containers running that business network on peers
- delete the images for that particular chaincode
- delete the chaincode package stored on the peer.

## Alternatives if above not possible
- leave the containers running but effectively put the business network out of action through our runtime (I believe this is what v0.6 does)
the problems with this are
- Containers are left running
- If we want to redeploy the same business network it will likely fail due to package already installed on peer. If we ignore the install error, what would instantiate do as the container is already running ? probably fail with an error
Only option would be to somehow re-instate the business network in the container

**Comment by davidkel** [comment]
So nothing will be coming of HLF V1 to allow the stopping of chaincode containers and removing of chaincode images from peers.
Is there a way we could get all chaincode containers running a business network to terminate themselves so that we can at least bring down the chaincode containers ? it would have to be sent to all peers that you wanted to terminate the container on.

**Comment by davidkel** [comment]
Spoke to Simon, we won't try to do anything clever like stopping chaincode containers.
@EdProsser We will need to add some documentation around what undeploy means with HLF V1. All it will do is make the business network unavailable. It won't stop the chaincode containers from running and a redeploy will not re-enable the business network - in other words you can't, however if  you get a new version of composer and as such the chaincode level changes version you will be able to deploy again but it will be a completely new instance as expected.

**Comment by EdProsser** [comment]
@davidkel Are there any other technical changes which would affect the content on this page? https://hyperledger.github.io/composer/reference/composer.network.undeploy.html

**Comment by EdProsser** [comment]
Other than on HLFv1 the redeploy doesn't re-enable the network.

**Comment by davidkel** [comment]
@EdProsser Hi Ed, I have made a change to the comment, but in summary what happens is this currently in with the alpha images.
- I deployed a business network (digitalproperty-network)
- I undeployed that network
- tried to connect to it using the rest server and got
```
Connection fails: Error: Error: The business network has been undeployed
```
as expected. 
- I tried to redeploy the network (ignore the original comment about chaincode version numbers) and got
```
Error: Chaincode exists digitalproperty-network
```
The error is because the all the undeploy can do is disable the business network. We are not able to shutdown the chaincode containers nor remove the install package from the peer (in essence what it does is leave the chaincode and composer runtime running, but put the business network implementation running in that container into a unusable state). We need to ensure this is documented as it will confuse users who would expect to be able to undeploy and it would clean everything up and if they wanted to be able to redeploy again. This is a limitation of HLF V1.

**Comment by davidkel** [comment]
covered by pull request #929 
just leaves the docs now :-)

**Comment by davidkel** [comment]
@EdProsser my part on this is done Ed. If you have finished as well feel free to close this issue.

**Comment by EdProsser** [comment]
Yup, the changes we discussed went in. :)
