### ISSUE TITLE
Do we need to support new capabilities in node-sdk ?

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#676]
new capabilities are being added to node sdk so far I have seen
- verifyProposal: verify the results of a proposal sent to peer
- timeout on sendProposal
  - this is defined when you create a peer or orderer and cannot be changed on the peer once created, also if not specified then it will default to 45 seconds (or 30 secs if no config present) currently for the current level of sdk-node. Which means we must set some sort of timeout just to cope with deploy which can take more than this time. Composer has 2 timeout values of deployWaitTime and invokeWaitTime for which it will timeout if no response received (these were likely required for 0.6 due to limitations in 0.6 not providing back errors so only option was to timeout). We can continue with our own timeouts and just set the sdk timeout to be the greater of the 2 values or remove our timeout code, and just use the hfc timeout and have a single parameter in the connection profile.
- fabric-ca reenroll
  - Unsure at this time.
- chaincode upgrade
  - Yes, this would be a useful facility to have, need to create a new story and investigate.
- Simplified API for creating a user
- getUserContext synchronous call (we use the asynchronous one currently)
  - No the synchronous one doesn't retrieve from the file system, only memory
- custom endorsement policy support 
  - assume we don't want to support this as this is around HLFV1 infrastructure which isn't composers responsibility but user will have to create appropriate connection profile based on endorsement policy

Missing or unknown capabilities
- What's the story with TCerts ?

**Comment by sstone1** [comment]
This is not a piece of work, closing - please raise user stories for the work we are going to tackle (e.g. chaincode upgrade).
