### ISSUE TITLE
Not possible to use any other FileKeyStore location other than ~/.hfc-key-store

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#677]
This is an issue with the node-sdk I believe and is being tracked by
https://jira.hyperledger.org/browse/FAB-2940

**Comment by caroline-church** [comment]
@davidkel Can you track progress on this please and close when prereq fixed?

**Comment by davidkel** [comment]
@caroline-church So they have made code changes, but it also introduced breaking api changes which were not obvious how to use in order to fix the issues.  I don't believe they fixed all the issues either with that code change and I was waiting for examples on how to use the new api to test. However when they did give examples they informed me there was another JIRA being worked on that changes the API yet again and when that is done, we will need to code to the new api and see what problems exist in this area. Still waiting for them to make the code drop.
So currently tracking this JIRA as there is no point in doing anything until they complete the new API.

**Comment by markcastle3** [comment]
@davidkel is this problem still happening ?

**Comment by davidkel** [comment]
In summary, this is a problem for hlfv1-alpha1
hlfv1-alpha2 have changed the api and I have now recoded to that api and can now use other directories as well.
this however is the area that is again going to change in the node-sdk and is likely to break us but for now, the problem has been resolved in the alpha2 release.
