### ISSUE TITLE
Upgrade Angular Generator

### ISSUE THREAD

**Issue by opiepj** [hyperledger/composer#694]
# Upgrade Angular Generator

## Context

I want to upgrade the Angular Generator to use Angular 4
## Expected Behavior

The fabric composer app generator should be up to date on Angular releases with best practice patterns

## Actual Behavior

Right now the generator is only on version 2.4 

## Possible Fix

I'll do a quick update

**Comment by dselman** [comment]
Is this work now complete?

**Comment by opiepj** [comment]
@dselman Yes, was merged by @sstone1, closing repo. I'll open another issue sometime next week adding on the home page as @Jakeeyturner requested.
