### ISSUE TITLE
As a user I can edit models and networks with dependencies in Playground

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#697]
## Context
Business Networks can be dependent on models (which are themselves npm modules). We would also like models to be dependent on other modules (story #631).

In addition for some scenarios it would be useful for a business network to depend on another business network (to share common models and scripts for example).

All of these requirements/changes require rethinking how Playground imports business networks and what the expected behavior of "save" should be when inside Playground.

## Expected Behavior
- [ ] Should be able to import a business network from GitHub that has dependencies on other npm modules (models or library networks)
- [ ] Should be able to deploy the business network
- [ ] Should be able to create a business network archive from the network
- [ ] Saving the business network should persist changes back into the origin GitHub repository
- [ ] Should be able to import a model from GitHub that has dependencies on other npm modules (models)

## Actual Behavior
Importing fails with no error message.

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Context
This is required to support graphs of dependent artifacts and a marketplace of networks and models.

**Comment by dselman** [comment]
I think the net is that Playground needs to be smarter about understanding the dependencies and what can be edited based on the current context.
We will need some UX design from @EdMoffatt e.g. extend the left-nav to also list "dependencies" and make those clickable links.
We may need to materialize 3 editing contexts: editing a business network project, editing a model project, editing a library project (edited)

**Comment by sstone1** [comment]
Folding into As a user I would like to create a model and publish it for reuse by networks and other models #579.
