### ISSUE TITLE
Trying to open the import/replace modal causes the modal to only flash up

### ISSUE THREAD

**Issue by winslet** [hyperledger/composer#706]
## Context

![kapture 2017-04-20 at 9 49 15](https://cloud.githubusercontent.com/assets/13980028/25222040/2b4c7884-25af-11e7-8e6e-c0adfb4dfb8a.gif)

Selecting to open the "import/replace" modal causes the modal to only flash up instead of being able to import anything. 

**Browser:** FF & Chrome on Mac
**Console Error to go with it:** 
![image](https://cloud.githubusercontent.com/assets/13980028/25222099/5bd23796-25af-11e7-8661-4244410b0b61.png)

Have not had this happen on the production environment, only the build locally.

API logs:

``` 

> composer-playground-api@0.5.11 start /Users/[]/fabric-composer/packages/composer-playground-api
> node cli.js

PlaygroundAPI            :main()                    >
PlaygroundAPI            :createServer()            > 15699
ConnectionProfileManager :constructor()             Created a new ConnectionProfileManager {"fs":{"F_OK":0,"R_OK":4,"W_OK":2,"X_OK":1}}
PlaygroundAPI            :createServer()            Playground API started on port 15699
PlaygroundAPI            :createServer()            <
github                   :GET /api/isOAuthEnabled() >
github                   :GET /api/isOAuthEnabled() < false
github                   :GET /api/isOAuthEnabled() >
github                   :GET /api/isOAuthEnabled() < false
github                   :GET /api/isOAuthEnabled() >
github                   :GET /api/isOAuthEnabled() < false

```

## Expected Behavior

The modal should open

## Actual Behavior

The modal opens for a split second then closes

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by nklincoln** [comment]
@winslet  - if you follow the link shown in the console error, do you get taken to a page with a "API rate limit reached/exceeded" message?

**Comment by samjsmith** [comment]
I've just exceeded my rate limit and when I select the import/replace option, I get the correct error message from the Playground so I don't think that this problem is caused by that.
@winslet does it still happen for you with the latest code?

**Comment by EdMoffatt** [comment]
Quick design triage - Sam W to pull down latest code and test whether he's still seeing this

**Comment by winslet** [comment]
Seems to be working now - will close this. Invalid. 👍
