### ISSUE TITLE
As a business network developer, I can enforce system level access control 

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#722]
This work is blocked by:
#920 As a contributor, I need to model core types in a system namespace

Currently we have no system level access control; there is no control over:

- Who can update the business network definition
- Who can perform CRUD operations on registries
- Who can issue and revoke identities

We need to resolve this. I would like to see us use the same ACL syntax used for the resources (assets, participants, transactions) in a business network as for the system artefacts.

The work in #920 will enable us to use the same ACL syntax and access controller code for enforcing access control to system level resources (registries, business network definition, etc) as used for enforcing access control to user resources (assets, participants, transactions, etc.).

The work in this story requires that we:

- Model all of the system artefacts we are trying to secure in the system namespace defined by the work done in #920.
- Use the standard model manager/factory/serializer APIs to persist these system artefacts instead of using [internal JSON data formats](https://github.com/hyperledger/composer/blob/master/packages/composer-runtime/lib/registrymanager.js#L194).
- Add in hooks to call the access controller when accessing these system artefacts, similar to those used for [enforcing access control to user resources](https://github.com/hyperledger/composer/blob/master/packages/composer-runtime/lib/registry.js#L77).

The final piece of the puzzle is to define where these ACL rules live. We could just have them in the same `permissions.acl` file that is used to today to secure user resources. However, users may want to separate the "admin" (still a participant!) level access control rules from the "user" level access control rules.

We may need to consider allowing multiple ACL files with user specified names, and maybe come up with a default that is our definition of best practice, for example `system.acl` and `user.acl`.

There are runtime impacts on multiple ACL files though; we need to very clearly define the order that ACL files and ACL rules are applied when testing to see if a participant can access a resource.

**Comment by markcastle3** [comment]
@sstone1 @dselman do we need some information to help understand the work here ?

**Comment by sstone1** [comment]
Adding design tag to request thoughts on single ACL files vs multiple ACL files, and how we handle these in the playground (if at all).

**Comment by mbwhite** [comment]
Mark as unblocked as system types are now in 0.9.0; will actively start working on this now.

**Comment by mbwhite** [comment]
**Documentation** - will be edited and updated
/cc @EdProsser 

----

**Comment by mbwhite** [comment]
# Scenario 

See this repo for a sample use of the ACLs 
https://github.com/ampretia/composer-dpn-scenario

**Comment by mbwhite** [comment]
1) Sample networks updated with all access ACLs
   Networks have been version bumped for playground use
2) getting started ok - as it uses the admin id
3) @14gracel  kindly checking the vehicle lifecycle demo.
