### ISSUE TITLE
Rebrand playground to reflect Hyperledger Composer naming

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#725]
The playground needs to reflect our new name, Hyperledger Composer, now that we are officially part of Hyperledger. 

Related:
[#724 Rebrand website and documentation to reflect Hyperledger Composer naming](https://github.com/hyperledger/composer/issues/724)

This is currently **blocked** whilst I confirm the branding requirements for user interface, as opposed to the website and documentation.

I am trying to find somebody in the Hyperledger team that can review the updates once ready.

**Comment by sstone1** [comment]
@winslet I have updated the requirement from Hyperledger, can you work your design magic please?

**Comment by EdMoffatt** [comment]
Assigning this one to @Tobias-Hunter - Toby, can you please take a thorough pass through the current UI and identify anywhere that we need to change some text?  This might also be a good time to swap out the "Welcome to Playground" image which has "Fabric" written on the blocks - as an interim step before we do the "catalog" style rework there.  I know you had some ideas around that, so please come up with a set of designs for all the bits that need to change, then attach to this issue so that somebody can dev the changes :)

**Comment by Tobias-Hunter** [comment]
Does this include Samples within the Playground? 🤔

**Comment by Tobias-Hunter** [comment]
Update: Samples are covered in #729 by @nklincoln

**Comment by Tobias-Hunter** [comment]
- [ ]  Entering the playground in the header & copy:

![screen shot 2017-04-25 at 15 43 10](https://cloud.githubusercontent.com/assets/25635381/25391782/f3adadac-29ce-11e7-8913-f430cf60ab68.png)

- [ ]  Top-left header branding:

![screen shot 2017-04-25 at 15 46 46](https://cloud.githubusercontent.com/assets/25635381/25391788/f7b5aae4-29ce-11e7-9a91-0aa76a214ad1.png)

- [ ] Connection Profile page:

![screen shot 2017-04-25 at 15 47 23](https://cloud.githubusercontent.com/assets/25635381/25391795/fb4ce370-29ce-11e7-9e0d-dd1c79e711a5.png)

- [ ] Contact us on the Connection Profile page, updated to the relevant channels:

- StackOverflow is hyperledger-composer

![screen shot 2017-04-25 at 15 49 01](https://cloud.githubusercontent.com/assets/25635381/25391805/003e9f40-29cf-11e7-946e-a1cf6f362226.png)

**Comment by Tobias-Hunter** [comment]
Also, the illustration that is there says Fabric Composer. I will produce an unbranded illustration!

**Comment by Tobias-Hunter** [comment]
<img width="338" alt="sandbox tmh v0 1 2x" src="https://cloud.githubusercontent.com/assets/25635381/25618678/c4f4e428-2f3f-11e7-91c1-e26db7fc3e04.png">

**Comment by nklincoln** [comment]
closing following delivered changes
