### ISSUE TITLE
Rebrand samples to reflect Hyperledger Composer naming

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#729]
The samples needs to reflect our new name, Hyperledger Composer, now that we are officially part of Hyperledger. 

Related:
[#724 Rebrand website and documentation to reflect Hyperledger Composer naming](https://github.com/hyperledger/composer/issues/724)
[#725 Rebrand playground to reflect Hyperledger Composer naming](https://github.com/hyperledger/composer/issues/725)

The README.md files are the main problem with the samples, for example:
https://github.com/hyperledger/composer-sample-networks/blob/master/packages/carauction-network/README.md

We should take this chance to sanitise the samples looking for HL, HyperLedger, IBM, Concerto, etc.
#724 includes links to the branding and trademark guidelines from Hyperledger that we should comply with.

I am trying to find somebody in the Hyperledger team that can review the updates once ready.

**Comment by nklincoln** [comment]
Work ongoing within composer-sample-networks

**Comment by nklincoln** [comment]
Changes delivered within:
 - https://github.com/hyperledger/composer-sample-networks/pull/35
 - https://github.com/hyperledger/composer-sample-models/pull/19
