### ISSUE TITLE
Rebrand Visual Studio Code plugin to reflect Hyperledger Composer naming

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#730]
The Visual Studio Code plugin needs to reflect our new name, Hyperledger Composer, now that we are officially part of Hyperledger. 

Related:
[#724 Rebrand website and documentation to reflect Hyperledger Composer naming](https://github.com/hyperledger/composer/issues/724)

Many things need updating here:
The README.md or whatever is used for the marketplace page
Fabric Composer -> Hyperledger Composer
Tags need updating
package.json needs updating, there are lots of "bad" values in here, I think it should be using these values:

```
"name": "composer-vscode-plugin", (the existing name sucks and we should change it)
"author": "Hyperledger Composer",
"license": "Apache-2.0",
"url": "https://github.com/hyperledger/composer-vscode-plugin.git"
"displayName": "Hyperledger Composer",
"description": "Hyperledger Composer syntax highlighting, autocomplete & error checking",
"publisher": "Hyperledger Composer",
"aliases": [
          "Hyperledger-Composer",
          "Composer"
        ],
```

I am trying to find somebody in the Hyperledger team that can review the updates once ready.

**Comment by 14gracel** [comment]
PR is waiting to be merged, unsure how to test and move to market place. Will research tomorrow
