### ISSUE TITLE
Rebrand Atom plugin to reflect Hyperledger Composer naming

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#731]
The Atom plugin needs to reflect our new name, Hyperledger Composer, now that we are officially part of Hyperledger. 

Related:
[#724 Rebrand website and documentation to reflect Hyperledger Composer naming](https://github.com/hyperledger/composer/issues/724)

Many things need updating here:
The README.md or whatever is used for the marketplace page
Composer -> Hyperledger Composer
package.json needs updating, there are lots of "bad" values in here, I think it should be using these values:

```
"homepage": "https://github.com/hyperledger/composer-atom-plugin",
"url": "https://github.com/hyperledger/composer-atom-plugin.git"
"url": "https://github.com/hyperledger/composer/issues"
"license": "Apache-2.0",
```

I am trying to find somebody in the Hyperledger team that can review the updates once ready.

**Comment by 14gracel** [comment]
PR is waiting to be merged, unsure how to test and move to market place. Will research tomorrow
