### ISSUE TITLE
As a user I am able to Submit a Transaction on an individual Asset

### ISSUE THREAD

**Issue by Tobias-Hunter** [hyperledger/composer#739]
In the Test tab & creating a transaction flow: rather than submitting a transaction through the “Submit Transaction” button, on each Asset the user will be able to submit transactions that could be performed on this particular Asset & then we’d pre-fill information based upon that asset.

.XD Click-through to explain:

Transaction Flow: https://xd.adobe.com/view/e89120cc-6c9d-40f6-9ce5-25bc0f8fb224/

**Comment by Tobias-Hunter** [comment]
Rather than "Available Transactions" the copy of the button could perhaps be "Related Transactions" 😛

**Comment by EdMoffatt** [comment]
This one's in need of a hi-fi.  Assigning @winslet :)

**Comment by winslet** [comment]
Progress wise, this is where discussion has led us:

![image](https://cloud.githubusercontent.com/assets/13980028/26308248/4997918e-3ef0-11e7-8904-5b2bc37b7f48.png)

We place an icon next to the assets in the repository and allow a dropdown to appear with the actions that are possible. Im not sure if we need to consider there being some actions that can only take place on some assets but it is there for discussion. If we are happy we're ready to upload a marketch.

**Comment by Tobias-Hunter** [comment]
Displaying only transactions for that specific asset would be best. I would also like to highlight that by submitting a transaction via this method the submit transaction dialog would be pre-filled with information based on that asset!
![image](https://cloud.githubusercontent.com/assets/25635381/26308543/a1f05388-3ef1-11e7-927c-c6579c14d1de.png)

**Comment by winslet** [comment]
@EdMoffatt @Tobias-Hunter are we happy with the above visual design? I'm not 100% but im not sure spending any more time will get us any further at this stage.

**Comment by sstone1** [comment]
Closing this as it will not happen any time soon.
