### ISSUE TITLE
"Unstable" build does not pull in any CSS changes for docs & homepage

### ISSUE THREAD

**Issue by winslet** [hyperledger/composer#743]
## Context

When pushing updates to the docs and homepage, any CSS changes do not go in. HTML is updated and works but any new CSS does not.

The CSS does appear when a release cut is done, but for testing purposes we're kinda guessing.

## Expected Behavior

CSS gets updated when an unstable build happens.

## Actual Behavior

CSS does not get updated.

## Steps to Reproduce

1. Change some CSS
2. Push changes and wait for a build
3. Look at ya code / cry

**Comment by EdMoffatt** [comment]
Removing the Design tag because I don't *think* this needs any input from the design team.

**Comment by sstone1** [comment]
@mahoney1 @mbwhite is this something you guys can help with?

**Comment by mahoney1** [comment]
hi Sam,
From what I can tell - the Travis deploy_docs.sh script (to build the Jekyll site) at
https://github.com/hyperledger/composer/blob/master/.travis/deploy_docs.sh

relies on your CSS changes (eg. under assets) to be updated on master under jekylldocs at 
https://github.com/hyperledger/composer/tree/master/packages/composer-website/jekylldocs/assets

to build the jekyll output site for unstable (at the time of writing, it was built 1 hour ago, so unstable is definitely being built it would appear).  https://github.com/hyperledger/composer/tree/gh-pages/unstable

So your source CSS changes would go into the master branch (above). 

Hope this helps.

**Comment by sstone1** [comment]
This seems to be working now:

https://hyperledger.github.io/composer/unstable/

```
    <link href="/composer/unstable/assets/css/normalize.css" rel="stylesheet">
    <link href="/composer/unstable/assets/css/new-style.min.css" rel="stylesheet">
    <link href="/composer/unstable/assets/css/grid-layout.min.css" rel="stylesheet">
```
