### ISSUE TITLE
Playground reports that both .cto and .js files are found in the /lib directory

### ISSUE THREAD

**Issue by 14gracel** [hyperledger/composer#757]
In Playground, the the 'Files' section says that all .cto and .js files are found in /lib, but when the network is exported, .cto files are found in /models

## Context
It is misleading to to new users, as they will believe that .cto and .js files belong in the same directory

## Expected Behavior
Models files should say `models/model.cto` rather than `lib/logic.js`

## Actual Behavior
![image](https://cloud.githubusercontent.com/assets/17450713/25435842/5cc3b1f0-2a89-11e7-9b4b-25a7cc5f71bd.png)

## Possible Fix
Change how file locations are reported in Playground

## Steps to Reproduce
1. Import network

## Context
Explaining the structure of a business network

**Comment by dselman** [comment]
Fixed
