### ISSUE TITLE
Breaking change in @ng-bootstrap/ng-bootstrap

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#758]
The playground declares a "Compatible with version" dependency on `@ng-bootstrap/ng-bootstrap` unfortunately the latest version, released on 25th April includes a breaking change:

> ng-bootstrap requires a minimal version of Angular 4.0.3

The playground UI doesn't come up (gets stuck on 'Loading..') with an error in the console:

`Template parse errors: "let-" is only supported on template elements...`

## Possible Fix

A couple of options:

1. Fix the version of `@ng-bootstrap/ng-bootstrap` to 1.0.0-alpha.24 (this works and is what I'm using to keep developing)

2. Update to later version of Angular

**Comment by caroline-church** [comment]
I think we should do option one for this release then, do option 2 after

**Comment by jthub** [comment]
Option 1 delivered in PR #759

**Comment by caroline-church** [comment]
This currently blocked by https://github.com/chymz/ng2-codemirror/issues/14.

**Comment by sstone1** [comment]
Let's get this piece of technical debt closed off.

**Comment by caroline-church** [comment]
updated so closing
