### ISSUE TITLE
Update the Modeling Language documentation to include events

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#763]
All functionality introduced under epic #66 needs to be added to the user documentation.
Need to cover:

- [ ] High level introduction; what is an event, what can they be used for?
- [ ] How to model events using the new modelling language features?
- [ ] How to publish events from a transaction processor function?
- [ ] How to subscribe to events from a client application?

**Comment by EdProsser** [comment]
Ok so: here's the docs plan.

1. Create a new document on publishing events. /business-network/publishing-events.md
2. Update the concept docs in /business-networks/ to reflect the addition of events.
3. Create new doc in Applications about subscribing to events. /applications/subscribing-to-events.md
4. Update modelling language docs.
5. Update Conceptual docs in Introduction etc.

@14gracel @sstone1  This seem good to you?
