### ISSUE TITLE
Doc errors

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#774]
## Context

There are some errors in the tutorial docs

## getting started:

https://fabric-composer.github.io/tutorials/getting-started-playground.html

If everything started OK, you should be able to access Fabric Composer Playground by clicking on this link: http://localhost:8080

That’s not true… It’ll be available at docker-machine-ip:8080

##  Tutorial

https://hyperledger.github.io/composer/tutorials/defining-a-business-network.html

{
  "$class": "org.acme.vehicle.auction.Offer",
  "bidPrice": "1000",
  "listing": "listing_1",
  "member": "alice@biznet.org",
}

Need to remove final comma at end of "member": "alice@biznet.org"

## Managing your Hyperledger Composer Solution

https://hyperledger.github.io/composer/managing/managingindex.html

Typo in hyperlink to Issuing an identity results in 404

**Comment by EdProsser** [comment]
I'll fold these changes into my next PR, ETA: 30 minutes or so?
