### ISSUE TITLE
User receives a success message if they cancel the export

### ISSUE THREAD

**Issue by Tobias-Hunter** [hyperledger/composer#776]
## Context
If a user goes to export a .BNA from within the Playground & they cancel when in their file browser they still receive the success message!

## Expected Behavior
They shouldn't get a success message if they cancel.

## Actual Behavior
They get a success message!

## Possible Fix
Remove success message!

<img width="717" alt="screen shot 2017-04-28 at 10 37 10" src="https://cloud.githubusercontent.com/assets/25635381/25523604/30c4a308-2bff-11e7-82b3-dbbb4f6762d7.png">

**Comment by samjsmith** [comment]
It's worse than that since the success message often appears before the dialog asking you where to export it to.

**Comment by samjsmith** [comment]
I was looking at this last week but never got around to merging it in.  It's behaving like it's fixed now so please @Tobias-Hunter could you check and close if it's not needed any more?

**Comment by Tobias-Hunter** [comment]
@samjsmith is this in unstable or?

**Comment by samjsmith** [comment]
it's in the master branch

**Comment by Tobias-Hunter** [comment]
Yey! However, no feedback is given now... 

Currently:
![pasted image at 2017_05_15 10_32 am](https://cloud.githubusercontent.com/assets/25635381/26051405/fc078e06-3959-11e7-853d-0e25f3295c77.png)
Low-Fi for expected:
![image](https://cloud.githubusercontent.com/assets/25635381/26051759/12733932-395b-11e7-8d6f-efd5ac4612bb.png)
So we give a notification for a successful export! @winslet any input on Hi-Fis? I believe the Hi-Fis for the notifications are done in #894

**Comment by samjsmith** [comment]
it looks like the code is still issuing the notification before the file has been saved for some reason. Could be a missing promise or something, I'll have a look.

**Comment by samjsmith** [comment]
I don't think that we can use the FileSave package that's in there since it doesn't expose an asynchronous interface to do the work so it doesn't tell you when it's done.  
See here https://github.com/eligrey/FileSaver.js
It also locks your browser while you have it open not allowing you to switch tabs which isn't ideal.

**Comment by Tobias-Hunter** [comment]
Ok we shouldn't show a notification unless we would be able to tell if it's been downloaded. I think we can close this issue when we get rid of the blank notification!

**Comment by shachisharma** [comment]
In order to check whether file has been downloaded or not, a check  is required to introduced, pls check the following fix:

exportBNA() {
    return this.clientService.getBusinessNetwork().toArchive().then((exportedData) => {
      if (exportedData !== 0) { //fix of issue #776 
      let file = new File([exportedData],
        this.clientService.getBusinessNetworkName() + '.bna',
        {type: 'application/octet-stream'});
      saveAs(file);
      this.alertService.successStatus$.next(this.clientService.getBusinessNetworkName() + '.bna was exported');
      } // fix of issue #776
    });
  }

**Comment by samjsmith** [comment]
Thanks for the suggestion @shachisharma.  I'm not sure that this code will work though since the exportedData will pretty much always be non-zero and you're left with the same problem with the non-asyn nature of SaveAs as before.
I did try it locally here and didn't get a notification when I said Cancel (or even when I didn't and let it download which is weird).

**Comment by bestbeforetoday** [comment]
I am not seeing this behaviour is 0.12.0 of playground, either in a cloud hosted or local environment, so closing this issue.
