### ISSUE TITLE
Link checking within docs should be automated

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#777]
Related to #449 

Documentation links need to be checked via a tool as part of an automated test. This needs to be part of the test pipe-line so that we can gain confidence in the documentation quality with regards to internal linking.

## Context
Issues are being raised relating to broken links; this can be avoided by incorporating a link checker within the automated tests

## Expected Behavior
If there is a broken link in the documentation, a test will fail

## Actual Behavior
No tests to fail, documents released with unintentional broken links

## Possible Fix
Incorporate a link checker into testing pipeline

**Comment by sstone1** [comment]
@EdProsser can you action this? If not please speak to Mark.

**Comment by EdProsser** [comment]
https://wummel.github.io/linkchecker/ This might be helpful

**Comment by EdProsser** [comment]
@mbwhite and I are working on this one actively. :)

**Comment by mbwhite** [comment]
Started the process of using linkchecker to attempt to find broken links.

Sadly this doesn't seem to work purely on the on-file html files; therefore this script is standing up the jekyll serve process and then run the linkchecker. After it ends it stops the jekyll serve process.

Details are in the log

**Comment by mbwhite** [comment]
The linkchecker is now in place on the docs build;  the whitelist needs some refinement as to much is being checked. 

The JSDocs have been filtered out already - there's a JSDoc bug that means internal auto-generated links are faulty!

**Comment by mbwhite** [comment]
Have updataed the version of Linkchecker to install using python installation. The version installed on the travis build was years out of date. 

Also the following issue has to be worked around https://github.com/wummel/linkchecker/issues/649

**Comment by mbwhite** [comment]
This is now integrated into the docs phase of the build.

```echo Starting linkchecking... ${URL}
Starting linkchecking... http://127.0.0.1:4000/composer/unstable/
linkchecker --ignore-url=jsdoc ${URL} -F text/UTF8/${DIR}/linkresults.txt 
INFO 2017-07-04 09:00:02,130 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
10 threads active,     6 links queued,   20 links in   3 URLs checked, runtime 1 seconds
10 threads active,    57 links queued,  175 links in  17 URLs checked, runtime 6 seconds
10 threads active,   164 links queued,  423 links in  26 URLs checked, runtime 11 seconds
10 threads active,   161 links queued,  816 links in  32 URLs checked, runtime 16 seconds
10 threads active,   141 links queued, 1001 links in  40 URLs checked, runtime 21 seconds
10 threads active,   145 links queued, 1109 links in  56 URLs checked, runtime 26 seconds
10 threads active,   182 links queued, 1544 links in  67 URLs checked, runtime 31 seconds
10 threads active,   190 links queued, 2028 links in  73 URLs checked, runtime 36 seconds
10 threads active,   150 links queued, 2680 links in  84 URLs checked, runtime 41 seconds
10 threads active,    21 links queued, 3085 links in  89 URLs checked, runtime 46 seconds
 9 threads active,     1 link queued, 3520 links in  99 URLs checked, runtime 51 seconds

if [ "$?" != "0" ]; then
	asciify '!!Broken Links!!' -f standard 

  # set the links as being broken.
  # need to ignore the jsdoc somehow for the momeny
fi

# always show the file - includes number of links checked
cat ${DIR}/linkresults.txt
LinkChecker 9.3              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html

Start checking at 2017-07-04 09:00:02+000

Statistics:
Downloaded: 1.18MB.
Content types: 144 image, 2604 text, 14 video, 0 audio, 214 application, 0 mail and 886 other.
URL lengths: min=16, max=134, avg=64.

That's it. 3862 links in 100 URLs checked. 0 warnings found. 0 errors found.
Stopped checking at 2017-07-04 09:00:56+000 (54 seconds)
```
Is the correct output you should see - any broken links will be marked here.
