### ISSUE TITLE
Submit Transaction dropdown repeats first item

### ISSUE THREAD

**Issue by Tobias-Hunter** [hyperledger/composer#778]
## Context
Submit Transaction dialog dropdown menu repeats the first item. (See pictures for reference)

## Expected Behavior
The dropdown shouldn't repeat the first item.

## Actual Behavior
The dropdown repeats the first item.

## Possible Fix
Remove the first item in the dropdown.

<img width="335" alt="screen shot 2017-04-28 at 10 45 13" src="https://cloud.githubusercontent.com/assets/25635381/25523835/1923c872-2c00-11e7-92b4-3ae74575121d.png">
<img width="387" alt="screen shot 2017-04-28 at 10 43 39" src="https://cloud.githubusercontent.com/assets/25635381/25523838/1bdd3ac6-2c00-11e7-8702-23e0e23cc93d.png">

**Comment by caroline-church** [comment]
@Tobias-Hunter I think this is the correct behavior as the one at the top is the one that is selected and the ones below are the ones you can select from. I have created issue #821 to update the styling of the drop downs
