### ISSUE TITLE
prereqs install script needs to be updated for docker install

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#780]
Docker installation process has changed, making a breaking change for Ubuntu 16.10+

Need to edit the installation method to account for this in the prereqs.sh file

## Context
New user should be able to install all prereqs via the provided script if using Ubuntu 16.10

## Expected Behavior
Docker gets installed and script completes

## Actual Behavior
Script fails at docker install

## Possible Fix
Edit install script to account for "docker-ce" install requirement

## Steps to Reproduce
On Ubuntu 16.10 machine, run pre-reqs.sh

## Context
Getting started golden path

## Your Environment

* Operating System and version (desktop or mobile): Ubuntu 16.10

**Comment by bestbeforetoday** [comment]
Let's target the latest release (currently 17.04) rather than 16.10 for a fix.

**Comment by bestbeforetoday** [comment]
It turns out that (today at least) there is no Docker CE build for 17.04. The only supported versions of Ubuntu are 14.04 LTS, 16.04LTS and 16.10. So perhaps a better strategy is to target all current (non-end-of-life) Ubuntu releases, with the exception of 17.04 for now since that isn't supported by Docker CE.

**Comment by bestbeforetoday** [comment]
Fixed by [hyperledger/composer-sample-applications#28](https://github.com/hyperledger/composer-sample-applications/issues/28)

**Comment by nuno-andre** [comment]
Docker supports Ubuntu 17.04 from June (Docker CE 17.06). I've been able to install Hyperledger Composer only by adding `zesty` to `versions` list in `prereqs-ubuntu.sh`.
