### ISSUE TITLE
Port HLF v0.6 runtime to DukTape.

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#784]
Port the javascript engine currently used in the chaincode for hyperledger fabric v0.6 from Otto to DukTape

**Comment by davidkel** [comment]
This isn't going well. Locally I have had one example of a single test failure but the logs didn't show anything. Since then I have been getting SIGSEGVs on a simple call to push a string to the duktape stack. I implemented a workaround (which isn't the right soln and doesn't give an indication into the actual problem) and now the all the tests pass on my machine, but still cannot get a clean build as a single test will fail (but it doesn't break the container so isn't a sigsegv). 
I have upgraded to the latest go-duktape which includes duktape 2.1 but that didn't address the problem. The current Go compiler level used is 1.7.3 so need to check what the hlf v1 containers are using to see if that may be the cause.

**Comment by sstone1** [comment]
Closing as @davidkel is no longer working this.
