### ISSUE TITLE
Tutorial/Getting Started Path Testing

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#791]
We provide/prescribe routes to get started with the Hyperledger Composer within the documentation. This prescribed route takes a user through installation and various tutorials targeting their local machine.

These routes into exploring the offering are clearly very important as they will provide part of the initial user experience. 

At present these entrance points are only tested manually - this should become automated.

## Context
A user wants to investigate the "getting started" aspects of Hyperledger Composer, and follows information/scripts provided within the documentation.

## Expected Behaviour
A user should be able to follow all guides without being blocked by an installation/configuration issue

## Actual Behaviour
Due to being reliant on so many moving parts, it is possible that aspects of the documentation, scripts, or samples, have become out of date and prevent the user from completing the intended path

## Possible Fix

There are a few options here, but wither way we want to test exactly what we advocate to the user and must link the documentation to a system test. We have two base options here, looking at things from the lens of a user, and the other from a "how we generate docs" option.

 - From user perspective: We could would parse target documentation and extract provided user commands, then run them. That way we would be testing exactly the path prescribed to the user and instantly pick up on regressions to the documented path.
 - From a doc generation perspective: We could tag a script file that describes the getting started process, and extract relevant sections into the documentation - this way we extract segments from testable scrips and place them inline with the documentation. We then establish the script files as system test items and enforce that no "free form" commands are added into documentation. It could even be possible to contain the entire documentation within a shell script file, and parse that into a markup file that is generated for a reference within the documentation

## Possible Approach

It is likely that the second option from above is more readily implementable and we can stage this in two separate deliverable items

1. Set up all samples to be run in a shell file, following a travis configuration to build the test system using the pre-reqs script

2. Look into extending the shell scripts to be consumable with the documentation, or at least linking their development

**Comment by nklincoln** [comment]
PR33 in composer-sample-applications enables the Travis build to be based from the ubuntu-prereqs script

**Comment by sstone1** [comment]
@nklincoln can this be closed now you have done the Travis build?

**Comment by nklincoln** [comment]
#2166 will enable coverage of the Playground tutorial
#1708 should give us a CLI tutorial

This leaves:
 - dev tutorial (working/editing files/using query)
 - Angular/Yo generator

**Comment by nklincoln** [comment]
closing this issue as constituent components have been broken into separate issues
