### ISSUE TITLE
Various issues with tutorial for playground

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#803]
The tutorial for playground 
https://hyperledger.github.io/composer/tutorials/getting-started-playground.html
has the following issues
- It talks about support for node 4.6.2 and gives examples but node 4 is now not supported.
- It says to use sudo but you should not be using sudo
- needs some proofreading for text and layout, for example
```
Docker Engine 1.12.3 or greater Test that Docker Engine is installed by running the following command in your terminal or command prompt:
``

**Comment by EdProsser** [comment]
Adding this to _the list_.
