### ISSUE TITLE
Broken link in Playground

### ISSUE THREAD

**Issue by samjsmith** [hyperledger/composer#805]
## Expected Behavior
The link should be valid: https://fabric-composer.github.io/tasks/github-oauth.html

## Actual Behavior
you get redirected here: https://hyperledger.github.io/composer/404.html

## Steps to Reproduce
1. Connect to a playground instance
2. Exceed your API limit with GitHub
3. Observe the error message
4. Click the link provided.

## Context
I was trying to learn how to setup OAuth to avoid the rate limit problem

## Your Environment
* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by samjsmith** [comment]
@EdProsser could you let me know what this link should be please Ed and I can make the code change?

**Comment by EdProsser** [comment]
Should be this: https://hyperledger.github.io/composer/managing/github-oauth.html
