### ISSUE TITLE
Spinning "load" button has a different size when selected.

### ISSUE THREAD

**Issue by winslet** [hyperledger/composer#815]
Button changes in height when selected on load:

**From this:**
![image](https://cloud.githubusercontent.com/assets/13980028/25622477/6c4ba78c-2f4c-11e7-8a25-23ddcd977825.png)

**To this:**
![image](https://cloud.githubusercontent.com/assets/13980028/25622450/5999bdae-2f4c-11e7-9cbb-2339adf0e1ce.png)

It should remain the same height at all times. Looks to be a relatively simple CSS bug.

**Comment by caroline-church** [comment]
This has been fixed already
