### ISSUE TITLE
As a user, I can view, issue, and revoke identities for participants in a business network

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#817]
This work is blocked by:
#920 As a contributor, I need to model core types in a system namespace

Currently, issued identities the identity registry are not exposed to users outside of the `issueIdentity` and `revokeIdentity` API methods in the [client API](https://github.com/hyperledger/composer/blob/master/packages/composer-client/lib/businessnetworkconnection.js#L415). These methods drive [runtime functions](https://github.com/hyperledger/composer/blob/master/packages/composer-runtime/lib/engine.identities.js) that in turn use the [IdentityManager](https://github.com/hyperledger/composer/blob/master/packages/composer-runtime/lib/identitymanager.js#L49) class to manipulate the `$sysidentities` data collection. That data collection uses an internal format - that is, a hardcoded JSON format 😉 

We need to turn the identity registry into a "proper" registry, as per any other asset or participant registry. By doing this, we will be able to support the following features:

- Full CRUD access to identities, allowing client applications (playground!) to view and manage identities in a business network.
- Full access control support for defining who can view, issue, and revoke identities in a business network.

I believe that this work depends on #920 as it will make the implementation much easier and quicker. Instead of trying to parse and expose the internal data format in both the runtime and client APIs, we can use the ability to model core types to model an `Identity` and its relationship to a `Participant`:

```
asset Identity identified by userID {
  o String userID
  o DateTime issued
  --> Participant participant
  --> Boolean activated
  --> Boolean revoked
}
```

All existing runtime and client APIs will be automatically able to handle this. We can then use the existing ACL rules to implement access control:

```
rule Default2 {
    description: "Allow all participants access to revoke identities"
    participant: "composer.Participant"
    operation: DELETE
    resource: "composer.Identity"
    action: ALLOW
}
```

I am also in favour of turning the `issueIdentity` and `revokeIdentity` calls into system transactions (a new concept):

```
transaction IssueIdentity {
  --> Participant participant
  o String userID
}
```

That are implemented using standard JavaScript transaction processor functions:

```
function onIssueIdentity(tx) {
  return getIdentityRegistry()
    .then(function (registry) {
      var newIdentity = factory.newResource(...);
      registry.add(newIdentity);
    });
}
```

... and secured using standard ACL rules:

```
rule Default2 {
    description: "Allow all participants access to issue identities"
    participant: "composer.Participant"
    operation: EXECUTE
    resource: "composer.IssueIdentity"
    action: ALLOW
}
```

... and viewable in the historian via standard historian functionality 😉 

... and finally, we could also easily extend this with events:

```
event IdentityIssued {
  --> Participant participant
  o String userID
}
```

The final piece of the puzzle would be to update [IdentityManager.getParticipant](https://github.com/hyperledger/composer/blob/master/packages/composer-runtime/lib/identitymanager.js#L121) to look in the new identity registry and use the standard registry APIs to find the current participant (based on the incoming certificate). We could even use features such as complex query or links to find the participant, even if the relationship to a participant for an issued identity points to a participant in another business network.

**Comment by markcastle3** [comment]
@sstone1 @dselman could you add some context to what would be required for this epic.

**Comment by sstone1** [comment]
Adding design tag for comments so they dump all of the identity registry designs into this issue 😉

**Comment by EdMoffatt** [comment]
I was just having a look at this one in light of the ID Cards work, and seeing if there was anything we should tweak.  I think this would be a decent set of changes to the existing screen (some of them are as required by ID Cards, some of them are just me having other ideas whilst I had the Sketch file open!):
![image](https://user-images.githubusercontent.com/7454304/27800796-c80af842-6012-11e7-9d28-d7150df95c70.png)

**Comment by EdMoffatt** [comment]
Just spoke to @jdp1g09 about this - for a first go, we're gonna focus on the top section (as I don't think we'll be pulling in the other data from the registry in our first pass) and he's gonna start working on those pieces.

Note to us all: the whole "Founder/Admin/AdminParticipant" thing is gonna be hella-confusing for Joe to work with/around, so we should definitely firm up what we're doing with this!

@sstone1 is a good person to talk to about the runtime component for this, Joe.

There are a couple of other issues that your work should close off in the process by the way:

#1320 (Displaying in the table which can issue new IDs)
#1321 (Confirmation on Removal/Revoke - language to be adapted according to which of those the button actually does!)

**Comment by EdMoffatt** [comment]
Hey @jdp1g09 - I was just thinking, my latest comment on here doesn't really explain how we ended up addressing the issue, by the look of the commits you're doing :)  Could you drop in a comment on what we're actually doing on this one?  (Just so ppl know what to expect when we drop it in!)

**Comment by jdp1g09** [comment]
As an intermittent step towards the final design, which is the modification of the existing "My Wallet" screen - there is now a table beneath the "My Wallet" table which is a list of **_all_** IDs in the identity registry that for the given business network connection, not just the ones in their wallet.

**Comment by caroline-church** [comment]
Closing as we have issues for remaining work
