### ISSUE TITLE
Make dropdowns prettier

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#821]
The current drop downs need better styling. They also need to make sure that the items don't look like they appear twice in the list #778

**Comment by winslet** [comment]
Styling to hopefully match:

![image](https://cloud.githubusercontent.com/assets/13980028/25663483/bb6253de-300f-11e7-9a3f-4efb211472cf.png)

**Comment by winslet** [comment]
I have started to take a look at the CSS for this. Could probably do with a code review before anything goes live 👍

**Comment by winslet** [comment]
Initial PR https://github.com/hyperledger/composer/pull/844 known issue is overflowing text when names are excessively long. Will open another issue about this.
