### ISSUE TITLE
Model files in dependencies not locateable when using `yarn link`

### ISSUE THREAD

**Issue by pospi** [hyperledger/composer#823]
I encountered issues with modules linked for development using Yarn, since yarn places these symlinks in ~/.config/yarn. Minimatch interprets all path wildcards as not matching (see https://github.com/isaacs/minimatch/issues/30) and as a result my builds are failing with `Failed to find a model file` when run in local development.

**Comment by sstone1** [comment]
@pospi now your PR has been merged, can this be closed?

**Comment by pospi** [comment]
For sure! Thanks all (:
