### ISSUE TITLE
Inspect all *.md files for references to incorrect naming

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#835]
Additional md files (readme etc) exist through the project(s) have references to Fabric composer .... these need to be dealt with!
 - [x] Composer (pull request #861)
 - [x] composer-sample-networks (no changes)
 - [x] composer-sample-applications (PR 31 within target repo)
 - [x] composer-sample-applications-hlv1 (PR 19 within hlfv1 repo)
 - [x] composer-tools (PR 14 in tools repo)
 - [x] composer-sample-models
(plugins have own issue raised #730 #731)

**Comment by EdProsser** [comment]
Can you give me some examples? I don't think there are any references left within packages/composer-website.

**Comment by nklincoln** [comment]
@EdProsser - this is not in the website, but in the code base itself (associated ReadMe files etc)

**Comment by nklincoln** [comment]
All file changes complete:
 - [x] Composer (pull request #861)
 - [x] composer-sample-networks (no changes)
 - [x] composer-sample-applications (PR 31 within target repo)
 - [x] composer-sample-applications-hlv1 (PR 19 within hlfv1 repo)
 - [x] composer-tools (PR 14 in tools repo)
 - [x] composer-sample-models
 - (plugins have own issue raised #730 #731)
