### ISSUE TITLE
UI nitpicks - May 2017

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#839]
Tracking of UI nitpicks in May 2017.
New functionality in this month includes:

- Connection profiles
- Identity management

Nitpicks:

- [x] (1) JSON display of resources is indented: **Caroline**

<img width="638" alt="indent" src="https://cloud.githubusercontent.com/assets/7118158/25696401/f781cbac-30ae-11e7-82e5-bb0f563b34df.png">

- [x] (2) Clicking Add to wallet or Issue New Identity opens a dialog. If you hit escape, you get the following error message: **Caroline**

<img width="832" alt="screen shot 2017-05-04 at 09 50 33" src="https://cloud.githubusercontent.com/assets/7118158/25696449/224c2f26-30af-11e7-87a3-8dbceb120e38.png">

- [x] (3) The text on this panel needs to be updated: **Caroline**

<img width="731" alt="screen shot 2017-05-04 at 09 51 01" src="https://cloud.githubusercontent.com/assets/7118158/25696482/3b83f8de-30af-11e7-84be-c48c8001124c.png">

Suggest:

> Or create a connection profile, select your ~Fabric~ Blockchain platform:

Then prefix both v0.6 and v1.0 with Hyperledger Fabric

- [x] (4) Selecting a new identity on the identities page doesn't actually switch identities **James**

- [x] (5) On deletion of a connection profile, the profile disappears from the side profile view list, but the user is not redirected to any remaining profiles (ie the profile that is deleted, remains in the view) **Caroline**

- [x] (6) Updated dropdown style causes text to overflow - Could do with a tweak to stop this from happening: **Caroline**

![image](https://cloud.githubusercontent.com/assets/13980028/25705802/7a69048c-30d6-11e7-812e-3a579055c741.png)

Would be great if there was an opportunity to put an ellipsis in on overflow.

(PR for new dropdown styling: #844 )

- [x] (7) When you create a new connection profile it appears on the right but is not selected on the left **Caroline**

- [x] (8) When viewing the about section of a business network (readme file) you do not need this: 
**Caroline**
![image](https://cloud.githubusercontent.com/assets/13980028/25711659/68e1420e-30e7-11e7-9047-6ac08fa77392.png)
 
It just needs removing from that page. 

- [x] (9) _Connect_ button on _Connect with an Identity_ dialog is enabled even if there or no identities in the wallet to select. **Caroline**

- [x] (10) Change the "Update" button to a "Deploy" button on the Edit screen: **Caroline**
![image](https://cloud.githubusercontent.com/assets/7454304/25714158/fc80eb7a-30ee-11e7-89c5-055f3b99f67a.png)

- [x] (11) "New" identity is not the right term here - we're adding an existing identity to the wallet. "Add identity"? **Caroline**
<img width="827" alt="screen shot 2017-05-04 at 20 00 03" src="https://cloud.githubusercontent.com/assets/7118158/25721001/d4429b46-3106-11e7-9b50-88148debe290.png">

- [x] (12) When you switch to the web profile it uses the internal $default name **Caroline**
<img width="737" alt="screen shot 2017-05-04 at 20 17 25" src="https://cloud.githubusercontent.com/assets/7118158/25721019/e1c197c2-3106-11e7-8a0f-16d6a94ffd83.png">

- [x] (13) If I click edit on a connection profile, and then click cancel, the page reloads? **Caroline**

- [x] (14) Dialog related issues that might be worthy of a separate issue: **Caroline**
1) The initial splash dialog and the "connecting" status dialogs do not work well together:

<img width="978" alt="screen shot 2017-05-04 at 20 29 34" src="https://cloud.githubusercontent.com/assets/7118158/25721446/6a81f0ba-3108-11e7-9a12-6efbf6ff9769.png">

Hi-Fis for that!

![fabric composer playground define 2 copy 90](https://cloud.githubusercontent.com/assets/25635381/25850809/a6a99910-34bb-11e7-96d8-27635e875bbe.png)
![fabric composer playground define 2 copy 95](https://cloud.githubusercontent.com/assets/25635381/25850813/aba4d902-34bb-11e7-82fb-538948541d7c.png)
Marketch File: [839 TMH v0.1.zip](https://github.com/hyperledger/composer/files/986559/839.TMH.v0.1.zip)

2) You have to click through lots of dialogs!

- [x] (15) Participant typeahead on issue identity cuts off text: **James**

![image](https://cloud.githubusercontent.com/assets/3535067/25739556/4a92c050-317a-11e7-8e80-5e1bbff1ccf2.png)

- (16) ~~There's no ability to see what you've typed in the password field.  Something like a little icon you click to show the text would be handy.  One for @winslet to weigh in on :)~~ Moved to #915

- (17) ~~Show success alert after switching identities~~

**Comment by Tobias-Hunter** [comment]
Added Hi-Fis for (14) @caroline-church

**Comment by jt-nti** [comment]
Displaying text in password fields seemed like an enhancement that could do with a bit more discussion so I've moved it to #915

**Comment by jt-nti** [comment]
While showing the new status popups to @winslet we decided that a success alert is probably not required for switching identities, so cancelling item 17

**Comment by caroline-church** [comment]
All nitpicks now done so closing
