### ISSUE TITLE
Revisit Connection Profile Tests

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#841]
Current connection profile tests provide good coverage at the sacrifice of establishing expected test behaviour.

Where possible expected results state-change/return response/actions should be checked to ensure that regressions do not occur. Currently we are only invoking controller functions, and not checking responses.

**Comment by caroline-church** [comment]
@nklincoln can this issue be closed now we have id cards as the connection profile component is completely different

**Comment by nklincoln** [comment]
... yes!
