### ISSUE TITLE
Editor File Test Extensions

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#851]
#658 Calls out the need for unit tests linking the rendering on the UI to the controller. Specifically the correct message (Error/OK) being displayed in UI for CTO, JS, ACL file content types

## Context
We ask contributors to give code that has 100% code coverage and is rigorously tested ... all the base components should have this too!

Additionally 100% code coverage does not guarantee comprehensive testing - since it is not considering the rendered UI nor the resulting UI logic. 

We need additional tests that incorporate testing the "fixture.debugElement" aspects. This is not about using Protractor to verify an end-to-end user experience, but about extending the existing Karma/Jasmine tests to include inspection of the DOM tree for the component under test and ensuring that the typescript logic facilitates the required/desired user intention.

## Expected Behavior
Can verify that information is being rendered correctly and being removed

## Actual Behavior
UI might be broken, and unknown

## Possible Fix
Add tests incorporating UI rendering checks.

**Comment by nklincoln** [comment]
Still requires branch coverage test for readme file

**Comment by caroline-church** [comment]
done so closing
