### ISSUE TITLE
Stack trace trying to delete connection profile

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#856]
This delete button does not work:

<img width="745" alt="screen shot 2017-05-04 at 20 21 10" src="https://cloud.githubusercontent.com/assets/7118158/25721116/3cbcfa40-3107-11e7-8802-74e0c18d61ce.png">

I see the following stack trace in the console:

[Error] EXCEPTION: Invalid argument type to path.join: undefined
	handleError (vendor.e4848d04a3b13649e6d2.bundle.js:1:676516)
	next (vendor.e4848d04a3b13649e6d2.bundle.js:1:422054)
	(anonymous function) (vendor.e4848d04a3b13649e6d2.bundle.js:1:80109)
	__tryOrUnsub (vendor.e4848d04a3b13649e6d2.bundle.js:1:12431)
	next (vendor.e4848d04a3b13649e6d2.bundle.js:1:11765)
	_next (vendor.e4848d04a3b13649e6d2.bundle.js:1:10811)
	next (vendor.e4848d04a3b13649e6d2.bundle.js:1:10483)
	next (vendor.e4848d04a3b13649e6d2.bundle.js:1:46837)
	emit (vendor.e4848d04a3b13649e6d2.bundle.js:1:79883)
	triggerError (vendor.e4848d04a3b13649e6d2.bundle.js:1:318403)
	onHandleError (vendor.e4848d04a3b13649e6d2.bundle.js:1:317993)
	runTask (polyfills.1c7d6519175c13bc016d.bundle.js:1:298697)
	invoke (polyfills.1c7d6519175c13bc016d.bundle.js:1:304040)
[Error] ORIGINAL STACKTRACE:
	handleError (vendor.e4848d04a3b13649e6d2.bundle.js:1:676650)
	next (vendor.e4848d04a3b13649e6d2.bundle.js:1:422054)
	(anonymous function) (vendor.e4848d04a3b13649e6d2.bundle.js:1:80109)
	__tryOrUnsub (vendor.e4848d04a3b13649e6d2.bundle.js:1:12431)
	next (vendor.e4848d04a3b13649e6d2.bundle.js:1:11765)
	_next (vendor.e4848d04a3b13649e6d2.bundle.js:1:10811)
	next (vendor.e4848d04a3b13649e6d2.bundle.js:1:10483)
	next (vendor.e4848d04a3b13649e6d2.bundle.js:1:46837)
	emit (vendor.e4848d04a3b13649e6d2.bundle.js:1:79883)
	triggerError (vendor.e4848d04a3b13649e6d2.bundle.js:1:318403)
	onHandleError (vendor.e4848d04a3b13649e6d2.bundle.js:1:317993)
	runTask (polyfills.1c7d6519175c13bc016d.bundle.js:1:298697)
	invoke (polyfills.1c7d6519175c13bc016d.bundle.js:1:304040)
[Error] resolve@http://localhost:8080/polyfills.1c7d6519175c13bc016d.bundle.js:1:202276
value@http://localhost:8080/main.91a0caa671836ce5093f.bundle.js:1:1342876
deleteProfile@http://localhost:8080/main.91a0caa671836ce5093f.bundle.js:1:498558
handleEvent_35
[native code]
http://localhost:8080/vendor.e4848d04a3b13649e6d2.bundle.js:1:465088
onInvokeTask@http://localhost:8080/vendor.e4848d04a3b13649e6d2.bundle.js:1:317630
runTask@http://localhost:8080/polyfills.1c7d6519175c13bc016d.bundle.js:1:298641
invoke@http://localhost:8080/polyfills.1c7d6519175c13bc016d.bundle.js:1:304039
	handleError (vendor.e4848d04a3b13649e6d2.bundle.js:1:676694)
	next (vendor.e4848d04a3b13649e6d2.bundle.js:1:422054)
	(anonymous function) (vendor.e4848d04a3b13649e6d2.bundle.js:1:80109)
	__tryOrUnsub (vendor.e4848d04a3b13649e6d2.bundle.js:1:12431)
	next (vendor.e4848d04a3b13649e6d2.bundle.js:1:11765)
	_next (vendor.e4848d04a3b13649e6d2.bundle.js:1:10811)
	next (vendor.e4848d04a3b13649e6d2.bundle.js:1:10483)
	next (vendor.e4848d04a3b13649e6d2.bundle.js:1:46837)
	emit (vendor.e4848d04a3b13649e6d2.bundle.js:1:79883)
	triggerError (vendor.e4848d04a3b13649e6d2.bundle.js:1:318403)
	onHandleError (vendor.e4848d04a3b13649e6d2.bundle.js:1:317993)
	runTask (polyfills.1c7d6519175c13bc016d.bundle.js:1:298697)
	invoke (polyfills.1c7d6519175c13bc016d.bundle.js:1:304040)
[Error] TypeError: Invalid argument type to path.join: undefined
	__tryOrUnsub (vendor.e4848d04a3b13649e6d2.bundle.js:1:12484)
	next (vendor.e4848d04a3b13649e6d2.bundle.js:1:11765)
	_next (vendor.e4848d04a3b13649e6d2.bundle.js:1:10811)
	next (vendor.e4848d04a3b13649e6d2.bundle.js:1:10483)
	next (vendor.e4848d04a3b13649e6d2.bundle.js:1:46837)
	emit (vendor.e4848d04a3b13649e6d2.bundle.js:1:79883)
	triggerError (vendor.e4848d04a3b13649e6d2.bundle.js:1:318403)
	onHandleError (vendor.e4848d04a3b13649e6d2.bundle.js:1:317993)
	runTask (polyfills.1c7d6519175c13bc016d.bundle.js:1:298697)
	invoke (polyfills.1c7d6519175c13bc016d.bundle.js:1:304040)

**Comment by caroline-church** [comment]
@sstone1 does this still happen for you on the latest unstable?

**Comment by samjsmith** [comment]
#WorksForMe on the latest code today.

**Comment by nklincoln** [comment]
@sstone1 unable to replicate on local build - are you still seeing this?

**Comment by sstone1** [comment]
Nah.
