### ISSUE TITLE
Correct and enforce playground source code formatting

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#876]
The playground source code seems to be using 2 space indenting, whilst the rest of the Composer source code uses 4 space indenting. We should correct that so we use a single standard everywhere.

It seems that indenting isn't enforced by linting either, for example this is a bit of a mess:

<img width="770" alt="screen shot 2017-05-06 at 18 00 23" src="https://cloud.githubusercontent.com/assets/7118158/25774411/ff8c876e-3285-11e7-915e-95ba32ed008f.png">

The linting for the rest of the Composer code is run automatically as part of the build. It does not seem to be run at all for playground, and when I try to run it locally it doesn't work.

**Comment by sstone1** [comment]
@caroline-church could you find someone to take care of this please? 😄

**Comment by caroline-church** [comment]
done
