### ISSUE TITLE
Ordering of tasks in tutorials a little confusing

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#882]
On the documentation website, the tutorials sections contains Tutorial1 followed by getting started (on CLI and Playgound) instructions (https://hyperledger.github.io/composer/tutorials/tutorialindex.html).

The tutorial seems to follow from these items though ... perhaps it would be better to more the menu ordering such that getting started is before the tutorial, or perhaps break out the getting started guides as a separate LHS menu option entirely? (then ask for contributors to add more tutorials so that the current tutorial isn't lonely)

Amends:
- Coding a business Network Definition seems to be a tutorial as well? Maybe we could link it under the tutorials items? (https://hyperledger.github.io/composer/business-network/getting-started-coding-bnd.html)

**Comment by EdProsser** [comment]
The 'Coding a BND' topic is going to be taken care of during the documentation review. I have plans for that doc.

I'll have a look at the ordering and update this issue.

**Comment by EdProsser** [comment]
I've updated this stuff a little, hesitant to change too much before the new user experience stuff get's going properly, but will commit the stuff I've updated and close this issue when it goes in on Weds.
