### ISSUE TITLE
Playground to display "success" notifications

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#894]
This issue is to add informational alerts of this style:

![image](https://cloud.githubusercontent.com/assets/7454304/25808961/888385c6-3403-11e7-9050-8266d62b4415.png)

![image](https://cloud.githubusercontent.com/assets/7454304/25808968/8d640bb0-3403-11e7-9473-cf5edd6197dc.png)

These should include the ability to set a time after which they self-dismiss, and we should be able to stack up to N of them with the most recent at the top.  Gut feel says N=3.  That's allowing for there to be 2 if we decide to display one when events are emitted by a transaction, and then a +1 just in case there's something I haven't thought of ;)  We should also keep the ability to set the timer to "infinite" if we wish to have something that stays there until the user actively dismisses it!

Now, to try and list all the places we should use this new component styling...

- [ ] After the user hits "Update" (or "Deploy", as a nitpick will soon relabel said button) on the "Edit" tab, and their business network successfully deploys.

- [ ] After switching to another connection profile

- [ ] After successful submission of a Transaction

- NOTE: We're explicitly NOT going to do info alerts on CRUD for Assets and Participants, because the user can see the fact that what they just did worked on the screen already after doing it, so there's no need for the additional feedback.  We *do* have it on Transactions because a transaction can be submitted without being on the Transaction Registry screen

There are probably other ones that we need to cover too, so please add to this list as needed!

**Comment by dselman** [comment]
Show events emitted by the TP functions?

**Comment by caroline-church** [comment]
@EdMoffatt @winslet When there is more than one notification what should it look like? The two examples you have shown are very different sizes how should we deal with that?

**Comment by winslet** [comment]
@caroline-church can they stack vertically please. It would be great if they could fade out after a 3/4 seconds too. Ill look into doing some interaction work here. 👍 

SVG code for the icon:

```
<svg width="19px" height="17px" viewBox="0 0 19 17" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs></defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" stroke-linecap="square" stroke-linejoin="round">
        <polyline id="Path-4" stroke="#3F55AF" stroke-width="2" points="17.1254845 11 1 11 4.95014198 14.950142"></polyline>
        <polyline id="Path-4-Copy" stroke="#3F55AF" stroke-width="2" transform="translate(9.062742, 3.975071) scale(-1, -1) translate(-9.062742, -3.975071) " points="17.1254845 2 1 2 4.95014198 5.95014198"></polyline>
    </g>
</svg> 
```

Should look something like this:

![image](https://cloud.githubusercontent.com/assets/13980028/25939570/40054a6c-362b-11e7-991f-4a041c0d446f.png)


@EdMoffatt has some more thoughts on the wording of some of the notifications. Will post any updates below.

**Comment by winslet** [comment]
@caroline-church by stacking vertically - does this help explain further?

<img width="371" alt="image" src="https://cloud.githubusercontent.com/assets/13980028/25943384/97c03e0e-3637-11e7-83e2-473912eaf7d3.png">

**Comment by caroline-church** [comment]
@winslet yes perfect
