### ISSUE TITLE
As a user, I can reference data stored in another business network

### ISSUE THREAD

**Issue by markcastle3** [hyperledger/composer#898]
We want to give the users of Composer the ability to reference data that is stored in another business network. Ideally we would give the users the ability to reference data stored in other targets, such as other Blockchain platforms or backend systems (IPFS, databases, etc) but this is out of scope for this epic.

Currently in Composer you can model relationships, and then create new relationships. Relationships are URIs now (thanks to recent work from Dan) that give us an easily extendable, very powerful way to reference data elsewhere. For example, today we support the `resource:TYPE#ID` format: `resource:org.acme.sample.SampleParticipant#participantId:1279`.

This could be extended with a registry:
`resource:MyParticipantRegistry/org.acme.sample.SampleParticipant#participantId:1279`

... and it could be extended with a business network name:

`resource:DansBusinessNetwork/EdsParticipantRegistry/org.acme.sample.SampleParticipant#participantId:1279`

... and it could be extended with a connection profile name:

`resource:SimonsBlockchain/DansBusinessNetwork/EdsParticipantRegistry/org.acme.sample.SampleParticipant#participantId:1279`

Hyperledger Fabric v1.0 has read-only support for calling into other chaincodes running in other channels that the peer is a member of. When this support is used, the identity of the caller is propagated to the other chain code.

However, we also need to cope with relationships to data in other Hyperledger Fabric instances, and also stay portable to other Blockchain platforms and backend systems. Therefore, we may want to target a REST API when calling into another business network. That would give us the ability to pretty much reference data anywhere.

We will need to think about how we tell one business network about another business network; where it is (hosts, ports, etc), what credentials to use, etc. The business network will also need to be able to consume the model files from the other business network so it can understand the data on the other side.

Whatever we do, we will need to extend the runtime to be able to resolve these new URI formats and make the necessary calls to the other business network to retrieve the data and pass it back to the user.

Finally, we also need to consider adding support for verifying the data in the other business network. This is usually done by storing a hash (SHA-2) of the data, so we might want to add the ability to store a hash as part of a relationship. The Composer runtime could then automatically validate the hash is a match.

**Comment by sstone1** [comment]
Leaving this one assigned to @dselman as he's currently doing some investigation/prototyping work in this area.

**Comment by dselman** [comment]
On hold.

**Comment by winslet** [comment]
is this related to #697 ? We have placed dependency design into the backlog for the moment.

**Comment by jonathan-yk-tan** [comment]
Seems like querying other chaincodes in the same channel is already available in Fabric v1, https://jira.hyperledger.org/browse/FAB-1788 , is this coming soon?
