### ISSUE TITLE
Documentation Content Review

### ISSUE THREAD

**Issue by EdProsser** [hyperledger/composer#900]
The current documentation is a mishmash of old content and new, with multiple methods of doing the same thing, sitting in a new structure.

## Context

Now that things have calmed down a bit and the new ToC structure is in place, the content needs to follow suit. Currently, each section has an array of topic which may or may not conflict with other content or explain the same thing in a different way. It's time to go through the various docs and straighten the whole mess out.

## Expected Behavior

The docs should represent every facet of a 'golden path' from discovery to implementation and management of a solution, we have probably 90%+ of the content we need, but we do a bad job of delineating the differences between pathways and methods.

## Possible Fix

Going through each of the ToC Headers and looking at what content lives under them and how it can be improved.

**Comment by EdProsser** [comment]
Having added the relevant issues, this epic is pretty large given that I am just one human.

**Comment by sstone1** [comment]
Closing as not actionable, need more humans. Plus split it into issues that are manageable.
