### ISSUE TITLE
Business Networks Content Review

### ISSUE THREAD

**Issue by EdProsser** [hyperledger/composer#901]
Going through all of the content in the business networks section and enhancing it and sorting out duplication.

Currently we have:

- businessnetwork.md <--- conceptual about what a business network is
- businessnetworkdefinition.md <--- conceptual about the implementation in composer
- bnd-define.md <--- half task half concept about using Yoemen to create a business network definition
- bnd-publish.md <--- Sounds like a task, but is really a concept/reference about publishing a BND
- deploybusinessnetwork.md <--- task deploying a BND to a running fabric.. 
- getting-started-coding-bnd.md <--- task creating and deploying a BND/BNA to a running fabric from the command line.
- model-define.md <--- Concept/Ref tells users to use the CTO lang, this is basically a nothing doc.
- model-publish.md <--- Task/Ref, technical spec for defining BND as an NPM module.
- runtime-update.md <--- task/ref, literally 3 lines giving you the composer network update command. 
- testing.md <--- task/reference/concept, I don't even... This doc needs a lot of work, conceptually and in implementation.

**This is too many docs for something relatively simple.**

Will book some meetings to discuss the best way to reduce the number of these docs and lay out what we need in a more clear and concise manner. Updates to follow...

**Comment by sstone1** [comment]
@dselman says you guys will tackle this review and fix activity as part of your weekly get togethers ("docfest").
