### ISSUE TITLE
Introduce Composer ID Cards to handle deployment of multiple business networks to a connection profile

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#902]
The work being undertaken here has changed significantly, so updating the description...
There have been extensive community-call discussions and multiple ideas thrown around on this issue, so the original description was really waaaay off what we're planning to implement at this stage!

# Overview / user experience
This issue will introduce a new "My Wallet" screen to the local version of Composer Playground.  This screen organises a user's ID Cards, grouped by Connection Profile.

Here is a sample `.card` file. Card files are zip archives. Note that the file extension is `.card`:
[dan.card.zip](https://github.com/hyperledger/composer/files/1155872/dan.card.zip)

Users can add and remove cards from this view, including creating them by providing details or importing fully-formed cards.  Each card can then be used to access a specific business network (on a specific connection profile) as a specific ID.  The user can then work with the existing Playground UI, and "log out" back to the My Wallets screen if they wish to connect to something different instead.

The full low-fi designs for this available here:
https://xd.adobe.com/view/94bea677-3235-4103-9cb9-e767e34d8da4/

Latest XD File for said designs is here:
https://ibm.box.com/s/iz9a187j2bvgajvub3z6h8h17sorstsv

The issue will be split down into smaller related chunks for hi-fi and implementation...

# Technical design
## ID card archive file structure
Bold items are mandatory; all others are optional. This structure will dictate the API for the IdCard object representation.

- **connection.json** - _connection profile (Object)_
  - **"name"** - _mandatory to contain the name of the connection profile_
- credentials/ - _credentials used to connect to the business network (Object where keys are filenames and values are file contents as a String)_
  - certificate
  - privateKey
- **metadata.json** - _specific accessor methods_
  - "**userName**" - _name if the identity (String). Unique for a given connection profile and business network_
  - "description" - _free text description of the ID card (String)_
  - "enrollmentSecret" - _enrolment information in place of credentials/ (String)_
  - "businessNetwork" - _name of the business network to which the ID card applies (String). Generally this will be present but may be omitted for system cards._
  - "roles" - _special roles that can be performed by this ID, which include: peerAdmin, channelAdmin, issuer. (Array)_
  - ~"image" - _image filename within card archive_~ (Not MVP)

**Comment by EdMoffatt** [comment]
After much back-and-forth over rough sketches, I think we have something approaching a coherent design for this :)

https://xd.adobe.com/view/514f261a-162c-45ff-b4d5-fa4f6b7eccc4/

The plan is:

- Combine Connection Profile + Business Network + ID into a single link in the header bar
- This takes the user to the Connection Profiles tab
- Non-active Connection profiles look as they did before, except that we recommend moving the "activate" and "export" buttons up above the details based on some recent observations of users interacting with the UI and missing those buttons on the longer Fabric v1 connection profiles.
- The active connection profile will have a "Reconnect to this" button instead of "Connect to this"
- It will also auto-collapse the connection profile config info, and show the list of Business Networks and the ID Wallet
- IDs and Business Networks can be switched between as shown (the layout and swapping mechanism on the 2 is actually different in the mid-fis: we should probably tidy that up with the next fidelity step!)

Next steps: we need hifis for -

1. The bit in the top right, which now tries to list all 3 bits of info and be a single clickable link
2. The Active Connection Profile, which now has the added Business Network List and Wallet to display

**Comment by sstone1** [comment]
@EdMoffatt I very much approve. What does the flow for the "Deploy a new business network" look like?

**Comment by sstone1** [comment]
@EdMoffatt @winslet this is super high up my priority list, can we get the designs closed off this week so we can get some code monkeys to knock it off?

**Comment by EdMoffatt** [comment]
We've had some further discussions around this, which are reflected in this set of mockups.
Here, 3 different ideas are explored (the first of which is the one outlined already in this issue).

Whilst the comments on this issue don't reflect it, I've received lots of feedback from people saying they're not keen on the first option, and hence the other 2 proposals.

Gut feel at the moment is that we most like option 3 (which includes the creation of this "Composer ID" artefact), but need to look at how much work it is!

https://xd.adobe.com/view/6a1b2887-ef12-4c14-ab59-e40673488d86/

**Comment by EdMoffatt** [comment]
Ok, what I think is a working design!  :O

XD Files here: https://ibm.box.com/s/lrck3127unfz2371psevrya8o3b9pegt

View the designs online: https://xd.adobe.com/view/94bea677-3235-4103-9cb9-e767e34d8da4/

Have a tagging, @winslet @caroline-church ;)

**Comment by EdMoffatt** [comment]
Just to make it easier to find the latest low-fi designs for this, I've updated the issue description, and now here they are in this comment too :)

The full low-fi designs for this available here:
https://xd.adobe.com/view/94bea677-3235-4103-9cb9-e767e34d8da4/

Latest XD File for said designs is here:
https://ibm.box.com/s/iz9a187j2bvgajvub3z6h8h17sorstsv

**Comment by EdMoffatt** [comment]
There's been a lot of discussion over on Rocket.Chat about this one, so lets capture it on Git too!  Here's the first pass we're going to implement - obviously we'll come back and iterate, but we needed to firm up what we would deliver first so here goes!

Basically, you're going to have 2 options for accessing a business network using Composer Playground: 

1. Deploy the business network outside of Playground (with the CLI tools), create an ID Card that can access it outside of Playground (again, CLI tools are your friend), then import that ID Card into Playground to access it.

2. Add ID Cards for the IDs required to deploy new business networks to that connection profile (usually a PeerAdmin and an admin ID Card) and Playground will let you try to deploy new business networks too.

Implicit in (2) is the fact that if you are missing either the PeerAdmin or admin card, Playground won't let you try to deploy a new business network (the button will just disable).  Also, we're just going to be looking for cards with those names, nothing more clever than that ;)
The one exception to this is the WebBrowser profile, where no PeerAdmin Card is needed.

A user installing the Local Composer install for the first time will see a WebBrowser section of their wallet, with an admin ID Card that can be used to access the basic-sample-network, and a hlfv1 section with a PeerAdmin ID Card (which cannot be used to connect to a business network) and an admin card which can be used to access the basic-sample-network.

If the user were to then deploy a new business network to either of those connection profiles, a new admin ID Card would appear as a result, with the name of the new business network on it.  (These may be using the same ID, but the user doesn't really see that, they just observe that there is a new card to click in order to access their new business network).

**Comment by EdMoffatt** [comment]
Here's the Rocket.Chat summary instead, in case anyone finds this more digestible than the above ;)

- After running through the single-line install, a user will have WebBrowser and hlfv1 connection profiles sections in My Wallet
- WebBrowser will have an *admin* card in there, which is for the basic-sample-network Business Network
- New Business Networks can be deployed to the WebBrowser profile - this will result in other *admin* cards appearing, but for different Business Networks
- If all the admin cards were to be removed, the user would no longer be able to deploy new business networks via Playground
- (To fix this, they could import or add an admin ID Card)
- hlfv1 will have a PeerAdmin Card (which cannot be used to connect to a business network) and an *admin* card, for the deployed basic-sample-network
- New business networks can be deployed, similar to WebBrowser
- If either the PeerAdmin or all *admin* cards are removed, Deploy new is no longer available.
- So essentially, we need you to have a PeerAdmin AND an admin card to be able to deploy to this connection profile
- In the case of new Fabrics... The user will need to get hold of ID Cards to import into Playground if they want to deploy there. They could either...
- Do the deploy from the command line, create a participant and issue an ID, then turn it into a card. This card can then be imported into Playground, allowing them to access a business network on this new connection profile (but not deploy any new ones from Playground).
-  If they were to then add the admin and PeerAdmin (and potentially ChannelAdmin if those certificates were for separate Fabric IDs in their particular setup) then we'd let them deploy new business networks too.
- To start with, we're planning to just assume that the ID card called admin is the one to use (for Playground). There will probably be some edge cases here, so lets make simplifying assumptions as needed to start, and then figure out what else needs to be supported!

**Comment by harrika1982** [comment]
Question-- is there an architecture diagram that explains how ID cards fit into an overall application and how they would potentially map to the underlying blockchain??
