### ISSUE TITLE
Installing Documentation Review

### ISSUE THREAD

**Issue by EdProsser** [hyperledger/composer#903]
The Installing docs have had some work done, but there's more to do. 

## Context

We don't currently delineate between platforms much in installing, things could be cleared up for a shorter and more directed experience. 

 - createconnectionprofile.md <--- Task, reasonably clear task about creating a connection profile for HL0.6 or HL1.0. Main concern is _should it be in installing?_
- Installingindex.md <--- concept, landing page which sends people off to where they want to be. Alright. Will need updates and improvement as we change the content of installing. 
- manual_prerequisites.md <--- Task, goes through the prereqs for using composer, installing each one manually. Doesn't explain why people might want to do that. This seems mad.
- prerequisites.md <--- Task, same as above, but with automation.
- quickstart.md <--- Task, installing the sample application for 0.6 or 1.0. Maybe more clarity needed but otherwise alright.
- runtime-start.md <--- ???, who even knows. This seems pointless.

Again. Meetings to follow to discuss best way to deal with these docs.

**Comment by sstone1** [comment]
@dselman says you guys will tackle this review and fix activity as part of your weekly get togethers ("docfest").
