### ISSUE TITLE
Applications Documentation Review

### ISSUE THREAD

**Issue by EdProsser** [hyperledger/composer#905]
This is mostly just a framework, I don't expect to get onto this in Playback 5, so will fill in more information when we get round to this.

- genapp.md <--- Task, using Yoeman to generate an angular2 or CLI application. Seems good but needs much reformatting. 
- getting-started-nodejs-app.md <--- Task, seems like an alright topic? needs a lot of simplifying.
- rest-api-server.md <--- Task, setting up a rest server to deal with commands from your application, does this connect to a running fabric?

Again... more to follow...

**Comment by EdMoffatt** [comment]
Looking at the Rest API instructions here: https://hyperledger.github.io/composer/applications/rest-api-server.html

1) I think the other tutorials tell you the command to check which version of a thing you're running?  Suggest we add in "node -v" instruction to check.

2) This is massively missing pre-reqs.  It tells you how to run a script that immediately asks you for things like:
- Fabric Connection Profile Name
- Business Network Identifier
- Fabric username
- Secret
So I'll have had to follow an install instruction that got Fabric running on my local machine as a pre-req.  How do I know what the connection profile name is?  Should I be running this in the same directory as something else?  Do I need my business network as a .bna also in the same directory?  How do I get a username and secret?

There seems to be quite a lot that's not explained here, about how to make the script actually do something useful.  Getting it installed and running is easy, sure :)  But these instructions really only tell a very small amount of the story!

**Comment by sstone1** [comment]
@dselman says you guys will tackle this review and fix activity as part of your weekly get togethers ("docfest").
