### ISSUE TITLE
Integrating Documentation Review

### ISSUE THREAD

**Issue by EdProsser** [hyperledger/composer#906]
Our integrating docs are.... lacking.

There's not much to go through, which may be a blessing in disguise. This one is more about optimising what we have and deciding whether there should be more. Obviously more will come in future, but _for now_.

- integrating-index.md <--- concept, landing page, not much to see here.... _"move along..."_
- getting-started-rest-api.md <--- Task, didn't I just do this in applications? Oh nope I didn't. Needs work to explain the differences.

**Comment by sstone1** [comment]
@dselman says you guys will tackle this review and fix activity as part of your weekly get togethers ("docfest").
