### ISSUE TITLE
Managing Documentation Review

### ISSUE THREAD

**Issue by EdProsser** [hyperledger/composer#907]
Here's a set of documentation which I actually feel does an alright job. It's reasonably clear, all notably different and explicitly detail what the purpose of each topic is. It's not structured perfectly, and there's work here to do, but I anticipate smaller scale changes here than elsewhere.

- current-participant.md <--- Task, as this is implementing access control, an optional part of a business network, should it go under business networks?
- github-oauth.md <--- Task, getting around the rate limit error when the limit is hit, a little technical , but a perfectly fine doc. Needs some style changes.
- identity-issue.md <--- Task, this one and the one below are fine, again, style tweaks needed.   
- identity-revokemd
- managingindex.md <--- concept, it's an index. It's alright.
- participant-add.md <--- Task, how to add a participant using the API or the CLI. 'Tis alright.
- participantsandidentities.md <--- concept, what is a participant and what is an identity. A little wordy, but it's alright.

**Comment by sstone1** [comment]
@dselman says you guys will tackle this review and fix activity as part of your weekly get togethers ("docfest").
