### ISSUE TITLE
Reference Documentation Review

### ISSUE THREAD

**Issue by EdProsser** [hyperledger/composer#909]
Ok. The Big One. 

This section is literally untouched almost since I started on Composer. I've updated the glossary, but the rest is basically marked "here be dragons".

I won't bother listing all the docs for these, but I'd need someone technical to sit down with me and go through each one to provide the technical usefulness rating of each so I can provide the ID/IA glitter and make them fit for purpose.

**Comment by sstone1** [comment]
@dselman says you guys will tackle this review and fix activity as part of your weekly get togethers ("docfest").
