### ISSUE TITLE
Use Bluebird for promises in node.js code

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#910]
bluebird is a high performance drop in replacement promise implementation but the killer feature is the ability to set the environment variable BLUEBIRD_DEBUG=1
This will generate stack traces for problems which also traverse back through the promise caller giving a more complete stack trace rather than stack traces starting at the top of the promise function.

**Comment by sstone1** [comment]
Higher performance is great, and the chained stack traces is nice.
However, my concern is that we should not mandate the use of a certain promise library in consuming Node.js applications, which may already be using another promise library.
To make that possible I think that we'd need to make sure we use only the ES6 promise APIs and we don't use any additional functions that a promise library might add to the Promise class.

Also, chained stack traces are not an alternative to adding good logging 😉

**Comment by dselman** [comment]
Can we close this?

**Comment by sstone1** [comment]
Closing as we're unlikely to get to this any time soon.
