### ISSUE TITLE
Optionally display contents of password fields

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#915]
As a _tbc_, I would like to be able to see the passwords that I type in.

Some dialogs in the playground require passwords to be entered, with no built in ability to see what you've typed in. For example:

![image](https://cloud.githubusercontent.com/assets/3535067/25860468/89c7d3c0-34d9-11e7-94b4-bf75e5ee30e7.png)

In #839 it was suggested that it might be handy to provide something like a little icon you click to show the actual text in password fields.

Hifi from @winslet 

![image](https://cloud.githubusercontent.com/assets/3535067/25860482/90efddc8-34d9-11e7-8d97-669d50ff37c6.png)

**Comment by jt-nti** [comment]
I'd be interested to know more about what problem this is intended to solve. I have seen this sort of feature before, which seems to targeted towards phone or tablet users where there is a higher chance of mashing the keyboard. Do we have lots of phone/tablet users that would find this useful? Do browsers on those devices have enough mitigation built in already, e.g. showing the last character that was entered.

If it is worth adding this feature to the playground, we probably need to make sure the browser isn't going to remember passwords that are typed in when the entry is visible.

**Comment by sstone1** [comment]
@jt-nti it looks like you're arguing with yourself, where did this requirement come from?

**Comment by winslet** [comment]
mainly from myself - my view is that people who are typing long passwords would like to be able to see if they are making mistakes before they click submit. My extended view would be that we should not asterisk out _anything_ and leave it as plain text - viewable all the time.

**Comment by jt-nti** [comment]
Someone else originally raised it on #839. Unfortunately I don't think it's possible to see the edit history of github issue comment updates, so no idea who it was.

I just opened this issue because it wasn't really a UI nitpick. I would personally be tempted to close it :)

**Comment by sstone1** [comment]
ID cards will make this even less of an issue, as nobody should be typing in secrets - so closing.
