### ISSUE TITLE
As a contributor, I need to model core types in a system namespace

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#920]
Here are some issues that provide the background for the work required in this contributor story:

#817 will introduce support for an identity registry, a registry that contains the set of issued/revoked identities within any given business network. This is data that is currently stored in an internal format and not exposed outside of the runtime.

Note that all our client and runtime side registry code currently assumes all data is modelled.

#722 will introduce support for system level access control rules, so business network developers can control who can perform CRUD operations on registries, update the business network definition, issue identities to participants, etc.

Note that we have existing an access control rules language and access controller in the runtime for enforcing access control to assets, participants, transactions, etc.

#488 requests that we stop the user from having to specify the transaction ID in the model. This is something I agree with; we control and generate the transaction IDs. Related to this is the magic timestamp property on a transaction, and automatically generated event IDs.

Something not covered by an issue today is that we have other internal data formats used by the runtime - for example a registry is just a random JSON object: https://github.com/hyperledger/composer/blob/master/packages/composer-runtime/lib/registrymanager.js#L194

We want to keep as much code common as possible - we do not want separate parsers or data formats for system types as opposed to user types. We also want to keep the experience as simple as possible for the user - for example, avoiding different ACL formats between the system level and resource level ACLs.

Therefore I propose that we start modelling core types in a system namespace - the equivalent of `java.lang` but in Composer. This system namespace would be automatically available in all business network definitions - perhaps by always adding it to the `ModelManager` class.

We could then model the following core types, which are the equivalents of `java.lang.Object`:

```
namespace composer

abstract asset Asset {

}

abstract participant Participant {

}

abstract transaction Transaction identified by transactionID {
  o String transactionID
  o DateTime timestamp
}

abstract event Event identified by eventID {
  o String eventID
  --> Transaction transaction
}
```

All other assets, participants, transactions, and events would automatically inherit from these types unless they specified that they extended another type.

This importantly allows us to define relationships in models to any asset, participant, transaction, or event in any business network - this will be particularly useful for the identity registry and system level ACLs, but also in work such as #55, the historian.

We can then start to model other system types:

```
namespace composer

asset Registry identified by registryID {
  o String registryID
}

asset AssetRegistry extends Registry {

}

asset ParticipantRegistry extends Registry {

}

asset TransactionRegistry extends Registry {

}

asset IdentityRegistry extends Registry {

}

asset Identity identified by userID {
  o String userID
  o DateTime issued
  --> Participant participant
  --> Boolean activated
  --> Boolean revoked
}
```

For the identity registry, we now have a registry that looks and feels like any other registry - it uses modelled types.

We can start to build ACLs around these things without changing the ACL language:

```
rule Default {
    description: "Allow all participants access to create asset registries"
    participant: "composer.Participant"
    operation: CREATE
    resource: "composer.AssetRegistry"
    action: ALLOW
}
rule Default2 {
    description: "Allow all participants access to revoke identities"
    participant: "composer.Participant"
    operation: DELETE
    resource: "composer.Identity"
    action: ALLOW
}
```

**Comment by jt-nti** [comment]
Early draft of a system model is available for comments: [system.cto](https://github.com/jt-nti/hyperledger-composer/blob/920-initial-system-model/packages/composer-common/models/system.cto)

**Comment by jt-nti** [comment]
There is currently a restriction on relationships which causes validation errors with the proposed system model: `Relationship transaction must be to an asset or participant`
Should this restriction be relaxed for system models, or for all models?
/cc @sstone1

**Comment by caroline-church** [comment]
I think it should probably only allow system models to have that relationship i'm not sure in what circumstance you would want to allow other models to be able to do it

**Comment by mbwhite** [comment]
Quick update: the scope of this is provide the 4 basic types, Asset, Participant, and Transaction only.

Currently have a good working prototype in a local branch of mine, building on what @jt-nti did.  I'll look to get at least a PR started today for these. 

The next issues are relating to the visitor patterns around the models. And Access Control. And the relationship issue mentioned aboved.

**Comment by sstone1** [comment]
Just to follow on from the comment from @mbwhite, this is the list of the work in my head from the discussion on Friday:

1. Build `composer.cto` with core system types.
2. Implicitly make all asset, participant, transaction, and event types extend the core system types (unless they specify an `extends` clause).
3. Implicitly add core system types to search path so users can reference core system types; for example, I want to add a relationship to any asset type.
4. Ensure that the core system types and a business network definition that uses them can be deployed and used.
5. Determine the versioning story for the core system types.
6. Update visitors to exclude the core system types, including making sure they don't appear in the REST server.
7. Ensure that access control rules can be applied to the core system types; for example, I want to apply a READ rule to all assets.
8. Documentation.
9. Grammar update and breaking changes for the transaction and event ID in the core system types which will break just about every model file out there.

**Comment by mbwhite** [comment]
[  ] List
[] lsiotg

.  [] Build `composer.cto` with core system types.
[]. Implicitly make all asset, participant, transaction, and event types extend the core system types (unless they specify an `extends` clause).
3. Implicitly add core system types to search path so users can reference core system types; for example, I want to add a relationship to any asset type.
4. Ensure that the core system types and a business network definition that uses them can be deployed and used.
5. Determine the versioning story for the core system types.
6. Update visitors to exclude the core system types, including making sure they don't appear in the REST server.
7. Ensure that access control rules can be applied to the core system types; for example, I want to apply a READ rule to all assets.
8. Documentation.
9. Grammar update and breaking changes for the transaction and event ID in the core system types which will break just about every model file out there.

**Comment by mbwhite** [comment]
@EdProsser  I've added a text file with notes on the documentation for this issue - starting point for discussions. 

[systemtypes.txt](https://github.com/hyperledger/composer/files/1100176/systemtypes.txt)

**Comment by mbwhite** [comment]
Migration helper bash script... 

```
echo "\nCTO Files containing \033[1;34m'transaction  xxx  identified by transactionId'\033[0m \n"
find .  -name *.cto | grep -v node_modules > .ctofiles
cat .ctofiles | xargs gawk '                              {fn = FILENAME;count=0}
                                            length(fn)>50 {fn = substr(FILENAME,length(fn)-49,50)} 
         /^.*transaction.*identified by transactionId.*$/ {count++;  printf "%50s (%4d):\t \033[1;34m%s\033[0m  \n", fn, NR, $0 } 
                                                      END { printf "%d files found\n", count}
'
echo "\nCTO Files containing \033[1;34m'event  xxx  identified by eventId'\033[0m \n"
cat .ctofiles | xargs gawk '                              {fn = FILENAME; count=0}
                                            length(fn)>50 {fn = substr(FILENAME,length(fn)-49,50)} 
                     /^.*event.*identified by eventId.*$/ {count++; printf "%50s (%4d):\t \033[1;34m%s\033[0m  \n", fn, NR, $0 } 
                                                      END { printf "%d files found\n", count}
                              '                              

rm -f .ctofiles

```
