### ISSUE TITLE
As a user, I should not have to specify an enrolment secret if I have already enrolled 

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#937]
Currently, all of our interfaces require an enrolment secret argument:

`composer network deploy -a carauction-network.bna -p composer-systests -i admin -s SECRET`
`bizNetworkConnection.connect('composer-systests', 'carauction-network', 'admin', 'SECRET')`

If the user has already enrolled with that ID and an enrolment certificate exists in the wallet, then the enrolment secret is completely ignored - apart from validating that a non-empty string has been specified. This can be easily tested by passing in a random string for the secret and observing that everything still works.

This is very confusing - the presence of the secret in all APIs and CLI commands makes the enrolment secret look like a non-functioning password rather than a one-time secret - so, as a user, I should not have to specify an enrolment ID if I have already enrolled.

We need to make the enrolment secret argument optional in all APIs and CLIs, and only throw an error or prompt for a secret (this is a CLI feature) if the enrolment secret has not been specified **and** there is no certificate in the wallet for the specified user.

We also need to consider the case where there is no enrolment process for the underlying Blockchain platform, for example in Fabric v1.0 you can bring your own certificate authority (CA) and bring your own certificates. This will involve the user providing the certificates and adding them to the wallet, rather than Composer trying to acquire the certificates from somewhere else.

**Comment by davidkel** [comment]
@sstone1 should we move this to P1 for inclusion in the next release ?

**Comment by sstone1** [comment]
Let's not make stuff P1 until we actually plan on doing it - I realise it's important for "v1.0" but we're not planning on doing this any time soon.

**Comment by bestbeforetoday** [comment]
Either needs changing for all applicable command-line commands; or...
If we go native ID Card support in the runtime, new ID Card commands that by their nature will not need these parameters.

**Comment by bestbeforetoday** [comment]
Resolved by stories already delivered under #2172
