### ISSUE TITLE
As a user, I should not need a GitHub ID to import samples in the playground

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#938]
Currently the playground requires that you need a GitHub ID to access samples. The steps are:

1. Click link to authenticate with GitHub
2. Allow the Composer application to access your account.
3. Get redirected back to playground to access samples.

We should remove this requirement as it adds unnecessary steps (getting a GitHub ID, even if I have no intention to use it for working with source code) to using playground. There is no good explanation of "why" that makes sense to a new user trying to learn Composer.

We should be using some kind of cloud based hosting - perhaps GitHub Pages, or S3, or equivalent - to host the built and released output from the `composer-sample-networks` build. Or perhaps we could use `npm` instead?

**Comment by sstone1** [comment]
@EdMoffatt I think we have discussed this before - any comments?

**Comment by EdMoffatt** [comment]
I only add my firm agreement that we should aspire to do away with the need to authenticate to get at the samples if at all possible.

An additional downside to it is that it frequently gets you a second "gotta clear your browser cache" modal if you've used a previous version after you click that link.

**Comment by winslet** [comment]
This will impact the design given on #657 (but not to a point where it will be a blocker) - do we have any timelines on this?

**Comment by sstone1** [comment]
I have written some code that uses `npm-registry-client` to pull BNA files published to npm.
https://github.com/sstone1/composer-sample-downloader

@caroline-church has volunteered at looking to integrate this code into playground.

**Comment by caroline-church** [comment]
done so closing
