### ISSUE TITLE
As a user, I can manage connection profiles using the CLI

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#939]
The CLI currently tries to avoid exposing parts of connection profiles to the user, which feels wrong to me. For example:

- There is a default connection profile name `defaultProfile`:
https://github.com/hyperledger/composer/blob/master/packages/composer-cli/lib/cmds/network/lib/deploy.js#L28
- We automatically create a HLF v0.6 connection profile if one does not already exist:
https://github.com/hyperledger/composer/blob/master/packages/composer-cli/lib/cmds/network/lib/deploy.js#L150
- As a side note, we always recreate the connection profiles even if they exist, which is dumb:
https://github.com/hyperledger/composer/blob/master/packages/composer-cli/lib/cmds/network/lib/deploy.js#L103

The default connection profile name is fine to me. It makes perfect sense that if I'm only ever using one connection profile, I should not have to type that name in for all the commands I issue.

I do have a problem with the hardcoded HLF v0.6 connection profile however. It means that the CLI is tied to a particular Blockchain platform and a particular level of that platform (see #675). The CLI should be completely Blockchain platform independent.

Additionally, the hardcoded profile is tied to the example HLF v0.6 instance **we** create as part of **our** getting started guide and tutorials. The chances of it matching a HLF instance that the end user has themselves created is minimal, especially with the vast configuration available in HLF v1.0.

So, I propose that we clean this up by doing the following:

- Consider changing the name from `defaultProfile` to `default` - the `Profile` suffix seems a bit redundant.
- Remove the hardcoded HLF v0.6 connection profile from all CLI code and any code that attempts to create a connection profile, restoring the CLI to Blockchain platform independence.
- Add two new commands for managing connection profiles - `composer profile export` and `composer profile import` - that make it easier to work with connection profiles from the CLI and automation.
- Update the getting started guide and tutorials to use these new commands for creating connection profiles based on the HLF instances that we stand up.
- Update the documentation to walk users through the process of creating and importing connection profiles for connecting to the HLF instances that they stand up.

**Comment by bestbeforetoday** [comment]
Either:
1. Connection profile-specific commands; or
1. ID Card-specific commands, which include connection profiles in the ID Card and so we do not need to provide explicit management of connection profiles.

**Comment by bestbeforetoday** [comment]
Effectively redundant now that identities and connection details are within business network cards, which have their own CLI management.
