### ISSUE TITLE
As a user, I can import/export identities between all Composer components

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#943]
Currently, Composer identities are stored in a wallet. This is basically a directory on a file system that contains a set of files, in a format determined by the underlying Blockchain platform. Each identity in a wallet contains the enrolment certificate (private and public keys) required to interact with the Blockchain platform, along with some additional meta data.

It is a difficult, manual process to take an identity from one Composer component - for example the playground - and use it with another Composer component - for example the CLI. Currently one must use `docker` commands to find the relevant files in the playground Docker image and extract them onto the machine using the CLI commands.

I propose that we add import/export functionality for identities to Composer to make it easy to move identities between different components. I think that this entails:

- Extending the connector API with `exportIdentity` method that take a user ID and returns a byte array, and a `importIdentity` method that takes a user ID and a byte array. The byte array would be a connector defined format for serialising all of the data required to move the identity (maybe a single JSON file or a zip file).
- Implementing the new connector methods in all relevant connectors, currently Fabric v0.6 and v1.0.
- Documenting how a user can take an identity created using the underlying Blockchain platform tools - as opposed to using Composer - and get it into the right format to import into Composer.
- Extending the CLI with `composer identity export` and `composer identity import` commands for exporting and importing identities from a wallet.
- Extending the playground with UI components that allow a user to export and import identities from the wallet (so adding design tag for comments).
- Extending the REST server to allow a user to export and import identities from the wallet.

Note that this work will be required in order to handle the new requirements around admin user IDs in Fabric v1.0, where you cannot enrol using the admin user ID and must instead provide a certificate.

**Comment by EdMoffatt** [comment]
I *think* this use case should be entirely covered by the designs for ID Cards, under Epic #902 - so I'm going to un-assign Sam and myself, but please shout if I'm missing something that needs looking at separately!

**Comment by sstone1** [comment]
Let's not make stuff P1 until we actually plan on doing it - I realise it's important for "v1.0" but we're not planning on doing this any time soon.

**Comment by bestbeforetoday** [comment]
Required for minimal implementation (no native ID Card support within runtime):
- New AdminConnection API and command-line commands for listIdentities
- Command-line command for exportIdentity

**Comment by mandeepsinghey** [comment]
Have we at least documented the process for 
"Documenting how a user can take an identity created using the underlying Blockchain platform tools - as opposed to using Composer - and get it into the right format to import into Composer."

Any updates?

**Comment by jt-nti** [comment]
@mandeepsinghey there is a _Manually Creating an ID Card_ section in the [ID Cards documentation](https://hyperledger.github.io/composer/playground/id-cards-playground.html) but I'm not sure if there is anything that would help when it comes to getting files out of Docker.

@bestbeforetoday is about to start a piece of work to bring the ID card concept to the command line which should improve things

**Comment by bestbeforetoday** [comment]
This is mostly delivered now. Once #2401 is in to unify the view of stored cards and associated runtime behaviour, it can be closed.

**Comment by bestbeforetoday** [comment]
Resolved by #2401
