### ISSUE TITLE
As a user I have access to a document that explains the Factory

### ISSUE THREAD

**Issue by liam-grace** [hyperledger/composer#944]
Composer makes extensive use of the [Factory](https://hyperledger.github.io/composer/jsdoc/module-composer-runtime.Factory.html) in the transaction processor functions and when using the client api's. 

It would be useful to have a document explaining why we use a factory to create transactions, resources, concepts and events, and when to use each.

**Comment by sstone1** [comment]
As far as I know, nobody is working on this at the moment or planning to work on it, so closing. 
If somebody wishes to work on this in the future, then please reopen this issue or open a new issue.
