### ISSUE TITLE
As a new user, I can install Composer Playground and a Blockchain platform in one command

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#945]
I have delivered a **prototype** of a one line installer command that currently only runs on Mac:

`curl -sSL http://hyperledger.github.io/composer/install-hlfv1.sh | bash`

It should:
1) Download Fabric v1.0 + Composer Playground
2) Start Fabric v1.0
3) Create and join a channel
4) Start Composer Playground which is configured to talk to the running Fabric v1.0
5) Open a browser pointing to Composer Playground

The only requirement I know of on top of a base operating system is Docker.

The source for this installer is here: `https://github.com/hyperledger/composer/tree/master/packages/composer-website/installers/hlfv1`

This needs a lot more work:

- It needs to run on other platforms, such as Linux - @mahoney1 has volunteered to look at this
- It needs to use the common Fabric v1.0 sample server config/scripts being built by @mbwhite 
- It needs to be manageable - after running the installer, there's no way to start/stop/restart the thing
- It needs to be documented
- It logs way too much
- It needs to detect and report back the lack of Docker, or install Docker (using brew?)
- It needs to be built and published in both unstable and release versions

**Comment by mahoney1** [comment]
On bullet 1 - have this running on Linux and will check in the script checks /changes for Playground browser launch on Linux platform.

**Comment by dselman** [comment]
Can we close this and open follow on issues?

**Comment by ljv5555** [comment]
@sstone1  -- thanks for your installer (described in this comment); I can confirm It worked for me on Debian-9 (64-bit): with prereqs installed I ran the following as root: 
```cat install-hlfv1.sh | bash```

---
---
---

```
I have delivered a prototype of a one line installer command that currently only runs on Mac:

curl -sSL http://hyperledger.github.io/composer/install-hlfv1.sh | bash

It should:

    Download Fabric v1.0 + Composer Playground
    Start Fabric v1.0
    Create and join a channel
    Start Composer Playground which is configured to talk to the running Fabric v1.0
    Open a browser pointing to Composer Playground
```

**Comment by hckim16** [comment]
Well, there you go...works perfect. Thank you so much
