### ISSUE TITLE
ACL File validation broken when models with similar namespaces are loaded.

### ISSUE THREAD

**Issue by m-g-k** [hyperledger/composer#946]
When writing the VSCode plugin for ACL validation I noticed that the ACL file would be declared incorrect by the ACLManager incorrectly if there were similar namespaces loaded into the ModelManager.

## Context
For example, taking the car auction example model and acl file, these will validate correctly as expected. However, if you load another model file into the model manager with a namespace the overlaps with the car auction one it will cause the ACl file to be declared invalid. As an example, the car auction uses "org.acme.vechicle.auction" and if the other file has the namespace "org.acme" which overlaps with the start of the car auction one then this error will occur.

## Expected Behavior
Overlapping namespaces should not cause validation failures in the ACL files.

## Actual Behavior
For this rule in the car auction demo:
rule   Auctioneer {
    description: "Allow the auctioneer full access"
    participant: "org.acme.vehicle.auction.Auctioneer"
    operation: ALL
    resource: "org.acme.vehicle.auction"
    action: ALLOW
}

for the resource: "org.acme.vehicle.auction"

then this code in composer-common\lib\acl\modelbinding.js in the validate method()
// assume qualifiedName is ns.class.property
const nsDotClass = ModelUtil.getNamespace(this.qualifiedName);
const ns = ModelUtil.getNamespace(nsDotClass);
const className = ModelUtil.getShortName(nsDotClass);
const propertyName = ModelUtil.getShortName(this.qualifiedName);
const modelFile = mm.getModelFile(ns);

gives the following values in the debugger:
this.qualifiedName == org.acme.auction.vehicle.auction
nsDotClass == org.acme.vehicle
ns == org.acme
className == vehicle
propertyName == auction

And this is the exception which is thrown from line 178
Error: Failed to find class org.acme.vehicle
    at ModelBinding.validate (c:\dev\vscode\hl-composer\myfork\composer-vscode-plugin\client\server\node_modules\composer-common\lib\acl\modelbinding.js:178:23)
    at AclRule.validate (c:\dev\vscode\hl-composer\myfork\composer-vscode-plugin\client\server\node_modules\composer-common\lib\acl\aclrule.js:106:19)
    at AclFile.validate (c:\dev\vscode\hl-composer\myfork\composer-vscode-plugin\client\server\node_modules\composer-common\lib\acl\aclfile.js:106:21)
    at AclManager.setAclFile (c:\dev\vscode\hl-composer\myfork\composer-vscode-plugin\client\server\node_modules\composer-common\lib\aclmanager.js:69:17)
    at validateTextDocument (c:\dev\vscode\hl-composer\myfork\composer-vscode-plugin\client\server\server.js:66:28)
    at documents.onDidChangeContent (c:\dev\vscode\hl-composer\myfork\composer-vscode-plugin\client\server\server.js:37:5)
    at CallbackList.invoke (c:\dev\vscode\hl-composer\myfork\composer-vscode-plugin\client\server\node_modules\vscode-languageserver\node_modules\vscode-jsonrpc\lib\events.js:113:39)
    at Emitter.fire (c:\dev\vscode\hl-composer\myfork\composer-vscode-plugin\client\server\node_modules\vscode-languageserver\node_modules\vscode-jsonrpc\lib\events.js:177:36)
    at __dirname.listen.connection.onDidChangeTextDocument (c:\dev\vscode\hl-composer\myfork\composer-vscode-plugin\client\server\node_modules\vscode-languageserver\lib\main.js:160:46)
    at handleNotification (c:\dev\vscode\hl-composer\myfork\composer-vscode-plugin\client\server\node_modules\vscode-languageserver\node_modules\vscode-jsonrpc\lib\main.js:353:21)

## Possible Fix
The assumption in this code appears incorrect and fixing this should stop this problem:
// assume qualifiedName is ns.class.property
const nsDotClass = ModelUtil.getNamespace(this.qualifiedName);        

## Steps to Reproduce
In code:
Create a ModelManager and an ACL Manager
Load in the car auction model cto file and permissions.acl file. 
The load another file with this contents and reload and validate the ACL file again to see the error:

// define the namespace for this model
namespace org.acme
enum State {
    o CREATED
    o REGISTERED
    o SOLD
}

All three files are attached in the defect.zip file. 

## Existing issues
None

## Context
Hit this whilst writing the acl validation for for the VSCode plugin and it made my life hell :-)

## Your Environment
Latest current, Windows 10

[defect.zip](https://github.com/hyperledger/composer/files/992669/defect.zip)

**Comment by m-g-k** [comment]
FYI, I can also recreate this defect in the Composer Playground.

**Comment by m-g-k** [comment]
Agh - hit the wrong button to close, so reopening :-(

**Comment by m-g-k** [comment]
FYI, I can also recreate this defect in the Composer Playground.

**Comment by jt-nti** [comment]
The problem appears to be that the code is just guessing what the resource and participant are by just removing the last segment each time. The theory is that it's looking for things in this order:
- namespace.class.property
- namespace.class
- namespace

Unfortunately that's too ambiguous and it's tripping up with similar namespaces. It's likely to have other unintended consequences as well, for example adding a `Wow` class to an `org.example` namespace when there's already a `org.example.Wow` namespace.

One possibility is to explicitly specify what the participant and resource are meant to be, which is probably a better idea than an unstable default for ACLs, eg.
- `ns:org.example`
- `class:org.example.Wow`
- `property:org.example.Wow.much`

Any thoughts/comments/suggestions?

**Comment by sstone1** [comment]
Me and @dselman discussed this yesterday.
There's another problem lurking here which is that with property level ACLs, those ACLs could - or rather should - also be applicable to properties which are nested inside concepts, for example:
`org.example.Wow.concept1.concept2.concept3.concept4.much`
At that point there's no way to tell where the namespace, class, or property start or end!
A follow on from that is that property level ACLs are available in the ACL language, but not implemented in the runtime - it's been left out because it's really quite difficult to do properly.

My vote would be to remove property level ACLs from the language until such time that we can implement it in the runtime as well. That would remove some of the probem.

I'd like to propose another option for the namespace vs class problem; we replace the namespace ACLs with wildcards instead. We now permit wildcards in imports, and I think that this actually maps better to what is going on under the covers - you don't get access to the namespace, you get access to all of the types in that namespace.

So instead of:
`resource: "org.acme.vehicle.auction"`

You would have:
`resource: "org.acme.vehicle.auction.*"`

We could also extend this to have multiple level wildcards, e.g.:
`resource: "org.acme.vehicle.auction.**"`

**Comment by markcastle3** [comment]
@jt-nti is this now ready to be closed ?

**Comment by jt-nti** [comment]
Fixed in 0.9.0
