### ISSUE TITLE
HLF 1.0 connection profile key value store directory limitation

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#957]
The current v1.0 Hyperledger Fabric only works if the key value store directory specified in the connection profile is `<home>/.hfc-key-store`

## Context

This appears to be a known/temporary Hyperledger Fabric v1.0 limitation however it's easy to fall over when coming to it from Hyperledger Composer: there's nothing in the documentation and the playground UI gives no clues that a specific value is required

## Expected Behavior

N/A

## Actual Behavior

Error that private key is not available it key value store directory when trying to connect to HLF.

## Possible Fix

It would be good to call out this pitfall somewhere until Hyperledger Fabric works with any key value store directory location, and perhaps add some validation to the playground.

## Steps to Reproduce

1. Create v1.0 connection profile in playground with a key value store directory that is not `<home>/.hfc-key-store`
2. Try to use the profile

**Comment by sstone1** [comment]
@davidkel when the bug is fixed (alpha 2?) then we need to revert these changes.
