### ISSUE TITLE
0.7.1: "composer network ping" does not show the list of participants

### ISSUE THREAD

**Issue by sanjay-saxena** [hyperledger/composer#958]
With `Hyperledger Composer 0.7.1`, using the following command on macOS 10.12.1:

```
$ composer network ping -n todolist-network-hlfv1 -p hlfv1 -i admin -s adminpw
```
results in the following output:

```
The connection to the network was successfully tested: todolist-network-hlfv1
	version: 0.7.1
	participant: <no participant found>

Command succeeded
```

even though the bootstrap transaction successfully created assets and participants. Note that I can use `composer list network ...` command to see the asset registry.

## Expected Behavior
Participants should be shown/displayed.

## Actual Behavior
Participants are not being shown/displayed.

## Your Environment
* Version used: 0.7.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): node v6.10.0
* Operating System and version (desktop or mobile): macOS 10.12.1
* Link to your project:

**Comment by sstone1** [comment]
The `composer network ping` command is not designed to show you the list of participants. It is designed to show you which participant, if any, the specified Blockchain ID is issued to.

We have an issue to add participant registries to the `composer network list` command:
#834 composer network list is not listing participant registry
