### ISSUE TITLE
As a user, I should not have to manually switch connection profiles to try out HLFv1

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#962]
Currently when using the Docker Compose scripts or the single command installer, playground starts up and connects to the web connection profile.

We should configure playground to automatically connect to the HLFv1 connection profile we create via the COMPOSER_CONFIG environment variable.

@caroline-church please can you change the playground code to look for a `defaultConnectionProfile` flag in `config.json`, and if exists use that value instead of `$default`? I can then make the changes to the scripts and installer to set the right value in COMPOSER_CONFIG.

@EdMoffatt FYI, as discussed.

**Comment by EdMoffatt** [comment]
Linking this to 912, as I'd like to be able to look back and see a full list of the things we've improved about the first time experience, and this definitely feels like ticking off one of the pieces of feedback we've received ;)

**Comment by caroline-church** [comment]
@sstone1 Merged in the playground part over to you

**Comment by caroline-church** [comment]
done so closing
