### ISSUE TITLE
As a user, I should be able to use the Identity client APIs

### ISSUE THREAD

**Issue by Jakeeyturner** [hyperledger/composer#971]
The ability to interact with an Identity registry should be exposed in the client APIs. This will be similar to how assets and participants are currently exposed in the composer-common package.
E.g. 'getAllIdentities', 'getIdentity(id)'

- [ ] Identity Registry API is exposed
- [ ] APIs are documented with JSDoc comments
- [ ] Unit tests written

**Comment by sstone1** [comment]
This has been delivered.
