### ISSUE TITLE
As a contributor, I should be able to model an Identity core type

### ISSUE THREAD

**Issue by Jakeeyturner** [hyperledger/composer#974]
Using the runtime changes in #920, I should be able model an identity core type, such as:
```
asset Identity identified by userID {
  o String userID
  o DateTime issued
  --> Participant participant
  --> Boolean activated
  --> Boolean revoked
}
```

- [ ] Should be able to model 'Identity' core type which is detected by the runtime
- [ ] Unit tested (extension of any existing tests)

**Comment by sstone1** [comment]
This has been delivered.
