### ISSUE TITLE
As a user, I should be able to view all business network identities in playground

### ISSUE THREAD

**Issue by Jakeeyturner** [hyperledger/composer#975]
I should be able to view all of the identities belonging to a business network inside of playground. This should be done using the new Identity API's related to issue #971.

- [ ] I should be able to interact with identities in playground using the identity APIs
- [ ] Should be unit tested
- [ ] Should follow designs below

### Navbar dropdown showing Wallet ID's and link to Identity Registry

![fabric composer playground define 2 copy 112](https://cloud.githubusercontent.com/assets/13980028/24305084/a9387d8a-10b3-11e7-8c52-afd068b71cc8.png)

![fabric composer playground define 2 copy 110](https://cloud.githubusercontent.com/assets/13980028/24305074/a0994bc8-10b3-11e7-8f09-749496291e3c.png)

### Identity Registry page

![fabric composer playground define 2 copy 103](https://cloud.githubusercontent.com/assets/13980028/24305112/bb26125a-10b3-11e7-98ae-124624fd20d4.png)

#### Registry page with hover options shown

![fabric composer playground define 2 copy 101](https://cloud.githubusercontent.com/assets/13980028/24305123/ca4659f2-10b3-11e7-96bc-e6df5335c5c0.png)

### Issue new ID flow

_User selects "issue new id" from top right and modal appears_
![fabric composer playground define 2 copy 102](https://cloud.githubusercontent.com/assets/13980028/24305138/d9ef193e-10b3-11e7-96f4-81d8f0cc2586.png)

_They can enter an ID name and then a participant from the dropdown_
![fabric composer playground define 2 copy 104](https://cloud.githubusercontent.com/assets/13980028/24305206/130f166a-10b4-11e7-8109-2ff7e51f2003.png)

_Dropdown is also an autocomplete object similar to that used in Watson Conversation, this screen shows loading of participants on typing_
![fabric composer playground define 2 copy 104](https://cloud.githubusercontent.com/assets/13980028/24305233/27427e24-10b4-11e7-9532-136ba4bddb14.png)

_User selects a participant and continues_
![fabric composer playground define 2 copy 109](https://cloud.githubusercontent.com/assets/13980028/24305306/60eadc5c-10b4-11e7-8ac2-ba13ced4c3cb.png)

_User selects "allow this id to issue new ID's" then clicks next_
![fabric composer playground define 2 copy 105](https://cloud.githubusercontent.com/assets/13980028/24305324/74cc618c-10b4-11e7-99f1-0ea5fd60b9a2.png)

_On the next screen they are presented with the secret to be shown once and a number of options. At this stage if they select "Done" the close icon top right or "Add to my wallet" the modal will close and the ID will appear in the table. The copy icons copy the relevant text to the users clipboard_
![fabric composer playground define 2 copy 106](https://cloud.githubusercontent.com/assets/13980028/24305393/b24e3f26-10b4-11e7-9843-1d29d687b9e6.png)

_User clicks Done and see's the ID appear in the registry_
![fabric composer playground define 2 copy 107](https://cloud.githubusercontent.com/assets/13980028/24305409/c045962e-10b4-11e7-8f02-27a34cf43555.png)

**Marketch**
[Identity_Management_FC_SW_1.zip](https://github.com/fabric-composer/fabric-composer/files/868653/Identity_Management_FC_SW_1.zip)

**Comment by caroline-church** [comment]
closing as this is a duplicate
