### ISSUE TITLE
As a contributor, I should be able to create system transactions

### ISSUE THREAD

**Issue by Jakeeyturner** [hyperledger/composer#976]
I should be able to model system transactions that execute JavaScript processor functions once called.
For example:

```
transaction IssueIdentity {
  --> Participant participant
  o String userID
}
```
Submitting an 'IssueIdentity' transaction should execute the following JavaScript processor function
```
function onIssueIdentity(tx) {
  return getIdentityRegistry()
    .then(function (registry) {
      var newIdentity = factory.newResource(...);
      registry.add(newIdentity);
    });
}
```

- [ ] Should be able to model system transactions
- [ ] Should be able submit system transactions which executes a JavaScript processor function
- [ ] Should be unit tested

**Comment by sstone1** [comment]
This has been delivered.
