### ISSUE TITLE
As a user, I can secure access to resources on a per-property basis

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#983]
Currently, the ACL format allows you to define access control rules that apply to individual properties:

> Resource defines the things that the ACL rule applies to. This can be a property on a class, an entire class or all classes within a namespace. It can also be an instance of a class, or a property on an instance of a class.
> 
> Resource Examples: - Namespace: org.acme - Class in namespace: org.acme.Car - Property on class: org.acme.Car.owner - Instance of a class: org.acme.Car#ABC123 - Property on an instance of a class: org.acme.Car.owner#ABC123

However, this is only implemented in the ACL language. There is no implementation on the runtime for securing access to resources on a per-property basis.

This user story will add support to the runtime for per-property level ACL. It will also need to extend the runtime & client so that a resource can be sent to a client with required properties omitted/obscured (in the case the client does not have access to read those properties).

**Comment by praveencastelino** [comment]
anyone working on this feature? is it considered in future release?

**Comment by vishwakt** [comment]
I would love to work on this issue, any pointers on where to start would be great!

**Comment by mahoney1** [comment]
hi @vishwakt  thanks for your post! You can see the Contributor's [Getting Started ](https://github.com/hyperledger/composer/blob/master/contrib-notes/getting-started.md) guide (off the main [repo](https://github.com/hyperledger/composer) ) for more info on contributing. There is a [chat link ](https://chat.hyperledger.org/channel/composer-contributors) for Composer contributors too (need a Linux Foundation id for that)  to discuss and share ideas FYI. Would be interested to know your outline/high-level approach for tackling the per-attribute/property question. Thanks for getting in touch!
