### ISSUE TITLE
As a user i can query transactions through the REST API

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#990]

**Comment by fenglianxu** [comment]
@caroline-church This is a query story, link this to the epic #543

**Comment by caroline-church** [comment]
SIZING: 1 day

**Comment by mbwhite** [comment]
This has now been integrated within the codebase. 
TXs previously where invoked with a PUT request, issue a GET request on the same transaction gets back all this type of transactions (they are now in their own registry)
