### ISSUE TITLE
As a user, I can use the historian to understand what changes have been made by a transaction

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#991]

**Comment by caroline-church** [comment]
SIZING:  5 days

**Comment by dselman** [comment]
Request for this from StackOverflow:
https://stackoverflow.com/questions/46372302/how-do-i-find-the-history-of-transactions-for-an-asset-in-a-blockchain-implement/46378623#46378623

**Comment by sadonsergey** [comment]
Are there any moves on this task?

**Comment by kletkeman** [comment]
Some queries I would like to be able to do with the historian:

"As a user, I would like to query the historian for all or a date time range of states for a specific asset by its ID"

"As a user, I would like to query the historian for all or a date time range of emitted events from all or selected transactions"

Given that all of this information is or will be available in historian records in Composer, I am really asking to make sure that these queries can be performed using the existing query language, or that augmentations be made to enable these.

**Comment by mahoney1** [comment]
Linking in this issue as its referring to the same thing (query the history of changes to a particular asset in this case) -> https://github.com/hyperledger/composer/issues/2458

**Comment by andyrichardson** [comment]
A proposed solution may be to add metadata injection capabilities at transaction execution. 

In the below example, the _currency_ and _amount_ attributes of a BuyFund transaction could be set at transaction time by the chaincode - this way, even if the fund value changes, the changes to balance can still be determined.

    transaction BuyFund {
      o Double quantity
      --> Fund fund
      --> Wallet wallet
      * o Currency currency   // Metadata
      * o Double value       // Metadata
    }

---

Another approach could be to use an Event / new data type to track metadata like so.

    transaction BuyFund {
      o Double amount
      --> Fund fund
      --> Wallet wallet
    }

    event MoneyMoved {
      --> Currency currency
      o Double amount
      --> Wallet from
      --> Wallet to
    }

The event fired by the chaincode communicates changes made. This currently isn't an effective approach as events cannot be queried.

**Comment by sergey-koba-mobidev** [comment]
+1 to this

**Comment by David-Kim-TPE** [comment]
Please reopen this thread since it isn't resolved.

**Comment by matt-r-bush** [comment]
Please reopen, this isn't resolved.

**Comment by volodyatan** [comment]
Please
