### ISSUE TITLE
As a playground user I can see the history of transactions

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#993]

**Comment by caroline-church** [comment]
SIZING: 5 days

**Comment by EdMoffatt** [comment]
Sizing design work assuming that:
- We set a limit for how many Playground will display
- We also add e.g. pagination
- We adapt the info that is shown on each "tile" such that it features the info we are actually getting back from the "Historian" component
- We do the first 2 bits (limit total and paginate) in such a way that we can then also apply the same behaviour to Assets and Participants (and we should produce designs for those registries too)

**Comment by winslet** [comment]
Content in the historian:

1. Transaction + JSON packet that goes with it (currently displayed)
2. Delta between the assets/participants (what has changed and how it changed)
3. The events a transaction has emitted and their JSON packet.
4. Which participant submitted the transaction.
5. We show all history of all transactions (no limit right now).

What is not in plan
- Viewing the history of an asset or transactions a participant has performed.

**Comment by winslet** [comment]
After discussion with @EdMoffatt we have made a decision (performance pending) that we will display **100** of the most recent transactions on each page. This is until we get more complex queries into the product which can further filter these transactions.

**Comment by winslet** [comment]
Current design specs for reference:

![image](https://cloud.githubusercontent.com/assets/13980028/26195987/689768e0-3bb5-11e7-8836-81880ee04f9b.png)

**Comment by winslet** [comment]
First pass on how a table might work in terms of content:

![image](https://cloud.githubusercontent.com/assets/13980028/26240636/92d0d064-3c79-11e7-89d1-ee2bae8737a4.png)

(Visually this is just to work out how much space we have and what content we might need to display).

**To do:**

- [ ] Confirm the content shown above is what is possible - not sure we have any of this defined yet.
- [ ] Modal with actual JSON data in it showing the diffs. - im not sure we know the shape of this yet, @caroline-church when you have an idea could you put it into here?
- [ ] Maybe a look into how filtering could work at a high level.
- [ ] Potentially looking at a separate tab for this whole experience?
- [ ] How scrolling works on this vs pagination

Assigning @EdMoffatt to have a look at the lo-fi's. 🎉

**Comment by Tobias-Hunter** [comment]
![image](https://cloud.githubusercontent.com/assets/25635381/26450524/ca2466ae-414f-11e7-94e9-3e4ee7d88047.png)
![image](https://cloud.githubusercontent.com/assets/25635381/26450537/d482dfe0-414f-11e7-8eee-026130bc8cb7.png)
After speaking with @caroline-church here is some initial thoughts on how this could work out... 🤔Will be exploring multiple ideas around this in the next few days so any suggestions welcome!

**Comment by Tobias-Hunter** [comment]
How Query, Historian & Pagination will work together in the Playground, as shared on the Community call on the 1st June! 😛 

.XD Clickthrough: https://xd.adobe.com/view/b653fcaa-4e9a-40ad-8edd-96891c2210bb/

**Comment by kletkeman** [comment]
So this **not in plan** item: "Viewing the history of an asset or transactions a participant has performed"

Does this mean that we will not have features like:

- As a user, I can retrieve historical asset states by assetID from timestamp *start* to timestamp *end*
- As a user, I can retrieve all historical asset states for one assetID in order
- As a user, I can connect an historical asset state to a transaction *and vice versa*

... among others of the same ilk ...

**Comment by EdMoffatt** [comment]
Hey @kletkeman - that's a fairly accurate statement!  Although what it really means is that we will not have features like those *yet*.  There is absolutely an intention to include such features in Playground, but the first pass at this functionality will not be that rich.
There will be separate issues to follow up with the additional behaviours accordingly!

**Comment by winslet** [comment]
The table designs for this issue have been centralised into #1015 - there will be further additions onto that issue to track everything in one place.

**Comment by kletkeman** [comment]
@EdMoffatt Can you tell me when we might expect the rich query historian that can view the entire list of history states for an asset or a timestamped range? Also, is the composer historian built on the Fabric historian or the get key history API in the stub? Or is it something that is custom to the composer runtime and its registry concept? Thx.

**Comment by kletkeman** [comment]
Another question: I just realized that the title says "as a playground user" ... hopefully any feature that a playground user can do will be available using the REST server, strongloop API, and possibly the native SDKs.

**Comment by EdMoffatt** [comment]
Hey @kletkeman - thanks for the comments :)

For your first question, I'm gonna defer to either @dselman or @fenglianxu , as they'll do a far better job of explaining how we're implementing Query than I would.  I certainly know that rich query historian will be supported in the composer-cli before it's supported in the Playground UI: we demo'd a first pass at query functionality in this week's community call, but there's still significant ongoing work and a likely breaking change to the behaviour in the next release...  As I say, Dan of Fenglian can better explain more!

On your second question, I've sort of already hinted at the answer, but you're right, any feature available in playground will also be available through the non-Playground methods.  There are other issues open for implementing the core functionality, then we usually raise a separate "as a Playground user" one to cover the front-end work so that we can divide the runtime and front-end work between different developers with different expertise ;)

**Comment by fenglianxu** [comment]
Hey @kletkeman  Thanks for your comments.  
The rich query historian will be supported in the Playground UI but it has to be after the rich query support by the REST layer. 
Right now we are working on Rich query to improve the usability -:)

**Comment by caroline-church** [comment]
done so lcosing

**Comment by Renu353** [comment]
> Current design specs for reference:
> 
> ![image](https://cloud.githubusercontent.com/assets/13980028/26195987/689768e0-3bb5-11e7-8836-81880ee04f9b.png)

how did you get this?
