### ISSUE TITLE
As a user, I can see notifications of published events in the playground

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#998]
We should update the playground so that it subscribes to events and displays them to the user.

**Comment by Tobias-Hunter** [comment]
Initial thoughts on this one @sstone1 

XD. Clickthrough for this:
https://xd.adobe.com/view/e89120cc-6c9d-40f6-9ce5-25bc0f8fb224/

A current presumptions with this is that we cannot link a transaction & an event. Also, when an event is emitted it will only be there for that time period (don't know the term for this 😉 ). Hence the disappearing after so long style behaviour. 

Something that this design doesn't account for is scaleability... I can imagine these notifications may become too cluttered very well & won't work well for this.

**Comment by sstone1** [comment]
@Tobias-Hunter the main problem with that is the lack of information, I can only see the event ID in the clickthrough. Events can be modelled and can have an arbitrary set of properties - we need to show all of those properties.

**Comment by Tobias-Hunter** [comment]
@sstone1 is this something which could potentially live in it's own registry? & with the notifications as an added benefit? Also, are we able to show the user historic events?

**Comment by Tobias-Hunter** [comment]
https://xd.adobe.com/view/e89120cc-6c9d-40f6-9ce5-25bc0f8fb224/
After chatting with @nklincoln, this is where we where I am at with this however we require more information on the Historian stuff so I've picked up #993 in order to understand how the event details & the transaction information work together! 😛

**Comment by dselman** [comment]
Yes, we need a view details on the popup that shows the JSON for the event.

**Comment by 14gracel** [comment]
@Tobias-Hunter @dselman Are we planning to display the event payload in the notification?

**Comment by winslet** [comment]
Hifi's for this flow:

### User submits a transaction and gets the following notification:

![fabric composer playground define 2 copy 114](https://user-images.githubusercontent.com/13980028/27482842-ece14b4e-581a-11e7-91d4-8c59aa10b4f9.png)

### Clicking the link in the notification opens a modal:

![fabric composer playground define 2 copy 119](https://user-images.githubusercontent.com/13980028/27482869-067dfcdc-581b-11e7-9f8d-d7831b30c6a4.png)

### Selecting "events" in the modal shows a second tab with the events collapsed down:

![fabric composer playground define 2 copy 120](https://user-images.githubusercontent.com/13980028/27482890-1c6f97d0-581b-11e7-88a8-38540aaab1b2.png)

_Hover state_
![fabric composer playground define 2 copy 121](https://user-images.githubusercontent.com/13980028/27482915-2760dd20-581b-11e7-9309-9c341ebf0cb7.png)

### Selecting a row in the table expands the event to view the JSON packet:

![fabric composer playground define 2 copy 122](https://user-images.githubusercontent.com/13980028/27483024-996e17ca-581b-11e7-8504-4c826f1e3af4.png)

Marketch:
[Transaction_Events_SW_1.zip](https://github.com/hyperledger/composer/files/1097836/Transaction_Events_SW_1.zip)

New assets:
[Transaction_Assets.zip](https://github.com/hyperledger/composer/files/1097842/Transaction_Assets.zip)

@14gracel let me know if you have any questions 🎉

**Comment by Tobias-Hunter** [comment]
All the above is good! Would use the Transaction Icon for the notification rather than the 🎺 
![image](https://user-images.githubusercontent.com/25635381/27483488-899bdc36-581d-11e7-887f-e340b5383e44.png)
.XD Clickthrough here:
https://xd.adobe.com/view/e89120cc-6c9d-40f6-9ce5-25bc0f8fb224/
